### ISSUE TITLE
Support angular-universal cache priming

### ISSUE THREAD

**Issue by SteveSandersonMS** [aspnet/JavaScriptServices#10]
This captures the HTTP requestes issued during server-side rendering, and packages them with the page so the client-side code doesn't re-issue the same requests.

Currently the implementation in angular-universal itself is incomplete (doesn't support current Angular 2 `http` APIs), so we need to wait for that.

**Comment by andreymir** [comment]
Is it different from `Microsoft.AspNetCore.AngularServices.PrimeCacheHelper.PrimeCache` or `Microsoft.AspNetCore.AngularServices.PrimeCacheHelper.PrimeCache` is incomplete?

**Comment by MarkPieszak** [comment]
It's not completed on the Universal side @andreymir. We have a spec out for it, but it hasn't been fully put together or incorporated just yet.

**Comment by SteveSandersonMS** [comment]
While this may be nice to do one day, there's no ETA for the feature on the Universal side, and very few people have expressed interest in having the feature anyway.

I'll close this. We can always reconsider including it once it does ship in Universal and if people are keen to have some integration with it.
