### ISSUE TITLE
React templates: Move *.css imports into components

### ISSUE THREAD

**Issue by stephtr** [aspnet/JavaScriptServices#1005]
At the moment one (or more) css files in ClientApp/css/ get imported by boot-client.tsx and not in boot-server.tsx.
Wouldn't it be better to import the css files in the corresponding ClientApp/components/ files, such that for example there is a NavMenu.css file which gets imported by NavMenu.tsx?
The only other change necessary would be to add a `{ test: /\.css$/, use: 'ignore-loader' }` to the server bundle's rules.

**Comment by SteveSandersonMS** [comment]
I'm not sure it would necessarily be better - it depends on whether it actually makes things clearer for the developer. Even if we did this, people would also wonder how to add global style files too, so it might increase the concept count in the templates.

If you think it would be substantially better, would you consider sending a speculative PR showing how you think it would be structured? Then we can discuss more concretely whether it's simpler or not. Thanks!
