### ISSUE TITLE
ReactXP/ReSub support/templates

### ISSUE THREAD

**Issue by stephtr** [aspnet/JavaScriptServices#1006]
I know that there are hundreds of frameworks for which templates could be build, however since ReactXP and ReSub are both developed by Microsoft, I wonder if there are any plans to include a template and maybe support for SSR?

**Comment by SteveSandersonMS** [comment]
Interesting thought. At the moment we don't have any specific plans for that. If you want to publish your own template along those lines, we can definitely link to it from the [wiki](https://github.com/aspnet/JavaScriptServices/wiki).
