### ISSUE TITLE
Support for internet explorer in angular 2 template

### ISSUE THREAD

**Issue by MartenOlofsson** [aspnet/JavaScriptServices#1009]
What are the necessary steps required to make the default template work in internet explorer 10?

**Comment by ADefWebserver** [comment]
See: https://github.com/aspnet/JavaScriptServices/pull/952 and: https://github.com/aspnet/JavaScriptServices/pull/953.

**Comment by SteveSandersonMS** [comment]
Thanks for the answer @ADefWebserver
