### ISSUE TITLE
Error fall-back : route '{*clientRoute}' must have a string value or be of a type which implements 'Microsoft.AspNetCore.Routing.IRouteConstraint'.

### ISSUE THREAD

**Issue by zigzag95** [aspnet/JavaScriptServices#101]
Hello,
I get an error when trying to fall-back

**Code**
` app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "default",
                    template: "{controller=Home}/{action=Index}/{id?}");             

                routes.MapSpaFallbackRoute(
                    name: "spa-fallback",
                    defaults: new { controller = "Home", action = "Index" });

            });`

Error
The constraint entry 'clientRoute'  on the route '{*clientRoute}' must have a string value or be of a type which implements 'Microsoft.AspNetCore.Routing.IRouteConstraint'.

**Comment by laskoviymishka** [comment]
Does it reproduce in tempalte? Can you please provide sample repo?

**Comment by zigzag95** [comment]
No it reproduce when starting the server

**Comment by laskoviymishka** [comment]
What do you mean under starting server

**Comment by zigzag95** [comment]
Yep

**Comment by MarkPieszak** [comment]
Andrei, I think the error he's talking about is coming from SpaRouteExtensions maybe? @laskoviymishka 

https://github.com/aspnet/JavaScriptServices/blob/ecada2f1656e6c91722d1c9bc5bb0bebb18957d1/src/Microsoft.AspNetCore.SpaServices/Routing/SpaRouteExtensions.cs#L32-L34

            if (templatePrefix.Contains("?")) {
                // TODO: Consider supporting this. The {*clientRoute} part should be added immediately before the '?'
                throw new ArgumentException("SPA fallback route templates don't support querystrings");
            }

**Comment by laskoviymishka** [comment]
Mark, looks like so.

**Comment by zigzag95** [comment]
I recompile nodeservice and spaservice after adding net451 target framework and now it works.

Thank you
