### ISSUE TITLE
Scaffolding for New Item missing - Angular SPA template

### ISSUE THREAD

**Issue by jsinh** [aspnet/JavaScriptServices#1010]
I am using VS2017 - seems like the only way to create new template (project) for Angular (my case) is from cmd using `dotnet new angular...`

If I am missing something please point through, but meanwhile i managed to use the cmd option to create Angular SPA project.

**Issue**: I do not have a clean way to create angular component which has component HTML and associated (properly grouped in VS solution explorer) - TS (code file) and mapped CSS file.

I have to manually copy three files and edit project settings to make it work, do we have a way / workaround for it?

**Comment by ADefWebserver** [comment]
Use new templates:
https://github.com/madskristensen/SpaTemplatePack

•	Need to upgrade to the latest JavaScriptServices
•	Need to install [VS 2017 Preview](https://www.visualstudio.com/vs/preview/)

**Comment by jsinh** [comment]
@ADefWebserver - Thanks for the response!

Sorry cannot use Preview for VS2017 for current development
Request to @madskristensen - please push a extension version for the same that would support VS 2017 stable versions.

But again, this only supports the creation of new projects, how can I create new item (e.g. Angular 2/4 component - which has html / .ts / .css files showing as linked in solution explorer.

**Comment by ADefWebserver** [comment]
> But again, this only supports the creation of new projects, how can I create new item (e.g. Angular 2/4 component - which has html / .ts / .css files showing as linked in solution explorer.

No way that I know of. However, it may be possible to make T4 templates. [This link](https://github.com/squadwuschel/MvcControllerToProxyGenerator) shows T4 templates for Angular services.

**Comment by SteveSandersonMS** [comment]
We'll be adding VS templates soon. For now, it's command-line only.
