### ISSUE TITLE
Webpack 3.0.0-rc.1 breaks?

### ISSUE THREAD

**Issue by asadsahi** [aspnet/JavaScriptServices#1017]
Not sure if this is webpack related as I cannot find any apparent breaking chnages from version 2.6.1 (which works with javascript services) vs 3.0.0-rc.1 which breaks with following error:

![image](https://user-images.githubusercontent.com/3470892/26876846-d880d9aa-4b7f-11e7-8a1c-6e6344182318.png)

 [This](github.com/asadsahi/AspNetCoreSpa) project can be used to reproduce the problem by upgrading webpack to 3.0.0-rc.1.

**Comment by SteveSandersonMS** [comment]
We don't yet have any attempt to support Webpack 3.0. I'm not sure what the breaking changes in Webpack 3.0 are, or what we need to do to support them.

If you want to figure out what's needed and send a PR that would be excellent. Otherwise it's not currently supported :(

**Comment by asadsahi** [comment]
no problem, thanks @SteveSandersonMS
