### ISSUE TITLE
React with Redux fetch should be in componentDidMount not componentWillMount

### ISSUE THREAD

**Issue by PaulKGray** [aspnet/JavaScriptServices#1022]
Hi

I used the JavaScript template and came up with an issue when copying the pattern that having the fetch call in componentWillMount caused it to call the API multiple times when the logic to check if the parameter has changed has gone.

If the call to fetch is moved to componentDidMount  this means it is only called once. 

Although the weather page is ok its difficult to understand why this is happening when using the supplied redux store pattern.

**Comment by SteveSandersonMS** [comment]
In the FetchData case, it needs to be in `componentWillMount` so that it runs each time the user navigates (e.g., pages back or forth). The action-dispatching logic in the store takes care of not issuing duplicate HTTP requests if there's a request for the same data that's already loaded.

**Comment by PaulKGray** [comment]
I think changing the route actually remounts the component, in which case componentDidMount works fine, and does not need this defensive code.

**Comment by PaulKGray** [comment]
I have just tried changing the fetch page to componentDidMount  and the functionality stays the same.
