### ISSUE TITLE
Failed to start node process on IIS 7.5, Windows 7.

### ISSUE THREAD

**Issue by jeffcj** [aspnet/JavaScriptServices#1026]
Created a new Angular template:

dotnet new angular
dotnet restore
npm install

Published the files to a local IIS site on my Windows 7 machine. The execution of the Node process that pre-renders the content in the default index.html page fails to load. 

IIS Returns: HTTP Error 502.3 - Bad Gateway

Disabling the aspnet-prerender portion of the index view resolves the issue.

This appears to be permissions related. I changed the Application Pool identity to Local System (also tried my domain account) and the app loads normally. 

I followed the exact same steps on my Windows 10 machine and experienced no issues using ApplicationPoolIdentity.

I attempted to grant the ApplicationPoolIdentity permissions to both the node.exe folder and the application folder with no success.  I also tried Everyone/Anonymous Logon/IUSR, etc. 

I'm at a loss as to why this does not work in Win 7 without changing the app pool user.

**Comment by SteveSandersonMS** [comment]
> I'm not aware of any Windows 7 specific problems with code in this repo, and unfortunately am not able to help diagnose general IIS issues.

Sorry, that's an IIS config issue, which unfortunately I'm not able to help with diagnosing. Please see IIS docs. Sorry I can't be more help.
