### ISSUE TITLE
New CSS not being added

### ISSUE THREAD

**Issue by attiqeurrehman** [aspnet/JavaScriptServices#1028]
Hi,

I have created the React with Redux template and added my css files into css folder under ClientApp, along with images and fonts folder and ran the webpack command but it's not adding my files into the dist folder. Following is the structure in my project. 

<img width="233" alt="capture" src="https://user-images.githubusercontent.com/1382615/27011490-ff94041e-4ed5-11e7-9641-4f590928eebd.PNG">

**Note:**
_I haven't made any changes in the code besides just copying the css, images and font files._

**Comment by SteveSandersonMS** [comment]
Just adding CSS files on disk won't cause them to be included in your app. Please see how the existing CSS is included and follow that pattern, or look at Webpack docs for full details.

**Comment by simonob** [comment]
For anyone that stumbles across this and also can't work out how the existing CSS is included per Steve's comment above... 
The webpack.config.vendor.js file contains the list of paths to be included. Add an entry to this list using the bootstrap.css entry as an example and then rerun webpack.

**Note that if using Visual Studio then the webpack.config.vendor.js is hidden within webpack.config.js - took me ages to realise!**
