### ISSUE TITLE
Angular Template - Bootstrap JS not working

### ISSUE THREAD

**Issue by VincentG85** [aspnet/JavaScriptServices#1029]
Hi, 

I created a new app using angular template with the command : 
`dotnet new angular`

The app built without problem, but when I shrink the browser's window, the button revealed to toggle menu display is not functionnal : clicking on it has no effect. 

Please tell me which file content you may need. 

I ran this test because I noticed the exact same behavior on an existing app, which was fully functionnal, after upgrading to Angular 4 template. 

Thanks,

**Comment by VincentG85** [comment]
Browsing repository I found this bug had been commit some days ago.
Any way to check the revision dotnet tooling is relying on ?

**Comment by pavlalexandr** [comment]
Hi @VincentG85 did you find a hotfix for this issue? Faced the same thing...

**Comment by VincentG85** [comment]
Hey @pavlalexandr , browsing comitted revisions I found it's been fixed for next releases adding
import 'bootstrap';
to the begining of boot-client.ts
