### ISSUE TITLE
React with Redux SPA not working published to Azure in VS2017

### ISSUE THREAD

**Issue by attiqeurrehman** [aspnet/JavaScriptServices#1033]
I have created the project based on React with Redux template and I have published it on azure but I am getting the following error:

> An error occurred while starting the application.
> .NET Core X86 v4.1.1.0    |   Microsoft.AspNetCore.Hosting version 1.1.0-rtm-22752    |    Microsoft Windows 6.2.9200 

To get more detail about error I followed this [post](https://stackoverflow.com/questions/41915522/asp-net-core-1-1-runs-fine-locally-but-when-publishing-to-azure-says-an-error-o?noredirect=1&lq=1).  Here is the detail error:

> System.Exception: Call to Node module failed with error: Webpack dev middleware failed because of an error while loading 'aspnet-webpack'. Error was: Error: Cannot find module 'aspnet-webpack'
>     at Function.Module._resolveFilename (module.js:469:15)
>     at Function.Module._load (module.js:417:25)
>     at Module.require (module.js:497:17)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous> (D:\local\Temp\tmp7696.tmp:83:19)
>     at __webpack_require__ (D:\local\Temp\tmp7696.tmp:20:30)
>     at createWebpackDevServer (D:\local\Temp\tmp7696.tmp:62:26)
>     at D:\local\Temp\tmp79A4.tmp:113:19
>     at IncomingMessage.<anonymous> (D:\local\Temp\tmp79A4.tmp:132:38)
>     at emitNone (events.js:86:13)
> Current directory is: D:\home\site\wwwroot
>    at Microsoft.AspNetCore.NodeServices.HostingModels.HttpNodeInstance.<InvokeExportAsync>d__7`1.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.AspNetCore.NodeServices.HostingModels.OutOfProcessNodeInstance.<InvokeExportAsync>d__13`1.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.AspNetCore.NodeServices.NodeServicesImpl.<InvokeExportWithPossibleRetryAsync>d__10`1.MoveNext()

**Comment by SteveSandersonMS** [comment]
Can you please obtain more detailed logs? The info posted above doesn't contain any error information that we could take any action on. Regards

**Comment by attiqeurrehman** [comment]
@SteveSandersonMS I have updated the question with more detail error.
