### ISSUE TITLE
Is "Server-side prerendering" also applied to VueJS template yet?

### ISSUE THREAD

**Issue by Smilefounder** [aspnet/JavaScriptServices#1036]

**Comment by SteveSandersonMS** [comment]
No, but if you have a clean way to do it, we'd definitely be interested in taking a pull request for it.

**Comment by MarkPieszak** [comment]
@SteveSandersonMS I had achieved it before, eventually removed it as most users didn't need SSR.
Still have the code [here ](https://github.com/MarkPieszak/aspnetcore-Vue-starter/tree/91284ba8e2c67d7b2152b58be1efb89d7f7febfe/Client) in git history. Can talk about it next week if you want, wonder if you ran into the same problems with it that I did.

**Comment by liamwang** [comment]
@MarkPieszak Thank you for providing an achieved repo. It worked. But the code is a little out of date with latest SpaServices nuget package.
