### ISSUE TITLE
Upgrading from Angular 2 to Angular 4 "Call to Node module failed with error: Error: Uncaught (in promise):"

### ISSUE THREAD

**Issue by ilMattion** [aspnet/JavaScriptServices#1037]
Hi,
I'm upgrading my current Angular 2 SPA with new yeoman template that use Angular 4.

I've moved all my code but I obtain one cryptic error message on application startup, this is the error message:

`
Call to Node module failed with error: Error: Uncaught (in promise):
Exception: Call to Node module failed with error: Error: Uncaught (in promise): Error
at resolvePromise (C:\Users\utente\Desktop\Progetto.WebApp\ClientApp\dist\vendor.js:83659:31)
at resolvePromise (C:\Users\utente\Desktop\Progetto.WebApp\ClientApp\dist\vendor.js:83630:17)
at C:\Users\utente\Desktop\Progetto.WebApp\ClientApp\dist\vendor.js:83707:17
at ZoneDelegate.module.exports.ZoneDelegate.invokeTask (C:\Users\utente\Desktop\Progetto.WebApp\ClientApp\dist\vendor.js:83316:31)
at Object.onInvokeTask (C:\Users\utente\Desktop\Progetto.WebApp\ClientApp\dist\vendor.js:14877:37)
at ZoneDelegate.module.exports.ZoneDelegate.invokeTask (C:\Users\utente\Desktop\Progetto.WebApp\ClientApp\dist\vendor.js:83315:36)
at Zone.module.exports.Zone.runTask (C:\Users\utente\Desktop\Progetto.WebApp\ClientApp\dist\vendor.js:83083:47)
at drainMicroTaskQueue (C:\Users\utente\Desktop\Progetto.WebApp\ClientApp\dist\vendor.js:83476:35)
at <anonymous>
at process._tickCallback (internal/process/next_tick.js:169:7)`

Any ideas?

**Comment by SteveSandersonMS** [comment]
Sorry, no clues about that. Since the error is happening inside `Zone` you might be better looking at Angular docs or raising the question with that community.

**Comment by MarkPieszak** [comment]
@ilMattion Did you remove all references to the older `angular2-universal` package / `angular2-universal-polyfills` etc as well?

**Comment by ilMattion** [comment]
Hi,
This is my package.json:

"dependencies": {
    "angular/animations": "4.1.2",
    "angular/common": "4.1.2",
    "angular/compiler": "4.1.2",
    "angular/core": "4.1.2",
    "angular/forms": "4.1.2",
    "angular/http": "4.1.2",
    "angular/platform-browser": "4.1.2",
    "angular/platform-browser-dynamic": "4.1.2",
    "angular/platform-server": "4.1.2",
    "angular/router": "4.1.2",
    "types/node": "7.0.18",
    "angular-2-local-storage": "1.0.1",
    "angular2-template-loader": "0.6.2",
    "aspnet-prerendering": "^2.0.5",
    "aspnet-webpack": "^1.0.29",
    "awesome-typescript-loader": "3.1.3",
    "bootstrap": "3.3.7",
    "css": "2.2.1",
    "css-loader": "0.28.4",
    "es6-shim": "0.35.3",
    "event-source-polyfill": "0.0.9",
    "expose-loader": "0.7.3",
    "extract-text-webpack-plugin": "2.1.2",
    "file-loader": "0.11.2",
    "html-loader": "0.4.5",
    "isomorphic-fetch": "2.2.1",
    "jquery": "3.2.1",
    "jslinq": "1.0.21",
    "json-loader": "0.5.4",
    "mydatepicker": "2.0.20",
    "ng2-pagination": "2.0.1",
    "ng2-bs3-modal": "0.10.4",
    "ng2-file-upload": "1.2.1",
    "ng2-toasty": "4.0.3",
    "ng2-typeahead": "1.2.0",
    "ngx-accordion": "0.0.17",
    "ngx-popover": "0.0.16",
    "preboot": "4.5.2",
    "raw-loader": "0.5.1",
    "reflect-metadata": "0.1.10",
    "rxjs": "5.4.1",
    "style-loader": "0.18.2",
    "to-string-loader": "1.1.5",
    "typescript": "2.3.4",
    "typings": "2.1.1",
    "url-loader": "0.5.9",
    "webpack": "2.6.1",
    "webpack-hot-middleware": "2.18.0",
    "webpack-merge": "4.1.0",
    "zone.js": "0.8.12"
  }

**Comment by thecoconutstudio** [comment]
@ilMattion Did you ever solve this issue?
