### ISSUE TITLE
The Node.js process failed to initialize

### ISSUE THREAD

**Issue by attiqeurrehman** [aspnet/JavaScriptServices#1038]
I have published the React with Redux template on Azure but I am getting the following error:

> AggregateException: One or more errors occurred. (The Node.js process failed to initialize: )
> System.Threading.Tasks.Task.ThrowIfExceptional(bool includeTaskCanceledExceptions)
> System.Threading.Tasks.Task.GetResultCore(bool waitCompletionNotification)
> System.Threading.Tasks.Task.get_Result()
> Microsoft.AspNetCore.NodeServices.TaskExtensions+<>c__1.<OrThrowOnCancellation>b__1_0(Task<T> t)
> System.Threading.Tasks.ContinuationResultTaskFromResultTask.InnerInvoke()
> System.Threading.Tasks.Task.Execute()
> System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
> System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> Microsoft.AspNetCore.NodeServices.HostingModels.OutOfProcessNodeInstance+<InvokeExportAsync>d__13.MoveNext()
> System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
> System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> Microsoft.AspNetCore.NodeServices.NodeServicesImpl+<InvokeExportWithPossibleRetryAsync>d__10.MoveNext()

**Comment by SteveSandersonMS** [comment]
Sorry, that doesn't provide enough info to give any suggestions. Can you obtain more detailed logs that show why the Node.js process didn't initalise?

**Comment by SteveSandersonMS** [comment]
BTW the NodeServices code is regarding Node as having not initalised because it's outputting an unexpected line, which appears to be a blank line based on your logs. I don't know why Node is doing that in your case, but maybe something in your code is doing that.

The next version of NodeServices skips that check altogether because it turns out not to be very useful, so this problem should not affect anyone in the future.

**Comment by SteveSandersonMS** [comment]
Closing due to lack of repro info.

I did check just now that a clean new React-Redux app created from these templates deploys and runs correctly on Azure without needing any modifications or special Azure configuration (and it does).
