### ISSUE TITLE
server-side render error when there is no network connection

### ISSUE THREAD

**Issue by Raika** [aspnet/JavaScriptServices#1048]
I create a template with yo generator
and debug it with visual studio and everything work fine.
but when I disable my network and put my laptop in airplane mode and go to `http://localhost:51302/fetchdata` and refresh the page for server render, application throw this error
```
An unhandled exception occurred while processing the request.
Exception: Call to Node module failed with error: Error
at ClientRequest.<anonymous> (C:\Users\raika\Desktop\a\ClientApp\dist\vendor.js:40132:11)
at emitOne (events.js:115:13)
at ClientRequest.emit (events.js:210:7)
at Socket.socketErrorListener (_http_client.js:400:9)
at emitOne (events.js:115:13)
at Socket.emit (events.js:210:7)
at emitErrorNT (internal/streams/destroy.js:62:8)
at _combinedTickCallback (internal/process/next_tick.js:102:11)
at process._tickDomainCallback (internal/process/next_tick.js:198:9)

Microsoft.AspNetCore.NodeServices.HostingModels.HttpNodeInstance+<InvokeExportAsync>d__7.MoveNext()
```
if there is any network connection even unreachable network, page would load fine.
why is this happening? is this happening just for me?

**Comment by SteveSandersonMS** [comment]
I'm afraid this does look specific to your machine. The same doesn't happen when I server-render that page while it's running on `localhost` and the machine is in fligth mode - it works fine for me.

My guess is that it's to do with how your networking is configured. If for some reason your machine is using an external network resource to resolve the `localhost` address, then perhaps that stops the Node process locating it while you're in flight mode.

This is not something we could resolve in this repo, so I'll mark as closed. Hope that's OK!
