### ISSUE TITLE
HMR linting

### ISSUE THREAD

**Issue by chris-brown** [aspnet/JavaScriptServices#1052]
Hey @SteveSandersonMS - how easy would it be to get ES lint errors to display in a similar fashion as the syntax errors do. (in the client overlay).

I appreciate [linting](https://github.com/aspnet/JavaScriptServices/issues/778) isnt something you intend to add to the SPA templates but would appreciate any guidence on how the webpack middleware could be used to assist. 

I have eslint working and running with the appropriate loaders but im struggling to get instant feedback.

Thanks,

**Comment by SteveSandersonMS** [comment]
I'm afraid I don't know about that, and am probably not the best person to ask. This is really a Webpack support question, so that community would be better positioned to give an authoritative answer. Would it be OK to move your question to the Webpack community?
