### ISSUE TITLE
Question : How to do routing ?

### ISSUE THREAD

**Issue by sherry-ummen** [aspnet/JavaScriptServices#1053]
Sorry if this is not the correct way to post a question. I am not sure where I could get some help.

So my question is, how to do the routing if I am using React+Redux SPA. Any guidelines or tutorial please ?

**Comment by SteveSandersonMS** [comment]
The React+Redux SPA template (like all the other SPA templates) already has a routing setup built in. When you click the "counter" or "fetch data" navigation, you'd using the routing configuration that's defined in `/ClientApp/routes.tsx`. If you need more info about how to work with `react-router`, please see the `react-router` docs. Thanks!
