### ISSUE TITLE
Error opening a yeoman generated project in VS2015 Pro

### ISSUE THREAD

**Issue by ronaldnsabiyera** [aspnet/JavaScriptServices#1054]
![image](https://user-images.githubusercontent.com/2325053/27439029-c2da7120-575e-11e7-85fd-b87021984030.png)

**Comment by SteveSandersonMS** [comment]
Sorry, the current templates are for VS2017 only.

If you need to use VS2015, please use a 0.8.x version of `generator-aspnetcore-spa`.
