### ISSUE TITLE
Can't Inject service in angular 2 with ASP Core 1.1

### ISSUE THREAD

**Issue by Ahmad-Magdy** [aspnet/JavaScriptServices#1056]
Hi 
i'm using generator-aspnetcore-spa and i'm trying to inject service into my app in Angular 2
so i added `providers: [ CommService]` in sharedConfig "app.module.shared.ts"
when i'm trying to run the app i got 

> Exception: Call to Node module failed with error: Error: Uncaught (in promise): Error: No provider for CommService!
> Error: No provider for CommService!

i tried  to add the service in providers in boot-server.ts 
and that's what i got 

> Exception: Call to Node module failed with error: Error: Uncaught (in promise): Error: No provider for Http! (CommService -> Http)
> Error: No provider for Http! (CommService -> Http)
> at Error (native)

So where i can import and inject my Services

**Comment by SteveSandersonMS** [comment]
I'm not sure what specifically is wrong with your config, but I just tried adding the following to `app.module.shared.ts`:

```
providers: [
    { provide: 'MY_THING', useValue: { abc: 123 } }
]
```

... and then in one of the component constructors:

```
constructor(@Inject('MY_THING') myThing: any) {
}
```

... and it worked correctly. In both server and client rendering, the configured value was passed to the component constructor.

So I'm not sure what in particular is wrong with your DI config, but could you follow up with the Angular docs for more information about how to configure DI as required? Thanks!

**Comment by Ahmad-Magdy** [comment]
This is my service
```
@Injectable()
export class CommService {

  constructor(private http: Http) { }


  getUserIP() {
    return this.http.get('http://api.ipify.org/?format=json')
      .map(x => x.json());
  }

}
```

Then i inject it in any component like this

```
export class HomeComponent implements OnInit {
    constructor(private service: CommService) { }
}
```

and i added it to app.module.shared.ts
```
export const sharedConfig: NgModule = {
    bootstrap: [ AppComponent ],
    declarations: [
        AppComponent,
        NavMenuComponent,
        CounterComponent,
        FetchDataComponent,
        HomeComponent,
        LoginComponent
    ],
    imports: [
        RouterModule.forRoot([
            { path: '', redirectTo: 'home', pathMatch: 'full' },
            { path: 'home', component: HomeComponent },
            { path: 'counter', component: CounterComponent },
            { path: 'fetch-data', component: FetchDataComponent },
            { path: 'login', component: LoginComponent },
            { path: '**', redirectTo: 'home' }
        ])
    ],
    providers: [CommService]
};
```

then when i run the app i got 

> No provider for CommService! 

but as you see i already injected it.

**Comment by SteveSandersonMS** [comment]
@Ahmad-Magdy Since this is an Angular-specific usage question, could you raise it with the Angular community?

**Comment by Ahmad-Magdy** [comment]
@SteveSandersonMS  Since it's belongs to specific files  structure  that's only exists in aspcore angular app not in normal angular app so this question belong to here, any way i fixed that problem , you should be more patient with issues like this !

**Comment by suisgrand** [comment]
I do have the same issue, generating an asp.net core app using angular from yeoman tools. @SteveSandersonMS is not working. 
@Ahmad-Magdy: how did you fix this problem?

**Comment by Ahmad-Magdy** [comment]
@suisgrand  check this https://github.com/aspnet/JavaScriptServices/issues/1064

**Comment by suisgrand** [comment]
This works like a charm:) Thank you sooo much @Ahmad-Magdy.
