### ISSUE TITLE
Proposal: Add ability to pass @Model to prerendered boot func

### ISSUE THREAD

**Issue by laskoviymishka** [aspnet/JavaScriptServices#107]
It would be nice to see some ability to pass extension model for our prerendered components. It could be very helpfull for some redux/flux apps (we could populate initial state with them). And it could reduce total overhead of loading some info via Http requests.
Proposal api looks pretty simple. In tag helper add populate new attribute:
```
<app asp-prerender-module="ClientApp/boot-server"
     asp-prerender-model="Model"
     asp-prerender-webpack-config="webpack.config.js">Loading...</app>
```

Inside boot func there is new optional parameter, which popuated from `asp-prerender-model` attribute:
```
export interface BootFunc {
  (params: BootFuncParams, model: any): Promise<RenderToStringResult>;
}
```
Such feature would be really good for building some dynamic parts for exist applications (not whole application handled by some JS-framework).

**Comment by SteveSandersonMS** [comment]
We might want to name it something more general that "model", as you could use this to pass arbitrary information, which could include things like authentication status, which component to render, etc. as well as initial data.

Maybe `asp-prerender-data` or `asp-prerender-params` would be a better attribute name.

**Comment by laskoviymishka** [comment]
@SteveSandersonMS MVC usually operate with `Model' verb for passing some information to view. This not real `params` or `data` IMHO.

**Comment by SteveSandersonMS** [comment]
Are you saying that you agree that "params" or "data" are better terms than "model" because they are more general? If you mean something else please clarify.

Of course, "params" or "data" could include some set of "model" values as subproperties, if that's the information you want to pass to the boot function.

**Comment by laskoviymishka** [comment]
No, I stand for separation of concerns. This should stay as model, or maybe data.

**Comment by SteveSandersonMS** [comment]
Having the ability to pass an arbitrary set of properties into the boot function will cover all the requirements we've discussed here. It's up to the developer to assign whatever meaning they want to those properties, and as such they can separate their concerns in any way they want.

**Comment by laskoviymishka** [comment]
Yeah, but it force developer to use low level http context stuff in view layer.

**Comment by laskoviymishka** [comment]
May be it better to give developer an option. 
If they don't wanna use any hooks - okay, use an data or model passing direct to you prerendering. 
If they want to introduce some generic behaivior - okay, use hooks, and populate this context data for every prerender.

Why we should reduce API? Hooks applicable in many scenarios. Especially for enterprise solutions, with all this layers and abstractions. 

Separating this concerns into 2 different API is not break anything, it still could be possible to pass everything in a `Model`, or via `Hook`. This just a good option. Let developer decide what he or she want to use.

**Comment by SteveSandersonMS** [comment]
I've implemented and documented `asp-prerender-data`, and it's now published. To get this feature, make sure you're on `SpaServices` 1.0.0-beta-000005 or later, and that your `aspnet-prerendering` NPM package is on version 1.0.2 or later. There's [a usage example in the docs](https://github.com/aspnet/JavaScriptServices/tree/master/src/Microsoft.AspNetCore.SpaServices#3-supplying-javascript-code-to-perform-prerendering) - see the "Passing data from .NET code into JavaScript code" subheading.

> Why we should reduce API?

Minimising API surface is essential for the long-term health of this - or any other - framework project. Every public API needs ongoing support, and you can never predict in advance what future enhancements would be precluded by decisions made now. As is often said in open source ["No is temporary; yes is forever"](https://twitter.com/solomonstre/status/715277134978113536).

In this particular case, if you do want this global pipeline-hooks type design, you can certainly enable that using `asp-prerender-data`. Just create your own tag helper that wraps `asp-prerender-*`, gets the global context information from wherever you want, and pass it to the `asp-prerender-*` tag helper as `asp-prerender-data`.

Longer term, if we hear requests from many other developers for a built-in implementation of that, we can certainly consider adding one. I just would not want to bake those design decisions into the packages so early on without evidence that a substantial number of developers will want it. We are yet to see how people will use `asp-prerender-data` and what patterns will emerge around it. Hope that's OK!

**Comment by tinchou** [comment]
What is `asp-prerender-export` for?

**Comment by jeinz11** [comment]
Hi i think its a good idea to pass the cookie in the server side rendering, right now my api is secure
so the first request is unauthorized and server side rendering is totally useless for me thanks
