### ISSUE TITLE
Troubleshooting tips: TypeError: func.apply is not a function

### ISSUE THREAD

**Issue by tlycken** [aspnet/JavaScriptServices#1073]
I'm getting a `System.Exception: Call to Node module failed with error: TypeError: func.apply is not a function` when trying to do some simple hello world stuff, and I'm not sure how to troubleshoot. I've tried to follow the guide in the readme and apply it to my application, but without success.

Here's my code:

`serverside-renderer.build.js`, produced by webpack and present in the project root:
```
/* some webpack bootstrapping omitted */
module.exports = function (callback) { // same result with export default
    var result = '<p>hello from node!</p>';

    callback( /*error*/null, result);
};
```

`MyView.cshtml`:
```
@using Microsoft.AspNetCore.NodeServices
@inject INodeServices Node
@await Node.RenderReactApplication() // same result when waiting synchronously with .Result
```

`NodeServicesExtensions.cs`:
```
public static class NodeServicesExtensions
{
    public static async Task<IHtmlContent> RenderReactApplication<T>(this INodeServices services, string path, T model)
    {
        var renderedApp = await services.InvokeAsync<string>("./serverside-renderer.build");
        return new StringHtmlContent(renderedApp);
    }
}
```

Am I missing something trivial here? How do I troubleshoot?

**Comment by tlycken** [comment]
Hm. I tried bypassing webpack, and got it working. 

I've uploaded the contents of the javascript files to [this gist](https://gist.github.com/tlycken/4eebcfda6aff5e1ed4d65c108c8ab2f3); with both those files in the root of the project, this works:

```
services.InvokeAsync<string>("./serverside-renderer");
```

but this doesn't:

```
services.InvokeAsync<string>("./serverside-renderer.build.js");
```

What's wrong with my module?

**Comment by SteveSandersonMS** [comment]
Your Webpack-emitted file doesn't set any global exports. Your webpack config is not what you need for building Node-compatible modules. Make sure your `webpack.config.js` is configured with `output: { libraryTarget: 'commonjs' }`. For more info on using Webpack to build Node-compatible modules, please see Webpack docs.

**Comment by tlycken** [comment]
Thanks for getting back! I'm quite new in the web world, and quite unfamiliar with all the tooling options.

For future reference, I needed to make the following changes to make this work:

* `libraryTarget: 'commonjs'` in the webpack config
* make a named export, with `export function bootstrapServer(callback) { ... }`.
* adjust the call to `nodeServices.InvokeAsync<string>("./thebundle.js", "bootstrapServer")`

**Comment by DamianMullins** [comment]
@tlycken You wouldn't happen to have a copy of your `webpack.config,js` laying around still would you?

**Comment by DamianMullins** [comment]
@tlycken Actually, don't worry, I noticed that in your last comment you should be calling `nodeServices.InvokeExportAsync` rather than `nodeServices.InvokeAsync` :relaxed:

**Comment by tlycken** [comment]
Good call; turns out that's what I'm actually doing in my code 🙈 

Updated the comment to reflect that, in case someone else comes along here.

**Comment by dazinator** [comment]
You also get this error if you use a named export like this:

```
module.exports = {   
    build: function (callback, requestDto) {

```

But then forget to specify the name when invoking, i.e if you accidentally do this:

```
nodeServices.InvokeAsync<string>("./thebundle.js", options)
```

instead of this:
```
nodeServices.InvokeAsync<string>("./thebundle.js", "build", options)
``
