### ISSUE TITLE
Using AntiForgeryToken on React/Redux Server Side Rendering

### ISSUE THREAD

**Issue by JoshClose** [aspnet/JavaScriptServices#1074]
I need to use the AntiForgeryToken for form submits. What I do on the client is generate a js variable like this
```
window.aft = '@Html.AntiForgeryToken()';
```
I can then do this in pages where I need it.
```
<div dangerouslySetInnerHTML={{ __html: global.aft }}></div>
```
When doing server side rendering this isn't possible.

How do you recommend doing this?

My only guess is to use `asp-prerender-data`. Is there a better way?

**Comment by SteveSandersonMS** [comment]
Using `asp-prerender-data` is the correct way to flow arbitrary info from your .NET code into your Node-side SPA code during prerendering, so I think you're already on the correct lines.
