### ISSUE TITLE
Passing AppSettings.Json to Angular

### ISSUE THREAD

**Issue by redowl3** [aspnet/JavaScriptServices#1075]
Not so much an issue but does anyone have a suggestion on how to pass values from appsettings in ASP.NET to an Angular service for example?  I'm looking to hit a number of different services but want to change the url based on development environment.

**Comment by shwedberlin** [comment]
Hi, please take a look at my example: https://github.com/shwedberlin/AngularWebApi
There I read some configurations from server (.json) BEFORE angular app appears in browser.

**Comment by redowl3** [comment]
Hi, thanks for the response, I'll take a look - much appreciated.

**Comment by jrmcdona** [comment]
@shwedberlin can you point me to the files in your example that shows where you read the config in ,NET then pass that value back over to the angular app?  I am not seeing it right away.   Thanks
