### ISSUE TITLE
'Iconv is not a constructor' during app warmup

### ISSUE THREAD

**Issue by jwhitex** [aspnet/JavaScriptServices#1077]
We recently deployed our app to a production environment and received the below error. It is followed by a 'FetchFailed' due to inability to parse json.  We suspect the later error is a result of the first.

```
TypeError: Iconv is not a constructor at convertIconv (...\ClientApp\dist\vendor.js:22203:13) 
at convert (...\ClientApp\dist\vendor.js:22166:22) 
at Body.module.exports.Body._convert (...\ClientApp\dist\vendor.js:8573:9) 
at PassThrough.<anonymous> (...\ClientApp\dist\vendor.js:8500:17) 
at emitNone (events.js:91:20) at PassThrough.emit (events.js:185:7) at endReadableNT (_stream_readable.js:974:12) 
at _combinedTickCallback (internal/process/next_tick.js:80:11) at process._tickDomainCallback (internal/process/next_tick.js:128:9)
```

*The fetch which throws the second exception:*

```
export const actionCreators = {
    requestStartupData: (): AppThunkAction<KnownAction> => (dispatch, getState) => {
        let fetchTask = fetch('/api/initialConfig')
            .then(response => response.json() as Promise<HelperTypes.IValidationResult<StartupData>>)
            .then(response => {
                dispatch({ type: 'RECEIVE_STARTUP_DATA', startupData: response.data });
            });
        addTask(fetchTask);
        dispatch({ type: 'REQUEST_STARTUP_DATA' });
    },

```

The below code produced in vendor.js shows ``Iconv`` being set with by a require of module 344. As noted by ``vendor-manifest.json``, Module 344 is 'node-noop'

```
	var iconvLite = __webpack_require__(240);
	// Load Iconv from an external file to be able to disable Iconv for webpack
	// Add /\/iconv-loader$/ to webpack.IgnorePlugin to ignore it
	var Iconv = __webpack_require__(344);
	
	....

    } else if (Iconv && !useLite) {
	try {
		result = convertIconv(str, to, from);  // this call throws exception
        } catch (E) {
            console.error(E);
            try {
                result = convertIconvLite(str, to, from);
            } catch (E) {
                console.error(E);
                result = str;
            }
        }
```

Below shows the vendor webpack config where ``node-noop`` replaces ``iconv-loader`` per your comment.

```
	
	//webpack.config.vendor.js
	
	    plugins: [
            new webpack.NormalModuleReplacementPlugin(/\/iconv-loader$/, require.resolve('node-noop')),  // Workaround for https://github.com/andris9/encoding/issues/16
            new webpack.DefinePlugin({
                'process.env.NODE_ENV': isDevBuild ? '"development"' : '"production"'
            })
        ]

```

This appears to be a misuse of 'node-noop' but I'm curious since everyone on the linked thread seems satisfied with this workaround.

Node         v6.11.0
SpaServices  v1.1.1
DOTNETCORE_ENVIRONMENT=Production

For now we have deployed without serverside rending. Major bummer!

**Comment by SteveSandersonMS** [comment]
Could you tell us what code you've added that causes `Iconv` to be needed at runtime in your server-side prerendering code path? It's not needed by default (hence others not getting this issue).

I'd like to know what a minimal repro would be so we can figure out whether a different workaround is needed.

**Comment by jwhitex** [comment]
We are redering a google recaptcha during our first render dependent on answers from the fetch shown above. 

To replicate, install npm package `react-google-recaptcha`

put recaptcha on the page
```
          <ReCAPTCHA
                ref="recaptcha"
                sitekey="6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI" />
```
This is a public sitekey.

**Comment by SteveSandersonMS** [comment]
Thanks for letting me know!

I'm not sure that `iconv` can actually be used during server-side prerendering, since AFAIK it's not compatible with building via Webpack to a Node-compatible bundle, hence the `node-noop` workaround that we and everyone else have to use. If it can't be used during server-side prerendering, you'll need to add some logic to your code to ensure that `react-google-recaptcha` doesn't get called when the code is running inside Node.

On the other hand, if you can find some way to make `iconv` build properly through Webpack without the `node-noop` workaround, please let us know!

I'll close this as an external issue with `iconv`. But like I said, if anyone can describe a better workaround or fix than the one we're already using, we'll definitely change to do that. Hope that's OK!
