### ISSUE TITLE
Error on fetch for url.js 

### ISSUE THREAD

**Issue by Flood** [aspnet/JavaScriptServices#1083]
Trying to implement the aspnet-prerendering using systemjs. I get this error on build

```
Error on fetch for url.js at file:///C:/dev/***/app/node_modules/url.js
Loading aspnet-prerendering
Loading dist\tmp\app\main-prod.js
Error: ENOENT: no such file or directory, open 'C:\dev\Bet***\app\node_modules\url.js
```

And my systemjs config:
```
{
       name:'aspnet-prerendering',
       path:'node_modules/aspnet-prerendering/Prerendering.js'
},
```

I don't have "url" as a dependency, but aspnet-prerendering has, and it's not downloaded by default.

**Comment by SteveSandersonMS** [comment]
`url` is a built-in package in Node.js: https://nodejs.org/docs/latest/api/url.html#url_url

So, your module system should not be trying to fetch it from anywhere. It's already built into Node.

**Comment by Flood** [comment]
Hmm ok, this is from Prerendering.ts
```
import * as url from 'url';
```
By default it looks in the node_modules folder, so I am not sure how to avoid it.

**Comment by SteveSandersonMS** [comment]
I'm afraid I can't provide advice on how to configure system.js - you'll need to check their docs or ask support questions to the system.js community. Hope that's OK!
