### ISSUE TITLE
React template IE11

### ISSUE THREAD

**Issue by EmmaHansson** [aspnet/JavaScriptServices#1085]
React template doesn't work in IE11. 
Seems no Promises in IE11.
So how to use Polyfill in this template? 

and 

Why Polyfill doesn't included into the template ?

**Comment by SteveSandersonMS** [comment]
We don't include polyfills for all browsers because it would make the applications much larger, and not everybody needs to support legacy browsers.

For an example of including polyfills, please see https://github.com/aspnet/JavaScriptServices/pull/953

**Comment by EmmaHansson** [comment]
Your forwarding link is for 
1. Angular
2. Not answers the question how to setup it in react template :)

**Comment by SteveSandersonMS** [comment]
It will work the same in the React template.

**Comment by EmmaHansson** [comment]
Seems, no.

In reactredux template what I need is only 

import 'core-js/es6';

This approach doesn't work in react.
