### ISSUE TITLE
dockerfile update after dotnet-migrate

### ISSUE THREAD

**Issue by ranbuch** [aspnet/JavaScriptServices#1087]
After migrating as described in this [https://docs.microsoft.com/he-il/dotnet/core/tools/dotnet-migrate](url) the Dockerfile has to be updated accordingly.

I've changed this:
```
FROM microsoft/dotnet:1.0.5-runtime
```
to this:
```
FROM microsoft/dotnet:1.1.0-sdk-projectjson
```

but this line:
```
COPY project.json .
```
is generating an error - there is no ```project.json``` file after the migration.

Can you provide an example to a valid Dockerfile for ```microsoft/dotnet:1.1.0-sdk-projectjson```?

Thank you.

**Comment by SteveSandersonMS** [comment]
`project.json` is deprecated, so I wouldn't recommend using any SDK or Docker setup based on that.

There are some general docs about using Docker with ASP.NET Core here: https://docs.microsoft.com/en-gb/dotnet/core/docker/building-net-docker-images Those techniques will apply to SPA projects too, with the one exception that you'll need to amend the `Dockerfile` to make it install Node.js during the image creation, for example by adding the following lines right after the `FROM` line:

```
RUN apt-get update
RUN apt-get install curl
RUN curl -sL https://deb.nodesource.com/setup_6.x | bash
RUN apt-get install -y build-essential nodejs
```

(assuming you're using a Docker image based on Ubuntu/Debian).
