### ISSUE TITLE
How to put the project covalent into JavascriptService Template

### ISSUE THREAD

**Issue by ElderJames** [aspnet/JavaScriptServices#1088]
[Covalent](https://github.com/Teradata/covalent) is a great project based on Angular and Material Design,But I failed to try to combine this project.

Anyone help?

**Comment by SteveSandersonMS** [comment]
Sorry, I don't have any specific experience with Covalent (nor had I heard of it before your post) so don't have any specific tips. Since the project templates in this repo give you a standard Webpack setup, whatever information Covalent has about working with Webpack should apply here too.
