### ISSUE TITLE
Proposal: lack of documentation

### ISSUE THREAD

**Issue by laskoviymishka** [aspnet/JavaScriptServices#109]
There is no documentation right now, may be it's time to add some wiki or docs?

**Comment by SteveSandersonMS** [comment]
Added docs for `NodeServices` in the `README.md` file: https://github.com/aspnet/JavaScriptServices/tree/master/src/Microsoft.AspNetCore.NodeServices

Will do the same for `SpaServices` soon.

**Comment by SteveSandersonMS** [comment]
Added docs for `SpaServices` at https://github.com/aspnet/JavaScriptServices/blob/master/src/Microsoft.AspNetCore.SpaServices/README.md

**Comment by SteveSandersonMS** [comment]
I've also updated the repo's root `README.md` file to describe the repo generally and link to specific docs for `NodeServices` and `SpaServices`.

So, although there are still other places that more docs could be added, the level of documentation is good now. I'm closing this issue as there's no longer a general lack of docs. We can still add more docs elsewhere as needed.
