### ISSUE TITLE
Node Modules script invoked by NodeServices are terminated automatically ?

### ISSUE THREAD

**Issue by davidsekar** [aspnet/JavaScriptServices#1093]
I'm using this package [Highcharts Node.js export server](https://github.com/highcharts/node-export-server) to generate charts on the server side.

Here is the node js script that I invoke from NodeServices

```
const exporter = require('highcharts-export-server');

// Export settings 
// var exportSettings = {
//  type: 'png',
//  options: {
//    title: {
//      text: 'My Chart'
//    },
//    xAxis: {
//      categories: ["Jan", "Feb", "Mar", "Apr", "Mar", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]
//    },
//    series: [
//      {
//        type: 'line',
//        data: [1, 3, 2, 4]
//      },
//      {
//        type: 'line',
//        data: [5, 3, 4, 2]
//      }
//    ]
//  }
// };

var exp = module.exports = {
  generateHighChart: (callback, chartOptions) => {
    try {

      var exportSettings = {
        type: 'png',
        options: chartOptions,
        scale: 2,
        sourceWidth: '1170',
        sourceHeight: '300'
      };

      exporter.logLevel(4);

      let config = {
        maxWorkers: 1,
        initialWorkers: 1,
        // reaper: false,
        listenToProcessExits: true
      };

      //exporter.log(4, 'Start Init');
      // Set up a pool of PhantomJS workers
      exporter.initPool(config);

      // Perform an export
      /*
          Export/Chart settings corresponds to the available CLI arguments described
          above.
      */
      exporter.export(exportSettings,
        (err, res) => {

          //exporter.log(4, JSON.stringify(res));
          try {
            // The export result is now in res.
            // If the output is not PDF or SVG, it will be base64 encoded (res.data).
            // If the output is a PDF or SVG, it will contain a filename (res.filename).
            // ret.data = res;
            //exporter.log(4, 'Received ' + res);
            // Kill the pool when we're done with it, and exit the application
            exporter.killPool();
            //process.exit(1);
          } catch (innerError) {
            // ret.err = innerError;
            exporter.log(4, 'Kill throws error : ' + innerError);
          }
          callback(err, JSON.stringify(res));
        });
    } catch (err) {
      //exporter.log(4, 'Try KillPool');
      exporter.killPool();
      //exporter.log(4, 'Kill succeeded');
      callback(err, null);
    };
  }
};
// exp.generateHighChart(function () { }, {});

```
.Net Core
```
result = await _nodeServices.InvokeExportAsync<string>("./client/modules/highcharts-image/generate-chart",
          "generateHighChart",
          chartOptions);

```

Even after completion of the execution, I see continuous message from the "Highcharts Node.js export server" i.e., 

> reaper checking for timed out phantom processes

Seems that the Highcharts node server is using time out. which is not close by nodeservices

how to properly exit the invoked node script ?

**Comment by davidsekar** [comment]
If I use process.exit(1) then nodeservices throws 

> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: The connection with the server was terminated abnormally
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()

**Comment by SteveSandersonMS** [comment]
When you invoke code in Node via NodeServices, that code can do anything that normal Node code can do, such as start arbitrarily long async operations, permanent event listeners, or timeouts/intervals to run further code in the future. It's up to the code you invoke to make sure it completes in a graceful way or otherwise offers a suitable API for stopping whatever you want to stop it doing. NodeServices doesn't forcefully terminate it in any way.

You *can* use `process.exit` if you want, but there are some serious drawbacks:

 * It will be bad for performance, because NodeServices will keep starting up new Node processes each time it notices the old one has been terminated
 * If you are processing more than one request at once, it's possible that some other unrelated request is still in progress when you kill the Node process. That will cause the other request to fail with an error.

So, it would be much better to make sure the code you're invoking knows how to stop whatever it's doing if you don't intend it to be an ongoing operation. This is unfortunately not something that NodeServices can do for you - we let the code you invoke do whatever it's programmed to do.

**Comment by davidsekar** [comment]
When multiple InvokeAsync calls are made by NodeServices simultaneously (at same moment) to **an exported module** (e.g., AddNumbers), does it create multiple instances of the nodejs, execute and return the results in parallel 

or else a single node process is maintained that receives multiple requests, execute them and returns result sequentially ??? 

Q: I was under impression that **_each call_** to InvokeAsync() **_creates a new nodejs instance_** for the script whether or not same node process already exists.  Please clarify.

**Comment by SteveSandersonMS** [comment]
There's only one Node instance at a time, and it can handle multiple invocations in parallel. It would be very bad for performance if we created and destroyed entire Node processes to handle each invocation.

**Comment by davidsekar** [comment]
Thanks for clarifying.

Just one more question, if there are 10 exported JavaScript functions and are invoked.

If module 1 is a long running process like a continuous job, will it block all requests to 9 other modules till that one completes execution ? (Since you said There's only one Node instance at a time)

So if I have chart rendering javascript that runs continuously,, in between if there are calls for prerendering the other pages. Will those request be blocked ?

**Comment by SteveSandersonMS** [comment]
It's a regular Node process, so it works the same as any other code running under Node. If you search for "node async" or similar you'll find lots of information about it, for example: https://blog.risingstack.com/node-hero-async-programming-in-node-js/

**Comment by davidsekar** [comment]
@SteveSandersonMS 👍 
Thanks a lot for clarifying. Now I understood what happens when InvokeAsync() is triggered.

As per your suggestion, I have modified the export script to start the node process once and init pool of  phantomjs workers and keep it running. Then in subsequent request, I use the same node process for future invocations. No exit calls for node process.
Just the link incase someone has the same question : [Rendering Highcharts using nodeservices](https://davidsekar.com/angular/server-side-rendering-of-highcharts-in-net-core
)
