### ISSUE TITLE
Socket hosting model not working

### ISSUE THREAD

**Issue by laskoviymishka** [aspnet/JavaScriptServices#110]
I faced issue with newly created Socket hosting model. It not respond for any requests. I not really sure what exact goes wrong. It could be enviroment issue or so.
My machine is win10 x64 with latest updates.
# Steps to reproduce

1. Open ReactGrid sample
2. Specify Socket hosting model by adding `services.AddNodeServices(new NodeServicesOptions { HostingModel = NodeHostingModel.Socket });` to your `ConfigureServices` method.
3. Run `dotnet run` command
4. Try to open _localhost:5000_

# Expected behaivior
Page rendered

# Actual behaivior
Page stuck in infinite load

***Note***:
If run under old fashion `Http` hosting model everything work perfect.

***UPD***:
after long long wait for response i recieve following error:
```
System.IO.IOException: Pipe is broken.
   at System.IO.Pipes.PipeStream.CheckWriteOperations()
   at System.IO.Pipes.PipeStream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.NodeServices.HostingModels.VirtualConnections.VirtualConnectionClient.<WriteAsync>d__19.MoveNext() in C:\dev\Source\Repos\NodeServices\src\Microsoft.AspNetCore.NodeServices\HostingModels\VirtualConnections\VirtualConnectionClient.cs:line 188
```

**Comment by SteveSandersonMS** [comment]
Thanks for pointing this out.

In my final commit I'd missed out the `PipeOptions.Asynchronous` option that's needed on Windows for the named sockets transport not to just hang. Fixed now.

**Comment by ManuelDeLeon** [comment]
Is the fix for this one out? I keep getting `One or more errors occurred. (Pipe is broken.)` intermittently  (no error log or stack trace)

**Comment by SteveSandersonMS** [comment]
> Is the fix for this one out?

Yes, the original issue reported by @laskoviymishka - that it *never* works - is fixed and was released as `beta-000004`.

If you have a scenario where it fails intermittently, that must be something different.

Based on your description, I'm pretty sure your intermittent issue is the same as #128, hence not reopening this issue. Let's keep any discussion about the intermittent thing in #128.
