### ISSUE TITLE
Version warning with webpack 3

### ISSUE THREAD

**Issue by mcm-ham** [aspnet/JavaScriptServices#1116]
Getting this in the build:
```
warning "aspnet-webpack@2.0.1" has incorrect peer dependency "webpack@^1.13.2 || ^2.1.0-beta".
```
I take it webpack 3.2 works fine and the peer dependency can be updated?

**Comment by SteveSandersonMS** [comment]
We haven't tested with Webpack 3+, so I can't say for sure what works or doesn't. Please let us know if you find any problems other than this warning.

**Comment by fhelwanger** [comment]
We're using webpack 3 and, besides the peer dependency warning, everything is working fine.

**Comment by rydergillen-compacSort** [comment]
Ditto

**Comment by nickkhan** [comment]
I can confirm, the warning is still there.
