### ISSUE TITLE
How to use Swagger and return 404 for unknown API urls

### ISSUE THREAD

**Issue by ysazak** [aspnet/JavaScriptServices#1119]
How can I use swagger with this template? When I implement swagger, the swagger page is redirected to home page due to SpaFallbackRoute.

Also, when unknown api url (for example; api/xyz) is called, it redirects to home page. I would like to return 404

Thanks for your help

**Comment by SteveSandersonMS** [comment]
Whatever middleware you're using for Swagger, put it before your call to SpaFallbackRoute, so it gets first priority on handling the request.

> Also, when unknown api url (for example; api/xyz) is called, it redirects to home page. I would like to return 404

You can use a technique similar to this: https://github.com/aspnet/JavaScriptServices/issues/973#issuecomment-303766597
