### ISSUE TITLE
How do you test an Angular 2 component here?

### ISSUE THREAD

**Issue by ManuelDeLeon** [aspnet/JavaScriptServices#112]
I'm trying to hack my way into testing an Angular 2 component but I think there's got to be an easier way. One without so many errors.

I added mocha and chai, then created the file `.\ClientApp\components\app\app.test.ts`:

```js
import { App } from './app';
describe("Test", function () {
    it("works", function () {
        let app = new App();
        chai.assert.ok(app);
    });
});
```

I compile with tsc into a test folder then try to run mocha but get the error `reflect-metadata shim is required when using class decorators`. After a LOT of trial and mostly errors I find a post that says I should add `var reflect = require('reflect-metadata');` to the test file. I do that and now I get  `Error: Cannot find module './nav-menu.html'` Then I tried to add the html files to the test folder but get `SyntaxError: Unexpected token <`

At this point I think I'm on the wrong path because it shouldn't be this hard. So how do you test an Angular 2 component here?

**Comment by MarkPieszak** [comment]
This should help you out a bunch! https://developers.livechatinc.com/blog/testing-angular-2-apps-dependency-injection-and-components/

**Comment by SteveSandersonMS** [comment]
@ManuelDeLeon - yes, I've no doubt this is tricky to set up. At some point we might include a suggested test setup in the default generated project. I hope @MarkPieszak's link gets you started.

For now I'm going to close this as it's really an Angular 2 setup question rather than being anything specific to JavaScriptServices. Please reopen if you disagree.

@MarkPieszak - thanks for the link!

**Comment by ManuelDeLeon** [comment]
@SteveSandersonMS - I totally understand your position as, strictly speaking, this isn't a problem with JavaScriptServices. That said, I think you guys should give an example of how to test Angular 2 components (a blog post, a footnote on the readme, anything). The link @MarkPieszak provided works beautifully for that particular starter/boilerplate but I'm on the 6th ring of hell trying to make it work with this starter app.

Again I know technically this isn't your problem but then it's no one's problem. If I go to the Angular groups they're going to say "testing works just fine if you use any of the node starter projects, take it to the .Net Core starter one"
