### ISSUE TITLE
Prerender Parent component and all its children except one

### ISSUE THREAD

**Issue by fatjoni** [aspnet/JavaScriptServices#1123]
My situation is this: I am building a single page website and parts of the page are different components. I need to integrate a map from  highcharts but i cannot find a way to include it as part of the same parent while excluding from prerendering in the same time. The whole app only works if i move it from shared.ts to client.ts. This hits the websites prerendering benefits. Can you help me on this? 
Thank you

**Comment by SteveSandersonMS** [comment]
You'll need to use a test in your code like [this one](https://github.com/aspnet/JavaScriptServices/issues/253#issuecomment-239939581) to ensure that client-only code only executes on the client.

There isn't a straightforward way that I know of, with either Angular or React, to just mark a whole component as not to be included during server-side prerendering. But for more details about Angular/React APIs, please check their docs.
