### ISSUE TITLE
[Question] Why was babel used in React templates?

### ISSUE THREAD

**Issue by antmdvs** [aspnet/JavaScriptServices#1124]
..instead of just `tsc`? I was always a little unclear on this. Was it just for RHL 2.x?

This question is prompted by:
https://github.com/aspnet/JavaScriptServices/commit/48b923fcd5a10a620a2b9931da0b3439d39fdc5d

Thanks!

**Comment by SteveSandersonMS** [comment]
It was for RHL 2.x which depended on Babel.

RHL 3 removes this dependency, so we were able to remove Babel altogether.
