### ISSUE TITLE
ReactGrid sample - HMR and React Hot Reloading

### ISSUE THREAD

**Issue by antmdvs** [aspnet/JavaScriptServices#113]
Hot Reloading is not working for the ReactGrid sample.

**Comment by SteveSandersonMS** [comment]
It is working when I run it. Are you definitely running in [development mode](http://stackoverflow.com/questions/37413374/run-application-in-development-environment)? If you start your app using `dotnet run`, check you see the following in the console:

    Hosting environment: Development

Please reopen with repro details if you still get a problem here! Thanks.

**Comment by antmdvs** [comment]
Hi Steve,

Yes, I am in Development mode. However, after further research, I found that HMR *is* working with Chrome (Version 50.0.2661.102 m), but I see the following in the Console output for IE 11 (on Windows 7 SP1):

> webpack-hot-middleware's client requires EventSource to work. You should include a polyfill if you want to support this browser: https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events#Tools

I will try this Polyfill and post back here when I get a chance:
https://github.com/Yaffle/EventSource

Thanks.
