### ISSUE TITLE
Debugging in Visual Studio after refresh

### ISSUE THREAD

**Issue by AJDray** [aspnet/JavaScriptServices#1130]
This is not exclusive to this template but wanted to get your thoughts. 

Having trouble debugging in visual studio. It's a common part of of dev workcycle to use the debugging tools in VS. Any guidelines on how to get this up and running with the WebPack middleware?

**Comment by alexdresko** [comment]
@AJDray Debugging is a wide topic. Can you explain what you're having trouble with? C#? TypeScript? Javascript? Client side? Server side?

**Comment by AJDray** [comment]
@alexdresko appreciate it's a broad topic. I have tried out the examples and am very interested in them. I'm currently a RequireJS user, looking at webpack to streamline workflow, so not that familiar with ins and outs of it. 

The only problem I think I have is that debugging is not working in Visual Studio 2017 enterprise. This means I want to place breakpoints in a specific file and for the debugger to break at this point. On further investigation I note that the requirements for map files are very specific in order for them to work in Visual Studio. 
This issue relates similar woes https://github.com/gulp-sourcemaps/gulp-sourcemaps/issues/205

I don't actually think this project is generating map files that meet the requirements of visual studio. I have had a similar problem using gulp-sourcemaps. For this reason I currently use visual studio to compile my typescript for debugging.

I'm using IIS Express and clicking the "Play" button in Visual Studio.

**Comment by SteveSandersonMS** [comment]
Projects generated by the templates in this repo automatically have VS-compatible debugging setups. Just press F5 to launch in Chrome, and VS will attach itself to Chrome. You can then set breakpoints on your `.ts` sources in VS and they will get hit as expected.

Alternatively you can use the browser's built-in debugger, which will get the sourcemaps so you can see your original `.ts` code.

> Debugging in Visual Studio after refresh

I'm not sure what you mean by "after refresh". If you have a specific scenario that doesn't work, could you post repro steps? Thanks!

**Comment by AJDray** [comment]
Hi, 
I've worked a lot more with the project and this is what I see. I'm not sure if this is specifically an issue with this template.

1.) Create new template from the Yeoman sources.
2.) Follow the run steps in the blog article published by Steve Sanderson. Including steps to enable debugging.
- I then upgraded all dependencies to latest version.
3.) Run project in chrome. 

Breakpoints work.

Make changes to the TS files in project, Using Hot Module Reloading.

Ensure relevant changes appear in client. 

I find that after this cycle is complete then breakpoints in the file that has been changed cease working. 
I find breakpoints continue to work in Chrome debug tools.

I have had trouble with Visual Studio source maps and understood they were particularly specific, I wondered if this was another example.  

HTH

**Comment by SteveSandersonMS** [comment]
Ah yes, that is true. VS's integration with Chrome for debugging doesn't have a concept of source files changing during a debugging session, so you will have to disconnect and reconnect after editing a file. Like you said, it is easier just to use the browser's built-in debugging tools.

**Comment by AJDray** [comment]
Assume by disconnect and reconnect you mean I need to stop and start Visual Studio, or is there a shortcut?

**Comment by SteveSandersonMS** [comment]
That is what I mean
