### ISSUE TITLE
Angular spa template's dist folder created twice.

### ISSUE THREAD

**Issue by asadsahi** [aspnet/JavaScriptServices#1137]
Just ran the latest spa template in visual studio and did dotnet build on it. And it has produced dist folders twice in the project as shown below:

![image](https://user-images.githubusercontent.com/3470892/28426183-57019452-6d6a-11e7-850c-c88e14d53450.png)

Any reason for this?

**Comment by rosieks** [comment]
If you notice the content is different. The one under ClientApp contains code that is run on server side, while wwwroot contains files that are exposed to the client and they are run in the browser. You can ask then why file like vendor.js is then duplicated. The answer is that it can have different content. For example it can be not minified.

**Comment by asadsahi** [comment]
@rosieks thanks for explaining. I am having another issue if you think of anything obvious?
![image](https://user-images.githubusercontent.com/3470892/28455120-d2f4dd36-6df5-11e7-8e7d-8085b7c2c237.png)


offending line is this:

![image](https://user-images.githubusercontent.com/3470892/28455133-e0cf45a4-6df5-11e7-9c53-7b71bbcf2f21.png)


Not sure why it is complaining for document.

**Comment by asadsahi** [comment]
@rosieks the issue was browseranimations module and some usage of document in the code, have fixed those, but now I am getting following error even I have prefixed my api calls with absolute url using BASE_URL token available in the base spa template: 
![image](https://user-images.githubusercontent.com/3470892/28459787-e9c52a14-6e06-11e7-914d-ec3405ecd430.png)

**Comment by SteveSandersonMS** [comment]
I'll close this since the original issue has been handled and the conversation seems to have moved on. @asadsahi, I'm not sure whether you are reporting a different issue, but if so, could you file a new issue with repro steps based on creating a fresh new project? Thanks!
