### ISSUE TITLE
[object Object]: ESLint configuration is invalid: - Unexpected top-level property "ecmaFeatures".

### ISSUE THREAD

**Issue by andrei-galkin** [aspnet/JavaScriptServices#1143]
I have created a angular project by **yo aspnetcore-spa** opened **webpack.config.js** and having the error _[object Object]: ESLint configuration is invalid: - Unexpected top-level property "ecmaFeatures"_. in visual studio code .

**Comment by mcquiggd** [comment]
If you are trying to use ESLint 4.x, there were some breaking changes, which were problematic with the airbnb style guide, among others. 

There is a possible solution on StackOverflow:

https://stackoverflow.com/questions/44531243/eslint-module-build-failed-error-with-eslint-config-airbnb

**Comment by andrei-galkin** [comment]
Thanks
