### ISSUE TITLE
Server-side rendering baseUrl not being set

### ISSUE THREAD

**Issue by stephenlautier** [aspnet/JavaScriptServices#1146]
Not sure if this is a bug or I'm missing something out, however, I'm configuring the `base` tag within `_Layout.cshtml` and the `params.baseUrl` within server side rendering is not being set.

This is what I'm doing:

```html
<base href="/@Model.Locale/" />

// which output the following
<base href="/en/" />
```

After debugging the server-side rendering, I've noticed that the `params.baseUrl` is set as `"/"`

```ts
// refering to the following
{ provide: APP_BASE_HREF, useValue: params.baseUrl }

// params.baseUrl => "/"
```

![2017-07-25 17_07_05-developer tools - node](https://user-images.githubusercontent.com/3908723/28579142-15ac1194-715c-11e7-83de-c1f2803ccf30.png)

**Expected**
I expect that the `baseUrl` is set accordingly from the specified `base` element.

**Issue**
The issue I'm getting due to this it's always landing on the home page, irrespective on which page I actually go and then re-route afterward.

**Comment by SteveSandersonMS** [comment]
Data from your `<base>` tag is not available during server-side prerendering. It never has been - we don't try to parse things out of your Razor pages like that.

Instead, `params.baseUrl` comes from ASP.NET's `PathBase` context property. This should match whatever virtual directory your app is being served from.
