### ISSUE TITLE
update `aspnet-webpack` to webpack 3

### ISSUE THREAD

**Issue by pfrendo** [aspnet/JavaScriptServices#1149]

**Comment by stephtr** [comment]
A newer version of `aspnet-webpack` isn't required for running webpack 3, I think at the moment it is relatively safe to ignore the warning about that when restoring packages.

**Comment by gaspardle** [comment]
Yes but then we can't do `npm shrinkwrap`

**Comment by SteveSandersonMS** [comment]
Duplicate of #1126
