### ISSUE TITLE
Angular2 RC1

### ISSUE THREAD

**Issue by wangkanai** [aspnet/JavaScriptServices#115]
when would you update package.json to 
```
"@angular/common" : "2.0.0-rc.1"
```

**Comment by SteveSandersonMS** [comment]
The `templates/Angular2Spa` template is already on Angular 2 RC1, and does reference the package version that you've mentioned.

If you mean updating the Music Store sample, that's on the backlog but is a low priority.

**Comment by MarkPieszak** [comment]
Hey Steve! How's everything been going with the .NET Core & Angular Universal integration lately? Let me know if you need any help, I believe Patrick contacted you recently. I'm an ASP.NET / Angular guy myself, so I'd love to help! Let me know if/when you want to talk sometime @SteveSandersonMS
