### ISSUE TITLE
Latest version of template

### ISSUE THREAD

**Issue by NeilIrvingMacc** [aspnet/JavaScriptServices#1152]
Hi Guys

I have written and deployed several Angular2 apps using your template, I would now like to try your new template which uses Angular4, in VS2015 if I do new project > Asp.net Core Angular 2 Starter Application it creates a new app but its all pointing at Angular2 in package.json, how do I create a new app using the latest template not the one I last used in Feb?

Thanks

Neil

**Comment by stephtr** [comment]
You could create your project using:
```
npm install -g yo generator-aspnetcore-spa
yo aspnetcore-spa
```
That way you get the latest version of the template (including Angular 4).
(More informations are available at [Building Single Page Applications on ASP.NET Core with JavaScriptServices](https://blogs.msdn.microsoft.com/webdev/2017/02/14/building-single-page-applications-on-asp-net-core-with-javascriptservices/))

**Comment by SteveSandersonMS** [comment]
Thanks for answering, @stephtr!

**Comment by NeilIrvingMacc** [comment]
Thanks for this guys I will try this later on
