### ISSUE TITLE
JavaScript heap out of memory - ability to set max_old_space_size?

### ISSUE THREAD

**Issue by mcm-ham** [aspnet/JavaScriptServices#1155]
I keep getting this error preventing HMR from working when I use `AddNodeServices` and `UseWebpackDevMiddleware`:
```
fail: Microsoft.AspNetCore.NodeServices[0]
      FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[0]
      An unhandled exception has occurred while executing the request
```
Is it possible to specify the argument `max_old_space_size` when starting node?

**Comment by MarkPieszak** [comment]
One way to do it is making a script within package.json, and calling webpack from there.

    "webpack": "node --max_old_space_size=4096 node_modules/webpack/bin/webpack.js"

**Comment by mcm-ham** [comment]
Thanks for the suggestion, still seem to get the error though.

**Comment by mcm-ham** [comment]
A work colleague pointed out to me node 8 introduces support for node options via an environment variable:
https://nodejs.org/dist/latest-v8.x/docs/api/cli.html#cli_node_options_options

```c#
app.UseWebpackDevMiddleware(new WebpackDevMiddlewareOptions
{
    HotModuleReplacement = true,
    EnvironmentVariables = new Dictionary<string, string> {
        { "NODE_OPTIONS", "--max-old-space-size=4086" }
    }
});
```

This solved the out memory issue for us, may still be worth considering adding an option for older node versions and for making it more discoverable.

**Comment by SteveSandersonMS** [comment]
Thanks @mcm-ham - good to know about that. If this gets reported commonly, we'll definitely look at exposing the relevant option in a more obvious way. So far this is the only report though :)
