### ISSUE TITLE
Angular4 AOT in the template

### ISSUE THREAD

**Issue by NeilIrvingMacc** [aspnet/JavaScriptServices#1156]
Hi Guys

Liking the new template with all the benefits of Angular4, I know looking at the closed issues AOT has been mentioned a lot and the suggestion is its coming and has been done in other repo's.  When is it likely to be in this template?  Is there a tutorial to follow to add it?

Thanks

Neil

**Comment by SteveSandersonMS** [comment]
It's already in the latest templates in this repo. They will be shipped as part of the upcoming ASP.NET Core 2.0 release.
