### ISSUE TITLE
pass webpack instance stats into createServerRenderer()

### ISSUE THREAD

**Issue by tehOPEologist** [aspnet/JavaScriptServices#1166]
is there a way to pass the node instance's webpack stats into the createServerRenderer() function?  i'm trying to reference the assetsByChunkName stat for utilizing webpack's dynamic import functionality and don't see how i can gain access to that information right now.  any help would be appreciated, thanks!

**Comment by SteveSandersonMS** [comment]
I'm not aware of a way of doing that. In general, we don't assume that Webpack is even present at runtime (for example, after publishing, you're running a prebuilt site and don't by default even have the Webpack libraries in your application).
