### ISSUE TITLE
Why webpack is not run with dotnet run command in Angular project type

### ISSUE THREAD

**Issue by andrei-galkin** [aspnet/JavaScriptServices#1170]
I have create test angular project and have to run webpack manually each time before detnet run. 
How to make webpack run along with dotnet run. I am running project from command line.

Thanks in advance for the support.

**Comment by stephtr** [comment]
Are you running in development mode? (Have you set the ```ASPNETCORE_ENVIRONMENT``` environment variable to ```Development```, does dotnet run outputs ```Hosting environment: Development````?)

**Comment by andrei-galkin** [comment]
Thanks mate for guiding me. It works !. I was stupid nor to find this 
http://blog.stevensanderson.com/2016/05/02/angular2-react-knockout-apps-on-aspnet-core/

Have a great day.

**Comment by SteveSandersonMS** [comment]
Thanks for answering, @stephtr!
