### ISSUE TITLE
Failed to retrieve information about 'Microsoft.VisualStudio.Web.CodeGeneration.Tools'

### ISSUE THREAD

**Issue by maraza** [aspnet/JavaScriptServices#1174]
after running 
`dotnet new react`
`dotnet restore`

gives the following issue

C:\Program Files\dotnet\sdk\2.0.0-preview2-006497\NuGet.targets(102,5): error : Failed to retrieve information about 'Microsoft.VisualStudio.Web.CodeGeneration.Tools' from remote source 'http://nuget.dev-web-01.csdev.com.au
/nuget/FindPackagesById()?id='Microsoft.VisualStudio.Web.CodeGeneration.Tools''.\r [C:\Training\TrainingSample.csproj]
C:\Program Files\dotnet\sdk\2.0.0-preview2-006497\NuGet.targets(102,5): error :   Response status code does not indicate success: 404 (Not Found). [C:\Training\TrainingSample.csproj]

**Comment by SteveSandersonMS** [comment]
I think this must have been a temporary issue in NuGet because it doesn't happen now, nor have others reported it. Please try again and let us know if you're still encountering this. Thanks!
