### ISSUE TITLE
Use Brotli as Compression Method for Webpack

### ISSUE THREAD

**Issue by beam-codegrind** [aspnet/JavaScriptServices#1179]
Since Microsoft embraced `Brotli` into net standard, I suggest adding `brotli-webpack-plugin` to compress ClientApp for production in this repo to keep up with that.

I'm starting this issue to discuss if we should include it in this repo or not. If it's OK I'll create a new PR for this issue.

**Comment by SteveSandersonMS** [comment]
Thanks for the suggestion. In general our goal is to keep the number of concepts small where possible, so I don't think we'd add an extra plugin by default. As long as it's easy enough for people who want it to put it in their own Webpack configs that's great. If it's more complex, would you be interested in writing up a wiki page to explain how to do it? Thank!
