### ISSUE TITLE
How/where to add additional style files?

### ISSUE THREAD

**Issue by kemmis** [aspnet/JavaScriptServices#1182]
I have my webpack.config.js setup to use less-loader and it is loading my component's less files just fine. However I have an additional base-theme.less file in my app folder that I want to include so it is applied globally. What is the appropriate way to include this additional less file in my main (non-vendor) webpack?

**Comment by SteveSandersonMS** [comment]
It should be enough just to put `import 'path/to/your/file.less';` in your boot file (e.g., for Angular, that's `boot.browser.ts` or `boot-client.ts`).

**Comment by kemmis** [comment]
Thanks for the reply @SteveSandersonMS. I ended up putting everything in my app.component.less file next to the aspp.component.ts, and then setting encapsulation: ViewEncapsulation.None in the @Component() decorator.
