### ISSUE TITLE
NPM packages not restored in new project

### ISSUE THREAD

**Issue by rosieks** [aspnet/JavaScriptServices#1185]
After creation of new React Redux project from Visual Studio 2017.3 Preview 7.1 the npm packages wasn't installed. I use yarn and for that reason I have disabled restoring npm packages on project open - that can be the reason.

It's not something super critical but cause that newly created project doesn't start (lack of webpack).

**Comment by SteveSandersonMS** [comment]
Thanks for letting us know, but I'm not certain what you do want to happen here. If you've deliberately disabled NPM package restore, then NPM packages won't be restored by default and you'll have to do it manually :)

I'll mark this as closed as this is expected, but if you think there's a defect somewhere, can you post more details on what you think should be happening?
