### ISSUE TITLE
Angular template not available

### ISSUE THREAD

**Issue by drewfus** [aspnet/JavaScriptServices#1188]
I ran: dotnet new --install Microsoft.AspNetCore.SpaTemplates::*

But angular is not an option for available project types.

This was the output:

NuGet Config files used:
      C:\Users\{}\AppData\Roaming\NuGet\NuGet.Config
      C:\Program Files (x86)\NuGet\Config\Microsoft.VisualStudio.Offline.config

  Feeds used:
      https://api.nuget.org/v3/index.json
      C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\

  Installed:
      112 package(s) to C:\Users\{}\.templateengine\dotnetcli\v1.0.4\scratch\restore.csproj
Templates                          Short Name      Language      Tags
-------------------------------------------------------------------------------
Console Application                console         [C#], F#      Common/Console
Class library                      classlib        [C#], F#      Common/Library
Unit Test Project                  mstest          [C#], F#      Test/MSTest
xUnit Test Project                 xunit           [C#], F#      Test/xUnit
ASP.NET Core Empty                 web             [C#]          Web/Empty
ASP.NET Core Web App               mvc             [C#], F#      Web/MVC
ASP.NET Core with Aurelia          aurelia         [C#]          Web/MVC/SPA
ASP.NET Core with Knockout.js      knockout        [C#]          Web/MVC/SPA
ASP.NET Core with Vue.js           vue             [C#]          Web/MVC/SPA
ASP.NET Core Web API               webapi          [C#]          Web/WebAPI
Solution File                      sln                           Solution

**Comment by BenLBartle** [comment]
Also getting this issue, No issue with 0.9.3, You can install using:
dotnet new --install Microsoft.AspNetCore.SpaTemplates::0.9.3

**Comment by dansoper** [comment]
Same here. Was able to resolve by installing 0.9.3. I note that 1.0.0 was newly released today.

**Comment by SteveSandersonMS** [comment]
As of .NET Core 2.0, the Angular, React, and Redux templates are built into the SDK, so you get them automatically without having to install any additional package.

As of version 1.0.0, the `Microsoft.AspNetCore.SpaTemplates` package is an optional add-on that only contains the Aurelia, Knockout, and Vue templates.

**Comment by dansoper** [comment]
Ok, that makes sense. But for someone who still has .NET Core 1.1 and installs the templates, they will find them missing. Isn't it possible to make the SpaTemplates package dependent on Core 2.0?

**Comment by rsandhumcr** [comment]
You could create a .Net Core 2.0 site with Angular from the template and then covert the MVC Core to 1,1 .
