### ISSUE TITLE
npm Dependencies

### ISSUE THREAD

**Issue by simonwoodhead** [aspnet/JavaScriptServices#119]
Not a major issue but the Dependencies folder in Visual Studio 2015 does not play nicely with these templates. It says "Dependencies - not installed" (when in fact they are) and right-click > Restore Packages restores packages but changes back to "Dependencies - not installed" when it is complete. The ASP.NET Core Web Application template that is built into Visual Studio 2015 doesn't have this problem (but then it doesn't have React or Webpack!).

**Comment by SteveSandersonMS** [comment]
You're totally right - the version of NPM that VS2015 uses by default is 2.x which doesn't work properly on Windows. You can upgrade to a newer version of NPM manually, or [hassle the VS people to ship an update that includes NPM 3.x](https://visualstudio.uservoice.com/forums/121579-visual-studio-2015).

Closing as there's nothing we can do here - it's a VS issue.

**Comment by simonwoodhead** [comment]
Thanks for explaining I had no idea they were bundled. I've upvoted the use of external node/npm/bower implementations (https://visualstudio.uservoice.com/forums/121579-visual-studio-2015/suggestions/9547935-allow-using-external-node-npm-bower). I can see the advantage of bundling with VS initially but the inevitable inconsistency is really unfriendly.

**Comment by JonCubed** [comment]
Just FYI, if you have npm installed on your machine you can tell Visual Studio to use it instead by
1. Right-Click ***npm*** under *Dependencies* folder in project tree
2. Click "Configure external tools..."
3. Move the nodejs folder (typically *c:\Program Files\nodejs*) above *$(VSINSTALLDIR)\Web\External*
4. Click ***OK*** button

**Comment by simonwoodhead** [comment]
@JonCubed Thank you, I should have spotted that. I have tried that but unfortunately I am still stuck on "Dependencies - Not Installed". npm version is 3.8.3.

**Comment by JonCubed** [comment]
@simonwoodhead have you tried right-click ***Dependencies - Not Installed*** and selecting *Restore packages* ? You could also try modifying the packages.json and on save it should restore them

**Comment by antmdvs** [comment]
@JonCubed I also tried the "Configure external tools" workaround, but am still seeing " - not installed". I have npm 3.9.3. I tried everything short of restarting my computer. @simonwoodhead, did you get yours resolved?

**Comment by simonwoodhead** [comment]
Sadly not.

**Comment by JonCubed** [comment]
@simonwoodhead @simonwoodhead  when I upgraded to preview 1, I am now also seeing it but the packages are being downloaded, I can see them all listed under the npm folder. I also ran `npm list --depth 0` in project root and it shows they are installed so think it is a Visual Studio tooling bug

**Comment by JonCubed** [comment]
@simonwoodhead @antmdvs you can track the issue at https://github.com/aspnet/Tooling/issues/479

**Comment by JonCubed** [comment]
@simonwoodhead @antmdvs possible fix http://www.hanselman.com/blog/VisualStudio2015FixingDependenciesNpmNotInstalledFromFseventsWithNodeOnWindows.aspx
