### ISSUE TITLE
Optional route parameters not allowed in the templatePrefix for the MapSpaFallbackRoute

### ISSUE THREAD

**Issue by bgever** [aspnet/JavaScriptServices#1199]
Because of this check for the `?` character in the `templatePrefix`, of a `MapSpaFallbackRoute` call, I'm not able to define an optional route parameter in the template prefix.

https://github.com/aspnet/JavaScriptServices/blob/680ba7497aab980cbfd1d625a2a894480dbf186e/src/Microsoft.AspNetCore.SpaServices/Routing/SpaRouteExtensions.cs#L71-L75

**Comment by SteveSandersonMS** [comment]
Although this was reported a very long time ago, nobody else since then has asked for this support, so it's unlikely to meet the bar for what we'd work on. I'll close it. Hope that's OK.
