### ISSUE TITLE
Docker File not updated for RC2

### ISSUE THREAD

**Issue by samuelcavendish** [aspnet/JavaScriptServices#120]
RC2 Yeoman samples still generate docker files using RC1 & DNX

**Comment by SteveSandersonMS** [comment]
Yes - waiting for https://github.com/OmniSharp/generator-aspnet/pull/743

**Comment by ctolkien** [comment]
Bumping this as https://github.com/OmniSharp/generator-aspnet/pull/743 has since been merged.

**Comment by SteveSandersonMS** [comment]
Thanks for the notice - this is now done!

I'll publish updated Yeoman generators to NPM shortly.
