### ISSUE TITLE
change back to angular 4 template

### ISSUE THREAD

**Issue by adirzoari** [aspnet/JavaScriptServices#1201]
Hello,
when I open angular project with 

> yo aspnetcore-spa
and then I choose angular I get a new angular template.
I mean i never see app.module.server.ts , app.module.shared.ts, boot-client.ts
How can i downgrade it to old version template?

**Comment by SteveSandersonMS** [comment]
If you want an older version of the Yeoman templates, you could use `npm install -g generator-aspnetcore-spa@version` where `version` is whatever version you want.

However I recommend using the latest templates only. The latest Angular template is built into the .NET Core 2.0 SDK, and you can generate projects on the command line using `dotnet new angular` without installing any extra packages.

The older Yeoman templates are deprecated now and won't be maintained further.
