### ISSUE TITLE
Angular Template not downloading

### ISSUE THREAD

**Issue by ILL35T** [aspnet/JavaScriptServices#1202]
dotnet new --install Microsoft.AspNetCore.SpaTemplates::*
Downloads every template besides the angular one which is the one I need.
I tried uninstall and install via cmd. Didnt work.
![vs2017temp](https://user-images.githubusercontent.com/31081102/29387666-5ac4fbce-82e1-11e7-9538-197c5ce5d791.PNG)

I am running:
VS2017: v15.3.0
NodeJS: v6.11.2
Windows 10 Home: v1703

**Comment by bbrandt** [comment]
If you are able to update to ASP.NET 2.0 SDK, the `Microsoft.AspNetCore.SpaTemplates` are now included in the framework (#948), making the `--install Microsoft.AspNetCore.SpaTemplates::*` unnecessary.  I can confirm that the angular template is available there.

![image](https://user-images.githubusercontent.com/602767/29395173-b1604b30-82d4-11e7-82ca-386529a00f9d.png)

**Comment by MiniverCheevy** [comment]
if they're not showing up (which they didn't for me) you can run

`dotnet new --install Microsoft.DotNet.Web.Spa.ProjectTemplates::*`

to install them.  I didn't install the ASP.NET 2.0 SDK (which I didn't know existed), I installed the .NET Core 2.0 SDK

**Comment by bbrandt** [comment]
@MiniverCheevy 
I think your right, there's only a  .NET Core 2.0 SDK.  I was a bit confused by the different announcements for [.NET Core 2.0](https://blogs.msdn.microsoft.com/webdev/2017/08/14/announcing-asp-net-core-2-0/) and [ASP.NET Core 2.0](https://blogs.msdn.microsoft.com/webdev/2017/08/14/announcing-asp-net-core-2-0/)  with [different](https://github.com/dotnet/core/blob/master/release-notes/download-archives/2.0.0-download.md) download [links](http://dot.net/core).

Why I had the templates already and you had to install them separately is a mystery to me.

**Comment by SteveSandersonMS** [comment]
As you've discovered, `angular`/`react`/`redux` are now all in the .NET Core 2.0 SDK by default, and the others (`aurelia`/`knockout`/`vue`) are now in `Microsoft.AspNetCore.SpaTemplates`.

If you're upgrading from an older .NET Core SDK and had previously installed an older version of the `SpaTemplates` package then you could see older templates showing up. That might explain why @bbrandt already had them.

**Comment by ILL35T** [comment]
Thanks guys. Updating to Core 2.0 solved my issue.
