### ISSUE TITLE
Angular project generates error when trying to use Windows Authentication.

### ISSUE THREAD

**Issue by tschock** [aspnet/JavaScriptServices#1206]
When using the Angular project template that is offered for .NET Core 2.0 in Visual Studio 2017 15.3 I get the following error when I try to debug the application using IIS Express with Windows Authentication turned on (anonymous authentication is turned off).

![image](https://user-images.githubusercontent.com/7988756/29465629-948675a8-83ff-11e7-8001-c316ce882b10.png)

Is there any reason as to why this new template can't be used with Windows authentication?

**Comment by Alex-Torres** [comment]
@tschock I have been using the extension using Windows Authentication and I don't experience any problems besides some slowness on refresh once changes are done.  However, I think the problem you have may be related to .NET Core run time.  Try to go [here](https://www.microsoft.com/net/download/windows), and download the sdk/runtime again or you can update Visual Studio 2017 to latest version which I think is 15.5.2 available [here](https://www.visualstudio.com/en-us/news/releasenotes/vs2017-relnotes).

**Comment by SteveSandersonMS** [comment]
This is a very old issue, and I don't think there's any specific reason why it would still apply in the more recent templates. Since nobody else is reporting it, I'll close it. If you still think this is an active issue, please let us know!
