### ISSUE TITLE
Update aspnetcore-spa generator to create projects with ASP.NET Core 2.0

### ISSUE THREAD

**Issue by ClaudioNunes** [aspnet/JavaScriptServices#1207]
There is no "dotnet new aurelia". We still need "yo" to generate aspnet core with JavaScriptServices for Aurelia

**Comment by SteveSandersonMS** [comment]
The template is there, but the docs are lagging behind a bit.

If you have the .NET Core 2.0 SDK, then you need to do this:

    dotnet new --install Microsoft.AspNetCore.SpaTemplates::*

... and then you will be able to `dotnet new aurelia`.
