### ISSUE TITLE
About unit test sample for Vue 

### ISSUE THREAD

**Issue by Ku4nCheang** [aspnet/JavaScriptServices#1213]
Is there any unit test sample that works with Vue?
I tried to add an unit test using karma with Jasmine.
 
However, Webpack could not compile the typescript file when the following code occured in the file
`const component = require('./component.vue.html')`
It said that better to use an appropriate loader. 

I really need help to write an unit test to test a component.
Thanks.

**Comment by agrcrobles** [comment]
It looks like it's babel that doesn't compile.

Did you try it with jest?

https://github.com/locoslab/vue-typescript-jest

**Comment by Ku4nCheang** [comment]
@agrcrobles I will take a look, thanks for the suggestion. Hope it works.

**Comment by SteveSandersonMS** [comment]
Thanks for the answer @agrcrobles!
