### ISSUE TITLE
Using a custom logger for the node output.

### ISSUE THREAD

**Issue by pauldotknopf** [aspnet/JavaScriptServices#122]
https://github.com/aspnet/JavaScriptServices/blob/f2e89fd/src/Microsoft.AspNetCore.NodeServices/HostingModels/OutOfProcessNodeInstance.cs#L154

Applications don't always run from the command prompt. I realize we probably don't want to reference Microsoft's new logging interfaces, so what about adding support for some ```ILogger``` interface that implementations could chose to do what they want with the output.

Or, make the ```SocketNodeInstance``` and ```HttpNodeInstance``` types public so that we may inherit and override the members.

I am open to creating a pull request if we can agree on an approach.

**Comment by SteveSandersonMS** [comment]
This is now implemented (e.g., in `f4efca`). The updated NuGet packages aren't yet shipped though.

**Comment by SteveSandersonMS** [comment]
> I realize we probably don't want to reference Microsoft's new logging interfaces

BTW I did reference Microsoft's new logging interfaces. I'm not sure what would be the reason for not doing that, so if it is a concern to anyone, please let us know.
