### ISSUE TITLE
webpack error on publish with third-party Angular 4 npm package

### ISSUE THREAD

**Issue by rballentine** [aspnet/JavaScriptServices#1222]
I added a third-party npm package to the Angular template. I put the following in webpack.config.vendor.js:

`'ng2-toasty',
'ng2-toasty/bundles/style-bootstrap.css'`  

And everything works in development mode. But when I publish, I get an error executing this command:

`node node_modules/webpack/bin/webpack.js --env.prod`

The error:

> ERROR in ./$$_gendir/~/ng2-toasty/src/toasty.component.ngfactory.ts
    Module parse failed: C:\App\\$$_gendir\node_modules\ng2-toasty\src\toasty.component.ngfactory.ts Unexpected token (15:28)
    You may need an appropriate loader to handle this file type.
    | import * as i4 from 'ng2-toasty/src/toasty.component';
    | import * as i5 from 'ng2-toasty/src/toasty.service';
    | const styles_ToastyComponent:any[] = ([] as any[]);
    | export const RenderType_ToastyComponent:i0.RendererType2 = i0.╔╡crt({encapsulation:2,
    |     styles:styles_ToastyComponent,data:{}});
     @ ./$$_gendir/ClientApp/app/components/app/app.component.ngfactory.ts 9:0-102
     @ ./$$_gendir/ClientApp/app/app.module.browser.ngfactory.ts
     @ ./ClientApp/boot.browser.ts

I suspect there's some additional webpack configuration I need to do, but I don't know enough about webpack. Any help is appreciated. Thanks.

**Comment by mcdonaldp2** [comment]
I have the same issue with ng2-toastr

**Comment by mcdonaldp2** [comment]
I think this is a duplicate of issue #1168 

This [comment](https://github.com/aspnet/JavaScriptServices/issues/1168#issuecomment-320026397) helped me fix this on my end

**Comment by rballentine** [comment]
Thanks @mcdonaldp2 that solved my issue as well.

**Comment by gBusato** [comment]
@mcdonaldp2 Thanks !
