### ISSUE TITLE
What happened to ReactReduxSpa template?

### ISSUE THREAD

**Issue by theCuriousOne** [aspnet/JavaScriptServices#1223]
I see that all has been restructured, but I can not find the ReactReduxSpa template . I see just the plain react template. And some stuff have changed. There use to be boot-client.tsx and boot-server.tsx file, and now there is only boot.tsx.
Maybe a small explanation of what are you intending, how to migrate, or any other explanation beyond the git comment?

**Comment by MarkPieszak** [comment]
Isn't it here?
 https://github.com/aspnet/JavaScriptServices/tree/dev/templates/Microsoft.DotNet.Web.Spa.ProjectTemplates/redux

**Comment by SteveSandersonMS** [comment]
@MarkPieszak is correct - that's where it is. For now... :)

We're about to merge the regular ASP.NET templates (e.g., Empty Web Application, etc.) with the SPA templates into a new template repo that's dedicated just to templates. So the Redux (etc) templates will shortly be removed from this repo, but you'll continue to be able to submit PRs, issues, etc. Nothing is really changing except file locations!

**Comment by theCuriousOne** [comment]
(DOH!) Didn't see. Why not name it react-redux, since it is clearly both of them?

**Comment by SteveSandersonMS** [comment]
Just because the command to create it is `dotnet new redux`, and it would be a breaking change to all the docs to change that. I don't think it will be confusing to anyone, since Redux is overwhelmingly associated with React in practice even if it's not technically coupled to it.
