### ISSUE TITLE
Rename app modules to follow convention *.module.ts

### ISSUE THREAD

**Issue by kubaszumiato** [aspnet/JavaScriptServices#1228]
I was struggling to set up AngularCLI to generate components for my Angular app with the newest templates, there is a small trick that I had to do to make it recognize the main app module. I had to rename the *app.**module.browser**.ts* to *app.**browser.module**.ts*.

Is there any reason for such convention of modules' files naming? Angular team recommendations for naming of modules is with module.ts suffix, could you change this in your templates to follow this recommendation? Would you find such PR reasonable for all 3 modules in app folder of Angular template (browser, server, shared)?

**Comment by MarkPieszak** [comment]
If we could sync on the naming convention that would be ideal! 👍 
Also having `app.module` be an NgModule itself (that browser & server import inside their `imports[]` would be ideal as well!

**Comment by SteveSandersonMS** [comment]
Good plan. Done.
