### ISSUE TITLE
An item with the same key has already been added. Key: NODE_PATH

### ISSUE THREAD

**Issue by MarkPieszak** [aspnet/JavaScriptServices#123]
Got latest yesterday, fresh repo install, and noticed this coming up, not sure if it's a project issue or a configuration issue on my part that's messed up.

    ArgumentException: An item with the same key has already been added. Key: NODE_PATH
    System.ThrowHelper.ThrowAddingDuplicateWithKeyArgumentException(Object key)

**Comment by SteveSandersonMS** [comment]
Thanks - should be fixed with a881ca5b96e1c2d8253bb1c4cd18c42e8b0a1d8e
