### ISSUE TITLE
Project Fails to build/Publish

### ISSUE THREAD

**Issue by vijayrkn** [aspnet/JavaScriptServices#1237]
Sample csproj from user:
```
<Project ToolsVersion="15.0" Sdk="Microsoft.NET.Sdk.Web"> <PropertyGroup> <TargetFramework>netcoreapp1.1</TargetFramework> <TypeScriptCompileBlocked>true</TypeScriptCompileBlocked> <IsPackable>false</IsPackable> <TypeScriptToolsVersion>2.3</TypeScriptToolsVersion> </PropertyGroup> <ItemGroup> <PackageReference Include="Microsoft.AspNetCore" Version="1.1.2" /> <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="1.1.2" /> <PackageReference Include="Microsoft.AspNetCore.Identity" Version="1.1.2" /> <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="1.1.3" /> <PackageReference Include="Microsoft.AspNetCore.SpaServices" Version="1.1.1" /> <PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="1.1.2" /> <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="1.1.2" /> <PackageReference Include="Serilog.Extensions.Logging" Version="1.4.0" /> </ItemGroup> <ItemGroup> <!-- Files not to show in IDE --> <None Remove="yarn.lock" />
 &lt;!-- Files not to publish (note that the 'dist' subfolders are re-added below) --&gt;
 &lt;Content Remove="ClientApp\**" /&gt;
</ItemGroup> <ItemGroup> <Content Include="ClientApp\dist\papaparse.min.js" /> </ItemGroup> <ItemGroup> <ProjectReference Include="..\Domain.Data\Domain.Data.csproj" /> <ProjectReference Include="..\Domain.Model\Domain.Model.csproj" /> </ItemGroup> <Target Name="RunWebpack" AfterTargets="ComputeFilesToPublish"> <!-- As part of publishing, ensure the JS resources are freshly built in production mode --> <Exec Command="npm install" /> <Exec Command="node node_modules/webpack/bin/webpack.js --config webpack.config.vendor.js --env.prod" /> <Exec Command="node node_modules/webpack/bin/webpack.js --env.prod" />
 &lt;!-- Include the newly-built files in the publish output --&gt;
 &lt;ItemGroup&gt;
   &lt;DistFiles Include="wwwroot\dist\**; ClientApp\dist\**" /&gt;
   &lt;ResolvedFileToPublish Include="@(DistFiles-&gt;'%(FullPath)')" Exclude="@(ResolvedFileToPublish)"&gt;
     &lt;RelativePath&gt;%(DistFiles.Identity)&lt;/RelativePath&gt;
     &lt;CopyToPublishDirectory&gt;PreserveNewest&lt;/CopyToPublishDirectory&gt;
   &lt;/ResolvedFileToPublish&gt;
 &lt;/ItemGroup&gt;
</Target> </Project>
```

Additional context on the issue - https://developercommunity.visualstudio.com/comments/103876/view.html

**Comment by SteveSandersonMS** [comment]
Hi @vijayrkn. I'm afraid the information posted here doesn't give us anything we could use to diagnose or investigate any issue. Was there a specific error that occurred? Also the "additional context" you linked to doesn't seem related to the project templates in this repo - that's a thread about ASP.NET publishing in general.

If you have specific repro steps and error information, could you please post them as a new issue? Thanks!

**Comment by dsslayers** [comment]
He posted this on behalf of an issue I am having. 
I have a .Net Core 1.1 Web Application that is using Webpack and Angular 2 front end.
Up until yesterday, I could publish with no issues. Starting yesterday, When I click publish, nothing happens. It doesnt build, and it doesnt publish. I am publishing to a folder location.
It is set to go to a remote location, but I have also tried it to a local location, and it also does nothing.The above is the sample csproj from me. I cant supply a sample project, because of restrictions of the company I am at currently.

**Comment by SteveSandersonMS** [comment]
@dsslayers I would need more info to be able to investigate this. Ideally repro steps, but failing that, an example of a project that surfaces the issue. Sorry I can't infer what's changed in your project without that info!
