### ISSUE TITLE
Project Fails to Publish

### ISSUE THREAD

**Issue by dsslayers** [aspnet/JavaScriptServices#1239]
I have attached a sample project. When you try and publish to a folder location, nothing happens. The location on the publish profiles are network locations, but I also tried local ones as well, and the project does not even build. This only started happening to me yesterday. I have since upgraded Visual Studio to the latest version hoping it would fix the issue, but it does not. I was referred here from the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/content/problem/24972/publish-not-working-in-vs-2017-ide.html)
[Audit - Copy.zip](https://github.com/aspnet/JavaScriptServices/files/1264167/Audit.-.Copy.zip)

**Comment by vijayrkn** [comment]
This is the error I am seeing 

The specified SDK version [1.0.3] from global.json [E:\Audit.-.Copy\Audit - Copy\WarehouseAudit\global.json] not found; install specified SDK version

Do you have 1.0.3 version of sdk in C:\Program Files\dotnet\sdk? Else please update the  global.json sdk to match the version you have installed and that should fix the "publish not getting triggered issue".

**Comment by dsslayers** [comment]
Thank you so much. That has fixed the issue. I did have the 1.0.3 installed, but I also had 1.0.4 and 1.1.0 installed.
I changed it to 1.1.0, and it worked.
