### ISSUE TITLE
Source maps don't seem to be generated properly

### ISSUE THREAD

**Issue by emzero** [aspnet/JavaScriptServices#124]
I have generated a react-redux project using the `aspnetcore-spa` yeoman generator as explained [here](http://blog.stevensanderson.com/2016/05/02/angular2-react-knockout-apps-on-aspnet-core/)

Project runs fine with `dotnet run` but I can't seem to see the original source files when debugging in Chrome DevTools.

![image](https://cloud.githubusercontent.com/assets/412489/15941641/7dd1c1a4-2e57-11e6-8803-4fc50a3137c9.png)

I see in the `webpack.config.dev.js` file that the source maps are being inlined. Maybe that's the reason?

[vscode-chrome-debug](https://github.com/Microsoft/vscode-chrome-debug) extension documentation says:
> This extension ignores sources that are inlined in the sourcemap - you may have a setup that works in Chrome Dev Tools, but not this extension, because the paths are incorrect, but Chrome Dev Tools are reading the inlined source content.

Any way to make it work? Maybe actually generating the source maps to the file system?

**Comment by xabikos** [comment]
Are you sure you are under development mode? And if yes you can change the source map file option inside the [webpack.config.dev.js](https://github.com/aspnet/JavaScriptServices/blob/master/templates/ReactReduxSpa/webpack.config.dev.js) by setting it to `source-map` from `inline-source-map`

**Comment by emzero** [comment]
@xabikos Sorry, I was in production mode. Debugging is working in Chrome Dev with the original ts files.

Thanks
