### ISSUE TITLE
Remove Typescript from Vue Template

### ISSUE THREAD

**Issue by elucidsoft** [aspnet/JavaScriptServices#1240]
After struggling with TypeScript while using Vue I don't see the value it adds when using it in this particular scenario.  It breaks many of the Vue Plugins, its very difficult to get it to work seamlessly especially with Vuex and you constantly have to do weird hacks to get things to work.  If it doesn't add value to the situation I don't think it makes sense to use it.

**Comment by MarkPieszak** [comment]
The Vue community hasn't particularly caught onto TypeScript yet (they will eventually, using es6 alone just isn't worth the trouble).

The equivalent ES2015 + Vue template can be found in the Wiki here:
https://github.com/aspnet/JavaScriptServices/wiki#related-project-templates

This project: https://github.com/MarkPieszak/aspnetcore-Vue-starter

**Comment by SteveSandersonMS** [comment]
Thanks for the suggestion @elucidsoft. If we continue to get requests from the community to do this then we'll certainly consider doing that. For now, it's valuable to leave TypeScript in place for consistency across all the SPA templates. We also hope the Vue community starts to pick up on the benefits of strong typing and accounts for it more in the design and implementation of Vue plugins, and having this template might be a small step towards encouraging that.

**Comment by ianfabs** [comment]
TypeScript is a shit pseudo-compiler that adds nothing but unnecessary complexity to a project, decreasing ease of development and work-ability. It is a pointless pursuit to make it a staple of any framework unless you hate yourself. I hate TypeScript. That being said, none of that means I don't see the value in it. And I do really respect the disposition to leave it as a component of the framework. I think once it becomes a requirement for all vue modules it will actually be apparently useful

**Comment by Eilon** [comment]
Hi @ianfabs , please respect this project's code of conduct in the discussions: https://opensource.microsoft.com/codeofconduct/
