### ISSUE TITLE
Add unit and e2e tests to the aurelia sample

### ISSUE THREAD

**Issue by alexandru-calinoiu** [aspnet/JavaScriptServices#1245]
The current Aurelia template does not have tests added.

For people not used to webpack (like myself) adding configuring tests and e2e tests is rather hard.

PS: Sample code on how to use a css processor or html template processor will also be nice, bringing in functionality similar to aurelia-cli.

**Comment by SteveSandersonMS** [comment]
This is one of the things that would depend on community contributions. If anyone wants to submit a PR with a clean and simple equivalent to the Karma tests in the Angular template we'll certainly consider including it. Hope that's OK!
