### ISSUE TITLE
[domain-task] addTask: return promise

### ISSUE THREAD

**Issue by stephtr** [aspnet/JavaScriptServices#1249]
Wouldn't it be more useful if `addTask` would return the original promise?
One could then write `const response = await addTask(fetch('/api/test'));` instead of
```
const task = fetch('/api/test');
addTask(task);
const response = await task;
```
Edit: [@DanHarman](https://github.com/aspnet/JavaScriptServices/issues/902#issuecomment-299418722) also mentioned it.

**Comment by SteveSandersonMS** [comment]
Thanks - I'll close this in favour of #1252.
