### ISSUE TITLE
Angular 2 and .NET Core 2 Support

### ISSUE THREAD

**Issue by techlexic** [aspnet/JavaScriptServices#1251]
Forgive me if this has already been asked and answered but I seem to be stuck in an information loop. 

Why is Angular2 in .NET Core 2 not supported? 

`yo aspnetcore-spa`

```
Using the .NET Core 2.0 SDK, you can run any of the following commands in an empty directory, without needing to install any external packages first:

    * dotnet new angular
    * dotnet new react
    * dotnet new redux
....
### This Yeoman generator is DEPRECATED
```
This fails:
`dotnet new angular`

So:
`dotnet new --install Microsoft.AspNetCore.SpaTemplates::* `

```
Templates                          Short Name      Language      Tags
-------------------------------------------------------------------------------
Console Application                console         [C#], F#      Common/Console
Class library                      classlib        [C#], F#      Common/Library
Unit Test Project                  mstest          [C#], F#      Test/MSTest
xUnit Test Project                 xunit           [C#], F#      Test/xUnit
ASP.NET Core Empty                 web             [C#]          Web/Empty
ASP.NET Core Web App               mvc             [C#], F#      Web/MVC
ASP.NET Core with Aurelia          aurelia         [C#]          Web/MVC/SPA
ASP.NET Core with Knockout.js      knockout        [C#]          Web/MVC/SPA
ASP.NET Core with Vue.js           vue             [C#]          Web/MVC/SPA
ASP.NET Core Web API               webapi          [C#]          Web/WebAPI
Solution File                      sln                           Solution

```

Why must I be in such pain?

**Comment by MarkPieszak** [comment]
If I'm not mistaken the yeoman generators are deprecated, and only `dotnet new` templates & the template within VS2017 will be updated in the future.

**Comment by techlexic** [comment]
"in the future" in framework speak is too late.  MEAN stack it will be again, I was hoping to play.  :(

**Comment by MarkPieszak** [comment]
`dotnet new angular` doesn't work?
Can you try uninstalling the SpaTemplates and reinstalling maybe?

I just tried a fresh install and I'm seeing the 2.0 Core with `dotnet new angular`

`<TargetFramework>netcoreapp2.0</TargetFramework>`

I just meant that in the future, they'll stop updating yeoman generators and only dotnet new & VS templates :)

**Comment by techlexic** [comment]
Had to plus 1 that! Thank you very much for checking me. You made my day.  I was 100% sure I got Core 2, but I must have just "really considered it."  I have been so busy in MEAN stack, I just updated to Core 2 no problems — I get to play!  Cheers, thanks again!
