### ISSUE TITLE
Targeted .NET framework?

### ISSUE THREAD

**Issue by verlok** [aspnet/JavaScriptServices#1256]
Hi there,
we're trying to use this, but we get the following error

> Could not install package 'Microsoft.AspNetCore.SpaServices 2.0.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

Which version of .NET framework should we use to be compatible to SpaServices 2.0.0?

Thanks

**Comment by SteveSandersonMS** [comment]
That package supports `netstandard2.0` and `net461`.
