### ISSUE TITLE
Implement Test Framework that is compatible with Visual Studio Test Explorer

### ISSUE THREAD

**Issue by Narnain** [aspnet/JavaScriptServices#1257]
I am using the Angular template and have the Jasmine unit test working through our CI/CD pipeline on VSTS by adding the jUnit reporter and phantomJS browser to the Karma config.  

I cannot find a way to surface these test in the Test Explorer inside Visual Studio

**Comment by SteveSandersonMS** [comment]
I haven't tried them personally, but there are [various third-party mechanisms](https://www.google.co.uk/search?q=karma+visual+studio) for integrating Karma with Visual Studio.
