### ISSUE TITLE
Redux support in Angular 4

### ISSUE THREAD

**Issue by tonywr71** [aspnet/JavaScriptServices#1259]
In the Startup.cs file for React with Redux, it has the following code:
```
app.UseWebpackDevMiddleware(new WebpackDevMiddlewareOptions
{
   HotModuleReplacement = true,
   ReactHotModuleReplacement = true
 });
```

My understanding is that this allows React components to be changed without losing in-memory state. I believe this is due to its use of Redux. Redux, however, is technology agnostic. It doesn't care if its being used by React or other javascript environments. There are a number of people using it with Angular online, but I also know that I can't add the ReactHotModuleReplacement flag to Startup.cs in an Angular project. 

My question is, if I use Angular with Redux, does the Angular template support Hot Module Replacement for components while retaining in-memory state?

**Comment by SteveSandersonMS** [comment]
> My question is, if I use Angular with Redux, does the Angular template support Hot Module Replacement for components while retaining in-memory state?

That's not something that would happen automatically. In the React+Redux template, there's `react-hot-loader` package that makes the state retention happen. You'd need to set up some equivalent for Angular, though I don't know what exactly the equivalent package would be, or if there is one. I'd enquire with the Angular community to see what folks are using for this.

**Comment by MarkPieszak** [comment]
Look into angular-HMR here: https://github.com/AngularClass/angular-hmr to get it setup.

**Comment by tonywr71** [comment]
Ok, I've implemented the redux pattern in the original template, but I haven't done the hot module replacement with retained in-memory state just yet. 

If anyone is interested, I have put my solution on github [here.](https://github.com/tonywr71/AngularReduxTest).

This demonstrates using redux in the counter component and the fetchdata component. The router state is managed for you just by registering the StoreRouterConnectingModule.

The entry point to redux may be found in the store folder, found under ClientApp/app. It contains root.redux.ts, which is where you find the application-wide redux components, in this case counter, fetchdata and the router (the RootReducer and RootState are referenced here).

A simplified version of the pattern is found in counter, where you can find the counter.redux.ts file, containing the Actions, Reducers and Methods. I have added variables (initial numbers, increment and decrement values, and reset value) to demonstrate passing of payload into the actions. 

If you execute the application, go to the counter page and click on the Increment/Decrement/Reset buttons and change the values, you can then change to the forecast page, then change back to the counter page and the state is retained. The value is where you left it when you transitioned to the forecast page.

Because of the retention of state, if you now go back to the forecast page, it does not need to call the api again to retrieve the forecasts. I have deliberately made it so that it only makes the call once. (You could create another action to cause a refresh on demand.)

A slightly more complicated version exists in fetchdata. The fetchdata.component attaches variables to the store in its constructor. It also dispatches an action (found in the fetchdata.redux file) to request forecast data, if it hasn't already been loaded. The effects file contains the action executor.

When you raise the "RequestWeatherForecastsAction" event, the effects method (action executor), which was registered in the app module, calls the fetchdata service, which retrieves the forecast data from /api/sampledata controller. It then calls another action (ReceiveWeatherForecastsSuccessAction) to say that the data has been retrieved. This returns the data to the subscription on the component page, and it will then show on the fetchdata.component.html page.

Note that there are a bunch of references in the app.module.shared file that I have added, grouped together. Also, this still works in prerender mode, and I have not made any modifications to the webpack files.

I hope this is of value to somebody!
