### ISSUE TITLE
.xproj file errors from Angular 2 option

### ISSUE THREAD

**Issue by matthewtanner** [aspnet/JavaScriptServices#126]
> "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External\npm.CMD" install
> npm WARN install Couldn't install optional dependency: Unsupported
> npm WARN EPEERINVALID angular2-express-engine@0.14.1 requires a peer of angular2-universal@^0.102.0 but none was installed.
> npm WARN EPEERINVALID angular2-hapi-engine@0.14.0 requires a peer of angular2-universal@^0.102.0 but none was installed.
> npm WARN EPACKAGEJSON ScrumReporter@0.0.0 No repository field.
> npm WARN EPACKAGEJSON ScrumReporter@0.0.0 No license field.

Went through the setup on http://blog.stevensanderson.com/2016/05/02/angular2-react-knockout-apps-on-aspnet-core/. Found that the .xproj file threw this into output when testing from VS2015, but it works with "dotnet run" in cli.

**Comment by SteveSandersonMS** [comment]
Can you make sure your installation of VS is using NPM v3.x? If yours is still on NPM v2.x, you're going to have trouble with Angular. (e.g., http://josharepoint.com/2016/05/04/how-to-configure-visual-studio-2015-integration-with-latest-version-of-node-js-and-npm/)

At some point this will cease to be an issue when VS includes NPM v3.x by default, but until then you'll need to do a manual upgrade.

If your copy of VS is already calling NPM 3.x, please reopen!
