### ISSUE TITLE
access twice on first load of fetch data

### ISSUE THREAD

**Issue by chencingyen** [aspnet/JavaScriptServices#1261]
In angular spatemplate, i try to put breakpoint in "api/SampleData/WeatherForecasts", the app will fetch it **twice** from that API if i directly access http://localhost:58498/fetch-data

any idea how to make the app fetch only **once**? in the prerender time only?

second question is... if i have a **empty-textbox** inside one of my component, immediately after the browser load only the html (server finished to prerender), the i try to put some text in the textbox... then after web-browser get the javascript, the value i typed recently in the textbox is gone... any idea how to make it right?

thanks in advanced

**Comment by MarkPieszak** [comment]
You'd need an HttpTransfer mechanism setup to stop an API from getting hit twice (only do this for essential Gets). The other issue is solved via preboot. Both are setup in my companion repo if you want to grab them from there.

**Comment by SteveSandersonMS** [comment]
We're working on building in a way of doing this: https://github.com/aspnet/JavaScriptServices/commit/1287709feb4f19b14c5121785962a4691b60a49a

If you wanted, you could use that approach now. Something like this will be built into a future version of the templates.
