### ISSUE TITLE
502.5 error Javascriptservices SPA Template build

### ISSUE THREAD

**Issue by KurtGarrettALS** [aspnet/JavaScriptServices#1263]
Regarding using the SPA Templates with VS2017 15.3.3
Posting this in hopes that it is helpful. I worked out the issue for my situation.
Symptoms:
A. **Development Machine**
1. Project generated with "dotnet new <framework name>".
2. Runs fine on local development machine (Win7Pro64).
3. Only .net Core 2.0 installed.
4. NOTE: no changes to Project, exactly as generated from template engine.
5. Switch to "Release" and set ASPNETCORE_ENVIRONMENT to "Production"
6. Publish with Web Deploy Package method.

B. **Over to the Server**
1. Win2008R2SP1(64)
2. New HyperV...never used to host web services.
3. Set up per instructions [https://docs.microsoft.com/en-us/aspnet/core/publishing/iis](url)
4. Install Web Deploy 3.6 via WPI.
5. Import published application using Deploy
6. ERROR 502.5 (both from "Browse" locally and remote machine) Latest Google Chrome in both cases.

Punchline: installed .net core 1.1.2 runtime on server, 502.5 error goes away and application works fine.

**Comment by SteveSandersonMS** [comment]
Thanks for letting us know. Hopefully this info will be useful to others.

Closing as this is already resolved.
