### ISSUE TITLE
dotnet new --install Microsoft.AspNetCore.SpaTemplates::*

### ISSUE THREAD

**Issue by bhavyashekar** [aspnet/JavaScriptServices#1264]
Used above command to add all templates like aurelia react etc. all templates are added except for angular.
I am using vs2017 version 15.3.1

**Comment by horseyhorsey** [comment]
Same issue, but only with Knockout. I ran this command to try the KO template, but it doesn't appear in dotnet new.

**Comment by horseyhorsey** [comment]
I solved my issue by removing dead nuget source feeds inside VS. 

These feeds were disabled, but until they were actually physically removed from the list this command wouldn't install.

**Comment by SteveSandersonMS** [comment]
Glad you sorted it out.

For anyone else reading, if you have .NET Core 2.0 SDK, then `angular`, `react`, and `redux` templates are built-in by default. You only need the `Microsoft.AspNetCore.SpaTemplates` package to get the `aurelia`, `knockout`, and `vue` templates.
