### ISSUE TITLE
Make Karma test be executed on Internet Explorer or Edge browser by default

### ISSUE THREAD

**Issue by brightcr** [aspnet/JavaScriptServices#1272]
The current tests for Angular SPA runs using Google Chrome browser which may not be installed in all machines. I would like to have it executed with IE/Edge by default. This would ensure the tests can be executed on wide range of machines and won't require browser installation.

**Comment by SteveSandersonMS** [comment]
Please see Karma docs for how to change the default browser.

> This would ensure the tests can be executed on wide range of machines and won't require browser installation.

We're cross-platform :) IE and Edge aren't available on Mac/Linux.
