### ISSUE TITLE
Angular Template Publish Error - CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by naveedahmed1** [aspnet/JavaScriptServices#1273]
Hi,

With Angular Template in Visual Studio 2017, the publish command fails with below error:

```
node node_modules/webpack/bin/webpack.js --env.prod
EXEC(0,0): Error : CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
D:\MyProject\MyProject.csproj(49,5): Error MSB3073: The command "node node_modules/webpack/bin/webpack.js --env.prod" exited with code 3.
```

When using Angular CLI, I was able to increase memory in **ng** and **ngc** files under **`node_modules\.bin`** folder.

I made the same changes for this project as well. But it seems that its not working. Is there any way to increase mode memory in visual studio when using Angular template from Microsoft?

**Comment by dasdecoder** [comment]
I'am also facing the same issue!!
How you solve this?
