### ISSUE TITLE
Disabling Angular AOT 

### ISSUE THREAD

**Issue by EduardTheThird** [aspnet/JavaScriptServices#1274]
Hi JSS,

Thank you for adding AOT compilation, it's a handy feature to have 👍 
Unfortunately we are dependant on 3rd-party Angular modules that do not support AOT yet.
Is there a way of temporarily disabling the AOT compilation for the publishing of the template?

Thanks 🐱

**Comment by SteveSandersonMS** [comment]
Yes. In `webpack.config.js`:

 * Change the rule for `.ts` so it never uses `'@ngtools/webpack'`, i.e., remove the conditional expression and always use the `isDevBuild` part of the expression.
 * Remove the use of `AotPlugin` from the array of plugins used in production builds (this appears in both client and server bundle configs)

**Comment by EduardTheThird** [comment]
Worked, thank you!
