### ISSUE TITLE
Yet another window is not defined error

### ISSUE THREAD

**Issue by meeweed** [aspnet/JavaScriptServices#1275]

**Comment by meeweed** [comment]
no answers :{

**Comment by watermelonpizza** [comment]
Hey @meeweed,

You need to supply some more information than the basic error message in the title. It's almost impossible to figure out what the problem is with what you have given us. 
Ensure to include what modules you are using, the call stack of the error, webpack config etc.

**Comment by meeweed** [comment]
Hello,

I figured it out. I had to hack the library. The original question had to do with using a javascript package which makes use of the window object without checking if it exists. The javascript package also tries to attach itself to jquery as well. I added the import to the browser file and was hoping that the plugin would be available inside my component once I verified that I was executing on the browser. It wasn't. 

I was looking for best practices when dealing with 3rd party javascript libraries and their requirements in order for it to work with the spa templates.

Thank you
