### ISSUE TITLE
Add Option for React Templates to be non TypeScript

### ISSUE THREAD

**Issue by pkellner** [aspnet/JavaScriptServices#1276]
I understand why it makes sense in Angular to have TypeScript only templates.  React is different. Most of the React community does not use TypeScript and if they do type checking I'm pretty sure they use Facebook Flow.  I'm not advocating creating a Flow template but I would recommend creating a vanilla JavaScript template.  Marius notes :

> If you're using React, on the other hand, you might prefer Flow because it easily integrates with Babel and other infrastructure you probably already have in place

https://blog.mariusschulz.com/2017/01/13/typescript-vs-flow

**Comment by SteveSandersonMS** [comment]
Thanks for the suggestion. We'll bear it in mind but it's not currently planned.
