### ISSUE TITLE
Error when using HotModuleReplacement

### ISSUE THREAD

**Issue by tidusjar** [aspnet/JavaScriptServices#1277]
I'm getting the following error in the browsers console when using HotModuleReplacement after upgrading to .Net core 2.0.

> EventSource's response has a MIME type ("text/html") that is not "text/event-stream"

The above is appearing in the browsers console. Note: this did not happen when using the latest .Net Core 1.1 package.

My Startup code:

    app.UseWebpackDevMiddleware(new WebpackDevMiddlewareOptions
    {
        HotModuleReplacement = true
    });

**Comment by AMatijevic** [comment]
I'm getting the same error in React frontend template.
I try the solution with:
`app.UseWebpackDevMiddleware(new WebpackDevMiddlewareOptions {
				HotModuleReplacement = true,
				HotModuleReplacementEndpoint = "/dist/__webpack_hmr"
			});`
But that did't work for me.
If some wan know how to fix hot module replacement in asp.net core 2.0 React JavaScript services templates please help.
Thanks.

**Comment by MattJeanes** [comment]
After upgrading to webpack-hot-middleware 2.19.1 from 2.18.2 and webpack 3.6.0 from 3.5.5 this issue is now resolved for me. Can anyone else confirm?

**Comment by tidusjar** [comment]
Yeah fixed for me, closing issue as it's not to do with the `UseWebpackDevMiddleware` extension.
