### ISSUE TITLE
Issue getting pre-rendered data into angular

### ISSUE THREAD

**Issue by avarndell** [aspnet/JavaScriptServices#1280]
Trying to get angular to see the pre-rendered data.

in my Index.html (HomeController)  I have the pre-render data loading.
<div id="my-spa" asp-ng2-prerender-module="ClientApp/boot-server"
     asp-prerender-data="new {
                    ApiUri = @ViewData["ApiUri"],
                    GrantType = @ViewData["GrantType"],
                    Token = @ViewData["TokenEndpoint"]
                 }"></div>
Using DI in asp.net core the viewdata is being passed in with values.

In the boot.server.ts, I have the following
  return new Promise<RenderResult>((resolve, reject) => {
            zone.onError.subscribe((errorInfo: any) => reject(errorInfo));
            appRef.isStable.first(isStable => isStable).subscribe(() => {
                // Because 'onStable' fires before 'onError', we have to delay slightly before
                // completing the request in case there's an error to report
                setImmediate(() => {
                    resolve({
                        html: state.renderToString(),
                        globals: {
                            apiUri: params.data.ApiUri,
                            grantType: params.data.GrantType,
                            tokenEndpoint: params.data.TokenEndpoint
                    }
                    });
                    moduleRef.destroy();
                });
            });
        });
I can't seem to get a hold of the "globals" and it's properties.

**Comment by SteveSandersonMS** [comment]
Check the HTML source that the prerendering emits (i.e., just look at your page's source in your brower). You should see the `globals` data emitted as values called `window.apiUrl`, `window.grantType`, etc. So you can read them back in your client-side code from those locations.
