### ISSUE TITLE
React examples for non-SPA websites

### ISSUE THREAD

**Issue by markgarcia** [aspnet/JavaScriptServices#129]
I want to use React only in parts of my existing website. Seeing that prerendering seems to be a good thing, among other features, I decided to use JavaScriptServices as the starting point (React.NET's dependency .NET versions conflicts with those of my existing dependencies). However, I'm lost on how I am able to do this as all examples focus on making SPAs, with a single entry point for both client and server. I know that somehow my scenario is already supported with the current state of this library, but I feel that I need guidance on doing it.

Thank you very much guys. I love the effort you're putting into this. :)

**Comment by xabikos** [comment]
If I understand correctly you want to render several sections of one page through React, right? In this case JavaScript services certainly supports this but it can be a bit tricky regarding configuration. So for every section you need to render you have to add the asp prerender tag 
`<div id="section" asp-prerender-module="ClientApp/boot-section" asp-prerender-webpack-config="webpack.config.js">Loading...</div>`
and then create the equivalent script for the client. If you need to render multiple sections in different pages then you will end up with too many boot scripts at least for the server. For the client you can reduce the number of the files. 

Actually based on your scenario a good idea would be in the prerender tag helper to add a parameter of which component to render.

**Comment by SteveSandersonMS** [comment]
Thanks for posting.

If I understand correctly, and based on @xabikos's response, the thing we're missing here is the ability to supply extra information to the boot module to tell it what component or other data to render. That makes sense and is definitely something we can improve.

This requirement is already captured by #107 so I'll close this issue in favour of that one. If this doesn't adequately cover what you want, please reopen with more details. Thanks!

**Comment by xabikos** [comment]
If I understood correctly what @markgarcia wants to do is slightly different and simpler. Passing the initial model is to that direction but I guess that we need also some info which component to render. In all samples we have now it's the routing that decides which component will be rendered.

In case we need to render just a part of the page then most probably we will define which component to render and additional to this pass some data as #107 suggests. This looks more like what Reactjs.NET already does.

**Comment by SteveSandersonMS** [comment]
> we need also some info which component to render

That can be part of the model information you pass.

**Comment by markgarcia** [comment]
The issue referenced by @SteveSandersonMS seems to be adequate enough for my needs. I've also taken @xabikos's suggestion and am in the process of creating a tag helper that I'll use to indicate which component to use. @xabikos is right in that I want more like that of the style of React.NET wherein you can simply create a component script and directly use it from a view for rendering, without going through a boot script / router.
