### ISSUE TITLE
app.module.server.ngfactory not found on publish

### ISSUE THREAD

**Issue by ZeekoZhu** [aspnet/JavaScriptServices#1294]
reproduce:
```
mkdir temp
cd temp
dotnet new angular
yarn install #  (or cnpm install) npm is very slow in China
vim temp.csproj # change npm to yarn or cnpm
dotnet restore
dotnet run # everything works well
dotnet publish
```

here is the log:
```
Microsoft (R) Build Engine version 15.3.409.57025 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  temp -> /home/zeeko/Projects/temp/bin/Debug/netcoreapp2.0/temp.dll
  ✔ Installed 51 packages
  ✔ Linked 0 latest versions
  ✔ Run 0 scripts
  ✔ All packages installed (used 18ms, speed 0B/s, json 0(0B), tarball 0B)
  Hash: 6519e31713523a1b78e0b5e515cf7d3dc8dab468
  Version: webpack 2.5.1
  Child
      Hash: 6519e31713523a1b78e0
      Time: 7823ms
                                     Asset    Size  Chunks                    Chunk Names
      89889688147bd7575d6327160d64e760.svg  109 kB          [emitted]         
                                 vendor.js  194 kB       0  [emitted]         vendor
                                vendor.css  289 kB       0  [emitted]  [big]  vendor
  Child
      Hash: b5e515cf7d3dc8dab468
      Time: 7811ms
                                     Asset    Size  Chunks                    Chunk Names
      89889688147bd7575d6327160d64e760.svg  109 kB          [emitted]         
                                 vendor.js  3.4 MB       0  [emitted]  [big]  vendor
  Hash: 2957d49fe26751c2264e8140e9bae979f059541c
  Version: webpack 2.5.1
  Child
      Hash: 2957d49fe26751c2264e
      Time: 6651ms
               Asset    Size  Chunks                    Chunk Names
      main-client.js  268 kB       0  [emitted]  [big]  main-client
      
      ERROR in ./ClientApp/boot.browser.ts
Module not found : error : Can't resolve './../$$_gendir/ClientApp/app/app.module.browser.ngfactory' in '/home/zeeko/Projects/temp/ClientApp' [/home/zeeko/Projects/temp/temp.csproj]
       @ ./ClientApp/boot.browser.ts 5:0-95
  Child
      Hash: 8140e9bae979f059541c
      Time: 6859ms
               Asset    Size  Chunks                    Chunk Names
      main-server.js  1.8 MB       0  [emitted]  [big]  main-server
      
      ERROR in ./ClientApp/boot.server.ts
Module not found : error : Can't resolve './../$$_gendir/ClientApp/app/app.module.server.ngfactory' in '/home/zeeko/Projects/temp/ClientApp' [/home/zeeko/Projects/temp/temp.csproj]
       @ ./ClientApp/boot.server.ts 8:0-94
/home/zeeko/Projects/temp/temp.csproj(41,5): error MSB3073: The command "node node_modules/webpack/bin/webpack.js --env.prod" exited with code 2.
```

version info:
```
dotnet sdk: 2.0.0
nodejs:8.5.0
yarn:1.0.4
cnpm:5.1.1
system: both Windows 10 Insider Fall Update Preview and Manjora 17.0.5
```

**Comment by davidsekar** [comment]
May be related to this issue that happens in AoT production builds.
https://github.com/aspnet/JavaScriptServices/issues/1293

**Comment by SteveSandersonMS** [comment]
From the thumbs-up, it looks like maybe @davidsekar's comment provides a resolution.

Failing that, your repro sounds like you have a scenario that works fine with NPM, but fails with cnpm? Is that really the case? If so, cnpm must not be an adequate drop-in replacement for NPM. Likewise Yarn is not really to be trusted because it doesn't support `npm-shrinkwrap.json` files so there's no guarantee it will give you a compatible set of packages (if you really want to use Yarn, you will need to create a `yarn.lock` file referencing the same package resolutions as are in `npm-shrinkwrap.json` to ensure your dependencies are correct).

**Comment by markuspalme** [comment]
For me `npm install enhanced-resolve@3.3.0` did solve the problem.

**Comment by johnpankowicz** [comment]
I have the same issue. I had already made @davidsekar's change when I had issue #1168. And I tried @markuspalme 's with no success. Below is my package.json and webpack.config.js. Also I have @angular/cli@1.7.1 installed globally.

++++++++++++ Package.json +++++++++++++
{
  "name": "WebAppSpaTemplate",
  "private": true,
  "version": "0.0.0",
  "scripts": {
    "test": "karma start ClientApp/test/karma.conf.js"
  },
  "dependencies": {
    "@angular/animations": "5.2.4",
    "@angular/common": "5.2.4",
    "@angular/compiler": "5.2.4",
    "@angular/compiler-cli": "5.2.4",
    "@angular/core": "5.2.4",
    "@angular/forms": "5.2.4",
    "@angular/http": "5.2.4",
    "@angular/platform-browser": "5.2.4",
    "@angular/platform-browser-dynamic": "5.2.4",
    "@angular/platform-server": "5.2.4",
    "@angular/router": "5.2.4",
    "@ng-bootstrap/ng-bootstrap": "^1.0.0",
    "@ngtools/webpack": "1.9.8",
    "@types/webpack-env": "1.13.5",
    "angular2-template-loader": "0.6.2",
    "aspnet-prerendering": "^3.0.1",
    "aspnet-webpack": "^2.0.1",
    "awesome-typescript-loader": "3.4.1",
    "bootstrap": "4.0.0",
    "classlist.js": "^1.1.20150312",
    "css": "2.2.1",
    "css-loader": "0.28.9",
    "es6-shim": "0.35.3",
    "event-source-polyfill": "0.0.12",
    "expose-loader": "0.7.4",
    "extract-text-webpack-plugin": "3.0.2",
    "file-loader": "1.1.6",
    "html-loader": "0.5.5",
    "isomorphic-fetch": "2.2.1",
    "jquery": "3.3.1",
    "json-loader": "0.5.7",
    "preboot": "6.0.0-beta.1",
    "raw-loader": "0.5.1",
    "reflect-metadata": "0.1.12",
    "rxjs": "5.5.6",
    "style-loader": "0.20.1",
    "to-string-loader": "1.1.5",
    "typescript": "2.7.1",
    "url-loader": "0.6.2",
    "videogular2": "^6.0.4",
    "webpack": "3.11.0",
    "webpack-hot-middleware": "2.21.0",
    "webpack-merge": "4.1.1",
    "zone.js": "0.8.20"
  },
  "devDependencies": {
    "@types/chai": "4.1.2",
    "@types/jasmine": "2.8.6",
    "chai": "4.1.2",
    "jasmine-core": "2.99.1",
    "karma": "2.0.0",
    "karma-chai": "0.1.0",
    "karma-chrome-launcher": "2.2.0",
    "karma-cli": "1.0.1",
    "karma-jasmine": "1.1.1",
    "karma-webpack": "2.0.9",
    "popper.js": "^1.12.9"
  }
}


+++++++++++++++ webpack.config.js +++++++++++++
const path = require('path');
const webpack = require('webpack');
const merge = require('webpack-merge');
//const AotPlugin = require('@ngtools/webpack').AotPlugin;
const AngularCompilerPlugin = require('@ngtools/webpack').AngularCompilerPlugin;
const CheckerPlugin = require('awesome-typescript-loader').CheckerPlugin;

module.exports = (env) => {
    // Configuration in common to both client-side and server-side bundles
    const isDevBuild = !(env && env.prod);
    const sharedConfig = {
        stats: { modules: false },
        context: __dirname,
        resolve: { extensions: [ '.js', '.ts' ] },
        output: {
            filename: '[name].js',
            publicPath: 'dist/' // Webpack dev middleware, if enabled, handles requests for this URL prefix
        },
        module: {
            rules: [
                // I got many webpack errors saying: "Unexpected token (11:25) You may need an appropriate loader to handle this file type."
                // See: https://github.com/aspnet/JavaScriptServices/issues/1168#issuecomment-320026397
                // I changed the following line.
                // { test: /\.ts$/, include: /ClientApp/, use: isDevBuild ? ['awesome-typescript-loader?silent=true', 'angular2-template-loader'] : '@ngtools/webpack' },
                { test: /\.ts$/, use: isDevBuild ? ['awesome-typescript-loader?silent=true', 'angular2-template-loader'] : '@ngtools/webpack' },
                { test: /\.html$/, use: 'html-loader?minimize=false' },
                { test: /\.css$/, use: [ 'to-string-loader', isDevBuild ? 'css-loader' : 'css-loader?minimize' ] },
                { test: /\.(png|jpg|jpeg|gif|svg)$/, use: 'url-loader?limit=25000' }
            ]
        },
        plugins: [new CheckerPlugin()]
    };

    // Configuration for client-side bundle suitable for running in browsers
    const clientBundleOutputDir = './wwwroot/dist';
    const clientBundleConfig = merge(sharedConfig, {
        entry: { 'main-client': './ClientApp/boot.browser.ts' },
        output: { path: path.join(__dirname, clientBundleOutputDir) },
        plugins: [
            new webpack.DllReferencePlugin({
                context: __dirname,
                manifest: require('./wwwroot/dist/vendor-manifest.json')
            })
        ].concat(isDevBuild ? [
            // Plugins that apply in development builds only
            new webpack.SourceMapDevToolPlugin({
                filename: '[file].map', // Remove this line if you prefer inline source maps
                moduleFilenameTemplate: path.relative(clientBundleOutputDir, '[resourcePath]') // Point sourcemap entries to the original file locations on disk
            })
        ] : [
            // Plugins that apply in production builds only
            new webpack.optimize.UglifyJsPlugin(),
            //new AotPlugin({
            new AngularCompilerPlugin({
                tsConfigPath: './tsconfig.json',
                entryModule: path.join(__dirname, 'ClientApp/app/app.module.browser#AppModule'),
                exclude: ['./**/*.server.ts']
            })
        ])
    });

    // Configuration for server-side (prerendering) bundle suitable for running in Node
    const serverBundleConfig = merge(sharedConfig, {
        resolve: { mainFields: ['main'] },
        entry: { 'main-server': './ClientApp/boot.server.ts' },
        plugins: [
            new webpack.DllReferencePlugin({
                context: __dirname,
                manifest: require('./ClientApp/dist/vendor-manifest.json'),
                sourceType: 'commonjs2',
                name: './vendor'
            })
        ].concat(isDevBuild ? [] : [
            // Plugins that apply in production builds only
            //new AotPlugin({
            new AngularCompilerPlugin({
                tsConfigPath: './tsconfig.json',
                entryModule: path.join(__dirname, 'ClientApp/app/app.module.server#AppModule'),
                exclude: ['./**/*.browser.ts']
            })
        ]),
        output: {
            libraryTarget: 'commonjs',
            path: path.join(__dirname, './ClientApp/dist')
        },
        target: 'node',
        devtool: 'inline-source-map'
    });

    return [clientBundleConfig, serverBundleConfig];
};
