### ISSUE TITLE
Universal Support?

### ISSUE THREAD

**Issue by jrmcdona** [aspnet/JavaScriptServices#1296]
Hello-
Does this project already have Universal setup or should we be using Mark's stater project for that.

I am thinking about starting very simple for one of my project's but wanted Universal so if dotnet new angular has that, I would go that route.

Thanks

**Comment by MarkPieszak** [comment]
Mine is a companion repo, this has universal in it as well for the angular template. You can start there and then add in whatever you'd like if that's best for your project! 👍

**Comment by jrmcdona** [comment]
@MarkPieszak cool!  I am using both templates in various projects!
