### ISSUE TITLE
Visual Studio 2017 Performance Problem 15.3.5 with ASPNETCORE & Javascript projects

### ISSUE THREAD

**Issue by varghesep** [aspnet/JavaScriptServices#1298]
I reported a performance problem with Visual Studio 2015 in 2015. I also met Dan at Microsoft and mentioned the problem. Now after two years, the problem has only become worse with **Visual Studio 2017 Enterprise Edition 15.3.5**. Out of 30 minutes that I code JavaScript (Angular & React) in Visual Studio 2017, I spend 10 minutes at least waiting at various times due to the unresponsiveness.

These are the issues:

1. Save a angular typescript file, the Visual Studio 2017 becomes unresponsive.
2. Code for few seconds and try to save, the Visual Studio will give a message saying it is formatting and then it hangs for a while.

I suspect that this unresponsiveness is due to some JavaScript service running in the background. Here is my processor look like at most of the time, and worse performance by **Node** server services most of the time consuming CPU 50%.

![image](https://user-images.githubusercontent.com/12233474/30784898-15d3f8d4-a123-11e7-9ddc-2d189f16b34d.png)

This is how my settings look like. Turning off **Language Service off** did not help.

![image](https://user-images.githubusercontent.com/12233474/30784935-d53d2c90-a123-11e7-889c-d776928f0eac.png)

![image](https://user-images.githubusercontent.com/12233474/30784936-dec11cd6-a123-11e7-9590-158d40522d40.png)

![image](https://user-images.githubusercontent.com/12233474/30784941-f2015464-a123-11e7-8e3d-7eaabed1f8b5.png)

![image](https://user-images.githubusercontent.com/12233474/30784946-fd64afe0-a123-11e7-8ce0-2fa755d0df4f.png)

**Solution:**

It is so frustrating to work in an Enterprise application in **Visual Studion 2017** that has **DOTNETCORE and Angular Typescript**. To save time, I had to ignore all the ```ts``` files from the project. This is the command I used in ```tsconfig.json```:

```
  "exclude": [
    "./node_modules/**/*",
    "./myangularapp/**/*"
  ] 
```

I had to use a **gulp** task to transpile the **typescript** files to **JavaScript** files.

A permanent solution to this problem may be in **Visual Studio or asp.net tools or msbuild**, but posting here because this problem does not exist for other language projects like C#.

**Comment by SteveSandersonMS** [comment]
I totally sympathise with your frustration and apologise for the inconvenience. IDE perf issues are one of the most annoying things that developers face.

Would you be able to follow up with Visual Studio by posting to https://visualstudio.uservoice.com/forums/121579-visual-studio-ide? This repo here only deals with JavaScriptServices, so there's nothing we can do here in this repo to change anything about Visual Studio. Hope that's OK!

**Comment by varghesep** [comment]
Use the configuration value ```<TypeScriptCompileBlocked>true</TypeScriptCompileBlocked>``` in the project file to disable the typescript compilation of the ```ts``` files. There is no need to use the ```exclude``` settings as I mentioned in the original issue.
