### ISSUE TITLE
Webpack builds continuously, every <100 ms. 

### ISSUE THREAD

**Issue by AlexSerbanG** [aspnet/JavaScriptServices#1299]
I'm recently tried moving an app that I'm working on  using the reactRedux template to the newest template that uses webpack >2.5, typescript >2.4 and so on. I've had a lot of trouble migrating to the new (very) strongly typed restrictions. However, I finally managed to make sense of it all, with the exception of one thing. The webpack build task is running every few milliseconds, and very distracting to see the messages in the terminal, not to mention if there are errors at build. You can't stop it from endlessly scrolling so there's no way of telling what the error is unless it appears as an overlay in the browser. I took a printscreen of it but a GIF would have probably been able to transmit the discomfort it presents.
Is there a way to stop this and to only run it when it detects changes (on save)? Am i doing something wrong? 
![webpack](https://user-images.githubusercontent.com/26898164/30875651-d93b867c-a2fc-11e7-8f5f-003ee9e3d7f4.jpg)

In the console of the browser I'm getting the same behavior with messages like "[HMR] bundle rebuilding
client.js:204 [HMR] bundle rebuilt in 103ms" popping about 10/s. I'm starting to believe it might have something to do with the hot-module-reloader but I can't tell for sure.

**Comment by geirsagberg** [comment]
Make sure you are excluding `wwwroot` in your `tsconfig.json`.

**Comment by AlexSerbanG** [comment]
@geirsagberg , thank you for opening my eyes. It wasn't the wwwroot causing the problems, but the dist folder. However, your answer lead me to sorting it out. Thanks. I think we can close the issue now.

**Comment by SteveSandersonMS** [comment]
Thanks for explaining, @geirsagberg!

If this gets reported by others, we'll definitely look at excluding it by default. For now since nobody else seems to have hit this (and it certainly doesn't happen in the default setup) I think we are OK as is.

**Comment by DanHarman** [comment]
@SteveSandersonMS Another vote for excluding the wwwroot folder by default, as changing tsconfig to `"allowjs":true` causes this issue.
