### ISSUE TITLE
Webpack errors on Publish using Angular 4.2.5

### ISSUE THREAD

**Issue by bgauvey** [aspnet/JavaScriptServices#1303]
First off, I am not sure where to post this.  I created an app using the [primeng](https://github.com/primefaces/primeng/) components. In order to get the bootstrap, fontawesome and primeng themes running I ran `webpack --config webpack.config.vendor.js`  so that I could add the css files to the `nonTreeShakableModules` array.  Everything seems to work until I publish. 

When I attempt to publish I get the following error

`
ERROR in ./$$_gendir/~/primeng/components/menu/menu.ngfactory.ts
Module parse failed: .\$$_gendir\node_modules\primeng\components\menu\menu.ngfactory.ts Unexpected token (14:32)
You may need an appropriate loader to handle this file type.
| import * as i3 from '@angular/router';
| import * as i4 from 'primeng/components/dom/domhandler';
| export const MenuModuleNgFactory:i0.NgModuleFactory<i1.MenuModule> = i0.?cmf(i1.MenuModule,
|     ([] as any[]),(_l:any) => {
|       return i0.?mod([i0.?mpd(512,i0.ComponentFactoryResolver,i0.?CodegenComponentFactoryResolver,
 @ ./$$_gendir/ClientApp/app/components/locations/locations.component.ngfactory.ts 9:0-99
 @ ./$$_gendir/ClientApp/app/components/list/list.component.ngfactory.ts
 @ ./$$_gendir/ClientApp/app/app.module.server.ngfactory.ts
 @ ./ClientApp/boot.server.ts
`

**Comment by SteveSandersonMS** [comment]
This is an issue with using AoT compilation with primeng.

Could you please report this to the primeng project? Most likely they just need to give you updated installation instructions to explain what extra Webpack config is needed to make it work.

**Comment by bgauvey** [comment]
Resolved.  Issue #1293 is the solution.
