### ISSUE TITLE
Diagnostics for server side rendering (Angular in particular)q

### ISSUE THREAD

**Issue by pauloya** [aspnet/JavaScriptServices#1304]
What is the best practice for diagnosing problems with an angular app while being rendered on the server in production?
Is there a way to see what is written in the console, and is there a way to get the callstack of an exception just like I get on the browser?
I noticed that there is `NodeInstanceOutputLogger`, can this help getting more diagnostics? and is there an example of an implementation for an ILogger I could use?

Thanks

**Comment by davidsekar** [comment]
https://github.com/aspnet/JavaScriptServices/tree/dev/src/Microsoft.AspNetCore.SpaServices#debugging-your-javascripttypescript-code-when-it-runs-on-the-server

**Comment by pauloya** [comment]
I realize there is a debugging mechanism, and I'm getting an errors doing that on my local machine, so I couldn't try it out.
But the question refers to diagnosing problems in production, where we don't plan to attach a debugger.

**Comment by davidsekar** [comment]
> I'm getting an errors doing that on my local machine,
You will get issue if you are trying to debug with Node version 6.0 + .Net core 1.1. With Nodejs 8.x & .net core 2.0 it should work fine.

https://github.com/aspnet/JavaScriptServices/issues/1176
Well in azure, you can see all the output written/logged to console by turning on 'Diagnostics logs' and storing it in a blob (If required). For other platforms too should support redirecting output to a file.

Well for your question on NodeInstanceOutputLogger -> I'm interested to know more about it.

**Comment by pauloya** [comment]
@davidsekar thanks, I can see the console logs show up on the asp.net core logs.

**Comment by SteveSandersonMS** [comment]
Thanks for the answer @davidsekar!
