### ISSUE TITLE
Please help me use webpack with template

### ISSUE THREAD

**Issue by QuanHuynhM** [aspnet/JavaScriptServices#1305]
If I have a folder assets(include css file and js file) in folder ClientApp. Please help me. I want to use webpack to bundle all files in folder assets(css file and js file). But I don't know how to do it.

**Comment by SteveSandersonMS** [comment]
I'm afraid all I can suggest is to look at the Webpack documentation, as that already describes its usage in more detail than I could.

Note that if you're using the SPA templates that ship with ASP.NET Core 2.0 (for Angular, React, or React+Redux), you already have Webpack set up for you by default.
