### ISSUE TITLE
ng-recaptcha integration

### ISSUE THREAD

**Issue by NazirTemirov** [aspnet/JavaScriptServices#1309]
Hi. I use the ng-recaptcha (https://github.com/DethAriel/ng-recaptcha) module in my project,
I described my problem [here](https://github.com/DethAriel/ng-recaptcha/issues/64)

Maybe you know what's the matter. Why the behavior in the prod mode differs from the dev mode?

Thanks.

**Comment by SteveSandersonMS** [comment]
It's probably an AoT build issue that you can resolve following this step: https://github.com/aspnet/JavaScriptServices/issues/1168#issuecomment-320026397

If that doesn't fix it, please contact the ng-recaptcha maintainers for instructions on making it work with AoT compilation.
