### ISSUE TITLE
How to update the vendor package?

### ISSUE THREAD

**Issue by ManuelDeLeon** [aspnet/JavaScriptServices#131]
How can I update the vendor package? In my particular case I'm trying to add `dragula` and `ng2-dragula` to the vendor package (an Angular 2 project). Here's what I'm doing:

1. Added `dragula` and `ng2-dragula` to `package.json` `"dependencies"` section.
2. Added `dragula` and `ng2-dragula` to `webpack.config.vendor.js` `entry.vendor` array.
3. Added the dragula typings.
4. Added `import * as dragula from 'dragula';` and `console.log(dragula);` to a file.
5. Ran `webpack --configure webpack.config.vendor.js`

This is where I get confused because it doesn't create/update the vendor bundle, only the `main.js` one.

```
ts-loader: Using typescript@1.8.10 and C:\MyFiles\Angular\MCAngular\tsconfig.json
Hash: 81d70ace7cd2ee804915
Version: webpack 1.13.1
Time: 3116ms
  Asset    Size  Chunks             Chunk Names
main.js  356 kB       0  [emitted]  main
   [0] multi main 28 bytes {0} [built]
    + 34 hidden modules
```

And if I try to run it I get:

```
[Node] ReferenceError: document is not defined
[Node]     at Object.<anonymous> (C:\MyFiles\Angular\MCAngular\node_modules\custom-event\index.js:24:23)
[Node]     at Module._compile (module.js:541:32)
[Node]     at Object.Module._extensions..js (module.js:550:10)
[Node]     at Module.load (module.js:458:32)
[Node]     at tryModuleLoad (module.js:417:12)
[Node]     at Function.Module._load (module.js:409:3)
[Node]     at Module.require (module.js:468:17)
[Node]     at require (internal/module.js:20:19)
[Node]     at Object.<anonymous> (C:\MyFiles\Angular\MCAngular\node_modules\crossvent\src\crossvent.js:3:19)
[Node]     at Module._compile (module.js:541:32)
```

It would be nice to know how to add something to the vendor module (like dragula), it would be even better to understand what's going on here.

Thanks for the help.

**Comment by laskoviymishka** [comment]
This error acure when you run prerendered app? Try to switch off server rendering. 
According to error message it looks like `ng2-dragula` not support server render, since it operate directly to document object (which not exist in node run process).

**Comment by ManuelDeLeon** [comment]
Thanks @laskoviymishka that takes care of the `document is not defined` problem (it's easy to forget you're doing SSR).

Now how do I add a library to the vendor?

**Comment by laskoviymishka** [comment]
Your steps should work well. After made them new vendor entry should be presented

**Comment by ManuelDeLeon** [comment]
It doesn't work. These are the steps with a new app:

```
test5> yo aspnetcore-spa

(Select Angular 2)
```

Add the following to dependencies in package.json

```
"dragula": "^3.7.1",
"ng2-dragula": "^1.1.10"
```

Run: `npm install`

Add the following to webpack.config.vendor.js entry.vendor array.

```
'dragula',
'ng2-dragula'
```

Add `import * as dragula from 'dragula';` and `console.log(dragula);` to the home.ts file.

Run: `webpack --configure webpack.config.vendor.js`

vendor.js isn't updated (main.js is):

```
ts-loader: Using typescript@1.8.10 and C:\MyFiles\Angular\test5\tsconfig.json
Hash: bb924dbe880056dd7b03
Version: webpack 1.13.1
Time: 3671ms
     Asset     Size  Chunks             Chunk Names
   main.js   351 kB       0  [emitted]  main
styles.css  1.69 kB       0  [emitted]  main
   [0] multi main 28 bytes {0} [built]
    + 34 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
		
```

**Comment by SteveSandersonMS** [comment]
You should execute:

    webpack --config webpack.config.vendor.js

(it's `--config`, not `--configure`)

**Comment by ManuelDeLeon** [comment]
Ouch! Thanks, that solves that part. Now the error is:

```
Hash: a11bbffa3895c58c3f2a
Version: webpack 1.13.1
Time: 4134ms
                               Asset     Size  Chunks             Chunk Names
89889688147bd7575d6327160d64e760.svg   109 kB          [emitted]
                           vendor.js  2.85 MB       0  [emitted]  vendor
                          vendor.css   316 kB       0  [emitted]  vendor
   [0] dll vendor 12 bytes {0} [built] [1 error]
    + 423 hidden modules

ERROR in dll vendor
Module not found: Error: Cannot resolve module 'ng2-dragula' in C:\MyFiles\Angular\MCAngular
 @ dll vendor
Child extract-text-webpack-plugin:
        + 7 hidden modules
```

The ng2-dragula docs say for a webpack project you just run `npm install ng2-dragula dragula --save` then import as usual `import {DragulaService, Dragula} from 'ng2-dragula/ng2-dragula';` (end of the page https://github.com/valor-software/ng2-dragula/wiki)

What am I missing?

**Comment by SteveSandersonMS** [comment]
Not sure, maybe you need `.d.ts` files if you're using TypeScript, or it could be something else specific to `ng2-dragula`. I'll close this as it's clear now it's not an JavaScriptServices bug.

**Comment by ManuelDeLeon** [comment]
k, thxs

**Comment by ManuelDeLeon** [comment]
Thanks again SteveSandersonMS and laskoviymishka, I know how frustrating it must be to receive tickets like this (which isn't your problem in the end).

For anyone who comes across an issue like this (`Module not found: Error: Cannot resolve module`). The problem is that the entries section of a Webpack config file receives the module you're importing from, not the name of the npm package.

In my case I have the package named `ng2-dragula` which is used like this:

```js
import {DragulaService, Dragula} from 'ng2-dragula/ng2-dragula';
```

So the config entry is `'ng2-dragula/ng2-dragula'` just like in the import statement:

```js
module.exports = {
    entry: {
        vendor: [
            'dragula',
            'ng2-dragula/ng2-dragula',
            ...
```
