### ISSUE TITLE
How to update Angular Version to latest 

### ISSUE THREAD

**Issue by noumanbhatti** [aspnet/JavaScriptServices#1313]
Currently package.json is pointing to 4.2.5 version of angular libraries. how do I update them to latest ?

**Comment by jrmcdona** [comment]
Update package.json and change 4.2.5 to the version you want.  I am running 4.3.6 for example.  Then save the file.

Then delete your node_modules folder.  Then run "npm install"

That is all.  That is just the standard stuff.

**Comment by noumanbhatti** [comment]
Thanks.. but it gives me this error 

https://github.com/aspnet/JavaScriptServices/issues/1242

Which I'm trying to fix by following what is mentioned here
https://github.com/aspnet/Templates/issues/866

**Comment by jrmcdona** [comment]
@noumanbhatti what files are you adding?

Send me your repo and I will clone and run it and let you know what needs to be fixed.
