### ISSUE TITLE
[Request] Support FuseBox

### ISSUE THREAD

**Issue by HamedFathi** [aspnet/JavaScriptServices#1315]
> FuseBox is a bundler/module loader with super powers - Blazing speed, simplicity, and ultimate flexibility.

Can we use [FuseBox](http://fuse-box.org/) with your awesome library? specially HMR.

**Comment by SteveSandersonMS** [comment]
There's no current plan to add any special support for this (and I've never even heard of FuseBox before your post), but you might be able to find a way of doing that yourself.

If somehow this third-party product ends up getting popular enough to rival Webpack we might consider adding something specific for it.
