### ISSUE TITLE
Update to React 16 and consider new SSR features (e.g., streaming)

### ISSUE THREAD

**Issue by rosieks** [aspnet/JavaScriptServices#1316]
React 16 introduced some improvements to SSR: https://hackernoon.com/whats-new-with-server-side-rendering-in-react-16-9b0d78585d67

One is support for streaming. Are you considering adding support for that to improve load time of the page?

**Comment by SteveSandersonMS** [comment]
Thanks for the idea. When we update the template to React 16 as part of the ASP.NET 2.1 update, we'll look at whatever improvements make sense to incorporate. I don't know specifically about the streaming feature but if it does fit into the architecture cleanly then it's definitely worth considering.

I'm going to leave this issue open (with a modified title) to track any notes about React 16 updates, if that's OK!

**Comment by SteveSandersonMS** [comment]
The current plan is that we'll get the React 16 upgrade as part of moving to a new create-react-app based template. This plan is better described by #997 so I'm closing this issue in favour of that one.
