### ISSUE TITLE
Server Side Render Specific Routes

### ISSUE THREAD

**Issue by bob19831** [aspnet/JavaScriptServices#1318]
If I have a single react app, is it possible to server side render specific routes and ignore others?

My use case is to server side render marketing pages for SEO, but exclude all routes that require authentication (i.e. all interactive parts of app).

**Comment by SteveSandersonMS** [comment]
In your `boot-server.tsx` file, you can put whatever logic you want to control what prerendering does. For example, you could look at the incoming `params.url`, and if it's something you don't want to prerender, just resolve the promise with an empty HTML string (e.g., `resolve({ html: '' })`).
