### ISSUE TITLE
pwa polymer templates in visual studio 2017

### ISSUE THREAD

**Issue by touseefbsb** [aspnet/JavaScriptServices#1320]
A suggestion I wanted to provide to asp.net core team. I am not sure who exactly will be responsible to create a polymer template for visual studio 2017. So I have requested visual studio team as well for this and now I am requesting the feature here to the asp.net core team.

Polymer and web components play main role in creating awesome progressive web apps. 
Visual Studio 2017 should integrate with Polymer to give it the templates already present in polymer-cli. 
Also ASP.NET CORE 2.0 already has templates with angular and react, polymer should also have templates with asp.net core 2 with pwa stuff included like service worker e.t.c. 

**Reason to use VS 2017 templates**
1. easy deployment to azure and other services
2. easy integration with multiple types of identity providers including **Azure AD B2C** which supports email sign up, and all social sign ups along with password reset easily.
3. awesome intellisense and brilliant development experience.

**Reason to use polymer**
1. Future of web development is **web components** and polymer is probably best tool to make them.
2. polymer also provides brilliant support for pwas.
3. Those who don't want to use heavy frameworks like angular, vue and react e.t.c, should use polymer because it is simpler and is able to give us a perfect pwa which can run on probably every device possible.

**So if we combine polymer with VS 2017 it will be a perfect environment for future of web development.**

P.S : here is the link of my request on visual studio user voice, please go to this link and vote the idea if you like it.

https://visualstudio.uservoice.com/forums/121579-visual-studio-ide/suggestions/31776661-pwa-template-for-polymer-2-and-3-with-asp-net-core

Thanks.

**Comment by SteveSandersonMS** [comment]
Thanks for posting!

We'll keep this in mind and will see how much more customer demand there is for this over time. I'm glad you also posted on uservoice as that's a better place for gauging overall demand over time.

**Comment by CminCode** [comment]
did this happen. How are you suppose to gauge demand if you close the thread.

**Comment by JohnGalt1717** [comment]
Is there support for: sw-precache-webpack-plugin or other ways of putting in service workers? Anyone done it?  I'm looking for ways of enabling PWA support which I would think MS would be pushing given the sorry state of the Windows store and PWAs being the last hope.

So any guidance on how to add Service workers to Angular with Webpack would be great. (not angular-cli)
