### ISSUE TITLE
Calling an action from another action in a redux store

### ISSUE THREAD

**Issue by AndyCJ** [aspnet/JavaScriptServices#1321]
I'm sorry if this is the wrong place for this, I had a look at the README.md but I didn't see anything about issue creation rules.

I have a simple store, and I want to call one action from another action:

I check the [redux documentation](http://redux.js.org/docs/basics/Actions.html#action-creators) and it seemed straight forward enough.

    dispatch(addTodo(text))

Here's a minimal repro of what I thought should work:

    import { AppThunkAction } from "./";

    enum ActionTypes { CreateRequest = "CREATE_REQUEST", CreateReceive = "CREATE_RECEIVE", LoadRequest = "LOAD_REQUEST", LoadReceive = "LOAD_RECEIVE" }
    
    interface CreateRequestAction { type: ActionTypes.CreateRequest; }
    interface CreateReceiveAction { type: ActionTypes.CreateReceive; }
    interface LoadRequestAction { type: ActionTypes.LoadRequest; }
    interface LoadReceiveAction { type: ActionTypes.LoadReceive; data: any }
    
    type KnownAction = CreateRequestAction | CreateReceiveAction | LoadRequestAction | LoadReceiveAction;
    
    export const actionCreators = {
        createProperty: (newItem: any): (AppThunkAction<KnownAction>) => (dispatch, getState) => {
            //Pretend to do something
            setTimeout(() => {
                dispatch({
                    type: ActionTypes.CreateReceive
                });
    
                //This produces an error: Error	TS2345	(TS) Argument of type 'AppThunkAction<KnownAction>' is not assignable to parameter of type 'KnownAction'
                dispatch(actionCreators.load());
            }, 1000);
    
            dispatch({
                type: ActionTypes.CreateRequest
            });
        },
        load: (): (AppThunkAction<KnownAction>) => (dispatch, getState) => {
            //Pretend to do something
            setTimeout(() => {
                dispatch({
                    type: ActionTypes.LoadReceive,
                    data: []
                });
            }, 1000);
    
            dispatch({
                type: ActionTypes.LoadRequest
            });
        },
    };

Which produces the error:

> Error	TS2345	(TS) Argument of type 'AppThunkAction<KnownAction>' is not assignable to parameter of type 'KnownAction'.
>   Type 'AppThunkAction<KnownAction>' is not assignable to type 'LoadReceiveAction'.
>     Property 'type' is missing in type 'AppThunkAction<KnownAction>'.

So it seems that the `AppThunkAction<KnownAction>` typing is not permissive enough to allow the call as shown.

This issue can be worked around by casting dispatch to any:

    const untypedDispath = <any>dispatch;
    untypedDispath(actionCreators.load());

But it'd be nice to have a typed solution.

**Comment by SteveSandersonMS** [comment]
I agree, it would be nice to have a typed solution! If you can figure out how the type definitions in @types/react-redux (or similar) should be updated to support this usage pattern, would you be able to submit an issue or PR to the @types project?

**Comment by jonorogers** [comment]
I just ran into the same issue. I think it's the typing of AppThunkAction. I changed it to the following and it worked:

```
export interface AppThunkAction<TAction> {
    (dispatch: (action: TAction | AppThunkAction<TAction>) => void, getState: () => ApplicationState): void;
}
```

Note the only change is changing dispatch's accepted action type from `TAction` to `TAction | AppThunkAction<TAction>`

**Comment by AndyCJ** [comment]
I ended up changing my approach so this was no longer an issue (for me personally).

I was trying to have data for multiple Stores loaded up in a single request, a reasonable goal.

The idea being I'd have one actionCreator which loaded the data, then it'd call other actionCreators passing in the data so they can directly update their respective Stores without further network trips.

I realized that a better approach would be to have a single actionCreator, which dispatches an action that reducers from multiple stores watch for and act upon.

This removes the problem I described above, results in less actions "flying around", and frankly feels a more correct/more redux-y way of doing things.

There was a similar requirement for cross-store typing in the reducers.

I handled that by bundling the action interfaces for each store in to an ActionInterfaces namespace which could then be easily referenced from other stores.

**PropertyStore**

    export enum ActionTypes {
        LoadPropertyRequest = "PROPERTY_LOAD_PROPERTY_REQUEST",
        LoadPropertyReceive = "PROPERTY_LOAD_PROPERTY_RECEIVE",
    }
    
    export namespace ActionInterfaces {
        export interface LoadPropertyRequestAction {
            type: ActionTypes.LoadPropertyRequest;
        }
    
        export interface LoadPropertyReceiveAction {
            type: ActionTypes.LoadPropertyReceive;
            property: Models.Property.Property;
            projects: Models.Project.Project[];
        }
    }

    export const reducer: Redux.Reducer<State> = (state: State, incomingAction: Redux.Action) => {
        const action = incomingAction as KnownAction;
    
        switch (action.type) {
            case ActionTypes.LoadPropertyRequest:
                return {
                    ...state,
                    isLoading: true
                };
    
            case ActionTypes.LoadPropertyReceive:
                return {
                    ...state,
                    isLoading: false,
                    properties: [action.property]
                };
    

            default:
                // The following line guarantees that every action in the KnownAction union has been covered by a case above
                const exhaustiveCheck: never = action;
        }
    
        return {
            ...unloadedState,
            ...state
        };
    };

**ProjectStore**

    import * as PropertyStore from "./property";

    export const reducer: Redux.Reducer<State> = (state: State, incomingAction: Redux.Action) => {
        const action = incomingAction as KnownAction
            | PropertyStore.ActionInterfaces.LoadPropertyReceiveAction;
    
        switch (action.type) {
            case ActionTypes.LoadProjectsWithChildrenReceive:
            case PropertyStore.ActionTypes.LoadPropertyReceive:
                return {
                    ...state,
                    isLoading: false,
                    projects: action.projects
                };
    
            default:
                // The following line guarantees that every action in the KnownAction union has been covered by a case above
                const exhaustiveCheck: never = action;
        }
    
        return {
            ...unloadedState,
            ...state
        };
    };
