### ISSUE TITLE
Can not debug with server-side prerendering

### ISSUE THREAD

**Issue by sakataa** [aspnet/JavaScriptServices#1323]
I want to debug boot-server.tsx but can not see original source code for debugging. I follow by docs here: https://github.com/aspnet/JavaScriptServices/tree/dev/src/Microsoft.AspNetCore.SpaServices#debugging-your-javascripttypescript-code-when-it-runs-on-the-server

Could everyone help me?
![image](https://user-images.githubusercontent.com/14236769/31286839-a0580bec-aae9-11e7-9628-5ddacc105cc9.png)

**Comment by SteveSandersonMS** [comment]
If you look in your `webpack.config.js`, you'll probably find that `SourceMapDevToolPlugin` is only used in the `clientBundleConfig` and not in the `serverBundleConfig`. It might be sufficent to add `SourceMapDevToolPlugin` to your `serverBundleConfig` too.

**Comment by sakataa** [comment]
hi @SteveSandersonMS, thank for you response.
But I still get original source when debugging. I configured devtool: 'source-map' in webpack config and use reactredux template.
Could you please help me?
