### ISSUE TITLE
updating package json

### ISSUE THREAD

**Issue by klanglie** [aspnet/JavaScriptServices#1325]
I tried to update package.json by running the npm-check-updates tool (aka ncu -a) and now the task runner fails when trying to install or run the development task.

I have tried rolling the package.json file back and deleting node_modules and so far still failure. The template is neat, but seems delicate.

My question is, what is the best way to update the package.json file with latest packages for all. Or are some packages, such as the one made by the team, have dependencies that cannot be updated?

**Comment by brycekmartin** [comment]
You can update the package version numbers in the package.json and then run npm install --save using the  node command line in that directory.  You will probably need to make sure that you run the command line as Administrator.

**Comment by StevenTCramer** [comment]
> My question is, what is the best way to update the package.json file with latest packages for all?

I think this is the key point.  The template comes with no tests and updating is a crap shoot.  Sure you can update the packages in package.json but it will likely break the app.  Try updating to React 16 and it won't even compile.  You can't even update some of the @types a single version.  What if you want to use the latest webpack?

We need a strategy for this and a tool would be even better.

Running npm outdated or yarn outdated right now lists the following:
```
λ npm outdated
Package                            Current         Wanted   Latest  Location
@types/react                       15.0.35        15.0.35  16.0.10  tempProject
@types/react-dom                    15.5.1         15.5.1   16.0.1  tempProject
@types/react-hot-loader              3.0.3          3.0.3    3.0.4  tempProject
@types/react-redux                  4.4.45         4.4.45   5.0.10  tempProject
@types/react-router                 4.0.12         4.0.12   4.0.15  tempProject
@types/react-router-dom              4.0.5          4.0.5    4.0.8  tempProject
@types/react-router-redux            5.0.3          5.0.3    5.0.8  tempProject
@types/webpack                      2.2.15         2.2.15   3.0.13  tempProject
@types/webpack-env                  1.13.0         1.13.0   1.13.1  tempProject
awesome-typescript-loader            3.2.1          3.2.1    3.2.3  tempProject
css-loader                          0.28.4         0.28.4   0.28.7  tempProject
event-source-polyfill                0.0.9          0.0.9   0.0.10  tempProject
extract-text-webpack-plugin          2.1.2          2.1.2    3.0.1  tempProject
file-loader                         0.11.2         0.11.2    1.1.5  tempProject
history                              4.6.3          4.6.3    4.7.2  tempProject
json-loader                          0.5.4          0.5.4    0.5.7  tempProject
react                               15.6.1         15.6.1   16.0.0  tempProject
react-dom                           15.6.1         15.6.1   16.0.0  tempProject
react-hot-loader              3.0.0-beta.7   3.0.0-beta.7    1.3.1  tempProject
react-redux                          5.0.5          5.0.5    5.0.6  tempProject
react-router-dom                     4.1.1          4.1.1    4.2.2  tempProject
react-router-redux           5.0.0-alpha.6  5.0.0-alpha.6    4.0.8  tempProject
redux                                3.7.1          3.7.1    3.7.2  tempProject
style-loader                        0.18.2         0.18.2   0.19.0  tempProject
typescript                           2.4.1          2.4.1    2.5.3  tempProject
url-loader                           0.5.9          0.5.9    0.6.2  tempProject
webpack                              2.5.1          2.5.1    3.6.0  tempProject
webpack-hot-middleware              2.18.2         2.18.2   2.19.1  tempProject
```

**Comment by klanglie** [comment]
@StevenTCramer - My thoughts exactly. Until the template and its dependencies can be updated separately, this project is really only a neat example of what is possible. Otherwise not too practical or cutting edge. For now I have seperated my AspNetCore Web API from the front-end using a starter package. I think I am using this one: https://github.com/angularclass/angular-starter .It did allow me to update all packages using npm check updates.

**Comment by SteveSandersonMS** [comment]
You can update your third-party dependencies at any time, but if newer versions introduce breaking changes, you would have to find solutions or not update those packages. I know it would be better if third-party packages never introduced breaking changes, but that's not something any of us can control I'm afraid! Sorry it's not easier.
