### ISSUE TITLE
ERROR in ./ClientApp/boot.server.ts Module not found : error : Can't resolve './../$$_gendir/ClientApp/app/app.module.server.ngfactory'

### ISSUE THREAD

**Issue by rahulsahay19** [aspnet/JavaScriptServices#1329]
Hi Team,

While publishing the app using dotnet publish command. Its failing with below reason. 

"ERROR in Could not resolve "D:\Rahul\MyExperiments\angular-4-apps\ReimbursementApp\ReimbursementApp\ClientApp\app\app.module.server" from "D:\Rahul\MyExperiments\angular-4-apps\ReimbursementApp\ReimbursementApp\ClientApp\app\app.module.server".

      ERROR in ./ClientApp/boot.server.ts
Module not found : error : Can't resolve './../$$_gendir/ClientApp/app/app.module.server.ngfactory' in 'D:\Rahul\MyExperiments\angular-4-apps\ReimbursementApp\ReimbursementApp\ClientApp' [D:\Rahul\MyExperiments\angular-4-apps\ReimbursementApp\ReimbursementApp\ReimbursementApp.csproj]"

I have attached the screenshot for the same.  I am using latest ASP.NET Core 2 template using angular. On local, everything is fine. While publishing only, its giving issue.

![3rd](https://user-images.githubusercontent.com/3886381/31331439-eb79bc7a-acff-11e7-9a9d-8714bfbbce7f.png)

You can also refer repo here:- https://github.com/rahulsahay19/ExpenseReview

Thanks,
Rahul

**Comment by davidsekar** [comment]
You can check the change mentioned in following comment 
https://github.com/aspnet/JavaScriptServices/issues/1293#issuecomment-331145362

**Comment by SteveSandersonMS** [comment]
Thanks for the answer @davidsekar!
