### ISSUE TITLE
Boosting performance of dev experience

### ISSUE THREAD

**Issue by cveld** [aspnet/JavaScriptServices#1334]
Currently if one presses F5 a couple of things happen before the app is really launched:
* msbuild builds the c# code
* a new browser is kicked off
* the browser fires an httprequest towards our serverside stack
* Our ASP.NET app gets bootstrapped
* SPA middleware gets bootstrapped
* an httpresponse gets back to the server
* the SPA gets bootstrapped
* the SPA is ready to use

As we currently look at it, this is not the optimal way the process would go: as every time a change to the .NET stack occurs the whole stuff gets teared down and everything happens all over again.

Our wish is that this gets optimized:
* the Angular-cli / webpack watch in memory cache should stay up and running
* the browser instance should stay up and running
* the .NET part should just get recompiled and hot swapped

At this point the javascript services middleware is simply too slow for us to apply in our dev workflow. For the time being we have to stick to regular Angular-cli / webpack watch commands through npm scripts / npm task runner plugin / commandline.

**Comment by SteveSandersonMS** [comment]
As part of the new Angular CLI-based project template, we're planning a "proxy-only" dev middleware mode that will let you manually run your own instance of Angular CLI server in the background as a separate process. This should cover the scenario you're describing.
