### ISSUE TITLE
Can't add new components / Angular and Net core

### ISSUE THREAD

**Issue by mausinc** [aspnet/JavaScriptServices#1336]
Hi,
Thanks for creating these templates to work with. Really awesome.
I have added this to an existing project. When i makes changes in the default files (counter.component.ts for example), all recompile and reloads the browsers. All worked well untill i added a new component. This does not work/recompile. 
I took the same steps with a new angular project using vs 2017. This works well.
What steps should i take to recompile everything when debugging in VS?

I know this is not really an issue, but i think this would help a lot of people trying to add this to an existing project.

**Comment by SteveSandersonMS** [comment]
I'm afraid I don't know what's different about your existing project that makes it not have the same functionality as the template. If you manage to track this down and think there are any issues in the code or docs in this repo that could have made it better, please let us know!

**Comment by mausinc** [comment]
This can be deleted. I fixed it.
