### ISSUE TITLE
Require and load images dynamically

### ISSUE THREAD

**Issue by azexpert** [aspnet/JavaScriptServices#1338]
Hi Team, 

I've got a large list of images to load dynamically

In component:
`
export class CardComponent {
    @Input() card: Card;
}
`

In html I want to do something like:
`
<img class="card-img-top" [src]="getUrl(card.imagePath)">
`

Card objects are loaded at request from a web api so the path is unknown upfront. 

I looked at the  #552 but there all references are to static image paths. Those you can get webpack to load with require(). However you cannot do require( 'this.gets.value.at.runtime' ).

What is the best and lightweight approach to load the images dynamically? How is it done with Webpack or should the Webpack be dropped altogether and the images be served from the wwwroot? 

Please advise. Ta!

**Comment by azexpert** [comment]
Huh... I found a working solution:
```
    getUrl(imagePath: string) {
        const imagesContext = require.context("../../assets/img", false); 
        return imagesContext(`./${imagePath}`);
    }
```
However I am still unsure if this is the best way to go.. 

Basically this approach pollutes the /dist root with the whole large list of images in a funky guid-like format:

dist/
├── fb112428a021413496882b0962e5bfc4.png
├── fdf360298d03161505a8145e89d20386.png

Please advise :)

**Comment by SteveSandersonMS** [comment]
Glad you got a solution. For other Webpack-specific questions, you might get a better result by asking the Webpack community. Hope that's OK!
