### ISSUE TITLE
PrimeNG Schedule

### ISSUE THREAD

**Issue by albrookesplowman** [aspnet/JavaScriptServices#1339]
Hi, I am trying to integrate the primeNG schedule component into the Angular 4 template but am struggling to work out what to put where so that it works successfully.  I understand that it relies on FullCalendar and moment so I have included these into the package.json file but I am struggling with what to import where so that it all works together.

Are you able to provide an example

Many thanks

Alan

**Comment by SteveSandersonMS** [comment]
Sorry, in general this issue tracker isn't the best place for support with third-party components. Could you please direct your question to the primeNG community? Thanks!
