### ISSUE TITLE
Cache server generated html - Angular

### ISSUE THREAD

**Issue by HenkeQuest** [aspnet/JavaScriptServices#1340]
Hi.
When my app is generating on server it takes 2-3 sec and it is to long time... Is it possible to cache the generated html from Angular-Universal?

In my case all the generated html from server is pretty much static so it's generating the same content for every one thats visiting my site. Of course it is different from page to page...

It there a best practice to speed up server-rendering?

**Comment by MarkPieszak** [comment]
Do you have API calls that are taking a while to finish? That's usually the biggest culprit in slow renderings, because otherwise it should be almost instant (assuming no API calls).

**Comment by HenkeQuest** [comment]
Thanks for your response. Yes, I have some API calls. But I turns them off if not in browser (return empty object if on server).

**Comment by SteveSandersonMS** [comment]
@HenkeQuest Please see the [cache tag helper](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/built-in/cache-tag-helper). You can wrap that around the HTML element that has the `asp-prerender-module` tag helper in your `Index.cshtml` file.

**Comment by HenkeQuest** [comment]
Thanks @SteveSandersonMS .
I will look into that! It looks like what I need.

**Comment by kevindqc** [comment]
@SteveSandersonMS Is there a way to cache the result with the new angular-cli based template in Microsoft.DotNet.Web.Spa.ProjectTemplates::2.0.0? 

If not, what do you think would be a good approach?

For now I'm thinking of just returning cache headers (either by adding a new middleware after the call to `app.UseSpa` or by pre-rendering myself similar to the code shown in #1423) and putting a CDN in front of .net core and let the CDN handle the caching.
