### ISSUE TITLE
source maps not working when debugging in node for templates with server-side prerendering

### ISSUE THREAD

**Issue by derekdavenport** [aspnet/JavaScriptServices#1342]
If you use `dotnet new` to create a new project with server-side prerendering (react-redux and angular), then [follow the instructions here](https://github.com/aspnet/JavaScriptServices/tree/dev/src/Microsoft.AspNetCore.SpaServices#debugging-your-javascripttypescript-code-when-it-runs-on-the-server), then open Chrome Devtools for Node.js, there is no "`webpack://` entry in the sidebar".

![image](https://user-images.githubusercontent.com/11248772/31645769-d73d06d2-b2cb-11e7-98cd-98b5b8ef4a69.png)

The transpiled js is listed under "(no domain)", and debugging that does work.

Trying to set breakpoints in Visual Studio 2017 says

> The breakpoint will not currently be hit. No symbols have been loaded for this document.

What do I need to do to be able to debug/set break points in the TypeScript in VS or Devtools? I'm using Node 8.7

**Comment by rosieks** [comment]
Take a look at this: https://github.com/aspnet/JavaScriptServices/pull/1003

**Comment by derekdavenport** [comment]
@rosieks That's for stack traces only tho? I tried it anyway, and it had no effect on debugging. For stack traces, they only ever show a NodeInvocationException in Microsoft.AspNetCore.NodeServices. I've never seen it stack trace the JS in the first place.

But back to debugging, any idea on what the problem might be? I've tried everything I can think of in tsconfig.json and webpack.config.js. Everything looks to be configured correctly out of the box, but it doesn't work. Did it used to work? Maybe some new version of something broke it? Downgrade Node? I tried Node 6.11, but that didn't work.

**Comment by apawsey** [comment]
I don't believe the node debugging is starting correctly...? Unless I have misunderstood this completely, which is entirely possible :smile:

I create a new angular project.  Add the following code:
```
services.AddNodeServices(options => {
                options.LaunchWithDebugging = true;
                options.DebuggingPort = 9229;
            });
```
But I cannot connect anything to port 9229... and now checking tcpview, there is nothing listening on that port.  I also can't find any debug/stdout/console messages regarding this debugging started, as is mentioned in the docs.

Have I misunderstood, or is something not working here?

**Comment by SteveSandersonMS** [comment]
Since this has also been reported as #1358, and that issue also covers updating docs, I'll close this one so there's a single issue tracking the requirement.
