### ISSUE TITLE
redirect to home while refreshing browser with URL pointing to child route

### ISSUE THREAD

**Issue by Jake-He** [aspnet/JavaScriptServices#1343]
redirect to home while refreshing browser with URL pointing to child route

Ex:  
At URL: https://localhost:44342/books (at client route - books, no controller - books at server side).
User clicks reload to refresh the browser. 
Page needs to be redirected to home since it depends store data in home to be populated first.

**Comment by SteveSandersonMS** [comment]
If your goal is to add some custom logic that causes a redirection while the page is first loading, you could put this into your `boot-client.ts` file, since that only executes during the initial startup, and not on subsequent client-side navigation events.
