### ISSUE TITLE
How to use Watch mode

### ISSUE THREAD

**Issue by RehanSaeed** [aspnet/JavaScriptServices#1345]
I'd like to execute some sort of watch command, so that any time I change a C# file, dotnet watch kicks in and restarts Kestrel and any time I change some web file, webpack watch kicks in and does HMR. 

Since we have `dotnet watch` and two webpack config files, how can this be achieved?

**Comment by SteveSandersonMS** [comment]
`dotnet watch` will work fine to restart the app when you change C# code. Plus when you're running in development mode, Webpack will automatically rebuild and push your changes into the browser.
