### ISSUE TITLE
Visual Studio 2017 template does not honor app.css file changes

### ISSUE THREAD

**Issue by fashaikh** [aspnet/JavaScriptServices#1346]
Here is a sample application I created using the .net core + Angular template in Visual Studio2107 15.4 .
https://github.com/fashaikh/webapplication1/blob/master/WebApplication1/ClientApp/app/components/app/app.component.css

Any changes I make in the css files dont reflect in the rendered app.
They get pushed in the `main-client.js` file as an export, however seem to have no effect in how the app is rendered.

Is there something I am missing ?

![image](https://user-images.githubusercontent.com/2650941/31738188-aed47eee-b3fe-11e7-903a-3d4ed3cbcaab.png)

![image](https://user-images.githubusercontent.com/2650941/31738303-0c4ac650-b3ff-11e7-8706-0904f534e5b6.png)

**Comment by SteveSandersonMS** [comment]
I ran your sample project, and the CSS changes were applied (both on the original page load, and when making subsequent edits). Is it possible that you just had your window open wider than 400px, causing the media query to exclude your CSS?

Closing as it appears to be working correctly, but please post further repro steps if you still think there's a problem. Thanks.

**Comment by fashaikh** [comment]
I had tried all widths. Also the `1000px` padding wouldnt reflect.
The vendor.js gets updated but the browser both Chrome (61.0.3163.100 (Official Build) (64-bit)
) and Edge  (Microsoft EdgeHTML 15.15063) wouldnt show classes in the dom explorer or render them

**Comment by SteveSandersonMS** [comment]
I'm not sure why you didn't see the CSS affecting the rendering in the browser - it did work correctly when I tried your repro case. If you manage to track down more details of something being wrong in your case, and you believe it's due to a defect in this repo, please let us know!
