### ISSUE TITLE
HMR does not work when setup a ContractResolver in JsonConvert.DefaultSettings

### ISSUE THREAD

**Issue by VSDekar** [aspnet/JavaScriptServices#1347]
When i setup a Contract Resolver in the ConfigureServices Method like this:

```csharp
public void ConfigureServices(IServiceCollection services)
        {
            JsonConvert.DefaultSettings = () => new JsonSerializerSettings() {
                PreserveReferencesHandling = PreserveReferencesHandling.Objects,
                ContractResolver = new CamelCasePropertyNamesContractResolver(),
                NullValueHandling = NullValueHandling.Ignore
            };
            
            ...
        }

public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
                app.UseWebpackDevMiddleware(new WebpackDevMiddlewareOptions() {
                    HotModuleReplacement = true
                });                
            }
            ...
        }
```

The webpack compilation will not be triggered after the server starded his work.

```
Multitool> dotnet run
Using launch settings from C:\Users\RemoFischer\Documents\Visual Studio 2017\Projects\Multitool\Multitool\Properties\launchSettings.json...
info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
      User profile is available. Using 'C:\Users\RemoFischer\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
Hosting environment: Development
Content root path: C:\Users\RemoFischer\Documents\Visual Studio 2017\Projects\Multitool\Multitool
Now listening on: http://localhost:22222
Application started. Press Ctrl+C to shut down.
```

When removing `ContractResolver`
```
Multitool> dotnet run
Using launch settings from C:\Users\RemoFischer\Documents\Visual Studio 2017\Projects\Multitool\Multitool\Properties\launchSettings.json...
info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
      User profile is available. Using 'C:\Users\RemoFischer\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
Hosting environment: Development
Content root path: C:\Users\RemoFischer\Documents\Visual Studio 2017\Projects\Multitool\Multitool
Now listening on: http://localhost:22222
Application started. Press Ctrl+C to shut down.
info: Microsoft.AspNetCore.NodeServices[0]
      webpack built 04e15700b1b5542a65d1 in 4867ms
```

Of course i can workaround this issue, but it would be nice if the library could fix this by using their own JsonSerializerSettings.

**Comment by VSDekar** [comment]
Oh i see there was already an issue https://github.com/aspnet/JavaScriptServices/issues/688 but it was closed without further action.

**Comment by SteveSandersonMS** [comment]
@VSDekar Thanks for reporting this.

#688 was closed because we did implement it (see https://github.com/aspnet/JavaScriptServices/commit/d6ae8829b6c27b2306dc683017ecb7ba3483450c) - it does override the serialization settings, and hence no longer has the issue described in #688 based on the repro we were working with.

What you've found however is a different way of triggering the problem, which we should also fix.

**Comment by VSDekar** [comment]
@SteveSandersonMS I took a look into the source and i think https://github.com/aspnet/JavaScriptServices/commit/d6ae8829b6c27b2306dc683017ecb7ba3483450c did already solve this issue as well. (I was not able to repro my issue with the actual dev branch)

Sorry for the naive question, but how do i update my project to use the version of SpaServices with the fix applied?

**Comment by SteveSandersonMS** [comment]
Aha, thanks for clarifying. In that case this issue is already fixed, so I'll close it.

> Sorry for the naive question, but how do i update my project to use the version of SpaServices with the fix applied?

Generally speaking you need to wait for ASP.NET Core to deliver a new release. I believe the next patch will be 2.0.2 I'm not sure when exactly it will ship.
