### ISSUE TITLE
Blank page after removing asp-prerender

### ISSUE THREAD

**Issue by intermension** [aspnet/JavaScriptServices#1349]
I've seen it mentioned multiple times that "all you have to do" to turn off server side rendering in SPA templates and still have a functional site is to replace

`<app asp-prerender-module="ClientApp/dist/main-server">Loading...</app>`

with 

`<app>Loading...</app>`

I've done this and it breaks - rendering only a blank page. The page has some markup in it but clearly Angular 2 has not been properly booted. 

Is this broken or do we need to do something in addition to removing that attribute?

**Comment by SteveSandersonMS** [comment]
If your client-side rendering is working correctly, then you can disable server-side rendering by removing the `asp-prerender-module` tag helper like you've described.

If, after removing this, you're just getting a blank page, that suggests your client-side rendering was already broken for some reason. Please check the browser console for error information.
