### ISSUE TITLE
Special Characters don't work

### ISSUE THREAD

**Issue by doczoidberg** [aspnet/JavaScriptServices#135]
Umlauts such as` ä, ü, ö` do not work in the Angular2 SPA.

**Comment by laskoviymishka** [comment]
Where it not work? Could you please provide more info.

**Comment by doczoidberg** [comment]
Just add these characters to e.g. to home.html
then � is shown instead of äöü$

**Comment by laskoviymishka** [comment]
File saved in bad coding. Use vs advanced save, and change encoding to UTF-8

**Comment by laskoviymishka** [comment]
This should be fixed in templates imho, all files there looks like have MS encoding(which don't have any Russian and German special letters)
