### ISSUE TITLE
vendor js stop the activities

### ISSUE THREAD

**Issue by yeganehaym** [aspnet/JavaScriptServices#1350]
when i put` vendor.js` in file, angular load old website but when i remove this line everything seems good
OnInit load data and show them but click event for example not working
i guess everything is well untill i come across this log:
![log1](https://user-images.githubusercontent.com/5742917/31859340-4e34019c-b717-11e7-8a70-13b14a9a39d0.png)
with vendor js i come across with this line:
![log2](https://user-images.githubusercontent.com/5742917/31859347-577e0568-b717-11e7-9259-97b72a0ae0e1.png)
i dont have hmr benefits as well because of these things

**Comment by SteveSandersonMS** [comment]
> when i putvendor.js in file

I'm sorry but I don't at all understand your question. What are you doing with `vendor.js` - which file are you putting it in, and how? You shouldn't have to do anything with this manually, as the default template already has all the files referenced correctly.

**Comment by yeganehaym** [comment]
you can see [here](https://github.com/aspnet/JavaScriptServices/issues/1281)

**Comment by SteveSandersonMS** [comment]
I see, this is the same issue reported before. I'm afraid I still don't know what's in your `vendor.js` file that causes it not to work. If you can post repro steps I'd be happy to look into it. Failing that there's not much I can say since this is specific to something in your project.

**Comment by SteveSandersonMS** [comment]
Closing due to lack of info, but please do let us know if you have specific repro steps that imply there's a defect in the code in this repo or the default template.
