### ISSUE TITLE
Shared hosting environment requirement

### ISSUE THREAD

**Issue by alexbenitez** [aspnet/JavaScriptServices#1351]
I'm new to .net core with the NodeServices() pre-rendering feature so this might be a newbie question.

I was under the (likely wrong) impression that a production build would pre-render by invoking an in-proc node.js implementation which wouldn't require node.js installed.

I recently deployed a starter which implements the pre-rendering feature to a shared server hosted by ASPHostPort. The web application is compiled as an .EXE (as per the site hosting provider requirement). When it attempts to run it fails with an error saying that Node.Js is not installed in the server. Does this mean that I need to look for a hosting provider who includes Node.JS in their servers (they do offer Node.JS... I just want to verify if this is indeed required not just for development but also production).

The other question I have.... If Node.Js is required in a production environment and its use is not in-process... is there are limitation/consideration to keep in mind given that Node.JS to my understanding doesn't support multi-threading?

Thanks in advance for the information.

**Comment by SteveSandersonMS** [comment]
> I was under the (likely wrong) impression that a production build would pre-render by invoking an in-proc node.js implementation which wouldn't require node.js installed.

It's not in-process, and it does require node.js to be installed on the host machine.

> Does this mean that I need to look for a hosting provider who includes Node.JS in their servers

If you want to use server-side prerendering, then yes that is correct.

> If Node.Js is required in a production environment and its use is not in-process... is there are limitation/consideration to keep in mind given that Node.JS to my understanding doesn't support multi-threading?

There'll be as many Node processes as there are ASP.NET processes, all handling requests concurrently in parallel. You shouldn't have to do anything to configure the Node side of it explicitly.
