### ISSUE TITLE
Upgrade path from .net core 1.1 to .net core 2

### ISSUE THREAD

**Issue by jagmagh** [aspnet/JavaScriptServices#1352]
I am having an existing application built using .net 1.1 and the JavascriptServices Angular template (using Angular 4.1.2). The version of Microsoft.Aspnetcore.SpaServices being used in my application is 1.1.1.

I am planning to upgrade my .net core framework from 1.1 to 2.0.

Can anyone guide me as to what steps are necessary to ensure that my Angular application and build process (webpack) that was originally setup by the JavascriptServices Angular template will work especially with the treeshaking / server side rendering etc as before?

Is it just as simple as   
1. Upgrade <TargetFramework>netcoreapp2.0</TargetFramework> for my projects
2. Upgrade all the Microsoft.Aspnetcore.SpaServices nuget dependencies to latest.

Or am i missing something else?

**Comment by SteveSandersonMS** [comment]
There's an upgrade guide here: https://docs.microsoft.com/en-us/aspnet/core/migration/1x-to-2x/

Note that once you start using the `Microsoft.AspNetCore.All` package from ASP.NET Core 2.0, you won't need to reference SpaServices directly any more (because that's referenced from the All package).

**Comment by jagmagh** [comment]
@SteveSandersonMS  thanks. Appreciate your prompt reply. I am looking at the guide and its mainly how to upgrade from a .net perspective. My main concern is the angular / webpack build / ssr etc that was part of the original javascriptservices template I was using. That is the part I am not clear about and wondering if there need to be any changes to that for it to continue working as before?
