### ISSUE TITLE
Asp.net Core 2 Razor Pages MapSpaFallback suggestion

### ISSUE THREAD

**Issue by pholly** [aspnet/JavaScriptServices#1354]
MapSpaFallback works well for MVC routes but does not exist for the new Razor Pages.

If [SpaRouteConstraint](https://github.com/aspnet/JavaScriptServices/blob/2ba5a0ac930a055acc6e711a701ed43aa993ec8b/src/Microsoft.AspNetCore.SpaServices/Routing/SpaRouteConstraint.cs#L7) were `public` instead of `internal` with a little work developers can add the constraint to Razor pages:

```C#
//Starup.cs ConfigureServices
//thank you Scott Hanselman https://www.hanselman.com/blog/AddingACustomInlineRouteConstraintInASPNETCore10.aspx
services.Configure<RouteOptions>(options => 
                options.ConstraintMap.Add("spaRoute", typeof(SpaRouteConstraint)));
services.AddMvc()
                .AddRazorPagesOptions(options =>
                {
                    options.Conventions.AddPageRoute("/Index", "{*catchAll:spaRoute(catchAll)}");
                });
```

Would be even better if `JavaScriptServices` somehow added `SpaRouteConstraint` to the `ConstraintMap`.

For now I'll just copy the `SpaRouteConstraint` class.
Thanks,
Philip

**Comment by buvinghausen** [comment]
I have just been using a regex to exclude the api routes.....

```csharp
services
    .AddMvc()
    .AddRazorPagesOptions(options =>
    {
        options.Conventions.AddPageRoute("/Index", "{*url:regex(^(?!api).*$)}");
    });
```

**Comment by SteveSandersonMS** [comment]
Thanks for the suggestion. In the next update, we're providing an alternative to `MapSpaFallbackRoute` that isn't coupled to the concept of MVC actions. It looks like this:

```
app.UseSpa("root-directory-goes-here", () => { /* config goes here */ });
```

This is generic middleware that you can use either with MVC or Razor projects. Hopefully that will cover your requirements even more cleanly.

**Comment by RichiCoder1** [comment]
@SteveSandersonMS That'd be awesome. On at least two of my projects, there's just a thin layer of razor over an index.html (generated by webpack).

**Comment by TheBearSO** [comment]
any toughs ?

**Comment by StefanKern** [comment]
@buvinghausen thank you for your solution. I took me a long time to understand it but it works now.

@SteveSanderson: when is this app.UseSpa avalible. With the newset version of .Net Core I don't have it yet :(

**Comment by SteveSandersonMS** [comment]
@jjgriff93 We shipped `UseSpa` in ASP.NET Core 2.1.

**Comment by jfborie** [comment]
Hi , @jjgriff93 
I am testing https://github.com/vasyliv/angular6/tree/angular-server to include it my project. I cannot get spa fall back to work any suggestion?

**Comment by jjgriff93** [comment]
Thanks @SteveSandersonMS - turns out it was a completely unrelated problem to spaservices! It was an SSL error. @jfborie I'm probably not best placed to help as I'm fairly new with the framework myself; however if you post your issue up separately and reference it I'm happy to take a look and see if i have any suggestions. Make sure you tell us what the error is with any code you can share

**Comment by jfborie** [comment]
I hit too many snag i am trying with https://github.com/angular/universal-starter for now. Thx.
