### ISSUE TITLE
HMR not working

### ISSUE THREAD

**Issue by JasonGT** [aspnet/JavaScriptServices#1355]
I am using Visual Studio 2017 15.4.1 with the Angular + ASP.NET Core 2.0 template. When I run the application (with IIS Express) I see the "[HMR] connected" message but other than that HMR is not working at all. 

To reproduce the issue I have created a couple of new projects 1) .NET Core CLI & dotnet new angular, and 2) VS 2017 with the template. In both cases for the new projects, HMR is working fine.

However, if I try to add a new Angular + ASP.NET Core 2.0 project to my existing solution, I cannot get HMR to work their either. 

I've compared all of the files I can think to compare but cannot figure this out at all. Any suggestions would be appreciated. Let me know what extra information you need.

Thank you!

**Comment by SteveSandersonMS** [comment]
I'm afraid I can't guess what's different about your existing project versus the newly-created ones. You'll need to continue comparing the code and config to track down what's different. Sorry I can't give a quicker solution than that!

**Comment by JasonGT** [comment]
Hi Steve. Thanks for taking a look. It's not about the differences between projects/config files, it's something else entirely, let me explain. I have an existing solution:

 - Solution
     - UI Project // SPA template HMR not working
     - Data Project
     - Logic Project

If I add a new SPA project to this solution (i.e. a new UI project), HMR doesn't work for the new project either. So it seems that HMR isn't working in this solution; or this file location. 

Do you have any idea what could cause this behaviour?

**Comment by SteveSandersonMS** [comment]
You probably have something in an ancestor-level directory that's interfering (e.g., a `tsconfig.json`, or a `package.json`, or something else like that).
