### ISSUE TITLE
Creating custom example - learning

### ISSUE THREAD

**Issue by alan994** [aspnet/JavaScriptServices#1356]
Hi,

I'm pretty new to webpack and all this modern web things, but I wont to figure it out :) 
I'm trying to reproduce ASP.NET core + angular application. I'm doing it by template generated from Visual studio 2017. In this [Git repo](https://github.com/alan994/asp.net-core_angular) I posted example app with a problem. All of features that I wont for now works, except automatic refresh (HMR) of page content after doing some changes in code. 

How to reproduce. 

- Run application (e.g. dotnet run)
- Open F12 chrome tools
- See message in console [HMR] connected
- Go to file  app/components/app/app.component.html and change some text
- Save file 
- Look at dotnet console output. Webpack is compiling...
- Look at chrome console 
  - [HMR] bundle rebuilding
  - [HMR] bundle rebuilt in 209ms
  - [HMR] Checking for updates on the server...
  - **GET http://localhost:4347/e414f0271c46a2ab8bc9.hot-update.json 404 (Not Found)**

And that is excepted as in project structure there is no e414f0271c46a2ab8bc9.hot-update.json file.

**Question is what I'm doing wrong and how to set up HMR to work in my example?**

**Comment by SteveSandersonMS** [comment]
Thanks for posting @alan994. I'm afraid I don't know what specifically is different between your custom project and how the default template sets things up. From a quick look at your Git repo, there are a lot of differences. I'd recommend comparing your implementation with the default template in more detail to track down what's missing. If you do manage to track it down and believe there's a problem with either the default template or any code in this repo, please let us know with a more concise repro! Sorry I can't provide a simpler answer.
