### ISSUE TITLE
Microsoft.AspNetCore.SpaTemplates::*

### ISSUE THREAD

**Issue by AlanGRutter** [aspnet/JavaScriptServices#1359]
I have VS2017 V15.4.0 installed. I ran dotnet new  --install Microsoft.AspNetCore.SpaTemplates::* to get hold of the Aurelia template.

I've done the dotnet restore and npm install and if I run it using dotnet run it works. However if I open the folder in VS2017 and try to debug it from there I get a FileNotFoundException looking for System.Runtime 4.2.0.0

I couldn't find any solutions out there so I'm looking for help here.

**Comment by SteveSandersonMS** [comment]
In VS2017, don't use the "Open folder" option. Instead, use File->Open->Project/Solution and choose the `.csproj` in the root directory of your project. I know this is not obvious if you're new to VS though!
