### ISSUE TITLE
Import Msal.js into an Angular Prj

### ISSUE THREAD

**Issue by spottedmahn** [aspnet/JavaScriptServices#1360]
How do I go about adding [Msal.js](https://github.com/AzureAD/microsoft-authentication-library-for-js) to an Angular project?

I've add it to package.json: `"msal": "^0.1.2"`

I've update webpack.config.vendor.js

```js
const treeShakableModules = [
    ...
    'msal'
];
```
I see the msal code in `vendor.js` but when I try to use it in a component I get

>AppComponent.ngfactory.js:12 ERROR ReferenceError: Msal is not defined
    at new AuthenticationService (authentication.service.ts:14)

**authentication.service.ts**
```js
import { Injectable } from '@angular/core';
import 'msal';

import { environment } from '../environments/environment';

@Injectable()
export class AuthenticationService {
    private authority = `https://login.microsoftonline.com/tfp/${environment.tenant}/${environment.signUpSignInPolicy}`;

    private clientApplication: Msal.UserAgentApplication;

    constructor() {
        this.clientApplication =
            new Msal.UserAgentApplication(
                environment.clientID,
                this.authority,
                this.authCallback,
                {
                    redirectUri: window.location.origin
                });
    }
...
```

[Full source code here](https://github.com/spottedmahn/NetCoreAngularAzureB2CMsal/tree/dev/msal)

**Comment by SteveSandersonMS** [comment]
I'm afraid I can't provide guidance on specific third-party libraries. You'll need to ask the creators of Msal.js about its usage with Angular and Webpack.

**Comment by spottedmahn** [comment]
Hi @SteveSandersonMS - I understand.  I should have made the post generic.  Importing Msal.js would be the same as importing any random JS file/library (I would think at least).  I'll open another issue.

**Comment by SteveSandersonMS** [comment]
OK, thanks. In general, whatever works with Angular + Webpack should work the same. If you're reporting an issue with integrating third-party libraries, please provide a repro of what doesn't work with this template that does work with other Angular+Webpack setups.

**Comment by spottedmahn** [comment]
Created #1364 ...
