### ISSUE TITLE
Using named attribute routes with MapSpaFallbackRoute

### ISSUE THREAD

**Issue by RehanSaeed** [aspnet/JavaScriptServices#1362]
I'd like to use attribute routing and also named routes. When I remove the default route in `Startup.cs` and use the `[Route]` and `[HttpGet]` attributes in my controller, the 404 page no longer gets rendered by the SPA.

```
[Route("")]
public class HomeController : Controller
{
    [HttpGet("", Name = HomeControllerRouteName.GetIndex)]
    public IActionResult Index() => this.View();

    [HttpGet("error", Name = HomeControllerRouteName.GetError)]
    public IActionResult Error()
    {
        this.ViewData["RequestId"] = Activity.Current?.Id ?? this.HttpContext.TraceIdentifier;
        return this.View();
    }
}

.UseMvc(routes =>
{
    routes.MapSpaFallbackRoute(
        name: "spa-fallback",
        defaults: new { controller = "Home", action = "Index" });
})
```

1. Why does the `MapSpaFallbackRoute` not work with attribute and named routes?
2. How can I specify a route name instead of a controller and action name with `MapSpaFallbackRoute`?

**Comment by SteveSandersonMS** [comment]
1. When you put the attribute route on your `HomeController`/`Index` action, you're restricting it to accept requests matching that URL. `MapSpaFallbackRoute` is only a way of setting up default routing parameters - it doesn't override any restrictions that specific controllers or actions have on accepting requests. So, this combination of usages isn't going to produce a useful result. Don't use attribute routing on `HomeController`/`Index` if you want to send conventionally-routed requests to it.

2. That's not applicable to what `MapSpaFallbackRoute` does. It's only setting up default routing parameters, not actually handling the request.

In the next update, we're providing an alternative to `MapSpaFallbackRoute` that does more of what you want, in that it is middleware that actually does handle the request independently of MVC routing.
