### ISSUE TITLE
Import JavaScript Library in Angular Prj

### ISSUE THREAD

**Issue by spottedmahn** [aspnet/JavaScriptServices#1364]
How I add Javascript files to an Angular project?

I've found this [great post about how to do it using the Angular CLI](https://hackernoon.com/how-to-use-javascript-libraries-in-angular-2-apps-ff274ba601af) but I'm not sure how to translate that to this project template.

>`angular.cli.json`
>`"scripts":[
"../node_modules/underscore/underscore.js"
]`

**Comment by SteveSandersonMS** [comment]
It sounds like you just want to load a `.js` file as a global in your web page. Webpack provides various ways to include scripts in its bundles (check Webpack docs for details), but for this simple case, you don't even need to use Webpack. You can put the `.js` file into `wwwroot` and add a `<script>` tag on to your layout or `Index.cshtml` to load it.

If you're trying to do something more sophisticated, then there isn't just one way to do it. It depends on what library you're trying to add and how it's intended to integrate with Angular and/or Webpack. The only way to know how to do this in general is to become familiar with Webpack (see: [webpack docs](https://webpack.js.org/)) and in the case of Angular add-ins, find out how the author of the add-in expects it to be set up with Webpack. But it sounds like this might not be necessary in your case as you might be just trying to load a script file globally.

**Comment by spottedmahn** [comment]
@SteveSandersonMS copy that.  Thanks!!! 🎉
