### ISSUE TITLE
reactredux app: webpack.ProvidePlugin is not supplying jQuery in vendor.js

### ISSUE THREAD

**Issue by timothywisdom** [aspnet/JavaScriptServices#1369]
I have created a new app via the command:
`dotnet new reactredux`

Next I have installed all the dependencies with the command:
`npm install`

Then I run the app via the command:
`dotnet run`

And I can see the app running when I visit localhost:5000

However, the webpack.ProvidePlugin in the webpack.config.vendor.js file is supposed to provide jQuery globally everywhere. Yet, when I open a JS console and try to access jQuery, it's not available.
`$` is returning `ƒ $(selector, [startNode]) { [Command Line API] }`
`jQuery` is undefined

Have I missed something? Does anyone else have this problem?

**Comment by SteveSandersonMS** [comment]
`ProvidePlugin` doesn't add globals - it just injects the appearance of a global into all your Webpack modules. What you want instead might be something more like this: https://github.com/webpack-contrib/expose-loader
