### ISSUE TITLE
MusicStore Database Location

### ISSUE THREAD

**Issue by LexDan** [aspnet/JavaScriptServices#137]
This is not an issue but a question. How do I locate that actual database for this sample project? I have it working perfectly however I am at a loss of where the database is and how I can configure the database to be somewhere else. I just am lost on where the connection info is unless this is wrapped up in the Key that is deep in: C:\Users\dmckown\Source\Repos\JavaScriptServices\tools\Key.snk

Thanks for this sample and any assistance!

**Comment by laskoviymishka** [comment]
Your sql lite db file placed in `Directory.GetCurrentDirectory()`

**Comment by LexDan** [comment]
Thank you very much that was the key to finding the db. After following your directions I later found the exact location: ...\MusicStore\bin\Debug\netcoreapp1.0
And also realized how this was setup in the Startup.cs code:

// Add EF services to the service container
services.AddEntityFramework()
    .AddEntityFrameworkSqlite()
    .AddDbContext<MusicStoreContext>(options => {
            options.UseSqlite("Data Source=music-db.sqlite");
       });

Is there a way to take control over where the db will get placed?
Thanks again.

**Comment by laskoviymishka** [comment]
Sure, you could specify `Data Source=music-db.sqlite` as `Data Source=C:\music-db.sqlite`, and if you have sophisticated permissions, it should work.

**Comment by LexDan** [comment]
Worked perfectly as you showed. Thanks again!
