### ISSUE TITLE
Calling into headless chrome timeouts in Production

### ISSUE THREAD

**Issue by chris-herring** [aspnet/JavaScriptServices#1370]
Not sure if this is an problem with JavaScriptServices but I'm running out of ideas so looking for any helpful info.

I'm using headless chrome to generate some PDFs from with the app and then is done by using NodeServices.InvokeAsync() to call into node which then uses headless chrome to generate the PDF. This works great locally however once deployed to a Product machine (IIS 7.5, Windows Small Business Server 2011 Standard) it times out trying to launch headless Chrome. If I run the script using node script.js from the command line it works fine, it's just when executing using NodeServices that it fails. 
I've turned on debugging and no errors in the logs. I've tried puppeteer & chromeless and both show the same behaviour. Could it be a permissions issue? I've tried running the IIS app pool under an admin account and that did not make a difference. When NodeServices launches node what user account does it run under?

**Comment by SteveSandersonMS** [comment]
> When NodeServices launches node what user account does it run under?

The same account that the host `dotnet` process is running under.

I'm afraid I can't guess what's different about your production server compared with your development environment. The best I can suggest is adding more logging so you can see how far it gets through the process. Your command prompt will be running `node` as whatever account you logged in with, and that might mean it has access to different files or has different environment variables.
