### ISSUE TITLE
[React/Redux template] Turn on noUnusedLocals & noUnusedParameters rules in tsconfig.json

### ISSUE THREAD

**Issue by thangchung** [aspnet/JavaScriptServices#1373]
Hi all,
Because I want to turn on the noUnusedLocals & noUnusedParameters rules in tsconfig.json to make my code neat and succinct. But if I turn it on, then the line at https://github.com/aspnet/templating/blob/dev/src/Microsoft.DotNet.Web.Spa.ProjectTemplates/content/ReactRedux-CSharp/ClientApp/store/Counter.ts#L42 violated the rules. I have searched around on Google, but could not end up with the solution. I notice that maybe Typescript doesn't support it, the issue at https://github.com/Microsoft/TypeScript/issues/12913. Do we have any solution there?

**Comment by PFAR** [comment]
Although code in the default switch can in practice also be considered 'Unused', you could add code that references the const exhaustiveCheck without changing its behavior, something like the following line would do just fine:
`if (typeof exhaustiveCheck != 'undefined') break;`

**Comment by SteveSandersonMS** [comment]
Thanks for the answer, @PFAR.
