### ISSUE TITLE
Non-Spa using SSR for "islands" of functionality seemingly caching data from previous call

### ISSUE THREAD

**Issue by fooberichu150** [aspnet/JavaScriptServices#1374]
I'm using a hybrid ASP.NET Core 2.x website with React (not as a SPA but just "islands of functionality") for various controller actions.  In order to have a faster render time we're making use of the asp-prerender-module taghelper and it is working out great.  

That being said, I've ran into an issue that I'm having a hard time figuring out what is going on and/or how to resolve it.  I have an action method that takes in parameters from the url (route parameters) and will pass data into a React component using the `asp-prerender-module` taghelper.  My first call after running debug is fine, server and client render the same, but if I navigate to a different result-set on that action the nodeJS server somehow decides to render the previous page (even though I'm passing it the data for the current page) and the client side accurately sees and renders the data for the current result.  I end up getting page flashing, of course, since the server side version does not match the client checksum.

My other actions that use similar functionality but don't vary by query parameters are fine and don't have the invalid checksum.  

Is there some caching turned on and, if so, is there a way to figure out how to disable that, or what else could I be missing along the way?

*EDIT* I'm using the `aspnet-prerendering` npm package 3.0.1 with `Microsoft.AspNetCore.SpaServices` v.2.0.0 in case that helps narrow things down.

**Comment by SteveSandersonMS** [comment]
> Is there some caching turned on

Not by default. It's possible you have a `<cache>` tag helper in your page or layout but there's nothing to make it repeat prior results by default.

Can you provide a minimal repro for the problem?

> I'm having a hard time figuring out what is going on and/or how to resolve it

You might be able to make progress in a simple way just by adding some `console.log` statements to the TypeScript/JavaScript code that's performing the prerendering so you can see how often it runs and what parameters it receives. You might find that either it's not getting called as often as you thought (if indeed there's some .NET-side caching), or that for some reason the JS/TS code is set up to reuse prior results.

**Comment by fooberichu150** [comment]
Oh my gosh you sexy genius.  So the problem was in out boot-server.js which was modified slightly to handle loading a module dynamically based on a parameter we sent to it.  Turns out that require(...) was the culprit and was, of course, caching the module.  While I don't love the solution, I can invalidate the require cache for that specific module.  I'll put the before and after boot-server.js files in separate comments to demonstrate the changes.

**Comment by fooberichu150** [comment]
```

const prerendering = require('aspnet-prerendering');
const React = require('react');
const path = require('path');
const renderToString = require('react-dom/server').renderToString;

module.exports = prerendering.createServerRenderer(params => {
	return new Promise((resolve, reject) => {
		if (typeof global !== 'undefined')
			global.initialData = params.data;

		//params.location
		//params.absoluteUrl
		const lastIndex = params.data.module.lastIndexOf('/');
		const moduleName = params.data.module.substr(lastIndex + 1)
			.split('-')
			.map((str, i) => {
				if (i === 0)
					return str;

				return `${str[0].toUpperCase()}${str.substr(1)}`;
			})
			.join('');

			if (require.cache[params.data.module])

		const module = require(params.data.module);

		try {
			resolve({
				html: renderToString(module.default),
				globals: {
					[moduleName]: params.data
				}
			});
		}
		catch (err) {
			reject(err);
		}
	});
});
```

**Comment by fooberichu150** [comment]
Ended up lifting the block of code from https://stackoverflow.com/a/14801711 and right before my call to `const module = require(params.data.module);` I added `purgeCache(params.data.module);`

Problem solved, headache averted.

**Comment by SteveSandersonMS** [comment]
I'd be cautious about using `purgeCache` like this on every request as it won't be optimal for performance (Node isn't designed to assume modules will be constantly unloaded and reloaded) but I'm glad you have a solution.

**Comment by fooberichu150** [comment]
Got me thinking why the problem was occurring in the first place and started reading through the code the other dev who implemented this had in place; turns out I could skip the `purgeCache` per your recommendation if I modified how he was seeding that data into these modules.  Thanks again for your help!
