### ISSUE TITLE
React/Redux template: How to access props.location?

### ISSUE THREAD

**Issue by emzero** [aspnet/JavaScriptServices#138]
I'm trying to get my head around Typescript and the React/Redux template. Since the components are strongly typed, one can't just simply do `this.props.location` for example.

So how do we add react-router state to the ApplicationState interface?

**Comment by xabikos** [comment]
As the template uses [react-router-redux](https://github.com/reactjs/react-router-redux) already you need to change the index.ts file inside the store folder to look like this
```
import { ActionCreatorGeneric } from 'redux-typed';
import * as WeatherForecasts from './WeatherForecasts';
import * as Counter from './Counter';
import { routerReducer } from 'react-router-redux'

// The top-level state object
export interface ApplicationState {
    counter: Counter.CounterState,
    weatherForecasts: WeatherForecasts.WeatherForecastsState,
    routing: TheShape of router reducer
}

// Whenever an action is dispatched, Redux will update each top-level application state property using
// the reducer with the matching name. It's important that the names match exactly, and that the reducer
// acts on the corresponding ApplicationState property type.
export const reducers = {
    counter: Counter.reducer,
    weatherForecasts: WeatherForecasts.reducer,
    routing: routerReducer
};

// This type can be used as a hint on action creators so that its 'dispatch' and 'getState' params are
// correctly typed to match your store.
export type ActionCreator = ActionCreatorGeneric<ApplicationState>;
```

And after doing this your store will contain under routing branch all the information for the routing. You can have a look in the [react-router-redux](https://github.com/reactjs/react-router-redux) for more information.

**Comment by emzero** [comment]
@xabikos I understand, but is "TheShape of router reducer" somewhere declared? Or is it just `typeof routerReducer`?

Actually, the shape of the routing reducer is not the interface of what redux saves in the store right? 

The Redux DevTools shows the following state for 'routing'

```javascript
routing: {
  locationBeforeTransitions: {
    pathname: "/yammer/oauth"
    search: ""
    hash: "#someHash"
    state: null
    action: "POP"
    key: "1orv78"
    query: {}
    $searchBase:{
      search: ""
      searchBase: ""  
    }
  }
}
```

I can't seem to find such interface in the react-router-redux typings or anywhere else...

**Comment by xabikos** [comment]
If you can not find something related to react-router-redux typings then you can create your own interface based on the shape you just described. This is something that should work. But please keep in mind that I am not familiar with TypeScript as I am using only ES2015 so far.

**Comment by SteveSandersonMS** [comment]
Thanks @xabikos for providing help here. There's not much to be added - everything you've said is exactly correct :)

I too cannot find any docs in `react-router-redux` that specifies what shape of data gets put into the store by `routerReducer`. However, the following type definition matches up with what I observe in practice:

```
interface RoutingData {
    locationBeforeTransitions: Location;
}
```

Note that `Location` is a native ES6 type built into TypeScript, so you don't need to define that. It is the interface that contains properties like `pathname` and `search`.

**Comment by emzero** [comment]
@SteveSandersonMS I'm having issues with code running on the server that should only run on the client.

I'm wrapping that code in a `if (window)` but I'm getting the server-side exception:
![image](https://cloud.githubusercontent.com/assets/412489/16365824/732be030-3be1-11e6-991b-a87b3b105b92.png)

Is there a reliable way to check whether we are in the server or client?
