### ISSUE TITLE
Use of Vue Single File Components?

### ISSUE THREAD

**Issue by RehanSaeed** [aspnet/JavaScriptServices#1382]
I'm new to Vue and it's [single file components](https://vuejs.org/v2/guide/single-file-components.html) which I think is an optional way of putting together your components. 

Apart from separation of concerns and perhaps better tooling (I think VS Code handles them ok), is there a reason why the TypeScript files are separated from the html and why a `.vue.html` file extension is used? Switching to a single file `.vue` file extension just means chaning the file extension in Webpack config right?

**Comment by SteveSandersonMS** [comment]
I think at the time we implemented the last round of updates to the Vue template, either VS or VS Code or both didn't handle `.vue` files properly (they didn't do proper intellisense or something). If you are able to verify that both of those do correctly handle all aspects of `.vue` files now, giving correct colourisation and code completion/intellisense to HTML, CSS/SASS/etc., and TypeScript parts of the file, we could certainly consider moving to that approach.

If this is something you'd like to submit a PR for (having verified it works correctly in those IDEs), please go ahead. Thanks!

**Comment by RehanSaeed** [comment]
Tried to add support in my webpack configuration and failed. It seems that `ts-loader` has support but we are using `awesome-typescript-loader` which [doesn't seem to have out of the box support](https://github.com/s-panferov/awesome-typescript-loader/issues/356).
