### ISSUE TITLE
Can't Inject service in angular 2 module with ASP Core 1.1

### ISSUE THREAD

**Issue by saimkhan** [aspnet/JavaScriptServices#1384]
Register in both app.module.shared and app.module.server but still getting this error An unhandled exception occurred while processing the request.

NodeInvocationException: Uncaught (in promise): Error: No provider for AuthenticationService!
Error: No provider for AuthenticationService!

**app.module.server**

import { NgModule } from '@angular/core';
import { ServerModule } from '@angular/platform-server';
import { AppModuleShared } from './app.module.shared';
import { AppComponent } from './components/app/app.component';
import { AlertService, AuthenticationService, UserService } from './components/login/services/index';

@NgModule({
    bootstrap: [ AppComponent ],
    imports: [
        ServerModule,
        AppModuleShared
    ], providers: [
        AlertService,
        AuthenticationService,
        UserService
    ]
})
export class AppModule {
}

**app.module.shared**
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { HttpModule } from '@angular/http';
import { RouterModule } from '@angular/router';
import { AppComponent } from './components/app/app.component';
import { categoryComponent} from './components/category/category.component';
import { HomeComponent } from './components/home/home.component';
import { LoginComponent } from './components/Login/login.component';
import { AlertService, AuthenticationService, UserService } from './components/login/services/index';
@NgModule({
    declarations: [
        AppComponent,
        HomeComponent,
        categoryComponent,
        LoginComponent
    ],
    imports: [
        CommonModule,
        HttpModule,
        FormsModule,
        RouterModule.forRoot([
            { path: '', redirectTo: 'home', pathMatch: 'full' },
            { path: 'home', component: HomeComponent },
            { path: 'login', component: LoginComponent },
            { path: 'catetory', component: categoryComponent },
            { path: '**', redirectTo: 'home' }
        ])
    ],
    providers: [
        AlertService,
        AuthenticationService,
        UserService
    ]
})
export class AppModuleShared {
}

**Comment by SteveSandersonMS** [comment]
Since this is an Angular usage question rather than anything specific to ASP.NET, would it be OK to raise it with the Angular community instead? Thanks!
