### ISSUE TITLE
Cannot find module '@angular/platform-browser/src/animate/animation_builder'.

### ISSUE THREAD

**Issue by doczoidberg** [aspnet/JavaScriptServices#139]
runnning `yo aspnetcore-spa` with Angular2 now throws the error:

```
ERROR in C:\temp\aspnetu2\node_modules\angular2-universal\dist\node\platform\dom\node_dom_renderer.d.ts
(3,34): error TS2307: Cannot find module '@angular/platform-browser/src/animate/animation_builder'.
```

and `dotnet run`:
```
[Node] Error: Cannot find module '@angular/platform-browser/src/animate/animation_builder'
[Node]     at Function.Module._resolveFilename (module.js:325:15)
[Node]     at Function.Module._load (module.js:276:25)
[Node]     at Module.require (module.js:353:17)
[Node]     at require (internal/module.js:12:17)
[Node]     at Object.<anonymous> (C:\temp\aspnetu2\node_modules\angular2-universal\dist\node\platform\dom\node_dom_renderer.js:24:27)
```

I think this has to do with angular rc2 release.

**Comment by laskoviymishka** [comment]
Seems like animation not suppored for `angular2-universal`. Does it work well with server render?

**Comment by doczoidberg** [comment]
how can I check?

**Comment by laskoviymishka** [comment]
In your index.cshtml remove asp-prerender stuff. Leave just your `app` tag.

**Comment by doczoidberg** [comment]
that works

**Comment by doczoidberg** [comment]
publishing still gives me the error in addition to [issue 133](https://github.com/aspnet/JavaScriptServices/issues/133)
```
ERROR in C:\temp\aspnetu2\node_modules\angular2-universal\dist\node\platform\dom\node_dom_renderer.d.ts
PUBLISH(3,34): Error TS2307: Cannot find module '@angular/platform-browser/src/animate/animation_builder'.
```

**Comment by ManuelDeLeon** [comment]
I got the same error today.

```
ERROR in C:\test6\node_modules\angular2-universal\dist\node\platform\dom\node_dom_renderer.d.ts
(3,34): error TS2307: Cannot find module '@angular/platform-browser/src/animate/animation_builder'.
```

It happens if you use v2.0.0-rc.2 (which is supposed to be compatible with v2.0.0-rc.1)

Solved it by pinning the version of angular2 in package.json:

```
    "@angular/common": "2.0.0-rc.1",
    "@angular/compiler": "2.0.0-rc.1",
    "@angular/core": "2.0.0-rc.1",
    "@angular/http": "2.0.0-rc.1",
    "@angular/platform-browser": "2.0.0-rc.1",
    "@angular/platform-browser-dynamic": "2.0.0-rc.1",
    "@angular/platform-server": "2.0.0-rc.1",
    "@angular/router": "2.0.0-rc.1",
    "@angular/router-deprecated": "2.0.0-rc.1"
```

@SteveSandersonMS 
Wouldn't it be better to use exact version numbers? As this example shows, compatible versions aren't exactly "compatible".

**Comment by SteveSandersonMS** [comment]
Thanks for reporting this.

> Wouldn't it be better to use exact version numbers? As this example shows, compatible versions aren't exactly "compatible".

Unfortunately, yes, that does look like the only clean resolution at the moment :( I've applied this fix (but not yet published the updated packages to NPM - will do so later in case there are more fixes and updates to go out at the same time).

The use of `peerDependencies` throughout the Angular 2 packages does make it tricky to find a mutually-compatible combination of dependencies, and it means that allowing version ranges is pretty much a guaranteed losing strategy. At least until Angular 2 ships its final release, we might be stuck manually pinning to specific RC versions. I didn't find a mutually-compatible set of RC2 packages (that includes `angular2-universal`) yet. We might have to wait for RC3 before that dependency can update.
