### ISSUE TITLE
Vue SPA Template

### ISSUE THREAD

**Issue by FooBartn** [aspnet/JavaScriptServices#1390]
I used the dotnet new vue SPA template, and tested it out this weekend. Some of the packages in this template are quite far behind and have security issues, etc. With a few minor changes, all packages can be updated to their latest stable versions. 

The primary change is that, unless other code is updated, you need to set the esModule option in vue-loader to false. Also need to add lang="ts" to the .ts imports in vue files.

I personally removed the ".html" from my vue files, removed awesome-typescript-loader, installed ts-loader, and set up my webpack config like so:

```
return [{
        stats: { modules: false },
        context: __dirname,
        resolve: { extensions: [ '.js', '.vue', '.ts' ] },
        entry: { 'main': './ClientApp/boot.ts' },
        module: {
            rules: [
                { test: /\.vue$/, include: /ClientApp/, loader: 'vue-loader', options: { esModule: false } },
                { test: /\.css$/, use: isDevBuild ? [ 'style-loader', 'css-loader' ] : ExtractTextPlugin.extract({ use: 'css-loader?minimize' }) },
                { test: /\.(png|jpg|jpeg|gif|svg)$/, use: 'url-loader?limit=25000' }
            ]
        },
```

example of script import:

`<script lang="ts" src="./fetchdata.ts"></script>`

dependencies:

```
  "devDependencies": {
    "@types/webpack-env": "^1.13.2",
    "aspnet-webpack": "^2.0.1",
    "bootstrap": "^3.3.7",
    "css-loader": "^0.28.7",
    "event-source-polyfill": "^0.0.11",
    "extract-text-webpack-plugin": "^3.0.2",
    "file-loader": "^1.1.5",
    "isomorphic-fetch": "^2.2.1",
    "jquery": "^3.2.1",
    "style-loader": "^0.19.0",
    "ts-loader": "^3.1.1",
    "typescript": "^2.6.1",
    "url-loader": "^0.6.2",
    "vue": "^2.5.6",
    "vue-loader": "^13.5.0",
    "vue-class-component": "6.1.0",
    "vue-property-decorator": "^6.0.0",
    "vue-router": "^3.0.1",
    "vue-template-compiler": "^2.5.6",
    "webpack": "^3.8.1",
    "webpack-hot-middleware": "^2.20.0"
  }
```

From my testing, all of the example code is functioning as expected in the template. Would it be acceptable to make these changes and submit a PR to the templating repo?

**Comment by ericop** [comment]
I  ❤️  this @FooBartn , even if you could just give a link to your source example in the mean time it would be a help to me. I'm trying to take advantage of the better TS support in vue 2.5+ but I'm still a newbie at webpack and it's throwing fits when I try to wire things up like `ts-loader` etc.

**Comment by FooBartn** [comment]
Apologies for the delay ... Turkey day and all ^__^ .. and I take no credit in being a webpack master by any means. Took me the better part of a weekend to get this all working the first time. Now that I know how it seems so simple.. but if anything breaks it'll be back to scouring docs... ha. >.<

If you want me to fork the templating repo, make those changes, and put in a PR just let me know.

If it would be easier for you to just look at the source for a working updated one, see: 

https://github.com/FooBartn/vue_spa_template 

I ran a "dotnet new vue" and updated everything to the latest packages. Modified the webconfig, changed the filenames to vue, removed awesome-typescript-loader, and added lang="ts" to the imports. Built it, ran it -- all functional, no errors. Pull it down, run an npm install, and check it out. Let me know if you run into any issues.

oh, also modified the fetch component slightly. Vetur (vue tooling for vscode) complained about the lack of a key on the for loop.

Cheers!

**Comment by FooBartn** [comment]
Note: may want to drop vue and vue-template-compiler back down to 2.5.6 .. seems the recent update to 2.5.8 caused some changes in the way vuerouter is handled. Throws an error in boot.ts

**Comment by ericop** [comment]
1. I did a `git pull https://github.com/FooBartn/vue_spa_template`  and `cd vue_spa_template`
2. Changed the **package.json** to use `"vue-template-compiler": "^2.5.6",` and ` "vue": "^2.5.6",` 
3. Deleted the shrink wrap to generate a **package-lock.json** 
4. As admin did `aspnet restore`
5. As Admin did `npm install`
6. Opened in *VSCode* and ran Debug as *.Net Core Launch (web)*
7. Seems to function. Vue Chrome extension acts a little crazy (see screenshot below)

![image](https://user-images.githubusercontent.com/5218249/33243827-ff3e87f0-d2ba-11e7-94cb-2889a89e1b33.png)

On the whole highly successful. also Notice that Vue 2.5.8 is still being used and preferred to 2.5.6 . I didn't dig into dependencies to figure it out, but seems off.

**Comment by ericop** [comment]
@FooBartn I even removed the `^` to force  2.5.6 on both, still seemed to have no effect, as I'm still seeing `[vue-devtools] Ready. Detected Vue v2.5.8` on the dev tools console . See https://github.com/ericop/vue_spa_template/blob/master/package.json#L19

**Comment by FooBartn** [comment]
I don't have any issues seeing the counter prop. I believe it should be a child under app component, though. I do see the same weirdness with choosing 2.5.6, and it showing me 2.5.8.

![vuecounter](https://user-images.githubusercontent.com/8498617/33269242-99cbb128-d345-11e7-8036-758567c61f34.PNG)

**Comment by ericop** [comment]
@FooBartn , okay, well I'd say what you have is better than what's in the current template, so I think it's worth a PR. I think it's worth you putting one in off your fork and seeing if they take it!

**Comment by Eilon** [comment]
@SteveSandersonMS - per your comment at https://github.com/aspnet/templating/issues/76#issuecomment-340840328, what do you recommend?

**Comment by SteveSandersonMS** [comment]
Thanks for proposing the changes! As it happens, we're recommending that interested community members might want to publish their own Vue templates separately now, since we're no longer developing one in this repo or in the templating repo ([details](https://github.com/aspnet/Announcements/issues/289)).

**Comment by mika76** [comment]
Anyone interested check out https://github.com/MarkPieszak/aspnetcore-Vue-starter
