### ISSUE TITLE
Equivalent of $('#myModal').modal('toggle') in React/Redux template

### ISSUE THREAD

**Issue by mgregory22** [aspnet/JavaScriptServices#1393]
Can someone explain how I can open a Bootstrap modal window programmatically?  I try it in the Chrome console and it tells me modal is not a function.  I'm using the React & Redux project template in VS2017. 

I'm new to this stack and I'm trying to sell a client on it because I know it's good, but I'm struggling to figure it out to give them a demo before I exhaust their patience.

I'm trying to use Bootstrap for modal dialogs, and I'm trying to go by the Bootstrap documentation, but things aren't working the way those docs say it does.  I think Typescript is the reason, but I'm not sure what to do about it.  This is all new to me.

**Comment by SteveSandersonMS** [comment]
I'll mark this closed because it's a general support request (about React and Redux) rather than being an issue or feature request related to this repo. @mgregory22, hope that's OK.

However if anyone has an answer, please feel free to post below!

**Comment by mgregory22** [comment]
It's okay.  Thanks for the kind note.  I didn't realize it had anything to do with Redux, so that's very helpful!
