### ISSUE TITLE
[Authorize] redirection SPA (server and client)

### ISSUE THREAD

**Issue by patsadow2** [aspnet/JavaScriptServices#1394]
Hello,

Could anyone tell how should i redirect SPA application from server or is it possible.

After unauthorized access my server redirect me to "/" page, but SPA aplication stay on the same site "/Edit", when i hit AJAX obvoiusly i can check if it's authorized or no and redirect SPA. But is it possible to say form server SPA that should change url ???

```
            services.ConfigureApplicationCookie(options =>
            {
                options.Cookie.HttpOnly = true;
                options.Cookie.Expiration = TimeSpan.FromDays(150);
                options.LoginPath = "/api/login";
                options.LogoutPath = "/api/logout";
                options.SlidingExpiration = true;
                // Requires `using Microsoft.AspNetCore.Authentication.Cookies;`
                options.ReturnUrlParameter = CookieAuthenticationDefaults.ReturnUrlParameter;
            });

```

```
            app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "default",
                    template: "{controller=Home}/{action=Index}/{id?}");
                    routes.MapSpaFallbackRoute("spa-fallback", new { controller = "Home", action = "Index" });
            });

```

```
        [HttpGet]
        [Route("login")]
        public IActionResult Login(string id)
        {
            Response.StatusCode = 302;
            return Redirect("/");
        }

```

I suppose only server side is redirected "whatever it means" and the client side stay on the same page.

**Comment by SteveSandersonMS** [comment]
If I understand correctly, you're asking how to make certain client-side routes perform auth checks and trigger a redirection if the user isn't authorised. If that is what you want, then the approach depends on which SPA framework you're using. For example, if you're using Angular, read about [route guards](https://angular.io/guide/router#guards), or if you're using react-router, there are many possible approaches such as [this one](https://reacttraining.com/react-router/web/example/auth-workflow).
