### ISSUE TITLE
Usage of WebPack Hash/ChunkHash

### ISSUE THREAD

**Issue by boraturant** [aspnet/JavaScriptServices#1397]
I would like to use Chunkhash instead of "asp-append-version='true'".

There are some patterns, such as;

1. https://github.com/kossnocorp/assets-webpack-plugin
2. https://github.com/aspnet/JavaScriptServices/issues/578

Do you have any recommendations on this? It would be also great if this could be integrated into the package. What do you think?

**Comment by SteveSandersonMS** [comment]
I don't personally have any recommendations on this, but if you come up with a design that you think works cleanly enough, please let us know how you think it should work. Thanks!
