### ISSUE TITLE
Cannot find namespace 'firebase' on update

### ISSUE THREAD

**Issue by doczoidberg** [aspnet/JavaScriptServices#140]
I added firebase to my project and as soon as I make a change to a file there goes something wrong with HMR? Refreshing the whole page via F5 works.
```
ERROR in C:\temp\aspnetu\node_modules\angularfire2\database\database.d.ts
(10,31): error TS2503: Cannot find namespace 'firebase'.
ERROR in C:\temp\aspnetu\node_modules\angularfire2\utils\firebase_object_factory.d.ts
(4,76): error TS2503: Cannot find namespace 'firebase'.
...etc
```

**Comment by SteveSandersonMS** [comment]
I'm afraid I don't know about any specific incompatibilities that firebase might have with webpack HMR. If when diagnosing this you think there are any particular changes we can make to these templates that will improve things for other developers then please let us know!
