### ISSUE TITLE
error in configureStore.ts buildRootReducer after the redux project creation

### ISSUE THREAD

**Issue by rpokrovskij** [aspnet/JavaScriptServices#1402]
redux project created with VS 2017 15.4.5 template,  dotnet --version 2.0.3
application started , before showing each page this exception is catched in debugger. After continue application somhow works, but e.g. INCREMENT button doesn't work.

```
Unhandled exception at line 7925, column 5 in http://localhost:62942/dist/main-client.js?v=t_7YZRKOFJl0xIwNHUHiPbsmtkcaNQ2IX-_BakvtCvU
0x800a01b6 - JavaScript runtime error: Object doesn't support property or method 'assign'

```

![image](https://user-images.githubusercontent.com/11598038/33483892-af698f4e-d6a8-11e7-8f08-0b61a139c895.png)

P.S. the same situation with reactdedux spa generated through `dotnet new`

**Comment by tpetrina** [comment]
Are you running this in IE? You probably need to add an `Object.assign` polyfill to ensure it works.

**Comment by rpokrovskij** [comment]
Thank you, and are right, it is only IE 11 problem. 
I've found answer there:
https://github.com/aspnet/JavaScriptServices/issues/836

polifills were added to boot-client.tsx

**Comment by SteveSandersonMS** [comment]
Rather than adding all of those polyfills, I'd recommend just adding the specific ones you need. Since you were having trouble with `Object.assign`, I'd start by adding only the polyfill for `core-js/fn/object/assign` and proceed from there.
