### ISSUE TITLE
Adding libraries to aurelia SPA template errors

### ISSUE THREAD

**Issue by robscottnh** [aspnet/JavaScriptServices#1406]
I'm having great difficulty adding several libraries to an app built using the Aurelia SPA template.  Something as simple as adding the numeral library fails with:

 ERROR in ./ClientApp/app/components/counter/counter.ts
(1,9): error TS2305: Module '"numeral"' has no exported member 'numeral'.

this is after doing the following:
1) running npm install for the typings and the library which results in the following in the package.json file:

'''
"dependencies": {
    "@types/numeral": "0.0.22",
    "numeral": "^2.0.6"
  }
'''

2) updating the boot.ts file with the following:
'''
aurelia.use.standardConfiguration()
         .plugin(PLATFORM.moduleName("numeral"));
'''

3) adding the following to counter.ts
'''
import {numeral} from "numeral"

export class Counter {
    public currentCount = 0;

    public incrementCounter() {
        this.currentCount++;
    }
}
'''
Some libraries such as aurelia-validation or aurelia-bootstrap-datetimepicker work fine using the same process, while others such as aurelia-api or aurelia-value-converters fail with similar errors or the infamous ModuleID "..." not found error.

As I'm just learning the intricacies of webpack and aurelia, it's highly likely that these are errors on my part..., but after much searching and numerous email exchanges with other aurelia developers, who say "I did the same thing you did, but using one of the Aurelia skeletons (not these skeletons) and it just worked...", I'm stumped.  

Regards,
Rob

**Comment by robscottnh** [comment]
Is there some additional info I could add to get a little help here?

**Comment by robscottnh** [comment]
So, I'm a little bit closer to understanding what the issue is here.  It has to do with the way entry element is configured in the different webpack skeletons.  Many of the popular aurelia plugins want you "add the plugin to the corebundles.aurelia section of your webpack config".   Now it appears that the webpack.config.js produced by these skeletons produces something like this:


    entry: { 'app': 'aurelia-bootstrapper' },

whereas the people providing these integration instructions expect that it looks something like this:

```
  const coreBundles = {
  bootstrap: [
    'aurelia-bootstrapper-webpack',
    'aurelia-polyfills',
    'aurelia-pal',
    'aurelia-pal-browser',
    'regenerator-runtime',
    'bluebird'
  ],

  aurelia: [
    'aurelia-bootstrapper-webpack',
    'aurelia-binding',
    'aurelia-dependency-injection',
    'aurelia-event-aggregator',
    'aurelia-framework',
    'aurelia-history',
    'aurelia-history-browser',
    'aurelia-loader',
    'aurelia-loader-webpack',
    'aurelia-logging',
    'aurelia-logging-console',
    'aurelia-metadata',
    'aurelia-pal',
    'aurelia-pal-browser',
    'aurelia-path',
    'aurelia-polyfills',
    'aurelia-route-recognizer',
    'aurelia-router',
    'aurelia-task-queue',
    'aurelia-templating',
    'aurelia-templating-binding',
    'aurelia-templating-router',
    'aurelia-templating-resources',
    'aurelia-api',
    'aurelia-authentication',
    'aurelia-testing'
  ]
}

const baseConfig = {
  entry: {
    //'app': [/* this is filled by the aurelia-webpack-plugin */],
    'aurelia-bootstrap': coreBundles.bootstrap,
    'aurelia': coreBundles.aurelia.filter(pkg => coreBundles.bootstrap.indexOf(pkg) === -1),

    'common': [
        "./src/resources/global/less/base/base.less", 
        "./src/resources/global/less/layout/layout.less",
       ],
    // 'homepage' : './src/application/homepage/homepage'
    /*'about': './src/application/about/about.less',*/

  },
```
Now, I'm not exactly sure what the ramifications are of changing things to the latter way.  If anyone could provide some guidance or point me to some guidance as to how this should be done, I'd be grateful.

Thanks,
Rob

**Comment by SteveSandersonMS** [comment]
We're no longer enhancing the Vue template (for info, please see https://github.com/aspnet/Announcements/issues/289).

Please feel free to continue any discussion about adding packages here though! I'm just marking it as closed because it's no longer an active work item in this repo.

**Comment by robscottnh** [comment]
Ah, just read your linked anouncements, not just Vue....

Sad,  I think my question was just about how to resolve the issue with how
do we reconcile the two different versions of webpack configs.

Rob
