### ISSUE TITLE
React/Redux template: How to disable server-side rendering?

### ISSUE THREAD

**Issue by emzero** [aspnet/JavaScriptServices#141]
I'm having some issues related to code that tries to run on the server while it shouldn't. I really don't have the expertise to deal with universal code so I'd like to just remove server-side rendering since I don't really need it.

I tried removing the `asp-prerender-module` tag in the `div#react-app` but that ended up in an empty div. I guess because the webpack.config.js never gets executed, and so boot-client.tsx never runs.

Is there an easy way to disable server-side rendering? I still want to use JavaScript services for its webpack integration.

**Comment by laskoviymishka** [comment]
You should add dist/main.js into your script, so it will start to render.

**Comment by emzero** [comment]
Great, it's working. Thanks
