### ISSUE TITLE
Installation of aspnet-webpack fails

### ISSUE THREAD

**Issue by mgregory22** [aspnet/JavaScriptServices#1410]
I'm trying to follow the "Installation into existing projects" section of the Microsoft.AspNetCore.SpaServices readme, but I'm running into an error trying to install the aspnet-webpack package.

It seems to have a dependency on fsevents, but I'm on a PC?

```
$ npm install --save-dev aspnet-webpack
npm ERR! path C:\TestProject\node_modules\fsevents\node_modules\dashdash\node_modules
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall scandir
npm ERR! Error: EPERM: operation not permitted, scandir 'C:\TestProject\node_modules\fsevents\node_modules\dashdash\node_modules'
npm ERR!  { Error: EPERM: operation not permitted, scandir 'C:\TestProject\node_modules\fsevents\node_modules\dashdash\node_modules'
npm ERR!   stack: 'Error: EPERM: operation not permitted, scandir \'C:\\TestProject\\node_modules\\fsevents\\node_modules\\dashdash\\node_modules\'',
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'scandir',
npm ERR!   path: 'C:\\TestProject\\node_modules\\fsevents\\node_modules\\dashdash\\node_modules' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Matt\AppData\Roaming\npm-cache\_logs\2017-12-04T16_21_18_453Z-debug.log
```

**Comment by SteveSandersonMS** [comment]
NPM installation is frequently unreliable on Windows. We get the `EPERM: operation not permitted, scandir` often on our CI systems and so have configured them to retry. Typically retrying fixes the problem. You might also benefit from ensuring Windows Defender isn't interfering with file accesses in that directory. This all has nothing to do with fsevents.

Closing as this is an external issue with NPM.
