### ISSUE TITLE
auto update browser on cshtml save - working with webpack

### ISSUE THREAD

**Issue by JohnGoldsmith** [aspnet/JavaScriptServices#1412]
I've got webpack and HMR working nicely with an ASP.NET Core 2 project (thanks to the docs here).  SCSS changes bubble up nicely in the browser without a full page reload.  

What I'm not clear on is how to include various views (cshtml) to this.  Is this something I should be looking to webpack to help with or should is there an alternative option here?  

My intitial thought was to use [Mads Kristensen's Browser Reload](https://marketplace.visualstudio.com/items?itemName=MadsKristensen.BrowserReloadonSave#overview) but now, even though I get cshtml changes auto reloading the page, changes to the webpack-handled scss also generate a page reload, which is obviously a backwards step.

Has anyone got these two to work together correctly?

**Comment by SteveSandersonMS** [comment]
Generally Webpack HMR works best for SPA type scenarios, where you wouldn't have multiple cshtml files. If you're structuring your application differently I'm afraid I don't have a specific recommendation.

**Comment by JohnGoldsmith** [comment]
Ok, fair enough.  I have a mix of straight MVC and one SPA.  I guess I was just hoping that they could all play nicely together, but that's fine, at least I'm not missing something straight forawrd.  Thanks very much for the feedback.

**Comment by JohnGoldsmith** [comment]
There you go, a bit more sleep and I've realised that you can filter out files from Browser Reload using  the 'Ignore patterns' field in _Tools / Options / Web / Browser Reload on Save_.  So now I get page reloads for cshtml changes and instant HMR for the JS and SASS.
