### ISSUE TITLE
Getting appsettings.json into TypeScript SSR - React.

### ISSUE THREAD

**Issue by orionstudt** [aspnet/JavaScriptServices#1414]
Steve,

I saw what you suggested for #1314 and I have used that `aspnet-prerender-data` to get my data into the `boot-server` & `boot-client` files. I can get this to work client side - for instance my config is needed to access a certain API so when one of my components gets mounted client side it has no issues accessing my data with something like `(window as any).data`.. but with no `window` on server side, do you think you can point me in the right direction on how I should go about getting that config into that component? 

Thanks.

**Comment by SteveSandersonMS** [comment]
If you're using Redux, then you should modify the code that constructs the initial store state so that it populates it with whatever data you're getting from `params.data`. This is how all components are meant to access state in a Redux app.

**Comment by orionstudt** [comment]
I got it working I just wasn't thinking of simply including it in the initial state. Thanks for your help.
