### ISSUE TITLE
Angular-CLI-Based-Template: It seems that it compiles all TS files for Platform Server

### ISSUE THREAD

**Issue by naveedahmed1** [aspnet/JavaScriptServices#1415]
@SteveSandersonMS It seems that the new Angular CLI based template always compiles all TS files for Platform Server.

Angular CLI allows multiple apps to exists in same project through `apps` array, and usually we don't enable SSR for our complete application rather its mostly enabled for the portion that is safe to run on server side and usually for the sections that are the entry points for users.

If we look at `apps` array in  `.angular-cli` it has two apps one for the client app and other for ssr. For app `ssr` we have `"tsconfig": "tsconfig.app-ssr.json",` and "main": "main.server.ts",

So as per my understanding, while building server bundles it should start from `AppServerModule` and recursively process files referenced in this module.

But it seems that it always compiles all files for platform server. Which breaks the app when we debug, and throws error like this.:

```
NodeInvocationException: Prerendering failed because of error: D:\MyProject\ClientApp\node_modules\ng2-img-cropper\src\imageCropperComponent.js:1
(function (exports, require, module, __filename, __dirname) { import { Component, Input, Renderer, ViewChild, Output, EventEmitter } from '@angular/core';
```

In this case I am using `imageCropperComponent `in `BrowserAppModule` only.

**Comment by SteveSandersonMS** [comment]
It's set up in the way recommended by Angular CLI docs: https://github.com/angular/angular-cli/wiki/stories-universal-rendering We don't have any further control over how the CLI does the build.

If you think there's a specific different way it should be set up, could you let me know what change you think should be made and why? Thanks!

**Comment by naveedahmed1** [comment]
Thank you @SteveSandersonMS for the clarification, I solved it by adding `exclude` setting in `tsconfig.app-ssr.json`
