### ISSUE TITLE
Vue Template error: Unknown custom element

### ISSUE THREAD

**Issue by Zaid-Safadi** [aspnet/JavaScriptServices#1416]
I'm trying to use the Vue template and also learning Vue. Things seems to be working until I try to use a nested component then I keep getting the error (in the browser console):

`Unknown custom element: <mylistitem> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
`

While this might be a vue issue I strongly believe something is messed up with the template or tools causing this as I have tried all options I can think of, even the names of my components are all lower case just so I get no naming problems. Here is my code:

app.ts:
```
import Vue from 'vue';
import { Component } from 'vue-property-decorator';


@Component({
    components: {
        MenuComponent: require('../navmenu/navmenu.vue.html'),
        mylistitem: require('../mylistitem/mylistitem.vue.html')
    }
})
export default class AppComponent extends Vue {
}
```

My list is rendered fine as I have it registered i the boot.ts routes and the navmenu 

mylist.vue.html:
```
<template>
    <div>
        <div>{{ myTitle }}</div>
        <mylistitem/> 
    </div>
</template>

<script src="./mylist.ts"></script>
```

mylist.ts:
```
import Vue from 'vue';
import { Component } from 'vue-property-decorator';

@Component
export default class MyList extends Vue {
    myTitle = "Rendering My List:";
}

```
This is the component that I can't display!

mylistitem.vue.html:
```
<template>
    <div>Hello from my list item</div>
</template>

<script src="./mylistitem.ts"></script>

```
mylistitem.ts:
```
import Vue from 'vue';
import { Component } from 'vue-property-decorator';

@Component({name:'mylistitem'})
export default class mylistitem extends Vue {
    
}


```

**Comment by SteveSandersonMS** [comment]
Sorry, I can't provide Vue usage support here! It doesn't look like anything in your question is specific to any code in this repo or the project template, so please see Vue docs or raise this with the Vue community. Hope that's OK.

**Comment by Zaid-Safadi** [comment]
No worries @SteveSandersonMS, I was thinking this might be something related to the tools being used in the template and webpack so thought I'll raise it here and get some feedback.
