### ISSUE TITLE
Angular-CLI-Based-Template: IE11 Issue

### ISSUE THREAD

**Issue by ryanbuening** [aspnet/JavaScriptServices#1419]
IE11 is throwing an error on line 14 in `ClientApp/node_modules/core-js/modules/_for-of.js` to the console when running an app created with the new Angular-CLI template.

`SCRIPT5022: Exception thrown and not caught`
`eval code (194) (14,36)`
`  if (typeof iterFn != 'function') throw TypeError(iterable + ' is not iterable!');`

IE11 version 11.726.15063.0

**Comment by SteveSandersonMS** [comment]
This behavior comes from Angular (the same thing would happen if you ran a stock `ng new` app in IE 11). Please see Angular docs for information on using polyfills to add IE11 support. Thanks!
