### ISSUE TITLE
Angular CLI-based template

### ISSUE THREAD

**Issue by chamikasandamal** [aspnet/JavaScriptServices#1420]
Shall we communicate with angular team officially and make a common template by involving both teams. 
I can see angular has their own suggestion here
https://github.com/angular/universal/tree/master/modules/aspnetcore-engine

and aspnet team trying to create new template here
https://github.com/aspnet/JavaScriptServices/issues/1288

It would be great if we can combine and share the effort.

**Comment by naveedahmed1** [comment]
With new Angular CLI based template `aspnetcore-engine` is not required any more and may ultimately be discontinued.

**Comment by chamikasandamal** [comment]
@naveedahmed1: I think you are talking about `aspnet-prerendering`  and not `aspnetcore-engine`

**Comment by naveedahmed1** [comment]
I am referring to `aspnetcore-engine` , `aspnet-prerendering` would still be required.

Did you get a chance to look at new template? It still uses `aspnet-prerendering` but doesn't depend on `aspnetcore-engine`.

**Comment by chamikasandamal** [comment]
@naveedahmed1: are you referring angular universal template or https://github.com/aspnet/JavaScriptServices/issues/1288
in aspnet spa templates even in angular 4 version, i didn't saw any dependencies on `aspnetcore-engine`. what i'm thinking is why we can't make common version which both teams can work and recommend.

**Comment by naveedahmed1** [comment]
I am referring to https://github.com/aspnet/JavaScriptServices/issues/1288 which is now aligned with Angular CLI.

**Comment by SteveSandersonMS** [comment]
> Shall we communicate with angular team officially and make a common template by involving both teams.

Updating to an Angular CLI-based template means we now *do* have a common template, because the one included in the .NET SDK is directly equivalent to the one produced by Angular CLI by design.

**Comment by chamikasandamal** [comment]
@SteveSandersonMS : But in angular site, they are referring to some other sample with `aspnetcore-engine`
