### ISSUE TITLE
async / await and AppThunkAction - TypeScript/React/Redux - Question

### ISSUE THREAD

**Issue by jonorogers** [aspnet/JavaScriptServices#1426]
What's the best way to mix the new async/await operators with redux thunk actions when using TypeScript/React/Redux?

I've tried marking the action creator as async:

`requestWeatherForecasts: async (startDateIndex: number): AppThunkAction<KnownAction> => (dispatch, getState) => {`

But it brings up the following error:

> (TS) Type 'AppThunkAction' is not a valid async function return type in ES5/ES3 because it does not refer to a Promise-compatible constructor value.

I've also tried returning async dispatch from the action:

```
requestWeatherForecasts: (startDateIndex: number): AppThunkAction<KnownAction> => (dispatch, getState) => {

        return async dispatch => {

        }
```

But that says dispatch is implicitly any:

> (TS) Parameter 'dispatch' implicitly has an 'any' type.

I've tried various ways of adding the correct type definition to dispatch inline, but can't seem to get anything working.

**Comment by SteveSandersonMS** [comment]
The TypeScript type information here implies that returning a promise is not allowed (as in, it doesn't think that Redux itself is going to work with you doing that). So if you believe the type definitions, this is not supported. If you don't believe the type definitions and want to do it anyway, you can always cast to `any`.

**Comment by jonorogers** [comment]
My bad. I was indicating the method was async in the right place. For anyone else who winds up here, the syntax is:

```
requestWeatherForecasts: (startDateIndex: number): AppThunkAction<KnownAction> => async (dispatch, getState) => {
    dispatch(...)
    await fetch(...)
}
```
