### ISSUE TITLE
Angular-CLI-Based-Template: Help link doesn't work

### ISSUE THREAD

**Issue by naveedahmed1** [aspnet/JavaScriptServices#1427]
The Startup file in new template has below comment

```
         // To learn more about options for serving an Angular SPA from ASP.NET Core,
         // see https://go.microsoft.com/fwlink/?linkid=864501
```

But when we open this link it takes us to https://pastebin.com/raw/sZaduK8a which displays page showing below error:

```
This site can’t be reached

pastebin.com refused to connect.
```

**Comment by Alex-Torres** [comment]
https://docs.microsoft.com/en-us/aspnet/core/spa/index#installation

https://docs.microsoft.com/en-us/aspnet/core/spa/angular?tabs=visual-studio

**Comment by SteveSandersonMS** [comment]
Thanks - the link now redirects correctly.
