### ISSUE TITLE
Angular-CLI-Based-Template: Docker development

### ISSUE THREAD

**Issue by andrelmp** [aspnet/JavaScriptServices#1431]
Created a new project using new angular-cli-based template, opened on VS 2017 and added Docker Support.

When browser opens, no response from server.

Any help or walkthrough how get it work?

**Comment by MarkPieszak** [comment]
What is the error you're getting?
Make sure your container has Node 8+ setup on it.

**Comment by SteveSandersonMS** [comment]
Please see this tip from @dapalmi who made it work: https://github.com/aspnet/JavaScriptServices/issues/1534#issuecomment-366605094
