### ISSUE TITLE
Angular-CLI-Based-Template: Whats the best say to conditionally disable Prerendering

### ISSUE THREAD

**Issue by naveedahmed1** [aspnet/JavaScriptServices#1432]
@SteveSandersonMS for larger apps, its not always required to enable server side rendering for the complete app as there is some additional cost associated for prerendering https://docs.microsoft.com/en-us/aspnet/core/spa/angular?tabs=visual-studio#drawbacks-of-ssr

So, we often enable the SSR for the pages that are either common entry points of our web app or the pages that are crawlable by search engines and disabled prerendering for the rest of the app.

So, whats the best way to disable SSR for the URLs matching certain pattern.

I found `ExcludeUrls` in `SpaPrerenderingOptions`, adding urls to this array skips prerendering for these urls. Is it the most appropriate way?

**Comment by SteveSandersonMS** [comment]
> I found ExcludeUrls in SpaPrerenderingOptions, adding urls to this array skips prerendering for these urls. Is it the most appropriate way?

Yes, that's the easiest way.

If you need logic more complex than just matching against URL path prefixes, then you could instead implement some ASP.NET middleware that runs before `app.UseSpa`, checks whether the incoming URL should return the HTML but without prerendering, and in that case serve your `index.html` file directly (or rewrite the request URL to something in the `ExcludeUrls` array).
