### ISSUE TITLE
URLs requested via Http on the server must be absolute Only in IE11

### ISSUE THREAD

**Issue by NeilIrvingMacc** [aspnet/JavaScriptServices#1433]
Hi,

I have created a new Angular4 project from the latest template via VS2017 and have created my first page.  The page works fine in Chrome and Edge but in IE I get the error 'URLs requested via Http on the server must be absolute' during server pre rendering.

The piece of code that fails is a call to get some data from a WebApi controller:

this.http.post('/api/Content/GetBasicContentByID',
            body, options).subscribe(
            res => {
                this.extractData(res)
            },
            err => { this.handleError(err) });

I did some Googling on this and found this:

https://stackoverflow.com/questions/43300257/system-exception-call-to-node-module-failed-with-error-error-urls-requested-v

and also on here an old issue here which is the same:

https://github.com/aspnet/JavaScriptServices/issues/989

Issue 989 above talks about using BASE_URL now which I can see in my app.module.browser.ts:

 providers: [
        { provide: 'BASE_URL', useFactory: getBaseUrl }
    ]

export function getBaseUrl() {
    return document.getElementsByTagName('base')[0].href;
}

My question is how do I call the getBaseUrl function above from my typescript code behind page / the code at the top of the post

Thanks

Neil

**Comment by mkArtakMSFT** [comment]
Hi @SteveSandersonMS, any thoughts on this?

**Comment by NeilIrvingMacc** [comment]
It seems to be an issue that has been round for a while with Angular v4, similar stuff works a treat in v2 ij IE11 which I you in a website that went live in March

**Comment by NeilIrvingMacc** [comment]
I got this working not sure if something was wrong when I originally did a File > New > Angular etc from VS2017, I created a new project and imported my code and it is fine now
