### ISSUE TITLE
Angular Cli Template: Best way to handle authorization via .NET

### ISSUE THREAD

**Issue by chrisvfabio** [aspnet/JavaScriptServices#1436]
Is there any way to apply .NET authorization using the new Angular SpaPrerendering? Previously I had my HomeController with `[Authorize]` which handled the authorization challenge and then return the prerendered result using NodeServices into razor, but the new middleware doesn't use razor anymore, so what's the best way to trigger authorization on the server (via oidc)

I could use the implicit flow using an angular package, but I prefer to use the hybrid flow with .NET's oidc. Thanks!

**Comment by SteveSandersonMS** [comment]
You can use any ASP.NET middleware before or after the `UseSpa` middleware. For example you could add some middleware to perform authorization. It might look something like the following, though I haven't tested this: https://stackoverflow.com/a/43503879
