### ISSUE TITLE
Can't update React when starting with the React + Redux Template

### ISSUE THREAD

**Issue by AleksandrAlbert** [aspnet/JavaScriptServices#1438]
Hi, I started a dotnet core 2.0 project with the React + Redux template in vs2017.3 . The React version is 15.6.1 by default, and I want to update it to v16.2.2 . 

I tried to do this by right clicking on react in the npm dependices inside of the solution explorer and clicking Update package, but this did not do anything. 

I also tried changing the package versions in the package.json files for 'react', 'react-dom' in the devDependencies section, as well as for the 'react' tar file in in the dependencies section, however when the file is saved the packages still do not update. Note that "16.2.2" showed up in the intellisense when I changed the react version in devDependencies.

How do I go about updating the React package, as v16 has a number of substantial improvements

**Comment by SteveSandersonMS** [comment]
The `npm-shrinkwrap.json` file is overriding your version selections. You should either use `npm install --save (packagename)` (optionally with `@(version)` on the end), which updates the `npm-shrinkwrap.json` file for you, or just delete the `npm-shrinkwrap.json` file and then your exact versions will no longer be controlled. **WARNING** Nothing in the template you're using is tested to work with React 16 or newer versions of any libraries except those specified in the original `npm-shrinkwrap.json` file, so if there are compatibility issues you'll need to resolve those on your own.

Alternatively you could try the new Create-React-App based template (which uses React 16) as described at https://docs.microsoft.com/en-us/aspnet/core/spa/.

**Comment by AleksandrAlbert** [comment]
Thank you Steve, you are my favorite demo presenter btw!
