### ISSUE TITLE
Single-page Application Templates 2.0.0 and .NET 4.6.1

### ISSUE THREAD

**Issue by robfarmergt** [aspnet/JavaScriptServices#1443]
Is there any plan to support .NET 4.6.1 with the new SPA Project Templates? We have some third party SDKs that don't yet support .NET Core.

**Comment by jesuslpm** [comment]
I'm the same situation. For example Oracle managed driver is not yet published for .NET Standard. That is making adopting .NET Core and Angular harder.

**Comment by SteveSandersonMS** [comment]
Yes, both the existing and updated SPA templates support .NET 4.6.1 as well as .NET Core, and always have done. Example: `dotnet new angular --target-framework-override net461`

**Comment by robfarmergt** [comment]
@SteveSandersonMS is there documentation for the different options? I'm attempting to use `--auth SingleOrg` and I'm getting errors.

**Comment by SteveSandersonMS** [comment]
@robfarmergt You can use `--help` (e.g., `dotnet new angular --help`) to get some info about available params. Unfortunately it doesn't list them all - for consistency with other web templates, the SPA templates marks some params as hidden, such as the `target-framework-override` one. Note that no `--auth` param is supported for the SPA templates.
