### ISSUE TITLE
Angular-CLI-Based-Template: No source maps when debugging server-side JavaScript.

### ISSUE THREAD

**Issue by astegmaier** [aspnet/JavaScriptServices#1449]
First of all, I wanted to say thanks to @SteveSanderson for the new angular-cli-based template. It looks awesome, and I can't wait for it to be released for real.

I wanted to report an issue I'm seeing in an effort to help work out the kinks. When I enable server-side rendering using the [instructions in the docs](https://docs.microsoft.com/en-us/aspnet/core/spa/angular?tabs=visual-studio#server-side-rendering), and attempt to debug the pre-rendered JavaScript (following [instructions here](https://github.com/aspnet/JavaScriptServices/tree/dev/src/Microsoft.AspNetCore.SpaServices#debugging-your-javascripttypescript-code-when-it-runs-on-the-server)), I find that the chrome debugger only sees the minified javascript instead of the clean source typescript:

![chrome debugger](https://github.com/astegmaier/dotnet-angular-cli-ssr-debug-test/raw/master/Repro.png)

I tried to create a clean, simplified repro of the issue in this repository: https://github.com/astegmaier/dotnet-angular-cli-ssr-debug-test

Looking at the `ClientApp/dist-server` folder I don't see any `.map` files, which might be related to the cause.

Am I doing something wrong? Or is this an issue with the template?

**Comment by astegmaier** [comment]
This might be related to #1358 and #1342, although those issues were focused on the older template, so I'm not sure--its seems like switching to the CLI significantly changes the pipeline for packaging/transpiling, so this issue might have a different root cause.

**Comment by astegmaier** [comment]
This might be caused by https://github.com/angular/angular-cli/issues/8931

**Comment by SteveSandersonMS** [comment]
I agree this looks like the same issue as https://github.com/angular/angular-cli/issues/8931.

Since Angular CLI now controls the build config in these new templates, issues like how to enable source maps would need to be handled via Angular CLI config so please see their docs/issues for info about that. Thanks!
