### ISSUE TITLE
'ReactDevelopmentServer' does not exist

### ISSUE THREAD

**Issue by rosieks** [aspnet/JavaScriptServices#1452]
I have just reinstalled my computer and when I try to build my project that's based on CreateReactApp template I receive the following errors:

> warning NU1603: Sample.Web depends on Microsoft.AspNetCore.SpaServices.Extensions (>= 2.0.1-preview1-10006) but Microsoft.AspNetCore.SpaServices.Extensions 2.0.1-preview1-10006 was not found. An approximate best match of Microsoft.AspNetCore.SpaServices.Extensions 2.1.0-preview1-27426 was resolved.
> error CS0234: The type or namespace name 'ReactDevelopmentServer' does not exist in the namespace 'Microsoft.AspNetCore.SpaServices' (are you missing an assembly reference?)

**Comment by SteveSandersonMS** [comment]
It looks like your project is still trying to use a very old build of SpaServices.Extensions. I suspect you may have a `NuGet.config` file in your project that references the ASP.NET CI NuGet feed and is trying to pull deleted packages from there.

To clean things up:

 * Run `dotnet nuget locals all --clear` to clear your NuGet cache
 * Remove any `NuGet.config` file from your project (or at least, remove any info from it that tells it to pull packages from the ASP.NET dev CI instance - you should only be getting ASP.NET packages from the main NuGet.org feed now)
 * Make sure the dependencies in your `csproj` files are up-to-date. For example, the current version of SpaServices.Extensions is `2.0.0-preview1-final`.
