### ISSUE TITLE
Angular Cli based SPA template is really slow when calling webapi

### ISSUE THREAD

**Issue by berlstone** [aspnet/JavaScriptServices#1454]
There are lot of calls ajax / websocket calls running in the background which makes the template too slow. 
When we make a call to webapi,  the request will need to wait for quite some time to fetch the result  because the other concurrent websock calls which takes too long to complete.
What are these calls ?
why are they required ?
Any suggestions to disable this multiple calls ?  

![image](https://user-images.githubusercontent.com/1524923/34342793-ba4f394c-e9d4-11e7-8782-0c4ff794df50.png)
![image](https://user-images.githubusercontent.com/1524923/34342796-d3f6eb56-e9d4-11e7-99cc-23d480dafc59.png)

**Comment by SteveSandersonMS** [comment]
> because the other concurrent websock calls which takes too long to complete.
> What are these calls ?
> why are they required ?
> Any suggestions to disable this multiple calls ?

The websocket stuff in the background is what Angular CLI apps use to get notifications when your code is changed and the app should reload. Please see Angular CLI docs for more info about what each of them is for, and whether there are any options for controlling/disabling them. Thanks!
