### ISSUE TITLE
Angular CLI-based template: dotnet publish does not produce a website that can be run

### ISSUE THREAD

**Issue by kadamgreene** [aspnet/JavaScriptServices#1455]
I installed the Angular CLI / Angular 5 based template as per [these instructions](https://github.com/aspnet/javascriptservices/issues/1288), and then ran "dotnet publish" and attempted to run the output.  Got the following error in console:

C:\projects\angular5spa\bin\Debug\netcoreapp2.0\publish>dotnet angular5spa.dll
info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
      User profile is available. Using 'C:\Users\adam.greene\AppData\Local\ASP.N
ET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at r
est.
info: Microsoft.AspNetCore.SpaServices[0]
      Starting @angular/cli on port 54138...
Hosting environment: Development
Content root path: C:\projects\angular5spa\bin\Debug\netcoreapp2.0\publish
Now listening on: http://localhost:5000
Application started. Press Ctrl+C to shut down.
npmfail: Microsoft.AspNetCore.SpaServices[0]
      npm ERR! path C:\projects\angular5spa\bin\Debug\netcoreapp2.0\publish\Clie
ntApp\package.json

npm ERR!fail: Microsoft.AspNetCore.SpaServices[0]
      npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open 'C:\projects\angular5spa
\bin\Debug\netcoreapp2.0\publish\ClientApp\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

fail: Microsoft.AspNetCore.SpaServices[0]
      npm ERR! A complete log of this run can be found in:

and the following in browser:

AggregateException: One or more errors occurred. (The NPM script 'start' exited without indicating that the Angular CLI was listening for requests. The error output was: npm ERR! path C:\projects\angular5spa\bin\Debug\netcoreapp2.0\publish\ClientApp\package.json 
 npm ERR! code ENOENT npm ERR! errno -4058 npm ERR! syscall open npm ERR! enoent ENOENT: no such file or directory, open 'C:\projects\angular5spa\bin\Debug\netcoreapp2.0\publish\ClientApp\package.json' npm ERR! enoent This is related to npm not being able to find a file. npm ERR! enoent 
 npm ERR! A complete log of this run can be found in: 
 )

**Comment by JCPuerto** [comment]
I'm using the same preview template and I haven't had any problems while publishing.

**Comment by SteveSandersonMS** [comment]
Here's your problem:

```
Hosting environment: Development
```

Once published, you need to run your app in production mode for it to work. https://docs.microsoft.com/en-us/aspnet/core/fundamentals/environments#development-staging-production

**Comment by CodingInfinite** [comment]
Solved my problem, Found solution [http://codinginfinite.com/npm-script-start-exited-without-indicating-that-angular-cli-listening-requests/](Here)

**Comment by arisliang** [comment]
@CodingInfinite link doens't work

**Comment by madumal7** [comment]
Just run the below command in command prompt
> IISRESET
