### ISSUE TITLE
2.0.0 SPA Templates & following progress

### ISSUE THREAD

**Issue by robfarmergt** [aspnet/JavaScriptServices#1460]
I just noticed that nuget was updated with the rc1 version. Is there a way to track the progress of the releases to see when the nuget packages are updated? Are there also release notes or somewhere on github to see what has changed between versions?

**Comment by Alex-Torres** [comment]
@robfarmergt I usually go to the nuget site, which was recently updated and it looks great!  Link [here](https://www.nuget.org/packages/Microsoft.AspNetCore.SpaServices.Extensions/2.0.0-rc1-final).  But release notes I usually wait for them to do a blog post.  There is also now a documentation site [here](https://docs.microsoft.com/en-us/aspnet/core/spa/) and [here](https://docs.microsoft.com/en-us/aspnet/core/spa/angular?tabs=visual-studio) that goes into detail on how to use the new extension.

**Comment by SteveSandersonMS** [comment]
> Are there also release notes or somewhere on github to see what has changed between versions?

For the 2.0.0 release of the new templates, nothing is changing between releases any more besides any minor bugfixes that you'd need to watch this git repo issue tracker for. My expectation is that the next release will be the final (i.e., RTM) release and so far there's no indication that we're going to change anything from the RC1. It's basically done and ready to ship now.

As @Alex-Torres describes, the best place to find overall information about the new templates is in the [docs](https://docs.microsoft.com/en-us/aspnet/core/spa/).
