### ISSUE TITLE
Angular cli issue with Claims.

### ISSUE THREAD

**Issue by dantheman999301** [aspnet/JavaScriptServices#1461]
I've been trying out the new Angular Cli template on `Microsoft.DotNet.Web.Spa.ProjectTemplates::2.0.0-preview1-final`. I've ported over a project and everything seems to build fine.

I have some middleware which decrypts a cookie and add some claims onto the User. This is then used in api calls, and works fine pre-cli template.

However, when I run it through the cli template the claims get added successfully but then the claims are empty on the api call.

Don't think I've done anything wrong when moving the code over, and none of the code has changed.

**Comment by SteveSandersonMS** [comment]
Unless I'm misunderstanding, this sounds like an Angular usage question (in that everything you're describing happens client-side). That being the case, could you redirect your question to Angular docs and/or the Angular community? Thanks!

**Comment by dantheman999301** [comment]
Sorry, had actually meant to close this, was entirely my own fault, I'd put the Middleware in slightly the wrong place...
