### ISSUE TITLE
Reducing size of main-client.js

### ISSUE THREAD

**Issue by NeilIrvingMacc** [aspnet/JavaScriptServices#1462]
I am close to doing a UAT deployment of a small Angular4 website (approx. 15 components) to a test server, when I do a publish I see the file sizes in the screenshot below.  This files are smaller than for development and smaller than Angular2 bundles and I have not configured netcore compression yet.

I cannot understand why main-client.js is almost 1MB though and how can I reduce it?  My Components do no more than 1-2 http calls, display lists and / or allow form input.  Its a very simple site.

If I look at main-client.js in VS2017 I notice it duplicates a lot of @License info if that's any clue?

Am I also right in thinking all the Bootstrap, JQuery and Angular stuff ends up in the Vendor file instead?

Thanks

Neil

![deployed](https://user-images.githubusercontent.com/20598580/34625199-b68116e0-f24f-11e7-9f52-2061fe741338.jpg)

**Comment by SteveSandersonMS** [comment]
To profile your bundles and find out exactly what's in each file (and what chain of dependencies has caused this), see Webpack's stats data feature: https://webpack.js.org/api/stats/

Basically you need to run `webpack` on the command line passing the flags mentioned in that webpage to make it generate a `stats.json` file, then you can upload that to their explorer tool to visualise it.
