### ISSUE TITLE
Changing page title when rendering server side - React template

### ISSUE THREAD

**Issue by chris-herring** [aspnet/JavaScriptServices#147]
How would you go about changing the page title when using the React template. To do so client side I can use document.title = 'Counter' however this throws an error when trying to render server side - 'document is not defined'.

**Comment by antmdvs** [comment]
You may want to take a look at:
https://www.npmjs.com/package/react-document-title

I haven't tried this yet so let me know how it goes.

**Comment by chris-herring** [comment]
It does work, thanks.
It uses react-side-effect which seems to store the changes to the title and when it hits the client side it runs the last one. Neat.
