### ISSUE TITLE
Dev Env, IIS Hosting, Error when using HMR with ASP.NET CORE 2.0

### ISSUE THREAD

**Issue by sjsingh85** [aspnet/JavaScriptServices#1475]
I tried info given on this page 
https://blogs.msdn.microsoft.com/webdev/2017/07/13/development-time-iis-support-for-asp-net-core-applications/ 
to host the react+redux asp.net javascript services solution in my local IIS for development purposes. 

Everything is working fine except the error 

> "EventSource's response has a MIME type ("text/html") that is not "text/event-stream". Aborting the connection."

 for HMR.

my virtual directory setup is `http://localhost/myApp` pointing to root of my project.

I have seen this error come in for people trying to run HMR in production env but this is Dev env with IIS hosting.

Also, I have already tried `HotModuleReplacementEndpoint = "/dist/__webpack_hmr"` and tried with some permutations of adding virtual directory name etc. but of no use. 

I want to know if I am doing something wrong /HMR is not supported while hosting in IIS /Or if is this a bug and can be fixed?

Thanks!

**Comment by gioscaduto** [comment]
Hey guy. I've had the same error.

Have you gotten any solution for this error ? 

Thanks you.

**Comment by sjsingh85** [comment]
I started using template of ASP.Net core 2.1 with react template that uses Create-React-App and am using https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#proxying-api-requests-in-development
in development env.
