### ISSUE TITLE
Angular-CLI-Based-Template: SSR Seems broken in Angular CLI 1.7.0-beta.0

### ISSUE THREAD

**Issue by naveedahmed1** [aspnet/JavaScriptServices#1476]
@SteveSandersonMS After upgrade to Angular CLI version 1.7.0-beta.0 the SSR seems to be broken and throw below error:

```
ERROR in ./src/main.server.ts
Module parse failed: Unexpected token (34:21)
You may need an appropriate loader to handle this file type.
| core_1.enableProdMode();
| exports.default = aspnet_prerendering_1.createServerRenderer(function (params) {
|     var _a = (module as any).exports, AppServerModule = _a.AppServerModule, AppServerModuleNgFactory = _a.AppServerModuleNgFactory, LAZY_MODULE_MAP = _a.LAZY_MODULE_MAP;
|     var options = {
|         document: params.data.originalHtml,
 @ multi ./src/main.server.ts
```

Can this be due to the changes introduced in https://github.com/angular/angular-cli/commit/aa90e42 ?

**Comment by JohnGalt1717** [comment]
I'm getting the same thing and 1.7.0 is required to fix another bug with the post-css and bootstrap 4. So completely suck right now.

**Comment by JohnGalt1717** [comment]
A workaround to this for now is to use 1.6.5 of the cli and then remove bootstrap from the angular-cli.json file and import it in your styles.(s)css file.

**Comment by SteveSandersonMS** [comment]
Yes, it looks like different docs will be needed for 1.7.0. But we'll have to wait until 1.7.0 ships to know what the final instructions would be. Thanks for reporting it.

**Comment by naveedahmed1** [comment]
@SteveSandersonMS  1.7 is now released, any update on this issue?

**Comment by SteveSandersonMS** [comment]
I've updated the template to Angular CLI 1.7.0 and the same SSR code is still working correctly. Verified this in dev builds and prod (AOT) builds, both with and without lazy-loading. I guess they already fixed whatever they broke.

**Comment by naveedahmed1** [comment]
Yes you are right, I can confirm its working perfectly with V1.7. Thank you so much :)

**Comment by SteveSandersonMS** [comment]
The final 2.0.0 templates are now released.

    dotnet new --install Microsoft.DotNet.Web.Spa.ProjectTemplates::2.0.0
