### ISSUE TITLE
Knockout template page "Fetch data" giving "fetch is undefined" JS exception

### ISSUE THREAD

**Issue by Gimly** [aspnet/JavaScriptServices#148]
Using the Knockout template, the "Fetch data" page doesn't work. It shows "Loading..." and no data is loaded. The SampleDataController function is never called either.

In the browser console, there is a JS exception that says : 'fetch' is undefined.

Edit: Managed to fix it by adding "isomorphic-fetch": "^2.2.1" to package.json but I'm not sure this is the correct way to do it.

**Comment by SteveSandersonMS** [comment]
Thanks for reporting this! It's now fixed (using `isomorphic-fetch` as you suggested).
