### ISSUE TITLE
.net Core SPA Knockout Template is not available

### ISSUE THREAD

**Issue by KaustubhDiwan** [aspnet/JavaScriptServices#1482]
I am new to net core and want to try sample application with .Net Core 2.0 knockout and SPA.
I installed nugget package Microsoft.AspNetCore.SpaTemplates.
 But I a am not able to see the knockout template getting installed.

**Comment by ridicoulous** [comment]
Unfortunally, this template is not available. You may get list of templates by running `dotnet new`

**Comment by SteveSandersonMS** [comment]
The command to install that template is `dotnet new --install Microsoft.AspNetCore.SpaTemplates::*`.
