### ISSUE TITLE
Wrong middleware behaviour, when ApiExplorer (ApiVersioning) is integrated.

### ISSUE THREAD

**Issue by merqlove** [aspnet/JavaScriptServices#1483]
So, subj.

Problem:
Wrong behavior means, that existing routes (From MVC Razor stack) redirecting/proxy to the React app.

Also posted here:
https://github.com/Microsoft/aspnet-api-versioning/issues/238

For me this behavior looks WRONG!

Sample project, that illustrates this behaviour:
[Sample](https://github.com/Mubicon/aspnet-spa-bug)

I really surprised, that no one has reported this bug.

**Comment by SteveSandersonMS** [comment]
Info at https://github.com/Microsoft/aspnet-api-versioning/issues/238#issuecomment-359280638, so closing this issue in favour of that other bug.
