### ISSUE TITLE
Error in 0.js from UglifyJs Unexpected Character '`', In Dotnet core app with angular template

### ISSUE THREAD

**Issue by RkReddy88** [aspnet/JavaScriptServices#1485]
I am facing an publish fail issue with error core MSB3073:
![image](https://user-images.githubusercontent.com/25411057/35231163-10783b1a-ff66-11e7-824f-122b11080c68.png)

because of the following error in 0.js from uglifjs

![image](https://user-images.githubusercontent.com/25411057/35231101-e2336630-ff65-11e7-92b9-e08cf1bb362f.png)

The code at that line is 
![image](https://user-images.githubusercontent.com/25411057/35231260-51d60a06-ff66-11e7-84a4-059b77f95766.png) 

which is generated from the NPM package dicom-parser where I am using Cornerstone Wado Image Loader to render dicom images(.dcm) in the browser which I am able to do in debugging mode but failed to publish. 
Can someone help me in solving this issue.
Thank you in advance.

**Comment by SteveSandersonMS** [comment]
It looks like your version of uglify doesn't support JavaScript interpolated strings (i.e., those delimited by backtick characters). This isn't something controlled by any of the code in this repo. Please check uglify and/or dircom-parser docs for suggestions on how to make them work together.
