### ISSUE TITLE
HMR With Riot JS

### ISSUE THREAD

**Issue by pushqrdx** [aspnet/JavaScriptServices#1487]
I can't get riot's hmr to work in a simple web app running under IIS Express using Webpack. HMR Connects normally and when i ever i do changes to a tag it re compiles and says app is up to date.

Log:
```

[HMR] connected
[HMR] bundle rebuilding
[HMR] bundle rebuilt in 16ms
[HMR] Checking for updates on the server...
[HMR] Updated modules:
[HMR]  - ./ClientApp/random.tag
[HMR] App is up to date.
```

I have put together a sample VS Project [here](https://github.com/pushqrdx/Riot-IIS-Issue/) to explain what i have tried so far and reproduce that.

**Comment by SteveSandersonMS** [comment]
Thanks for supplying the demo app, but I'm afraid we can't debug issues related to third-party frameworks. If you're able to track this down to something you think is a bug in any of the ASP.NET Core packages then please let us know. Sorry!
