### ISSUE TITLE
Angular-CLI - Hot Module Replacement (HMR) Full Page Refresh when run from VS

### ISSUE THREAD

**Issue by LinqBeast** [aspnet/JavaScriptServices#1489]
Using latest Angular-CLI template:

https://www.nuget.org/packages/Microsoft.DotNet.Web.Spa.ProjectTemplates/2.0.0-rc1-final

Created new project with:  dotnet new angular

Opened in VS 2017 15.5.4

Ran with F5, JS Debugging with ASP.NET disabled

Modified home.component.html only and saved, but got full page refresh ??? everytime I saved

"dotnet run" and "npm start" work fine

"ng serve" does full page refresh

**Comment by LinqBeast** [comment]
Any reason HMR wouldn't work by default?

It seems to, in that when I save an html file, the browser refreshes, but it's a full page refresh.

**Comment by LinqBeast** [comment]
Even with "dotnet run" and "npm start", I get full page refreshes on save if I have more than one module in my app... and it doesn't have to be for lazy-loaded components/views - same problem with a module that loads services (providers) only.

If I only have one module in the app, where I load all components and services, HMR works fine with "dotnet run" and "npm start".  Of course, starting from VS still gives full page refresh.

**Comment by LinqBeast** [comment]
As soon as I import a service (class with @injectable() decorator), I get the same problem.

**Comment by SteveSandersonMS** [comment]
Angular CLI does full-page refreshes by default. Please see Angular CLI docs for info about setting up HMR.

**Comment by LinqBeast** [comment]
I figured that much, but when I set it up according to:|

https://github.com/angular/angular-cli/wiki/stories-configure-hmr

It works fine as long as I don't run through VS.  Run from VS, it seems fine the first few refreshes, but then it becomes painfully slow.

**Comment by LinqBeast** [comment]
Okay. :)  Working now, doing the same as above.

Think it was an issue I fixed with LazyLoading trying to figure this out.

Thanks for all you do...
