### ISSUE TITLE
Issues adding Bootstrap 4

### ISSUE THREAD

**Issue by mohsinma** [aspnet/JavaScriptServices#1496]
After adding bootstrap 4 (along with popper.js and JQuery). ng build/ng serve is broken.
error message below:

_ERROR in ./node_modules/css-loader?{"sourceMap":false,"importLoaders":1}!./node_modules/postcss-loader/lib?{"ident":"postcss","sourceMap":false}!./node_modules/bootstrap/dist/css/bootstrap.min.css
Module build failed: BrowserslistError: Unknown browser major
    at error (D:\TestApps\DotNetCoreCli-Bootstrap\ClientApp\node_modules\browserslist\index.js:37:11)
    at Function.browserslist.checkName (D:\TestApps\DotNetCoreCli-Bootstrap\ClientApp\node_modules\browserslist\index.js:320:18)_

 FYI: tried importing boostrap.css in the algular-cli.json and also tried importing it in the styles.css, nothing seems working
When I revert back to bootstrap 3.3.7 it works fine.

**Comment by rohan-buchner** [comment]
I'm currently using Bootstrap 4 with a completely customized build. I've used the following loader with a lot of success in previous projects as well, and can highly recommend it. [bootstrap-loader](https://github.com/shakacode/bootstrap-loader)

**Comment by SteveSandersonMS** [comment]
This is an Angular CLI usage question, so please direct it to the Angular CLI project. Hope that's OK!
