### ISSUE TITLE
React Redux Template does not work with typescript@next

### ISSUE THREAD

**Issue by ILL35T** [aspnet/JavaScriptServices#1497]
React Redux Template does not work with the latest typescript.
VS2017 > File > New > React Redux SPA Template
Change typescript version in package.json to: "typescript": "^2.8.0-dev.20180126"

Project fails to build and produces the following errors:

> ERROR in [at-loader] ./ClientApp/components/Counter.tsx:31:3 
    TS2345: Argument of type 'typeof Counter' is not assignable to parameter of type 'Component<CounterState>'.
  Type 'typeof Counter' is not assignable to type 'StatelessComponent<CounterState>'.
    Type 'typeof Counter' provides no match for the signature '(props: CounterState & { children?: ReactNode; }, context?: any): ReactElement<any> | null'.
ERROR in [at-loader] ./ClientApp/components/FetchData.tsx:73:3 
    TS2345: Argument of type 'typeof FetchData' is not assignable to parameter of type 'Component<WeatherForecastsState>'.
  Type 'typeof FetchData' is not assignable to type 'StatelessComponent<WeatherForecastsState>'.
    Type 'typeof FetchData' provides no match for the signature '(props: WeatherForecastsState & { children?: ReactNode; }, context?: any): ReactElement<any> | null'.
ERROR in [at-loader] ./ClientApp/configureStore.ts:20:19 
    TS2349: Cannot invoke an expression whose type lacks a call signature. Type '{}' has no compatible call signatures.
ERROR in [at-loader] ./ClientApp/routes.tsx:10:12 
    TS2322: Type '{ path: string; component: typeof Counter; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Route> & Readonly<{ children?: ReactNode; }> & Rea...'.
  Type '{ path: string; component: typeof Counter; }' is not assignable to type 'Readonly<RouteProps>'.
    Types of property 'component' are incompatible.
      Type 'typeof Counter' is not assignable to type 'StatelessComponent<RouteComponentProps<any> | undefined> | ComponentClass<RouteComponentProps<any...'.
        Type 'typeof Counter' is not assignable to type 'ComponentClass<RouteComponentProps<any> | undefined>'.
          Types of parameters 'props' and 'props' are incompatible.
            Type 'RouteComponentProps<any> | undefined' is not assignable to type 'CounterProps | undefined'.
              Type 'RouteComponentProps<any>' is not assignable to type 'CounterProps | undefined'.
                Type 'RouteComponentProps<any>' is not assignable to type 'CounterProps'.
                  Type 'RouteComponentProps<any>' is not assignable to type 'CounterState'.
                    Property 'count' is missing in type 'RouteComponentProps<any>'.
ERROR in [at-loader] ./ClientApp/routes.tsx:11:12 
    TS2322: Type '{ path: string; component: typeof FetchData; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Route> & Readonly<{ children?: ReactNode; }> & Rea...'.
  Type '{ path: string; component: typeof FetchData; }' is not assignable to type 'Readonly<RouteProps>'.
    Types of property 'component' are incompatible.
      Type 'typeof FetchData' is not assignable to type 'StatelessComponent<RouteComponentProps<any> | undefined> | ComponentClass<RouteComponentProps<any...'.
        Type 'typeof FetchData' is not assignable to type 'ComponentClass<RouteComponentProps<any> | undefined>'.
          Types of parameters 'props' and 'props' are incompatible.
            Type 'RouteComponentProps<any> | undefined' is not assignable to type 'WeatherForecastProps | undefined'.
              Type 'RouteComponentProps<any>' is not assignable to type 'WeatherForecastProps | undefined'.
                Type 'RouteComponentProps<any>' is not assignable to type 'WeatherForecastProps'.
                  Type 'RouteComponentProps<any>' is not assignable to type 'WeatherForecastsState'.
                    Property 'isLoading' is missing in type 'RouteComponentProps<any>'.
ERROR in [at-loader] ./node_modules/@types/react/index.d.ts:109:81 
    TS2344: Type 'ChangeTargetHTMLAttributes<T>' does not satisfy the constraint 'DOMAttributes<T>'.
  Types of property 'onChange' are incompatible.
    Type 'EventHandler<ChangeEvent<T>> | undefined' is not assignable to type 'EventHandler<FormEvent<T>> | undefined'.
      Type 'EventHandler<ChangeEvent<T>>' is not assignable to type 'EventHandler<FormEvent<T>> | undefined'.
        Type 'EventHandler<ChangeEvent<T>>' is not assignable to type 'EventHandler<FormEvent<T>>'.
          Types of parameters 'event' and 'event' are incompatible.
            Type 'FormEvent<T>' is not assignable to type 'ChangeEvent<T>'.
              Types of property 'target' are incompatible.
                Type 'EventTarget' is not assignable to type 'EventTarget & T'.
                  Type 'EventTarget' is not assignable to type 'T'.
ERROR in [at-loader] ./node_modules/@types/react/index.d.ts:2479:15 
    TS2430: Interface 'ChangeTargetHTMLAttributes<T>' incorrectly extends interface 'HTMLAttributes<T>'.
  Types of property 'onChange' are incompatible.
    Type 'EventHandler<ChangeEvent<T>> | undefined' is not assignable to type 'EventHandler<FormEvent<T>> | undefined'.
      Type 'EventHandler<ChangeEvent<T>>' is not assignable to type 'EventHandler<FormEvent<T>> | undefined'.
        Type 'EventHandler<ChangeEvent<T>>' is not assignable to type 'EventHandler<FormEvent<T>>'.
          Types of parameters 'event' and 'event' are incompatible.
            Type 'FormEvent<T>' is not assignable to type 'ChangeEvent<T>'.
              Types of property 'target' are incompatible.
                Type 'EventTarget' is not assignable to type 'EventTarget & T'.
                  Type 'EventTarget' is not assignable to type 'T'.

**Comment by SteveSandersonMS** [comment]
Sorry for the inconvenience. You can either cast to `any` or stick with the older version of TypeScript.

This issue doesn't apply to the newer React template (because it doesn't use TypeScript) so it's effectively fixed, in that no change to the code in our repos would be relevant, hence closing.

**Comment by Vladis466** [comment]
@SteveSandersonMS

**Comment by xzessmedia** [comment]
3 Months now, don't expect an answer
