### ISSUE TITLE
Getting domain during SSR

### ISSUE THREAD

**Issue by AleksandrAlbert** [aspnet/JavaScriptServices#1498]
I am writing an app building on the React + Redux SPA which has a client and an api at different domains, something like this:

[local]
localhost:5000 (client)
localhost:5001 (api)

[web]
app.domain.com (client)
api.domain.com (api)

Now, when writing my fetch requests, I'd like to be able to send requests to the localhost api when I make requests from the localhost client, and the web api when requested from the web client. To do this, I have to be able to set my base url, so I am trying to write a `getApiDomain` method which I can use to pick the right domain.

```
let fetchTask = fetch(`${Domain.getApiDomain()}/api/Item/${id}`)...
```

My method looks like this:

```
export abstract class Domain {
    public static isLocalhost = Boolean(window.location.hostname === 'localhost' );

    public static getApiDomain(): string {

        return this.isLocalhost
            ? "http://localhost:5001"
            : "http://api.domain.com";
    }
}

```

This works well for the client, but I can't get it to work on the server during SSR due to the use of `window`. How can I get the hostname while executing on the server?

**Comment by AleksandrAlbert** [comment]
I was able to solve this problem in the end. The key here was remembering that if we are on the server we are executing in Node, so I created an environment variable on my localhost machine and made the following change to my Domain class:

```
export abstract class Domain {
    
    public static isLocalhost() : boolean {
        if (window) {
            // Get hostname on client
            return Boolean(window.location.hostname === 'localhost' );
        } else {
            // Check to see if we are running on localhost by checking some environment variable
            return !(process.env.LOCALHOST_ENV === null);
        }
    }

    public static getApiDomain(): string {

        return this.isLocalhost()
            ? "http://localhost:5001"
            : "http://api.domain.com";
    }
}
```

**Comment by rohan-buchner** [comment]
@AleksandrAlbert I also struggled with that for a while, the solution I ended up using was to set  the base url in both the `boot-server.tsx` & `boot-client.tsx` files. You can make use of the following to set it during startup.
```
import { baseUrl } from 'domain-task';

// server
baseUrl("http://localhost:5001");

// then on boot client
baseUrl("http://api.domain.com");
```

**Comment by AleksandrAlbert** [comment]
@rohan-buchner Ah I see, I could do 

`baseUrl(Domain.getApiDomain())`

**Comment by SteveSandersonMS** [comment]
Glad you found a solution!
