### ISSUE TITLE
Update Angular template so that FetchDataComponent emulates what AngularCLI generates

### ISSUE THREAD

**Issue by PurdueGuy531** [aspnet/JavaScriptServices#1500]
Can you please update the Angular template so that by default the FetchDataComponent emulates what the AngularCLI generates when you add a new component via ng g c MyComponent? 

More specifically: 
1) IMPORTANT: Implement OnInit and make your service call within the ngOnInit() method.

2) Consider injecting in a service class and wrapping your weatherforecast logic in that service. This demonstrates dependency injection and is more unit test friendly. 

2B) If that's to much - maybe just a code comment that states that this is a simple example with 'http.get' and that the more recommended approach is to pass in a service class to trigger in ngOnInit, ideally using observables (via .subscribe).

Great work guys! keep it up!

-Chris

**Comment by SteveSandersonMS** [comment]
Would you consider submitting a PR for item 1 on your list?

For item 2, this is something we're specifically avoiding to minimise concept count like you suggested, but yes we could add a comment linking to some Angular docs about service classes.
