### ISSUE TITLE
Consider adding --mvc flag to dotnet new angular command

### ISSUE THREAD

**Issue by PurdueGuy531** [aspnet/JavaScriptServices#1501]
Please consider adding --mvc flag to "dotnet new angular" command so that the resulting dotnet core app is wired-up with MVC core as well. I build a lot of 'hybrid apps' - where we utilize MVC views/controllers for some SEO friendly pages, login, change password, user profile page, etc. - easier then pre-rendered Angular. 

As-is, I run your command then wire-up the MVC portions (treating it like an 'empty MVC core project') .It'd definitely be handy to have an --mvc flag if possible. OR, maybe it makes more sense to have an --angular flag on the "dotnet new mvc" command? 

With the usual 'No Authentication', 'Windows Authentication', etc. authentication options and default MVC layout page and styling you get when creating a new MVC project.

Thanks again and keep up the great work!
Chris

**Comment by SteveSandersonMS** [comment]
The SPA templates already do produce MVC-enabled applications, in that the `Startup.cs` contains `UseMvc` and there's already an MVC controller in the app.

> With the usual 'No Authentication', 'Windows Authentication', etc. authentication options and default MVC layout page and styling you get when creating a new MVC project.

Supporting auth in a way that ties in with Angular is a more complex task we already have on the backlog at https://github.com/aspnet/JavaScriptServices/issues/548

Not sure if that covers everything you're requesting, but please let us know if not.
