### ISSUE TITLE
Error deploy site in server

### ISSUE THREAD

**Issue by Eilon** [aspnet/JavaScriptServices#1504]
_From @MansoorJafari on January 29, 2018 8:42_

Hi
after publish  site and put to server  give me this error.

<img width="980" alt="screen shot 1396-11-08 at 23 15 56" src="https://user-images.githubusercontent.com/15822698/35500970-a0b763c2-04ed-11e8-8f8b-d15093233daa.png">
 please help me.

_Copied from original issue: aspnet/Home#2833_

**Comment by Eilon** [comment]
_From @Tratcher on January 29, 2018 15:6_

Did you have trouble with the instructions on the error page?

**Comment by Eilon** [comment]
_From @MansoorJafari on January 29, 2018 17:52_

@Tratcher 
Thanks for your answer. I have trouble after publish site and put to server.
Works well on my device locally, just have error in win server.
my Startup.cs is this

```c#
if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
                app.UseWebpackDevMiddleware(new WebpackDevMiddlewareOptions
                {
                    HotModuleReplacement = true
                });
            }
            else
            {
                app.UseExceptionHandler("/Home/Error");
            }
```

after delete else statement page not loaded and gives me 403.1 error.

**Comment by Eilon** [comment]
_From @Tratcher on January 29, 2018 18:44_

What server are you using? Here are the troubleshooting instructions for IIS https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/troubleshoot

**Comment by Eilon** [comment]
_From @MansoorJafari on January 29, 2018 18:50_

I'm using windows server 2012

**Comment by Eilon** [comment]
_From @MansoorJafari on January 29, 2018 20:49_

An error occurred while starting the application.

```
AggregateException: One or more errors occurred. (Webpack dev middleware failed because of an error while loading 'aspnet-webpack'. Error was: Error: Cannot find module 'aspnet-webpack'
at Function.Module._resolveFilename (module.js:538:15)
at Function.Module._load (module.js:468:25)
at Module.require (module.js:587:17)
at require (internal/module.js:11:18)
at Object.<anonymous> (C:\WINDOWS\TEMP\vt0hiogs.umy:83:19)
at __webpack_require__ (C:\WINDOWS\TEMP\vt0hiogs.umy:20:30)
at createWebpackDevServer (C:\WINDOWS\TEMP\vt0hiogs.umy:62:26)
at C:\WINDOWS\TEMP\5et1uyuh.c1b:114:19
at IncomingMessage.<anonymous> (C:\WINDOWS\TEMP\5et1uyuh.c1b:133:38)
at emitNone (events.js:106:13)
```

give me this error

**Comment by SteveSandersonMS** [comment]
> Webpack dev middleware failed because of an error

Webpack dev middleware should not be used in production. It's a dev-time feature only.

It looks like you already have some code that's meant to disable it in production:

```csharp
if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
                app.UseWebpackDevMiddleware(new WebpackDevMiddlewareOptions
                {
                    HotModuleReplacement = true
                });
            }
            else
            {
                app.UseExceptionHandler("/Home/Error");
            }
```

So, if it's still trying to run Webpack dev middleware, that implies you're running in development mode even after publishing. You should make sure your production server runs in production mode. For more info, please see https://docs.microsoft.com/en-us/aspnet/core/fundamentals/environments#development-staging-production
