### ISSUE TITLE
UseSpaStaticFiles and UserSpa should return with IApplicationBuilder

### ISSUE THREAD

**Issue by pherbel** [aspnet/JavaScriptServices#1505]
UseSpaStaticFiles and UseSpa extension methods are void and not return with  IApplicationBuilder as any other AppBuilder extension method in Asp.Net Core

Is there any reason why they are void? If there is no, then it would be great to return with IApplicationBuilder.

Thanks

**Comment by SteveSandersonMS** [comment]
Thanks for the suggestion. If you're keen, would you be interested in submitting a PR to this effect?

Closing pending any PR.

**Comment by pherbel** [comment]
Here is the PR #1547
