### ISSUE TITLE
config.devServer options ignored

### ISSUE THREAD

**Issue by MJLHThomassen-Eurocom** [aspnet/JavaScriptServices#1506]
When specifying devServer options in my webpack config, it looks like all these settings are ignored by app.UseWebpackDevMiddleware();

webpack.config.js example:

```
const errorOverlayMiddleware = require('react-dev-utils/errorOverlayMiddleware');
const noopServiceWorkerMiddleware = require('react-dev-utils/noopServiceWorkerMiddleware');
(...)

module.exports = {
(...)
    devServer: {
        before(app)
        {
            app.use(errorOverlayMiddleware());
            app.use(noopServiceWorkerMiddleware());
        }
    }
(...)
}
```

When running webpack via the command line, the error overlay middleware shows me runtime erros in file. When running integrated in my asp.net core app with app.UseWebpackDevMiddleware(); this does not work.

Are the devServer settings ignored? If so, is there a way to achieve setting things like devServer middleware a different way?

**Comment by SteveSandersonMS** [comment]
> Are the devServer settings ignored?

Yes, because it's not using Webpack's own dev server at all. It's being served by ASP.NET instead.

> If so, is there a way to achieve setting things like devServer middleware a different way?

You can configure `webpack.config.js` arbitrarily to change how the bundles get built, but I'm afraid it's still totally different to Webpack's own dev server.

**Comment by MJLHThomassen-Eurocom** [comment]
So no way to customize these settings and nothing on the roadmap to enable this then?

**Comment by SteveSandersonMS** [comment]
@MJLHThomassen-Eurocom It doesn't use Webpack's built in dev server, so those settings aren't applicable.

**Comment by MJLHThomassen-Eurocom** [comment]
Ok, thanks for clarification.
