### ISSUE TITLE
Cannot get Angular-CLI template installed

### ISSUE THREAD

**Issue by ShaneCourtrille** [aspnet/JavaScriptServices#1507]
I followed the instructions as per [#1288 (comment)](https://github.com/aspnet/JavaScriptServices/issues/1288#issuecomment-346003334) and while there were no errors at any step of the way the generated code did not have the Views directory and there was still a UseSpa call.  I deleted my .templateengine directory and tried again with the VS2017 developer command prompt running as Admin but same results.

I checked in the .templateengine directory after my latest attempt and I do see `microsoft.dotnet.web.spa.projecttemplates.2.0.0-preview1-final.nupkg` but I also see `microsoft.dotnet.web.spa.projecttemplates.2.0.5.nupkg` so wondering if that overrides it?

Thoughts?

**Comment by SteveSandersonMS** [comment]
I think you've misread the setup instructions. With the new template, you should *not* have a Views directory, and you *should* have a UseSpa call. So it sounds like you do have the template installed correctly.
