### ISSUE TITLE
performance issue with asp.net core mvc + angular

### ISSUE THREAD

**Issue by mkArtakMSFT** [aspnet/JavaScriptServices#1510]
_From @mchenx on January 30, 2018 17:14_

I have run a few tests recently by using AB (Apache Bench) and noticed the performance for asp.net core 2.0 mvc looks good to me, over 1,000 requests/sec for accessing /home (300 requests, 100 concurrency)

But when I created the asp.net core mvc + angular, I got only 14 requests/sec performance for accessing /home, way slower (300 requests, 100 concurrency)

I am wondering if there is anything wrong with my test setup. 
Has anyone encountered this kind of issue?

I tried this on both windows 10 and macOS 10.13, similar outcome

After investigate a bit, I think it runs slow for two reasons：
1   the site created by using angular template renders page on server side as there is the asp-prerender-module="ClientApp/dist/main-server" attribute in <app> node

2  it uses IIS

After removed the asp-prerender-module attribute and ran the site by executing "dotnet run" (which means using kestrel directly), I got over 460 requests/sec on a desktop pc.

However, when I tried to deploy the site on Azure Web App, but it seems I can only deploy it using IIS, which  turned out very slow, just like running on iis express locally.

Any way this is not an issue that relates to asp.net core.. I'll looking to the aspNetCoreModule for IIS.

_Copied from original issue: aspnet/Mvc#7318_

**Comment by mchenx** [comment]
As this is moved here, if I'm not wrong this (#1510) is a bug related to angular server rendering, and the fix will have nothing to do with the aspNetCoreModule, right? So my issue will remain as I can reproduce this without angular...

**Comment by SteveSandersonMS** [comment]
Server-side rendering (SSR) is expensive as it involves starting up an entire Angular application. SSR is most useful in scenarios where you aren't dealing with extremely high traffic, but you do have users on low-end mobile devices or slower network connections.

In the next update to the Angular template, SSR is not enabled by default. Developers should enable it if they think it's relevant for their app goals. We've written [a bit more about the tradeoffs here](https://docs.microsoft.com/en-us/aspnet/core/spa/angular?tabs=visual-studio#drawbacks-of-ssr).

We don't currently have any specific plans to change anything that would affect the performance, so I'll close this for now. If anyone has proposals for specific changes to improve performance, please let us know!
