### ISSUE TITLE
domain-tasks fetch lacks response type information

### ISSUE THREAD

**Issue by RyanLamansky** [aspnet/JavaScriptServices#1511]
The domain-tasks library has `fetch` returning `Promise<any>`, but should return a well-defined structure as the one found in lib.dom.d.ts:

Excerpt from that file:
```TypeScript
interface Response extends Object, Body {
    readonly body: ReadableStream | null;
    readonly headers: Headers;
    readonly ok: boolean;
    readonly status: number;
    readonly statusText: string;
    readonly type: ResponseType;
    readonly url: string;
    readonly redirected: boolean;
    clone(): Response;
}

declare function fetch(input: RequestInfo, init?: RequestInit): Promise<Response>;
```

If it's intended to wrap the common fetch function perfectly, it should directly reference the types from lib.dom.d.ts.

**Comment by SteveSandersonMS** [comment]
Thanks for the suggestion. If this is important to you, please consider submitting a pull request for it.
