### ISSUE TITLE
Release date for the new Angular CLI template?

### ISSUE THREAD

**Issue by jrmcdona** [aspnet/JavaScriptServices#1513]
Apoligies if this has been said.  I stopped following progress for a bit while doing another project.

It looks like this is still in preview mode.   Is there any word on when it will officially released?

**Comment by Eilon** [comment]
@jrmcdona hopefully very soon! We've done a preview and an RC (release candidate) of new support for this: https://www.nuget.org/packages/Microsoft.AspNetCore.SpaServices.Extensions/2.0.0-rc1-final

So assuming we don't get any feedback that would cause us to reset that, we're just about ready to go to ship it.

**Comment by jrmcdona** [comment]
Thanks @Eilon  I just created a project using:
dotnet new --install Microsoft.DotNet.Web.Spa.ProjectTemplates::2.0.0-rc1-final
dotnet new angular

and Index.html is not found and fails. 

I can log a new issue now.

**Comment by Eilon** [comment]
@jrmcdona sorry you're running into that, we'll investigate.

@SteveSandersonMS any thoughts on this?

**Comment by Eilon** [comment]
Ah, I see you filed it in https://github.com/aspnet/JavaScriptServices/issues/1514, so we'll take a look at that. Thanks!

**Comment by SteveSandersonMS** [comment]
@jrmcdona Because Angular CLI itself has changed in a few ways, we'll need to make some updates and then ship an RC2 version of the new templates package first. Hopefully this will be in the next week.

Hopefully we can ship the final release within a week of the RC2, assuming there are no blockers.

**Comment by SteveSandersonMS** [comment]
It's now released: https://www.nuget.org/packages/Microsoft.DotNet.Web.Spa.ProjectTemplates/2.0.0

To install,

    dotnet new --install Microsoft.DotNet.Web.Spa.ProjectTemplates::2.0.0
