### ISSUE TITLE
Make NpmScriptRunner public

### ISSUE THREAD

**Issue by tpetrina** [aspnet/JavaScriptServices#1515]
This class is very useful for starting other npm based projects and it is a shame that currently I need to duplicate it in my code.

**Comment by SteveSandersonMS** [comment]
Thanks for the suggestion. It's not something we specifically have planned to do at the moment (because every bit of public API we expose is a maintenance contract forever), but if others continue to show interest in this we could review that.

**Comment by tpetrina** [comment]
Thanks for the info, I'll extract it manually then.
