### ISSUE TITLE
HMR (Hot Module Replacement) and hot reloading for the build folder of the React app created by create-react-app

### ISSUE THREAD

**Issue by farzadmf** [aspnet/JavaScriptServices#1516]
Hello,

I'm trying to integrate a react app created by this service into an external application by including the `JS` and `CSS` files created by running `build` from the React app. In other words, the project created by this service would act as a file server to serve the bundled JS and CSS files.

For this reason, I have a new NPM script in my `package.json` (say, `build-rename`) to rename (and remove the hash) from the resulting files created by the `build` command from `create-react-app`

Right now, whenever I change something in my React application, I have to run the NPM script manually to update the files being served by the server.

I was wondering if there's a way to enable hot reloading so that I will have the same convenience as running the app normally

**Comment by SteveSandersonMS** [comment]
Since this question is specifically about React and the create-react-app scripts, you'd be better off raising it with the create-react-app community. Hope that's OK!
