### ISSUE TITLE
Angular-CLI Template RC1 recompile very slow in

### ISSUE THREAD

**Issue by tonywr71** [aspnet/JavaScriptServices#1519]
On making a change to my application and hitting save, the application is talking a lot more time to hot-module-replace, far longer than using the pre angular-cli template.

**Comment by SteveSandersonMS** [comment]
It does take longer, that's true. Unfortunately the speed of Angular CLI is outside our control.

**Comment by tonywr71** [comment]
It's so slow that I've returned to using JIT compilation in the old template, as I don't need pre-rendering. The experience is superior IMHO.
