### ISSUE TITLE
.NET Core 2 Pre-render external compiled angular app 

### ISSUE THREAD

**Issue by meirib** [aspnet/JavaScriptServices#1521]
We'd like to use the .NET MVC core 2 mainly for serving an existing compiled version of angular application, that we build elsewhere (continuous integration build)

Is it possible to pre-render (through index.cshtml app: asp-prerender-module) a compiled app of angular cli build, while hosting the compiled "dist" folder inside wwwroot/dist folder?

Thanks

**Comment by SteveSandersonMS** [comment]
Yes, please see docs on `asp-prerender-module`: https://github.com/aspnet/JavaScriptServices/tree/dev/src/Microsoft.AspNetCore.SpaServices#server-side-prerendering

You'll need to work out for yourself what specific JavaScript code is needed on the receiving side to invoke your own precompiled application and get its output in the right format.

**Comment by meirib** [comment]
@SteveSandersonMS Thank you for your reply. 
Could you please guide me through?
Suppose I have all *.js/*.css bundles - should I only invoke boot-server.js with certain code on my end?
