### ISSUE TITLE
Question: Having subpath/Virtual Directory in IIS hosted development setup

### ISSUE THREAD

**Issue by sjsingh85** [aspnet/JavaScriptServices#1523]
I am using Microsoft.DotNet.Web.Spa.ProjectTemplates::2.0.0-rc1-final which internally uses Create-react-app and AspnetCore.ReactDevelopmentServer

My Dev. Environment is using IIS for hosting multiple api's say api1 as http://localhost/api1 and api2 as http://localhost/api2

Problem is if I host my Asp.Net core React app from Microsoft.DotNet.Web.Spa.ProjectTemplates::2.0.0-rc1-final template to http://localhost/myApp - it expects the files are always served with PublicPath "/" and hence does not work.

This feature is due for release in react-scripts 2.0 which should include https://github.com/facebook/create-react-app/pull/1887. This will allow subpaths to be included in url from where the files are being served in create-react-app.

Just wanted to check if there is any work around for it at this time?

**Comment by SteveSandersonMS** [comment]
> Just wanted to check if there is any work around for it at this time?

We're limited to what create-react-app itself offers, so please see create-react-app docs for any techniques to control what URLs it looks for resources at. Hope that's OK!

**Comment by sjsingh85** [comment]
For people coming to this thread - create-react-app has a proxy api requests feature - https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#proxying-api-requests-in-development which helped in my case
