### ISSUE TITLE
Hitting a breakpoint in webpack.config.js ('This breakpoint will not currently be hit')

### ISSUE THREAD

**Issue by JohnGoldsmith** [aspnet/JavaScriptServices#1524]
I've followed the docs [here](https://github.com/aspnet/JavaScriptServices/tree/dev/src/Microsoft.AspNetCore.SpaServices#debugging-your-javascripttypescript-code-when-it-runs-on-the-server) on debugging server side js but am still not able to debug my webpack.config.js file.

```
services.AddNodeServices(options => {
    options.LaunchWithDebugging = true;
    options.DebuggingPort = 9229;
});
```
I'm assuming that that the webpack config code is run in the node instance prior to the browser being launched, but is there a good way of using a breakpoint in there?

[In VS 2017 15.5.6]

**Comment by JohnGoldsmith** [comment]
I'll update here just incase this helps anyone else:
  
My goal here was to debug my webpack.config.js to find out why I wasn't getting a production build and I've since realised I was making the (now) obvious mistake of not calling webpack in the first place.  I've got so used to it running automatically in development with UseWebpackDevMiddleware + HotModuleReplacement that I completely forgot about the prod version.
  
So I've now added an npm script via Task Runner Explorer + [NPM Task Runner](https://marketplace.visualstudio.com/items?itemName=MadsKristensen.NPMTaskRunner) so that '`webpack --env production`' is called before build.
  
I've also managed to labouriously step through webpack.config.js using:
  
`node --inspect-brk=9229 ./node_modules/webpack/bin/webpack.js --config webpack.config.js 
`   
This is useful for better understanding webpack but not great for productivity :)

....so if anyone has a trick to just debug directly in Visual Studio, as part of the build process I'd love to hear about it.

**Comment by SteveSandersonMS** [comment]
We don't support using VS to debug the Node code that runs via NodeServices. Rather, the options you mentioned (`LaunchWithDebugging`, etc.) are a way of launching the Node process with the debug flag so you can connect to it using Node inspector. This is basically equivalent to what you figured out by calling `node --inspect...` manually.

**Comment by JohnGoldsmith** [comment]
Ok.  Thanks very much for the followup.  I guess I wasn't sure if the node instance you get from `LaunchWithDebugging` was the same one as the one created UseWebpack and HMR.  It would be great if there was a simpler way to hit breakpoints in webpack.config.js without all of the code stepping in webpack.js, but I understand (a little better now) the restrictions.  Thanks again. John

**Comment by xxred** [comment]
@JohnGoldsmith  The following example might work for you. It
is using VS Code to debug the Node code that runs via NodeServices.

1. 断点在下图所示位置，运行一次InvokeExportAsync，仅仅为了成功附加进程
The breakpoint is in the position shown below。Run InvokeExportAsync once, just for Attach.
![7t 3t k2mi 67phj6h06n](https://user-images.githubusercontent.com/19650464/45105052-0268c000-b166-11e8-8748-730c80e76bd8.png)

2. 添加调试配置
Launch.json add configuration
![95 ppja 50peuiv4jig](https://user-images.githubusercontent.com/19650464/45105166-3f34b700-b166-11e8-93c0-f16e0e79f9b1.png)

3. 开始附加进程进行调试，并添加断点
Start the add process for debugging and add breakpoints. 
![6 oen 8zva 3s3zayvdiam](https://user-images.githubusercontent.com/19650464/45105384-b4a08780-b166-11e8-8844-acb64e2aa13e.png)

4. 如果附加进程成功，调试控制台会输出如下信息
If the attached process is successful, the debug console will output the following information.
![m2 j3 736af 3dr_1kvb7](https://user-images.githubusercontent.com/19650464/45105513-fc271380-b166-11e8-9518-f7f368fcd46d.png)

5. 然后回到VS，执行下一步语句，如果一切顺利，将会出现如下结果
Then go back to VS and execute the next statement. If everything goes well, the following result will appear.
![y1v q0 mm6vu97t9e58wrl](https://user-images.githubusercontent.com/19650464/45105650-4d370780-b167-11e8-9395-c225a08a20e2.png)

**Comment by JohnGoldsmith** [comment]
Thanks for this @xxred I'll give it a try.

I've since realised that running webpack from the command line (as opposed to having NodeServices do it on build) means that at least console.log results do get output into the cmd window.
