### ISSUE TITLE
Invoke webpack or npm run from NodeServices?

### ISSUE THREAD

**Issue by zolakt** [aspnet/JavaScriptServices#1529]
Hi,

I have a theme system, that is editable through the UI. After a theme is edited I need to run webpack with a config script to generate css files from scss at runtime.

Is it in any way possible to invoke webpack from NodeServices manually?

I've tried:
`nodeServices.InvokeAsync<int>("webpack --config ./webpack.config.themes.js --env.prod")`
`nodeServices.InvokeAsync<int>("./node_modules/webpack/bin/webpack.js --config ./webpack.config.themes.js --env.prod")`
`nodeServices.InvokeAsync<int>("npm run webpack:themes")`

Nothing seems to work.
I'm getting this exception

> NodeInvocationException: Cannot find module

Btw. I have a corresponding "webpack:themes" script in package.json
`  "scripts": {
    "webpack:themes": "webpack --config webpack.config.themes.js"
  }`

**Comment by SteveSandersonMS** [comment]
To invoke arbitrary external tools at runtime, you can use .NET's standard `Process.Start` APIs. You don't need JavaScriptServices for that :)
