### ISSUE TITLE
Angular Template not working with Docker support in VS 2017

### ISSUE THREAD

**Issue by dapalmi** [aspnet/JavaScriptServices#1534]
I installed the latest Release-Candidate from NuGet (rc2-final) and created a new Angular web app (dotnet new angular -o my-new-app). But when I add Docker support for the created project in VS 2017 and start via Docker I get following error:

> AggregateException: One or more errors occurred. (One or more errors occurred. (Failed to start 'npm'. To resolve this:. [1] Ensure that 'npm' is installed and can be found in one of the PATH directories. Current PATH enviroment variable is: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin Make sure the executable is in one of those directories, or update your PATH. [2] See the InnerException for further details of the cause.))
System.Threading.Tasks.Task.GetResultCore(bool waitCompletionNotification)
Microsoft.AspNetCore.SpaServices.Extensions.Util.TaskTimeoutExtensions+<WithTimeout>d__1.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.SpaServices.Extensions.Proxy.SpaProxy+<PerformProxyRequest>d__4.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Builder.SpaProxyingExtensions+<>c__DisplayClass2_0+<<UseProxyToSpaDevelopmentServer>b__0>d.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Builder.RouterMiddleware+<Invoke>d__4.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware+<Invoke>d__7.MoveNext()

**Comment by dapalmi** [comment]
I made it work by using the microsoft/aspnetcore-build image instead of the microsoft/aspnetcore image, because the build image includes nodejs. Is there going to be a lighter image available for SPA projects with only nodejs installed, because the the aspnetcore-build image is 2GB big instead of the 300MB of the aspnetcore image?

**Comment by SteveSandersonMS** [comment]
Glad you got a solution!

> Is there going to be a lighter image available for SPA projects with only nodejs installed, because the the aspnetcore-build image is 2GB big instead of the 300MB of the aspnetcore image?

This is not something we're building, but if you're interested in creating your own base image and publishing it, we'd be happy to link to it from the wiki and docs here. Please let us know if so!

**Comment by dapalmi** [comment]
I don't know if I understand this right. Is this template going to be the standard Angular project template in a future Visual Studio Release? If so, I would recommend that, when adding Docker support to this project, you use the aspnetcore-build image in the created Dockerfile. Otherwise you will get a flood of requests from confused developers.

**Comment by matafonoff** [comment]
My dockerfile has following code:
`
FROM microsoft/dotnet:2.1-aspnetcore-runtime AS base
RUN apt-get update -y && apt-get install -y gnupg2  && curl -sL https://deb.nodesource.com/setup_10.x | bash - && apt-get update -y && apt-get install -y nodejs
WORKDIR /app
`

It's about 500Mb that is better than 2Gb in case of using aspnetcore-build

Hope this will help someone
