### ISSUE TITLE
Hot Replace not working

### ISSUE THREAD

**Issue by jerv89** [aspnet/JavaScriptServices#1539]
I'm trying to create a new app with the new spa-templates from Microsoft, but HMR (Hot Module Replacement) is not working, im on linux. I tried this.

. Install the SPA templates:

    dotnet new --install Microsoft.DotNet.Web.Spa.ProjectTemplates::2.0.0-rc2-final
. Created a new application using command line

    dotnet new angular -o MyApp
Ran command (working on linux):

    export SET ASPNETCORE_Environment=Development 
.In the ClientApp folder:

    npm install
.Back in the main folder:

    dotnet run
I was able to see the app running without any problems at http://localhost:5000, but when I modify any .ts file or .html in the angular app folder no changes are reflected or sent to the browser. How I configure HMR in this new angular/cli based template.

I also tried something like this: https://github.com/angular/angular-cli/wiki/stories-configure-hmr

Or this. https://medium.com/@beeman/tutorial-enable-hmr-in-angular-cli-apps-1b0d13b80130

I hope you can help me.

PD.: With VSCode happens the same, serveral browsers tested, my angular/cli, npm, nodejs, .netcore are up to date

**Comment by SteveSandersonMS** [comment]
When you're using the Angular CLI template, the live reloading feature comes entirely from Angular CLI, so it's not something we control or even influence in this repo. Could you please report it to Angular CLI?

We've verified that it works end-to-end on a stock Ubuntu distribution. If you are able to provide any repro steps where it works in Angular CLI but not in the ASP.NET Core templates, could you let us know what the repro steps are? Thanks!
