### ISSUE TITLE
Angular SpaTemplate 2.0.0-rc2-final on full net error

### ISSUE THREAD

**Issue by hodzanassredin** [aspnet/JavaScriptServices#1543]
dotnet new --install Microsoft.DotNet.Web.Spa.ProjectTemplates::2.0.0-rc2-final
 dotnet new angular
change target <TargetFramework>net461</TargetFramework>
Nuget: remove Microsoft.AspNetCore.All, add Microsoft.AspNetCore, Microsoft.AspNetCore.Mvc

Result:

> fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[0]
>       An unhandled exception has occurred while executing the request
> System.ArgumentException: The 'Accept' header must be modified using the appropriate property or method.
> Parameter name: name
>    at System.Net.WebHeaderCollection.ThrowOnRestrictedHeader(String headerName)
>    at System.Net.WebHeaderCollection.Set(String name, String value)
>    at Microsoft.AspNetCore.SpaServices.Extensions.Proxy.SpaProxy.<AcceptProxyWebSocketRequest>d__8.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.AspNetCore.SpaServices.Extensions.Proxy.SpaProxy.<PerformProxyRequest>d__4.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.AspNetCore.Builder.SpaProxyingExtensions.<>c__DisplayClass2_0.<<UseProxyToSpaDevelopmentServer>b__0>d.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
>       Request finished in 99.5188ms 500 text/html; charset=utf-8

**Comment by SteveSandersonMS** [comment]
Thanks for reporting it. It's now fixed. The fix will be included in the next package release, which hopefully is today.
