### ISSUE TITLE
Prerender to another tag

### ISSUE THREAD

**Issue by matjanos** [aspnet/JavaScriptServices#1545]
I would like to prerender some styles code which is generated on JavaScript code. 

I'm using [material-ui](https://material-ui-next.com/guides/server-rendering/) package which renders styles code in runtime on rendering app.

```
@{
    ViewData["Title"] = "Home Page";
}

<div id="react-app" asp-prerender-module="ClientApp/dist/main-server">Loading...</div>

@section scripts {
    <script src="~/dist/main-client.js" asp-append-version="true"></script>
    <style id="jss-server-side"> /*CSS code passed from ClientApp/dist/main-server*/ </style>
}
``` 

 I can of course generate styles within the HTML code, but I'll always get syntax warning because `<style>` tag ought not to be inside a `<div>` container. 
```
Warning: Did not expect server HTML to contain a <style> in <div>.
```

**Comment by SteveSandersonMS** [comment]
It sounds like you'd be better not using the `asp-prerender-*` tag helpers, and instead invoking your JS code as an arbitrary method call. You can then do whatever you want with the result value, such as emitting it anywhere in your page's markup. Please see docs at https://github.com/aspnet/JavaScriptServices/tree/dev/src/Microsoft.AspNetCore.NodeServices#simple-usage-example
