### ISSUE TITLE
Using webpack with VS2017 - ASP.NET Core 2.0

### ISSUE THREAD

**Issue by Legends** [aspnet/JavaScriptServices#1546]
**The code below works fine in VsCode + webpack** [(referenced)](https://github.com/webpack/webpack/issues/6539#event-1483677627)

 

**Index.ts:**
```
require("./jQueryPlugin-No-Module");
debugger;
$.fn.test();  // fails here
```
I am using the ProvidePlugin to inject jQuery into this script file.

**jQueryPlugin-No-Module.js:**
```
(function ($) {
	$.fn.test = function () {
		console.log("jQuery-Plugin called with options");
	};
})(jQuery);
```
**I have copied the all code from VsCode to VS2017-ASP.NET Core Project and just adapted the paths.. Everything runs perfectly except the plugin above,
I get this error:**

![image](https://user-images.githubusercontent.com/966368/36454984-7765977e-169e-11e8-8941-363700daae4e.png)

In `index.ts` I put a `debugger`  statement. When I run the application it stops there, the plugin `$.fn.test` has been successfully attached to jQuery. I switch to the Chrome console and execute `$.fn.test();` there, works as expected.
I go back to source view and hit F11 to execute the next step and I get the error above.

`tsc && webpack -d --env.dev --display-modules --progress --display-error-details --config webpack.config.dev.js`

**Comment by SteveSandersonMS** [comment]
This doesn't sound like an issue related to anything in this repo so it's not something I'd be able to investigate, sorry.

If you're able to track this down to something you think is a bug in something in this repo, please let us know where you think the bug is.

**Comment by Legends** [comment]
Also, when I use the `clean-webpack-plugin` in my `webpack.config.js`, which deletes the `dist` folder, it throws a `RemoteException` and after that. The plugin actually succeeds in deleting the folder and `webpack` continues to build, but after that everything is marked red during progress.

![image](https://user-images.githubusercontent.com/966368/36473284-66935098-16f4-11e8-8e07-6576656c1961.png)

**Comment by Legends** [comment]
Can you recommend a repo? Because it works fine in VsCode.

**Comment by SteveSandersonMS** [comment]
Sorry, I don't know what your issue relates to.
