### ISSUE TITLE
Uncaught SyntaxError: Unexpected token <

### ISSUE THREAD

**Issue by AlwaysAbhl001** [aspnet/JavaScriptServices#1548]
Using new angular 5 template as it was angular-cli standard. I want to render components from views/cshtml. 

Added required .js files in layout.cshtml under the `<app-root></app-root>` as follows

```
<script type="text/javascript" src="inline.bundle.js"></script>
<script type="text/javascript" src="polyfills.bundle.js"></script>
<script type="text/javascript" src="styles.bundle.js"></script>
<script type="text/javascript" src="vendor.bundle.js"></script>
<script type="text/javascript" src="main.bundle.js"></script>
```

It runs cool in locally but After deployment the bundles will generated with unique names as `main.bundle.b7122ae25d71.js`  so it unable to find the exact bundles for loading angular application. how do I get this achieve by referring exact bundles or any other way cause I need to carry some values from back end to front end so I prefer this process more.

**Comment by SteveSandersonMS** [comment]
> I want to render components from views/cshtml.

That's not supported by Angular CLI - it relies on compiling your `index.html` file for you, and putting the correct URLs in there.

If you want to find some way of putting the equivalent content in an MVC view you might be able to find some way of doing it, but it's not a thing we have any recommendations on how to do. Sorry!

**Comment by AlwaysAbhl001** [comment]
Then how about passing data from back end to front end in New angular 5 template?

**Comment by AlwaysAbhl001** [comment]
@SteveSandersonMS When user login, page get redirect to post method in HomeController there I collect token and need to send over to angular. So if we don't have option to render angular components from views then how could I send data from controller to Index.html which is in ClientApp directory ? . don't find any examples how they transfer the dynamic data from aspnet controller to ClientApp/src/Index.html.

**Comment by AlwaysAbhl001** [comment]
@SteveSandersonMS  I found this [passing data from net code into typescript](https://docs.microsoft.com/en-us/aspnet/core/spa/angular?tabs=visual-studio#pass-data-from-net-code-into-typescript-code)
but it is for `SSR` enable then what about other scenario's where `SSR` is not prefer.

**Comment by AlwaysAbhl001** [comment]
you can see [here](https://github.com/angular/angular-cli/issues/4630) they have option to set deployeurl in ng but in our case I think we don't have such type of option specify the path of the JS bundles in our views. let me know is it work for our scenarios as well.
