### ISSUE TITLE
Redirect with status code 301

### ISSUE THREAD

**Issue by hzinchenko** [aspnet/JavaScriptServices#1550]
I'm using PrerenderTagHelper and I wanted to implement redirect logic. So I resolved promise in main-server.js with object 
resolve({
          statusCode: statusCode,
          redirectUrl: redirectUrl,
          html: html,
        }); 
It works fine, but I noticed that I got a response with status code 302, which is not SEO friendly in my case. What I need is 301 status code 
Is there any chance that redirect will be improved in the further release?  And how would you recommend to deal the issue for now? 
Thank you

**Comment by SteveSandersonMS** [comment]
`PrerenderTagHelper` itself doesn't have any special support for 301s. It just uses the default 302 redirections.

If you need to control this more precisely, you could consider:

 * Calling `ISpaPrerenderer.RenderToString` directly from your C# code. This returns a `RenderToStringResult` so you can see the redirection status code and handle it however you want.
 * Or, move to the `UseSpaPrerendering` API from the `SpaServices.Extensions` package, as it already has logic for recognising 301s and preserving that status code in the response. Docs: https://docs.microsoft.com/en-us/aspnet/core/spa/angular?tabs=visual-studio#server-side-rendering
