### ISSUE TITLE
process.env in webpack on Azure

### ISSUE THREAD

**Issue by marcinwenger** [aspnet/JavaScriptServices#1551]
Hi,

I'm trying to access Node's env variables as follows inside webpack.config.js. I've set CMS_API_URL in Application Settings in Azure but webpack doesn't seem to be reading those values.

Both process.env.TEST_API and process.env.TEST_API_2 inside my project are `undefined`

`plugins: [`
`            new webpack.DefinePlugin({`
`                'process.env': {`
`                    TEST_API: JSON.stringify(process.env.CMS_API_URL),`
`                    TEST_API_2: JSON.stringify(process.env.APPSETTINGS_CMS_API_URL)`
`                }`
`            })`
`        ]`

Is it at all possible to access Azure's app settings inside webpack?

Thanks

**Comment by rjgotten** [comment]
You shouldn't be using `process.env` you should be using the environment variables that are passed to your webpack configuration when you [export it as a function](https://webpack.js.org/configuration/configuration-types/#exporting-a-function).

These would normally be populated via the call to `UseWebpackDevMiddleware`. E.g. to configure a production-mode switch:

```csharp
bool isProduction = ...
app.UseWebpackDevMiddleware(new WebpackDevMiddlewareOptions
{
  EnvironmentVariables = new Dictionary<string, string>
  {
    { "production", isProduction }
  }
});
```


However, as per #1532 which I reported two weeks ago, this is currently completely broken.

**Comment by SteveSandersonMS** [comment]
```
JSON.stringify(process.env.CMS_API_URL),
```

This will resolve to a string at *compile time*, hence you won't see any runtime variables.

I think you should change it to:

```
TEST_API: 'process.env.CMS_API_URL',
```

... so that it gets resolved at runtime instead.

That said, I don't know why you'd use `DefinePlugin` for this at all, instead of just referencing `process.env.CMS_API_URL` in your code directly.
