### ISSUE TITLE
Yarn support

### ISSUE THREAD

**Issue by smlynch** [aspnet/JavaScriptServices#1553]
Using the new [Microsoft.DotNet.Web.Spa.ProjectTemplates](https://www.nuget.org/packages/Microsoft.DotNet.Web.Spa.ProjectTemplates/2.0.0) for a React project I noticed it uses `npm` for packaging, but was hoping to use `yarn` (especially with the recent botched npm 5.7.0 release).

While some of this is a [templating](https://github.com/aspnet/templating/tree/dev/src/Microsoft.DotNet.Web.Spa.ProjectTemplates/content/React-CSharp) question and should be asked there, my question here mostly is with regards to the [middleware(s)](https://github.com/aspnet/JavaScriptServices/blob/dev/src/Microsoft.AspNetCore.SpaServices.Extensions/ReactDevelopmentServer/ReactDevelopmentServerMiddleware.cs#L74-L76) and such.

I've only briefly looked around at the source code, but it appears to use npm [directly](https://github.com/aspnet/JavaScriptServices/blob/dev/src/Microsoft.AspNetCore.SpaServices.Extensions/ReactDevelopmentServer/ReactDevelopmentServerMiddleware.cs#L74-L76).

Looking at the `.csproj` the template generates it looks like I can replace `npm <command>` with `yarn <command>`...

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <TypeScriptCompileBlocked>true</TypeScriptCompileBlocked>
    <TypeScriptToolsVersion>Latest</TypeScriptToolsVersion>
    <IsPackable>false</IsPackable>
    <SpaRoot>ClientApp\</SpaRoot>
    <DefaultItemExcludes>$(DefaultItemExcludes);$(SpaRoot)node_modules\**</DefaultItemExcludes>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.5" />
    <PackageReference Include="Microsoft.AspNetCore.SpaServices.Extensions" Version="2.0.0" />
  </ItemGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.0.1" />
  </ItemGroup>

  <ItemGroup>
    <!-- Don't publish the SPA source files, but do show them in the project files list -->
    <Content Remove="$(SpaRoot)**" />
    <None Include="$(SpaRoot)**" Exclude="$(SpaRoot)node_modules\**" />
  </ItemGroup>

  <Target Name="DebugEnsureNodeEnv" BeforeTargets="Build" Condition=" '$(Configuration)' == 'Debug' And !Exists('$(SpaRoot)node_modules') ">
    <!-- Ensure Node.js is installed -->
    <Exec Command="node --version" ContinueOnError="true">
      <Output TaskParameter="ExitCode" PropertyName="ErrorCode" />
    </Exec>
    <Error Condition="'$(ErrorCode)' != '0'" Text="Node.js is required to build and run this project. To continue, please install Node.js from https://nodejs.org/, and then restart your command prompt or IDE." />
    <Message Importance="high" Text="Restoring dependencies using 'npm'. This may take several minutes..." />
    <Exec WorkingDirectory="$(SpaRoot)" Command="npm install" />
  </Target>

  <Target Name="PublishRunWebpack" AfterTargets="ComputeFilesToPublish">
    <!-- As part of publishing, ensure the JS resources are freshly built in production mode -->
    <Exec WorkingDirectory="$(SpaRoot)" Command="npm install" />
    <Exec WorkingDirectory="$(SpaRoot)" Command="npm run build" />

    <!-- Include the newly-built files in the publish output -->
    <ItemGroup>
      <DistFiles Include="$(SpaRoot)build\**" />
      <ResolvedFileToPublish Include="@(DistFiles-&gt;'%(FullPath)')" Exclude="@(ResolvedFileToPublish)">
        <RelativePath>%(DistFiles.Identity)</RelativePath>
        <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      </ResolvedFileToPublish>
    </ItemGroup>
  </Target>

</Project>
```

...but for the middleware I wasn't sure if it was possible to influence it to use yarn.

I looked in the previous issues for yarn support but it seemed most was for the 1.0.0 templates and were not applicable to the new 2.0.0 way.

Thanks

**Comment by smlynch** [comment]
I have been using `spa.UseProxyToSpaDevelopmentServer("http://localhost:3000");` instead of `spa.UseReactDevelopmentServer(npmScript: "start");` but wasn't sure if:

- There are only places that npm would be used
- If I wanted to switch back to having create-react-app started by the ASP.NET, could I use something like `spa.UseReactDevelopmentServer(yarnScript: "start");` or `spa.UseReactDevelopmentServer(npmScript: "start", runner: "yarn");`

**Comment by SteveSandersonMS** [comment]
> I have been using spa.UseProxyToSpaDevelopmentServer

That will work fine and is a good approach.

> [wasn't sure if] There are only places that npm would be used

As far as I'm aware, those are the only places it's used (in the `csproj`, and in `UseReactDevelopmentServer`).

> [wasn't sure if] If I wanted to switch back to having create-react-app started by the ASP.NET, could I use something like spa.UseReactDevelopmentServer(yarnScript: "start");

We don't currently have any `yarnScript` or `runner` params as in your examples. If you're interested in submitting a PR to add that support we could certainly consider it!

**Comment by youfoundkris** [comment]
@SteveSandersonMS 
https://github.com/aspnet/JavaScriptServices/pull/1776
