### ISSUE TITLE
React component problem

### ISSUE THREAD

**Issue by NickMaev** [aspnet/JavaScriptServices#1555]
Hi all.
I have React component:

`
export class MyComponent extends React.Component<{}, {}> {
...
componentDidMount(){
// Now I want to initialize it in client-side rendering.
if(typeof window !== undefined) {
// jQuery code here... 
/* But node thrown errors:
An unhandled exception occurred while processing the request.
NodeInvocationException: Prerendering failed because of error: TypeError: Cannot set property 'serializeJSON' of undefined 

After I updated page second time, I've got:
An unhandled exception occurred while processing the request.
NodeInvocationException: Prerendering failed because of error: TypeError: $.extend is not a function
*/
}

// Furthermore:
if(false){ // <--FALSE
// jQuery code here... 
/* But node thrown errors AGAIN!
An unhandled exception occurred while processing the request.
NodeInvocationException: Prerendering failed because of error: TypeError: Cannot set property 'serializeJSON' of undefined 

After I updated page second time, I've got:
An unhandled exception occurred while processing the request.
NodeInvocationException: Prerendering failed because of error: TypeError: $.extend is not a function */
}
}
...
}

`

What should I do to prevent initialize scripts in server rendering and run it on client side only?
I am using React + Redux starter kit.

**Comment by SteveSandersonMS** [comment]
If you still have calls to `$.extend` even though you've got `if (false) { ... }`, then your code must be somewhere else outside that `if (false) { ... }` block. I'm afraid you'll have to check the rest of your code to find out where the offending call is!
