### ISSUE TITLE
WebSocket connection to 'ws://localhost:52090/sockjs-node/819/yjalqx53/websocket' failed

### ISSUE THREAD

**Issue by DerGroncki** [aspnet/JavaScriptServices#1556]
I am using "Microsoft.DotNet.Web.Spa.ProjectTemplates 2.0.0" and I have created the project with "dotnet new react" (no other modification). I use Visual Studio 2017:

![image](https://user-images.githubusercontent.com/2815398/36667281-a2d3dc60-1aed-11e8-8eca-e1912d7c0611.png)

Now I am getting the following error if I start the application:
WebSocket connection to 'ws://localhost:52090/sockjs-node/819/yjalqx53/websocket' failed: Error during WebSocket handshake: Unexpected response code: 400

The following image is showing the console output of Chrome but the same error is shown with Firefox and Internet Explorer 11 as well:

![image](https://user-images.githubusercontent.com/2815398/36667039-dac03516-1aec-11e8-86bb-3904a5b289f9.png)

Thanks for helping! 

Best regards,
Michael

**Comment by SteveSandersonMS** [comment]
My guess is that you're running on Windows 7. If so, I'm afraid that's not a supported scenario for WebSockets, because the low-level `http.sys` driver in Windows 7 itself can't accept WebSocket connections.

If that's not the reason, please let us know.

**Comment by k-vekos** [comment]
@SteveSandersonMS I am getting a similar error using the default Angular SPA template created by New > Project in Visual Studio 2017.

If this isn't viable on Windows 7 then what kind of functionality would I be losing as a result of WebSockets not working? And, how can I stop this error message then?
