### ISSUE TITLE
Angular CLI timeout - even though it's actually running fine

### ISSUE THREAD

**Issue by mcaden** [aspnet/JavaScriptServices#1557]
I'm using the latest Microsoft.DotNet.Web.Spa.ProjectTemplates 2.0.0 that was published 6 days ago.

I did the following:

1. `dotnet new --install Microsoft.DotNet.Web.Spa.ProjectTemplates`
2. `dotnet new angular`
3. `SET ASPNETCORE_Environment=Development`
4. `dotnet run`

So far so good. I receive in the log:
> info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
>       User profile is available. Using 'C:\Users\{{user}}\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
> info: Microsoft.AspNetCore.SpaServices[0]
>       Starting @angular/cli on port 34100...
> Hosting environment: Development
> Content root path: C:\repos\ngpoc
> Now listening on: http://localhost:5000
> Application started. Press Ctrl+C to shut down.
> info: Microsoft.AspNetCore.SpaServices[0]
>       > ngpoc@0.0.0 start C:\repos\ngpoc\ClientApp
> > ng serve --extract-css "--port" "34100"
> 
> ** NG Live Development Server is listening on localhost:34100, open your browser on http://localhost:34100/ **
> 
> info: Microsoft.AspNetCore.SpaServices[0]
>       Date: 2018-02-27T21:14:41.782Z
> 
> info: Microsoft.AspNetCore.SpaServices[0]
>       Hash: 3c1a7b9355c0deb242a6
> Time: 11790ms
> chunk {inline} inline.bundle.js (inline) 3.85 kB [entry] [rendered]
> chunk {main} main.bundle.js (main) 50.9 kB [initial] [rendered]
> chunk {polyfills} polyfills.bundle.js (polyfills) 549 kB [initial] [rendered]
> chunk {styles} styles.bundle.css (styles) 119 kB [initial] [rendered]
> chunk {vendor} vendor.bundle.js (vendor) 9.5 MB [initial] [rendered]
> 
> 
> info: Microsoft.AspNetCore.SpaServices[0]
>       webpack: Compiled successfully.

Ok, so I navigate to http://localhost:5000 and I receive this:

> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
>       Request starting HTTP/1.1 GET http://localhost:5000/fetch-data
> fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[0]
>       An unhandled exception has occurred while executing the request
> System.TimeoutException: The Angular CLI process did not start listening for requests within the timeout period of 50 seconds. Check the log output for error information.
>    at Microsoft.AspNetCore.SpaServices.Extensions.Util.TaskTimeoutExtensions.<WithTimeout>d__1`1.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.AspNetCore.SpaServices.Extensions.Proxy.SpaProxy.<PerformProxyRequest>d__4.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.AspNetCore.Builder.SpaProxyingExtensions.<>c__DisplayClass2_0.<<UseProxyToSpaDevelopmentServer>b__0>d.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
>       Request finished in 50161.8848ms 500 text/html; charset=utf-8
> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
>       Request starting HTTP/1.1 GET http://localhost:5000/favicon.ico
> info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
>       Sending file. Request path: '/favicon.ico'. Physical path: 'C:\repos\ngpoc\wwwroot\favicon.ico'
> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
>       Request finished in 8.5569ms 200 image/x-icon

I've seen the other post about changing the timeout and such, but the thing is it's *not* the timeout. **I get the same error if I set the timeout to 600 seconds.** It's like the cli just isn't seeing that angular is running. If I go to http://localhost:34100 like the original output states that `ng serve` is running on then everything works beautifully b/c it's already compiled and running - except of course the .net services b/c they are running on 5000.

It's simply as if the project isn't talking to the angular process.

If I run `ng serve` in a separate console and place `spa.UseProxyToSpaDevelopmentServer("http://localhost:4200");` in `Startup.cs` the whole thing works fine.

**Comment by mcaden** [comment]
1. I tried again several times and the problem existed each time.
2. I tried again on a different computer and it went through smooth as butter.
3. I tried again on the original computer but I installed AspNetCore 2.1-preview and used Visual Studio to create the solution and it's fine.

Are there any troubleshooting steps I can use to figure out why it won't work through the CLI?

**Comment by mcaden** [comment]
I believe this has something to do with the network interfaces on the machine. I believe I'm seeing other symptoms of this as well as `dotnet restore` is timing out and that points to a bunch of closed "cannot repro" issues where people are mentioning VMware ethernet interfaces.

I am indeed doing it on a VMWare VM and while `nuget restore` works, `dotnet restore` does not. interestingly enough, if I disable the VMWare ethernet interfaces the http://localhost:5000 magically starts working and everything is fine.

As I posted at https://github.com/dotnet/cli/issues/1732 I was able to add nuget proxy configuration and magically the `dotnet restore` started working. Could this somehow be attempting to use a proxy even though both addresses are localhost?

**Comment by smichelotti** [comment]
@mcaden Did you ever get a legitimate solution to this? Out of the blue, I just started getting this same error (and when I was using the template a couple weeks ago, everything was fine). I'm not sure what changed.

**Comment by mjrousos** [comment]
+1. I'm seeing a similar error. Not sure what caused the ASP.NET Core -> Angular communication to stop working.

**Comment by mcaden** [comment]
I worked around the issue simply by disabling the vmware network interfaces I had. Seems really odd that they would be an issue for this when they don't seem to hinder anything else I've ever done on the box over multiple years of development.

I also tried several boxes that were not VMs and they work fine with no changes. I'm working on one right now and all seems well.

**Comment by mjrousos** [comment]
Turns out the issue I saw was similar (unrelated networking interference). Thanks for the suggestion!

**Comment by SteveSandersonMS** [comment]
From the discussion, it seems that the underlying issue is a networking fault on the machine, which is unfortunately beyond our control, so I'll mark this closed.

If anyone is affected by this and doesn't have any way to fix their local networking, one alternative that might work for you is this: https://docs.microsoft.com/en-us/aspnet/core/spa/angular?tabs=visual-studio#run-ng-serve-independently
