### ISSUE TITLE
Uncaught Error: Can't resolve all parameters for MyService: ([object Object], ?).

### ISSUE THREAD

**Issue by Basel78** [aspnet/JavaScriptServices#1561]
Hello,
I have built service library using "generator-angular2-library" template and updated it with angular V "^4.4.6", then used it in andular-cli all working fine..
The library module looks like

```
export class ServiceLibraryModule { 
  static forRoot(config:any): ModuleWithProviders {
    return {
      ngModule: ServiceLibraryModule ,
      providers: [Serv1
        Serv2 
        { provide: MODULE_CONFIG, useValue: config }]
    };
  }
}
```

where `export const MODULE_CONFIG = new InjectionToken<any>('');`
 to pass config parameters to the services of the library before using it.

now when I want to reuse my library in aspnetcore angular SPA project with V "^4.4.6", I added the "ServiceLibraryModule " to "app.shaed.module.ts" of the Angular-SPA project similar to what I did in angular-cli,  
```
 imports: [...
ServiceLibraryModule .forRoot({"config_url" : "http://somedomain"}),
....]
```
but I keep getting the error:
"Uncaught Error: Can't resolve all parameters for Serv2 : ([object Object], ?)."

the Ser2 class looks like
```
export class Serv2
{

    constructor( private http: Http,@Inject(MODULE_CONFIG) private config:any){}
.....
}
```
can you help me find out what I did wrong or how to fix this issue in Angular-SPA, as the services library is working fine in angular-cli same version "^4.4.6".

**Comment by Basel78** [comment]
more on this issue:
I noticed the service in the umd.js file has the parameters written like this:

```
Serv2.ctorParameters = function () { return [
        { type: http.HttpClient, },
        { type: undefined, decorators: [{ type: core.Inject, args: [MODULE_CONFIG,] },] },
    ]; };
```
Is that possible to has type : undefined in the ctorParameters  of the service

**Comment by Basel78** [comment]
so the solution to this issue in my case was to check on two things:
1- the custom library routing has to match with the routing where the library module was used in the app.
2- seems that since i am using the custom libraries Serv1, Serv2 ... in angular-cli using symlinks , so i used to run "ng serve --preservesymlinks" and since the aspnet core project is running ng serve internally on background then obviously there are two ways to solve it, 
2-a: running "ng serve"  externally with " --preservesymlinks"" by following the instructions in the link below https://docs.microsoft.com/en-us/aspnet/core/spa/angular?tabs=visual-studio#run-ng-serve-independently](url) , 
or 
2-b: update the one line of code in "webpack.config.js" with "modules: [path.join(__dirname, "node_modules")] " as appears below.

```
const sharedConfig = {
        stats: { modules: false },
        context: __dirname,
        resolve: { extensions: [ '.js', '.ts' ], **modules: [path.join(__dirname, "node_modules")]** },
```

hope this was helping

**Comment by SteveSandersonMS** [comment]
Glad you found a solution!
