### ISSUE TITLE
ng serve does not terminate when VS debugging is stopped

### ISSUE THREAD

**Issue by leak** [aspnet/JavaScriptServices#1563]
VS: 15.5.7
Node: 6.9.1
Browser: Vivaldi (Chrome)

`dotnet new --install Microsoft.DotNet.Web.Spa.ProjectTemplates::2.0.0`
`dotnet new angular`
`npm restore -f`

1) Switch to project launch in debug configuration
2) Start debugging with VS
3) Wait for everything to boot up
4) Load the website
5) Stop debugging in VS

=> Console window with ng serve doesn't go away

These processes stay open and don't terminate unless manually killed:
![image](https://user-images.githubusercontent.com/530056/37036944-79429f20-2151-11e8-90c5-48920760ad9b.png)

Am I missing something?

**Comment by SteveSandersonMS** [comment]
I think this is just how VS debugging works. AFAIK it's the same for all ASP.NET Core projects, but please let me know if you have a situation where that's not the case!
