### ISSUE TITLE
AngularCLI: Unable to find any apps in `.angular-cli.json`

### ISSUE THREAD

**Issue by piotrek-k** [aspnet/JavaScriptServices#1564]
I've just generated new project using this template, but it seems I cannot create anything using angular cli, as it throws this error:

> Unable to find any apps in `.angular-cli.json`.

How to configure angular cli to find my app and where is `.angular-cli.json` it's talking about?

(I'm currently talking about default angular project generator that can be seen while creating new project in Visual Studio 2017, I hope it's proper github page for this issue)

**Comment by SteveSandersonMS** [comment]
It sounds like you're using the older, pre-Angular CLI template.

If you want to use the Angular CLI-based template, please see https://docs.microsoft.com/en-us/aspnet/core/spa/
