### ISSUE TITLE
Webpack Dev Middleware keeps rebuilding my typescript when I recompile my back end code and reload the page

### ISSUE THREAD

**Issue by eugene159** [aspnet/JavaScriptServices#1566]
I have a huge Angular project set up in Visual Studio. I enabled hot module replacement following the instructions.

app.UseWebpackDevMiddleware(new WebpackDevMiddlewareOptions {
    HotModuleReplacement = true
});

Now every time I run my project with CTRL-F5 my typescript is being rebuilt. This significantly slows down application start. I don't want to rebuild it every time. I want to run webpack in watch mode myself and rebuild it only when typescript files change. It even rebuilds dev build when I run production build manually with webpack. This drives me crazy. Is it possible to disable auto-rebuild ?

**Comment by SteveSandersonMS** [comment]
If you prefer, you can remove the `UseWebpackDevMiddleware` call from your .NET code, and run `webpack --watch` manually in a separate command prompt. If you want HMR too, you'll need to follow Webpack docs to add all the config for that.

I'm afraid that's the only way of keeping the Webpack process alive across .NET rebuilds.
