### ISSUE TITLE
Angular-Cli Spa Template. ServerSideRendering with --aot and Typescript 2.6 support

### ISSUE THREAD

**Issue by speige** [aspnet/JavaScriptServices#1567]
The latest angular officially supports Typescript 2.6. If I use the latest angular-cli template & upgrade package.json to Typescript 2.6.2, everything works fine.

If I follow the SSR instructions from https://docs.microsoft.com/en-us/aspnet/core/spa/angular everything still works fine.

If I add --aot to "build:ssr" in package.json, I get an error.

If I downgrade to Typescript 2.5.3, everything works again, even with --aot.

ERROR in ./src/main.server.ts
Module parse failed: Unexpected token (18:21)
You may need an appropriate loader to handle this file type.
| core_1.enableProdMode();
| exports.default = aspnet_prerendering_1.createServerRenderer(function (params) {
|     var _a = (module as any).exports, AppServerModule = _a.AppServerModule, AppServerModuleNgFactory = _a.AppServerModuleNgFactory, LAZY_MODULE_MAP = _a.LAZY_MODULE_MAP;
|     var options = {
|         document: params.data.originalHtml,

![image](https://user-images.githubusercontent.com/2002030/37119052-7643a25c-2213-11e8-938a-cd46bc030f1a.png)

Not sure how important AOT is for server-side rendering (since it's not on by default in the template), but it seems like it'd be valuable to enable, if possible.

main.server.ts is a port to .net core from the node+express version at https://github.com/angular/angular/blob/master/aio/content/examples/universal/server.ts
I haven't tested the node+express version to see if it works with Typescript 2.6.2 & aot.

**Comment by chrisvfabio** [comment]
I've been having this issue since v1.7.0. There is an issue being tracked here: https://github.com/angular/angular-cli/issues/9219

As a workaround, I downgraded to v.1.6.8.

**Comment by SteveSandersonMS** [comment]
As per @chrisvfabio's comment, it's an Angular CLI issue - please follow up with that project. Thanks!
