### ISSUE TITLE
why was Microsoft.DotNet.Web.Spa.ProjectTemplates::2.0.0-rc1-final deleted

### ISSUE THREAD

**Issue by amccool** [aspnet/JavaScriptServices#1568]
we based a project of Microsoft.DotNet.Web.Spa.ProjectTemplates::2.0.0-rc1-final.   The angular-cli was really helpful.

can you please put the nuget package back?

**Comment by SteveSandersonMS** [comment]
It wasn't removed - it's here: https://www.nuget.org/packages/Microsoft.DotNet.Web.Spa.ProjectTemplates/2.0.0-rc1-final
