### ISSUE TITLE
React publish 404

### ISSUE THREAD

**Issue by mmccoy173** [aspnet/JavaScriptServices#1569]
I'm trying to publish to my local IIS the initial react app that is generated with `dotnet new react` and I am getting 404 not found for the static files. The index.html loads but is blank. Looking at the index.html that is generated it is pointing to `/static/js/main.5aa7d1c0.js` which seems weird to me because they are within ClientApp\build\ directory. Can anyone help point me in the right direction? Thanks in advance.

I am running dotnet core 2.0 and using the latest react template found here: Microsoft.DotNet.Web.Spa.ProjectTemplates::2.0.0

**Comment by SteveSandersonMS** [comment]
Could you provide repro steps? Example: what sequence of steps in the command line or VS UI are you using to publish the app to your local IIS instance?

**Comment by SteveSandersonMS** [comment]
I'll close this due to lack of information, but please let us know if you end up having specific repro steps.
