### ISSUE TITLE
Add dotnet-watch to the templates

### ISSUE THREAD

**Issue by emzero** [aspnet/JavaScriptServices#157]
Since we already have HMR for the client side source files it would be good if we also have [dotnet-watch](http://docs.asp.net/en/latest/tutorials/dotnet-watch.html) for the server ones so we don't need to stop and re-run `dotnet run` ever again during a development session.

**Comment by SteveSandersonMS** [comment]
Sounds great. Would definitely take a pull request for that :)

**Comment by emzero** [comment]
@SteveSandersonMS I can submit a PR if you want but it's just a one liner.

Just add the package inside the `tools` section in `project.json`
```json
"tools": {
  "Microsoft.DotNet.Watcher.Tools": "1.0.0-preview2-final"
},
```
