### ISSUE TITLE
Reactjs and Redux template's Typings issues

### ISSUE THREAD

**Issue by mantasmarcinkus** [aspnet/JavaScriptServices#1571]
Hello everybody,

## Issue at hand
I hope i got to the right place. I created a new project 
![image](https://user-images.githubusercontent.com/21105827/37243511-241ded58-2483-11e8-82e0-8d02cd2b5306.png)
However, It seems that the predefined `package.json` and typings in it has been messed up somehow.
I get several errors in several places
![image](https://user-images.githubusercontent.com/21105827/37243519-5f1eced6-2483-11e8-866b-e014d8b83e91.png)

## Reproducability
Just try creating a new project with this template

## What I've tried
- I tried upgrading minor versions of typings and packages. Started with the router, because I thought it might be somewhat guilty for that. However, this did not help.
- Tried looking for errors, but it did not help, as they are very generic Typescript errors.

It's very hard to pin point where the problem is when you don't know what the project template is using. Can anyone help?
Thank you so much in advance

**Comment by feafarot** [comment]
I have the same problem (note: I'm using typescript 2.7 installed globally)

**Comment by joalcava** [comment]
Hi guys, any updates on this? I'm having the same problem.

**Comment by SteveSandersonMS** [comment]
Please try our much newer React + Redux template: https://docs.microsoft.com/en-us/aspnet/core/spa/

**Comment by mantasmarcinkus** [comment]
Will this be updated and replaced in new Visual Studio update? Because this issue has to be fixed - it affects all the users of Visual Studio

**Comment by SteveSandersonMS** [comment]
Yes, it is updated and replaced in the ASP.NET Core 2.1 SDK (which is currently in preview). The 2.1 SDK moves to the newer template.

**Comment by mantasmarcinkus** [comment]
@SteveSandersonMS this is not a solution. I got 2.1 SDK and it has a completely different approach. New project template is not using Typescript. What are the reason for ditching Typescript in new React Redux template?
