### ISSUE TITLE
aspnet-webpack should take publicPath from devServer.publicPath first, then fallback to output.publicPath

### ISSUE THREAD

**Issue by rjgotten** [aspnet/JavaScriptServices#1573]
Currently, the setting is hardcoded to be `output.publicPath`. 

https://github.com/aspnet/JavaScriptServices/blob/67560266aba6d06226f6b6bc4df08f6ae5c65772/src/Microsoft.AspNetCore.SpaServices/npm/aspnet-webpack/src/WebpackDevMiddleware.ts#L124

There is supposed to be an explicit override in `devServer.publicPath` which can be used when the two do not match:

https://webpack.js.org/configuration/dev-server/#devserver-publicpath-

While it is recommended that both match, for more complex folder structures this is many times simply not possible due to peculiarities in how webpack and several mainstream plugins resolve paths.

This is in particular a problem with ASP.NET Core and the `wwwroot` folder, which doesn't exist in the URL structure; only on disk. Many webpack plugins that handle file path mapping (e.g. file-loader, extract-text, etc.) sort of rely on the disk path and url path being consistent.

**Comment by SteveSandersonMS** [comment]
Thanks for reporting this.

At the moment I'm unsure under what exact circumstances this will affect anyone. Does this cause a problem that's hard to work around? Since nobody else has reported having trouble with this, I'd be reluctant to introduce a potentially breaking change here.

I apologise if this is causing trouble for you in particular. We would have to balance fixing that against the potential for causing different trouble for others!

**Comment by rjgotten** [comment]
> Does this cause a problem that's hard to work around? 

I've currently worked around this by reorganizing folder structure a bit.
It's doable; just not nice.

> I'd be reluctant to introduce a potentially breaking change here.

I wouldn't expect anything to break here, considering `devServer.publicPath` currently doesn't work at all; nobody can actually be succesfully relying on it, and there would also be no reason to actually configure it.

**Comment by SteveSandersonMS** [comment]
OK, thanks for the update! I'm glad you have found a workaround.

If this does become a more widely reported issue we'd certainly consider implementing changes. If not, it's unlikely it would meet the bar for a fix. Hope that's OK!
