### ISSUE TITLE
Docker Support for Angular

### ISSUE THREAD

**Issue by dapalmi** [aspnet/JavaScriptServices#1574]
I really like the new templates of Microsoft.DotNet.Web.Spa.ProjectTemplates v2.0.0.
The Angular template works really well until I add Docker support for that project.
For example it does not recognize code changes and reloads the app automatically.
I have to stop and start debugging again manually and even than the build process get stuck often so I have to manually remove the container and image manually so it can build correctly again.
Are all those Docker support issues known and worked on?
Or is this the wrong repository for this issue?

**Comment by R4z0** [comment]
I have the same problem.
VisualStudio 2017 can not kill the image of the container when it tries to build the solution and then freezes it.
I have to kill the docker container manually all the time.

Thanks

**Comment by SteveSandersonMS** [comment]
Whether or not Angular CLI detects changes in the filesystem is an Angular CLI issue, so would you be able to report this to that project? https://github.com/angular/angular-cli They may already have docs on how to set this up. Hope that's OK!

**Comment by dapalmi** [comment]
Ok. But how about that VS 2017 is not able to kill the respective container?

**Comment by SteveSandersonMS** [comment]
I'm afraid the VS/Docker integration is totally separate from this repo and is not something we control (or even influence) here. There isn't anything in the JavaScriptServices code or associated templates that has special handling for Docker, so whatever issues you're seeing most likely apply to all project types.

Would you be able to report this to VS instead? For example at https://visualstudio.uservoice.com/forums/121579-visual-studio-ide.

**Comment by dapalmi** [comment]
I created a ticket with the Visual Studio Developer Community:
https://developercommunity.visualstudio.com/content/problem/222197/vs-cannot-kill-container-of-project-with-angular-t.html
If anybody has the same problem please upvote this ticket!

**Comment by R4z0** [comment]
I have found a workarround to fix the reload of the container when restart debug in VS2017 for Angular CLI template.

## Context:
Angular CLI creates a new process inside Docker image in Debug mode to provide HMR and debug support.
VisualStudio 2017 docker compatibilty kill the docker images using the command:"/bin/bash -c \"if PID=$$(pidof -x dotnet); then kill $$PID; fi\"

## Problem:
There are an other active process launched by Angular CLI named "ng", so VisualStudio don't kill it and cannot stop the container.

## Workarround:
Extend the command launched by VS to kill the other process also.
(Can find the command in the file docker-compose.vs.debug.g.yml)

## How To:
- Open the **docker-compose.vs.debug.yml**
- Find the container definition and replace the label "com.microsoft.visualstudio.debuggee.killprogram" with the sentence:

>  "/bin/bash -c \"if PID=$$(pidof -x dotnet); then kill $$PID; fi\"; \"if PID=$$(pidof -x ng); then kill $$PID; fi\";"

### Final result:
```
services:
  angularcli:
    labels:
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/bash -c \"if PID=$$(pidof -x dotnet); then kill $$PID; fi\"; \"if PID=$$(pidof -x ng); then kill $$PID; fi\";"
```

Related: https://developercommunity.visualstudio.com/content/problem/222197/vs-cannot-kill-container-of-project-with-angular-t.html
