### ISSUE TITLE
.Net Core 2.1 P1 - Can't website from fresh Angular web template: '@angular-devkit/core'

### ISSUE THREAD

**Issue by Eilon** [aspnet/JavaScriptServices#1578]
_From @WereDev on February 28, 2018 22:23_

# Issue Title

Can't website from fresh Angular web template: Error with `@angular-devkit/core`

# General

Trying to start the website after creating a fresh project using the Angular web template nets me `Error: Cannot find module '@angular-devkit/core'.`

Adding `@angular-devkit/core` as a devDependency in package.json seems to fix the issue.

_Copied from original issue: dotnet/core#1315_

**Comment by Eilon** [comment]
_From @Petermarcu on March 15, 2018 4:26_

@Eilon @muratg @DamianEdwards

**Comment by SteveSandersonMS** [comment]
This happens if your version of NPM is too old. You need to have NPM 5.x or later.

Note that this is unrelated to the version of Node shipped in VS, because it doesn't use that anyway. It only uses the version you've installed manually, and that version has to be new enough to work.
