### ISSUE TITLE
Passing Data from to client with SSR not working

### ISSUE THREAD

**Issue by isaac2004** [aspnet/JavaScriptServices#1579]
I followed the steps in the doc to setup SSR, and I want to test passing around the isHttpsRequest from Startup. I added this code to main.server.ts

`{ provide: 'isHttp', useValue: params.data.isHttpsRequest }`
and this in fetch-data.component.ts
````
 constructor(http: HttpClient, @Inject('BASE_URL') baseUrl: string, @Inject('isHttp') isHttp: boolean) {
    var foo = isHttp;
    http.get<WeatherForecast[]>(baseUrl + 'api/SampleData/WeatherForecasts').subscribe(result => {
      this.forecasts = result;
    }, error => console.error(error));
  }
}
````
When I publish to Azure, I get this error in console when I go to the Fetch Data route

> Error: StaticInjectorError[isHttp]:
StaticInjectorError[isHttp]:
NullInjectorError: No provider for isHttp!

The reason this seems to happen is that isHttp is not provided in main.ts. I assumed that main.server.ts was used when in Production environment, is that not the case?

Here is a repo with the code
https://github.com/isaac2004/TestSSR

and the site deployed to Azure
https://test-ssr.azurewebsites.net/

I assume I am missing a stupid step, but the doc isn't clear. Any help would be greatly appreciated. Thanks

**Comment by SteveSandersonMS** [comment]
> The reason this seems to happen is that isHttp is not provided in main.ts. I assumed that main.server.ts was used when in Production environment, is that not the case?

It's not a question of dev-versus-production. It's a question of server-versus-client. `main.server.ts` is used on the server; `main.ts` is used on the client. Both of them are used in production.

So you need to define your value in both files.

**Comment by isaac2004** [comment]
@SteveSandersonMS but what needs to go in `main.ts`? Is there a factory that needs to be used?

**Comment by SteveSandersonMS** [comment]
The equivalent to the `BASE_URL` entry that is already there.

**Comment by isaac2004** [comment]
@SteveSandersonMS not following, in my example if I want to inject my `isHttp` property and read it from the app, I need to load it in `main.ts` and `main.server.ts`. The example for `BASE_URL` gets the value from html element. Is this the same approach as any property? Sorry if this a stupid question but the doc doesn't make it clear where the injected property is put

**Comment by SteveSandersonMS** [comment]
Your code in `main.ts` runs on the client, so it can only access information that the client knows about. It's up to you to implement some logic to get whatever data you want.

In your isHttp example, the client-side code could use a condition like `location.protocol == "https:"`.

Your `isHttp` code in `main.server.ts` is backwards, by the way. It gets set to true when `params.data.isHttpsRequest`. You probably should rename it to `isHttps`.

**Comment by isaac2004** [comment]
So you are basically hardcoding the value to something in `main.ts`? For instance if I wanted to pass something like an App Insights Key from appsettings, I would set it to some default value in `main.ts` but set it to the injected value in `main.server.ts`? Is that correct? If so, I think I am going to update the doc so it is a little more straightforward.

**Comment by SteveSandersonMS** [comment]
> I would set it to some default value in main.ts but set it to the injected value in main.server.ts? Is that correct?

No, not at all. The client-side code doesn't see the data you had on the server automatically. These are two different independent rendering processes.

If your goal is to pass some specific data to the client, data that the client can't otherwise know about, then you can either:

[1] Use server-side rendering to emit the data into the inital HTML in some way, and then in your client-side code pick it up from the DOM
or [2] don't involve SSR in any way; instead on the client fetch it from the server via an API endpoint

Option [2] is cleaner and simpler. Option [1] only has the advantage that you can get the data synchronously while the page is loading, if you really need that.

**Comment by isaac2004** [comment]
That makes sense, but old templates seemed to do this a bit more straightforward. If I want to do [1], is there a good doc to look at to see the best approach to doing that? Is Universal the way to go?

**Comment by SteveSandersonMS** [comment]
I agree this particular thing was a little easier before. That's the tradeoff for using Angular CLI.

I don't have a specific doc to recommend other than Angular docs that show how you can render arbitrary things into the DOM, and general JavaScript docs that would show how to acquire data from the DOM, I'm afraid!

**Comment by isaac2004** [comment]
@SteveSandersonMS I hate to have to do this, but is there a simple example you can give me? I have been playing with this for a bit. Here is what I am looking to do.

Pass value from config and inject it into page on server. One example I think of is an Application Insights key. 

I have tried a few things but it seems like using the same approach mentioned above, I cannot get that value to be injected into my components

**Comment by ssohal** [comment]
@isaac2004 Did you ever figure this out?
