### ISSUE TITLE
including node_modules causes long publish, deploy times and Azure issues with Angular template + server side rendering

### ISSUE THREAD

**Issue by craigsmitham** [aspnet/JavaScriptServices#1584]
I'm using the 2.0.0 of the project templates to create a new Angular app and have configured it to use server side rendering as described [here](https://docs.microsoft.com/en-us/aspnet/core/spa/angular?tabs=visual-studio).

The package/publish takes a very long time to copy the `node_modules` directory to the publish directory, and the upload/deployment process takes even longer. I'm not sure it even works with Azure App Services. I zipped the outputs and used Kudu zip deploy. It uploaded OK, but the Kudu deployment process is stuck at 50% after 10 minutes. 

I was curious about the rationale for including the entire node_modules directory instead of bundling with Webpack. I saw @SteveSandersonMS 's  [comment](https://github.com/aspnet/JavaScriptServices/issues/429#issuecomment-265502827) on issue #429, but that looks out of date. Any advice on what to do about these issues, or will server-side bundling be supported?

**Comment by SteveSandersonMS** [comment]
@craigsmitham We're awaiting a fix for https://github.com/angular/angular-cli/issues/8616. I don't know of any ETA for that but you could contact the Angular CLI folks and ask for it to be prioritised.
