### ISSUE TITLE
Asp.net core 2 + Angular 4 SPA SEO issues

### ISSUE THREAD

**Issue by marvelTracker** [aspnet/JavaScriptServices#1586]
Hi There,

I've used the ASP.net core 2 + Angular 4+ SPA template for one of my projects. It worked really well and I deployed it on Azure. 

However, when I tried to index with google bot, it didn't correctly identify my content. I've attached the screen shot how the google bot renders the page and it didn't render the html in angular app

![22](https://user-images.githubusercontent.com/1152084/37744321-73507556-2dc2-11e8-8a30-b910cd04a116.PNG)
![11](https://user-images.githubusercontent.com/1152084/37744324-7953dc36-2dc2-11e8-952a-7267f267dfbc.PNG)

I really appreciate your help on this.

Thanks,

**Comment by koolbuddhi** [comment]
Hi,

Default Angular app only renders in the client. Therefore for the bots to
work you need server side rendering enabled. This requires node services
enabled on the server too. You can get some idea reading this
https://angular.io/guide/universal

\B


Buddhima W.Wickramasinghe
---------------------------------------------
Mobile: 94 77 7599939
Yahoo: buddhima@yahoo.com
MSN: koolbuddhi@hotmail.com
SKYPE: koolbuddhi

**Comment by SteveSandersonMS** [comment]
Thanks for answering, @koolbuddhi!
