### ISSUE TITLE
Instructions for Server Side PreRendering using the 2.1.0 Template

### ISSUE THREAD

**Issue by QuinntyneBrown** [aspnet/JavaScriptServices#1590]
Unable to find clear end-to-end instructions on how to prerender using the 2.1.0 template.

The home page says "If you want to enable server-side prerendering, see the steps in Startup.cs." But there is not much in the Start up.

There is a BuildServerSideRenderer configuration in the project file, so I'm assuming I can enable it.

Thanks

**Comment by kemmis** [comment]
+1

@QuinntyneBrown Did you figure this out?
