### ISSUE TITLE
Error TS2350 when create a new Promise in certain situations

### ISSUE THREAD

**Issue by QuinntyneBrown** [aspnet/JavaScriptServices#1591]
Using the .NET Core 2.1 Template when creating a new Promise in certain situation, you get a TS2350 error.

It looks like there is another Promise type definition that Visual Studio is getting confused with, Q.IPromise.

The following code inside a HubClient Service will raise an error as the compiler thinks I'm trying to use Q.IPromise and not the native promise.

  public connect(): Promise<any> {
    if (this._connect) return this._connect;
    
    this._connect = new Promise((resolve) => {
      this._connection = this._connection || new HubConnection("/signalrDemoHub");
      this._connection.start().then(() => resolve());
    });

    return this._connect;
  }

**Comment by QuinntyneBrown** [comment]
![image](https://user-images.githubusercontent.com/1749159/37904663-781057f4-30ca-11e8-9d92-432162c5d176.png)

**Comment by exequielc** [comment]
same error ehere
