### ISSUE TITLE
HMR doesn't work with docker

### ISSUE THREAD

**Issue by pmaza** [aspnet/JavaScriptServices#1593]
Hi!

We have a problem with docker. When we deploy the app in debug mode with docker, the changes from server don't reflect in the container. It seems that the port where angular cli is listenning should be open in the docker container.
I think that the problem is when the method UseAngularCliServer exec the npm script (start script in this case), the port is assigned randomly, so we can't know which port is used by angular cli to listen the changes from server.
We need to know/set the port where hmr is working to open it in the container definition.

**Comment by SteveSandersonMS** [comment]
Since this is a question about how to configure Angular CLI, could you please see Angular CLI docs? Thanks!
