### ISSUE TITLE
Cross domain calls on SSR

### ISSUE THREAD

**Issue by leonardochaia** [aspnet/JavaScriptServices#1599]
Hello all, I'm using the new template `dotnet new angular` with the angular-cli. I've striped everything and left only the Fetch Data part. (HTTP call done to an API on the same project)

I've enabled SSR according to [MSDN blog](https://docs.microsoft.com/en-us/aspnet/core/spa/angular?tabs=visual-studio).

I've enabled CORS to allow any Origin, Method, Header, and Credentials.

If I open the browser (Chrome) to `http://localhost:5000/` the API call is done on the server and the results are prerendered correctly.

If I browse to a subdomain, i.e: `http://foo.localhost:5000/` the API call is not performed on the server (fails), but does succeed on the client. 

Relevant Server Logs ( [complete logs](https://gist.github.com/leonardochaia/1a43aa7d44c71e02bd454350d4daf548) )

```
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://foo.localhost:5000/  
info: Microsoft.AspNetCore.NodeServices[0]
      http://foo.localhost:5000/api/SampleData/WeatherForecasts
fail: Microsoft.AspNetCore.NodeServices[0]
      HttpErrorResponse {
        headers: HttpHeaders { normalizedNames: Map {}, lazyUpdate: null, headers: Map {} },
        status: 0,
        statusText: 'Unknown Error',
        url: null,
        ok: false,
        name: 'HttpErrorResponse',
        message: 'Http failure response for (unknown url): 0 Unknown Error',
        error: 
         ProgressEvent {
           type: 'error',
           target: 
            XMLHttpRequest {
              onloadstart: null,
              onprogress: null,
              onabort: null,
              onerror: null,
              onload: null,
              ontimeout: null,
              onloadend: null,
              _listeners: [Object],
              onreadystatechange: null,
              _anonymous: undefined,
              readyState: 4,
              response: null,
              responseText: '',
              responseType: 'text',
              responseURL: '',
              status: 0,
              statusText: '',
              timeout: 0,
              upload: [XMLHttpRequestUpload],
              _method: 'GET',
              _url: [Url],
              _sync: false,
              _headers: [Object],
              _loweredHeaders: [Object],
              _mimeOverride: null,
              _request: null,
              _response: null,
              _responseParts: null,
              _responseHeaders: null,
              _aborting: null,
              _error: null,
              _loadedBytes: 0,
              _totalBytes: 0,
              _lengthComputable: false },
           currentTarget: 
            XMLHttpRequest {
              onloadstart: null,
              onprogress: null,
              onabort: null,
              onerror: null,
              onload: null,
              ontimeout: null,
              onloadend: null,
              _listeners: [Object],
              onreadystatechange: null,
              _anonymous: undefined,
              readyState: 4,
              response: null,
              responseText: '',
              responseType: 'text',
              responseURL: '',
              status: 0,
              statusText: '',
              timeout: 0,
              upload: [XMLHttpRequestUpload],
              _method: 'GET',
              _url: [Url],
              _sync: false,
              _headers: [Object],
              _loweredHeaders: [Object],
              _mimeOverride: null,
              _request: null,
              _response: null,
              _responseParts: null,
              _responseHeaders: null,
              _aborting: null,
              _error: null,
              _loadedBytes: 0,
              _totalBytes: 0,
              _lengthComputable: false },
           lengthComputable: false,
           loaded: 0,
           total: 0 } }
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 2248.4028ms 200 text/html
```

The URL is correct (second info log), quick Google results seems to point to CORS not being enabled, but it is. 

I've tested it using `spa.UseProxyToSpaDevelopmentServer("http://localhost:4200")` instead of the `AngularCliMiddleware` and the same result happens on 5000 port.
Also, if browsing to the SPA development server on port 4200, with it being forced to perform the API calls against `http://localhost:5000` it works, which should mean that CORS is working fine.

Here's a [repo reproducing the issue](https://github.com/leonardochaia/JavaScriptServicesTests)
Any guidance will be appreciated. 
Thank you,
Leo.

**Comment by SteveSandersonMS** [comment]
Can you add some logging to your code so that you can see what `params.origin` and `params.baseUrl` values are being received by your `main.server.ts`? That might clarify whether the issue is happening inside your .NET code or in your TypeScript code.

**Comment by leonardochaia** [comment]
On a working request, i.e: `http://localhost:5000` that would be:
```
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:5000/  
info: Microsoft.AspNetCore.NodeServices[0]
      params.origin: http://localhost:5000
info: Microsoft.AspNetCore.NodeServices[0]
      params.baseUrl: /
```

On a failing request: i.e :`http://foo.localhost:5000`

```
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://foo.localhost:5000/  
info: Microsoft.AspNetCore.NodeServices[0]
      params.origin: http://foo.localhost:5000
info: Microsoft.AspNetCore.NodeServices[0]
      params.baseUrl: /
```

I have added on `main.server.ts`:

```
export default createServerRenderer(params => {
    console.log(`params.origin: ${params.origin}`);
    console.log(`params.baseUrl: ${params.baseUrl}`);
[..]
}
```

Thank you very much. 
Any other info, or test I'd be happy to perform using the repo I've provided.
Leo.

**Comment by leonardochaia** [comment]
@SteveSandersonMS maybe this has anything to do with this issue, but using the `UseProxyToSpaDevelopmentServer` also reproduces the issue.

[AngularCliMiddleware.cs](https://github.com/aspnet/JavaScriptServices/blob/d6588c31bf0dc8e97af248a650197ba23bc097fc/src/Microsoft.AspNetCore.SpaServices.Extensions/AngularCli/AngularCliMiddleware.cs)
```
// Everything we proxy is hardcoded to target http://localhost because:
// - the requests are always from the local machine (we're not accepting remote
//   requests that go directly to the Angular CLI middleware server)
// - given that, there's no reason to use https, and we couldn't even if we
//   wanted to, because in general the Angular CLI server has no certificate
var targetUriTask = angularCliServerInfoTask.ContinueWith(
    task => new UriBuilder("http", "localhost", task.Result.Port).Uri);
```

**Comment by SteveSandersonMS** [comment]
@leonardochaia Thanks for the additional info.

> Everything we proxy is hardcoded to target http://localhost

That's unrelated (if I'm understanding correctly). That remark is about how we proxy to the Angular CLI middleware (which is always running on `localhost`, even if your web app is hosted on some other hostname, even when running locally). It doesn't have anything to do with the hostname that your ASP.NET Core app is running on, which is what should matter in this case.

> On a failing request: i.e :http://foo.localhost:5000
> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
>     Request starting HTTP/1.1 GET http://foo.localhost:5000/  
> info: Microsoft.AspNetCore.NodeServices[0]
>      params.origin: http://foo.localhost:5000
> info: Microsoft.AspNetCore.NodeServices[0]
>      params.baseUrl: /

OK then, so as far as I can tell, your server-side code is getting the correct `origin` information and should be issuing requests to the correct location. I don't know when then it isn't. Could you also put logging into your `fetchdata` page to see what exact URL it's making the outbound HTTP request to? Assuming it is targeting the correct hostname, any failure would suggest it's some sort of networking issue rather than being a defect in your application logic. For example, maybe your OS is preventing the Node process from making connections to hosts other than `localhost` for some reason.

**Comment by leonardochaia** [comment]
@SteveSandersonMS Thanks for your quick response.
My fetchdata page is performing the HTTP request to the correct API call as seen on logs posted on the issue:
```
info: Microsoft.AspNetCore.NodeServices[0]
      http://foo.localhost:5000/api/SampleData/WeatherForecasts
```
I know the log doesn't say so, sorry about that, but that's the URL the failing request is being performed to. The URL does work.

> any failure would suggest it's some sort of networking issue rather than being a defect in your application logic. For example, maybe your OS is preventing the Node process from making connections to hosts other than localhost for some reason.

Ok, so I'll try to run the sample repo on another host, or maybe setup a Docker container to try this.
Leo.

**Comment by leonardochaia** [comment]
I've realized that Chrome is magically pointing urls like foo.localhost to localhost.
I'm not doing anything explicitly to serve content on these urls so Node can not find it.
I've done the same test using different ports and it appears to be working correctly.
Sorry for the trouble @SteveSandersonMS,
Leo.
