### ISSUE TITLE
OWIN Support

### ISSUE THREAD

**Issue by wasabii** [aspnet/JavaScriptServices#1600]
This is a crazy request, since nobody should care anymore. But I have a lot of legacy apps, that I'm slowly migrating one by one into more rich JS stuff. I'd love to be able to have webpack hot reload working in a classic OWIN pipeline.

**Comment by Eilon** [comment]
@wasabii sorry no plans at this time to support OWIN directly. If you wanted to take a crack at it, and have the time, you could consider porting the code yourself (and maybe even release it to the world!). By my understanding of the code, it's probably not a monumental effort, but it's just not something we can devote any time to given our other priorities. Thanks!
