### ISSUE TITLE
Webpack dev middleware not working on Windows when folders contain spaces

### ISSUE THREAD

**Issue by jtheisen** [aspnet/JavaScriptServices#1609]
This is independent from the other issue I just filed.

In the react template (I assume with others as well), webpack will not rebuild on changes when the folder name of the project contains spaces.

Folders on Windows often contain spaces: (User name, DropBox (<CompanyName>), etc.).

Short of fixing the issue, it would be cool to at least have a warning that this is why it doesn't work. It's difficult to guess that this is the problem otherwise and it's easily worked around once the programmer realizes how.

**Comment by SteveSandersonMS** [comment]
Glad you tracked it down.

Since this is an issue inside Webpack, it's not something we can easily control or even detect. The good news however is that this should not affect the latest templates which are based on Angular CLI and create-react-app.
