### ISSUE TITLE
New 2.0 Angular Template - Home Controller/View ASP.NET Authentication 

### ISSUE THREAD

**Issue by aherrick** [aspnet/JavaScriptServices#1613]
I've created a file/new of the 2.0 Angular Template.

I've noticed that the angular cli index.html page is not mapped through a Controller/Action when loading. 

What I want is for Controller Home/Action Index to return the index.html page that angular-cli JSON is configured.

Otherwise, how would I apply ASP.NET Auth against my main App? Traditionally I would add an AUTHORIZE attribute to my Controller.

Another way of asking this...

How can I host the SPA on an MVC/CSHTML page instead of the angular cli index.html? Is it even possible... should I just be using the 1.0 Angular Template at this point?

**Comment by ADefWebserver** [comment]
Would this work for you? [An Angular 4 .Net Core 2.0 Example With Application Shell and Authentication](http://lightswitchhelpwebsite.com/Blog/tabid/61/EntryId/4312/An-Angular-4-DotNetCore-2-0-Example-With-Application-Shell-and-Authentication.aspx)

**Comment by syedm0** [comment]
I am looking for exactly the same functionality. I need to setup an input element in cshtml which could be accessible by the angular components (to pass data from server) and don't want to use server side pre-rendering.

I just downloaded the latest template using command: 

dotnet new --install "Microsoft.DotNet.Web.Spa.ProjectTemplates"

Then I went on to create a new project using :

dotnet new angular
The template "ASP.NET Core with Angular" was created successfully.

However the result project only had an API Controller (SampleDataController.cs) and did not contain the Views folder. Not sure if I got the correct template.

Can someone please comment?

**Comment by Vx2gas** [comment]
@aherrick @syedm0 Look to this thread.
[https://github.com/aspnet/JavaScriptServices/issues/1518#issuecomment-386035771](url)

**Comment by aherrick** [comment]
I've added basic B2C to my App. Using something similar to below to redirect user to force auth.

```
            app.UseAuthentication();

            app.Use(async (context, next) =>
            {    
                if (!context.User.Identity.IsAuthenticated)
                {
                    await context.ChallengeAsync(OpenIdConnectDefaults.AuthenticationScheme,
                        new AuthenticationProperties { RedirectUri = "/" });
                    return;
                }
                await next.Invoke();
            });
```
