### ISSUE TITLE
Incorrect timeout message when timeout set to 60s or more

### ISSUE THREAD

**Issue by martinstenhoff** [aspnet/JavaScriptServices#1614]
If you configure a StartupTimeout of 60 seconds or more (e.g. using `spa.Options.StartupTimeout = TimeSpan.FromSeconds(60);` in app.UseSpa) and the timeout triggers you get the following slightly confusing message:

_The Angular CLI process did not start listening for requests within the timeout period of 0 seconds. Check the log output for error information._

This is due to the timeout messages using TimeSpan.Seconds instead of TimeSpan.TotalSeconds.

**Comment by SteveSandersonMS** [comment]
Thanks for reporting this! Closing in favour of #1615.
