### ISSUE TITLE
Localization?

### ISSUE THREAD

**Issue by Junik** [aspnet/JavaScriptServices#162]
Whether there is a strategy for the localization via this approach? Particularly if the resources are in the database?

**Comment by laskoviymishka** [comment]
Check-out great write-up how to manage localization in a2 _https://damienbod.com/2016/04/29/angular-2-localization-with-an-asp-net-core-mvc-service/_

**Comment by SteveSandersonMS** [comment]
> Whether there is a strategy for the localization via this approach? Particularly if the resources are in the database?

It's a great question, but I suspect beyond the scope of what would be useful in the templates. Adding that concern would make things significantly harder for people to understand, so I think that should be addressed by separate posts/docs, e.g., the one @laskoviymishka linked to.
