### ISSUE TITLE
Template not used when adding .net Core stateless service in Service Fabric

### ISSUE THREAD

**Issue by John-Bell** [aspnet/JavaScriptServices#1622]
Hi

After installing the new templates dotnet new --install Microsoft.DotNet.Web.Spa.ProjectTemplates::2.0.0 the new Angular (angular-cli) version is used through Visual Studio,  

However when adding a stateless .net core Service to a Service Fabric Application and selecting 'Angular', the older webpack based template is used.

**Comment by SteveSandersonMS** [comment]
Thanks for reporting this. Moving the issue to https://github.com/Microsoft/service-fabric-aspnetcore/issues/55
