### ISSUE TITLE
Load and execute JS from database

### ISSUE THREAD

**Issue by samcov** [aspnet/JavaScriptServices#1623]
I want to store the script files in a database. 

The only problem is that I can't find a method to do this, one like,

string JsScript = FromNoSqlStore(id);
var result = await _nodeServices.InvokeAsync<int>(JsScript, p1, p2);

Is there a way to do this?

**Comment by SteveSandersonMS** [comment]
It's probably better to ask this "how to" question on StackOverflow, as this issue tracker is for tracking work bugs or features requests for JavaScriptServices. Hope that's OK!

**Comment by samcov** [comment]
I'm not asking a how to question, I'm asking an existence question.

I've seen how this might be accomplished using temp files, but that still requires a file, and I'm asking if you guys have, or will surface an invocation that works with a string.
