### ISSUE TITLE
spa.UseAngularCliServer(npmScript: "start") Does not work when targeting .NET Framework

### ISSUE THREAD

**Issue by groogiam** [aspnet/JavaScriptServices#1627]
I am attempting to use the new SPA template while targeting .NET 4.6.2. I have modified the template slightly to remove the AspNetCore.All  packages and include the .NET standard nuget packages. However when doing this the angular cli server fails to start. I have attached a repro project. 

Is it possible to use the new template with .NET framework. The old template seems to have issues with angular material and converting many of our libraries to .NET Core is not feasible at the moment.

[SpaTest.zip](https://github.com/aspnet/JavaScriptServices/files/1949650/SpaTest.zip)

**Comment by SteveSandersonMS** [comment]
The latest templates do support .NET Framework. The way to create a .NET Framework project is, for example:

```
dotnet new angular --target-framework-override net462
```

I just verified the generated project (with ASP.NET Core 2.1.0-rc1-final) starts the Angular CLI server successfully. You don't need to edit the csproj manually.
