### ISSUE TITLE
Is there anyway to show warnings in the overlay too?

### ISSUE THREAD

**Issue by archonsunny** [aspnet/JavaScriptServices#1628]
I know the devServer settings get ignored in the webpack.config.js.

But is there anyway to get the overlay to show warnings? 

So that it'd be equivalent to setting:

```
devServer {
  overlay: {
    warnings: true,
    errors: true
  }
}
```

**Comment by SteveSandersonMS** [comment]
Sorry, I'm not aware of a specific way of doing that. It may be possible but this is more of a Webpack question.

Also note that it's not applicable to the latest templates, as they don't have a Webpack configuration at all.
