### ISSUE TITLE
SPA Templates Typescript

### ISSUE THREAD

**Issue by SihirliDev** [aspnet/JavaScriptServices#1629]
Hello,

Did the templates change to JavaScript? I've installed .net core 2.1 preview and saw that the files Javascript files and the directory structure also changed.

Where can I find more information about the changes to templates?

Thank you.

**Comment by eblancperso** [comment]
@SihirliDev Did you find any response to your issue? I have the same question. React's spa template changed from tsx to js files.

**Comment by gehnster** [comment]
After much looking around it and trying to fully understand the changes to the react-redux SPA I think I figured it out. It looks like the react and react-redux templates now use the create-react-app npm package to help create them and that is why they are no longer typescript. I think then they are then adding the redux packages for that template and their own starting client code to keep in-line with the other templates.

**Comment by eblancperso** [comment]
@gehnster Yep! The work around I did is to use the "create-react-app" CLI with the typescript flag and copy/paste all tsx files into the ClientApp folder from .Net Core. You will also need to modify the package.json to add proper script and dependencies.

**Comment by SteveSandersonMS** [comment]
Yes, that's exactly correct. It's based on `create-react-app`, which produces `.jsx` files.

**Comment by SteveSandersonMS** [comment]
@poimis That's not standard. It's getting the script content from a third-party NPM package, which we have no idea if it will be maintained or stay correct over time.

**Comment by gittestcoder** [comment]
> @poimis That's not standard. It's getting the script content from a third-party NPM package, which we have no idea if it will be maintained or stay correct over time.

Do you know what the last commit was before switching over to CRA?
