### ISSUE TITLE
Question: Changing the base href for Angular app

### ISSUE THREAD

**Issue by chrissainty** [aspnet/JavaScriptServices#1630]
I'm working on an Angular SPA using the new templates in core 2.1. But I need to change the `<base href>` when I publish to production. I know with the Angular CLI I can add the --base-href argument to change it. What is the recommended way of doing this with the new templates?

**Comment by chrissainty** [comment]
I've kind of got things working by putting dev base href in the start script and the prod base href in the build script in the package.json file. Not sure this is the right way to do it but seems to have gotten things loading.

**Comment by chrissainty** [comment]
@cvalerio I added the --base-href switch with the prod base URL to the build command in the package.json file, as this is what get called when a production build is created.

**Comment by sispor** [comment]
> @cvalerio Agregué el modificador --base-href con la URL base de prod al comando de compilación en el archivo package.json, ya que esto es lo que se llama cuando se crea una compilación de producción.

your explain it's not very complet, can you paste the code? please
