### ISSUE TITLE
Change Json.net default to camel case causes HMR to stop working

### ISSUE THREAD

**Issue by sherif-elmetainy** [aspnet/JavaScriptServices#1631]
#### Steps to reproduce: 

- Create a new angular application
```dotnet new angular```
- In Startup.cs constructor type the following code
```JsonConvert.DefaultSettings = () => new JsonSerializerSettings() { ContractResolver = new CamelCasePropertyNamesContractResolver() };```
- Run the app.

#### Result
Angular will run in production mode and HMR will not be enabled.

#### Expected Result
Angular should run in development mode and HMR would be enabled.

#### Reason
The HotModuleReplacement property is serialized as hotModuleReplacement while WebpackDevMiddleware.js file in aspnet-webpack npm package expects it to start with a capital letter.

#### Workaround
I solved the issue by removing the line that changes Json.net default settings. However, I think a better solution would be putting JsonProperty attributes on the properties that get serialized.

**Comment by SteveSandersonMS** [comment]
Thanks for the report. I'm glad you've got a workaround. Also to note, the newer Angular template does not have this issue any more.
