### ISSUE TITLE
SpaTemplates V2.0.7 fail to install

### ISSUE THREAD

**Issue by belugabob** [aspnet/JavaScriptServices#1636]
For some reason, installing this on my desktop machine has no effect.
Using the commandline...

`dotnet new --install Microsoft.AspNetCore.SpaTemplates::2.0.7`

...seems to complete correctly, but a subsequent invocation of...

`dotnet new angular`

...generates a project in the same style as when I had V2.0.0 of the template installed.
The distinguishing factor (for me) is the a 2.0.0 project has `package.json` in the root of the project, and a 2.0.7 project has `package.json` in the `ClientApp` directory. (and the 'burger' menu works correctly in a 2.0.7 project)
The reason that I know what the two version of a project should look like is because I did the same upgrade (to V2.0.7 of the template) on my laptop and the effect was immediately noticable.

Am I missing something subtle - have checked versions of Node/NPM/Visual Studio etc. and can't see any differences?

**Comment by belugabob** [comment]
I've just realised one thing that's different - desktop = Windows 7, laptop = Windows 10

**Comment by belugabob** [comment]
Update: As of today, attempts to create a new project - on either my desktop or laptop - result in a V2.0.0 style project. This is very perplexing, as I very clearly have an existing project that uses the V2.0.7 style, so I must have had the update template working at some point. Maybe this is the result of recent VS2017 updates?

**Comment by SteveSandersonMS** [comment]
It's also possible that you have multiple .NET Core SDK installations, and were generating projects in the context of a different SDK than the one with the newer template installed. In any case, I'm glad it's now all straightened out for you!
