### ISSUE TITLE
Webpack sample makes requests to `/dist/__hmr_endpoint` - bug in UseWebpackDevMiddleware?

### ISSUE THREAD

**Issue by sm-g** [aspnet/JavaScriptServices#1638]
Because this commit https://github.com/aspnet/JavaScriptServices/commit/44f86eb8a111b91ef0600ea035362634eb3c26f0#diff-cf4fed006c4f5ac483999ecf02221e0d made it to always do requests to `publicPath + hmrEndpoint`

**Comment by SteveSandersonMS** [comment]
As far as I'm aware, HMR works correctly in the shipped templates. I'm not sure whether your report is to say that it doesn't work, or just that it's also doing something unexpected and under what circumstances. If you are able to provide more specific information (e.g., repro steps) we can figure out whether there's an issue to be fixed. Hope that's OK!

**Comment by sm-g** [comment]
Commit I am talking about changed expected url.

Repro: just run sample
