### ISSUE TITLE
Add support for Angular 2 RC4 and new router

### ISSUE THREAD

**Issue by rmaspoch** [aspnet/JavaScriptServices#164]
Please consider upgrading to the latest Angular 2 release candidate bits and the new router.

**Comment by SteveSandersonMS** [comment]
Will definitely get to it. We only just updated to RC3 a few days ago. They appear too fast to keep up with in realtime :)

The latest templates already use the new router (as of the RC3 update) BTW.

**Comment by aggrojus** [comment]
I just upgraded to my local version of the template to RC4 and the latest router.  The initial load in the dev environment failed with the error ... Invalid route configuration of route '{path: "", redirectTo: "home"}' ...  I resolved it by changing it to { path: '', redirectTo: 'home', pathMatch:"full" },

**Comment by doczoidberg** [comment]
what router version do you use? Beta2?

**Comment by MarkPieszak** [comment]
Can be implemented in PR #205 if/when it's merged

**Comment by SteveSandersonMS** [comment]
Thanks @MarkPieszak - this was merged :)
