### ISSUE TITLE
React JS, dotnet core 2.0.5, AWS Lambda -> requestPathAndQuery is null

### ISSUE THREAD

**Issue by cjnoname** [aspnet/JavaScriptServices#1653]
Hi,

I have a new app running on AWS lambda, it's built on reactJS 16 and dotnet core 2.0.5.

Now I got a issue when I push it to AWS, the param.location is null then the site won't work.

I tried to hacked in the code and make it working, but the Route is not working correctly due to this issue because it rely on requestPathAndQuery

Please help to give me some advices.

Thanks
Cheng

**Comment by SteveSandersonMS** [comment]
I'm sorry, but this issue report doesn't give enough information. I don't know what's different about AWS Lambda specifically, compared with other .NET Core hosting environments. This scenario certainly works in a standard .NET Core hosting environment.

If you have more information, could you please reopen or file a new issue, specifying what is different about your hosting environment that causes the URL not to be known at runtime? Then we'll have an idea about whether it's a scenario we can support. Hope that's OK!
