### ISSUE TITLE
Uncaught ReferenceError: vendor_ is not defined when using DllReferencePlugin

### ISSUE THREAD

**Issue by sturatcliffe** [aspnet/JavaScriptServices#1660]
Firstly, apologies for raising yet another issue around this, I've already tried everything in [this](https://github.com/aspnet/JavaScriptServices/issues/717) one with no luck.

I've put together a sample application which displays this issue for me, it can be found [here](https://github.com/sturatcliffe/Vue2Dotnet2SSR). The steps to reproduce are as follows:

Clone the above repo  
dotnet restore  
npm install  
npm run webpack  
dotnet run  

I receive the following error: *NodeInvocationException: vendor_19f7ef894c06af9bbdef is not defined*  

I've tried everything in the issue linked above, as well as playing around with the DllPlugin settings in both webpack.config.js and webpack.config.vendor.js. The only way to get the app working that I've found so far is to remove the following from webpack.config.js:

```
new webpack.DllReferencePlugin({
  context: __dirname,
  manifest: require("./wwwroot/dist/vendor-manifest.json")
})
```

Any ideas what I'm missing? I'm sure it's something very simple but I can't figure it out!

I'm running node v8.9.3 / npm v5.6.0 / dotnet v2.1.3 if it helps.

Cheers

**Comment by SteveSandersonMS** [comment]
Since this is a Webpack config question (and you have a custom Webpack configuration), would you be able to raise it with the Webpack community? Thanks!

**Comment by sturatcliffe** [comment]
Hi @SteveSandersonMS - this was originally generated using the dotnet CLI (VueJS template). All I've done is remove TypeScript for personal preference, and add a couple of extra parts around SCSS and ES6 support. The DllReference code is all standard dotnet template as far as I can recall? Cheers.

**Comment by SteveSandersonMS** [comment]
`DllReferencePlugin` is a standard Webpack feature, not a .NET Core feature. I don't think we ever had support for SSR in the Vue template.

**Comment by sturatcliffe** [comment]
No the VueJS template doesn't have SSR, I'm just trying to add it in but as soon as I render on the server I get this issue. Client rendering is fine. I'll jump on SO and raise it there.

Thanks for your help.

**Comment by selaromdotnet** [comment]
hey @sturatcliffe did you ever get this working? I'm facing a similar issue (linked above) perhaps you can offer some insight?
