### ISSUE TITLE
aspnet-webpack support?

### ISSUE THREAD

**Issue by rgamage** [aspnet/JavaScriptServices#1661]
Given that the aspnet-webpack NPM page has this message:

"You should not use this package directly in your own applications, because it is not supported, and there are no guarantees about how its APIs will change in the future."

Does this suggest we should not be using this template at all, if we are needing a Production application that will need to be maintained and supported?  I'm very hesitant to move forward with any design that has a critical dependency on a package the author says I shouldn't use.

Is there an alternative to using this package as a dependency?

Thanks,
Randy

**Comment by SteveSandersonMS** [comment]
It only means that its intended usage is within those template only. It doesn't mean that you shouldn't use it at all, but rather that its design is entirely to support those templates, and we're not implementing any features for other scenarios outside those templates.
