### ISSUE TITLE
JavaScriptServices vs Templating github

### ISSUE THREAD

**Issue by ShaneCourtrille** [aspnet/JavaScriptServices#1674]
@SteveSandersonMS has pointed to aspnet/templating#515 a few times for the update towards Angular 6 and so I'd like some clarification as to the difference between this github issues list vs that one.  Do we watch both or are we okay on just this one?

**Comment by SteveSandersonMS** [comment]
The templating repo is for the template content, whereas the JavaScriptServices repo is for the NuGet packages it uses (SpaServices, NodeServices, etc.)
