### ISSUE TITLE
HMR is always one update behind

### ISSUE THREAD

**Issue by mover96** [aspnet/JavaScriptServices#169]
After I start the server, the first time I update a module the HMR fails, but all subsequent changes are successful. However the change before the most current one is the one that is successfully reloaded. For example, I start the server with `<div></div>`. Then I change it to be `<div>Hi</div>` and the update fails. So I change it to `<div>Hello</div>` and the HRM is sucessful and `<div>Hi</div>` is what is displayed. Next update no matter what it was would display `<div>Hello</div>` etc.

**Comment by SteveSandersonMS** [comment]
Thanks for reporting this.

If you have any information on how to reproduce this fault (e.g., with a fresh `yo aspnetcore-spa`-generated project on a clean machine), or what might be unique about your dev machine that might trigger this, please let us know. I've never personally seen this happen and don't have any guesses about what might cause it, so without more info I probably won't be able to do much about it :(

**Comment by SteveSandersonMS** [comment]
Oh, I just spotted the other issue you opened then closed. Are you using Webpack 2.0 **beta**? If so, that's not something I've tried, and it wouldn't be surprising to find breaking changes.

If you do want Webpack 2.0 beta support, I would welcome pull requests (assuming they don't break Webpack 1.0 support, and are clearly explained :) ).

**Comment by mover96** [comment]
Yes I am using Webpack 2 beta, but I think all of the changes I made were to the aspnet-webpack npm package that the middleware uses. That and then the webpack configs in the generators would be the only changes for webpack 2 support! But the aspnet-webpack package is outside of this repo, correct?

**Comment by mover96** [comment]
And I was having this issue before I updated the aspnet-webpack package to webpack 2, but also my config files were written for webpack 2 so maybe that was the issue. I will try either downgrading or trying to reproduce with a fresh install to see if I can get it to be recreated!

**Comment by mover96** [comment]
Here is the error I get from the aspcore server when it detects the first file change. The first one fails with the follow error, and then all subsequent changes are successful, but are for the change before them (hence the one behind error). Let me know if you have any ideas, this may be something simple I am overlooking, I am not too familiar with dotnet core!

```
[Node] webpack building...
[Node] webpack built 3a5583a7fe5414b4e736 in 1780ms
fail: Microsoft.AspNetCore.Server.WebListener.MessagePump[0]
      ProcessRequestAsync
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 41708.7617ms 200 text/event-stream; charset=utf-8
fail: Microsoft.Net.Http.Server.WebListener[0]
      Abort
```

**Comment by mover96** [comment]
Well apparently Kestrel is extremely important to getting the HMR to work. By adding UseKestrel to my startup I got this working. Thanks for all the help!
