### ISSUE TITLE
Unable to build project (Windows)

### ISSUE THREAD

**Issue by pealmeid** [aspnet/JavaScriptServices#180]
I'm trying to follow the directions on the `README.md` file without success. The steps I'm following are:
- Clone the repo
- Run `dotnet restore` at the repo root dir
- Go to sample (cd templates/Angular2Spa)
- Restore NPM dependencies (run `npm install`)
- Launch (`dotnet run`)

However, on step 2 (`dotnet restore` at root) I'm getting the following `Unable to resolve` errors:

![errors](https://cloud.githubusercontent.com/assets/6384219/16824425/27104416-4942-11e6-97e1-069fb9c295e2.png)

I'm running version 3180 of `dotnet` (in Windows):

![version](https://cloud.githubusercontent.com/assets/6384219/16824463/6e573a32-4942-11e6-86e2-efac9fc737d2.png)

Thanks in advance!

**Comment by SteveSandersonMS** [comment]
You're on preview 3 of the `dotnet` tooling, but the current released version is preview 2 (specifically, `1.0.0-preview2-003121`).

While I would expect everything here to work with bleeding-edge nightly builds of `dotnet`, it's not something I can guarantee. If you want things to just work, I'd recommend downgrading to the currently supported `dotnet` version. If you want to continue with preview 3, I'm afraid you'll have to figure out what else is needed to get all the references to work (and if you do, please let us know!).
