### ISSUE TITLE
The instructions should include npm install npm -g

### ISSUE THREAD

**Issue by jvelezc** [aspnet/JavaScriptServices#186]
I had an old version of npm and the template only worked after I updated npm. 
I am referring instruction here:
http://blog.stevensanderson.com/2016/05/02/angular2-react-knockout-apps-on-aspnet-core/

**Comment by SteveSandersonMS** [comment]
Thanks for the suggestion. That blog post does already mention this:

> If you’re on Windows, make sure your installation is new enough to have NPM version 3+ (run npm -v to find out) otherwise you’ll have a bad time.

... so I hope that's enough for now, but if more people report confusion, I can amend the wording. Glad you sorted it out in your case!
