### ISSUE TITLE
Simple task like adding a new module

### ISSUE THREAD

**Issue by jvelezc** [aspnet/JavaScriptServices#187]
npm install angular --save-dev
then i just try to add 
import angular from 'angular' 

I get cannot find module 'angular' 

What is the procedure to register angular or any other module so that it is discoverable?

**Comment by SteveSandersonMS** [comment]
This sounds more like an Angular question, so you might want to follow up with them. But my guess is that, if you're using Angular 1 which doesn't include TypeScript support by default (which Angular 2 does), then you'll need to get hold of some suitable `.d.ts` files for the Angular 1 libraries.

This looks like a reasonable guide: https://coderwall.com/p/qsrzyq/getting-started-with-typescript-angular

**Comment by jvelezc** [comment]
You are right I have to add typings d.ts files and then Visual Studio stopped complaining. I guess Angular2 being better tricked me.
