### ISSUE TITLE
Successful installation! But still being given, what causes it? Thank you!

### ISSUE THREAD

**Issue by wspnet** [aspnet/JavaScriptServices#189]
C:\Users\weisp\AppData\Roaming\npm\node_modules\sharp

Successful installation! But still being given, what causes it? Thank you!

An unhandled exception occurred while processing the request.

Exception: Call to Node module failed with error: Error: Cannot find module 'sharp'
at Function.Module._resolveFilename (module.js:325:15)
at Function.Module._load (module.js:276:25)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
at Object.<anonymous> (F:\Qibu\src\Qibu.Web\Node\resizeImage.js:1:75)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Module.require (module.js:353:17)
MoveNext

Stack Query Cookies Headers
Exception: Call to Node module failed with error: Error: Cannot find module 'sharp' at Function.Module._resolveFilename (module.js:325:15) at Function.Module._load (module.js:276:25) at Module.require (module.js:353:17) at require (internal/module.js:12:17) at Object.<anonymous> (F:\Qibu\src\Qibu.Web\Node\resizeImage.js:1:75) at Module._compile (module.js:409:26) at Object.Module._extensions..js (module.js:416:10) at Module.load (module.js:343:32) at Function.Module._load (module.js:300:12) at Module.require (module.js:353:17)
MoveNext
ThrowForNonSuccess
HandleNonSuccessAndDebuggerNotification
GetResult
MoveNext
ThrowForNonSuccess
HandleNonSuccessAndDebuggerNotification
GetResult
MoveNext
ThrowForNonSuccess
HandleNonSuccessAndDebuggerNotification
GetResult
MoveNext in ResizeImage.cs
            var imageStream = await _nodeServices.InvokeAsync<Stream>(
ThrowForNonSuccess

**Comment by SteveSandersonMS** [comment]
I can see from your other issue (#190) that you've now succeeded in installing `sharp`, so I guess this issue is now redundant, so I'll close it.

If I'm wrong and you think there's a problem installing the module, please reopen with any further details you have.
