### ISSUE TITLE
Aurelia Template?

### ISSUE THREAD

**Issue by leak** [aspnet/JavaScriptServices#196]
Any news about the Aurelia template mentioned here: https://github.com/aspnet/JavaScriptServices/pull/118#issuecomment-224571062

Or alternatively if someone else already has tackled this, please do share some wisdom (and code) ;)

**Comment by SteveSandersonMS** [comment]
No news - I've been in contact with the Aurelia team and they mentioned that support for server-side rendering is on the way, so I'm waiting for that. I don't have an ETA, but you could chat with the Aurelia team and perhaps come up with a proposal for how the JavaScriptServices template for Aurelia should work.

**Comment by leak** [comment]
Alright, thanks for the update.
