### ISSUE TITLE
I want to add to the cache, there is better than my way? 

### ISSUE THREAD

**Issue by wspnet** [aspnet/JavaScriptServices#197]
`Response.Headers.Add("Last-Modified", DateTime.Now.ToString("U", DateTimeFormatInfo.InvariantInfo));
            DateTime IfModifiedSince;
            if (DateTime.TryParse(Request.Headers["If-Modified-Since"], out IfModifiedSince))
            {
                if ((DateTime.Now - IfModifiedSince.AddHours(8)).Seconds < 10)
                {
                    Response.StatusCode = 304;
                }
            }`

I want to add to the cache, there is better than my way? I hope it is permanent in nature cached on the client, and the same access to the general characteristics of the image

**Comment by SteveSandersonMS** [comment]
Yes, this is a built-in feature of ASP.NET - see https://docs.asp.net/en/latest/performance/caching/response.html

**Comment by wspnet** [comment]
`[ResponseCache(Duration = 60 * 60 * 24 * 365, Location = ResponseCacheLocation.Any)]
        [Route("resize_{maxWidth}_{maxHeight}/{*imagePath}")]
        public async Task<IActionResult> Index(string imagePath, int maxWidth, int maxHeight)
        {`

I did not see the cache Status 304

**Comment by RehanSaeed** [comment]
The ResponseCache sets the `Cache-Control` HTTP header while you are using `Last-Modified`. One is not better than the other. They have different purposes. `Cache-Control` deals with when the resource will expire in the future while `Last-Modified` deals with when it was modified in the past.
