### ISSUE TITLE
Don't force Node to be on the PATH

### ISSUE THREAD

**Issue by andersekdahl** [aspnet/JavaScriptServices#20]
From what I can read, the code currently assumes that Node is on the PATH. I think it's a good idea not to bundle a specific version of Node with this package, but it would be great if it was possible to specify where the Node executable is. Would make it easier to deploy multiple sites using this to the same server where the different sites use different Node versions.

**Comment by SteveSandersonMS** [comment]
Good idea. This config option could be added to the `services.AddNodeServices(config)` API, with the default being to continue assuming Node is on the system path.

Pull requests are welcome :)

**Comment by SteveSandersonMS** [comment]
For anyone wondering how to override the path where the `node` executable is found, you can do it like this:

public class MyHttpNodeInstance : HttpNodeInstance
{
    protected override ProcessStartInfo PrepareNodeProcessStartInfo(string entryPointFilename, string projectPath, string commandLineArguments)
    {
        var startInfo = base.PrepareNodeProcessStartInfo(entryPointFilename, projectPath, commandLineArguments);
        // Now modify 'startInfo' to specify where the Node executable should be found
        return startInfo;
    }
}

... and then set `MyHttpNodeInstance` as the active Node instance type, as per the docs at https://github.com/aspnet/JavaScriptServices/tree/dev/src/Microsoft.AspNetCore.NodeServices#custom-hosting-models.
