### ISSUE TITLE
[Question] - What is the dependency type of the "aspnet-webpack" package?

### ISSUE THREAD

**Issue by dopare** [aspnet/JavaScriptServices#203]
I can see that "aspnet-webpack" package is either in "dependencies" ( [Angular2Spa](https://github.com/aspnet/JavaScriptServices/blob/dev/templates/Angular2Spa/package.json),   [ReactReduxSpa] (https://github.com/aspnet/JavaScriptServices/blob/dev/templates/ReactReduxSpa/package.json) ) or in "devDependencies" ( [KnockoutSpa](https://github.com/aspnet/JavaScriptServices/blob/dev/templates/KnockoutSpa/package.json), [ReactSpa](https://github.com/aspnet/JavaScriptServices/blob/dev/templates/ReactSpa/package.json)  ) .  

Is there any purpose for this difference or it just a mistake ?

**Comment by MarkPieszak** [comment]
It might of just been an accident, aspnet-webpack is just to add webpack configuration into the Statup.cs process. I'm sure it could be moved to devDependencies for everything without an issue. Did you test it out and it worked fine that way?

**Comment by dopare** [comment]
It works fine for me, created #207 PR

**Comment by SteveSandersonMS** [comment]
Thanks - the PR was merged :)

**Comment by dopare** [comment]
Thank you :)
