### ISSUE TITLE
[Proposal] recipies for some additional documentation

### ISSUE THREAD

**Issue by laskoviymishka** [aspnet/JavaScriptServices#206]
It may have sense to have some folder with all recipies about best practices, like adding sass support and lazy loading etc. 
It could be a Wiki for a project, which is right now empty, or just a *recepies* folder with *recipie_name*.md files.

Does it make sense? So if anyone have a good practice for some feature adding he may just submit a pull request that add a new recipie in our recepie collection :+1:

**Comment by SteveSandersonMS** [comment]
Sounds good to me!

There's already [a wiki in this repo](https://github.com/aspnet/JavaScriptServices/wiki). Please feel free to set up a structure you think will meet these needs. If there are any issues with this (e.g., if you don't have permission according to GitHub or something), please let me know.
