### ISSUE TITLE
[Question] - script files

### ISSUE THREAD

**Issue by dazinator** [aspnet/JavaScriptServices#214]
When calling `_nodeServices.InvokeAsync<string>()` you can only pass a module name, and then you have to make sure a physical file containing your module exists, in your project directory.

How do I execute something, passing the script itself? I want to avoid having to create a file. Is that a possiblity?

The reason I am looking to do this is because I want to distribute my library as a NuGet package, and I don't want the consumers of my library (via  a nuget package manager) to have to worry about also manually creating the appropriate `.js` files in their project directories. NuGet doesn't seem to support adding content files to projects anymore in the latest project systems.. 

Any guidance would be appreciated :-)

**Comment by SteveSandersonMS** [comment]
The NuGet packages in this repo face the exact same quandry (they want to embed their own JS in the package), so they use the technique of writing the scripts to disk as a temporary file that gets cleaned up when they are done.

This technique is encapsulated in the `Microsoft.AspNetCore.NodeServices.StringAsTempFile` class, which is publicly exported from the `Microsoft.AspNetCore.NodeServices` package. You can see an example of its use here: https://github.com/aspnet/JavaScriptServices/blob/dev/src/Microsoft.AspNetCore.NodeServices/HostingModels/OutOfProcessNodeInstance.cs#L45

**Comment by dazinator** [comment]
Ok - cheers, will give `StringAsTempFile`  file a go.
