### ISSUE TITLE
CSS: ExtractTextPlugin & Hot Module Reload

### ISSUE THREAD

**Issue by rustybox** [aspnet/JavaScriptServices#215]
For me CSS reloading is one of the most important things.
This currently doesn't work out of the box with the Angular2 template.

My solution at the moment is to switch out the loader when in development.
` { test: /\.css/, loader: isDevelopment ? "style-loader!css-loader" : ExtractTextPlugin.extract(styles) }`

If this is a suitable solution and there isn't a better way to solve the problem I will gladly throw together a pull request?

**Comment by xabikos** [comment]
So far this is the best solution based on my knowledge. The ExtractTextPlugin in general is used only for the final bundles that will be part of the production application. During development it's acceptable according to me to embed all the styles inside `styles` html elements in the head of the document in order to have the hot module reload.

**Comment by SteveSandersonMS** [comment]
Agreed with @xabikos.

Though I've been wondering for a while what's to stop `ExtractTextPlugin` from supporting HMR (e.g., when it's notified that there's a new version of the content, it could remove the old `<link>` element and insert a new one to load the updated styles). This would obviously be completely independent of JavaScriptServices - it would be a general enhancement to `ExtractTextLoader`. I'm not personally expecting to have capacity to work on that any time soon, but if anyone else does, it would be great to see such an enhancement!

**Comment by rustybox** [comment]
Whilst I agree it would be great if ExtractTextPlugin supported this better, the current community response seems to be that ExtractTextPlugin is intended only for production, and that by design one should use the other css loaders for dev work.

**Comment by eness** [comment]
As stated in the README of ExtractTextPlugin ([](https://github.com/webpack/extract-text-webpack-plugin)) one of the caveats of using ExtraxtTextPlugin is that it disables your webpack's hot module replacement feature.
