### ISSUE TITLE
Angular routes don't match on server with non-root BASE_URL (waiting on universal #495)

### ISSUE THREAD

**Issue by baseless** [aspnet/JavaScriptServices#217]
Hi!
Im applying the js services with prerendering to part of an application. But is having issues getting components to pre-render properly when applying app prefix (i.e using http://site/appName instead of root).

So if i would like to use `/AppName/` as starting point i add `<base href="/AppName/" />`, set the `ngCore.provide(APP_BASE_HREF, { useValue: '/AppName/' })` in boot-server.ts and add `templatePrefix: "AppName"` to the MapSpaFallbackRote. This effectively results in the ** route always being the prerendered content. This seems to indicate some routing issue, but it all seems correct and works fine other than this.

Is there something im missing here? Or should this be all that is needed?

**Comment by SteveSandersonMS** [comment]
I tracked this down to a surprising behaviour in `angular2-universal` and have filed an issue here: https://github.com/angular/universal/issues/495

The issue is that `angular2-universal` currently expects the `REQUEST_URL` values you give to it to have the `BASE_URL` prefix stripped off already. If you don't strip off that prefix, it generates malformed URLs internally that won't match your route configuation.

Until that bug is fixed - or if they decide they want to keep the current behaviour - you can work around it in your `boot-server.ts` logic. Here's an example that does strip off the base URL before `angular2-universal` gets involved:

```typescript
import 'angular2-universal/polyfills';
import * as ngCore from '@angular/core';
import { APP_BASE_HREF } from '@angular/common';
import { provideRouter } from '@angular/router';
import * as ngUniversal from 'angular2-universal';
import { BASE_URL, ORIGIN_URL, REQUEST_URL } from 'angular2-universal/common';
import { App } from './components/app/app';
import { routes } from './routes';

const BaseHref = '/AppName/';

const bootloader = ngUniversal.bootloader({
    async: true,
    preboot: false,
    platformProviders: [
        ngCore.provide(APP_BASE_HREF, { useValue: BaseHref })
    ]
});

// This is a workaround for https://github.com/angular/universal/issues/495
function removeBaseHrefPrefix(url: string) {
    return url.indexOf(BaseHref) === 0
        ? '/' + url.substring(BaseHref.length)
        : url;
}

export default function (params: any): Promise<{ html: string, globals?: any }> {
    const config: ngUniversal.AppConfig = {
        directives: [App],
        providers: [
            ngCore.provide(ORIGIN_URL, { useValue: params.origin }),
            ngCore.provide(REQUEST_URL, { useValue: removeBaseHrefPrefix(params.url) }),
            ...ngUniversal.NODE_HTTP_PROVIDERS,
            provideRouter(routes),
            ...ngUniversal.NODE_LOCATION_PROVIDERS,
        ],
        // TODO: Render just the <app> component instead of wrapping it inside an extra HTML document
        // Waiting on https://github.com/angular/universal/issues/347
        template: '<!DOCTYPE html>\n<html><head></head><body><app></app></body></html>'
    };

    return bootloader.serializeApplication(config).then(html => {
        return { html };
    });
}
```

**Comment by baseless** [comment]
Thanks a bunch, tried it and your workaround solves it.
