### ISSUE TITLE
TypescriptServices and custom CompilerHost 

### ISSUE THREAD

**Issue by dazinator** [aspnet/JavaScriptServices#218]
I'm fairly new to typescript, but reading some docs, the typescript compiler has an interface that abstracts away the underlying file system, it looks like this:

```
interface CompilerHost {
    getSourceFile(filename: string, languageVersion: ScriptTarget, onError?: (message: string) => void): SourceFile;
    getDefaultLibFilename(options: CompilerOptions): string;
    getCancellationToken?(): CancellationToken;
    writeFile(filename: string, data: string, writeByteOrderMark: boolean, onError?: (message: string) => void): void;
    getCurrentDirectory(): string;
    getCanonicalFileName(fileName: string): string;
    useCaseSensitiveFileNames(): boolean;
    getNewLine(): string;
}

```

Heres an implementation: https://github.com/Microsoft/TypeScript/blob/59608778a64a599c42351e68749fe4543935836d/src/harness/unittests/reuseProgramStructure.ts#L106

How cool would it be, if we could implement one of these, where `getSourceFile()` calls back into the `IFileProvider` that NodeServices is using in your aspnet core app?

This would allow us to run a typescript compiler, that can see / access all the files that your asp.net application can see - which may include files from any source, not just physical files.

Am I barking up the wrong tree here? 

I'd be happy to try and give this ago but i'm not sure where to start with how to implement a callback from nodejs code into .net to hook my .NET IFileProvider.. I'm assuming i'd have to fork `NodeServices` and make changes somewhere..

If we did do such a thing, we could put this in a project called `TypeScriptServices` ?

**Comment by SteveSandersonMS** [comment]
> How cool would it be, if we could implement one of these, where getSourceFile() calls back into the IFileProvider that NodeServices is using in your aspnet core app?

It's an interesting prospect, though TBH I'm unsure of the use case. Could you clarify how you think this would be applicable in typical projects?

> I'd be happy to try and give this ago but i'm not sure where to start with how to implement a callback from nodejs code into .net to hook my .NET IFileProvider.. I'm assuming i'd have to fork NodeServices and make changes somewhere..

That's right. Invocations from Node to .NET have not been a requirement for anything else in NodeServices. Having that sort of bidirectional RPC facility (and losing the existing client-server model) would complicate the setup significantly and would introduce additional security considerations, so we have avoided it.

If you make progress on this I'll be interested to see where it ends up, and whether it might be applicable for other people's apps!

In the meantime I'll close this as there's no action for us to take in the JavaScriptServices repo right now. Thanks!

**Comment by dazinator** [comment]
No probs, thanks for the insight!

> Could you clarify how you think this would be applicable in typical projects?

Yeah - I don't think this would be applicable to typical `aspnet core` projects at the moment, because most typical projects are not interested in typescript compilation at runtime. Most projects are using compilation on build, and seperate / external watcher processes to re-compile when changes to typescript files are made. 

But.. if you are an adventurous soul like me, and want your running `asp.net core` application to be "the watcher" (when in dev mode) and processing your build pipeline for assets automatically when they change (j the same process), then this idea could be beneficial because a running asp.net core application is sitting on an an `IFileProvider` and assets cannot always be assumed to be physical files, they be embedded or resolvable from other sources.
