### ISSUE TITLE
Spa generator with Angular 1.5 error.

### ISSUE THREAD

**Issue by asadsahi** [aspnet/JavaScriptServices#220]
Hi @SteveSanderson , 

I am attempting to configure the spa generator with Angular 1.5 after reading [this](https://github.com/aspnet/JavaScriptServices/issues/213) conversation. Followed these steps:

1. Scaffold using Angular 2 template
2. removed Angular 2 dependencies, and installed angular 1 packages
3. Just created basic angular 1.5 component
4. Created vendor manifest file.

.. but getting window not defined, as shown below

![image](https://cloud.githubusercontent.com/assets/3470892/17158203/8fc802ce-538c-11e6-987d-8d8eaebf97f2.png)

Can you please guide me, how I can get angular 1.5 working with spa generator? Is there any sample with Angular 1.x?

I have created a git repository with current snapshopt [here] (https://github.com/asadsahi/AspNetCoreAngularWebpack): if you want to investigate.

Appreciate your time.

Thanks

**Comment by asadsahi** [comment]
Right, the error is gone after removing the asp-prerender-module="ClientApp/index" from index.cshtml, as we don't want to render angular 1.5 based code through node. 
This is because of reliance on window and dom etc as explained by @laskoviymishka [here](https://github.com/aspnet/JavaScriptServices/issues/105).

Next problem is with the HMR, any change in file gives this warning and doesn't reload the app:

![image](https://cloud.githubusercontent.com/assets/3470892/17170309/6072c20a-53e3-11e6-9025-40c72d8f5fd7.png)

Any guesses why?

**Comment by SteveSandersonMS** [comment]
As per your comment on #213, it sounds like Angular 1.x is not compatible with Webpack HMR.

I'm surprised because I would have thought it could at least have just wiped out all its previous DOM and started up a new instance of the app (that's how the Knockout HMR template works, even though KO itself has no knowledge of HMR). But maybe Angular 1.x relies on persistent things like globals, properties on `window`, etc., which can't be reset or changed once they are defined.

So it doesn't sound like there's much we can do for Angular 1.x. Do you think we can close this issue, or is there more you think we can do?

**Comment by MarkPieszak** [comment]
@asadsahi @SteveSandersonMS I've been able to achieve HMR (which ends up doing a full page refresh, but better than nothing) in Angular1 you just need to tell Webpack at the ROOT client app file to accept it.

    // Required for Webpack to ensure children modules have the ability to Hot reload themselves
    module.hot.accept();

I did this right after initializing the main App module itself. Hope that helps!

**Comment by asadsahi** [comment]
Thanks @SteveSandersonMS.  I cannot find any success story of webpack + angular 1+ hmr online. So, I think we cannot win this war. I will close it for now.

@MarkPieszak  I would love to even see the full page reload in aspnet core spa generator, if that is possible. Can you please share the settings or an example on github with full reload on changing client assets? 

Thanks all.

**Comment by asadsahi** [comment]
@MarkPieszak did you manage to get angular 1 app full reloading working inside asp.net core spa generator?

**Comment by asadsahi** [comment]
@MarkPieszak  Got this working, by triggering the reload on hot dispose handler. Happy to hear any better solution.

```

require('angular');

import { AppComponent } from './components';


declare var module: any;


angular.module('app', [])
    .component('app', new AppComponent());


if (module.hot) {
    module.hot.accept();
    module.hot.dispose(function (data) {
        window.location.reload();
    });
}


```

**Comment by MarkPieszak** [comment]
Very nice! @asadsahi 
I have a private repo that is able to do it (I haven't made public just yet), but it doesn't have aspNET in it, it's straight up ng1 & node instead. There must be something else I'm doing with either gulp or webpack to avoid doing dispose & location reload. I'll take a look

**Comment by asadsahi** [comment]
Thanks @MarkPieszak , I have implemented reload using gulp and node based project or using webpack dev server for a node based project. But with Asp.Net, and webpack, I haven't found a single project on internet which does client compilation and reload. So, aspnet core spa generator by Steve Sanderson is an awesome effort for .net Community. Angular 1 with webpack and asp.net was a gap, which got a temporary solution right now until I find a better solution. :)

Thanks again.
