### ISSUE TITLE
Setting node's NODE_ENV based off of ASPNETCORE_ENVIRONMENT?

### ISSUE THREAD

**Issue by pauldotknopf** [aspnet/JavaScriptServices#230]
Or, allow us to manually specific environment variables for the node instances ourselves.

**Comment by SteveSandersonMS** [comment]
Yes, this sounds good! If you want to do a PR that would be great, otherwise I'll get to this within the next couple of weeks.

**Comment by SteveSandersonMS** [comment]
Now implemented. I'll publish updated packages soon.

I've also added an `EnvironmentVariables` property to `NodeServicesOptions` you can use to pass arbitrary env vars.

If you just want `NODE_ENV` set to `development`/`production` based on your ASP.NET app's hosting environment, you don't have to do anything - this now happens automatically.
