### ISSUE TITLE
[Question/Bug] NodeServices[0] [fail] ts-loader: Using typescript@1.8.10 and c:\**\**\tsconfig.json

### ISSUE THREAD

**Issue by baseless** [aspnet/JavaScriptServices#231]
Hi folks
I got an issue in an app im building and im unsure exactly what caused it. When running it in Kestrel, **the first line that appears** is an error: "NodeServices[0] [fail] ts-loader: Using typescript@1.8.10 and c:\**\**\tsconfig.json" and thats it. The application then works fine, both prerender and client render. But i realized that this breaks azure publishing through visual studio for example.

I first assumed it was some of my code, but i couldnt locate anything. So i checkedout an old branch which i previously deployed successfully to azure -> same error. So i created a new empty project and pasted the samplecode from the sampleproject (yo aspnetcore-spa angular2) and got the exact same error. Running the sample project worked however.

Now im starting to suspect if it perhaps is something that is broken after i updated visual studio 2015or something. But i **wanted to check if anyone here knows what this error means** (it tells me absolutely nothing in regards as to what is wrong). As said everything works perfectly efter that error has passed locally.

**Comment by MarkPieszak** [comment]
Do you have `ts-loader` installed in your **node_modules**? It's the webpack loader used to compile TS files. It's strange that it would work, but still give you an error on the kestrel & azure side.

**Comment by frankwallis** [comment]
@baseless the message 'ts-loader: Using typescript@1.8.10 and /.../tsconfig.json' is just a normal console message which ts-loader always outputs when starting the compilation, it's not an error. Not sure why NodeServices is prefixing it with [fail]

**Comment by baseless** [comment]
Thanks for the input. Frank: i see the message in the older generated aspnetcore project as well (but it dont fail there). Mark: Yes i include the exact versions and dependencies specified by the generated yeoman template.

Tried the above on the newest version of the yeoman template for angular2 which i cgenerated a while ago. This do not give the same error and it worked locally. But examining it, the parameter `ts-loader?silent=true` has been added. Removing that and i get the same error. it still do not seem to work when uploading to azure.

Will do more tests during the evening, the azure part could perhaps be something in the code in my original project. 

But frankwallis: Is it expected that it is actually prefixed as fail? It is not sign of an error in itself? Was unsure if you stated it was strange i got it or its strange that nodeservices does it that way.

**Comment by nil4** [comment]
https://github.com/TypeStrong/ts-loader/issues/249 explains why *Using typescript@* is seen as an error: it is printed to stderrr instead of stdout.

**Comment by baseless** [comment]
This is solved. It was enough to add the flag for silent ts-loader (thus avoiding the compile exception) and it seems to work nu. The strange thing is how this worked before without this flag. I know i ran some updates for vs, but strange if that would have affected it.

ANYWAY seems like the thread that nil4 provided link with covers this and after adding the silent trigger it works so i thank you for the input and go ahead and close this.
