### ISSUE TITLE
VS 2015 vs dotnet run

### ISSUE THREAD

**Issue by dknaack** [aspnet/JavaScriptServices#232]
I use the ReactRedux Template. 

If i start the app using `dotnet run` it starts, listen on port 5000 and everything (javascript) works as expected.

However, if i start using Visual Studio 2015 it listens on another port and the javascript does not work. The Chrome Dev Tools says "Uncaught Error: Cannot find module "./ClientApp/boot-client.tsx".

**Comment by dknaack** [comment]
There was a problem. I used the repo and did a mistake setting it up. After using the generator it works.

**Comment by dcarl1** [comment]
What was the issue? I'm having the exact same problem using the generator.
