### ISSUE TITLE
reflect-metadata is missing in package

### ISSUE THREAD

**Issue by shivakb** [aspnet/JavaScriptServices#239]
When i start build the application the  error is throwing 

ERROR in ./ClientApp/boot-client.ts
Module not found: Error: Cannot resolve module 'reflect-metadata' in /Users/Andrew/Projects/myYoApp/ClientApp
@ ./ClientApp/boot-client.ts 4:0-27

**Comment by MarkPieszak** [comment]
Is `reflect-metadata` in your **node_modules**? You might want to try deleting that folder, and reinstalling `npm i`

**Comment by ronnyek** [comment]
I've noticed that this happens.. and it is as easy as manually installing. Even though I added reflect metadata to my package.json, when doing things like building docker containers, it fails to install reflect-metadata correctly for whatever reason. (I'm no NPM guru, just that I've encountered this, and have had problems at least with the angular2 template not successfully AUTOMATICALLY installing reflect-metadata)

**Comment by nklt** [comment]
is there a fix or a work around for this issue?

**Comment by ronnyek** [comment]
I think npm i reflect-metadata should be fine, but I don't know how to actually fix it for my problems regarding docker

**Comment by ronnyek** [comment]
Any ideas on this one? Its starting to become a problem. I'd like to build a prototype of an idea I've got, but cant seem to get templates generated for angular2 spa to be able to run inside of a container because of runtime javascript problem with the location of reflect-metadata.

**Comment by ronnyek** [comment]
FYI I just installed latest node/npm, installed generators and ran generator from scratch for new angular2 spa, and it worked without a hitch, even in building my docker containers... maybe its a npm version >3 thing

**Comment by SteveSandersonMS** [comment]
Yep, I just remembered we already knew about this (see #82) :)

Sorry I didn't remember that earlier - could have saved you some trouble...
