### ISSUE TITLE
Angular2 - 'TypeError: str.replace is not a function' when using [disabled]

### ISSUE THREAD

**Issue by baseless** [aspnet/JavaScriptServices#245]
Noticed that multiple [] tags do not work in the out of the box 'yo aspnetcore-spa' generated project.

For example by adding `test: boolean = false;` to counter.ts and then adding `[disabled]="test"` to the submit button in the html form. This generates the exception 

> Exception: Call to Node module failed with error: TypeError: str.replace is not a function
> at escapeString (D:\Repos\_Samples\YoNgSpa\node_modules\angular2-universal\node_modules\parse5\lib\serialization\serializer.js:27:10)

ONLY when directly using the url localhost:5000/counter. If using the routerlink to access the counter component it works.

Another issue is for example if adding the method `test() { return false; }` to the counter.ts and adding `[style]="disabled: test()"` to the submit button on the html form. This generates a 

> quotes are not supported for evaluation!

 error originating from vendor.js

Unsure if this is an issue with Angular2 och with nodeservices but it seems to make these tags impossible to use.

**Comment by baseless** [comment]
This actually seems to boil down to the fact that im using boolean as property type. When using string it works. I assume this is an angular2 matter, not javascriptservices at all, so ill close this.

**Comment by MarkPieszak** [comment]
You need to do [attr.disabled], we need to update this in the Universal side as well since we should allow for either use-case. There will be some fixes with parsing coming from universal so give it time :)
