### ISSUE TITLE
Should Html.PrimeCache be named Html.PrimeCacheAsync?

### ISSUE THREAD

**Issue by justinvp** [aspnet/JavaScriptServices#246]
MVC APIs that return `Task`/`Task<T>` have the `Async` suffix, e.g. [`Html.PartialAsync`](https://github.com/aspnet/Mvc/blob/93be3dee6e96e9de19825a9d0d4fc9f483d2dc9e/src/Microsoft.AspNetCore.Mvc.ViewFeatures/ViewFeatures/HtmlHelper.cs#L490).

For consistency with MVC APIs and as an indicator to developers that they should `@await` the result, shouldn't [`Html.PrimeCache`](https://github.com/aspnet/JavaScriptServices/blob/b684aeb6d2bc9e6f3aebc6846d331fa6a1ad4932/src/Microsoft.AspNetCore.AngularServices/PrimeCacheHelper.cs#L14) be named `Html.PrimeCacheAsync`?

**Comment by SteveSandersonMS** [comment]
Yes, I think you're right! Will add that as a new overload and will mark the old one as obsolete.

**Comment by justinvp** [comment]
While you're at it, maybe the new overload should return `Task<IHtmlContent>` instead of `Task<HtmlString>` (like `Html.PartialAsync`), which would allow the results to be written to a `TextWriter` instead of having to concatenate/format/allocate a (potentially large) string to return with `HtmlString`? `HtmlString` itself implements `IHtmlContent` so the existing implementation could remain as-is for now; returning `Task<IHtmlContent>` leaves the door open to perf improvements in the future.

**Comment by justinvp** [comment]
(To give you an idea, I prototyped some potential changes to the existing implementation earlier this weekend: https://github.com/aspnet/JavaScriptServices/commit/4c7bdcfc19d067df5ee93689818450bb44234877)

**Comment by SteveSandersonMS** [comment]
Implemented. As per your suggestion, also changed the return type to `Task<IHtmlContent>`. Currently it's still using `HtmlString` but could change to a custom less-allocatey alternative like your prototype in the future.
