### ISSUE TITLE
Duplicate <html> tag in markup for angular

### ISSUE THREAD

**Issue by andreymir** [aspnet/JavaScriptServices#251]
For angular template, with server-side rendering enabled the resulting markup is invalid. It contains duplicate `<html>` and `<body>` tags.
```html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Home Page - TestAngular</title>
        <base href="/" />
        <link rel="stylesheet" href="/dist/vendor.css" />
        <link rel="stylesheet" href="/dist/styles.css" />
    </head>
    <body>
<app><!DOCTYPE html><html><head><title></title></head><body><app><h1>My First Angular 2 App</h1></app></body></html></app>
<script src="/dist/vendor.js?v=ST5Wa4e5mzPX7ta66f3OtVqEjo2qferfDltnP-noHNg"></script>
<script src="/dist/main.js?v=xXJhvd8rq7SFv-t1CDTZ0d9PUS2-IRftQ4NTA_R9aqc"></script>
</body>
</html>
```

**Comment by ronnyek** [comment]
I believe this is actually a known thing related to a angular-universal bug https://github.com/angular/universal/issues/347

**Comment by andreymir** [comment]
While it is not supported by angular could we update `boot-server.ts` and remove incorrect tags from the result like this:
``` javascript
    return bootloader.serializeApplication(config).then(html => {
        return { html: html
                .replace('<!DOCTYPE html><html><head><title></title></head><body><app>', '')
                 .replace('</app></body></html>', '') };
    });
```
?

**Comment by SteveSandersonMS** [comment]
@andreymir Absolutely - that's a good workaround for now.

We don't want to put that in the templates because it looks confusing and we're hoping the angular/universal#347 issues will get fixed soon anyway. But for your own use in your own project, your workaround looks ideal.

**Comment by MarkPieszak** [comment]
I still owe you a fix for 347 in Universal, apologies been swamped lately! @SteveSandersonMS
