### ISSUE TITLE
Hotloading TSX files with interfaces does not seem to be working

### ISSUE THREAD

**Issue by dcarl1** [aspnet/JavaScriptServices#254]
This might be my setup, but hotloading React modules crashes if you reference an interface:

**IFormInput.ts**

```
export interface IFormInput
{
   Value?: string;
   OnModelChange?: Function;
   PropertyName?: string;
   ValidationError?: string;
}
```

**React Module**
```
import {IFormInput} from "./IFormInput";

@observer
export default class FormInputGroup extends React.Component<IFormInput, any>
{
 ...trimmed react code
}
```

Webpack builds everything fine and the application works, however when I make a change and the hotloader fires I get several errors around the interface:

![image](https://cloud.githubusercontent.com/assets/4975773/17597725/6c26524c-5fb4-11e6-88b4-252b11fa7564.png)

**Comment by dcarl1** [comment]
I redid how I import things and now it seems to work fine:

Exporting all components/interfaces in a single file:

```
export * from "./Form";
export * from "./FormTextBox";
//export * from "./FormDropDown";
export * from "./FormInputGroup";
export * from "./FormLabel";
export * from "./FormSubmitButton";
export * from "./IFormInput";
export * from "./IFormModel";
```

And then importing via:

`import * as FormComponents from '../../Forms/FormImports';`

Seems to fix hotloading.

**Comment by SteveSandersonMS** [comment]
Glad you got it fixed. I'm not aware of any specific technical issues with using TypeScript that way, but will keep a lookout in case anyone else reports troubles.
