### ISSUE TITLE
Update to React 15

### ISSUE THREAD

**Issue by geirsagberg** [aspnet/JavaScriptServices#255]
`aspnet-webpack-react` currently uses React 0.14, which leaves `data-reactid`-attributes all over the output. Updating to v 15 will fix this, and some other issues (https://facebook.github.io/react/blog/2016/04/07/react-v15.html).

**Comment by SteveSandersonMS** [comment]
Sounds good! Would you be able to submit a pull request?

**Comment by geirsagberg** [comment]
Yup, see #256.

**Comment by SteveSandersonMS** [comment]
Thanks - closing in favour of #256

**Comment by geirsagberg** [comment]
A quick note; seems the `react-id`-attributes are still there in React 15 when calling `renderToString`, as they are needed to connect the client code. Still, updating to React 15 shouldn't have any adverse effects.
