### ISSUE TITLE
Update to Angular2 Final

### ISSUE THREAD

**Issue by doczoidberg** [aspnet/JavaScriptServices#257]
please support the latest release.

**Comment by danjford** [comment]
They'll probably have to wait for Angular2-universal to update as well as there are breaking changes with Angular2 RC5. Here is their [RC issue](https://github.com/angular/universal/issues/511).

**Comment by MarkPieszak** [comment]
Yes it's still a work in progress, the changes created quite a ripple effect in Universal. It's a top priority though!

**Comment by MarkPieszak** [comment]
I'll update and setup a PR in the next few days once everything is implemented / tested and published. Still need to iron out a few kinks, you can track PR https://github.com/angular/universal/pull/524 if you'd like. Sorry for the delay!

**Comment by doczoidberg** [comment]
RC6 is around the corner. maybe rc5 should be skipped?

**Comment by MarkPieszak** [comment]
Luckily we can use Universal the same, the problem we're facing internally in Universal for rc6 is ensuring we still have access to all some Core Angular APIs that will soon be private (when rc6 ships), which is delayed at the moment due to a few outstanding issues & a TS2 bug. With luck the update for rc6 will be just a version bump :) Haha but you never know!

**Comment by lydemeister** [comment]
@MarkPieszak What is the status on the rc6 update?

**Comment by MarkPieszak** [comment]
There are still a few outstanding issues we're facing before being able to publish the rc5/6 version of Universal (which will set us up to be prepared for the 1.0 release which is coming shortly as well (but it has no breaking changes thank god!)

The moment we publish Universal I'll refactor and update :)

**Comment by MarkPieszak** [comment]
So we finally have things more fine tuned and I'll update to rc7 by Friday! 😀

**Comment by vandensd** [comment]
Looking forward to the updates!  Will the yo Generator update as well with all the goodies?

**Comment by MarkPieszak** [comment]
Sure will, Steve's generator uses the templates inside the repo itself, so it will all be there :)

**Comment by mikelunn** [comment]
Now that Angular 2 finally officially released yesterday, i'm really looking forward update. The whole build pipeline with these next generation javascript frameworks are ridiculously complex. I love that this project template gives you a way to hit the ground running.

**Comment by hheexx** [comment]
Aungular-universal is also updated yesterday.
No show stoppers for updating templates now.

**Comment by MarkPieszak** [comment]
Working on it now :) @hheexx 
There might be some issues (from a Universal point of view) why I was waiting until we ironed out all of the kinks. But if anything Universal-related shows up, you can open up an issue at: https://github.com/angular/universal/issues or let me know here so I can take a look!

**Comment by MJomaa** [comment]
@MarkPieszak Should one wait until it is updated or can you use the template now and update the missing parts manually?

**Comment by MarkPieszak** [comment]
I'd say wait, I've had some delays since the changes we had to make in Universal were drastic but feel like I should have this finished up today, then we just need Steve to take a look and make sure everything checks out. 

If you're just working on the Angular components themselves, or REST API, I'm sure you could get going and copy over most of that to a newer project template without any problems!

Trying to clean up the typescript 2 PR as well.

**Comment by MJomaa** [comment]
@MarkPieszak Thank your for your response, I appreciate it.
The REST API is finished, so I will wait.  Don't rush it :)

**Comment by MarkPieszak** [comment]
I just posted the PR (#319) to upgrade to Angular 2.0.0, Universal 2.0.7, Preboot 4., and TypeScript 2.0 (which I needed to be able to include universal 2..)

This includes the NgModules, separate ones for both Client & Server, and is connected with the latest Universal API and updates.

Let me know here or create an issue under (https://github.com/angular/universal-starter/issues) if anything Universal-related comes up! There were major changes there, so something is bound to creep up. 

The other projects will be upgraded to TS2.0 in the other PR, #258 when it's finished. (ReactReduxSpa was using outdated tsd files)

**Comment by vandensd** [comment]
Thanks for the update @MarkPieszak. I'm in no hurry but monitoring when everything is up to date. I'm actually still on RC2 for my stuff since I decided to hold when things were in flux.  The template has been a great benefit to have and keep up the good work!

**Comment by ptk86** [comment]
Is the aspnetcore-spa generator updated to Angular2 1.0? I reinstalled it and it still produces Angular 2 2.0.0-rc.4. Could you help?

**Comment by SteveSandersonMS** [comment]
Now done :)

@ptk86 - It is updated and published to NPM as of about 30 minutes ago. You can update your generator by running `npm install -g generator-aspnetcore-spa`.

**Comment by doczoidberg** [comment]
thanks for your great work!

**Comment by tanwarsatya** [comment]
Not sure if someone tried the latest NPM or not. With all the defaults and even running webpack commands manually, when trying to run the application using VS it's not working.

**Comment by mikelunn** [comment]
@tanwarsatya This blog post has some good information about what the repository has to offer:
[angular2-react-knockout-apps-on-aspnet-core](http://blog.stevensanderson.com/2016/05/02/angular2-react-knockout-apps-on-aspnet-core/)

Make sure you first
`npm install -g yo generator-aspnetcore-spa`
`npm install -g webpack`
`cd some-empty-directory`
`yo aspnetcore-spa`
`dotnet run`

Also, make sure you have the latest DotNetCore 1.0.1. I had 1.0.0, and when running dotnet run I received warning messages that it was required to have 1.0.1 installed.

**Comment by MJomaa** [comment]
@tanwarsatya

Make sure to have **Node 4.x** installed, because else **to-string loader** will break.

Update Node simply with the Windows installer: https://nodejs.org/en/download/

And make sure to call  ```webpack``` atleast once before ```dotnet run```.

**Comment by vandensd** [comment]
@SteveSanderson 

Performed a generator install a few days ago without a hitch.
Now today when an NPM install occurs on a new generator run (clean directory) core-js no longer comes down... in addition to a few other discrepancies in node_modules.

Problem is in Visual Studio Intellisense is not recognizing 'require' and 'Promise'.  I believe core-js was filling this void.

**Comment by tinchou** [comment]
I think it's actually @types/node, but check for yourself :)

**Comment by vandensd** [comment]
@tinchou 
Agree this is the correct typings file and maybe core-js is not the factor...

However, VS (Enterprise 2015 Update 3)

Intellisense was non issue running generator a few days ago
Today it is

Interested in knowing what the solution might be

**Comment by tinchou** [comment]
Maybe the update to Typescript 2 had something to to with it? I remember I
recently found an issue that pointed me to removing core-js completely. I
think it was angular universal, that brings its own polyfills.

I can look it up tomorrow if you don't find it.

**Comment by vandensd** [comment]
@tinchou 

Any help would be appreciated.  I'm finding node, npm, day to day versioning and dependency changes, etc. hard to deal with when all I want is something that works out of the box...

As long as I don't update specific packages, I can roll with the node_modules installed a few days ago.  So no rush except I'm sure others will run into issues like I am and a solution somewhere would be beneficial.

**Comment by hheexx** [comment]
I had the same problem and solved it by moving tsconfig from ClientApp to root.

**Comment by MarkPieszak** [comment]
Yes actually Steve we need to move the ts config back to root, almost forgot it can't go "down" directories when looking for @types or anything, just like packagejson webpack, they all need to be in the root 😓
