### ISSUE TITLE
All project files are in non-UTF encoding

### ISSUE THREAD

**Issue by ysilvestrov** [aspnet/JavaScriptServices#259]
All project files after yeoman generator are created in non-UTF encoding (in my case - Windows 1251), which lead to national characters (in my case - Cyrillic) are corrupted.
After resaving from Visual Studio with UTF8 encoding, the issue has gone.

**Comment by SteveSandersonMS** [comment]
Can you give repro instructions?

I'm not 100% sure what you mean when you say the files are saved in a non-UTF encoding, given that without a BOM (which the files don't have) or any special chars (which the generator doesn't itself put in the files), the UTF-8 encoding of the file is bitwise-identical with ASCII. As such, I'm not clear how it's meaningful to say the files are in one encoding or another. Only when you edit them to include some extended-range characters would a difference appear, and then it's your choice of encoding when you save the edited file.

No doubt you are correct that there's something for us to fix here - I'm just not sure what, so would appreciate specific steps that show something going wrong! Thanks.

**Comment by SteveSandersonMS** [comment]
In the absence of more info, I'll close this, but if anyone is able to provide repro information, please let us know!

**Comment by ysilvestrov** [comment]
Looks like it's rather up to VS2015.
However, to reproduce it, you need the following (Win 10 anniversary update x64, VS2015 community edition, Windows 1251 is set as system default for non-UTF):

1. generate the Angular2 project using `yo aspnetcore-spa`
2. try to edit e.g. the Startup.cs file with Notepad++. It shows that the file is in UTF8 encoding.
3. open the generated .xproj file with VS2015
4. open Startup.cs from within VS2015, add some Cyrillic chars, save the file
5. open Startup.cs with Notepad++ - it shows that file is in Windows 1251 encoding
6. save Startup.cs from VS2015 setting the encoding to UTF8 - now everything works right.
