### ISSUE TITLE
Will not run

### ISSUE THREAD

**Issue by AndrewKralovec** [aspnet/JavaScriptServices#260]
After i create the projects  and do the npm install, i run dotnet run this is what i get. 
Compiling AspAngular for .NETCoreApp,Version=v1.0
/home/andrew/workspace/CSharp/Linu
SP/AspAngular/project.json(7,54): error NU1002: The dependency Microsoft.AspNetCore.AngularServices 1.0.0-beta-000010 does not support framework .NETCoreApp,Version=v1.0.
/home/andrew/workspace/CSharp/Linu
SP/AspAngular/project.json(9,40): error NU1002: The dependency Microsoft.AspNetCore.Mvc 1.0.0 does not support framework .NETCoreApp,Version=v1.0.
/home/andrew/workspace/CSharp/Linu
SP/AspAngular/project.json(10,42): error NU1002: The dependency Microsoft.DotNet.Cli.Utils 1.0.0-preview2-003121 does not support framework .NETCoreApp,Version=v1.0.
/home/andrew/workspace/CSharp/Linu
SP/AspAngular/project.json(10,42): error NU1002: The dependency Microsoft.DotNet.ProjectModel.Loader 1.0.0-preview2-003121 does not support framework .NETCoreApp,Version=v1.0.
Compilation failed.
    0 Warning(s)
    4 Error(s)
Time elapsed 00:00:00.0785882

**Comment by MarkPieszak** [comment]
Do you have the latest .NET Core installed?
What template are you trying to run?

**Comment by AndrewKralovec** [comment]
dotnet version is 1.0.0-preview1-002702
yo aspnetcore-spa and i select Angular2

**Comment by MarkPieszak** [comment]
I believe you might have an outdated aspnet core version, not by a computer at the moment to verify though!

**Comment by xabikos** [comment]
The preview 1 is the RC2 tools version. You need to install the latest version of tools, preview 2 and give another try.

**Comment by SteveSandersonMS** [comment]
As per other comments - please update to 1.0.0 (RTM) version of dotnet core.

**Comment by AndrewKralovec** [comment]
I tried to install preview2, but no matter what my dotnet version says preview1, i even ran this [script](https://github.com/dotnet/cli/blob/rel/1.0.0/scripts/obtain/uninstall/dotnet-uninstall-debian-packages.sh) . Is there a way i can run it on preview1

**Comment by SteveSandersonMS** [comment]
Sorry, you do need the 1.0.0 (RTM) version of dotnet core, both for these libraries and many other up-to-date parts of dotnet core. I'm not sure why your attempt to update didn't succeed, but if it continues to give you trouble, I'd recommend describing the issue at https://github.com/dotnet/cli
