### ISSUE TITLE
Specifying the Node project directory with webpack dev middleware

### ISSUE THREAD

**Issue by mattwcole** [aspnet/JavaScriptServices#262]
I would like to be able to specify the Node project path when using webpack dev middleware to allow Javascript apps to be included from any location e.g.

```
Host/
  project.json
  Startup.cs
  Program.cs
App/
  package.json
  webpack.config.js
  src/
  node_modules/
```

At the moment it can't be changed from the content route. I've made what look like the necessary changes in [a fork] (https://github.com/mattwcole/JavaScriptServices/commit/bd69cb714f5985d1cb59e82d841d807d35787b4e), but ran into [another issue](https://github.com/aspnet/JavaScriptServices/issues/261) packaging the library before I could try it out. Happy to create a pull request if this is deemed useful enough.

**Comment by SteveSandersonMS** [comment]
This looks good to me!

It's now implemented (pretty much the same as in your fork). I'll publish updated NuGet packages soon.
