### ISSUE TITLE
Router 3.0.0-rc.1

### ISSUE THREAD

**Issue by doczoidberg** [aspnet/JavaScriptServices#263]
is there any reason why Router rc.1 is not supported? I changed `package.json` to `Router 3.0.0-rc.1` and it seems to work at least on my local machine in development mode.

But when publishing I get the errors:
```
ERROR in D:\temp\simulaton1\node_modules\@angular\router\src\router_module.d.ts
PUBLISH(9,10): Error TS2305: Module '"D:/temp/simulaton1/node_modules/@angular/core/index"' has no exported member 'ModuleWithProviders'.
ERROR in D:\temp\simulaton1\node_modules\@angular\router\src\router.d.ts
PUBLISH(14,39): Error TS2305: Module '"D:/temp/simulaton1/node_modules/@angular/core/index"' has no exported member 'NgModuleFactoryLoader'.
ERROR in D:\temp\simulaton1\node_modules\@angular\router\src\common_router_providers.d.ts
PUBLISH(9,55): Error TS2305: Module '"D:/temp/simulaton1/node_modules/@angular/core/index"' has no exported member 'NgModuleFactoryLoader'.
```

And when running on Azure I get the JS error:
`vendor.js?v=q8XzvTF_DTJOT7DL1Oy9K50isNCKoxrZNhoQGyG6uts:938 Uncaught Invalid provider - only instances of Provider and Type are allowed, got: [object Object]`

**Comment by doczoidberg** [comment]
after I tried the pusblish I now get the error:
`Invalid provider - only instances of Provider and Type are allowed, got: [object Object]`

**Comment by MarkPieszak** [comment]
I haven't ran into that issue, but from the looks of it there are still plenty of issues with the v3 router even in rc1 ([open issues](https://github.com/angular/angular/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20router%20rc1)). I'd maybe stick the previous beta version for now, maybe rc2 will fix whatever's going on!
