### ISSUE TITLE
webpack-dashboard?

### ISSUE THREAD

**Issue by asadsahi** [aspnet/JavaScriptServices#265]
Is there a way to get [webpack dashboard](https://github.com/FormidableLabs/webpack-dashboard) working with webpack-dev-middleware that asp.net core spa project is using?

I tried to use it, as per described on the webpack-dashbaord repository page, but nothing shows up in console. 

Would be really handy if we can see the output in dashboard console with bunch of other information which in normal output window isn't useful.

**Comment by MarkPieszak** [comment]
I can look into this if you'd like @SteveSandersonMS

**Comment by SteveSandersonMS** [comment]
@MarkPieszak Thanks - sounds good! Obviously this would only be useful if the log output is able to combine both the Webpack status info alongside the regular ASP.NET log output. Not sure if webpack dashboard really handles the case where you have other server-side code running, or if it's only intended for use on trivial static-file dev servers where you only have Webpack running.

**Comment by SteveSandersonMS** [comment]
I'll close this since it's somewhat tangential (not being directly a bug or feature in JavaScriptServices) but if anyone (e.g., @MarkPieszak) find a good webpack dashboard setup that is worth adding to the docs, please let us know!
