### ISSUE TITLE
Angular Universal with Firebase (AngularFire2)

### ISSUE THREAD

**Issue by doczoidberg** [aspnet/JavaScriptServices#268]
Not sure if I am right here but maybe someone can help me here? Crosspost from AngularFire2:

https://github.com/angular/angularfire2/issues/440

**Comment by MarkPieszak** [comment]
Hey Doc, research is still being done on integrating a Universal with AngularFire2 at the moment (https://github.com/angular/universal-starter/issues/127). I'll make sure to add he integration to our priority release for 1.0!

**Comment by SteveSandersonMS** [comment]
Thanks @MarkPieszak 

Closing as it's an external issue
