### ISSUE TITLE
JSPM support

### ISSUE THREAD

**Issue by alexkolt** [aspnet/JavaScriptServices#274]
I wonder if this is discussed. We plan to migrate to aspnetcore and currently our SPA applications use JSPM as package manager. Is the support for it coming or how would I go about creating middleware for it?

**Comment by SteveSandersonMS** [comment]
We don't have any specific plan for that, as there are many alternative build and packaging systems, and it would be unmanageable to try to support all combinations of them. I'd hope that it wouldn't be too hard for you to adapt the NPM+Webpack-based system provided here to do whatever you want to do with JSPM, and would be interested to hear if you discover anything we can change to make this more streamlined.

**Comment by nmocruz** [comment]
sorry to reply in a closed issue. But I just want to say that not everyone wants to use npm+webpack, maybe is just a flavor problem or resistance to use webpack, but it should be good to let people use/build alternatives.
