### ISSUE TITLE
EXCEPTION: TypeError: $(...).modal is not a function

### ISSUE THREAD

**Issue by doczoidberg** [aspnet/JavaScriptServices#278]
I want to open a bootstrap modal in my angular2 component. But I get the error:
`
EXCEPTION: TypeError: $(...).modal is not a function`

Also what is the right way to add a javascript library?

**Comment by MarkPieszak** [comment]
If you're trying to use Bootstrap, are you using https://github.com/valor-software/ng2-bootstrap ?
That one has no jQuery / etc. jQuery and other DOM manipulating libraries aren't able to work on the server-side, but you shouldn't have any problems with that one. Dmitriy did an incredible job with that one.

**Comment by doczoidberg** [comment]
tried it an gives the error:
`Error: Cannot find module "@angular/forms"`

it should work without typing and additional libs?
the javascript bootstrap is loaded.

**Comment by SteveSandersonMS** [comment]
In general, TypeScript (at present) only lets you reference modules where you have a corresponding .d.ts file, or at least declare the module as existing. Example:

```
declare module '@angular/forms' {
    export (whatever top-level thing you want, probably typed as 'any' if you don't want to give details)
}
```
