### ISSUE TITLE
Consider using Typings instead of TSD in templates

### ISSUE THREAD

**Issue by kavanshaban** [aspnet/JavaScriptServices#285]
Just have to say the templates work great out of the box.  However, as npm typings is now the preferred method to include definition files and also contains the newer versions of most libraries it would be great to utilize npm typing instead of the old TSD.

In addition, typings will detect if a definition file ships with the node module and it still has the ability to use the Definitely Typed repository if that's all that exists.

**Comment by MarkPieszak** [comment]
We're waiting for TypeScript to get out beta for 2.0 to use `@types` in PR #258, so it's coming soon :)
