### ISSUE TITLE
use ng2-boostrap

### ISSUE THREAD

**Issue by doczoidberg** [aspnet/JavaScriptServices#286]
I think ng2-bootstrap should be used as default. 

https://github.com/valor-software/ng2-bootstrap

**Comment by SteveSandersonMS** [comment]
Is it particularly difficult for people to set up in the Yeoman-generated projects? If so, would you be interested in sending a PR that adds documentation on how to add it to a project? If not, perhaps there's nothing else we need to do.

We can consider adding it to the default templates if people keep requesting it over time. Naturally we want to minimise dependencies until then!
