### ISSUE TITLE
Responsive to Client device to specific boot.ts 

### ISSUE THREAD

**Issue by wangkanai** [aspnet/JavaScriptServices#287]
Would SpaService support for `boot.mobile.ts` and `boot.desktop.ts` by responsing to specific access device? Im developing [ASP.NET Core Responsiveness](https://github.com/wangkanai/Responsiveness) and maybe thinking it would be possible to integrate this library together.

**Comment by SteveSandersonMS** [comment]
If you want to present different UIs depending on whether the client device is a desktop or mobile browser, that's more of a job for CSS (or potentially, your React/Angular/KO/etc view templates or  even some logic in your client-side component code). I don't think people would really want to have completely separate boot scripts depending on the client device (that would imply having completely separate client-side apps, which is hugely unnecessary). So I'll close this and suggest people use CSS/template/component code to vary the UX by device type.
