### ISSUE TITLE
PathTooLongException

### ISSUE THREAD

**Issue by dknaack** [aspnet/JavaScriptServices#288]
I cant run the ReactRedux template in Visual Studio 2015 because of the following exception. 

```
Error	MSB4018	The "FindConfigFiles" task failed unexpectedly.
System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.GetDirectoryName(String path)
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.EnumerateFiles(String path)
   at TypeScript.Tasks.FileHelpers.RecursiveGatherFiles(String directoryPath, String projectPath, Func`2 filter)
   at TypeScript.Tasks.FileHelpers.RecursiveGatherFiles(String directoryPath, String projectPath, Func`2 filter)
// ...
```

The reason is, off course, the long folder path and the limitation of windows.

How to deal with this? Is there something i can do without simply moving my project to another, shorter folder?

**Comment by MarkPieszak** [comment]
Unfortunately not much besides sharing a sunfolder, or using command line to assign a drive. 

What I'd recommend is storing your projects directly on C:, on my Windows machine everything is on C:\Git\ with relatively short project names, and I've never ran into the problem. Visual studio by default wants you to save projects in an already long location name (so many sunfolders), give this a shot and you'll be surprised you never see the problem again!

**Comment by dknaack** [comment]
Thanks! That worked great. Another short question, maybe you could help here too.
My project has multiple projects . Lets say.

+MyApp
   + XProj File
   + MyApp.Core
   + MyApp.Web (this is the Web Application) :)

My Problem is that if i select "MyApp.Web" as the start project. I get "error DOTNET1017: Project file does not exist 'C:\MyApp\project.json'.".

**Comment by MarkPieszak** [comment]
Was this already happening, or now after you moved it?
What if you do a **`dotnet restore`** on that root-level `C:\MyApp\` directory?

**Comment by dknaack** [comment]
This was happening before too. I was getting around this by opening only the project "MyApp.Web". But i want to open the solution to get debugging for the "MyApp.Core" too.

**Comment by MarkPieszak** [comment]
Is there a project.json at that root level?

**Comment by dknaack** [comment]
No, only the global.json.

**Comment by MarkPieszak** [comment]
Nevermind don't think it needs to, what about that second project, does it have one as well? You might need to dotnet restore on that project itself (if visual studio didn't restore the packages for you automatically). Just tried adding a separate NETCore Web API project to an existing default yeoman template and it ran fine, strange.

**Comment by dknaack** [comment]
Yes, thats really strange. I am doing aspnet mvc for about 10 years now, but i really have some problems with this templates. 

I will report back if i found something.

**Comment by SteveSandersonMS** [comment]
I'm not sure what particularly is going wrong in your scenario, but it sounds independent of anything in JavaScriptServices (it's a general question about debugging .NET core apps), so I'll close this. If you think there's something specific we can improve in the JavaScriptServices templates, please let us know!

**Comment by max-favilli** [comment]
Are you including react from cdn or installed via npm? Maybe you installed some other react  module from npm? Which version of npm are you using?
If you have installed react and modules via npm, and you have done so with the npm and you have not updated npm to version 3+ this is likely to occur due to many modules file names exceeding windows filename length limits.
If that is the scenario, just update npm to 3+, from version 3 npm use short file names.
Keep in mind visual studio 2015-update-3 is still bundled with npm 2.

**Comment by luisa123456** [comment]
Long path error is a very common problem in Windows users face. Try using Long Path Tool if your computer is giving errors like, “Path too long”, “Path too long – aborting (error code 80/1)”, 0x80010135 Path too long”, “Error cannot delete file: cannot read from source file or disk” or “File cannot be copied”. You can use Long Path Tool to resolve these problems. Get support of this product by subscribing it online.
