### ISSUE TITLE
Hot Module Replacement not working unless entry is main

### ISSUE THREAD

**Issue by sjaase** [aspnet/JavaScriptServices#289]
Exception is thrown in UseWebpackDevMiddleware() when enabling HMR and the webpack config file dosent contain an entry named "main".

**Comment by MarkPieszak** [comment]
It looks like there's a marker for this in the `aspnet-webpack` package actually, you're right.

```
// TODO: Stop assuming there's an entry point called 'main'
if (typeof webpackConfig.entry['main'] === 'string') {
    webpackConfig.entry['main'] = ['webpack-hot-middleware/client', webpackConfig.entry['main']];
}
```

And of course the webpack files (default) come with:

    entry: {
        main: ['./ClientApp/boot-client.ts'] // <--
    },

We might need to just dynamically look and see what entry is there, problem I see is if they have multiple entry points in an [] Array. @SteveSandersonMS

**Comment by hheexx** [comment]
So HMR is broken currently?

In my app I receive output in console:
[HMR] bundle rebuilding                                         main.js:720:23
[HMR] bundle rebuilt in 2900ms                              main.js:723:8
[HMR] Checking for updates on the server...           main.js:1606:23
[HMR] Updated modules:                                        main.js:1679:10
[HMR]  - ./ClientApp/styles/style.scss                      main.js:1681:12
[HMR]  - ./ClientApp/boot-client.ts                         main.js:1681:12
[HMR] App is up to date.                                         main.js:1686:10
Angular 2 is running in the development mode. Call enableProdMode() to enable the production mode.


But the content on the page does not change.

**Comment by MarkPieszak** [comment]
Do you have the default `main` entry? @hheexx 

```
entry: {
    main: ['./ClientApp/boot-client.ts'] // <--
},
```

**Comment by hheexx** [comment]
Yes I have.
I guess it's not this problem.
When I first read the thread I thought that file needs to be named main.ts

**Comment by SteveSandersonMS** [comment]
Fixed. To get the fix, update to the latest version of `aspnet-webpack` (version `1.0.11` or later).

**Comment by MarkPieszak** [comment]
What did you do to fix it? @SteveSandersonMS just curious!

**Comment by SteveSandersonMS** [comment]
See bc2de2ad598d90c29e19f1b585afbf074384a93c
