### ISSUE TITLE
In WebpackDevMiddleware, support array-style Webpack configs

### ISSUE THREAD

**Issue by SteveSandersonMS** [aspnet/JavaScriptServices#291]
As per comments in #132, Webpack itself allows multiple simultaneous configurations (the `webpack.config.js` file just needs to export an array of configs).

WebpackDevMiddleware should support it (just because there's no reason why not, as long as each config specifies a distinct `publicPath`). Need to have the JS code return an array of `publicPath` values to .NET rather than just a single one.

**Comment by tinchou** [comment]
I'm glad you took this even if nobody was explicitly requesting it :')
