### ISSUE TITLE
project failed to run when Visual Studio 2015 publish project to bin\Release\PublishedOutput (with fix 09e1cd3)

### ISSUE THREAD

**Issue by nklt** [aspnet/JavaScriptServices#293]
All sample applications as well as SPA template failed to compile and run, once Visual Studio builds and publish the application to bin\Release\PublishedOutput location within the project space.

This cause the Visual Studio .net core compile, and as well as dotnet tools, to give an erroneous error on typescript file.

Error TS2664 Invalid module name in augmentation, module '../../Observable' cannot be found. TypeScript Virtual Projects C:\workspace6\Angular2Spa\node_modules\rxjs\add\observable\combineLatest.d.ts 2 

This error is seen on every typescript file in the project.

It appear the TSC cannot comletely ignore the bin folder for some reason.
This bug occur, even after included the fix on tsdconfig.json to add bin as the filtered folder.

https://github.com/aspnet/JavaScriptServices/commit/09e1cd3b077aa505be73fdcd2f87658510e8cc34

The Angular2SPA project is tested on this release.

https://github.com/aspnet/JavaScriptServices/commit/03dcae24071968349b0eeeb8e03018cf562075f4

**Comment by SteveSandersonMS** [comment]
I'm afraid I wasn't able to repro this. Here's what I tried:

1. Installed the latest `generator-aspnetcore-spa` package
2. In an empty dir, ran `yo aspnetcore-spa` and made a new Angular 2 project
3. Opened the `.xproj` in VS
4. Did a ctrl+F5 to run the project and check it works
5. Used the Build->Publish UI in VS, telling it to publish to "File System". It went through the publishing process and put output in `.\bin\Release\PublishOutput`
6. I tried compiling again (ctrl+shift+b), expecting to get the error you mentioned, but no compiler error did occur
7. I tried publishing again, but again no error occurred

Is there something else I should do to reproduce the issue? Can you provide details?

I'll close this as 'no-repro' but if you can still reproduce the issue, please reopen with details!
