### ISSUE TITLE
Unable to run Angular 2 output out of the box...

### ISSUE THREAD

**Issue by dythim** [aspnet/JavaScriptServices#297]
I am unable to run the code created by the yoman template... I am uncertain about what to look at.

I get the following four errors saying that beta versions of some references do not support .NETCoreApp 1.0.  Is that expected?

> C:\Users\User\Documents\Visual Studio 2015\Projects\Angular2Test\project.json(7,54): error NU1002: The dependency Microsoft.AspNetCore.AngularServices 1.0.0-beta-000011 does not support framework .NETCoreApp,Version=v1.0.
> C:\Users\User\Documents\Visual Studio 2015\Projects\Angular2Test\project.json(9,40): error NU1002: The dependency Microsoft.AspNetCore.Mvc 1.0.0 does not support framework .NETCoreApp,Version=v1.0.
> C:\Users\User\Documents\Visual Studio 2015\Projects\Angular2Test\project.json(10,42): error NU1002: The dependency Microsoft.DotNet.Cli.Utils 1.0.0-preview2-003121 does not support framework .NETCoreApp,Version=v1.0.
> C:\Users\User\Documents\Visual Studio 2015\Projects\Angular2Test\project.json(10,42): error NU1002: The dependency Microsoft.DotNet.ProjectModel.Loader 1.0.0-preview2-003121 does not support framework .NETCoreApp,Version=v1.0.

The main page says the template should work on ".NET Core 1.0 RC2 or later on Windows".  I have npm 3.10.3, yoman 1.8.5 and ran the commands as specified.  This is a Windows 10 machine, with Visual Studio 2015 Update 3.

Any help would be appreciated. Thanks!

**Comment by SteveSandersonMS** [comment]
My apologies, the README file should have been updated to say you need .NET Core 1.0 RTM (since RTM shipped, we dropped support for RC2).

The error you're seeing suggests you're trying to run it inside RC2. Can you update and try again? The following instructions might be helpful: https://github.com/aspnet/Mvc/issues/4999
