### ISSUE TITLE
Integration with PrimeNg

### ISSUE THREAD

**Issue by nklt** [aspnet/JavaScriptServices#300]
I am trying integrate Angula2SPA with Prime NG (http://www.primefaces.org/primeng/#/setup).  Prime NG requires @angular/forms at 2,0.0-rc.6 but most of Angular 2.0 components are in 2.0.0-rc4 ( the version I downloaded).  Will there be plans to work on version that allow Prime NG to be installed together?

**Comment by SteveSandersonMS** [comment]
Yes, this is tracked as #257, which itself is waiting for Angular Universal itself to support RC6.
