### ISSUE TITLE
Cannot run samples according to documentation

### ISSUE THREAD

**Issue by jskulavik** [aspnet/JavaScriptServices#301]
Following the steps in the readme for building and running the samples produces `Project Microsoft.AspNetCore.NodeServices does not have a lock file. Please run "dotnet restore" to generate a new lock file.` each time.

**Comment by SteveSandersonMS** [comment]
Thanks for reporting that. I've fixed the instructions (basically you need to run `dotnet restore` from either the repo's root directory, or at least in its `src` directory, before you try to start any of the samples).

**Comment by jskulavik** [comment]
Thank you @SteveSandersonMS, this effort is absolutely fantastic and we look forward to it maturing
