### ISSUE TITLE
In templates, add option to generate unit tests

### ISSUE THREAD

**Issue by SteveSandersonMS** [aspnet/JavaScriptServices#304]
Original request was #87, with comments:

@on3al commented:
These templates are extremely helpful for getting started, but I'm at a loss how to fit unit testing into this workflow. Could someone please look into adding a working sample of a unit test using jasmine/karma? A jasmine test page in addition to the index page on the home controller that updates as changes occur during development would be great.

@laskoviymishka commented:
Good point, this issue related to #9.
A jasmine test page in controller IMHO is not quite good, it better to run your tests from CLI via something like karma. But option to add unit tests should be presented in yo generator definetely

**Comment by EduardTheThird** [comment]
Hi @SteveSandersonMS 

The karma-testing-example was extremely helpful in setting up unit tests, thank you.
This suggested workflow worked for us up until the move to TypeScript 2 and the move to the new TS types implementation.
 
Karma does start, however, Jasmine's definitions are not found, even though we added @types/jasmine and @types/karma-jasmine. Please could you provide some much needed guidance!

![karmaoutput](https://cloud.githubusercontent.com/assets/6488837/19152382/04630a98-8bd2-11e6-8694-b152d1491e91.PNG)

Screenshot of the package.json that was used:

![karmapackage](https://cloud.githubusercontent.com/assets/6488837/19152616/220da44e-8bd3-11e6-934a-231e33a3ae46.PNG)

**Comment by MarkPieszak** [comment]
@EduardTheThird Do you have `noResolve: false` in your karma.config.js?

**Comment by EduardTheThird** [comment]
Hi @MarkPieszak 

Thank you for the suggestion, I've added noResolve to karma.config.js and unfortunately, the same errors persisted.

Please find below the karma.config.js, it is the same as the karma-testing-example:

![karmaconf](https://cloud.githubusercontent.com/assets/6488837/19181010/727865f8-8c6a-11e6-9d6f-910cae9d47ef.PNG)

**Comment by SteveSandersonMS** [comment]
This is now implemented. If you get the latest `generator-aspnetcore-spa` generator, then when you create an Angular 2 project, it will ask if you want to include tests. If you say yes, then once the project is created, you can run `npm test` to start the Karma test runner.

**FEEDBACK REQUESTED** For anyone familiar with good unit test practices in Angular 2 (@MarkPieszak?), do the contents of `ClientApp/app/components/counter/counter.component.spec.ts` look good to you?

**Comment by MarkPieszak** [comment]
@SteveSandersonMS Let me take a look tomorrow morning and I'll get back to you!

**Comment by EduardTheThird** [comment]
I can confirm that this is working! Thank you @SteveSandersonMS 😸

**Comment by MarkPieszak** [comment]
@SteveSandersonMS Sorry for the delay, been swamped, but everything looks great from this end! TestBed is indeed the ideal way to test a Component in a more realistic environment. 👍 💯
