### ISSUE TITLE
CSS Modules and Post-CSS support

### ISSUE THREAD

**Issue by Spiralis** [aspnet/JavaScriptServices#305]
I am very interested in getting CSS modules working. I have become fond of the css modules solution in combination with React. I just moved from Meteor to finally (:smile:) getting a .Net backbone to work with. 

CSS Modules is becoming a very popular solution it seems, understandingly. I was also hoping to start benefitting from post-css features, such as autoprefixing.

But, I can't find out how to get css modules working. I have tried to make this work myself, but I keep getting import errors. Also, I see that there are two different ways to import data. I see that one has to use require instead of import if a variable is needed (like with CSS Modules). I found that I could use the <any> trick referred to here: http://stackoverflow.com/a/36107464/95008. But, I am getting an import error:
```
[node]  Error: Cannot find module './../../../../node_modules/css-loader/lib/css-base.js'
+ stack
```
Are there any solutions or workarounds for this? 

If not, what are the current roadmap plans in regards to supporting CSS Modules and/or Post-CSS?

Currently, CSS modules is the last thing holding me back from introducing this to my tech team, so that we can start converting of my old meteor project.

**Comment by SteveSandersonMS** [comment]
This error:

> Error: Cannot find module './../../../../node_modules/css-loader/lib/css-base.js'

... is what `css-loader` throws if you try to run it on the server (it doesn't support running on the server - it would be meaningless for it to do so, as there's no DOM there for it to inject the styles into).

So one easy solution is to move your imports into `boot-client.ts`, so they don't get executed on the server. Or, as a more drastic solution, you could disable server-side prerendering altogether if you don't really want it (just remove the `asp-prerender-*` tag helpers from `Index.cshtml`).

> what are the current roadmap plans in regards to supporting CSS Modules and/or Post-CSS?

More broadly, these templates are based on Webpack, so anything that's possible in a Webpack setup is also possible here. We don't have specific plans for PostCSS because it should work just like it does in any other Webpack-based setup. However, if you find ways of streamlining the experience of setting it up, please let us know. We could definitely add info to the docs if you find a particularly good PostCSS arrangement that others might not easily discover!

Hopefully this is a reasonable resolution, but if you think there are issues we need to fix, please reopen with details!

**Comment by Spiralis** [comment]
Thanks. I have disabled the server side rendering, as that is less important for me. But, I do want to keep the css files next to the react components, and I do want them to be imported according to what is becoming the de-facto standard. 

*In case someone else is on the same path as myself:*
To get the setup the way I wanted it I changed webpack.config.js to this:
```
var path = require('path');
var webpack = require('webpack');
var ExtractTextPlugin = require('extract-text-webpack-plugin');
var merge = require('extendify')({ isDeep: true, arrays: 'concat' });
var devConfig = require('./webpack.config.dev');
var prodConfig = require('./webpack.config.prod');
var isDevelopment = process.env.ASPNETCORE_ENVIRONMENT === 'Development';
var extractCSS = new ExtractTextPlugin('site.css');

module.exports = merge({
    resolve: {
        extensions: [ '', '.js', '.jsx', '.ts', '.tsx' ]
    },
    module: {
        loaders: [
            { test: /\.ts(x?)$/, include: /ClientApp/, loader: 'babel-loader' },
            { test: /\.ts(x?)$/, include: /ClientApp/, loader: 'ts-loader?silent=true' },
            { test: /site\.css/, include: path.resolve(__dirname, "ClientApp/css"), loader: extractCSS.extract(['css']) },
            { test: /\.css$/, exclude: path.resolve(__dirname, "ClientApp/css"), loaders: [ 'style?sourceMap', 'css?modules&importLoaders=1&localIdentName=[path]___[name]__[local]___[hash:base64:5]', 'postcss-loader' ] } 
        ]
    },
    entry: {
        main: ['./ClientApp/boot-client.tsx'],
    },
    output: {
        path: path.join(__dirname, 'wwwroot', 'dist'),
        filename: '[name].js',
        publicPath: '/dist/'
    },
    plugins: [
        extractCSS,
        new webpack.DllReferencePlugin({
            context: __dirname,
            manifest: require('./wwwroot/dist/vendor-manifest.json')
        })
    ]
}, isDevelopment ? devConfig : prodConfig);
```
As you can see that only means adding another loader for the CSS, plus still keeping the site.css handled separately (as before). I guess I'd have to do the same as is done for site.css for each global css added to this folder. But, that will probably limit itself to a reset.css stylesheet in my scenario. I might not even have a site.css at all, just a reset.css instead.

I also added `react-css-modules` as I like the approach on styling. Added post-css: `postcss-cssnext, postcss-focus, postcss-loader, postcss-reporter`.

The Home React component needed a little bit of changes to load CSS and to use `react-css-modules`. So, it currently looks like this:
```
import * as React from 'react';
import * as CSSModules from 'react-css-modules';
const CSSModulesDecorator = (CSSModules as any).default;
const styles = require<any>('./Home.css');

class Home extends React.Component<any, void> {
    public render() {
        return <div>
            <h1 styleName='home'>Hello, world!</h1>
            <p>Welcome to your new single-page application, built with:</p>
            <ul>
                <li><a href='https://get.asp.net/'>ASP.NET Core</a> and <a href='https://msdn.microsoft.com/en-us/library/67ef8sbd.aspx'>C#</a> for cross-platform server-side code</li>
                <li><a href='https://facebook.github.io/react/'>React</a>, <a href='http://redux.js.org'>Redux</a>, and <a href='http://www.typescriptlang.org/'>TypeScript</a> for client-side code</li>
                <li><a href='https://webpack.github.io/'>Webpack</a> for building and bundling client-side resources</li>
                <li><a href='http://getbootstrap.com/'>Bootstrap</a> for layout and styling</li>
            </ul>
            <p>To help you get started, we've also set up:</p>
            <ul>
                <li><strong>Client-side navigation</strong>. For example, click <em>Counter</em> then <em>Back</em> to return here.</li>
                <li><strong>Webpack dev middleware</strong>. In development mode, there's no need to run the <code>webpack</code> build tool. Your client-side resources are dynamically built on demand. Updates are available as soon as you modify any file.</li>
                <li><strong>Hot module replacement</strong>. In development mode, you don't even need to reload the page after making most changes. Within seconds of saving changes to files, rebuilt React components will be injected directly into your running application, preserving its live state.</li>
                <li><strong>Efficient production builds</strong>. In production mode, development-time features are disabled, and the <code>webpack</code> build tool produces minified static CSS and JavaScript files.</li>
                <li><strong>Server-side prerendering</strong>. To optimize startup time, your React application is first rendered on the server. The initial HTML and state is then transferred to the browser, where client-side code picks up where the server left off.</li>
            </ul>
        </div>;
    }
}

export default CSSModulesDecorator(Home, styles);
```
But, to get the imports going I needed to add a type definition for typescript for react-css-modules (thanks to @BeeZethttps://gist.github.com/BeeZet/24026f8130a0fdee7a9d83117023c695). I added that in the `typings/react-css-modules/react-css-modules.d.ts` file :
```
declare module 'react-css-modules' {
	interface Options {
		allowMultiple?: boolean;
		errorWhenNotFound?: boolean;
	}

	module Decorator {
		interface Props {
			styles?: any;
			styleName?: string;
		}
	}

	interface Decorator {
		(defaultStyles: any, options?: Options): any;
	}

	export const Decorator: Decorator;
}
```
 - and added a refenrece to that file in the `typings/tsd.d.ts` file:
```
/// <reference path="react/react.d.ts" />
/// <reference path="react-router/history.d.ts" />
/// <reference path="react-router/react-router.d.ts" />
/// <reference path="react/react-dom.d.ts" />
/// <reference path="whatwg-fetch/whatwg-fetch.d.ts" />
/// <reference path="react-redux/react-redux.d.ts" />
/// <reference path="react-router-redux/react-router-redux.d.ts" />
/// <reference path="redux-thunk/redux-thunk.d.ts" />
/// <reference path="redux/redux.d.ts" />
/// <reference path="source-map/source-map.d.ts" />
/// <reference path="uglify-js/uglify-js.d.ts" />
/// <reference path="webpack/webpack-env.d.ts" />
/// <reference path="react-css-modules/react-css-modules.d.ts" />
```
Another note is that I needed a somewhat quirky definition for the CSSModulesDecorator. Normally CSSModules is just composed over the class like this (in a non typescript file):
```
import React from 'react';
import CSSModules from 'react-css-modules';
import styles from './Home.css';

class Home extends React.Component<any, void> {
   ...
}
export default CSSModules(Home, styles)
``` 
But, the CSSModules import in typescript needed both the `import * as CSSModules` change as well as the additional `const CSSModulesDecorator = (CSSModules as any).default;` line. 
Finally, to avoid type-checking for the css import, I changed from 
`import * as styles from ('./Home.css')` 
to 
`const styles = require<any>('./Home.css');

It all now seems to work. I obviously also wish that SSR would work too. But, I have no idea how to get that working. Maybe someone can help on that?
