### ISSUE TITLE
WebpackDevMiddlewareOptions.ProjectPath no longer sets Node project path

### ISSUE THREAD

**Issue by mattwcole** [aspnet/JavaScriptServices#307]
The recent change to `WebpackDevMiddleware` [here](https://github.com/aspnet/JavaScriptServices/commit/f04fb8c42115d3816f9b8005dacefe7e6e485325#diff-cf4fed006c4f5ac483999ecf02221e0dL48) has removed the ability to set the Node project path for webpack dev middleware, breaking #262. While the project path is used to build the path to the webpack.config, node_modules is now expected in the content root.

**Comment by SteveSandersonMS** [comment]
Ah yes, sorry about that. Is the fix in d76b013 suitable for your needs?

**Comment by mattwcole** [comment]
That looks like it should do it - thanks for another speedy fix!
