### ISSUE TITLE
Update to ASP.NET Core 1.0.1

### ISSUE THREAD

**Issue by flightlevel** [aspnet/JavaScriptServices#309]
Update to ASP.NET Core 1.0.1
https://github.com/aspnet/Announcements/issues/203

**Comment by SteveSandersonMS** [comment]
Done :)

**Comment by fergalmoran** [comment]
Can't get this running on Ubuntu 16.04

`The specified framework 'Microsoft.NETCore.App', version '1.0.1' was not found.
  - Check application dependencies and target a framework version installed at:
      /usr/share/dotnet/shared/Microsoft.NETCore.App
  - The following versions are installed:
      1.0.0
  - Alternatively, install the framework version '1.0.1'.
[DotNetWatcher] fail: dotnet exit code: 131
[DotNetWatcher] info: Waiting for a file to change before restarting dotnet...
`
Great work by the way - just fricking great!

**Comment by MarkPieszak** [comment]
@fergalmoran Means you need to update your Core framework from 1.0 to 1.0.1.

**Comment by fergalmoran** [comment]
@MarkPieszak - I figured that but can't see how to do this on Ubuntu? Which package do I need to update?

**Comment by MarkPieszak** [comment]
Go to the .NET core download site it'll realize you're on Ubuntu and give you the instructions needed. It's basically the normal install process though!

**Comment by fergalmoran** [comment]
@MarkPieszak Yeah - that was the first thing I tried but it still gave me 1.0.0 - I even did a complete uninstall and reinstall but still 1.0.0. Even the instructions on the page say to 
`apt-get install dotnet-dev-1.0.0-preview2-003131`
