### ISSUE TITLE
When catching exceptions in node, attempt to find source map.

### ISSUE THREAD

**Issue by pauldotknopf** [aspnet/JavaScriptServices#310]
I use webpack to generate ```server.js```. If ```NodeServices``` catches an error from there, attempt to locate ```server.js.map``` and generate a stack trace from it.

This will help with debugging issues.

**Comment by pauldotknopf** [comment]
I found out how to back this directly into the generate webpack file!

http://jlongster.com/Backend-Apps-with-Webpack--Part-I

I essentially just added this into my ```webpack.config``` for my ```server.js``` file.

```js
module.exports = {
  ...
  plugins: [
    new webpack.BannerPlugin('require("source-map-support").install();', { raw: true, entryOnly: false })
  ],
  devtool: 'source-map'
};
```

Worked perfectly!

![image](https://cloud.githubusercontent.com/assets/523150/18499455/059f66e4-7a0d-11e6-9989-5031a60c320c.png)

**Comment by MarkPieszak** [comment]
This is great, definitely something worth adding !
