### ISSUE TITLE
Node environment variables on webpack dev middleware options

### ISSUE THREAD

**Issue by mattwcole** [aspnet/JavaScriptServices#311]
It could be useful to be able to set environment variables on `WebpackDevMiddlewareOptions`. E.g. currently there is no way to avoid NODE_ENV=production when the environment is anything other than "development". Example implementation [here](https://github.com/mattwcole/JavaScriptServices/commit/2f588dfd25462f797809e89e2a5da11f7e39009a) can be turned into a PR if desired.

**Comment by SteveSandersonMS** [comment]
Thanks for the suggestion. This is now implemented :)
