### ISSUE TITLE
[Proposal] Template for Aurelia Framework

### ISSUE THREAD

**Issue by ClaudioNunes** [aspnet/JavaScriptServices#313]
Now that:
- Aurelia Framework is final (1.0)
- Rob Eisenberg has joined MS

A Yeoman template using JavaScriptServices and Aurelia Framework would be very nice

**Comment by StephenRedd** [comment]
Yes please!

**Comment by SteveSandersonMS** [comment]
This has been under discussion for some time - totally happy to have such a template in here - we just need someone familiar enough with Aurelia to make the equivalent template (not just any Aurelia template, but specifically one that's as similar as possible to the other templates in this project). Anyone who feels they can do that, please submit a PR!

I know Rob has joined Microsoft, but he mentioned that his work on Aurelia remains separate, so I don't think it's going to be his responsibility to work on this.
