### ISSUE TITLE
SASS Support in templates

### ISSUE THREAD

**Issue by hheexx** [aspnet/JavaScriptServices#315]
SASS is standard now for modern web apps.

Why not add sass-loader to webpack config in templates?

**Comment by MarkPieszak** [comment]
In the documentation it's shown how to set it up with webpack it's actually real easy to add in there. I think Steve just didn't want it to be a default, as some people prefer Stylus, or Less, (or even regular css)

https://github.com/aspnet/JavaScriptServices/tree/dev/src/Microsoft.AspNetCore.SpaServices#example-a-simple-webpack-setup-that-builds-typescript

**Comment by hheexx** [comment]
Yea, I added it very easily to wabpack.
But I thought it should be in by default.

If you are interested I may submit pull request...

**Comment by asadsahi** [comment]
One of my project based on spa generator uses SCSS, if that helps:

https://github.com/asadsahi/AspNetCoreSpa

Just upgraded to Latest and greatest too (Typescript 2, Webpack 2, Angular 2 Final) :)

**Comment by SteveSandersonMS** [comment]
Thanks for the suggestion. As per @MarkPieszak's comment, I think this is covered by docs, and we are trying our best to minimise the out-of-the-box concept count, hence not putting this in by default.

It doesn't seem like there is any one de-facto standard way of handling styling these days (about as many people ask about SASS as LESS as PostCSS as SPA-framework-specific styling concerns), so it's tough to say one way is what everyone wants. But as always we'll keep listening to feedback, and if one particular setup becomes much more popular than alternatives, we'll certainly consider making it the template default.
