### ISSUE TITLE
Making it easier for unexperienced npm users

### ISSUE THREAD

**Issue by MJomaa** [aspnet/JavaScriptServices#316]
Hello,

maybe I'm not the only one who is coming from a pure .NET background, is unexperienced with npm and would like to start using it more with one of your templates. My suggestion would be to add a section at the bottom with some npm related notes.

**For example:**

- How to install npm
- My npm version is outdated. How do I upgrade it?
- How to update packages
- How to disable the progress bar (perf)
- I get connection errors? How can I set the npm registry to http? (perf)

**Comment by SteveSandersonMS** [comment]
Thanks for the suggestion! I'll monitor other feedback and we will certainly look into this if it becomes a common request.
