### ISSUE TITLE
Error: Cannot resolve module 'reflect-metadata'

### ISSUE THREAD

**Issue by MJomaa** [aspnet/JavaScriptServices#317]
I'm using the yeoman generator to scaffold a project with the angular template.
Seems like a module is missing. (Used in boot-client.ts)
Opening **package.json**, adding  **"reflect-metadata": "^0.1.8"**, running  **npm install** and then webpack  will fix the issue.

**Comment by SteveSandersonMS** [comment]
Thanks for reporting this.

It turns out that with the latest 3rd-party modules (e.g., Angular 2.0 final) we no longer need any explicit reference to `reflect-metadata`, so I've removed it from the current templates.
