### ISSUE TITLE
to-string loader depends on Node 4+

### ISSUE THREAD

**Issue by NorDroN** [aspnet/JavaScriptServices#330]
I've tried to create Angular2 application, but I've got some errors. I can't run webpack

![screenshot_6](https://cloud.githubusercontent.com/assets/5458276/18781577/0fce1626-818b-11e6-9fc3-7eff5ce3bfee.png)

I think it associated with this commit
https://github.com/aspnet/JavaScriptServices/commit/925f47fece9f075f1dd750fd203b3549c7979ae6

**Comment by SteveSandersonMS** [comment]
Apparently, in the last week, the `to-string` loader started strictly depending on Node 4+. I guess you must still be running Node 0.x.

For a quick solution, can you upgrade to a more current version of Node?

Longer term, I'll look at whether the `to-string` owner would be willing to restore 0.x compatibility (have reported [this issue](https://github.com/gajus/to-string-loader/issues/9)). If not, we'll have to replace `to-string` with something else.

**Comment by NorDroN** [comment]
Thanks, @SteveSandersonMS, you are right! I've just updated Node and I can build this project now.
