### ISSUE TITLE
Plans to have ES6 templates

### ISSUE THREAD

**Issue by tugberkugurlu** [aspnet/JavaScriptServices#334]
Are there any plans to have templates on ES6 along with TypeScript ones?

**Comment by antmdvs** [comment]
Hi! This was already discussed in #118, #117.

**Comment by SteveSandersonMS** [comment]
As per @antmdvs's comment, we don't have plans for that in the short term. It's important for us to keep the range of things we're maintaining and supporting manageable. Of course, you can make and distribute your own ES6 templates if you wish!

**Comment by thangchung** [comment]
@tugberkugurlu if you want to use ES6, please have a look on my repo (the quick ports for ES6) at https://github.com/thangchung/netcorelibs
