### ISSUE TITLE
Minor: Convert single quote strings to double quote ones in the templates

### ISSUE THREAD

**Issue by emzero** [aspnet/JavaScriptServices#343]
Following your own [Typescript coding standards](https://github.com/Microsoft/TypeScript/wiki/Coding-guidelines) strings should be double quoted. 

Opening a template project with VSCode with TSLint or any other editor with TSLint will underline every string present in the `.tsx` files as they are all single quoted.

**Comment by SteveSandersonMS** [comment]
Pull requests welcome!

**Comment by stephtr** [comment]
#360
I hope it is okay to also convert quotes in webpack.config.* files for consistency.

**Comment by SteveSandersonMS** [comment]
After further consideration, and [with reasons outlined here](https://github.com/aspnet/JavaScriptServices/pull/360#issuecomment-251687077), we're going to stick with `'` in the default templates for now. Obviously you can change it to whatever you want in your own projects!
