### ISSUE TITLE
Content security policy

### ISSUE THREAD

**Issue by MrCrimp** [aspnet/JavaScriptServices#345]
The following files where reported from content security policy checking
domain-task/fetch.js 

Inline eval() and functions() are not compliant with content security policy
`var isBrowser = (new Function('try { return this === window; } catch (e) { return false; }'))();`

This is how I'd do the same test

```
export const isNode = (typeof process === 'object' && Object.prototype.toString.call(process) === '[object process]');
export const isBrowser = !isNode && Object.prototype.toString.call(window) === '[object Window]';
```

**Comment by SteveSandersonMS** [comment]
Thanks for the suggestion. In the end I used the following test as it's quite succinct and explicit:

    const isNode = typeof process === 'object' && process.versions && !!process.versions.node;

If you think there's anything inadequate about that test, please let us know!
