### ISSUE TITLE
Move tsconfig.json files to template root folders

### ISSUE THREAD

**Issue by SteveSandersonMS** [aspnet/JavaScriptServices#346]
As per comments in #257, having the tsconfig.json files at non-root locations causes issues in TypeScript 2.0. Or at least people say so (I haven't hit any such issues myself) - it would be great to know for sure what the repro steps are.

If there really is a reliably reproducible problem with `tsconfig.json` in non-project-root locations, we'll need to move it back to project root.

Note: supposedly [this is fixed in TS 2.1 anyway](https://github.com/Microsoft/TypeScript/issues/3645), but we can't really wait for that.

**Comment by MarkPieszak** [comment]
I can take care of this one inside the TS2 upgrade PR #258 if you'd like @SteveSandersonMS

**Comment by SteveSandersonMS** [comment]
Don't worry - it was super trivial, so I just did it :)
