### ISSUE TITLE
Add ahead of time compilation (AOT) build using ngc and rollup

### ISSUE THREAD

**Issue by musabsudan** [aspnet/JavaScriptServices#350]
Do you have any plans to include it soon? what is the best way to add it to the current Angular template?

**Comment by tinchou** [comment]
Right now all efforts are put into integrating with Webpack, which will support tree-shaking (aka rollup aka harmony) in version 2.

I coincidentally spent my day trying to accomplish exactly what you asked. Upgrading to Webpack 2 was fairly easy (some info here: https://github.com/aspnet/JavaScriptServices/issues/318), but then the rest was just impossible for me.

This is the best post I found explaining how to do tree-shaking: http://blog.mgechev.com/2016/06/26/tree-shaking-angular2-production-build-rollup-javascript/

Even using `ngc` without tree-shaking would've required lots of effort in a custom build pipeline, which I wasn't ready to implement: I prefer to stick to the templates for now to make upgrading easier.

I think your best shot at the moment would be to have a pipeline exclusively for production builds, that doesn't use Webpack and is based on the solution proposed in the blog post I mentioned.

All that said, I'd love to see this project move in a direction that would allow us to have seamless AOT and tree-shaking :).

**Comment by SteveSandersonMS** [comment]
It would be great to have this in, but there isn't yet a clear standard way to make `ngc` and `webpack` work together well. A few people have tried making Webpack loaders that work with `ngc` but as of now, none of them seem complete or well supported.

I'm sure that `ngc` will get better Webpack support soon. One way or another, people will find a way to make this work, and we'll include it in the default template.

If someone can propose a clean and well-supported way to do this, please let us know! In the meantime, I'll close this as there's no action we can take on it.
