### ISSUE TITLE
webpack hmr react-router exception server-side in production mode

### ISSUE THREAD

**Issue by cveld** [aspnet/JavaScriptServices#354]
Steps to reproduce, following http://blog.stevensanderson.com/2016/05/02/angular2-react-knockout-apps-on-aspnet-core/
* `yo aspnetcore-spa`  (using version 0.3.4)
* Choose the React redux template
* `set ASPNETCORE_ENVIRONMENT=Production`
* `webpack --config webpack.config.vendor.js`
* `webpack`
* `dotnet run`
* Fetch http://localhost:5000 from a webbrowser

This will result in the following server-side exception:
```
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[0]
      An unhandled exception has occurred: Call to Node module failed with error: Error: The location '/__webpack_hmr' doesn't match any route configured in react-router.
at ClientApp\boot-server.js:1:802
```

How can I prevent this? Why is Webpack Hot Module Replacement kicking off in production mode - at least server-side?

**Comment by SteveSandersonMS** [comment]
I think you just have some other development-mode browser tab still running that's trying to connect to `/__webpack_hmr`. So it's nothing to do with your production app :)

If this turns out to be wrong and you can confirm the issue is something else, please reopen with details.
