### ISSUE TITLE
Loosing connection to webpack

### ISSUE THREAD

**Issue by rbasniak** [aspnet/JavaScriptServices#357]
Sorry for the title but I really don't know how to explain this in a few words.

I'm trying to find a situation where I can reproduce these two situations so I could post here but until now I couldn't. 

The bad thing is that they are happening very often with me. So this question is to see if anyone else is experiencing them and if there's any solution or workaround. 

1) Sometimes the application stops from loading and I start getting an error on Chrome console like this:
![image](https://cloud.githubusercontent.com/assets/10734059/19072872/09f0c06a-8a0e-11e6-95a7-23f6f8dbb199.png)

It seems that it cannot find the vendor bundles anymore. I try to rebuild them as many times as I can and the error persists. If I restart VS everything goes back to normal...

2) Sometimes it seems that the client bundle stops from compiling in the memory. I'm running the application then goes back do VS, do some changes and nothing happens on the browser. Iif I look in the Chrome console the HMR is compiling the changes, but they doesn't reflect on browser. 

Then I close the browser and run the application again in VS, but still the changes don't reflect in the browser. Then to be sure I go to Developer Tools, and find my source files and they are really unchanged. Any changes I do in the code (be in html, css or ts files) stops from being compiled. 

Again, restating VS fixes the problem.

It's really annoying because I'm having to restart VS like from 15 to 15 minutes...

I know this seems vague but it's just to see if anyone else is experiencing this or I'm getting crazy =( 

These are happening for many weeks now, but I waited to be 100% sure that I'm not messing anything because I know how odd the second situation sounds =)

I'll keep trying to reproduce this in a controlled environment...

**Comment by SteveSandersonMS** [comment]
Thanks for the report. In general, Visual Studio shouldn't be involved in anything that happens at runtime, so it's hard to see why restarting VS changes anything. Is it possible that you have some VS extension installed that interferes, for example by trying to auto-compile files or automatically runs Webpack? Try removing or disabling any extensions you have, in case this helps to identify the cause.

**Comment by rbasniak** [comment]
At first glance I don't have any Webpack related extension. Anyway I'll disable all my extensions and play around with the seed project to see if this still happens. I'll post an update tomorrow...

**Comment by rbasniak** [comment]
First situation is still happening from time to time when I rebuild the vendor files, but since this is something you don't have to do all the time it's not a big issue.

The second situation happened a couple of times yesterday, a lot less than the usual, but still happened. I'll re-enabled my extensions one by one to see if the rate changes.

I think you close this issue due the lack of information, but I'll keep trying to reproduce it and will post an update in case that happens.

**Comment by rbasniak** [comment]
I don't know how much sense this will have but I totally solved the problem uninstalling Augury extension in Chrome. 

The problems kept happening and I notice that something I faced an '"Cannot read property 'name' of undefined" exception on console inside vendor.js. I always thought it was something with my code, but then I noticed it was coming from a 'chromeextensions' domain or something. 

Since Augury is the only extension in chrome related to Angular 2, I uninstalled and both problems went away.

**Comment by SteveSandersonMS** [comment]
That's great to know. Thanks so much for tracking this down and letting us know what the resolution was. Now we'll know to warn people about that extension!

**Comment by MarkPieszak** [comment]
@rbasniak So Augury was causing this? That's strange, it shouldn't cause any additional errors hmm. I'll talk to some of the folks and Augury and see if they've seen this one before!

**Comment by rbasniak** [comment]
@MarkPieszak Yes I think so because I haven't had any single problem since the moment I uninstalled it. And they were happening very often, like 2 or 3 times per hour...

I won't be using Angular 2 this week, but next week I'll try to reinstall Augury and see if the problems are back so I can be 100% sure...
