### ISSUE TITLE
How to access params.data in react component or Redux store

### ISSUE THREAD

**Issue by Raika** [aspnet/JavaScriptServices#368]
is there a way to access params.data in react component or redux store?
or pass it through state from `<Provider>` to components or store?

**Comment by SteveSandersonMS** [comment]
You receive `params.data` in your `boot-server.ts`, and can pass it from there to the rest of your app in whatever way is most convenient for you. For example, in your `configureStore` method, you could use the `params.data` values as part of the store's initial state.
