### ISSUE TITLE
Angular 2 Docker exception

### ISSUE THREAD

**Issue by EduardTheThird** [aspnet/JavaScriptServices#373]
Hi

The included Docker file does compile to a Docker image and it can be added to a docker container, however, when browsing to the served Angular 2 app, the following exception occurs:

![docker](https://cloud.githubusercontent.com/assets/6488837/19273550/399f0186-8fcd-11e6-8c4c-9d0f7724f758.PNG)

We tested it with a newly generated, clean Angular 2 sample with no local changes. 
The test docker image is available from the Docker hub-> https://hub.docker.com/r/lightfleet/jssdocker/

Thanks! 🙈

**Comment by SteveSandersonMS** [comment]
Thanks for reporting this and for providing the convenient repro.

I've fixed the templates. You can fix the `Dockerfile` in your own project by changing it in the same way as this: https://github.com/aspnet/JavaScriptServices/commit/6a9b7accce7f93f51889e3a5896506f8410df41c
