### ISSUE TITLE
VSCode

### ISSUE THREAD

**Issue by doczoidberg** [aspnet/JavaScriptServices#374]
the project works fine in visual studio, but how do I run an ng2 application from VSCode? Is it possible to debug the typescript files? Can you give short description?

**Comment by boban984** [comment]
Can't you just Ctrl+P (for Chrome) find the file and set a break point?

Files should be in that webpack:// thingy (in memory, virtual, not really on disk) in the sources tab

**Comment by doczoidberg** [comment]
I mean debugging in VSCode, not in Chrome.

**Comment by marcelush** [comment]
have you tried  [vscode chrome debug](https://github.com/Microsoft/vscode-chrome-debug) extention?

**Comment by doczoidberg** [comment]
yes. I have this installed

**Comment by AndrewKralovec** [comment]
VSCode doesn’t support front end debugging, you need to use the chrome debug extension.

**Comment by SteveSandersonMS** [comment]
I've added some fairly extensive docs about debugging approaches here: https://github.com/aspnet/JavaScriptServices/tree/dev/src/Microsoft.AspNetCore.SpaServices#debugging-your-projects

In particular, there's a guide to setting up and using the VS Code debugger with these projects here: https://github.com/aspnet/JavaScriptServices/tree/dev/src/Microsoft.AspNetCore.SpaServices#using-visual-studio-codes-debugger-for-chrome-extension

**Comment by asadsahi** [comment]
@SteveSandersonMS unable to start debugging, getting this error after following the instructions above:

![image](https://cloud.githubusercontent.com/assets/3470892/21549254/e2a9cc44-cde8-11e6-8421-b88926c175b8.png)

**Launch.json settings**
```
 {
            "name": "Launch localhost:5000 with sourcemaps",
            "type": "chrome",
            "request": "launch",
            "url": "http://localhost:5000",
            "webRoot": "${workspaceRoot}/wwwroot",
            "sourceMaps": true
        },
```
Also, is it possible to launch Coreclr debugger through VScode first and then chrome debugger? Apparently, I can launch both, but whether I run .net core app from commandline or F5, chrome debugging doesn't succeed.

**Comment by asadsahi** [comment]
Sorry msised the part > close chrome.

After that chrome launches, but breakpoint doesn't turn on:
![image](https://cloud.githubusercontent.com/assets/3470892/21549811/c6638da0-cdec-11e6-931d-4401f4918e9d.png)

Any idea?
