### ISSUE TITLE
Add support for different css frameworks

### ISSUE THREAD

**Issue by AnderssonPeter** [aspnet/JavaScriptServices#375]
Add support for different css frameworks.
Some examples:
* Materialize-css, has a angular 2 module (https://www.npmjs.com/package/angular2-materialize)
* Pure-css
* Material design lite

**Comment by SteveSandersonMS** [comment]
The project templates here use Webpack, which itself already has great support for all mainstream CSS frameworks. We've written [some docs and examples here](https://github.com/aspnet/JavaScriptServices/tree/dev/src/Microsoft.AspNetCore.SpaServices#example-a-simple-webpack-setup-that-builds-less). Anything you can do with a Webpack-based build system, you can do here too, so in that sense we already have support.

For further information about other CSS frameworks, please see documentation for Webpack or those CSS frameworks themselves.

**Comment by AnderssonPeter** [comment]
@SteveSandersonMS Thanks, i managed to add `Materialize-css` to both my `webpack` config files.
But when i run the application i get a error that window does not exist? (my guess is that `Materialize-css` relies on it and it does not exist in the prerender stage in node? is there any polyfill i can add to my `boot-server.ts` to fix this issue?)

**Comment by SteveSandersonMS** [comment]
Unfortunately it sounds like `Materialize-css` isn't compatible with `angular2-universal`, so you won't be able to invoke its code during server-side prerendering.

To solve this, you can either disable server-side prerendering, or you can use some technique to avoid calling Materialize during server-side rendering (e.g., [these techniques](https://github.com/aspnet/JavaScriptServices/issues/377#issuecomment-254018503)). There won't be a nice easy quick solution - for a better long-term solution, work with the `Materialize-css` folks to improve the library so it's compatible with `angular2-universal`.

**Comment by AnderssonPeter** [comment]
Thanks ill post a issue for `Materialize-css`.
