### ISSUE TITLE
Exclude node_modules from the compile directories

### ISSUE THREAD

**Issue by gary-holland** [aspnet/JavaScriptServices#378]
I'm getting compile issues when packages (specifically the "protractor" package) loading into the node_modules directory have .aspx files within them.  Also, there is no need for the compiler to be scanning the node_modules directory for every rebuild.

Can you modify the project.json file to exclude this directory.  The following works for me:

  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true,
    "compile": {
      "exclude": [ "node_modules" ]
    }
  },

Thanks.

**Comment by SteveSandersonMS** [comment]
Thanks - great suggestion! This is now done.
