### ISSUE TITLE
TS 2.0: Update for redux-typed NPM package?

### ISSUE THREAD

**Issue by radu-porumb** [aspnet/JavaScriptServices#381]
When will you be able to push an update to the `redux-typed` NPM package? I've got just about everything up and running on TS 2.0 but this error `TS2314: Generic type 'Dispatch<S>' requires 1 type argument(s).` keeps popping up and I'd rather not resort to hacks to get around it when the fix is very simple and already done.

**Comment by stephtr** [comment]
Is already fixed (version 1.0.1).

**Comment by SteveSandersonMS** [comment]
Thanks for answering @stephtr. Also wanted to say I appreciated your thoroughness and preciseness when reviewing PR 362. I hope you'll remain involved in this project and welcome any suggestions you have for improving it!

**Comment by stephtr** [comment]
Somehow I overlooked that post...
Thank you and everyone else for that whole project!
As far as my knowledge and time allow I will try to help where I can.
