### ISSUE TITLE
guide to port existing samples

### ISSUE THREAD

**Issue by lucamorelli** [aspnet/JavaScriptServices#382]
Hi, I'm trying to create a few angular 2 and aurelia templates using webpack and I would like to use these packages, but since I'm starting from existing samples that have a complete pipeline of scripts to run the app with webpack dev server, I have a few problem understanding how to adapt them to work fine this way.
Is there any documentation about how to adapt existing samples and make them work fine with vs?

**Comment by lucamorelli** [comment]
I'm trying to add the code from the samples created from the yo generator but I have a few problems: looks like is not listening file changes. Could be a problem use framewrok 4.6.1 instead of net core?

**Comment by MarkPieszak** [comment]
Yes, these samples were created for .NET Core. I'm sure some things could be ported over but the wiring of webpack with .NET for example, that's specific to Core.

**Comment by lucamorelli** [comment]
hmm ... yes, I changed the framework in the sample in fx 4.6.1, and from iis express to kestrel. The sample is working anyway, but my project not. How can I fix the problem? I tried to apply to the changes found in the sample but doesn't update when I change something.

**Comment by SteveSandersonMS** [comment]
> The sample is working anyway, but my project not. How can I fix the problem?

I'm afraid you'd have to be a lot more specific than saying it's "not working" :)

As for your original question, there are docs about the NodeServices/SpaServices technologies [here](https://github.com/aspnet/JavaScriptServices/blob/dev/src/Microsoft.AspNetCore.NodeServices/README.md) and [here](https://github.com/aspnet/JavaScriptServices/tree/dev/src/Microsoft.AspNetCore.SpaServices). If you find gaps in the docs then please let us know what specific other things you think we should cover.

If you want to apply them in a different project setup, that's absolutely great and should certainly be possible, but you will of course have to investigate and find solutions for any setup issues you encounter. Hope that's OK!

**Comment by lucamorelli** [comment]
I'have just added this project to the solution here https://github.com/lucamorelli/CoreTemplates, the project is Angular.WebPack.
Since both the frameworks support webpack I would like to create the webpack version of these projects as templates.
Looks like the problem is rebuild is not triggered when I save a file, sometimes I see null reference errors in the debug window, or something is triggered just when I modify the entry file: I did a lot of changes but I haven't found a way to make it work

**Comment by lucamorelli** [comment]
this is the log of the working sample

Microsoft.AspNetCore.NodeServices: Information: Node will restart because file changed: D:\temp\js\ClientApp\app\components\home\home.component.ts
Microsoft.AspNetCore.NodeServices: Information: webpack building...
Microsoft.AspNetCore.NodeServices: Information: webpack built 2015d691a1aa6397bbdd in 2933ms
Microsoft.AspNetCore.Hosting.Internal.WebHost: Information: Request starting HTTP/1.1 GET http://localhost:5000/dist/55311a06a668e6227487.hot-update.json  
Microsoft.AspNetCore.Hosting.Internal.WebHost: Information: Request finished in 11.0925ms 200 application/json; charset=UTF-8
Microsoft.AspNetCore.Hosting.Internal.WebHost: Information: Request starting HTTP/1.1 GET http://localhost:5000/dist/0.55311a06a668e6227487.hot-update.js  
Microsoft.AspNetCore.Hosting.Internal.WebHost: Information: Request finished in 9.2677ms 200 application/javascript; charset=UTF-8

looks like that after the node restart webpack doesn't rebuild the program. which could be the problem?

**Comment by SteveSanderson** [comment]
> after the node restart webpack doesn't rebuild the program

It's not supposed to - it rebuilds lazily (only when a new request for a compiled file goes to the Webpack dev middleware).

**Comment by lucamorelli** [comment]
ok, I'm trying to understand why in the template after the message "Node will be restarted..." I see webpack rebuild it and the web page is update, and in my sample not. I don't see differences in the code and configuration
