### ISSUE TITLE
Why not add watermark function

### ISSUE THREAD

**Issue by qibucloud** [aspnet/JavaScriptServices#383]
JavaScriptServices/samples/misc/NodeServicesExamples/Node/resizeImage.js
Why not add watermark function

**Comment by SteveSandersonMS** [comment]
You can certainly do that if you want to in your own code!

As for the code in this repo, `resizeImage.js` is just a small sample to demonstrate integrating .NET code with Node code, so I don't think it would benefit people to add extra features. Hope that's OK!
