### ISSUE TITLE
Angular2 generator does not install typings ?

### ISSUE THREAD

**Issue by tebeco** [aspnet/JavaScriptServices#385]
Hi, i'm new to front dev but from what I can read here :
https://angular.io/docs/ts/latest/quickstart.html

Should the angular2 template reference typings in packages.json ?
It seems to cause issue to Vs2015.3
For example : require from Node is marked in red (eg : require('somefile.html') )
The mouseOver seem to understand that it comes from node but nothing more

It may comes from R# too but still i'm looking to fix squiggle as possible ;)

i've try to add Typing to my solution by adding the following line to packages.json :

  "scripts": {
    "postinstall": "typings install",
    "tsc": "tsc",
    "tsc:w": "tsc -w",
    "typings": "typings"
  },
  "dependencies": {
    "typings": "^1.4.0",
}

But now it tries to cast everything as "Any" , rofl
Any idea ?

**Comment by MarkPieszak** [comment]
I believe Resharper may be causing those errors I'd suggest disabling/uninstalling that extension. I've heard that's helped others!

If you are using the latest template, it has TypeScript2, which deprecated tsd and typings. It instead uses `@types`. If in visual studio you are getting this area, you need to make sure you have the latest visual studio updates, and that it is using TS 2 itself. (You can make sure also by going to even package manager console and typing tsc --v.

Even with resharper gone, vstudio can sometimes still throw ts errors about require and Promise, so I'd suggest updating it to 2.0.3 in your package json, as well as downloading the VStudio update in the extensions marketplace for Typescript 2.0.3. This made the issue go away on some machines I've tested on. Hope that helps!

**Comment by tebeco** [comment]
So I removed the "script" block and the "typings 1.4.0 " (right ?)
Typescript vsix 2.0.3 was installed, and I just updated all angular package to 2.0.3 as said

> If in visual studio you are getting this area, you need to make sure you have the latest visual studio updates, and that it is using TS 2 itself. (You can make sure also by going to even package manager console and typing tsc --v.

I'm not sure what you mean (as i said i'm trying to make my debut in front dev so i'm not sure to get it
also i did not understand if I should run or not `typing tsc -v` :)

**Comment by MarkPieszak** [comment]
Are you working off the latest template?
Do you have @types/node in your dependencies like in the template? 

Also types : ['node'] in your tsconfig? All of these would be in the latest template from yeoman as well!

Restarting vstudio and such should make all those go away especially after installing 2.0.3 if you get the latest template.

**Comment by tebeco** [comment]
As i said, i just "updated" this Yeoman generator and ran it nothing else.
I don't think i have the knowledge in angular or typescript to make the PullRequest  but that's where I wanted to go, to have all of this simply after :

>yo aspnetcore-spa
>npm install

**Comment by MarkPieszak** [comment]
Is it working now without errors?

**Comment by SteveSandersonMS** [comment]
> require from Node is marked in red

This happens in VS if you've got an old version of TypeScript installed. Make sure you install [TypeScript 2.0 for Visual Studio](https://blogs.msdn.microsoft.com/typescript/2016/09/22/announcing-typescript-2-0/).

(For anyone who isn't using Visual Studio, you don't need to install this or anything similar.)

**Comment by tebeco** [comment]
@SteveSandersonMS Typescript extension is up to date :)

So this leads to the next question, does this template install `@types` if `tsd` and `typings` are deprecated ?

**Comment by SteveSandersonMS** [comment]
@types is a feature of TypeScript 2. It's not something that you install separately.
