### ISSUE TITLE
VueJS compatibility

### ISSUE THREAD

**Issue by alexsandro-xpt** [aspnet/JavaScriptServices#389]
There are some plan to support VueJS?

**Comment by SteveSandersonMS** [comment]
Not at the moment, but we'll keep a lookout for how often this gets requested, and possibly do so if it grows significantly in popularity.

There are only so many different frameworks we have capacity to maintain templates for :)

**Comment by alexsandro-xpt** [comment]
https://github.com/aspnet/Docs/issues/2856
