### ISSUE TITLE
Change AngularSPA to use services

### ISSUE THREAD

**Issue by brentos99** [aspnet/JavaScriptServices#391]
I would like to update the AngularSPA template so that the fetchdata component uses services instead of embedding http object

**Comment by SteveSandersonMS** [comment]
Thanks for the suggestion @brentos99. You're certainly welcome to submit a pull request!

Whether or not we pull it into the core templates depends on whether we think it will make things better for new developers. If it's simpler and clearer in your suggested way that's great. However if it's more abstraction and/or more files, it might not be the ideal fit for a getting-started template.

I'll mark this closed and look out for your pull request. Thanks!
