### ISSUE TITLE
Deployment to Azure Webapp

### ISSUE THREAD

**Issue by BentleyDavis** [aspnet/JavaScriptServices#392]
I have tried several different ways to deploy my app to azure but it has not worked. To test, I followed your base instructions and loaded the unmodified code to Github and set up deployment from GitHub. All I get is the "Error. An error occurred while processing your request." and I can't get more info. 

Source:
https://github.com/BentleyDavis/CoreAngular2Default

Deployed:
 http://coreangular2default.azurewebsites.net/

Any assistance would be appreciated.

**Comment by SteveSandersonMS** [comment]
Please get hold of the detailed error logs (e.g., using [this approach](https://azure.microsoft.com/en-gb/documentation/articles/web-sites-dotnet-troubleshoot-visual-studio/) or [maybe this one if it's not out-of-date](http://stackoverflow.com/questions/29518365/how-to-get-error-details-of-an-asp-net-5-app-deployed-on-azure-websites)) so you can see what went wrong.

When you find the error message, if you think it's a problem in the template or libraries, please reopen this issue with details! Thanks.

BTW Just in case you didn't, be sure to set Azure to use a recent version of Node (e.g., as described in [this blog post](http://blog.stevensanderson.com/2016/10/04/angular2-template-for-visual-studio/)). It uses an old version by default that doesn't work.

**Comment by BentleyDavis** [comment]
Thank you, I re-did everything based on the blog post you added (I was working off of http://blog.stevensanderson.com/2016/05/02/angular2-react-knockout-apps-on-aspnet-core/ which didn't have any deploy instructions) It gave me the same error so I started to get the logs and it started working. I'm sure it said deployed. Maybe the initial run had a timeout. I do have it on shared at the moment. I'll let you know if I get any more info in case it is helpful. I am up and running for now.

**Comment by SteveSandersonMS** [comment]
Glad it works!
