### ISSUE TITLE
Redux-typed typescript errors

### ISSUE THREAD

**Issue by ericj17** [aspnet/JavaScriptServices#395]
Hi There,

I'm not sure how I managed to get into this state where I am running into the following typescript errors within redux-typed.
I've also included my package.json and tsd.json below. Would you happen to know what the issue is off the top of your head?
Let me know if you need any further details.

Thanks so much for this template and support!
Eric

>     ERROR in C:\Users\x\Source\Repos\epas-ui-client\node_modules\redux-typed\StrongProvide.d.ts                                                                                    
>     (1,1): error TS1084: Invalid 'reference' directive syntax.                                                                                                                            
>                                                                                                                                                                                           
>     ERROR in C:\Users\x\Source\Repos\epas-ui-client\node_modules\redux-typed\StrongProvide.d.ts                                                                                    
>     (9,14): error TS1005: '=' expected.                                                                                                                                                   
>                                                                                                                                                                                           
>     ERROR in C:\Users\x\Source\Repos\epas-ui-client\node_modules\redux-typed\StrongProvide.d.ts                                                                                    
>     (9,22): error TS1005: ';' expected.                                                                                                                                                   
>                                                                                                                                                                                           
>     ERROR in C:\Users\x\Source\Repos\epas-ui-client\node_modules\redux-typed\StrongProvide.d.ts                                                                                    
>     (9,34): error TS1005: '=' expected.                                                                                                                                                   
>                                                                                                                                                                                           
>     ERROR in C:\Users\x\Source\Repos\epas-ui-client\node_modules\redux-typed\StrongProvide.d.ts                                                                                    
>     (9,14): error TS2304: Cannot find name 'allProps'.                                                                                                                                    
>                                                                                                                                                                                           
>     ERROR in C:\Users\x\Source\Repos\epas-ui-client\node_modules\redux-typed\StrongProvide.d.ts                                                                                    
>     (9,36): error TS2304: Cannot find name 'TActions'.                                                                                                                                    
>                                                                                                                                                                                           
>     ERROR in C:\Users\x\Source\Repos\epas-ui-client\node_modules\redux-typed\StrongProvide.d.ts                                                                                    
>     (9,47): error TS2304: Cannot find name 'TExternalProps'.                                                                                                                              
>                                                                                                                                                                                           
>     ERROR in C:\Users\x\Source\Repos\epas-ui-client\node_modules\redux-typed\StrongActions.d.ts                                                                                    
>     (1,1): error TS1084: Invalid 'reference' directive syntax.                                                                                                                            
>                                                                                                                                                                                           
>     ERROR in C:\Users\x\Source\Repos\epas-ui-client\node_modules\redux-typed\StrongActions.d.ts                                                                                    
>     (18,16): error TS2315: Type 'Dispatch' is not generic.   

**package.json**
```
{
  "name": "client",
  "version": "0.0.0",
  "dependencies": {
    "aspnet-prerendering": "^1.0.2",
    "aspnet-webpack": "^1.0.6",
    "aspnet-webpack-react": "^1.0.2",
    "babel-core": "^6.5.2",
    "babel-loader": "^6.2.3",
    "babel-preset-es2015": "^6.5.0",
    "babel-preset-react": "^6.5.0",
    "bootstrap": "^3.3.6",
    "css-loader": "^0.23.1",
    "domain-task": "^2.0.0",
    "event-source-polyfill": "^0.0.7",
    "extract-text-webpack-plugin": "^1.0.1",
    "file-loader": "^0.8.5",
    "jquery": "^2.2.1",
    "react": "^15.0.1",
    "react-dom": "^15.0.1",
    "react-redux": "^4.4.4",
    "react-router": "^2.1.1",
    "react-router-redux": "^4.0.2",
    "redux": "^3.4.0",
    "redux-thunk": "^2.0.1",
    "redux-typed": "^1.0.0",
    "style-loader": "^0.13.0",
    "ts-loader": "^0.8.1",
    "typescript": "^1.8.2",
    "url-loader": "^0.5.7",
    "webpack": "^1.12.14",
    "webpack-node-externals": "^1.4.3",
    "webpack-hot-middleware": "^2.10.0",
    "webpack-merge": "^0.14.1"
  }
}
```

**tsd.json**
```
{
  "version": "v4",
  "repo": "borisyankov/DefinitelyTyped",
  "ref": "master",
  "path": "typings",
  "bundle": "typings/tsd.d.ts",
  "installed": {
    "react/react.d.ts": {
      "commit": "9f0f926a12026287b5a4a229e5672c01e7549313"
    },
    "react-router/react-router.d.ts": {
      "commit": "9f0f926a12026287b5a4a229e5672c01e7549313"
    },
    "react/react-dom.d.ts": {
      "commit": "dade4414712ce84e3c63393f1aae407e9e7e6af7"
    },
    "react-router/history.d.ts": {
      "commit": "9f0f926a12026287b5a4a229e5672c01e7549313"
    },
    "whatwg-fetch/whatwg-fetch.d.ts": {
      "commit": "dade4414712ce84e3c63393f1aae407e9e7e6af7"
    },
    "react-redux/react-redux.d.ts": {
      "commit": "9f0f926a12026287b5a4a229e5672c01e7549313"
    },
    "redux/redux.d.ts": {
      "commit": "9f0f926a12026287b5a4a229e5672c01e7549313"
    },
    "react-router-redux/react-router-redux.d.ts": {
      "commit": "9f0f926a12026287b5a4a229e5672c01e7549313"
    },
    "redux-thunk/redux-thunk.d.ts": {
      "commit": "9f0f926a12026287b5a4a229e5672c01e7549313"
    },
    "uglify-js/uglify-js.d.ts": {
      "commit": "9f0f926a12026287b5a4a229e5672c01e7549313"
    },
    "source-map/source-map.d.ts": {
      "commit": "9f0f926a12026287b5a4a229e5672c01e7549313"
    },
    "webpack/webpack-env.d.ts": {
      "commit": "9f0f926a12026287b5a4a229e5672c01e7549313"
    }
  }
}
```

**Comment by SteveSandersonMS** [comment]
Thanks for reporting this!

It turns out that the latest update to `redux-typed` made it take a dependency on the TypeScript 2.0 compiler. That's because it was generated by the TS 2.0 compiler, so its `.d.ts` files used the `/// <reference types="react" />` syntax, and the TS 1.x compiler doesn't understand that and throws the errors you've posted. This is a bit of a surprise but there is an easy solution.

I've now published two new versions of `redux-typed`:

 * `1.0.2` restores compatibility with the TS 1.x compiler
 * `2.0.0` represents the breaking change of taking a dependency on TS 2.x

@ericj17: You can fix your project now just by updating `redux-typed` to version `1.0.2` (e.g., in your `package.json`, change the version specifier to `^1.0.2` and then re-run `npm install`). Because of how the `^version` specifier works, you'll only get the latest `1.x` version.

For anyone who's using the more recent templates that use TypeScript 2, you may need to update your `redux-typed` dependency to `^2.0.0` to restore compatibility with the TS 2.x compiler.

I've updated the `generator-aspnetcore-spa` package so that `ReactReduxSpa` uses the `2.0.0` version by default.

@ericj17 Sorry for the inconvenience - hope this fix sorts things out for you. Please let me know if not!
