### ISSUE TITLE
ReactRedux template fails to build properly and results in client-side errors

### ISSUE THREAD

**Issue by DamianReeves** [aspnet/JavaScriptServices#396]
If you execute the yeoman template and choose the ReactRedux option you end up with something which fails to work out the box, Typescript errors ensue immediately.

**Comment by SteveSandersonMS** [comment]
Can you let me know what version of `generator-aspnetcore-spa` you're using?

The latest version (0.3.8) appears to work fine when I installed and tried it. If you need to upgrade, just run `npm install -g generator-aspnetcore-spa` again.

**Comment by DamianReeves** [comment]
Apparently I had 0.3.6 (I thought I had updated to the latest).
I tested 0.3.8 and it works. Sorry, I tried this multiple times on 2 machines and got the same errors each time.

But 0.3.8 looks good.
