### ISSUE TITLE
KO template installation failed

### ISSUE THREAD

**Issue by sad1y** [aspnet/JavaScriptServices#397]
Hi, I have an issue when trying to generate an KO template:

Version: webpack 1.13.2
Time: 1855ms
                               Asset    Size  Chunks             Chunk Names
89889688147bd7575d6327160d64e760.svg  109 kB          [emitted]
                           vendor.js  970 kB       0  [emitted]  vendor
                          vendor.css  315 kB       0  [emitted]  vendor
   [0] dll vendor 12 bytes {0} [built]
    + 71 hidden modules
Child extract-text-webpack-plugin:
        + 7 hidden modules
Hash: 74784594e1014c1c8b45
Version: webpack 1.13.2
Time: 1375ms
      Asset     Size  Chunks             Chunk Names
    main.js  25.7 kB       0  [emitted]  main
     1.1.js  2.27 kB       1  [emitted]
     2.2.js     1 kB       2  [emitted]
     3.3.js  1.68 kB       3  [emitted]
main.js.map  36.3 kB       0  [emitted]  main
 1.1.js.map  2.55 kB       1  [emitted]
 2.2.js.map  1.45 kB       2  [emitted]
 3.3.js.map  2.65 kB       3  [emitted]
    + 26 hidden modules

ERROR in ./ClientApp/router.ts
(18,26): error TS2503: Cannot find namespace 'History'.

ERROR in ./ClientApp/components/nav-menu/nav-menu.ts
(19,57): error TS2304: Cannot find name 'require'.

ERROR in ./~/ts-loader?{"silent":true}!./ClientApp/components/home-page/home-page.ts
(6,58): error TS2304: Cannot find name 'require'.

ERROR in ./~/bundle-loader?lazy!./ClientApp/components/home-page/home-page.ts
(6,58): error TS2304: Cannot find name 'require'.

ERROR in ./~/ts-loader?{"silent":true}!./ClientApp/components/fetch-data/fetch-data.ts
(15,9): error TS2304: Cannot find name 'fetch'.

ERROR in ./~/ts-loader?{"silent":true}!./ClientApp/components/fetch-data/fetch-data.ts
(23,59): error TS2304: Cannot find name 'require'.

ERROR in ./~/bundle-loader?lazy!./ClientApp/components/fetch-data/fetch-data.ts
(15,9): error TS2304: Cannot find name 'fetch'.

ERROR in ./~/bundle-loader?lazy!./ClientApp/components/fetch-data/fetch-data.ts
(23,59): error TS2304: Cannot find name 'require'.

ERROR in ./~/ts-loader?{"silent":true}!./ClientApp/components/counter-example/counter-example.ts
(12,64): error TS2304: Cannot find name 'require'.

ERROR in ./~/bundle-loader?lazy!./ClientApp/components/counter-example/counter-example.ts
(12,64): error TS2304: Cannot find name 'require'.

ERROR in ./ClientApp/components/app-root/app-root.ts
(16,36): error TS2503: Cannot find namespace 'History'.

ERROR in ./ClientApp/components/app-root/app-root.ts
(26,45): error TS2304: Cannot find name 'require'.

ERROR in ./ClientApp/components/app-root/app-root.ts
(27,51): error TS2304: Cannot find name 'require'.

ERROR in ./ClientApp/components/app-root/app-root.ts
(28,46): error TS2304: Cannot find name 'require'.

ERROR in ./ClientApp/components/app-root/app-root.ts
(43,57): error TS2304: Cannot find name 'require'.

ERROR in ./ClientApp/boot.ts
(5,23): error TS2304: Cannot find name 'require'.

**Comment by SteveSandersonMS** [comment]
Thanks for reporting this! It's now fixed in the latest version of `generator-aspnetcore-spa` (version 0.3.10). To upgrade, run `npm install -g generator-aspnetcore-spa`.

**Comment by jcramer** [comment]
Getting typing errors in app-root.ts and router.ts, I think they are missing `import * as History from 'history'`

**Comment by SteveSandersonMS** [comment]
@jcramer Thanks - should now be fixed as of `generator-aspnetcore-spa` version 0.4.2.
