### ISSUE TITLE
    TypeScriptCompileBlocked

### ISSUE THREAD

**Issue by lucamorelli** [aspnet/JavaScriptServices#399]
please, I suggest a small update in the documentation on how to add hot module reload in a existing project.
To make it work with the ts loader like in your sample I found that I have to add this 
`<TypeScriptCompileBlocked>true</TypeScriptCompileBlocked>`
to the project file.

If you don't do this, ts compiles to a js file, and webpack look at first the js compiled file, see that is not changed and doesn't trigger the reload.

you have 2 solutions:
1. add that to the project.
2. and compileOnSave to the tsconfig, this way that js file is updated and webpack reload the changed files.

This thing has made me mad for a week.

**Comment by lucamorelli** [comment]
btw: if it's of interest now that I solved this problem and using the aurelia sample in the pull request I realized a couple of templates using angular 2 and aurelia with jwt authentication. 
I'm used to write backoffice procedures, and I don't find a project template without authentication very useful.

**Comment by SteveSandersonMS** [comment]
Done. Thanks for the suggestion!
