### ISSUE TITLE
Live updating for angular2 spa...

### ISSUE THREAD

**Issue by levarcooper** [aspnet/JavaScriptServices#400]
I probably missed something... when viewing the test Angular site (Music Store) using "dotnet run", the changes made do not update until I run gulp. Is there a way to allow live updating or enable a watcher?

**Comment by SteveSandersonMS** [comment]
The Angular 2 Music Store sample is a bit behind the times and doesn't use Webpack. As such, it doesn't feature Hot Module Replacement. For a better example of setting this up, please see the Angular2Spa template, which is what we recommend people actually base real projects on.
