### ISSUE TITLE
"React with Redux": tsc error

### ISSUE THREAD

**Issue by nZeus** [aspnet/JavaScriptServices#401]
Hi, I'm trying to do a fresh installation according to the documentation.

First I run `npm install -g yo generator-aspnetcore-spa`. It works fine. 
Then I run `yo aspnetcore-spa`, select "React with Redux" and I get the following error:

![image](https://cloud.githubusercontent.com/assets/2727326/19628354/fd802700-995b-11e6-8944-c2f8426b28b2.png)

Version of typescript is 2.1.0-dev.20161016

**Comment by SteveSandersonMS** [comment]
Hi @nZeus. Are you sure you're running the latest `generator-aspnetcore-spa`? Is it possible that you are installing older versions of NPM modules somehow, perhaps from a local cache?

The error you've posted doesn't happen when I try the latest `generator-aspnetcore-spa` (version 0.3.10), and the type `Dispatch` *is* generic in the current version of `@types/redux` (see line 105 of its `index.d.ts` file). So I think you must have got some older NPM modules somehow.

**Comment by nZeus** [comment]
You're right!
When I run `npm ls --global` I saw that version of `aspnetcore` generator was `0.3.6`.
Version `0.3.10` works fine.

Thanks a lot!
