### ISSUE TITLE
Accessing globals from boot-server prerendering

### ISSUE THREAD

**Issue by abhilash1990** [aspnet/JavaScriptServices#403]
Hi,

In Angular 2 and Asp.Net core app, I am using the DI system to make some global data available with some arbitrary key, e.g., by adding this to the providers array in boot-server.ts:

ngCore.provide('myCustomKey', { useValue: params.data.yourValue }),
... and then receiving this as a constructor parameter in a component:

constructor(@ng.Inject('myCustomKey') myValue: any) {
    // Do something with myVaue, e.g., prepopulate the component's data properties
}

After this i need to declare the same provide('myCustomKey', { useValue: params.data.yourValue }), in boot-client.ts otherwise application shows error - provider not available.

The issue is the data is coming in the pre-render but after a fraction of second it got overridden by the boot-client provider data.

Is there any way to get the pre-render data in boot-clien.ts?

**Comment by SteveSandersonMS** [comment]
Yes, in your `boot-server.ts`, as well as returning `html`, you can return a property called `globals`, and then it will be made available to your client-side code as a property on `window` (that you can capture and then optionally delete from `window` if you want to).

This is exactly how the ReactReduxSpa template transfers the Redux store state from the prerendered application to the client-side application (see it go from [here on the server](https://github.com/aspnet/JavaScriptServices/blob/dev/templates/ReactReduxSpa/ClientApp/boot-server.tsx#L45) to [here on the client](https://github.com/aspnet/JavaScriptServices/blob/dev/templates/ReactReduxSpa/ClientApp/boot-client.tsx#L13)).

**Comment by abhilash1990** [comment]
Already tried this. this is what mentioned in the document. 

But window is not available on ts file.

Getting error as window is undefined while trying to access the global variable from window.

**Comment by SteveSanderson** [comment]
I'm not sure what you mean by "not available". Are you talking about a TypeScript compilation error, or a runtime error?

**Comment by SteveSandersonMS** [comment]
I'm not sure what you mean by "not available". Are you talking about a TypeScript compilation error, or a runtime error?

**Comment by nickdb93** [comment]
I'm having the same issue. I get `window is not defined` at runtime
