### ISSUE TITLE
Issue with Angular2 - 2.1.1

### ISSUE THREAD

**Issue by lmaslanka** [aspnet/JavaScriptServices#406]
When I upgrade my angular2 npm packages to 2.1.1 I receive this error when I run the application? Has anyone run into this?

Exception: Call to Node module failed with error: TypeError: Cannot read property 'SelectorMatcher' of undefined at Object.<anonymous>

**Comment by MarkPieszak** [comment]
We are working on the fix for that you can track the PR here (https://github.com/angular/universal/pull/607) Stick with 2.1.0 for the moment if you can !

**Comment by EduardTheThird** [comment]
We just tried upgrading the JavaScriptServices Angular 2 template to Angular 2.4 without success. I accecpt that the Angular Universal 4 release that hindered the 2.1.1 upgrade is also keeping us from upgrading to 2.4?

**Comment by EduardTheThird** [comment]
We were able to update the JSS Angular 2 template to Angular 2.4.1 by upgrading the package.json as follows:
`	"@angular/common": "2.4.1",
		"@angular/compiler": "2.4.1",
		"@angular/core": "2.4.1",
		"@angular/forms": "2.4.1",
		"@angular/http": "2.4.1",
		"@angular/platform-browser": "2.4.1",
		"@angular/platform-browser-dynamic": "2.4.1",
		"@angular/platform-server": "2.4.1",
		"@angular/router": "3.4.1",
	        "rxjs": "5.0.1",
	        "zone.js": "^0.7.2"`

**Comment by F0rt1s** [comment]
Same here. Kendo.UI requires angular 2.4.*, but the when I update and run I get `"Exception: Call to Node module failed with error: Prerendering failed because of error: undefined"`. Currently I have 2.4.4. installed.

**Comment by EduardTheThird** [comment]
Removing pre-rendering from the <app> tag in your Index.cshtml bypasses the issue.

**Comment by larstbone** [comment]
Was able to upgrade past @angular:2.1.1 using the patch found here. 
https://github.com/MarkPieszak/aspnetcore-angular2-universal/blob/master/Client/__2.1.1.workaround.ts

**Comment by consigliory** [comment]
@larstbone so you did managed to upgrade angular to latest version and still have serverside running without any issues? right? did you just added _2.1.1.workaround.ts ?

**Comment by MarkPieszak** [comment]
Yes sorry I completely forgot to post back! As @larstbone said, the workaround will work to get you above 2.1.0+, so it works with the latest `2.4.5` (Just updated my repo as well, can see the file & imports [here](https://github.com/MarkPieszak/aspnetcore-angular2-universal/tree/master/Client)) for reference.

One thing to remember, you have to make sure the `__2.1.1.workaround.ts` file is imported at the very **TOP** of your boot-client & boot-server files. *This it to avoid an issue that's hard to pinpoint why it's happening: reflect-metadata Parser(?) unknown issue.*

Sorry for the annoyance but I hope that at least helps everyone!

@consigliory @EduardTheThird @lmaslanka

**Comment by EduardTheThird** [comment]
Fantastic, thank you @MarkPieszak.
Angular 2 updates as well as Webpack 2 in one month,(https://github.com/aspnet/JavaScriptServices/commit/be3fb6e87695689d2e079f9b17d0a63cc1b403fd) **epic**  🎈 🎉 Thanks!

**Comment by SteveSandersonMS** [comment]
`generator-aspnetcore-spa` version 0.8.1 is now published and offers the option to create Angular 2.4.5 projects (using @MarkPieszak's patch).
