### ISSUE TITLE
Angular2 in asp.net core which can only be used? Can not the official use of the original ecology?

### ISSUE THREAD

**Issue by qibucloud** [aspnet/JavaScriptServices#407]
Angular2 在  asp.net core 里面只能这样使用？ 不能官方原生态使用？

Angular2 in asp.net core which can only be used? Can not the official use of the original ecology?

**Comment by MarkPieszak** [comment]
Hey!
I'm not quite sure what you're asking, but if you're looking for the Angular2 project, use the Angular2Spa project in templates/Angular2spa. Not MusicStore.

https://github.com/aspnet/JavaScriptServices/tree/dev/templates/Angular2Spa

我不知道你问什么，但如果你正在寻找Angular2项目，在模板/ Angular2spa使用Angular2Spa项目。不MusicStore。

**Comment by SteveSandersonMS** [comment]
@qibucloud I hope Mark's reply answered your question, but if you are asking for something else, could you please clarify?

I'll close this hoping that your question is resolved, but please reopen if we haven't answered your question!
