### ISSUE TITLE
Does this support VUE.js?

### ISSUE THREAD

**Issue by sweetwxh** [aspnet/JavaScriptServices#410]
Or any plan to support vue?

**Comment by SteveSandersonMS** [comment]
If you mean "ship a Vue.js template", then no, we have no plans for that at the moment. We will keep track of how that library's popularity grows over time and might reconsider if it becomes important in the future. For now, there are only so many frameworks we have the capacity to maintain templates for!

Of course, the underlying SpaServices/NodeServices libraries can be used with any JS framework, so if you are keen enough on Vue, it should be possible to implement the equivalent HMR/server-side rendering/etc. features using those libraries.

**Comment by MarkPieszak** [comment]
Figured I'd try and tackle this one.

Started up an [ASP.NET Core & Vue 2.* webpack starter](https://github.com/MarkPieszak/AspNETCore-Vue-starter) (with server-side rendering, etc) for those who want to follow its progress!
Equivalent to these templates, but still need to add a few things to catch up to it. @laskoviymishka @sweetwxh
