### ISSUE TITLE
VueJS Support

### ISSUE THREAD

**Issue by laskoviymishka** [aspnet/JavaScriptServices#412]
VueJS is one of big UI framework that start to play big role on market. 

It would be nice to have template for VueJS (with server render enabled), since it already have a built-in support for it.
_https://vuejs.org/guide/ssr.html_

**Comment by SteveSandersonMS** [comment]
Thanks for the suggestion. There's limited capacity to maintain more templates at the moment, but if VueJS continues to grow in popularity, we can review this in the future. Of course, other people could offer VueJS yeoman templates using this technology stack if they wanted.

Closing for now as there's no action to take in this repo immediately. Hope that's OK.

**Comment by laskoviymishka** [comment]
@SteveSandersonMS that funny but actually this framework is far more popular than angular 2 😓 at least if we compare github stars ⭐️

**Comment by MarkPieszak** [comment]
In general I'd be cautious correlating stars in relation with general developer traction though. That being said Vue is great, it's easy when coding with es5 the way Angular 1.* was, think that's what spurred the general interest. For small/mid projects I think it's perfect! It's easy to get started with since you just drop in your `<script>` tag and get going.

I can imagine it'd be tough maintaining yet another template in the repo though! haha

**Comment by laskoviymishka** [comment]
Vuejs extremely popular in China. It's like angular 1.x in USA. Moreover vue is more like react then angular. It's a library which supply base infrastructure. Inner structure provides you ability to create blazing fast spa. It's could be even faster than react (and more lightweight). 

Anyway since templates count growth I thought that this framework is number one candidate. May be it worth to think about reorganize templates in something more scalable?

**Comment by SteveSandersonMS** [comment]
> Anyway since templates count growth I thought that this framework is number one candidate. May be it worth to think about reorganize templates in something more scalable? 

The scale limit is with developers working on maintaining/documenting/etc these templates. The ASP.NET team can only stretch its effort over so many third-party frameworks. Vue might be the top candidate if we were adding another, but right now there are other higher priorities. Of course, not everything needs to be in this one repo - others can publish their own Yeoman templates :)

**Comment by waynebrantley** [comment]
@SteveSandersonMS The argument here is about 'resources' to do Vue.  however, isn't this open source?   Shouldn't a pull request of Vue be allowed here?   There are several people working on these templates already - perhaps be nice to have it here in the 'official' repository.

**Comment by waynebrantley** [comment]
@MarkPieszak 
https://github.com/MarkPieszak/AspNETCore-Vue-starter

**Comment by waynebrantley** [comment]
And this one that you have contributed to?
https://github.com/ligershark/CoreTemplatePack

**Comment by MarkPieszak** [comment]
Steve if you'd like you can link to my Vue starter, for people looking for one.
I'm going to get it up to par with your templates here shortly, it has the basics working (SSR, webpack, etc), just need to spice up the components/templates.  @SteveSandersonMS
