### ISSUE TITLE
Error running new project from ASP.NET Core Angular 2 Starter Application template

### ISSUE THREAD

**Issue by mandarincreative** [aspnet/JavaScriptServices#415]
I am unable to run the app after creating a new project from the VS2015 template.  I have not made any changes to the project and have confirmed that app.component.css exists.

`An unhandled exception occurred while processing the request.

Exception: Call to Node module failed with error: Error: Cannot find module "./app.component.css"
at webpackMissingModule`

**Comment by mandarincreative** [comment]
After several rounds of NPM and Node.js uninstall/re-install, reboots and clean ups, I got this working.  Closing issue.

**Comment by hodzanassredin** [comment]
I had the same issue. Updated npm,restarted, removed all npm packages and restored.
But problem still here. Could you describe n details how did you do cleanup?

**Comment by hodzanassredin** [comment]
Also I had these errors in output:
```
ERROR in Angular2Application1\node_modules\to-string-loader\src\to-string.js:16
    return `
           ^
Unexpected token ILLEGAL
 @ ./ClientApp/app/components/navmenu/navmenu.component.ts 19:21-55

ERROR in Angular2Application1\node_modules\to-string-loader\src\to-string.js:16
    return `
           ^
Unexpected token ILLEGAL
```

**Comment by andreypopp** [comment]
Looks like `to-string-loader` requires at least Node v4 (because it uses ES2015 template literals, see [here](https://github.com/gajus/to-string-loader/blob/master/src/to-string.js#L16)) which is reasonable given that it's LTS.

**Comment by hodzanassredin** [comment]
Manually updated nodejs and the problem has gone.
