### ISSUE TITLE
Error when following the instructions to run sample (tag helper directive '@addTagHelper' with value '*, Microsoft.AspNetCore.SpaServices'.)

### ISSUE THREAD

**Issue by alebrozzo** [aspnet/JavaScriptServices#417]
I am getting this error when trying to test the samples MusicShop with react:

> Encountered an unexpected error when attempting to resolve tag helper directive '@addTagHelper' with value '*, Microsoft.AspNetCore.SpaServices'. Error: Could not load file or assembly 'Microsoft.AspNetCore.Mvc.ViewFeatures, Version=1.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
> @using MusicStore
> @addTagHelper "*, Microsoft.AspNetCore.Mvc.TagHelpers"
> @addTagHelper "*, Microsoft.AspNetCore.SpaServices"
 
I don't know MVC, I am trying to see the feasibility to use core + angular or core + react in the company I work for, and this seems like a good way to check the hybrid possibility, but I have no idea how to overcome this :(

**Comment by SteveSandersonMS** [comment]
Thanks for reporting this. The React MusicStore sample had got quite out-of-date and was relying on some previous-version technologies (TypeScript 1.x, .NET Core 1.0.0). I've just updated it to the latest technologies and patterns. It should work out-of-the-box now.

**Comment by alebrozzo** [comment]
Awesome! I've tried it and it works perfectly.
