### ISSUE TITLE
Method rename suggestion 

### ISSUE THREAD

**Issue by imranbaloch** [aspnet/JavaScriptServices#42]
Just a small suggestion to rename these method to make it consistent async naming.

https://github.com/aspnet/NodeServices/blob/74cac774f8800f59da9aaf98950b7da9e2297d72/src/Microsoft.AspNet.AngularServices/AngularRenderer.cs#L16

RenderToString to RenderToStringAsync

https://github.com/aspnet/NodeServices/blob/74cac774f8800f59da9aaf98950b7da9e2297d72/src/Microsoft.AspNet.NodeServices/INodeInstance.cs#L6-L8

Invoke to invokeAsync

https://github.com/aspnet/NodeServices/blob/74cac774f8800f59da9aaf98950b7da9e2297d72/src/Microsoft.AspNet.AngularServices/PrimeCacheHelper.cs#L11

PrimeCache to PrimeCacheAsync

:)

**Comment by MarkPieszak** [comment]
I could take this one if you'd like @SteveSandersonMS. Sounds like a good idea (just to keep the naming conventions consistent).

Also glad to of found this Repo, was trying to ask in Angular Universal where you were doing your .NET / Angular2 things :)

I'd love to help as much as possible, integrating .NET Core with Angular2 & Universal is near the top of my priority list! 👍

**Comment by SteveSandersonMS** [comment]
Thanks Mark, would be great to have your contributions here!

I'm about to deprecate and remove `AngularRenderer` altogether (in favour of the more general `SpaServices` prerendering helper, which with Angular as well as React etc.) so there's no need to update that one.

However I agree it would be good to clean up the naming for `Invoke` and `PrimeCache`.

Thanks!

**Comment by MarkPieszak** [comment]
Maybe we can talk next week so I can get up to speed with the project?
Actually starting a new Angular2 project with my team and have to use .NET Core and Universal :+1: 

Glad to help! @SteveSandersonMS

**Comment by SteveSandersonMS** [comment]
This is now done. The old names `Invoke` and `InvokeExport` remain available but marked as `[Obsolete]`. They will be removed at some point.
