### ISSUE TITLE
Production use and project ambitions

### ISSUE THREAD

**Issue by MrCrimp** [aspnet/JavaScriptServices#423]
@SteveSanderson 

On the home page it's state that _NodeServices_ "provides a fast and robust way to invoke Node.js code from a .NET application"

1. Is the _aspnet-prerender_ design battle tested yet in regards of stability, performance and scaling of node processes? Could you maybe elaborate a bit on the design, and recommendations for production hosting?
It's not clear to me if the node interop and server pre-render part has real ambitions or not.

2. Our team has built upon the _react-redux_ template as a dev stack for a rather large product, and we're loving it, but I'm getting questions about the project objectives and if it will merge itself into another part of the asp core stack in near or far future?

**Comment by SteveSandersonMS** [comment]
NodeServices is absolutely intended to be usable in production hosting. If you find any problems with its use then please let us know. There are no unusual requirements for production hosting - you just need a .NET Core host on a machine that also has `node` accessible (e.g., Azure has this; so would any Windows/Linux machine where you've installed both Node and .NET Core). If you have other specific questions please let us know!

> Our team has built upon the react-redux template ... I'm getting questions about the project objectives and if it will merge itself into another part of the asp core stack

The React-Redux project template is also intended to be suitable for real production use, though is relatively niche compared with say the Angular 2 template or the underlying NodeServices library itself. There's no plan to merge the template with some other part of ASP.NET - it's going to stay in the `javascriptservices` repo and be published as a Yeoman generator for the foreseeable future. Hope that helps!
