### ISSUE TITLE
Update solution to show Aurelia Template

### ISSUE THREAD

**Issue by ClaudioNunes** [aspnet/JavaScriptServices#426]
Please update sln file  to show Aurelia Template. It will make easier to find and contribute

**Comment by MarkPieszak** [comment]
Isn't it already in the yeoman template here? https://github.com/aspnet/JavaScriptServices/blob/dfcaae6fda8c6022506bfd12a0aa7cfbfd7b4384/templates/package-builder/src/build/build.ts#L16

![image](https://cloud.githubusercontent.com/assets/2574412/20192936/f2ef67fe-a759-11e6-985a-b38a28a6af17.png)

Template itself here: https://github.com/aspnet/JavaScriptServices/tree/dfcaae6fda8c6022506bfd12a0aa7cfbfd7b4384/templates/AureliaSpa

Did you update your yeoman?

    npm i -g generator-aspnetcore-spa

**Comment by SteveSandersonMS** [comment]
@MarkPieszak Yes, it is in the Yeoman template. @ClaudioNunes means adding a reference from the `.sln` file to the `AureliaSpa.xproj`. We seem to be missing a reference to `KnockoutSpa.xproj` in there too.

**Comment by SteveSandersonMS** [comment]
This is now done thanks to @laskoviymishka's pull request.
