### ISSUE TITLE
ASP.net core Angular 2 template not running.

### ISSUE THREAD

**Issue by bilalhassan88** [aspnet/JavaScriptServices#430]
Hi Team,

I followed all the steps from Steve's blog trying to run the template.
http://blog.stevensanderson.com/2016/10/04/angular2-template-for-visual-studio/

I get this error
In Startup.cs this comes up highlighted.

app.UseWebpackDevMiddleware(new WebpackDevMiddlewareOptions {
HotModuleReplacement = true
});

with message

An exception of type 'System.AggregateException' occurred in System.Private.CoreLib.ni.dll but was not handled in user code

Any idea what might be causing this?
Banging my head for 2 days now.

Please help

**Comment by bilalhassan88** [comment]
Inner exception

call to Node module failed with error: TypeError: Cannot read property 'publicPath' of undefined at createWebpackDevServer (C:\Users\Bilal\node_modules\aspnet-webpack\WebpackDevMiddle‌​ware.js:9:43) at module.exports.createWebpackDevServer (C:\Users\Bilal\AppData\Local\Temp\tmp85CD.tmp:19:49) at C:\Users\Bilal\AppData\Local\Temp\tmp8726.tmp:113:19 at IncomingMessage.<anonymous> (C:\Users\Bilal\AppData\Local\Temp\tmp8726.tmp:132:38) at emitNone (events.js:67:13) at IncomingMessage.emit (events.js:166:7) at endReadableNT (_stream_readable.js:921:12)...

**Comment by mhheise** [comment]
Do you have a publicPath defined in your `package.json`?

```javascript
module.exports = {
    context: __dirname,
    resolve: {
        extensions: [ '', '.js', '.ts' ]
    },
    output: {
        filename: '[name].js',
        publicPath: '/dist/' // This line
}
```

**Comment by bilalhassan88** [comment]
this is what my package.json looks like at the moment, unchanged from what was in the template

{
  "name": "Angular2Spa",
  "version": "0.0.0",
  "dependencies": {
    "@angular/common": "2.0.0",
    "@angular/compiler": "2.0.0",
    "@angular/core": "2.0.0",
    "@angular/forms": "2.0.0",
    "@angular/http": "2.0.0",
    "@angular/platform-browser": "2.0.0",
    "@angular/platform-browser-dynamic": "2.0.0",
    "@angular/platform-server": "2.0.0",
    "@angular/router": "3.0.0",
    "@types/node": "^6.0.38",
    "angular2-platform-node": "~2.0.10",
    "angular2-universal": "~2.0.10",
    "angular2-universal-polyfills": "~2.0.10",
    "aspnet-prerendering": "^1.0.6",
    "aspnet-webpack": "^1.0.11",
    "bootstrap": "^3.3.7",
    "css": "^2.2.1",
    "css-loader": "^0.25.0",
    "es6-shim": "^0.35.1",
    "expose-loader": "^0.7.1",
    "extract-text-webpack-plugin": "^1.0.1",
    "file-loader": "^0.9.0",
    "isomorphic-fetch": "^2.2.1",
    "jquery": "^2.2.1",
    "preboot": "^4.5.2",
    "raw-loader": "^0.5.1",
    "rxjs": "5.0.0-beta.12",
    "style-loader": "^0.13.0",
    "to-string-loader": "^1.1.5",
    "ts-loader": "^0.8.2",
    "typescript": "^2.0.0",
    "url-loader": "^0.5.7",
    "webpack": "^1.12.14",
    "webpack-externals-plugin": "^1.0.0",
    "webpack-hot-middleware": "^2.10.0",
    "webpack-merge": "^0.14.1",
    "zone.js": "^0.6.21"
  }
}

**Comment by MarkPieszak** [comment]
It looks like you have an old version of the template.

Try:

`npm i -g generator-aspnetcore-spa` to update it, then reinstall a new one. `yo aspnetcore-spa` etc

**Comment by SteveSandersonMS** [comment]
@MarkPieszak they're using the Visual Studio template, not the Yeoman generator. It's the same content (not as up-to-date, but should still work).

@bilalhassan88 Is your project really at `C:\Users\Bilal\`? As in, your application files are at the root of your user directory? That would be extremely unusual and probably isn't what you want. Or if your project is in some other directory (or a subdirectory), then it looks like your machine has `node_modules` installed badly. I see that the directory `C:\Users\Bilal\node_modules\` exists, which is worrying, because that is going to interfere with every Node project you create within your `C:\Users\Bilal` directory (Node looks for `node_modules` in all ancestor directories of the one your project is in). I'd suggest deleting `C:\Users\Bilal\node_modules` and being careful not to run `npm install` from `C:\Users\Bilal`. After clearing up any rogue `node_modules` directories, you may need to re-run the template to create a new project so it can install dependencies properly.

**Comment by bilalhassan88** [comment]
@SteveSandersonMS Thanks for the reply, i have just started with node and had no idea how it operated, will remove it and move my project to another directory. 
I was banging my head wondering why this was happening, the template was working great on my office laptop.

**Comment by Ardevik** [comment]
@SteveSandersonMS I have same issue
"One or more errors occurred. (Call to Node module failed with error: TypeError: Cannot read property 'publicPath' of undefined\n    at c:\\Users\\Vikar\\Documents\\Visual Studio 2015\\Projects\\Modalin\\src\\Modalin\\node_modules\\aspnet-webpack\\WebpackDevMiddleware.js:159:59\n    at Array.forEach (native)\n    at Server.<anonymous> (c:\\Users\\Vikar\\Documents\\Visual Studio 2015\\Projects\\Modalin\\src\\Modalin\\node_modules\\aspnet-webpack\\WebpackDevMiddleware.js:148:32)\n    at Server.g (events.js:291:16)\n    at emitNone (events.js:86:13)\n    at Server.emit (events.js:185:7)\n    at emitListeningNT (net.js:1288:10)\n    at _combinedTickCallback (internal/process/next_tick.js:71:11)\n    at process._tickCallback (internal/process/next_tick.js:98:9))"

this is my webpack config

"use strict";
var webpack = require("webpack");
var path = require("path");
var clone = require("js.clone");
var webpackMerge = require("webpack-merge");
exports.commonPlugins = [
    new webpack.ContextReplacementPlugin(
    // The (\\|\/) piece accounts for path separators in *nix and Windows
    /angular(\\|\/)core(\\|\/)src(\\|\/)linker/, root("./Client"), {}),
    // Loader options
    new webpack.LoaderOptionsPlugin({}),
];
exports.commonConfig = {
    // https://webpack.github.io/docs/configuration.html#devtool
    devtool: "source-map",
    resolve: {
        extensions: [".ts", ".js", ".json"],
        modules: [root("node_modules")]
    },
    context: __dirname,
    output: {
        publicPath: '/dist/',
        filename: "[name].bundle.js"
    },
    module: {
        rules: [
            // TypeScript
            { test: /\.ts$/, use: ["awesome-typescript-loader", "angular2-template-loader"] },
            { test: /\.html$/, use: "raw-loader" },
            { test: /\.css$/, use: "raw-loader" },
            { test: /\.json$/, use: "json-loader" }
        ]
    },
    plugins: []
};
// Client.
exports.clientPlugins = [];
exports.clientConfig = {
    target: "web",
    entry: { "main-client": "./Client/boot-client.ts" },
    output: {
        path: root("wwwroot/dist")
    },
    node: {
        global: true,
        crypto: "empty",
        __dirname: true,
        __filename: true,
        process: true,
        Buffer: false
    }
};
// Server.
exports.serverPlugins = [];
exports.serverConfig = {
    target: "node",
    entry: { "main-server": "./Client/boot-server.ts" },
    output: {
        path: root("wwwroot/dist"),
        libraryTarget: "commonjs2"
    },
    module: {
        rules: [
            { test: /@angular(\\|\/)material/, use: "imports-loader?window=>global" }
        ]
    },
    externals: includeClientPackages(/@angularclass|@angular|angular2-|ng2-|ng-|@ng-|angular-|@ngrx|ngrx-|@angular2|ionic|@ionic|-angular2|-ng2|-ng/),
    node: {
        global: true,
        crypto: true,
        __dirname: true,
        __filename: true,
        process: true,
        Buffer: false
    }
};
exports.__esModule = true;
exports["default"] = [
    // Client
    webpackMerge(clone(exports.commonConfig), exports.clientConfig, { plugins: exports.clientPlugins.concat(exports.commonPlugins) }),
    // Server
    webpackMerge(clone(exports.commonConfig), exports.serverConfig, { plugins: exports.serverPlugins.concat(exports.commonPlugins) })
];
// Helpers
function includeClientPackages(packages, localModule) {
    return function (context, request, cb) {
        if (localModule instanceof RegExp && localModule.test(request)) {
            return cb();
        }
        if (packages instanceof RegExp && packages.test(request)) {
            return cb();
        }
        if (Array.isArray(packages) && packages.indexOf(request) !== -1) {
            return cb();
        }
        if (!path.isAbsolute(request) && request.charAt(0) !== ".") {
            return cb(null, "commonjs" + request);
        }
        return cb();
    };
}
exports.includeClientPackages = includeClientPackages;
function root(args) {
    args = Array.prototype.slice.call(arguments, 0);
    return path.join.apply(path, [__dirname].concat(args));
}
exports.root = root;

**Comment by nicolaslawdune** [comment]
Your problem occurs because your WebPackDevMiddleware don't find your webpack.config.ts.
Specify the configPath value

`              app.UseWebpackDevMiddleware(new WebpackDevMiddlewareOptions
                {
                     ConfigFile = "AppConfig/webpack.dev.js",
                    HotModuleReplacement = true
                });`

**Comment by gayan1991** [comment]
Hi, I am having the issue, Please help me. the exception is

```
Call to Node module failed with error: TypeError: Cannot read property 'publicPath' of undefined
    at C:\Users\nadeeshag.NCS\node_modules\aspnet-webpack\WebpackDevMiddleware.js:99:59
    at Array.forEach (native)
    at Server.<anonymous> (C:\Users\nadeeshag.NCS\node_modules\aspnet-webpack\WebpackDevMiddleware.js:88:32)
    at Server.g (events.js:286:16)
    at emitNone (events.js:86:13)
    at Server.emit (events.js:185:7)
    at emitListeningNT (net.js:1279:10)
    at _combinedTickCallback (internal/process/next_tick.js:71:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```
Following is the method
```
app.UseDeveloperExceptionPage();
                    app.UseWebpackDevMiddleware(new WebpackDevMiddlewareOptions
                    {
                        HotModuleReplacement = true
                    });
```

**Comment by nicolaslawdune** [comment]
Did you specify the webpack.config file path in the WebpackDevMiddlewareOptions ?
You have to specify too the "PublicPath" in your webpack.config,

**Comment by gayan1991** [comment]
The same solution is working in another computer, only in one computer its not working.

In case I have attached my webpack.confg.js file as well

```
var isDevBuild = process.argv.indexOf('--env.prod') < 0;
var path = require('path');
var webpack = require('webpack');
var nodeExternals = require('webpack-node-externals');
var ExtractTextPlugin = require('extract-text-webpack-plugin');
var merge = require('webpack-merge');
var allFilenamesExceptJavaScript = /\.(?!js(\?|$))([^.]+(\?|$))/;
var CopyWebpackPlugin = require('copy-webpack-plugin');
const CheckerPlugin = require('awesome-typescript-loader').CheckerPlugin;
const clientBundleOutputDir = './wwwroot/dist';

// Configuration in common to both client-side and server-side bundles
module.exports = (env) => {
    // Configuration in common to both client-side and server-side bundles
    const isDevBuild = !(env && env.prod);

    // Configuration in common to both client-side and server-side bundles
    return {
        stats: { modules: false },
        context: __dirname,
        entry: {
            'polyfills': './ClientApp/polyfills.browser.ts',
            'main-client': './ClientApp/boot-client.ts'
        },
        resolve: { extensions: ['.js', '.ts'] },
        output: {
            filename: '[name].js',
            sourceMapFilename: '[name].map',
            chunkFilename: '[id].chunk.js',
            publicPath: '/dist/',
            libraryTarget: 'var',
            path: path.join(__dirname, clientBundleOutputDir)
        },
        module: {
            rules: [
                {
                    test: /\.ts$/,
                    include: /ClientApp/,
                    exclude: [/\.(spec|e2e)\.ts$/],
                    use: ['ts-loader?silent=true', 'angular2-template-loader']
                },
                 {
                     test: /\.json$/,
                     use: 'json-loader'
                 },
                { test: /\.html$/, use: ['html-loader?minimize=false'] },
                //{
                //    test: /\.css/, use: ExtractTextPlugin.extract({
                //        fallback: "raw-loader",
                //        use: "css-loader"
                //    })
                //},
                {
                    test: /\.(jpg|jpeg|gif|png)$/,
                    exclude: /node_modules/,
                    use: ['url-loader?limit=25000&name=images/[name].[ext]']
                },
                { test: /\.woff(2)?(\?v=[0-9]\.[0-9]\.[0-9])?$/, use: ['url-loader?limit=10000&mimetype=application/font-woff'] },
                { test: /\.(ttf|eot)(\?v=[0-9]\.[0-9]\.[0-9])?$/, use: ['url-loader?limit=1024&name=fonts/[name].[ext]'] },
                {
                    test: /\.svg(\?v=\d+\.\d+\.\d+)?$/,
                    use: ["url-loader?limit=10000&mimetype=image/svg+xml&name=images/[name].[ext]"]
                },
                 {
                     test: /(\.css|\.scss)$/,
                     use: ExtractTextPlugin.extract({
                         fallback: "raw-loader",
                         use: [
                             "css-loader",
                             "sass-loader"]
                     })
                 }
            ]
        },
        plugins: [
            new CheckerPlugin(),
            new ExtractTextPlugin('styles.css'),
            new CopyWebpackPlugin([
                        // Copy icons
                        {
                            context: 'ClientApp/images',
                            from: '**/*',
                            to: 'images'
                        }
            ],
                    {
                        ignore: [
                            // Doesn't copy any files with a txt extension     
                            '*.txt'
                        ],

                        // By default, we only copy modified files during 
                        // a watch or webpack-dev-server build. Setting this 
                        // to `true` copies all files. 
                        copyUnmodified: false
                    }),
            new webpack.DllReferencePlugin({
                context: __dirname,
                manifest: require('./wwwroot/dist/vendor-manifest.json')
            }),
            new webpack.ProvidePlugin({
                Reflect: 'core-js/es7/reflect'
            })  
        ].concat(isDevBuild ? [
            // Plugins that apply in development builds only
            new webpack.SourceMapDevToolPlugin({
                module: true,
                filename: '[file].map', // Remove this line if you prefer inline source maps
                columns: false,
                moduleFilenameTemplate: path.relative(clientBundleOutputDir, '[resourcePath]') // Point sourcemap entries to the original file locations on disk
            })
        ] : [
            // Plugins that apply in production builds only
            new webpack.optimize.OccurrenceOrderPlugin(),
            new webpack.optimize.UglifyJsPlugin()
        ])
    }
};
```

**Comment by bilalhassan88** [comment]
I had the same issue that it was working on one computer and not the other, Steve's reply did the trick for me, i had to move my project from C drive to another drive and it worked.

**Comment by gayan1991** [comment]
Actually it did the trick for me too. Thank you @SteveSandersonMS @bilalhassan88
