### ISSUE TITLE
ASP.NET Core Template Pack in the corporate environment - Proxy Authentication Required

### ISSUE THREAD

**Issue by EDTInfrastructure** [aspnet/JavaScriptServices#438]
OK, 1st up apologies if this is the wrong place for this but it's where Steve Sanderson's blog (http://blog.stevensanderson.com/2016/10/04/angular2-template-for-visual-studio/) pointed to for issues on the ASP.NET Core Template Pack. I saw Steve present at MS future decoded 2016 and really wanted to try this out back in the office as a complete newbie to web development. My issue is integration of nuget/VS 2015 with this template when fetching packages like Microsoft.AspNetCore.AngularServices. I'm obviously now behind a proxy server in the corporate environment so I get "Response status code does not indicate success: 407 (Proxy Authentication Required)" for all the packages required. How would I configure this to work with the proxy server?

Solved! 
1) Started by updating my nuget version: 
`nuget update self`

2) Added proxy details to the config file: 
`nuget config -Set http_proxy=http://username:password@proxyserver.company.com:port`

Magic - only thing I hate is nugget leaving my plain text password in %appdata%\NuGet\NuGet.Config

**Comment by SteveSandersonMS** [comment]
Thanks for posting.

As far as I'm aware, the solution you've posted (`nuget config ...`) is the correct one. Glad you sorted it out!
