### ISSUE TITLE
VS2017 support (e.g. new csproj format)

### ISSUE THREAD

**Issue by tinchou** [aspnet/JavaScriptServices#440]
Just dropping this here so we have this in mind.

Tried using the automatic migration with my project but I'm having some issues. Bug report here: https://github.com/Microsoft/msbuild/issues/1354.

**Comment by LunicLynx** [comment]
Possible solution here: https://github.com/dotnet/cli/issues/4785

**Comment by SteveSandersonMS** [comment]
This is now published. If you get the latest `generator-aspnetcore-spa` Yeoman generator, then whenever you create a new project, you'll be able to choose between VS2015-style project.json or VS2017-style .csproj.

If you have an existing project.json project and want to start using VS2017RC, you most likely can just drop in a `.csproj` produced by the new template and delete your own `project.json` and `.xproj` files.
