### ISSUE TITLE
Create a few 5 to 10 minute videos explaining how the template works for beginners.

### ISSUE THREAD

**Issue by JerryPierre** [aspnet/JavaScriptServices#441]
Hi all,

a suggestion, because of the complexities of the template it would be very helpful to create a few 5 to 10 minute videos explaining how the template works for beginners.

thanks.

**Comment by boban984** [comment]
Hi Jerry
There is already a great video presentation by Steve : [![ASP.NET Core for Angular, React, Knockout etc developers](http://img.youtube.com/vi/C6MPSLgsGGs/0.jpg)](https://www.youtube.com/watch?v=C6MPSLgsGGs)

Do you need more explanation than that, if so on what topic would you like more details?

**Comment by SteveSandersonMS** [comment]
I think @boban984 is correct - that video covers pretty much what I think newcomers will need to know. When we move the docs for this onto docs.asp.net, I'll make sure we link to that video or something similar.

**Comment by JerryPierre** [comment]
Great, thank you!
