### ISSUE TITLE
Update to Asp.Net Core 1.1

### ISSUE THREAD

**Issue by flightlevel** [aspnet/JavaScriptServices#442]
https://blogs.msdn.microsoft.com/dotnet/2016/11/16/announcing-net-core-1-1/

**Comment by SteveSandersonMS** [comment]
Done. We've published `1.1.0-beta-000001` packages to NuGet that take dependencies on 1.1.0 packages rather than 1.0.1 ones. The source for this is in the `netcore-1-1-update` branch that will be merged to `dev` once we're ready to move on from 1.0.1 completely.

**Comment by justsayno** [comment]
Is this available via the yeoman generator at all? If so how would I install it?
