### ISSUE TITLE
Webpack 2 no longer appends "-loader" suffix

### ISSUE THREAD

**Issue by scottaddie** [aspnet/JavaScriptServices#444]
The following PR was merged into Webpack 2: https://github.com/webpack/webpack/pull/3102. To better position these templates for an upgrade to Webpack 2, all loaders should explicitly use the "-loader" suffix. Let me know if this is a change you'd like, and I'll submit a PR for it.

**Comment by SteveSandersonMS** [comment]
Thanks for the notification and the offer of a PR!

Yes, this would be great. I should be able to merge that as soon as you submit it.

**Comment by scottaddie** [comment]
@SteveSandersonMS You're welcome! It's ready for you to take a look.

**Comment by scottaddie** [comment]
This was addressed with PR #447, which has been merged.
