### ISSUE TITLE
Windows Authentication: fail to get User.Identity.Name in controller (always null)

### ISSUE THREAD

**Issue by wenkangjing** [aspnet/JavaScriptServices#455]
Project was generated by yo `aspnetcore-spa - React With Redux`, with following settings

launchSettings.json
```
    "windowsAuthentication": true,
    "anonymousAuthentication": true,
```
Symptom
 User.Identity.Name; is always null in any controllers

Walk around
Set anonymousAuthentication to false can walk around it, but just curious why.

**Comment by SteveSandersonMS** [comment]
Would you mind posting this at https://github.com/aspnet/Identity/issues, since it's a general question about identity in ASP.NET Core rather than being specific to the SPA templates? Thanks!
