### ISSUE TITLE
Bug in deployment script for "ASP.NET Core + Angular 2 template for Visual Studio"

### ISSUE THREAD

**Issue by syerkes1** [aspnet/JavaScriptServices#459]
I have tried to deploy the template "ASP.NET Core + Angular 2 template for Visual Studio" as defined at: 

http://blog.stevensanderson.com/2016/10/04/angular2-template-for-visual-studio/

...and I always get this error:

"...004056\Extensions\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Props" was not found. "

full error...

Project "D:\home\site\repository\Angular2App7.xproj" on node 1 (Publish target(s)).
D:\home\site\repository\Angular2App7.xproj(8,3): error MSB4019: The imported project "D:\Program Files (x86)\dotnet\sdk\1.0.0-preview3-004056\Extensions\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Props" was not found. C
hat the path in the <Import> declaration is correct, and that the file exists on disk.
Done Building Project "D:\home\site\repository\Angular2App7.xproj" (Publish target(s)) -- FAILED.

**Comment by justsayno** [comment]
I can report this error also occurs in the React + Redux project with fresh install just now.

```
c:\dev\test-dotnet\TestDotnet.xproj(8,3): error MSB4019: The imported project "C:\Program Files\dotnet\sdk\1.0.0-preview4-004117\Extensions\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
```

**Comment by justsayno** [comment]
@syerkes1 Did you get it to not have this error?

**Comment by syerkes1** [comment]
No. I have tried several times, on 2 different computers, but I always get the same error.  The web app runs fine locally, but it errors on deploy.  I'm using VS 2015 Update 3, Node.js 7.2.0,  and  .NET Core 1.0.1 tools Preview 2.

**Comment by syerkes1** [comment]
I'm not sure why the status says "closed" on this...I didn't close it.

**Comment by SteveSandersonMS** [comment]
Hi all. I guess you have installed VS2017RC or .NET Tools Preview 3.

You're facing this issue: [Installing preview-3 breaks VS2015 and dotnet cli (https://github.com/dotnet/cli/issues/4384)](https://github.com/dotnet/cli/issues/4384).

The fix is as per [@livarcocc's comment](https://github.com/dotnet/cli/issues/4384#issuecomment-258031454), i.e.:

 * Make sure you also have .NET Core 1.0.1 installed (you probably already do, if you were working in VS2015 previously)
 * Add a `global.json` file at the root of your project telling `dotnet` to build using the preview2 SDK:

```
{
  "sdk":
  {
    "version": "1.0.0-preview2-003121"
  }
}
```

I'm going to add this `global.json` file to the templates now, so newly-created projects won't be affected by SDK preview3 (though the error will still occur if you *only* have SDK preview3 and not preview2).

**Comment by syerkes1** [comment]
Yeah, this is not really is fix/solution.  Preview 2 is obsolete. Where can I even download it? Why don't you just make the scripts work with Preview 3. "ASP.NET Core + Angular 2 template for Visual Studio" is busted and not usable....

**Comment by justsayno** [comment]
To clarify for other readers there are preview-3 and preview-4 out. But they are not the officially rleased version. If you go to this page

[https://www.microsoft.com/net/core](https://www.microsoft.com/net/core)

And click on the `Command Line / Other` tab then you will get preview 2 as mentioned above. (or whatever latest rleased version is when this is being read).

**Comment by syerkes1** [comment]
I still don't get it.  I have Preview 2 installed, and VS2015 with Update 3.  WTF?

**Comment by syerkes1** [comment]
I have been a .NET dev since 1.0 and so far, this new Mircosoft stack, with .NET Core on the back end and Angular 2 on the front end is big "fail"...  seriously...  you guys templates that don't even work...  I'm trying to sell this solution to a client right now...  bullshit.

**Comment by justsayno** [comment]
Have you got 2017 Preview Installed? I found that once I uninstalled that it worked. I agree was rocky to get this going but once I have its good.

**Comment by syerkes1** [comment]
No, like I stated above..

I still don't get it. I have Preview 2 installed, and VS2015 with Update 3.

...and when I say Preview 2, I mean ".NET Core 1.0.1 tools Preview 2".  The stuff on the main .net CORE page...  if there is something else I need to get, the dude that close the bug should provide some links.  I appreciate that fact that he put a template out for this stack, but it's outdated and dude needs to update it..  he closed it without really solving the problem..

**Comment by justsayno** [comment]
What do you get when you run:

```bash
dotnet --version
```

I get

```bash
1.0.0-preview2-003131
```

**Comment by syerkes1** [comment]
@SteveSandersonMS 

Tell us the exact software stack we need to run your template, please.  VS2015 Update 3, I'm assuming, and .NET Core 101. Tools Preview 3, correct? I am running a brand new PC, this is all I have installed... just break it down for me..

**Comment by syerkes1** [comment]
@justsayno 

Yup, I get the same.. 

1.0.0-preview2-003131

**Comment by syerkes1** [comment]
@justsayno, Thanks for helping, by the way...  super cool... shit is frustrating... just trying get it to run.. It deploys, but it dies when it tries to start the web server...  I followed the instructions exactly, like 7 times.. .no matter what I do, same error...

**Comment by justsayno** [comment]
Ohh I just re-read your original post. Have you tried using the Yoeman Generator rather than the Visual Studio Template? It will work I think as that is what worked for me today.

**Comment by syerkes1** [comment]
By the way, I added the global.json the @SteveSandersonMS recommended, but now I get the error when I try and build... 

"Severity	Code	Description	Project	File	Line	Suppression State
Error		The project is configured to use .NET Core SDK version 1.0.0-preview2-003121 which is not installed or cannot be found under the path C:\Program Files\dotnet. These components are required to build and run this project. Download the version of .NET Core SDK specified in global.json or update the SDK version in global.json to the version that is installed.	Angular2App7	C:\Users\[user]\documents\visual studio 2015\Projects\Angular2App7\Angular2App7\GETSDKTOOLINGINFO	1	
"

...this shit is wonky..

So, how about a link to the SDK that I need? jeezuss...

**Comment by syerkes1** [comment]
....I'm going to bed.. LOL.. .if Microsoft wants to be a contender in the PWA/Angjul2 to world, that is for sure gonna be the standard for the next 5+ years, they better get their shit together...   This isn't cool...

**Comment by MarkPieszak** [comment]
Change your global json to match the version you have installed, it's telling you 

> "Error The project is configured to use .NET Core SDK version 1.0.0-preview2-**003121** which is not installed or cannot be found under the path C:\Program Files\dotnet. 

Change it to be **003131** which you said you have installed.

I just pulled down a fresh Template, I have 03177 installed, it worked *without* even the global.json.

The fact that it's acting up for you means you have .NET Core 1.1 (a preview, an RC, something) installed, even if you didn't install 2017. Either way using global json to point to a 1.0.1 version will get it to work.

1.1 just came out last week, so everything is still in transition.

**Comment by justsayno** [comment]
Another idea. Try cloning this:

```bash
git clone https://github.com/justsayno/dotnet-angular2
```

That was generated yesterday and works fine with the following:

```bash
dotnet --version
# 1.0.0-preview2-1-003177
```
