### ISSUE TITLE
how to define a static INodeServices 

### ISSUE THREAD

**Issue by AnyListen** [aspnet/JavaScriptServices#461]
It's complicated to define a static INodeServices；
for the moment i defined it using below code;
how can i define a static INodeServices more easily.
```
Startup.cs

public void ConfigureServices(IServiceCollection services) 
{
        services.AddApplicationInsightsTelemetry(Configuration); 
        services.AddMvc();  
        services.AddNodeServices(); 
        CommonHelper.InitNode(services); 
} 
```
```
NodeHelper.cs

private static INodeServices _nodeServices;
public static void InitNode(IServiceCollection serviceCollection)
{
        var service = serviceCollection;
        var serviceProvider = service.BuildServiceProvider();
        _nodeServices = NodeServicesFactory.CreateNodeServices(new  NodeServicesOptions(serviceProvider));
}
```

**************************************************************************

**Comment by SteveSandersonMS** [comment]
You can do that with a static instance if you want to, but it's better and easier to use ASP.NET's built-in dependency injection system to obtain `INodeServices` instances. Docs are here: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection
