### ISSUE TITLE
ASP.NET Core + Angular 2 template for Visual Studio - broken

### ISSUE THREAD

**Issue by syerkes1** [aspnet/JavaScriptServices#466]
This template is busted. I now get this error..

Build FAILED.

"D:\home\site\repository\Angular2App8.xproj" (Publish target) (1) ->
  D:\home\site\repository\Angular2App8.xproj(8,3): error MSB4019: The imported project "D:\Program Files (x86)\dotnet\sdk\1.0.0-preview3-004056\Exten
 that the path in the <Import> declaration is correct, and that the file exists on disk.

...dude, fix your template, or delete it.  You are doing the community a dis-service.  I'm sure it worked at some point in the past, but you wasted 8 hours of my time.  We are trying to write real software here... seriously, thank you, but your shit is out-dated and irrelevant.  It doesn't work with the latest binaries... don't waste our time anymore... like I said, fix it or delete it... but you're shit doesn't work and it's wasting our time and costing us money.  Be professional and get your shit together...   jeezus fucking Christ..  You're killing me!!!

**Comment by MarkPieszak** [comment]
This is an *extremely* unprofessional, rude, and unwarranted attack... 

Using new software and libraries isn't easy, and having people help you isn't a service you are simply entitled to. You need to properly explain what is happening, what you've done that led to the template not working.

**Comment by syerkes1** [comment]
This issue is closed.
