### ISSUE TITLE
Node.js error after EntityFramework Core installation

### ISSUE THREAD

**Issue by EmaGht** [aspnet/JavaScriptServices#474]
Hi, once i downloaded this template and created a new project i installed Microsoft.EntityFrameworkCore 1.1.0 from nuget and at the startup, my browser shows this message:

Exception: Call to Node module failed with error: Error: Zone.js has detected that ZoneAwarePromise `(window|global).Promise` has been overwritten.
Most likely cause is that a Promise polyfill has been loaded after Zone.js (Polyfilling Promise api is not necessary when zone.js is loaded. If you must load one, do so before loading zone.js.)

I'm only using this template and nuget to install EF.Core, I haven't done any other modifications to the project files whatsoever.

Regards,
Ema

**Comment by MarkPieszak** [comment]
This is actually related to something else, you can track https://github.com/aspnet/JavaScriptServices/issues/470, but it looks like Steve has a fix in mind that should be out in the next few hours as well!

**Comment by SteveSandersonMS** [comment]
Fixed in #440. Sorry for the inconvenience!
