### ISSUE TITLE
Error: Zone.js has detected that ZoneAwarePromise 

### ISSUE THREAD

**Issue by Ciejaa** [aspnet/JavaScriptServices#476]
Hi, I'm getting an error message when I'm running project

> Exception: Call to Node module failed with error: Error: Zone.js has detected that ZoneAwarePromise `(window|global).Promise` has been overwritten.
> Most likely cause is that a Promise polyfill has been loaded after Zone.js (Polyfilling Promise api is not necessary when zone.js is loaded. If you must load one, do so before loading zone.js.)

Do you know what's going on ?

**Comment by nicwillemse** [comment]
Hi, this is a duplicate  - please see https://github.com/aspnet/JavaScriptServices/issues/470

**Comment by nicwillemse** [comment]
@SteveSandersonMS please close as duplicate

**Comment by SteveSandersonMS** [comment]
The fix is live now. Please update to version 1.0.0-beta-0000021 (or just go back to specifying 1.0.0-* but make sure it fetches the latest).

If you still get any issues please let me know!
