### ISSUE TITLE
How to apply changes to project structure?

### ISSUE THREAD

**Issue by hrantbagdasarian** [aspnet/JavaScriptServices#478]
I'm sorry if this is not the correct place to ask this, but I was wondering if the generated project template changes for some reason, for example when .csproj is re-introduced in VS2017 or when there are some code changes in the boot-client/server.ts files, are there any steps we can follow to update an existing project to the latest version?

The reason I'm asking this is because I'm currently developing an Angular 2 application which was generated by the angular-cli, but I'd like to move it into a ASP.NET Core application using the ASP.NET Core Angular starter pack template, but I'm not sure how to keep the project up to date with the latest releases (both in code and project structure).

**Comment by SteveSandersonMS** [comment]
One of the age-old problems with all project templates is the lack of any automated way to "round trip" changes, i.e., acquire updates in the base template while preserving all the changes and additions you made on top of that template. Unfortunately, the templates here do not include any solution to that age-old problem!

The good news however is that, in most cases, you don't strictly need to acquire any updates corresponding to newer templates. The templates are valid starting points for building an app, and once you're building something that works, you can continue forever without caring whether newly-created projects would look the same or not. We try to keep our libraries and packages back-compatible with the projects generated by older templates, so you should be able to upgrade those in most cases without it being a problem.

There will be some exceptions, notably the move to `.csproj` like you mention. Once that becomes mandatory (for support on newer tooling, e.g., VS2017) and the exact details are finalised, we'll publish a migration guide.

If you are especially keen to migrate to the same structure, Webpack config, etc., as the latest templates, I'm afraid it will be a manual process of copying your own files into the new project, re-applying any changes to build config, etc., as it would be for any other project template.
