### ISSUE TITLE
Debugging TypeScript Code in Aurelia-SPA Template

### ISSUE THREAD

**Issue by R74NN** [aspnet/JavaScriptServices#481]
Hello,

after installing Aurelia template with SPA generator, I'm not able to make debugging of TypeScript files work. I have tried VS 2015 Update3 and VS Code with no luck. Source map files seem to be generated, but the breakpoints are not hit, because of "no symbols loaded".

Is there a guide how to make it work?

Thanks.

**Comment by SteveSandersonMS** [comment]
There's a guide to setting up debugging here: https://github.com/aspnet/JavaScriptServices/tree/dev/src/Microsoft.AspNetCore.SpaServices#debugging-your-projects

If it still doesn't work, please reopen with details. Thanks!
