### ISSUE TITLE
Docker: Broken after .Net Core 1.1.0 upgrade

### ISSUE THREAD

**Issue by EduardTheThird** [aspnet/JavaScriptServices#489]
Hi Guys

Docker containers are still running .Net Core 1.0.1 and not 1.1.0.

![dockerexception](https://cloud.githubusercontent.com/assets/6488837/20919348/f23252dc-bba3-11e6-8f3e-cf8a0939742b.PNG)

**Comment by SteveSandersonMS** [comment]
Thanks for reporting this! Now fixed.
