### ISSUE TITLE
MSBUILD : error MSB4025: The project file could not be loaded. Data at the root level is invalid. Line 1, position 1. 

### ISSUE THREAD

**Issue by ranbuch** [aspnet/JavaScriptServices#495]
I'm getting this error:
```
Build FAILED.
       "c:\Users\ranbu\Documents\dev\creators3d-dot-net-core\project.json" (Build target) (1) ->
         MSBUILD : error MSB4025: The project file could not be loaded. Data at the root level is invalid. Line 1, position 1. [c:\Users\ranbu\Documents\dev\creators3d-dot-net-core\project.json]
    0 Warning(s)
    1 Error(s)
```

I think it's not working since I've installed Visual Studio 2017 RC but I'm still using VS Code.

(I haven't migrated my project to Visual Studio 2017)

**Comment by SteveSandersonMS** [comment]
If you've installed VS2017RC, then your machine now has .NET Core Tools Preview 3 on it. That's not compatible with `project.json`-based projects such as yours.

There's an easy solution though :) Just add a file called `global.json` at the root of your project containing this:

```
{
  "sdk": { "version": "1.0.0-preview2-1-003177" }
}
```

Now the build system will know to build it using the Preview 2 tools.

**Comment by ranbuch** [comment]
I already have a ```global.json``` file and he looks like this:
```
{
  "sdk": { "version": "1.0.0-preview2-003121" }
}
```
I've tried to change it to what you've suggested but I'm still getting the same error.

**Comment by MarkPieszak** [comment]
Do you have that version of .NET Core tools (preview2) installed on your machine as well? @ranbuch

**Comment by ranbuch** [comment]
```
C:\Users\ranbu>dotnet --info
.NET Command Line Tools (1.0.0-preview3-004056)

Product Information:
 Version:            1.0.0-preview3-004056
 Commit SHA-1 hash:  ccc4968bc3

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
```

How can I know if I have preview2 as well? I probably use to have . . .

**Comment by ranbuch** [comment]
Downloaded preview2 from here: [https://www.microsoft.com/net/core#windowsvs2015](url)

and installed it but ```dotnet --info``` still returns preview3 version.

**Comment by MarkPieszak** [comment]
Can you try installing the "Current" SDK ?  https://www.microsoft.com/net/download/core#/current

**Comment by ranbuch** [comment]
That's what I've installed again, The link that you shared here is preview2.

**Comment by ranbuch** [comment]
@SteveSandersonMS  can you please re-open this issue?

**Comment by SteveSandersonMS** [comment]
@ranbuch It doesn't seem like an issue in any JavaScriptServices code, so it's not like we can change anything in this repo to fix it. It only appears that you don't have the correct SDK installed. Please check `c:\Program Files\dotnet\sdk` and verify you have installed the 1.1 SDK whose version matches your `global.json` file.

If you are able to repro the issue in a way that points to it being specific to JavaScriptServices, please do let us know. For example, if you can take your failing project, strip out the JavaScriptServices code, and it starts working (without changing `global.json` or which SDKs are installed), that would imply there's an issue in this repo.

**Comment by ranbuch** [comment]
Understood, Thank you @SteveSandersonMS

**Comment by antmdvs** [comment]
@ranbuch

> `dotnet --info` still returns preview3 version

Try running that from the folder that contains global.json. In the absence of a global.json, I believe the CLI always resolves to the subfolder of %PROGRAMFILES%\dotnet\sdk that represents the greatest semver version.

**Comment by miyelo** [comment]
hi, the solution for me was uninstall preview3 from the programs list

**Comment by ranbuch** [comment]
Thank you @miyelo

**Comment by Tiger333** [comment]
@miyelo  thanks - also solved the problem for me

**Comment by kiranjulapalli** [comment]
Thanks @miyelo

**Comment by kiranj321** [comment]
thanks @miyelo

**Comment by AbhimanyuAryan** [comment]
@ranbuch I had Visual Studio 2017 installed on my mac. I removed it from applications directory. But I am still confused what version of dotnet to install that would support project.json & that docs.microsoft.com are following

**Comment by ranbuch** [comment]
Hi @AbhimanyuAryan ,
As already written above, go to ```c:\Program Files\dotnet\sdk``` and check what's the exact ```preview2``` version you have installed on your machine (Ignore the ```preview3``` version).
Then match it on your ```global.json``` file.

**Comment by AbhimanyuAryan** [comment]
What's in the local I should check in case of OSX?

**Comment by thesmallbang** [comment]
I believe the new version does not support the global.json so it is being ignored if you have installed preview3

**Comment by AbhimanyuAryan** [comment]
@thesmallbang I have 1.0.0-rc4-004771

**Comment by summoncse** [comment]
Restore using command prompt, it works for me.

**Comment by joeseggie** [comment]
Added the global.json file and it worked for me.

**Comment by trivli** [comment]
I had if not excatly the same problem, but similar. To get a more specific error, I built the solution using msbuild from command line:

msbuild Data.sln /t:Build /p:RunOctoPack=true

Instead of just:
error MSB4025: The project file could not be loaded. Data at the root level is invalid. Line 1, position 1.

I got (something like this):
The solution file contain a reference to a project with Guid xxxxxx, but no such project was found.

Found the solution here: 
https://therightjoin.wordpress.com/2014/07/04/msb4025-the-project-file-could-not-be-loaded-data-at-the-root-level-is-invalid-error-when-building-ssdt-project-in-teamcity/

**Comment by per3ian** [comment]
@summoncse Thank you. it works!

**Comment by per3ian** [comment]
@summoncse Thank you, it works for me!

**Comment by Matticusau** [comment]
I know this is closed but just a point as I came across with my repo. In my case I am building my website from a subdirectory of the repo. The **global.json must exist in the root of the repo**, not the site to be built.

**Comment by engwalid2007** [comment]
Hey
@ranbuch had you fixed this issue?

**Comment by ranbuch** [comment]
For me the issue has been resolved.
I still have to refresh the page after every code change or I'm getting:
```
Error in :0:0 caused by: The selector "app" did not match any elements
```
Is there some way to better adjust the project after migration?

**Comment by joepadz** [comment]
it works just run  "dotnet restore" under package manager console. 👍

**Comment by anandtpatel** [comment]
Thanks @joepadz 

It fixed my issue

run "dotnet restore" under package manager console.

**Comment by xiankaylle019** [comment]
Deleting the .targets, .cache, .props, . q.targets file in obj folder and run dotnet restore works for me.

**Comment by gauravjoshi18** [comment]
I solve the same problem in my project by

Tools -> NuGet Package Manager -> Package Manager Console
Select required project from 'Default Project' list
Run the command "dotnet restore" on Package Manager Console
Rebuild the your project again this will solve your problem
