### ISSUE TITLE
Support in-process hosting via Edge.js

### ISSUE THREAD

**Issue by SteveSandersonMS** [aspnet/JavaScriptServices#5]
Blocked waiting for https://github.com/tjanczuk/edge/issues/279

**Comment by SteveSandersonMS** [comment]
I'm not sure whether https://github.com/tjanczuk/edge/issues/279 will at some point be implemented, but it's not totally clear how much it would be needed anyway.

We now have the per-request overhead down to about 0.3ms with cross-process calls. There are requests for many other features, but perf hasn't been a strongly felt issue.

So I'll close this, but if https://github.com/tjanczuk/edge/issues/279 does get implemented in the future and there are demands to reduce that 0.3ms overhead, we can reopen!

**Comment by hiyelbaz** [comment]
EdgeJS provides much better results (~0.04ms). Let's keep eyes on it.
