### ISSUE TITLE
Webpack Includes Tests in Production Build

### ISSUE THREAD

**Issue by nicwillemse** [aspnet/JavaScriptServices#501]
In the current setup it looks as if the webpack configuration is including the JS specs as part of the production build.

**Comment by SteveSandersonMS** [comment]
Does it really include them? I just tried `webpack --env.prod` and looked at the resulting `wwwroot/dist/main-client.js`. Ctrl+F for "karma" and "should" both gave zero results, so it doesn't look like any test code is in there.

If you have repro steps that cause the tests to be included in production build, can you please post them?

**Comment by nicwillemse** [comment]
Hi @SteveSandersonMS, 

I was referring to the actual tests themselves, since the webpack configuration does not seem to be excluding specs at all ?

**Comment by MarkPieszak** [comment]
@nicwillemse Do you mean that the webpack configs need the `exclude` portion for `.spec.ts` files added in there?

**Comment by SteveSandersonMS** [comment]
@nicwillemse Unless I'm missing something, the spec files don't need to be excluded. They won't be bundled with the application code, because the application code doesn't reference the specs.

**Comment by nicwillemse** [comment]
@MarkPieszak thats exactly what im saying. @SteveSandersonMS do you agree with this comment ?

**Comment by SteveSandersonMS** [comment]
No I don't - please see my previous comment for details :)

**Comment by nicwillemse** [comment]
@SteveSandersonMS - im not sure your previous comment applies, the specs will be bundled due to the webpack configuration.

**Comment by SteveSandersonMS** [comment]
Can you confirm that you're actually seeing spec code inside the built bundles in `wwwroot/dist/`?

I searched mine and didn't find any spec code in those bundles, nor would I expect to, since the specs are not referenced from the application code.
