### ISSUE TITLE
Add HMR support for Aurelia Template

### ISSUE THREAD

**Issue by ClaudioNunes** [aspnet/JavaScriptServices#502]
It's seems to me that work done  in latest aurelia official templates ( see  [this](https://github.com/aurelia/skeleton-navigation/pull/714#issuecomment-266068169) ) will make HMR support in Aurelia JavascripServices possible. (maybe server side rendering also)

**Comment by SteveSandersonMS** [comment]
Sounds great. Pull requests welcome!

I'll close this because it's not something we'll implement any time soon on our own, but if someone in the community offers a sufficiently clean and simple pull request, we can definitely try to include it.

**Comment by jozefizso** [comment]
@SteveSandersonMS Can you reopen this issue to indicate Aurelia hot module reload is not supported yet and add the **up-for-grabs** label so it is visible to community that this needs to be worked on?
