### ISSUE TITLE
IE11: Object doesn't support property or method 'assign'

### ISSUE THREAD

**Issue by LovedByTheLord** [aspnet/JavaScriptServices#504]
Similar to #386.  

The template throws the following error in Internet Explorer 11:

![image](https://cloud.githubusercontent.com/assets/17475836/21066252/3c0a48dc-be2a-11e6-8061-db2ecb3f6ece.png)

The error is coming from configureStore.ts:

![image](https://cloud.githubusercontent.com/assets/17475836/21066367/cd906214-be2a-11e6-8216-7c647820b0aa.png)

Please consider adding a polyfill to the template for this.

**Comment by SteveSandersonMS** [comment]
Thanks for reporting this!

I'll add this as a note to #484, and close this one as duplicate.

**Comment by neominky** [comment]
How to resolve this?

**Comment by SteveSandersonMS** [comment]
https://github.com/aspnet/JavaScriptServices/wiki/Supporting-Internet-Explorer-11-(or-older)
