### ISSUE TITLE
Add this repo to up-for-grabs.net

### ISSUE THREAD

**Issue by MarkPieszak** [aspnet/JavaScriptServices#51]
@SteveSandersonMS Maybe we can make some kind of hot-list so we can make it easier to get contributions from the community?

Some simpler bugs
Some easy new features
Etc.

Just an idea!

**Comment by VishalMadhvani** [comment]
I found this site when I wanted to get involved in open source.
So maybe listing it on here? http://up-for-grabs.net/#/tags/.NET

**Comment by jFensch** [comment]
I really appreciated the demonstration on the ASP.NET Community Standup and I'm excited about the potential this project holds to help reduce fatigue around new project setup.  Anything to facilitate community involvement and contributions would be welcome.

**Comment by SteveSandersonMS** [comment]
Very good suggestions.

May I suggest that for the first item, somebody [adds this project to up-for-grabs.net](https://github.com/up-for-grabs/up-for-grabs.net#add-your-project). I've already added the tag up-for-grabs to this issue :)

**Comment by VishalMadhvani** [comment]
I've opened a pull request for this here: https://github.com/up-for-grabs/up-for-grabs.net/pull/468

**Comment by VishalMadhvani** [comment]
Done

**Comment by SteveSandersonMS** [comment]
Brilliant - thanks @VishalMadhvani!
