### ISSUE TITLE
[Angular template] ng-xi18n

### ISSUE THREAD

**Issue by hheexx** [aspnet/JavaScriptServices#511]
Can you support angular tool ng-xi18n ?
It is supposed to extract strings for internationalization to a messages.xlf file.

But it generates empty file:
```
<?xml version="1.0" encoding="UTF-8" ?>
<xliff version="1.2" xmlns="urn:oasis:names:tc:xliff:document:1.2">
  <file source-language="en" datatype="plaintext" original="ng2.template">
    <body>
    </body>
  </file>
</xliff>
```

... and a bunch of js and map files. It looks like it compiles ts files in same folder.

https://angular.io/docs/ts/latest/cookbook/i18n.html#!#ng-xi18n

**Comment by SteveSandersonMS** [comment]
I'm afraid I don't know anything about ng-xi18n. Do we need to do anything specific to support it?

If you can track down any specific changes that we'd need to support it, please let us know.

**Comment by hheexx** [comment]
I'm trying but it's not easy as there is no documentation yet.

It may require AOT as it's in compiler-cli package.

**Comment by hheexx** [comment]
This is what it does:

Compiler CLI

This program mimics the TypeScript tsc command line. It accepts a -p flag which points to a tsconfig.json file, or a directory containing one.

This CLI is intended for demos, prototyping, or for users with simple build systems that run bare tsc.

Users with a build system should expect an Angular 2 template plugin. Such a plugin would be based on the index.ts in this directory, but should share the TypeScript compiler instance with the one already used in the plugin for TypeScript typechecking and emit.


https://github.com/angular/angular/tree/master/modules/%40angular/compiler-cli

**Comment by hheexx** [comment]
Also maybe it requires Angular 2.1.0 as it was introduced with it.

**Comment by SteveSandersonMS** [comment]
Thanks for clarifying. Doesn't look like there's anything specific we need to do to support that then, besides update to Angular 2.1+ which is on the way anyway.

**Comment by hheexx** [comment]
Ok, I will recheck after update.
I hope it will be soon, I need this to work ASAP.
