### ISSUE TITLE
Unable to resolve 'Microsoft.AspNetCore.AngularServices

### ISSUE THREAD

**Issue by Jbassking** [aspnet/JavaScriptServices#514]
Hello,
I'm trying to use the Asp.Net Angular 2 template and I get the following error:
error: Unable to resolve 'Microsoft.AspNetCore.AngularServices (>= 1.0.0)' for '.NETCoreApp,Version=v1.0'.

From what I can tell I have the prerequisites installed. Any suggestions?

I'm using VS 2015 Pro

**Comment by Jbassking** [comment]
I found the issue. I had to install a different version of the .NET Core

**Comment by MikeInSwitzerland** [comment]
> I found the issue. I had to install a different version of the .NET Core

I've just installed the latest version of .Net Core, and I _do_ get this error, when simply attempting to create my first "**ASP.Net Core Angular 2 Starter Application (.Net Core)**" project in VS2015 Update 3.

I haven't even written a line of code yet, and I'm already getting "Restore failed" errors !!
