### ISSUE TITLE
Why did you remove typeName?

### ISSUE THREAD

**Issue by MistyKuu** [aspnet/JavaScriptServices#521]
Hey,
I have a quick question. I can see that on DEV branch which was updated 19 days ago you converted 

```
@typeName("REQUEST_WEATHER_FORECASTS")
class RequestWeatherForecasts extends Action {
    constructor(public startDateIndex: number) {
        super();
    }
}
```

to 

```
interface ReceiveWeatherForecastsAction {
    type: 'RECEIVE_WEATHER_FORECASTS',
    startDateIndex: number;
    forecasts: WeatherForecast[]
}
```

Is there a particular reason why don't you use typeName anymore?
I am asking because I find the previous syntax easier in case of usage.

**Comment by LovedByTheLord** [comment]
I wondered the same thing.  The main thing I don't like now is the hard coded strings in the interfaces and all over the code.  I tried replacing with a constant variable, but it didn't like a constant in the interface definition.  Is there a way to do that?

**Comment by MistyKuu** [comment]
@LovedByTheLord it's not truly string. It's a new type based on string variable. You have type checking etc. But anyway I find the previous concept easier. Was it related due to the fact that there were classes which are not serializable because of constructor?

**Comment by LovedByTheLord** [comment]
@MistyKuu I understand the new 2.0 feature; however, we now have strings in the action creators, reducers, and client-side unit tests (in my project).  I could create constants for everything but the action interfaces, but was curious if there was a better way.

**Comment by SteveSandersonMS** [comment]
@MistyKuu You can find a discussion about why we changed this here: https://github.com/aspnet/JavaScriptServices/issues/387. I also agree that the previous version was easier to use, but the community more widely decided that it wasn't standard enough.

You can continue using `redux-typed` if you like it in your project. But please note we won't be releasing any further updates to `redux-typed`, so if you want to keep it going as a project, please consider forking and maintaining your own version of that NPM package. Sorry for the inconvenience!

**Comment by MistyKuu** [comment]
@SteveSandersonMS thanks Steve for clarification. I decided to use redux-typed 'provide' but for actions I'll go for a different library.
