### ISSUE TITLE
Getting error C:\Program Files\dotnet\sdk\1.0.0-preview3-004056\Extensions\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Props

### ISSUE THREAD

**Issue by JByfordRew** [aspnet/JavaScriptServices#522]
I am following the simple instructions from the readme using the yo builder. Happens for Aurelia and Angular2 so far, probably others.

**Comment by JByfordRew** [comment]
sorry where the file in this issue title is not found

**Comment by knunery** [comment]
I am getting the same error. I don't have a v14.0 folder locally but I do have a v15.0 folder.

**Comment by SteveSandersonMS** [comment]
This error means you don't have the necessary version of .NET Core tools installed. Be sure to install .NET Core 1.1.0 (and not just some later version, e.g., as bundled with VS 2017RC). Also if you're on an old version of `generator-aspnetcorespa`, please update. Current versions emit projects with a `global.json` file that tells the .NET tooling which version needs to be used.

Note that if you want to use VS2017RC, then you *must* use csproj-based tooling, not xproj/project.json. The latest `generator-aspnetcorespa` package gives you the choice of which tooling type you want to use when creating new projects.
