### ISSUE TITLE
Published JS File Sizes and Pre Rendering Speed

### ISSUE THREAD

**Issue by NeilIrvingMacc** [aspnet/JavaScriptServices#528]
Hi Guys

I have been trying to make my website to load quicker on the initial load where user visits for the first time, I have got this to between 4-9 seconds where 9 seconds is on slow smartphones.  After that other routes load in under a second and if I revisit the website it loads in under 2 seconds.  I have even put a loading message up that changes every 2 seconds!

I messed with the webpack.config.vendor file as shown below and got vendor.js down to 800k and main-client.js down to 300k on a prod build

Just wondering why it still takes a while to load as I only have 12 routes and 9 of them are lazy loaded and I am using caching and compression on the server.

Is there anything else I can do or do I have to wait for WebPack v2 for tree shaking and AOT?

Thanks

Neil

vendor: [
            //'@angular/common',
            //'@angular/compiler',
            //'@angular/core',
            //'@angular/http',
            //'@angular/platform-browser',
            //'@angular/platform-browser-dynamic',
            //'@angular/router',
            //'@angular/platform-server',
            'angular2-universal',
            'angular2-universal-polyfills',
            'bootstrap',
            'bootstrap/dist/css/bootstrap.css',            
            //'es6-shim',
            //'es6-promise',
            'jquery',
            //'zone.js',
            'es6-promise-loader'
        ]

**Comment by SteveSandersonMS** [comment]
To diagnose this further, I'd suggest trying to break down that time to identify what phases are consuming it. The startup process is roughly like this:

 1. **Server side**: (First visitor only) Start up .NET process and ASP.NET application
 2. **Server side**: (First visitor only, with older templates only) Run Webpack to produce server-side `.js` code for prerendering
 3. **Server side**: Run ASP.NET code and server-side prerendering
 4. **Client side**: Display initial (server-rendered) HTML
 5. **Client side**: Parse JS bundles
 6. **Client side**: Execute application on the client; re-render the resulting HTML

You can work out what time is spent in each of these phases by considering things like the difference between first-visitor and subsequent-visitors (that accounts for phases 1 and 2), and by using the dev tools in your browser to work out how long is spent in phases 1-3, and in 4, 5, and 6.

If you do this and find that some phase seems disproportionately expensive, please let us know!
