### ISSUE TITLE
Remove tsd - update to typings

### ISSUE THREAD

**Issue by MarkPieszak** [aspnet/JavaScriptServices#53]
To do: Update sample projects to use `typings` not deprecated `tsd`.
Also update TS to 1.8+

**Comment by emzero** [comment]
+1

**Comment by MarkPieszak** [comment]
I'll start working on this one this week, sorry for the delay

**Comment by SteveSandersonMS** [comment]
Do you think this is still worth doing? The TypeScript people have announced that, as of v2.0, TypeScript will have native support for acquiring .d.ts files directly from NPM, under the `@types` namespace that they will be managing. This will supersede the use of tsd/typings.

I don't know how soon that's going to ship, but unless the use of `tsd` is really problematic for anyone in the short-term, we might decide it's a better use of our resources to leave things as-is until TypeScript v2 ships.

**Comment by SteveSandersonMS** [comment]
Oh, for more information about this, see https://blogs.msdn.microsoft.com/typescript/2016/06/15/the-future-of-declaration-files/

**Comment by MarkPieszak** [comment]
I was actually about to comment on this last night about that! You read my mind :)
It's up to you! Switching from `tsd` to `typings` is real easy as well.

Very excited for @types... being able to have all those dependencies listened in the package.json will make so much simpler.

Should I close this one out or rename the title?

**Comment by SteveSandersonMS** [comment]
I'll close this. We can pick up the @types stuff when TypeScript 2 ships - there's nothing for us to do until then. Thanks for your input!
