### ISSUE TITLE
Error in aurelia app in IE11

### ISSUE THREAD

**Issue by waldimen** [aspnet/JavaScriptServices#531]
I created new aurelia application it works on chrome and Microsoft Edge but on IE11 it get error in console:
"'Promise' is undefined"

Should it work in IE 11 ?

**Comment by beatsm** [comment]
@waldimen - Have you fixed this yet?

Have you tried ensuring that you have: 

1. `"webpack": "2.1.0-beta.24"` in your package.json
2. `new webpack.ProvidePlugin({ Promise: 'bluebird' }),` in your webpack.config.js
3. `new webpack.ProvidePlugin({ Promise: 'bluebird', $: 'jquery', jQuery: 'jquery' }),` in your webpack.config.vendor.js
4. `entry: {
        vendor: [
            'bluebird', .....` in your webpack.config.vendor.js

You will probably need a fetch polyfill also for the fetchdata view.

Might be worth clearing your temp files and running the two following commands:
webpack --config webpack.config.vendor.js
webpack

Regards
Mike

**Comment by waldimen** [comment]
Thanks Mike,

It worked perfectly.

I am closing the issue
