### ISSUE TITLE
Deploy on Azure fails error MSB4019

### ISSUE THREAD

**Issue by psaussure** [aspnet/JavaScriptServices#538]
## Bug on Azure Deploy
*Just created a new project, let dependencies update then, via GIT method, tried to deploy on Azure. An error occurs.*

Following: http://blog.stevensanderson.com/2016/10/04/angular2-template-for-visual-studio/#publishing-to-azure

### Install all required VS2015 packages:
- Core 1.0.1
- npm and node last versions
- VS2015 Update 3
- Typescript for VS
- Install ASP.NET Core Template Pack extension

- Local `dotnet --version ->
1.0.0-preview2-003131`
- Local node version: `7.2.1`

### Create and run the project in VS2015
- Create new project -> "ASP.NET Core Angular2 Starter Application" > C:\Angular2Application1
- I don't modify anything
- `git init` in "C:\Angular2Application1\Angular2Application1" (not at root level where sln file is, but where package.json and project.json are)

- **Run the App in VS2015**: **works perfectly**

- first `git commit`

### Setup Azure Web App
![nodeversion](https://cloud.githubusercontent.com/assets/24230585/21456476/547ad252-c8f6-11e6-9872-69ebc17b8f72.PNG)
- Deployement option set to `local git`
- `git remote add azure https://azurewebap-git-repo-url`
- `git push azure master`

## On Push to Azure, Error summary
```D:\home\site\repository\Angular2Application1.xproj(8,3): error MSB4019: The imported project "D:\Program Files (x86)\dotnet\sdk\1.0.0-preview3-004056\Extensions\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.```

## On push to Azure, log
```
remote: D:\home\site\repository\project.json
remote: Restore completed in 67974ms.
remote:
remote: NuGet Config files used:
remote:     C:\DWASFiles\Sites\#1myapp14446564\AppData\NuGet\NuGet.Config
remote:
remote: Feeds used:
remote:     https://api.nuget.org/v3/index.json
remote:
remote: Installed:
remote:     212 package(s) to D:\home\site\repository\project.json
remote: Microsoft (R) Build Engine version 15.1.0.0
remote: Copyright (C) Microsoft Corporation. All rights reserved.
remote:
remote: Build started 12/23/2016 3:10:38 PM.
remote:      1>Project "D:\home\site\repository\Angular2Application1.xproj" on node 1 (Publish target(s)).
remote:      1>D:\home\site\repository\Angular2Application1.xproj(8,3): error MSB4019: The imported project "D:\Program Files (x86)\dotnet\sdk\1.0.0-preview3-004056\Extensions\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
remote:      1>Done Building Project "D:\home\site\repository\Angular2Application1.xproj" (Publish target(s)) -- FAILED.
remote:
remote: Build FAILED.
remote:
remote:        "D:\home\site\repository\Angular2Application1.xproj" (Publish target) (1) ->
remote:          D:\home\site\repository\Angular2Application1.xproj(8,3): error MSB4019: The imported project "D:\Program Files (x86)\dotnet\sdk\1.0.0-preview3-004056\Extensions\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
remote:
remote:     0 Warning(s)
remote:     1 Error(s)
remote:
remote: Time Elapsed 00:00:00.39
remote: Failed exitCode=1, command=dotnet publish "Angular2Application1.xproj" --output "D:\local\Temp\8d42b45add7eef8" --configuration Release
remote: An error has occurred during web site deployment.
remote:
remote: Error - Changes committed to remote repository but deployment to website failed.
```

More complete log Here: [PasteBin](http://pastebin.com/gRnxsQhs)

## Local console
```
dotnet --version
D:\home\site\wwwroot
1.0.0-preview3-004056
```

Do you know why build fails?

**Comment by psaussure** [comment]
Tried the global.json method of course:
```
{
    "projects": [],
    "sdk": { "version": "1.0.0-preview2-003131" }
}
```

Then another error occurs:
```
remote: Updating branch 'master'.
remote: Updating submodules.
remote: Preparing deployment for commit id '7877ff34a9'.
remote: Generating deployment script.
remote: Running deployment command...
remote: Handling ASP.NET Core Web Application deployment.
remote: Restoring packages for D:\home\site\repository\project.json...
remote:   CACHE https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore.angularservices/index.json
remote:   CACHE https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore.angularservices/1.0.0-beta-000021/microsoft.aspnetcore.angularservices.1.0.0-beta-000021.nupkg
remote: Restoring packages for tool 'Microsoft.AspNetCore.Razor.Tools' in D:\home\site\repository\project.json...
remote: Restoring packages for tool 'Microsoft.AspNetCore.Server.IISIntegration.Tools' in D:\home\site\repository\project.json...
remote: Restoring packages for tool 'Microsoft.DotNet.Watcher.Tools' in D:\home\site\repository\project.json...
remote: Committing restore...
remote: Lock file has not changed. Skipping lock file write. Path: D:\home\site\repository\project.lock.json
remote: D:\home\site\repository\project.json
remote: Restore completed in 5426ms.
remote:
remote: NuGet Config files used:
remote:     C:\DWASFiles\Sites\#1myapp14446564\AppData\NuGet\NuGet.Config
remote:
remote: Feeds used:
remote:     https://api.nuget.org/v3/index.json
remote: 'Angular2Application1.xproj' does not contain a project.json file
remote: Failed exitCode=1, command=dotnet publish "Angular2Application1.xproj" --output "D:\local\Temp\8d42b497bccf2b0" --configuration Release
remote: An error has occurred during web site deployment.
remote:
remote: Error - Changes committed to remote repository but deployment to website failed.
```

**Comment by parys** [comment]
> 'Angular2Application1.xproj' does not contain a project.json file

This message reminds me that MS want to restore using cproj files instead of using project.json. And you downloaded new version, that doesn't contain json file. But changed version to old preview2 that uses project.json.  It's just my assumption based on error message.

**Comment by psaussure** [comment]
I just created the project using the VS2015 extension ASP.NET Core Template Pack extension for Angular2 Core app. Is this installed version of project messed?

**Comment by parys** [comment]
> 'Angular2Application1.xproj' does not contain a project.json file

This message reminds me that MS want to restore using cproj files instead of using project.json. And you downloaded new version, that doesn't contain json file. But changed version to old preview2 that uses project.json.  It's just my assumption based on error message. Sorry for dalying comment.

**Comment by parys** [comment]
Oh, I think I understood the problem. You trying to use template that has already build on new version of dotnet and creates project for it without project.json. As a workaround I propose to create it manually and filled or jsut install preview dotnet(that contains preview3 like template)

**Comment by psaussure** [comment]
Any way to use the new dotnet version could be interesting to find

**Comment by parys** [comment]
I think yes. Because MS wants to revert project.json to cproj. And starting new project better in new environment. That's helps you to avoid migration things. That's my point of view.

**Comment by psaussure** [comment]
Ok so how can i fix my deployment error using the new template?

**Comment by psaussure** [comment]
Side Note: on my first try (using the template): **web deploy from VS2015 works**. I was able to publish without problem. When using CI or git, the error occurs.

**Comment by SteveSandersonMS** [comment]
The error says you don't have a `project.json`. Can you check whether `project.json` is really getting deployed? You can use the debug console from the Azure portal to see what files are on your server.

An alternative would be to use `csproj` tooling. With the latest `generator-aspnetcore-spa` Yeoman package, you can have it produce `csproj` projects (compatible with VS 2017RC) that should not have any such issue.

**Comment by arebelong** [comment]
I experience the same issue and get this error. Any ideas as to how to fix this issue?  

remote: myproj.xproj' does not contain a project.json file
remote: Failed exitCode=1, command=dotnet publish "myproj.xproj" --output "D:\local\Temp\8d4359db44a3711" --configuration Release
remote: An error has occurred during web site deployment.

Site note I tried to change type of project to csproj and then I can deploy but the site returns this error instead. I will create a seperate issue regarding this. 

_An error occurred while processing your request._

Any help would be greatly appriciated.

**Comment by arebelong** [comment]
I found the solution the error regarding 
_remote: myproj.xproj' does not contain a project.json file_

Simply delete the file :)

**Comment by SteveSandersonMS** [comment]
> Simply delete the file :)

Yes, that does work! Also, for anyone who wants to keep the `.xproj` file, another solution is to add a file at the root of your project called `.deployment`, containing this:

    [config]
    SCM_SCRIPT_GENERATOR_ARGS=--aspNetCore project.json

Then Azure will know you want to use the `project.json` file and it will ignore the `.xproj`.

I'm adding this `.deployment` file to the templates now.

**Comment by arebelong** [comment]
Thank you for a quick response :) I have just verified it to be working. Have a nice day.

**Comment by ajs-clarity** [comment]
Just for anyone else who might have the added dimension of an azure-cli generated deploy.cmd/sh I had to amend the line: 

`call :ExecuteCmd dotnet publish ".\src\MyWebApplication\MyWebApplication.xproj" --output "%DEPLOYMENT_TEMP%" --configuration Release` 

to target the project.json file:

`call :ExecuteCmd dotnet publish ".\src\MyWebApplication\project.json" --output "%DEPLOYMENT_TEMP%" --configuration Release`
