### ISSUE TITLE
Error with @angular/material: "2.0.0-beta.1"

### ISSUE THREAD

**Issue by sjahongir** [aspnet/JavaScriptServices#540]
I want to use `@angular/material: "2.0.0-beta.1".` But when I install this package occured following error:

`+-- UNMET PEER DEPENDENCY @angular/common@2.0.2
+-- @angular/compiler@2.0.2
+-- UNMET PEER DEPENDENCY @angular/core@2.0.2
+-- @angular/forms@2.0.2
`-- UNMET PEER DEPENDENCY @angular/http@2.0.2

npm WARN @angular/material@2.0.0-beta.1 requires a peer of @angular/core@^2.2.0 but none was installed.
npm WARN @angular/material@2.0.0-beta.1 requires a peer of @angular/common@^2.2.0 but none was installed.
npm WARN @angular/material@2.0.0-beta.1 requires a peer of @angular/http@^2.2.0 but none was installed.`

**Comment by SteveSandersonMS** [comment]
> npm WARN @angular/material@2.0.0-beta.1 requires a peer of @angular/core@^2.2.0 but none was installed.

That message is saying you need to use Angular 2.2.0. You'll need to update all your Angular dependencies to 2.2.0. I don't know how easy that is right now, but we'll be updating the core templates to Angular 2.x (latest) in the next few weeks I hope. @MarkPieszak, do you have any knowledge of how easy/hard it will be for us to update our templates to the latest Angular 2.x?

**Comment by MarkPieszak** [comment]
The problem at the moment is that even with some workarounds it is tough to get past 2.2.x+ (if you're using Universal). So Material can be used, but for the time being SSR should be disabled. Now that people are returning from vacations etc soon, we should be merging some core components of universal int angular Core itself, sure we'll have some big performance boosts from that as well ! 👍😎 

The timeframe will be most likely 4.x for that piece.

Maybe for now we can make a note pointing some of this out in the docs?
I'll be trying to push for a newer release of Universal in between all of that, so we can at least let people use the latest & greatest without workarounds! I'll make sure you ping you when we get something, can help make a PR to upgrade. Should be effortless once we update things on our end though. 
@SteveSandersonMS
