### ISSUE TITLE
can I use library ng2-bootstrap in  your template?

### ISSUE THREAD

**Issue by sergeu90** [aspnet/JavaScriptServices#542]
I am installing library and I am getting 

`+-- UNMET PEER DEPENDENCY @angular/common@2.0.2
+-- UNMET PEER DEPENDENCY @angular/compiler@2.0.2
+-- UNMET PEER DEPENDENCY @angular/core@2.0.2
+-- UNMET PEER DEPENDENCY @angular/forms@2.0.2
`-- ng2-bootstrap@1.1.16-9

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.15: wanted {"os":"darwin","arch":"a
ny"} (current: {"os":"win32","arch":"x64"})
npm WARN angular2-google-maps@0.17.0 requires a peer of @angular/common@^2.3.1 but none was installed.
npm WARN angular2-google-maps@0.17.0 requires a peer of @angular/core@^2.3.1 but none was installed.
npm WARN angular2-in-memory-web-api@0.0.20 requires a peer of reflect-metadata@^0.1.3 but none was installed.
npm WARN ng2-bootstrap@1.1.16-9 requires a peer of @angular/common@^2.3.1 but none was installed.
npm WARN ng2-bootstrap@1.1.16-9 requires a peer of @angular/compiler@^2.3.1 but none was installed.
npm WARN ng2-bootstrap@1.1.16-9 requires a peer of @angular/core@^2.3.1 but none was installed.
npm WARN ng2-bootstrap@1.1.16-9 requires a peer of @angular/forms@^2.3.1 but none was installed.
npm WARN Angular2Spa@0.0.0 No description
npm WARN Angular2Spa@0.0.0 No repository field.
npm WARN Angular2Spa@0.0.0 No license field.`

**Comment by MarkPieszak** [comment]
Are you importing the FormsModule and adding it in your NgModule as well? As I have [here](https://github.com/MarkPieszak/aspnetcore-angular2-universal/blob/master/Client/app/shared-module/base.shared.module.ts#L18)

**Comment by sergeu90** [comment]
Yes,I solved the problem

**Comment by rahmajiji** [comment]
@sergeu90 how did u fix it ? i have the same error, any help please ?
