### ISSUE TITLE
Difficuluties during installation to VS 2017 RC project

### ISSUE THREAD

**Issue by rpokrovskij** [aspnet/JavaScriptServices#543]
Create such project - great idea, should be very useful for new "npm users". Thank you. But it is still very hard to understand how it suppose to work.

Could you append documentation or just consult us there with those topics?

1) Is it possible to get JavaScriptServices project with Target Framework not "Core" but ".NET Framework 4.6.2"? 
    a) the way "Installation into existing projects" through nuget "Microsoft.AspNetCore.SpaServices" ?
    b) the yoman way  ?
    c) since I can't just switch Target Framework in "Project Properties" (it suggests to change core 1.1 to 1.0 core) may be you can document how it can be safely changed through json files (I know about project.json "frameworks" property, but now I even not sure that project.json suppose to work with new csproj... also I have changed it to "net462"; dotnet restore works but "Project properties" still show "Core" target framework)?

2) please add some sentence how to check that project is ready (after nuget or yoman install).
I have a new node_modules folder in project folder with all packages including webpack. But what aslo should be done by yoman script? Even several words will be very useful to describe what should going on.

3a) add to the documentation line that warnings user that he will need to delete .xproj file after migration to .csproj (otherwise dotnet run deny to work).

3b) dotnet run return an error (after first run one, after second another)
```
PM> dotnet run
dotnet : The specified framework 'Microsoft.NETCore.App', version '1.1.0' was not found.
At line:1 char:1
+ dotnet run
+ ~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (The specified f... was not found.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 

  - Check application dependencies and target a framework version installed at:
      C:\Program Files\dotnet\shared\Microsoft.NETCore.App
  - The following versions are installed:
      1.0.0
      1.0.1
  - Alternatively, install the framework version '1.1.0'.

PM> dotnet run
dotnet : A fatal error was encountered. The library 'hostpolicy.dll' required to execute the application was not found in 
'D:\cot\Vse\AdminkaV1\Web.Client\bin\Debug\netcoreapp1.1'.
At line:1 char:1
+ dotnet run
+ ~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (A fatal error w...netcoreapp1.1'.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
```

Run through visual studio "IIS Express" returns modal error message box "**Unable to run your project. The 'RunCommand' property is not defined.**"

What is wrong?

**Info:**

PM> dotnet --version
1.0.0-preview4-004233
PM> npm -v
3.10.10

**Comment by SteveSandersonMS** [comment]
1. Yes, it works with .NET Framework as well as .NET Core (but only with ASP.NET Core, which itself works on both .NET Framework and .NET Core). There's documentation about how to add the NuGet packages and use them in existing projects here: https://github.com/aspnet/JavaScriptServices/blob/dev/src/Microsoft.AspNetCore.SpaServices/README.md#installation-into-existing-projects

2. Sorry, I'm not sure what you mean by that. Perhaps you are unfamiliar with Yeoman. Note that Yeoman is only used when creating *new* projects. Don't use Yeoman with existing projects - please follow the docs linked above for that.

3a. I understand your point, but I don't know where such documentation would go, since this project doesn't address anything about migrating from xproj to csproj - it's a separate concern entirely. Also one that will disappear soon as people will no longer be on xproj.

3b. It's saying you need to install .NET Core 1.1.0. You can get it from https://www.microsoft.com/net/download/core#/current

Hope that helps!

**Comment by rpokrovskij** [comment]
```
Q: Is it possible to get JavaScriptServices project with Target Framework not "Core" but ".NET Framework 4.6.2"?
A: There's documentation about how to add the NuGet packages ...
```
In document you point there are no explanation what is `.NETCoreApp` target framework. There is no "word" target at all.
When I have realized that this is a new sort of proxy for "core" and "framework" targets (like  "standard" ?) Only then I was able to get more information from there:
https://jonhilton.net/2016/09/07/using-asp-net-core-against-net-4-6/
But it was wroted before VS 2017 RC. Is it still relevant?

```
Q: user ... will need to delete .xproj
A:  Also one that will disappear soon as people will no longer be on xproj.
```

How it can dissapear if yoman generates exactly xproj?

P.S. I can't understand why all Core teams are so quick in closing issues...  It looks like "race for nice stats". I have never have such filling with other github projects. Can I use the same topic to continue asking if I still have questions.

**Comment by SteveSandersonMS** [comment]
> How it can disappear soon if yoman generates xproj+json ?

As of the latest version of generator-aspnetcore-spa, you get the choice of whether to generate xproj+json or simply csproj. People using VS2017 should choose csproj.

> I'm asking to provide documentation what should be generated . How the generation result should look in file system (xproj? csproj?)

The choice between xproj and csproj is up to you. People using VS2017 should choose csproj.

> The link you provide is assisting to install VS RC 2017,

From the link I provided, please download and install the Windows version of .NET Core 1.1 SDK (not the VS2017 tools - sorry for the ambiguity).

> P.S. I can't understand why all Core teams are so quick in closing issues... It looks like "race for nice stats"

We don't have any such stats that I'm aware of. Issues are only closed if it no longer appears that there's action to take on them. This is to keep focus on issues where there is action to take. You can certainly continue on the same topic to ask further questions even if it's closed :)

**Comment by rpokrovskij** [comment]
> The choice between xproj and csproj is up to you. People using VS2017 should choose csproj.
Today update of generator-aspnetcore-spa helped me. Thank you.

But I still can't understand how to configure .NETCoreApp target to use exactly .NET Framework 4.6.2 ?
What should be changed instead of project.json in previous versions? I feel that is not SpaServices question, but may be you still can help me or point where to read? It is not obvious.
