### ISSUE TITLE
HMR don't work with HTTPS

### ISSUE THREAD

**Issue by sunliil** [aspnet/JavaScriptServices#547]
I'm developing .net core web app with angular 2 and used template for .net core+angular2+webpack with HMR. And there is HMR error when I running app on https://localhost;xxxx/, it tells that https can't call http resources.
Is it possible to run HMR on HTTPS too?

**Comment by MarkPieszak** [comment]
Check previous issue here: https://github.com/aspnet/JavaScriptServices/issues/450#issuecomment-261912505
