### ISSUE TITLE
Cannot debug Angular 2's *.ts file on ASP.NET Core Template Pack

### ISSUE THREAD

**Issue by Sampath-Lokuge** [aspnet/JavaScriptServices#549]
Hi,

Why I cannot debug Angular 2's *.ts file on chrome dev tools ?

Source window as shown below.But unable to find out the `webpack://` folder.Can you tell me why ? I need to find out the location of *.ts files.How can I do that ? This is running on debug mode with VS 2015 community edition.

**Chrome browser's Version : 55.0.2883.87 m**  

**tsconfig.json**

```
{
  "compilerOptions": {
   "moduleResolution": "node",
    "target": "es5",
    "sourceMap": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "skipDefaultLibCheck": true,
    "lib": [ "es6", "dom" ],
    "types": [ "node" ]
  },
  "exclude": [ "bin", "node_modules" ],
  "atom": { "rewriteTsconfig": false }
}
```

![Alt Text](https://i.stack.imgur.com/G0axe.jpg)

**Comment by SteveSandersonMS** [comment]
There's a debugging guide here: https://github.com/aspnet/JavaScriptServices/blob/dev/src/Microsoft.AspNetCore.SpaServices/README.md#debugging-your-projects

If following that guide doesn't work for you, could you please post repro steps saying what you did and at what point something doesn't work?

**Comment by Sampath-Lokuge** [comment]
Hi,

It seems to be a Chrome browser's issue (Version 55.0.2883.87 m ) .It's working fine on the Canary (Version 57.0.2969.0 canary (64-bit)). Thanks.
