### ISSUE TITLE
Dockerfile: The specified framework 'Microsoft.NETCore.App', version '1.1.0' was not found.

### ISSUE THREAD

**Issue by anmolmahatpurkar** [aspnet/JavaScriptServices#550]
The Dockerfile is using the microsoft/dotnet:1.0.0-preview2-onbuild version because of which building the project using docker, fails right now.

**Comment by SteveSandersonMS** [comment]
The dockerfiles have been updated to use `microsoft/dotnet:1.1.0-sdk-projectjson`, e.g., https://github.com/aspnet/JavaScriptServices/blob/dev/templates/Angular2Spa/Dockerfile

Let us know if that isn't working!
