### ISSUE TITLE
yoman error during installation "The imported project was not found"...

### ISSUE THREAD

**Issue by rpokrovskij** [aspnet/JavaScriptServices#551]
**To repeat**
1. Open VS 2017 RC , create test solution (creating class lib project)
2. Open console, go to the solution folder create folder  for test JavaScriptServices folder e.g. "TestJavaScriptServices " go to it.
3. Run `yo aspnetcore-spa` choose "react + redux" (as it is described in http://blog.stevensanderson.com/2016/05/02/angular2-react-knockout-apps-on-aspnet-core/)

**Expected result:** 

yoman works without errors

**Observerd result**
yoman error:

![image](https://cloud.githubusercontent.com/assets/11598038/21589317/3c4b1f38-d0f9-11e6-8fb9-407ee63251ed.png)

Other info:
```
npn -v 
3.10.10
dotnet --version
1.0.0-preview4-004233


```

**Comment by SteveSandersonMS** [comment]
Two possible reasons for this:

 * You haven't got .NET Core 1.1.0 SDK installed. This is required, even if you also have VS2017RC installed.
 * Or, you're using an old version of generator-aspnetcore-spa. Old versions don't produce `global.json` files, but those files are needed to specify which SDK version to use.

So please check you have installed .NET Core 1.1.0 SDK (not only older or newer versions). Also please make sure you're on the latest `generator-aspnetcore-spa`.

If that doesn't fix it, please reopen with details. Thanks!

**Comment by rpokrovskij** [comment]
SDK installation helps.
But it sill work as not described in documentation http://blog.stevensanderson.com/2016/05/02/angular2-react-knockout-apps-on-aspnet-core/ 

1) it seems you do not need `md/cd some-empty-directory` since now yoman script manages folders in iteractive dialog.
2) after dotnet run I see those errors

![image](https://cloud.githubusercontent.com/assets/11598038/21591148/2325f0e4-d10a-11e6-820c-9f04b2f28f63.png)

**Comment by SteveSandersonMS** [comment]
Hi. It sounds like your goal is to add a SPA project into an existing VS2017RC solution. If so, here are the steps:

1. Install the latest Yeoman and generator (`npm install -g yo generator-aspnetcore-spa`)
2. In VS2017RC, create a new solution
   * File -> New -> Project
   * Expand Templates -> Other Project Types -> Visual Studio Solutions
   * Choose *Blank Solution*
   * Pick a name (e.g., `MyBlankSolution`), click OK
3. In a command prompt, change directory to where the solution is (e.g., `cd c:\Users\<youruser>\Documents\Visual Studio 2017\Projects\MyBlankSolution`)
4. Run `mkdir MyReduxProject`, then `cd MyReduxProject`, then `yo aspnetcore-spa`
5. Choose `React with Redux`, then choose `.csproj`, then accept the name `MyReduxProject`, and wait for it to restore dependencies and build the client-side files
6. Back in Visual Studio, right-click on your solution name in Solution Explorer and choose Add -> Existing Project
    * Browse to the directory containing `MyReduxProject.csproj` (e.g., `C:\Users\<youruser>\Documents\Visual Studio 2017\Projects\MyBlankSolution\MyReduxProject`)
    * Select `MyReduxProject.csproj` and click OK
7. Check you can build it by pressing Ctrl+Shift+B. There will be no build errors.
8. Run it by pressing Ctrl+F5. It will appear in a browser.

I'm not sure how what you've done is different from this. If you are following some different procedure that you believe is correct but still doesn't work, can you please post exact repro steps, starting from creating an entirely new solution in a blank directory, with the same level of detail as in the instructions above? Thanks!

**Comment by rpokrovskij** [comment]
I have did the same, only instead of Blank solution I have created new "Core project" as it was recommended after SDK installation for VS 2017 (I guess for initialization).

Going to try it with blank solution.

**Comment by rpokrovskij** [comment]
I can compile it, but can't start (Ctrl+F5 doesn't work):

![image](https://cloud.githubusercontent.com/assets/11598038/21592314/0e63a90c-d115-11e6-9a90-743d857bd96a.png)

**Comment by SteveSandersonMS** [comment]
Try restarting Visual Studio. I once had it doing that, and restarting it made the problem go away. Seems like it was a bug in VS2017 RC.

**Comment by rpokrovskij** [comment]
Restart helps. Thank you.

**Comment by rpokrovskij** [comment]
When I move moved folder "MyReduxProject" (with all content) to subfolder: e.g. webapps\MyReduxProject application stop worked. Message box which points to error in tmp folder:

![image](https://cloud.githubusercontent.com/assets/11598038/21595225/3d602e6e-d134-11e6-8b1f-f1d2170d5e92.png)


Please share more information about project internals! Somewhere is hidden dependencies on the folders strucure that is not declared in configuration file!

**Comment by SteveSandersonMS** [comment]
The `configuration data for the page is invalid` error is a general ASP.NET configuration/permissions issue - it's not specific to anything to do with these project templates.

To resolve it, I'd suggest a web search for that error message and looking for what you might not have configured correctly.

**Comment by rpokrovskij** [comment]
@SteveSandersonMS , please just do not think that I want to load my work on you, just give me a chance to explain:
I think every user of spaservices sees on that that this is not just "for learning purposes", not only expect that it is MS recommended way to setup SPA environment, but also expect to use it as backbone for his own projects. That means:
1) it is possible switch core to framework 
2) it is possible  to move project a) to other folder b) to other solution

Yes, to support this in documentation it is an additional work for you. You can refuse this but please  just inform on first page that it was never tested by you. 

When now you suggest just "web search" not MSDN page this means that even you do not know where it is described (some pieces somewhere in ".NET blog"). Because of permanent revolution in asp core tooling there is no docuemntation about this.

The most actual topic about switching core services is github issue https://github.com/dotnet/cli/issues/4996
Note: they suppose to drop 

And there are no topics about moving projects folders from one folder to another (except we now that this was not working in the VS 2015 and as I see doesn't work in VS 2017 RC). 

There are no other person in the world who could now better how to manage asp.core projects, because your spaservices are most complex presetup environments at a moment.

**Comment by SteveSandersonMS** [comment]
I was only saying that I don't know what the issue is because the error you've posted is a general IIS/ASP.NET one and isn't specific to anything in these templates. The 500.19 error is widely discussed online so if you search for that error message you will find plenty of advice on diagnosing and fixing it.

**Comment by rpokrovskij** [comment]
Thank you for your patience.
I have tried to create gif-video with moving to subfolder, and then rebuild/run, and on fifth or sixth attempt of recording moving to subfolder succeed.

So it somehow works. I can launch and see app in browser.
But together I see  an error in VS Error List:  MSB4131, The "FilesWritten" parameter is not supported by the "GenerateRuntimeConfigurationFiles" task. Verify the parameter exists on the task, and it is a gettable public instance property.	

![image](https://cloud.githubusercontent.com/assets/11598038/21617989/70db652a-d1f1-11e6-81c4-cd49537b1702.png)

This will never finish...
