### ISSUE TITLE
AOT in Angular Template

### ISSUE THREAD

**Issue by NeilIrvingMacc** [aspnet/JavaScriptServices#557]
Hi

Has anyone got an example or guidelines of how to do AOT compilation for a production build  / publish in the Angular2 template project?  Alternatively is this something that is going to be built into the template once Webpack v2 is released?

Thanks

Neil

**Comment by AdnanCukur** [comment]
Wondering this as well

**Comment by MarkPieszak** [comment]
Duplicate of #508 

Also apologies with the holidays been extremely busy, but I'll have an AoT setup done soon I hope! If everything goes well.

**Comment by NeilIrvingMacc** [comment]
Ok Mark thanks for the update, will it be included as an update to the template and not a fork?

**Comment by MarkPieszak** [comment]
@NeilIrvingMacc I'd imagine to the templates here, as well as my repo [here](https://github.com/MarkPieszak/aspnetcore-angular2-universal) when I can get everything thing worked out correctly.

**Comment by SteveSandersonMS** [comment]
Thanks @MarkPieszak - closing as duplicate.
