### ISSUE TITLE
An error occurred while processing your request.

### ISSUE THREAD

**Issue by arebelong** [aspnet/JavaScriptServices#558]
I have create a new SPA template using these options. 

Version: 0.7.2
  
_? Framework Angular 2
? What type of project do you want to create? .csproj      (compatible with .NET Core tooling preview 3 and Visual Stud
io 2017)
? Do you want to include unit tests? Yes
? Your project name myName_

I have then created a new app service and created a git repository which I commit the project to. The commit is fine but unfortunately I get this error. 

An error occurred while processing your _request._

I am not sure as to where to go from here? I am unable to create a VS2015 project as I experience the problems described here

https://github.com/aspnet/JavaScriptServices/issues/538

**Comment by SteveSandersonMS** [comment]
Sorry for the inconvenience. I'm putting a fix for this into the templates.

In the meantime, if you just re-publish your site **to the same Azure web service**, it may work, as it appears to be an issue that occurs only on the first time a given Kudu target is deployed to.

**Comment by SteveSandersonMS** [comment]
`generator-aspnetcore-spa` has now been updated to version 0.7.3 and includes a fix.

I've just verified that both the `project.json` and `csproj` flavours of generated projects deploy succesfully to Azure (via Git) without needing any changes or special configuration.
