### ISSUE TITLE
Error enabling routeTracing in the angular 2 template

### ISSUE THREAD

**Issue by lucamorelli** [aspnet/JavaScriptServices#559]
Hi, 
  often happens that if I add routeTracing 

```
RouterModule.forRoot([
    { path: '', redirectTo: 'home', pathMatch: 'full' },
    { path: 'home', component: HomeComponent },
...
  ], { enableTracing: true }),
```
I obtain this error message

```
Exception: Call to Node module failed with error: TypeError: console.group is not a function
at SafeSubscriber._next (D:\Sorgenti\Interno\MyCrm\src\CrmApp\ClientApp\dist\vendor.js:59646:26)

```

The strange thing is that at first worked: I added this in the appmodule, recompiled and restarted and worked showing the data in the console but nowe, after a restart of vs, I recompile, start the app and obtain this error message

**Comment by MarkPieszak** [comment]
What browser are you using? console.group might not be supported there.

**Comment by MarkPieszak** [comment]
@lucamorelli Apologies, I just realized this is happening on the Node side.

This is because Node (or any server) doesn't have a method `group` on `console`.

You can require a package like https://github.com/Rich-Harris/node-console-group and even require it only during Development mode in your boot-server, that should get things working there.

**Comment by SteveSandersonMS** [comment]
Could you report this to either the Angular or Angular Universal projects? It's an issue in one of those, depending on how you choose to think about it.

Angular's `enableTracing` relies on the JS runtime having a `console.group` function, but that's not present in Node.js, hence it failing during server-side rendering. It would be good if either Angular didn't rely on an API that isn't available everywhere, or if Angular Universal included a polyfill for it so it was compatible with Node environments.

In the short term, you might be able to reference something like this to polyfill it yourself: https://github.com/Rich-Harris/node-console-group

**Comment by SteveSandersonMS** [comment]
Ah, @MarkPieszak beat me to it :)

**Comment by MarkPieszak** [comment]
So close too! :1st_place_medal: 
😄

**Comment by lucamorelli** [comment]
thanks, just saw the reply, installed and added to the boot-server
require('console-group').install();

and now seems to work
