### ISSUE TITLE
Add Aurelia to NPM description page

### ISSUE THREAD

**Issue by AshleyGrant** [aspnet/JavaScriptServices#561]
Would it be possible to add Aurelia to the list of supported frameworks listed on this project's NPM page: https://www.npmjs.com/package/generator-aspnetcore-spa

**Comment by ClaudioNunes** [comment]
@AshleyGrant  this link is outdated.  The generator now have an Aurelia template. See this [http://blog.aurelia.io/2016/11/17/aurelia-in-asp-net-javascriptservices/]

**Comment by AshleyGrant** [comment]
I know the generator has an Aurelia template. I'd like to have this be mentioned on the NPM description for this generator. It isn't the list shown in the screenshot below:
![image](https://cloud.githubusercontent.com/assets/9885322/21728205/06e96878-d413-11e6-9511-efe5c621b067.png)

**Comment by SteveSandersonMS** [comment]
Thanks for pointing this out - have now added it :)

**Comment by AshleyGrant** [comment]
Thank you!
