### ISSUE TITLE
error refreshing page with local storage

### ISSUE THREAD

**Issue by lucamorelli** [aspnet/JavaScriptServices#567]
Hi, In my app I have a service that prepare the request option adding jwt tokens to request calls this way

```
    public get jwt(): RequestOptions {
        var authHeader = new Headers();
        var token = localStorage.getItem('access_token');
        authHeader.append('Authorization', 'Bearer ' + token);
        authHeader.append('Content-Type', 'application/json');
        return new RequestOptions({ headers: authHeader });
    }

```

it works normally, but if during navigation I press F5 to and refresh, I obtain this error message

```
Exception: Call to Node module failed with error: ReferenceError: localStorage is not defined
at RequestOptionsService.Object.defineProperty.get [as jwt] (D:\Sorgenti\Interno\MyCrm\src\CrmApp\ClientApp\dist\main-server.js:20252:26)
at CampagnaService.aperteSimpleList (D:\Sorgenti\Interno\MyCrm\src\CrmApp\ClientApp\dist\main-server.js:20666:59)

```

Am I missing somthing?

**Comment by MarkPieszak** [comment]
When you're refreshing the App is being first rendered by the server again. You'll need to use dependency injection to provide a StorageService for both the Client (which will use regular localStorage) & the Server (to use Redis, in-memory variable storage, whatever you choose).  

These kinds of situations aren't easy when dealing with universal/isomorphic apps, but it gets easier with time!

Basically you want to create a Browser class around localStorage, and maybe on the server, you just do nothing.

```
export class BrowserStorage {
    getItem (key: string) {
        return localStorage.getItem(key);
    } 
    /* setItem , clear etc if you want */
}

export class ServerStorage {
    getItem (key: string) {
        return '';
    } 
    /* setItem , clear etc if you want */
}
```

Then you want your abstraction Class.

```
export class StorageService {
    abstract getItem (key:string) {}
    abstract setItem (key:string, val: any) {}
}
```

Then in your `app.module` file, under **providers** add:

```
import { isBrowser } from 'angular2-universal';

{ provide : StorageService, useClass: isBrowser ? BrowserStorage : ServerStorage }
```

I hope that helps get you going in the right direction!

**Comment by SteveSandersonMS** [comment]
Thanks for the answer, @MarkPieszak!

**Comment by lucamorelli** [comment]
thanks, I tried , added the code and I think this steps works, but now I have this error

```
Exception: Call to Node module failed with error: Error: This method is not implemented in Parse5DomAdapter: Parse5DomAdapter#getCookie
at _notImplemented (D:\Sorgenti\Interno\MyCrm\src\CrmApp\ClientApp\dist\vendor.js:79077:13)
at Parse5DomAdapter.getCookie (D:\Sorgenti\Interno\MyCrm\src\CrmApp\ClientApp\dist\vendor.js:79696:16)
at CookieXSRFStrategy.configureRequest (D:\Sorgenti\Interno\MyCrm\src\CrmApp\ClientApp\dist\vendor.js:52197:93)
at XHRBackend.createConnection (D:\Sorgenti\Interno\MyCrm\src\CrmApp\ClientApp\dist\vendor.js:52237:33)
at httpRequest (D:\Sorgenti\Interno\MyCrm\src\CrmApp\ClientApp\dist\vendor.js:52575:25)
at Http.get (D:\Sorgenti\Interno\MyCrm\src\CrmApp\ClientApp\dist\vendor.js:52686:21)
at CampagnaService.aperteSimpleList (D:\Sorgenti\Interno\MyCrm\src\CrmApp\ClientApp\dist\main-server.js:20647:27)
at CampagneAperteComponent.ngOnInit (D:\Sorgenti\Interno\MyCrm\src\CrmApp\ClientApp\dist\main-server.js:21435:23)
at AppView._View_CampagneAperteComponent_Host0.detectChangesInternal (CampagneAperteComponent_Host.ngfactory.js:28:92)
at AppView.detectChanges (D:\Sorgenti\Interno\MyCrm\src\CrmApp\ClientApp\dist\vendor.js:12652:19)

```

but I think this happens when the get call is done, but I don't use cookies in this services.
```
    public aperteSimpleList(): Observable<CampagnaVm[]> {
        var apiPath = this.basePath + 'Aperte/';
        return this.http.get(apiPath, this.requestOptions.jwt)
            .map(response => this.extractData(response));
    }
```
beside this , I have 2 more questions:

1. where can I find any reference on how to create a polyfiller for the storage service? I'm evaluting how much may be impacting for me and my customers to support server side rendering, and developer polyfillers in node for people with a C# background can be problematic.
2. how they works these two services when I'll do the authentication? When I do login (not actually implemented in this program) I do a server call to the authentication service that returns the token but, if I understand well, at this point I have to set the token key in both the services manually or angular make this automatically?

**Comment by lucamorelli** [comment]
if possible another question @SteveSandersonMS.
I see that sometimes error handling is not consistent: some js errors are reported on screen using that error message, sometimes js fails and I have to check in the console. Sometimes a few errors seems that stop webpack reloading and I have to stop and rerun the project from Vs.
Is this by design or has to be reported?

**Comment by SteveSandersonMS** [comment]
> where can I find any reference on how to create a polyfiller for the storage service? ... develop polyfillers in node for people with a C# background could be problematic

That's a general TypeScript/Node question so I'd recommend searching for general resources relating to those. If your team is going to build a nontrivial Angular/React/etc application, then regardless of whether you're building polyfills for server-side rendering in Node or not, your team will certainly have to get good at writing TypeScript and understanding how a JavaScript runtime environment works - you can't really avoid that I'm afraid!

> how they works these two services when I'll do the authentication?

If your server-side .NET code has authentication information, you can pass information such as the user's authentication token into your `boot-server.ts` code (e.g., see docs here: https://github.com/aspnet/JavaScriptServices/tree/dev/src/Microsoft.AspNetCore.SpaServices#3-supplying-javascript-code-to-perform-prerendering). Then your JS code can set up Angular in whatever way you want so it passes it on to any APIs that it calls. The exact details of working with Angular are best discussed with the Angular community itself.

> I see that sometimes error handling is not consistent: some js errors are reported on screen using that error message, sometimes js fails and I have to check in the console.

There may be inconsistencies; I'm not sure. As far as I know, there are reasons why errors that occur at different phases (e.g., during build, or during .NET app startup, or on the server while handling a request, or on the client) get presented in different ways. If you think you have a specific scenario where it's not behaving sensibly, could you please file a separate issue with repro steps?

**Comment by MarkPieszak** [comment]
There's are just different situations where errors can occur, as Steve was just saying.
JS client-side errors will be in the browser console. 
If you refresh the page, and the error screen with Node information appears (that's an error that occured during the server-side rendering).
Then there's the regular .NET error page of course.

Nothing to worry about :)

When developing front-end applications, I'd suggest locking those devtools open permanently :smile:
