### ISSUE TITLE
Incorrect docker image when generating with csproj

### ISSUE THREAD

**Issue by chriscooper87** [aspnet/JavaScriptServices#574]
When generating a csproj project for VS 2017 RC the Dockerfile is still using microsoft/dotnet:1.1.0-sdk-projectjson. I believe this should be microsoft/dotnet:1.1.0-sdk-msbuild

Once I change this and add docker via 'Project -> Add -> Docker Solution Support' in VS 2017 RC I still cannot get the project to build with docker. Are there any additional changes required for the compose files to get this to work? Thanks

**Comment by spboyer** [comment]
What is the error you are getting after changing to the new Dockerfile?

**Comment by chriscooper87** [comment]
When building with docker I get: 
Service 'test' failed to build.  The command 'dotnet-restore' returned a non-zero code: 1.

**Comment by spboyer** [comment]
In the `docker-compose.yml` file is there a *test* service defined and/or do you have a test project in your solution?

**Comment by chriscooper87** [comment]
Yes my docker-compose file is as follows:

`version: '2'

services:
  test:
    image: test
    build:
      context: .
      dockerfile: Dockerfile'

The only change I have made to this was to set the context to . as it was complaining that the context could not be null.

**Comment by SteveSandersonMS** [comment]
Thanks for reporting this. I confirmed that the `microsoft/dotnet:1.1.0-sdk-msbuild` base image does work with csproj projects. So I've updated `generator-aspnetcore-spa` to use that when you choose .csproj. This fix is in `generator-aspnetcore-spa` version 0.7.4, which I'll publish to npm when the CI system finishes building it.

> Service 'test' failed to build. The command 'dotnet-restore' returned a non-zero code: 1.

I don't know what's going on there, but I've not been able to reproduce it. It works correctly with `generator-aspnetcore-spa` version 0.7.4 as far as I can tell, so I'll close this. If you're able to supply repro steps for the `Peer certificate cannot be authenticated` error, please let us know (but it doesn't sound like it's got anything to do with these templates).
