### ISSUE TITLE
Ungroup items in solution explorer

### ISSUE THREAD

**Issue by MaklaCof** [aspnet/JavaScriptServices#580]
How can I ungroup items in solution explorer. Right now all my .ts and .css files are grouped beneath .html files which is default behaviour. But I do not want this.

**Comment by MarkPieszak** [comment]
This is a Visual Studio / aspnet tooling issue actually, it's still open here : https://github.com/aspnet/Tooling/issues/347 but I agree If anything i would prefer the TS file to be the main one.

Try VSCode for now, it has better TypeScript support as well currently.

**Comment by SteveSandersonMS** [comment]
Agreed with @MarkPieszak's answer.
