### ISSUE TITLE
Docker node version

### ISSUE THREAD

**Issue by psaussure** [aspnet/JavaScriptServices#591]
Hi there. Is there any reason to use 4.x version of node instead of latest 7.x versions in Dockerfile?

`RUN wget -qO- https://deb.nodesource.com/setup_4.x | bash -`

6.x is recommanded as LTS but with ES6 features provided in the 7 version, it would be great to update Docker version. 

I found no issue/error running the SPA on both node 7 and node 6 versions.

But if there is any other consideration, let us know.

**Comment by SteveSandersonMS** [comment]
Thanks for the suggestion. Updated to 6.x by default because it's LTS. As you point out, developers can trivially update to 7.x in their own apps if they want to.
