### ISSUE TITLE
Debugging original source (.ts) when testing

### ISSUE THREAD

**Issue by ManuelDeLeon** [aspnet/JavaScriptServices#592]
In the default Angular setup, when you debug the tests you get one big `boot-test.ts` file in the browser. The file has the tests in the original TypeScript but the components' code in the transpiled JavaScript. What's the magic setting so it shows the TypeScript for everything? (not just the `*.spec.ts`)

**Comment by SteveSandersonMS** [comment]
Good question. It's not something I've looked into.

From a quick search, it looks like maybe Karma has to be configured with something like https://www.npmjs.com/package/karma-sourcemap-loader to get the original sources in its debug view.

If you're able to figure out how to set that up simply, would you please consider submitting a pull request?

I'll close this as it's not a feature we have yet - until your pull request :)
