### ISSUE TITLE
Mess when run from VS2017

### ISSUE THREAD

**Issue by rosieks** [aspnet/JavaScriptServices#593]
I have created new project with react + redux. When I hit Start Debugging then TSX files are converted to JSX and then to JS. And all that files appear in my solution (with sourcemap). I don't know if that is intentional or if that's just side effect of Visual Studio.

**Comment by KraigWalker** [comment]
He @rosieks, this is a Visual Studio side effect, which you can prevent by editing the csproj/xproj of the project.

In Visual Studio, right click your project in the solution explorer and choose "Unload Project"

Then, click the project to edit the actual csproj/xproj file - it's a big XML file.

Within a `PropertyGroup` tag insert:

`<TypeScriptCompileBlocked>true</TypeScriptCompileBlocked>`

And Save, then reload the project again. This will stop Visual Studio from automatically compiling ts/tsx files and adding them to your solution. This has happened to me in VS2015 too.

**Comment by rosieks** [comment]
Now is better. And I see that's also in new template.
