### ISSUE TITLE
Error on run generator-aspnetcore-spa

### ISSUE THREAD

**Issue by Ciejaa** [aspnet/JavaScriptServices#594]
Hey,

After I download generator-aspnetcore-spa from yeoman and restore all packages I tried to run projects in Visual Studio 2015 and I'm getting an error:

> An unhandled exception occurred while processing the request.
> 
> Exception: Call to Node module failed with error: TypeError: Cannot convert object to primitive value
> at ZoneTask.scheduleTask [as scheduleFn] (C:\Users\username\documents\visual studio 2015\Projects\test\src\test.Web\ClientApp\dist\vendor.js:50343:41)
> at ZoneDelegate.scheduleTask (C:\Users\username\documents\visual studio 2015\Projects\test\src\test.Web\ClientApp\dist\vendor.js:49630:27)
> at Zone.scheduleMacroTask (C:\Users\username\documents\visual studio 2015\Projects\test\src\test.Web\ClientApp\dist\vendor.js:49556:40)
> at C:\Users\username\documents\visual studio 2015\Projects\test\src\test.Web\ClientApp\dist\vendor.js:50360:34
> at setTimeout (eval at createNamedFn (C:\Users\username\documents\visual studio 2015\Projects\test\src\test.Web\ClientApp\dist\vendor.js:50224:58), <anonymous>:3:37)
> at C:\Users\username\documents\visual studio 2015\Projects\test\src\test.Web\ClientApp\dist\vendor.js:50681:18
> at bound (domain.js:256:14)
> at runBound (domain.js:267:12)
> at Object.exports.run (C:\Users\username\documents\visual studio 2015\Projects\test\src\test.Web\ClientApp\dist\vendor.js:50802:36)
> at Object.exports.runInNewDomain (C:\Users\username\documents\visual studio 2015\Projects\test\src\test.Web\ClientApp\dist\vendor.js:50828:19)

Do you have any idea what's wrong?

**Comment by Antoshjkee** [comment]
Try to rebuild the project in CMD, webpack --config  webpack.config.js

**Comment by Ciejaa** [comment]
I've tried it and the results is the same

**Comment by SteveSandersonMS** [comment]
I'm afraid I don't know what's going on in your environment, but I just verified that the following steps work without error:

 * On a machine with VS2015 Update 3 and Node.js (I used Node 6.2.0)
 * `npm install -g generator-aspnetcore-spa`
 * `yo aspnetcore-spa` (choose Angular and other options as default)
 * After it's finished generatoring, open the `.xproj` in VS
 * Press Ctrl+F5 to launch

If following these steps don't work for you, can you provide details of what specific aspect of your environment (machine setup, etc.) will reproduce the problem? I'll close this for now as there's no further action I can take in the absence of repro steps.
