### ISSUE TITLE
I suggest using the release github feature

### ISSUE THREAD

**Issue by Spiralis** [aspnet/JavaScriptServices#599]
If the project used the release github feature I could set up our slack account to monitor the releases RSS feed and thus automatically get notified of any new releases inside our slack channel, like I already do with many other github projects.

**Comment by SteveSandersonMS** [comment]
Thanks for the suggestion.

The artifacts from this repo ship as packages on NuGet and NPM. There aren't any other standalone shippable artifacts, so I don't think the GitHub 'releases' feature really fits the need (there's nothing to 'release' outside of NuGet and NPM).

If you want automated notifications of updates, I'd recommend polling NuGet/NPM.
