### ISSUE TITLE
Disabling Server-Side Rendering using Angular 2 Webpack starter

### ISSUE THREAD

**Issue by stevenknox** [aspnet/JavaScriptServices#602]
When disabling server-side rendering using the Angular 2 Webpack starter (using the Visual Studio Asp.Net Core Template Pack - https://marketplace.visualstudio.com/items?itemName=MadsKristensen.ASPNETCoreTemplatePack) I get a blank page with the error:

`Uncaught TypeError: ctorParameters.map is not a function
    at ReflectionCapabilities.parameters (http://localhost:39581/dist/vendor.js?v=uDhibyj1JCvnQ_atjbkYgdDXemO3YhimVE71Ib9XzU4:13837:52)`

I have updated my packages to the latest as per latest version generated using "yo-generator aspnetcore spa"

In my Index.cshtml page I have replaced the following:

`<app asp-prerender-module="ClientApp/dist/main-server">Loading...</app>`

with 

`<app></app>`

Am i missing a step somewhere, any reference I can find to disabling server-side rendering only mentions removing the asp-prerender-module tag.

Snapshot of my package.json as follows:

@angular/common": "2.0.2",
"@angular/compiler": "2.0.2",
"@angular/core": "2.0.2",
"@angular/forms": "2.0.2",
"@angular/http": "2.0.2",
"@angular/platform-browser": "2.0.2",
"@angular/platform-browser-dynamic": "2.0.2",
"@angular/platform-server": "2.0.2",
"@angular/router": "3.0.2",
"@types/jQuery": "2.0.34",
"@types/node": "^6.0.42",
"@types/react": "0.0.0",
"angular2-platform-node": "~2.0.11",
"angular2-template-loader": "^0.6.0",
"angular2-universal": "~2.0.11",
"angular2-universal-polyfills": "~2.0.11",
"aspnet-prerendering": "^2.0.0",
"aspnet-webpack": "^1.0.17"

**Comment by RonCass** [comment]
I'm having the same problem and have yet to find the answer. Not sure why you closed this without an answer so if you figured out, please let me know. 

If I replace the tag: 
<app asp-prerender-module="ClientApp/dist/main-server">Loading...</app> 
with 
<app>Loading...</app>
, all I get is "Loading..." Not sure what else I need to do to disable server side rendering to move forward with my project. Any help you can give would be most appreciated.

Thank,s

Ron C.

**Comment by stevenknox** [comment]
I closed it as i'm not sure if its related to the JavascriptServcies project itself. I created a new project using the aspnetcore-spa yoman generator and could successfully disable the serverside prerendering.
