### ISSUE TITLE
initial load time improvement

### ISSUE THREAD

**Issue by emailtowalter** [aspnet/JavaScriptServices#604]
We call NodeServices from a MVC controller to leverage node.js SAML20 package . The first call to InvokeAsyn() took about 1 sec, and subsequent  calls are about 0.1 sec. Of cause, the first call need to start-up the node.exe etc. 

I guess we can add some logic in startup.cs to launch the node.exe there to improve the first call time. Not sure if there is a better way.

Thanks, 

Walter

**Comment by SteveSandersonMS** [comment]
If you need Node to be pre-launched so there's no time spent waiting for it to start, I'd recommend making a call to it from in your `Startup.cs` (as you've guessed). I don't think there's a better way, as it does take a second or so for Node to start up.
