### ISSUE TITLE
self-contained deployment with node

### ISSUE THREAD

**Issue by emailtowalter** [aspnet/JavaScriptServices#605]
We use cloud foundry ( on Linux) to run .net core. The way we deploy is to publish the website as a self-contained package. 

Here is the issue: Node.js is not on the platform, and we do not want to install it on the platform either. A ideal case would be to include node.js as part of the deployment package during publishing process. Of cause, it has to be the right node.js runtime depending on the OS. 

At this moment, we have a workaround : include the node and npm from linux platform in the root directory. But it is not elegant. 

Thanks, 

Walter

**Comment by SteveSandersonMS** [comment]
One option would be to deploy with Docker. That's basically the industry-standard way to have fully self-contained deployments. Hope that helps (and I'm afraid it's the only suggestion I have!).
