### ISSUE TITLE
Using Jquery

### ISSUE THREAD

**Issue by Azayzel** [aspnet/JavaScriptServices#609]
This is more of a question.

How do I use Jquery in a component ts file?

**Comment by MarkPieszak** [comment]
You can take a look at Steven's comment here about it: https://github.com/aspnet/JavaScriptServices/issues/464#issuecomment-263244571

> Install both jQuery and its type definitions (npm install --save jquery @types/jquery)
> In any TypeScript file, you can now add at the top: import * as $ from 'jquery';. Now you can use $ in that file and will get correct intellisense, etc.
> Please note that it's not great practice to use jQuery directly in an Angular 2 app, both because it will prevent you from doing server-side prerendering (jQuery can only run in browsers), and it bypasses all the Angular 2 APIs that are meant to be in control of updating the DOM. If you choose to go ahead and use jQuery directly anyway, you'll be on your own in terms of keeping the document state consistent :)

If you're using a plugin, import it in your `boot-client.ts` file only. `import 'some-jquery-plugin';` for example.

I'm not sure which template you're using this for, but if it's Angular, make sure you wrap it conditionally in `import { isBrowser } from 'angular2-universal';` like so: `if (isBrowser) { /* $('body').hide(); */ }`

Hope that helps!

**Comment by Azayzel** [comment]
I am using the Angular2+ .NETCore template. I see that Jquery is in the package.json and gets installed and configured under webpack.vendor. I was just hoping it would be an easy fix because I tried both methods stated above and it either can't find the module. I'll keep plugging away at it, I just want charts and this template uses Universal, thus ruling out ngx-charts or most other charting libraries.

**Comment by MarkPieszak** [comment]
Are you using recent code from this template? It should already include jQuery in vendor & webpack Plugins for you.

Can you post some code? Which part isn't working currently, does regular jQuery manipulation work like:

    // boot-client.ts file 
    import 'ngx-charts';

    // up top of your Component
    import { isBrowser } from 'angular2-universal';
    import * as $ from 'jquery';

    // inside ngOnInit 
    if (isBrowser) { 
        $('body').hide(); 
    }

Make sure that ngx-charts (or some client-only library) **is not** in your Vendor webpack file, you want the server to completely ignore it. Only import it in your boot-client file like above.

You can most-any library to work, but you can only get it work on the Client/browser, you can't server-render jQuery or other DOM manipulating libraries unfortunately.  There's some difficult way to patch it with jsDOM but your performance takes a big hit.

**Comment by Azayzel** [comment]
I think you're onto something. I was trying pre render that stuff. I'm trying now to import ngx-charts into my boot-client. I haven't tried that. If I can do without Jquery I'd prefer that.

**Comment by Azayzel** [comment]
This is my boot-client file
```
import 'angular2-universal-polyfills/browser';
import { enableProdMode } from '@angular/core';
import { platformUniversalDynamic } from 'angular2-universal';
import { AppModule } from './app/app.module';
import 'bootstrap';
import 'jquery';
import 'ngx-charts';

// Enable either Hot Module Reloading or production mode
if (module['hot']) {
    module['hot'].accept();
    module['hot'].dispose(() => { platform.destroy(); });
} else {
    enableProdMode();
}

// Boot the application, either now or when the DOM content is loaded
const platform = platformUniversalDynamic();
const bootApplication = () => { platform.bootstrapModule(AppModule); };
if (document.readyState === 'complete') {
    bootApplication();
} else {
    document.addEventListener('DOMContentLoaded', bootApplication);
}

```

Im then putting the below into my .html partial 
```
        <ngx-charts-advanced-pie-chart [view]="view"
                                       [scheme]="colorScheme"
                                       [results]="single"
                                       [gradient]="gradient"
                                       (select)="onSelect($event)">
        </ngx-charts-advanced-pie-chart>
```

I then end up with template parse erros. So, its like it's not pickling that module up. Thank you for your help with this,.

**Comment by Azayzel** [comment]
I'm trying to follow ngx-charts guide [here](https://swimlane.gitbooks.io/ngx-charts/content/charts/advanced-pie-chart.html) but i can't seem to get it working.

**Comment by MarkPieszak** [comment]
It looks like from a server-side rendering point of view they have an issue open here https://github.com/swimlane/ngx-charts/issues/18

I forgot at first that it's going to be using Directives/Components. Those will throw errors since they haven't been registered.

This next part is annoying, but if you wanted to temporarily ignore them on the server side, you just want to make *blank* Components to match those, and add them to your app.module file (and only load them for the server platform).

I can't type it all out now but you're basically just creating (for the example above)

```
@Component({
    selector: 'ngx-charts-advanced-pie-chart'
    template: ''
})export class ChartsAdvancedPieChart {}
```

In the app.module file you want to declare these, but only for the server

```
import { isNode } from 'angular2-universal';

let serverBlankComponents = [];

if (isNode) {
    serverBlankComponents.push(ChartsAdvancedPieChart);
}

@NgModule({
   // ..
   declarations : [
       // components
       ...serverBlankComponents  // (spread operator to add it in)
   ]
})
```

Confusing I know, but splitting things between platforms can be tough sometimes.

**The easiest option** at the moment might be to disabled SSR, and wait for them to add Universal support in their library.

**Comment by Azayzel** [comment]
YEah, i'm thinking i may need to hold off for a bit. Thanks again!! you've been very helpful.

**Comment by Azayzel** [comment]
Oh,  how would i disable SSR? i can prpbably look it up but you may know the better way.

**Comment by MarkPieszak** [comment]
Go to Views/Home/ Index.cshtml and remove the `asp-prerender-module` tag to disable SSR for now.

**Comment by Azayzel** [comment]
Thank you very much man

**Comment by MarkPieszak** [comment]
Not a problem sorry it's not any easier, Isomorphic JS isn't always a piece of cake 🎂 unfortunately. It's worth it though!
