### ISSUE TITLE
Authorize WebApi - Server PreRendering

### ISSUE THREAD

**Issue by NicolasHumann** [aspnet/JavaScriptServices#616]
Hi,

My web apis are protected by OAuth and use the Authorize attribute.
When I  call my webapi in the constructor or in ngOnInit, Any credentials are passed in the request made by node in the rendering process.

How can I pass the token from the browser cookies to node ?

PS: I use the template ASP.NET Core Template Pack extension with angular2 / ts / webpack

Thanks !

**Comment by SteveSandersonMS** [comment]
You can pass through the cookie or other auth token data from your .NET code into your Node prerendering code, as described in the docs under the heading _Passing data from .NET code into JavaScript code_ [here](https://github.com/aspnet/JavaScriptServices/tree/dev/src/Microsoft.AspNetCore.SpaServices#server-side-prerendering).

You can then (via your TypeScript code) pass that auth token on to any services you call via Angular `http` methods.
