### ISSUE TITLE
WebPack,OIDC and Client Side Rendering -WebStorageStateStore

### ISSUE THREAD

**Issue by DoubleExposure** [aspnet/JavaScriptServices#617]
In my appcompnent.ts file, I am trying to authenticate my user by calling the following on page load:
```
export class AppComponent implements OnInit {

    constructor( private authService: AuthService) { }

    ngOnInit() {
        this.authService.startSigninMainWindow();

    }
```
I expect this to route me to the IdentityServer login page. 
In my auth.service.ts file, I am loading WebStorageStateStore like below.
`import { UserManager, Log, MetadataService, User, WebStorageStateStore} from 'oidc-client';`

In auth.service.ts I have a const called settings. This is where I set the WebStorageStateStore.
```
```
....    filterProtocolClaims: true,
    loadUserInfo: true,
    userStore: new WebStorageStateStore({ store: window.localStorage })
}

I get an error saying window is not defined. How do I resolve this? Webpack seems to be trying to render this serverside when there is no window object serverside. What is the recommended way to work around the serverside rendering and the conflict with a nonexistent window object? 

An unhandled exception occurred while processing the request.

```
Exception: Call to Node module failed with error: Prerendering failed because of error: ReferenceError: window is not defined
at Object.<anonymous> (main-server.js:617:65)
```

Any suggestions as to a work around? Does anyone know how to turn off serverside prerendering for this component? Can I tell Webpack to ignore this component somehow since the OIDC javascript library is clientside only and needs the window object?

**Comment by SteveSandersonMS** [comment]
Does it really make sense to do server-side prerendering if you are strictly dependent on an authentication technology that only works client-side? What server-side prerendering output do you want to get in this case anyway?

If you do want to keep doing server-side prerendering, you could use something like Angular's DI system to supply different authentication service objects depending on whether you're running on the client or on the server. On the server, it could return some dummy object that always says you're not authenticated, whereas on the client, it could take a dependency on `oidc-client` etc. and follow the logic you already have. There are some pointers about this here: https://github.com/aspnet/JavaScriptServices/issues/303#issuecomment-246620724, but for more info please consult Angular docs.

If you want to disable server-side prerendering, just remove the `asp-prerender-module` tag helper from your `Index.cshtml` (and optionally remove the server-side bundle stuff from your Webpack configs).

**Comment by DoubleExposure** [comment]
Thanks. I am learning Angular and IdentityServer at the same time so there is much to learn. 
Trying to work out all of the various technologies that make up these two platforms.
