### ISSUE TITLE
App doesnt work when I remove asp-prerender-module

### ISSUE THREAD

**Issue by RonCass** [aspnet/JavaScriptServices#619]
Hi Guys,

I upgraded to the latest Angular 2.4.5 and get the error: "Prerendering failed because of error: undefined". And from what I read I should be able to just disable pre-rendering to get around this for now. The problem is that if I change my app tag from:
&lt;app asp-prerender-module="ClientApp/dist/main-server"&gt;Loading...&lt;/app&gt;
to:
&lt;app&gt;Loading...&lt;/app&gt; all I see is the Loading... and the application never starts.

I've googled the heck out of this and tested numerous things to an avail. Also, I'm using a solution created using the ASP.Net Core Angular 2 Starter templates. I created the project months ago.

So please let me know what little stupid thing I must be over looking. :)

Thanks,

Ron C.

**Comment by RonCass** [comment]
Turns out a had an issue with the order the polyfills were loaded. The app runs now without the prerendering and not I'm back to my original issue when creating a new angular module. I click the link to that new module and get a nice very descriptive error "Uncaught (in promise): ReferenceError: System is not defined".
Thanks

**Comment by paddyfink** [comment]
Hi @RonCass, how exactly did you solve that problem please? I got the same thing.
