### ISSUE TITLE
Angular 2 "MusicStore" sample still uses old version of Angular

### ISSUE THREAD

**Issue by AndrewCarre** [aspnet/JavaScriptServices#622]
I am learning from the sample project MusicStore for angular 2 and alot of the api's and classes are now deprecated in the stable release. Does anyone want to update them? 

I'll take a shot at it when I have time. In the meantime it should be noted. 

here are some of the classes and so on that are now deprecated:
* ngFormModel
* router.ROUTER_DIRECTIVES
* Control

EDIT: Here is some of the classes that were deprecated: https://www.picnet.com.au/blogs/guido/post/2016/06/30/upgrading-to-angular-2-reactive-forms-rc3-new-forms/

**Comment by tonysneed** [comment]
+1 ... The aspnet-spa generator is still using DNX.

**Comment by MarkPieszak** [comment]
You want to check out the Templates/Angular2Spa for up to date repos. I can't remember, but the samples are very old, not sure if they're meant to be used (?). Have to ask Steven on that one though.

As for generators you want to npm install -g generator-aspnetcore-spa to get the latest ones.

**Comment by tonysneed** [comment]
@MarkPieszak I just installed generator-aspnetcore-spa and the templates are DNX-based.  I looked at [project.json](https://github.com/aspnet/JavaScriptServices/blob/dev/templates/Angular2Spa/project.json) in the dev branch, and that's up-to-date.  But it looks like the npm package has not been published from dev. /cc @SteveSanderson

**Comment by SteveSandersonMS** [comment]
@AndrewCarre Yes, you're right - the Angular 2 MusicStore sample is still on `2.0.0-beta.15`, which is ancient. If you are interested in updating this, that would be great! Like @MarkPieszak mentions, the up-to-date stuff is in the templates. See the `templates/` directory. At some point, if that sample remains badly out-of-date and nobody is ready to update it, we'll most likely just remove it to avoid confusing anyone.

@tonysneed That's not correct. I'm not sure what you're looking at, but `generator-aspnetcore-spa` produces projects based on the `dotnet` tooling (and you can choose between `project.json` (e.g., works with VS2015 or CLI tooling prior to preview3) or `.csproj` (e.g., works with VS2017 or CLI tooling preview3+) formats. This is completely up-to-date. You might want to check you have the latest `generator-aspnetcore-spa` installed (current is v0.7.4) and that you're running `yo aspnetcore-spa` to start it.

**Comment by tonysneed** [comment]
@SteveSanderson Yes, my local version is outdated.  If I run `npm install -g generator-aspnet-spa` I get 0.1.3.

```
npm ls -g generator-aspnet-spa
C:\Users\Tony\AppData\Roaming\npm
`-- generator-aspnet-spa@0.1.3
```

I uninstalled, then re-installed, and still got v 0.1.3.  Then I ran `npm install -g generator-aspnet-spa@latest` and still got v 0.1.3.  Lastly, I tried `npm install -g generator-aspnet-spa@0.7.4` and got:

```
Cannot read property 'path' of null
```

Is this just an NPM issue?  I'm getting this same behavior on both Windows 10 and Mac OS.

**Comment by SteveSandersonMS** [comment]
@tonysneed The package name is `generator-aspnetcore-spa`, not `generator-aspnet-spa`.

I've just updated the NPM registry to mark `generator-aspnet-spa` as deprecated, so you should now get a warning if you try to install it.

**Comment by tonysneed** [comment]
Ahhh ... that explains it! I figured it had to be something like that. 😊

**Comment by SteveSandersonMS** [comment]
This sample has been removed in the latest `dev` branch because it was ridiculously out-of-date. We probably don't need a newer equivalent to this sample, because the `AngularSpa` template itself is a more convincing application structure and provides good guidance on its own. It's not desirable to have detailed examples of third-party framework usage in this repo - documentation and samples about that should be maintained by the third-party framework teams themselves.
