### ISSUE TITLE
Need to use KendoUI with Angular 2 Core plugin. 

### ISSUE THREAD

**Issue by ravimittal16** [aspnet/JavaScriptServices#628]
Hello,

I want to use [Kendo UI](http://www.telerik.com/kendo-angular-ui/getting-started/) with Angular 2. When i try to add the dependency, my project stop running and start giving too many issues. Actually Kendo UI require new version of Angular 2, updating the angular package to new version not working with this template.

Please help!!!

**Comment by SteveSandersonMS** [comment]
We are in the process of updating to Angular 2.4.5 this week, so hopefully after that, you should find it easier to proceed! That said, I don't personally have experience with Kendo UI, so I don't know whether it will support server-side rendering (and if not, you can disable server-side rendering by removing the `asp-prerender-module` tag helper from your `Index.cshtml` file).

I'll mark this closed because we're already working on the Angular update. Hope that's OK.

**Comment by SteveSandersonMS** [comment]
Oh, and in the meantime, you can probably upgrade to Angular 2.4+ on your own without errors if you just disable server-side prerendering as described above. That's the only thing that makes the upgrade difficult.

**Comment by ravimittal16** [comment]
After uninstalling the package above, we are getting error below...

**An unhandled exception occurred while processing the request.**

Exception: Call to Node module failed with error: Prerendering failed because of error: TypeError: Cannot read property 'SelectorMatcher' of undefined

**Comment by SteveSandersonMS** [comment]
Sounds like you didn't disable server-side rendering. Please see my first comment above :)

**Comment by ravimittal16** [comment]
now getting this error

Uncaught Error: Cannot find module "webpack-hot-middleware/client?path=http%3A%2F%2Flocalhost%3A52487%2F__webpack_hmr"

**Comment by SteveSandersonMS** [comment]
Sorry, I don't know about that. I'm not getting that error. If you can provide repro steps (starting from a new project) please let us know.

**Comment by ravimittal16** [comment]
[package.json.txt](https://github.com/aspnet/JavaScriptServices/files/741894/package.json.txt)

i am sending you my package json file, may be that can help

**Comment by SteveSandersonMS** [comment]
If you're able to find out what specifically causes the error and you think it might be a bug in some of the code in this repo, please let us know, giving repro steps based on a new project. Thanks!

**Comment by SteveSandersonMS** [comment]
BTW, as promised, `generator-aspnetcore-spa` is now updated and can produce Angular 2.4.5 projects.

**Comment by ravimittal16** [comment]
thanks much

**Comment by ravimittal16** [comment]
Could you please confirm that creating a project using this [template ](http://blog.stevensanderson.com/2016/10/04/angular2-template-for-visual-studio/) will give me the updated repo.

**Comment by SteveSandersonMS** [comment]
@ravimittal16 No, it won't. Please use `generator-aspnetcore-spa` for an Angular 2.4.5 project.

**Comment by ravimittal16** [comment]
okay sure.

Thanks for the help :+1:
