### ISSUE TITLE
error upgrading to latest version

### ISSUE THREAD

**Issue by lucamorelli** [aspnet/JavaScriptServices#630]
Hi, a few days I updated a project using the template from the yo generator 0.7.4, and I was able to run my project using csproj format.
Now I updated the project using the 0.8.0 template, but I'm facing an issue:
I updated using the **ts.config, package.json, the .csproj file, and both the webpack config files,** adding just a few alias like these:
```
            alias: {
                ditta: path.resolve(__dirname, './ClientApp/app/ditta'),
                campagna: path.resolve(__dirname, './ClientApp/app/campagna'),
                tabella: path.resolve(__dirname, './ClientApp/app/tabella'),
                contatto: path.resolve(__dirname, './ClientApp/app/contatto'),
                attivita: path.resolve(__dirname, './ClientApp/app/attivita')
            }

```
I deleted the node_module dir to reinstall the correct version of the package, but if I try to run webpack (when I have problems I run for command line to better understand) I obtain

**import { StorageService } from './common/Storage/StorageService';**
```
    ERROR in ./ClientApp/app/common/Storage/StorageService.ts
    Module build failed: Error: Final loader didn't return a Buffer or String

```

**import { dittaComponents, dittaServices, dittaRoutes } from 'ditta';**
```
    ERROR in ./ClientApp/app/ditta/index.ts
    Module build failed: Error: Final loader didn't return a Buffer or String

```
all these are imports in the **app.module.ts** file

this is the ending part of the message 
```
        at D:\Sorgenti\Interno\MyCrm - Copia\src\CrmApp\node_modules\awesome-typescript-loader\src\index.ts:91:13
        at process._tickCallback (internal/process/next_tick.js:103:7)
     @ ./ClientApp/app/app.module.ts 25:23-65
     @ ./ClientApp/boot-client.ts
```

To make happy vs I added this to the **tsconfig** to be able to resolve the alias 

```
    "baseUrl": ".",
    "paths": {
      "ditta": [ "clientApp/app/ditta" ],
      "campagna": [ "clientApp/app/campagna" ],
      "tabella": [ "clientApp/app/tabella" ],
      "contatto": [ "clientApp/app/contatto" ],
      "attivita": [ "clientApp/app/attivita" ]
    }

```
and so far the double configuration worked fine without problems,  but I suppose that this is giving problems with the awesome-typescript-loader.
Do you have any suggestion to solve this problem?

**Comment by SteveSandersonMS** [comment]
Searching StackOverflow brings up this: http://stackoverflow.com/a/40970345/1972948 ... which suggests maybe you have an invalid `import` statement somewhere.

Besides that I'm afraid I don't know. If you can compare your project to the default template output, and find out what change is responsible for the error, and if you think it's a defect in the template, please let us know! Sorry I can't be of more help.

**Comment by lucamorelli** [comment]
@SteveSandersonMS FYI solved, and now all seems working. to use new paths and baseUrl feature of TS 2.0 we have to include **TsConfigPathsPlugin**.
You need to add
`var TsConfigPathsPlugin = require('awesome-typescript-loader').TsConfigPathsPlugin;`

and 

```
resolve: {
            extensions: ['.js', '.ts'],
            plugins: [
                new TsConfigPathsPlugin(/* { tsconfig, compiler } */)
            ]
        },

```
Another things, but I think you already know, looks like that this webpack and/or awesome-typescript-loader is case sensitive, so if you write **campagnaVm** instead of **CampagnaVm** now you'll have errors.
