### ISSUE TITLE
ASP.NET Core Angular 2 Starter Application (.NET Core)

### ISSUE THREAD

**Issue by pappasa** [aspnet/JavaScriptServices#631]
I am trying to run the template "ASP.NET Core Angular 2 Starter Application (.NET Core)" found in http://blog.stevensanderson.com/2016/10/04/angular2-template-for-visual-studio, but I get the error:

The imported project "C:\Program Files\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk. d:\temp\Angular2Application1\Angular2Application1.xproj.

**Comment by SteveSandersonMS** [comment]
That error occurs if you've installed .NET Core tooling preview 3 or later on your machine (which happens if you install VS2017RC).

To fix it, you can add a `global.json` file at the root of your project containing this:

```
{
  "sdk": { "version": "1.0.0-preview2-1-003177" }
}
```

A better solution though, instead of using the VS project template, is to use the Yeoman generator, which produces much more up-to-date projects. To do this, create an empty directory somewhere, then in a command prompt, run:

```
cd your-empty-directory
npm install -g yo generator-aspnetcore-spa
yo aspnetcore-spa
```

If you have any trouble with that, make sure you have an up-to-date version of Node.js (e.g., version 6+).

**Comment by pappasa** [comment]
Thank you very much for your feedback.

I get the error mentioned when I create the project, so there is no directory yet, and therefore there is nowhere to put the global.json file. I attach the screenshots:
![angular2starter1](https://cloud.githubusercontent.com/assets/23055341/22498612/2b803da2-e862-11e6-861b-ca054e73ea60.jpg)
![angular2starter2](https://cloud.githubusercontent.com/assets/23055341/22498623/33fee370-e862-11e6-854c-e4ddb99127c3.jpg)

How else can I resolve this problem?

Unfortunately, I cannot use npm, because I am behind a firewall. I attach the log file of npm:
[npm-debug.log.txt](https://github.com/aspnet/JavaScriptServices/files/744112/npm-debug.log.txt)

If I cannot use the template, is there a sample Visual Studio project with Angular2?

**Comment by pappasa** [comment]
I installed ASP.NET Core 1.1 (dotnet-dev-win-x86.1.0.0-preview2-1-003177.exe), and now I could create a new project with the template "ASP.NET Core Angular 2 Starter Application (.NET Core)", but I get the following message in the output window:

PATH=.\node_modules\.bin;C:\Program Files\Microsoft Visual Studio 14.0\Web\External;%PATH%;C:\Program Files\Microsoft Visual Studio 14.0\Web\External\git
C:\Program Files\dotnet\dotnet.exe restore "d:\temp\Angular2Application2\.vs\restore.dg" -s "C:\Program Files\Microsoft SDKs\NuGetPackages"
log  : Restoring packages for d:\temp\Angular2Application2\project.json...
error: Unable to resolve 'Microsoft.AspNetCore.AngularServices (>= 1.0.0)' for '.NETCoreApp,Version=v1.0'.

![angular2starter3](https://cloud.githubusercontent.com/assets/23055341/22512602/4b3afe12-e8a2-11e6-9f13-c506daac1b7b.jpg)

[npm-debug.log.txt](https://github.com/aspnet/JavaScriptServices/files/745230/npm-debug.log.txt)

**Comment by MarkPieszak** [comment]
Are you using VS2017 RC?

I may be wrong, but I believe that is for VS2015 (notice the project.json) as opposed to the XML & .csproj that's required for 2017.

**Comment by pappasa** [comment]
Yes, I am using VS2017 RC. Do I have to install VS2015 to use the template "ASP.NET Core Angular 2 Starter Application (.NET Core)"?

**Comment by pappasa** [comment]
I would prefer to stay on VS2017 RC. Can you perhaps provide a version for VS2017 RC?

**Comment by MarkPieszak** [comment]
I'm not sure if the Template has a 2017 version, Steve would have to answer that one for you. But there is of course the 2017 version available under the generator-aspnet-spa.

Also I would definitely talk with IT and get npm available as it's such a crucial part of development these days, you'll need it! The templates and VS install things through npm, I'm not even sure those would work unless you had access?

**Comment by pappasa** [comment]
What is the generator-aspnet-spa?

**Comment by MarkPieszak** [comment]
It uses yeoman to generate the application, it's a command-line version of the Template packs (it's much easier to update projects with it as well).

`npm i -g yo generator-aspnetcore-spa` (installs both yeoman and the generator) with npm

`yo aspnetcore-spa` runs the generator (from there, you select angular2, and any other options you want (one of them being VS2015 or VS2017), it'll then install everything for you) Then you can open it in Visual Studio, etc.

**Comment by pappasa** [comment]
I have not succeeded to make npm use the proxy. Is it not possible to work without npm? Would it be possible to get the Visual Studio 2017 RC project with all the dependencies downloaded?

**Comment by MarkPieszak** [comment]
The problem is Visual Studio itself will use `npm` to download these dependencies regardless, so even if you could pull it down you'd run into the same problem.

Can you contact IT about it, `npm` is one of those things that needs to be accessible :(

**Comment by pappasa** [comment]
I now installed VS2015, but I get the following error in the Output window:

PATH=.\node_modules\.bin;C:\Program Files\Microsoft Visual Studio 14.0\Web\External;%PATH%;C:\Program Files\Microsoft Visual Studio 14.0\Web\External\git
C:\Program Files\dotnet\dotnet.exe restore "d:\temp\Angular2Application4\.vs\restore.dg" -s "C:\Program Files\Microsoft SDKs\NuGetPackages"
log  : Restoring packages for d:\temp\Angular2Application4\project.json...
error: Unable to resolve 'Microsoft.AspNetCore.AngularServices (>= 1.0.0)' for '.NETCoreApp,Version=v1.0'.
log  : Restoring packages for tool 'Microsoft.AspNetCore.Razor.Tools' in d:\temp\Angular2Application4\project.json...
log  : Restoring packages for tool 'Microsoft.AspNetCore.Server.IISIntegration.Tools' in d:\temp\Angular2Application4\project.json...
log  : Restoring packages for tool 'Microsoft.DotNet.Watcher.Tools' in d:\temp\Angular2Application4\project.json...
log  : Writing lock file to disk. Path: d:\temp\Angular2Application4\project.lock.json
log  : d:\temp\Angular2Application4\Angular2Application4.xproj
log  : Restore failed in 34712ms.
Errors in d:\temp\Angular2Application4\Angular2Application4.xproj
    Unable to resolve 'Microsoft.AspNetCore.AngularServices (>= 1.0.0)' for '.NETCoreApp,Version=v1.0'.
PATH=.\node_modules\.bin;C:\Program Files\Microsoft Visual Studio 14.0\Web\External;%PATH%;C:\Program Files\Microsoft Visual Studio 14.0\Web\External\git
C:\Program Files\dotnet\dotnet.exe restore "d:\temp\Angular2Application4\.vs\restore.dg"
log  : Restoring packages for d:\temp\Angular2Application4\project.json...
log  : Retrying 'FindPackagesByIdAsyncCore' for source 'https://www.nuget.org/api/v2/FindPackagesById()?id='Microsoft.AspNetCore.AngularServices''.
log  : Response status code does not indicate success: 407 (authenticationrequired).
log  : Retrying 'FindPackagesByIdAsyncCore' for source 'https://www.nuget.org/api/v2/FindPackagesById()?id='Microsoft.AspNetCore.AngularServices''.
log  : Response status code does not indicate success: 407 (authenticationrequired).
error: Failed to retrieve information from remote source 'https://www.nuget.org/api/v2/FindPackagesById()?id='Microsoft.AspNetCore.AngularServices''.
error: Response status code does not indicate success: 407 (authenticationrequired).
error: Failed to retrieve information from remote source 'https://www.nuget.org/api/v2/FindPackagesById()?id='Microsoft.AspNetCore.AngularServices''.
error:   Response status code does not indicate success: 407 (authenticationrequired).

![angular2starter4](https://cloud.githubusercontent.com/assets/23055341/22584303/48721fae-e9fa-11e6-8f19-e96d77a43df4.jpg)
