### ISSUE TITLE
npm test => Error in config file!

### ISSUE THREAD

**Issue by ManuelDeLeon** [aspnet/JavaScriptServices#634]
So the new Angular generator (v0.8.0) now exports a function in the webpack config files, yet the karma config wasn't updated and thus you get `require('../../webpack.config.js').filter` is not a function when you try to run the tests.

A simple fix is to run the config: `require('../../webpack.config.js')().filter`

**Comment by SteveSandersonMS** [comment]
Thanks for reporting this. It was fixed in `generator-aspnetcore-spa` version 0.8.1.
