### ISSUE TITLE
Add support of Angular-Cli on angular 2 template

### ISSUE THREAD

**Issue by JanickRoss** [aspnet/JavaScriptServices#642]
Do you have plan to add support of angaular cli on template ?

**Comment by MarkPieszak** [comment]
So just speaking from an Angular CLI point of view, there are actually a lot of reasons why the two couldn't sync up unfortunately. :(

The CLI for example generates a scaffolding like this:
![image](https://cloud.githubusercontent.com/assets/2574412/22602681/29fd57ec-ea12-11e6-8ada-5af2f4d8e05d.png)

This has many issues with the way the templates are used here, for .NET has control over the View (index.cshtml), and also is aware of the webpack dev server, and building the webpack files.

What part of the CLI do you most wish was usable within a template outside of the CLI itself ?
I've been wondering if it'd be worth re-creating the generators for outside use.

**Comment by MarkPieszak** [comment]
Technically you **could** connect it, but you can only use some of the functionality, like the generator.
.NET handles so much of the integration here, that you can't "serve" or use other aspects of it.

You'd have to be using the Experimental 2.4.5 version from the generator also.
But you could **technically**:

```
npm i -g angular-cli
// go to the root of your project
ng init --source-dir clientapp

// prompts will come up:
// now you want to make sure you don't overwrite certain files...

? Overwrite clientapp\app\app.module.ts? No, skip
? Overwrite .gitignore? No, skip
? Overwrite karma.conf.js? No, skip
? Overwrite package.json? No, skip

npm i --D angular-cli
```

It's going to add a bunch of random files, you'll have to make sure to wipe all of those out.

The only real benefit is that you can "generate" components and such, but it won't have a connection to the NgModule, so you'll still have to manually add them in there.

---

So you can't:

- `ng serve` (you already have the .NET version of this when you start the project, it runs webpack etc), 
- `ng test` etc (this is already available through npm scripts)
etc

Hope that helps!

**Comment by SteveSandersonMS** [comment]
Thanks @MarkPieszak for the info. Agreed that it's not something that would produce a lot of extra value right now. However we will watch out for opportunities to add extra integration in the future.

**Comment by jrmcdona** [comment]
What is the best way to add tests?  Does anyone have a sample?

Thanks
