### ISSUE TITLE
Unable to change environment

### ISSUE THREAD

**Issue by larserikfinholt** [aspnet/JavaScriptServices#644]
Just downloaded latest, created a new aurelia spa but no reloading is happening, (I know there are issues with HMR, but basic reload of the entire page should work?) 

Maybe the reason is that is stuck in Production environment.

Tried 

- set ASPNETCORE_ENVIRONMENT=Development
- dotnet run --watch
- dotnet run --environment Development

I guess I'm missing something obvious here?

**Comment by zheylmun** [comment]
I've found this issue in Windows as well.  You can see that the environment when using dotnet run is still production.  It isn't keying off of the flag properly.

**Comment by SteveSandersonMS** [comment]
All the templates here support HMR, *except* for the Aurelia one unfortunately. This is because, last time we worked on the Aurelia template, the (required) Aurelia Webpack Plugin didn't support HMR.

If you are able to determine that Aurelia Webpack Plugin has been improved since then and now supports it, please let us know what changes are needed to enable it in the template. Thanks!

**Comment by larserikfinholt** [comment]
Sorry, but I may be wrong,  but I think this is not related to HMR. The
issue I am facing is that Im unable to change the environment to
development.

Den tir. 7. feb. 2017, 18.29 skrev Steve Sanderson <notifications@github.com

**Comment by chrisjmccrum** [comment]
in MacOS it seems to be working when i run `export ASPNETCORE_ENVIRONMENT=Development `

**Comment by zheylmun** [comment]
@chrisjmccrum: Absolutely, the command works as advertised MacOS.
I can confirm that it does not work as advertised on Windows across several machines.
set ASPNETCORE_ENVIRONMENT=Development
still results in a production environment when invoking dotnet run.

**Comment by chrisjmccrum** [comment]
Hmm sorry misread earlier when you said "It DOES work".  I took a peek at my api project that my dev team uses and did notice one difference with our Program class( `.AddEnvironmentVariables(prefix: "ASPNETCORE_"`). If you don't have that maybe that'll work for you. I know my devs that are on windows can run this project in development mode no problem (`dotnet run --environment Development`).

```
    public static class Program
    {
        public static string[] Args;
        public static void Main(string[] args)
        {
            Args = args;

            var config = new ConfigurationBuilder()
                .AddCommandLine(args)
                .AddEnvironmentVariables(prefix: "ASPNETCORE_")
                .Build();

            var host = new WebHostBuilder()
                .UseUrls("http://*:5000")
                .UseConfiguration(config)
                .UseKestrel()
                .UseStartup<Startup>()
                .ConfigureServices(services => services.AddSingleton(new ConsoleArgs(args)))
                .Build();

            host.Run();            
        }
    }
```
