### ISSUE TITLE
angular2-template-loader v0.6.1 is broken

### ISSUE THREAD

**Issue by SimonTestNet** [aspnet/JavaScriptServices#649]
The `angular2-template-loader` dependency needs to be fixed at v0.6.0 because v0.6.1 is broken (it doesn't work with relative paths). There's an [issue](https://github.com/TheLarkInn/angular2-template-loader/issues/50) for it but in the meantime the generator creates bad Angular environments.

**Comment by SteveSandersonMS** [comment]
Thanks for the report. I've published generator-aspnetcore-spa 0.8.2 which pins to `angular2-template-loader`. I'll revert that change once `angular2-template-loader` contains a fix for this.

**Comment by SteveSandersonMS** [comment]
Closing now the upstream issue in `angular2-template-loader` is fixed.
