### ISSUE TITLE
(0.8.2) React/Redux warning and errors on clean template generation

### ISSUE THREAD

**Issue by docrinehart** [aspnet/JavaScriptServices#651]
* loader option has been deprecated - replace with "use"
* (displays in console x2) ERROR in [at-loader] node_modules\@types\react-router-redux\index.d.ts:9:10
        TS2305: Module '"C:/repos/playground/serenityhr2/src/node_modules/@types/react-router/index"' has no exported member 'Location'.

Haven't had a chance to dig into it further yet.

**Comment by sad1y** [comment]
i have same problem and dont find appropriate @types version for it

**Comment by benhysell** [comment]
In Package.json I modified
 "@types/react-router-redux": "^4.0.30",
to
 "@types/react-router-redux": "4.0.30",

This will get things up and running for now.

**Comment by bpugh** [comment]
In addition to what @benhysell said, you can run `npm install @types/react-router-redux@4.0.30` to fix your existing installation until the typings can be fixed.

**Comment by SteveSandersonMS** [comment]
Thanks for reporting this. I've applied a fix (same fix as suggested here) in generator-aspnetcore-spa version 0.8.3 which will be published shortly. That new package also updates the Webpack configs to eliminate the `loader option has been deprecated` warnings.
