### ISSUE TITLE
Can not run project

### ISSUE THREAD

**Issue by MaklaCof** [aspnet/JavaScriptServices#657]
I follow [this blog](http://blog.stevensanderson.com/2016/05/02/angular2-react-knockout-apps-on-aspnet-core/).

> ? Framework Angular 2.4.5 (experimental)
> ? What type of project do you want to create? .csproj      (compatible with .NET Core tooling preview 3 and Visual Stud
> io 2017)
> ? Do you want to include unit tests? No
> ? Your project name OpPISWeb

Then I open project with VS 2017 and it failed with error. (look screenshot)
I also try to run dotnet run and it also failed.
![runerror](https://cloud.githubusercontent.com/assets/1589573/22778596/cbcb8f68-eeb7-11e6-9666-52da8651a732.PNG)

Just for test I create and successfully run new ASP.NET Core Web Application (.Net Core) project.

**Comment by SteveSandersonMS** [comment]
I think you must be running an old version of VS2017RC. Older versions of VS2017RC don't include up-to-date versions of .NET Core tools, which are required.

I've just verified it works correctly with the current version, which is VS2017RC build 26206. Please update. Thanks!
