### ISSUE TITLE
error MSB4019: The imported project "../Microsoft.DotNet.Props" was not found. 

### ISSUE THREAD

**Issue by nrgjack** [aspnet/JavaScriptServices#658]
hi everyone, 

running 
> yo aspnetcore-spa

i selected angular 2.0.2, yes to unit tests, project.json

yo seems to go smoothly, it creates the project, runs npm, then it stats populating my local package cache, 
unfortunately after expanding i get the error in the title 
![image](https://cloud.githubusercontent.com/assets/11472052/22781863/c4ac0a20-eec4-11e6-9539-0f048f4d6acf.png)

my dotnet informations are : 
![image](https://cloud.githubusercontent.com/assets/11472052/22781818/906ea2ae-eec4-11e6-87f6-f4f99b59b8f0.png)

aftewr that i try to open the solution with VS 2017

i can see the solution 
with the project (loading..)

after a while VS 2017 crashes...

i tried 4 or 5 times, 

the latest the project succeded loading... 

can i ignore the issue ?

thanks

**Comment by SteveSandersonMS** [comment]
`project.json` is not compatible with VS2017. Please re-run the generator, and this time, choose `csproj` instead.
