### ISSUE TITLE
Lazy loading is not working with aspnet core

### ISSUE THREAD

**Issue by ravimittal16** [aspnet/JavaScriptServices#660]
Hello,

I am facing hard time to make the lazy loading working with aspnet-core and angular 2. 

tried this
`{ path: 'home', loadChildren: () => require("./components/home/home.module")("HomeModule") }`
AND
`{ path: 'home', loadChildren:() =>   "./components/home/home.module#HomeModule" },`

also tried this plugin 

[Angular 2 lazy loading with Webpack](https://medium.com/@daviddentoom/angular-2-lazy-loading-with-webpack-d25fe71c29c1#.eryzjegp6)
but facing the same issue.

**Comment by SteveSandersonMS** [comment]
See this comment for hints on setting it up: https://github.com/aspnet/JavaScriptServices/issues/465#issuecomment-264200617

**Comment by ravimittal16** [comment]
this is not working with webpack 2

**Comment by SteveSandersonMS** [comment]
That's interesting. I'm surprised that Webpack 2 makes a difference, but maybe `angular2-router-loader` somehow isn't fully compatible with it. If so, you might need to take this up with the `angular2-router-loader` maintainers (or at least, they should know whether or not it's compatible with Webpack 2).

It's not something I can look into at the moment, but if you figure out a solution please let us know!

**Comment by ravimittal16** [comment]
okay, i have reported the same issue to `angular-router-loader` maintainers.
