### ISSUE TITLE
redux store created AFTER router match while doing server-side rendering in ReactReduxSpa

### ISSUE THREAD

**Issue by HaraldMuehlhoffCC** [aspnet/JavaScriptServices#663]
I'm using `onEnter` in some Route elements that require authentication. On client-side things just worked; when rendered on server I got exceptions. As it turned out I was trying to access login-related info in the redux store in the function called by `onEnter` and it wasn't configured yet by `boot-server.tsx`. A simple issue to correct once I found it. To help other poor souls it might be a good idea to move the `configureStore()` call before the match in the template so client and server-side work the same.

[https://github.com/aspnet/JavaScriptServices/blob/dev/templates/ReactReduxSpa/ClientApp/boot-server.tsx](https://github.com/aspnet/JavaScriptServices/blob/dev/templates/ReactReduxSpa/ClientApp/boot-server.tsx)

**Comment by KraigWalker** [comment]
Is the problem not that you're trying to run logic in a method that will only be executed on the client side?.  

Would it not be better to put your auth logic in something like ComponentWillMount instead?

**Comment by HaraldMuehlhoffCC** [comment]
@KraigWalker Thx for your comment. Actually the logic is executed also on the server-side ... and from what I understand about Route `onEnter` it's exactly the place to do things like authentication &ndash; and a redirect to login if not authorized (there are lot's of examples on the web). Once I moved the `configureStore()` in `boot-server.tsx` before the `match` things are working out as expected (`redirectLocation` is set and the login rendered)

**Comment by SteveSandersonMS** [comment]
Thanks for the suggestion. This change is now made and will be included next time the templates are published.
