### ISSUE TITLE
Missing import isomorphic-fetch

### ISSUE THREAD

**Issue by kelong** [aspnet/JavaScriptServices#664]
In Aurelia
import "isomorphic-fetch";
is missing in boot.ts

I would add it, but I think I dont have privileges to create branch.

**Comment by MarkPieszak** [comment]
So what you want to do is Fork the Repo, create a branch there (in your fork), you can submit a PullRequest from there which will show up here 👍

**Comment by kelong** [comment]
Ok, done, thank you
