### ISSUE TITLE
how to generate a smaller vendor.js file?  vendor.js file size is not minified or uglified when running the vendor webpack

### ISSUE THREAD

**Issue by btmadison** [aspnet/JavaScriptServices#668]
At close to 5 MB this is very high for a production build, and I notice the vendor.js file served when in production mode is not compressed or uglified.

I have set the environment variable in the console to Production instead of Development and rerun the webpack with the vendor config.  Actually with either Dev or Prod, the resultant vendor.js file that is generated is the same size.

Is there a step I am missing to generate a smaller tree shaken, minified and uglified vendor.js file?

**Comment by SteveSandersonMS** [comment]
Sounds like you're missing the `--env.prod` flag:

    webpack --config webpack.config.vendor.js --env.prod

**Comment by btmadison** [comment]
thanks, this brought it down to closer to 3 from over 7 (with some additional libraries I needed) thanks - FYI the instructions in the site readmedo not mention this for production mode - thanks for your quick response and help though!  FYI the instructions link to your blog with instructions that only mention the following: Make a production build. Set the ASPNETCORE_ENVIRONMENT variable to Production and then run (may want to update with the step you just mentioned here:

webpack --config webpack.config.vendor.js
webpack
…to regenerate both the vendor and app bundles. Now when you run the app (dotnet run again), the browser will receive fully minified resources.

Thanks again
