### ISSUE TITLE
Angular 2 SPA Docker: Can't access site

### ISSUE THREAD

**Issue by EduardTheThird** [aspnet/JavaScriptServices#669]
Hi Guys

Hope you are well!

I've noticed strange behaviour regarding Docker containers and Angular2Spa where I can't access the site using the published IP port as usual. Opening the site on the published port, does not trigger activity on the Docker container. I did not see any obvious errors upon building the Docker image.

![docker1](https://cloud.githubusercontent.com/assets/6488837/22877120/96e15198-f1dc-11e6-942e-10508c89c727.PNG)
![docker2](https://cloud.githubusercontent.com/assets/6488837/22877124/9835328a-f1dc-11e6-9cc5-a223fd699496.PNG)

To ensure it is not something I changed on my project, I've created a freshly generated Angular2Spa (2.4.5) using generator-aspnetcore-spa 0.8.3 and generated a clean unmodified Docker image for Angular2Spa. 

The test docker image shown above is available from the Docker hub-> https://hub.docker.com/r/lightfleet/jssdocker/

Please let me know if you need more detail or if I can be of any assistance.

Thanks!

**Comment by pysco68** [comment]
Hi there, 

I just had a similar issue (albeit with the Aurelia template). I solved it by adding an env variable:
ASPNETCORE_URLS=http://+:5000

Could you give that a try?

**Comment by EduardTheThird** [comment]
Your suggestion saved our docker deployments, thank you @pysco68!

I can confirm that this worked for Angular 2. I've added a new pull request for the fix https://github.com/aspnet/JavaScriptServices/pull/687.

**Comment by pysco68** [comment]
You're welcome! Glad I could help.
 Still debugging another issue in the same context atm ^^"

**Comment by SteveSandersonMS** [comment]
Thanks for reporting this and submitting the PR.

As discussed in #687, we're removing the `Dockerfile` to be more consistent with other ASP.NET templates. Developers using Docker can add their own `Dockerfile` with their own config. As such, this is no longer applicable so I'll close it.
