### ISSUE TITLE
Prerendering tag helper should support setting HTTP status codes

### ISSUE THREAD

**Issue by TE2s** [aspnet/JavaScriptServices#673]
Is it possible to return a 404 status code for a specific route?

Right now I have my router set up with this as the last route:
`<Route onEnter={listen} path="*" components={{body: NotFound}} status={404} />
`
however, if I hit the route it is coming back as a 200.  Is there a way to set up the prerendering to return a 404 status code for this route?

**Comment by peterlazzarino** [comment]
I am wondering the same thing.

**Comment by SteveSandersonMS** [comment]
Good suggestion. The way we'd implement this is by amending the .NET-side `PrerenderingTagHelper` to look out for the JS-side code specifying a nonempty `StatusCode` property on the `RenderToStringResult`. When it sees such a value, it would assign it to the response status code. Then in your `boot-server.ts`, you could use whatever logic you want to set that value, for example based on the `status` property of the matched route.

If you feel like you could implement this yourself, we'd happily take a pull request for this. If not, no worries, we can keep it on the backlog and it will be implemented at some point.

**Comment by SteveSandersonMS** [comment]
There's now a PR for this (#700 - thanks @peterlazzarino!) so I'll close this issue as a "duplicate" of that one.
