### ISSUE TITLE
Add prerender pipeline hooks for better extensibility

### ISSUE THREAD

**Issue by laskoviymishka** [aspnet/JavaScriptServices#68]
This need some design, so i address it to @SteveSandersonMS, if you good with such approach i could implement this.
So for better extensability it will be realy nice to have some pipeline injects to manage some additional variables passing from asp.net server directly to server JS (like some auth info beside cookie, or may be initial state of Redux store, so we don't have to grab it from web api via additional http requests).
For example there is could be some `PrerenderOptions` class which could be extended via calling `AddPrerender` method in `ConfigureServices` method of application startup class. This method just register some hepler interface to run prerender manually and setup prerender opions.
This options could be something like
```
 public class PrerenderOptions
 {
        public Action<Request, NodeInvocationInfo> BeforeRenderModule{ get; set; }

        public NodeServicesOptions() {
            this.HostingModel = _ => { };
        }
 }
```

Inside on `NodeInvocationInfo` options already `Args[]` property which passing directly to the JS Module invocation, so we could push anything to our JS code from server via this hook.

This is kinda realted to issue #66 (both require prerry much same refactoring, to establish clearer pipeline for prerendering process).

**Comment by SteveSandersonMS** [comment]
> it will be realy nice to have some pipeline injects to manage some additional variables passing from asp.net server directly to server JS (like some auth info beside cookie, or may be initial state of Redux store, so we don't have to grab it from web api via additional http requests)

Totally agree. It seems to me that your `asp-prerender-model` proposal would cover this requirement. You could use that to pass any information you wanted into your server-side boot function.

Would that be sufficient? I'm hoping we don't need to introduce anything more complex than that, because there are already a lot of unfamiliar wiring concepts that developers have to deal with here.

**Comment by laskoviymishka** [comment]
Well, hooks very usefull to push data to every SPA you have (like user info or claims list or may be roles). 
Model is usefull to populate initial state.

**Comment by SteveSandersonMS** [comment]
I mean "model" in the general sense. It can contain any information - for example a combination of user info, claims list, initial data, etc.

**Comment by SteveSandersonMS** [comment]
From your comment it sounds like #107 can be generalised enough to cover this requirement, so closing this issue in favour of #107. Please reopen if you disagree!

**Comment by laskoviymishka** [comment]
@SteveSandersonMS general information is still very usefull. If you need to pass to every SPA you have something, you need to create somekind of decorator to modify your model. And this is extra action you need to do. Like for same scenario with auth:
We have model passed to our View with some Data field.
```
<app asp-prerender-mode="Model"/>
```
And you pass just this data, and if you wanna to push User infor with this data, you have to create addtional ViewModel, and populate it some how. 
```
@{
var decoratedModel = new DecoratedViewModel(Model, UserInfo);
}

<app asp-prerender-mode="decoratedModel "/>
```
What if you have 20 modules, each of them have different view model? You need to create some sort of abstraction around it. This scenario easily handled by such hook.
