### ISSUE TITLE
Troubleshooting after "git clean"

### ISSUE THREAD

**Issue by logischdenker** [aspnet/JavaScriptServices#680]
This may be obvious for most developers, that are familiar with all the npm and webpack stuff. But as I heard of some guys having trouble getting an "aspnetcore-spa" application back to work after they run `git clean` or just cloned a repository with an existing "aspnetcore-spa" application, this is for you!

- First of all make sure you have installed webpack globally by running `npm install -g webpack` from the command line.
- Change to your project's root directory and run `npm install` to restore the "node_modules" folder
- Now run `webpack --config webpack.config.vendor.js` and finally `webpack` to make a production build (this will "restore" the "ClientApp/dist" and "wwwroot/dist" folders)

Now you should be up and running again, after a cleanup of your repository.

All this is also explained within a blog post of Steven Sanderson under "How do I start?" : 
http://blog.stevensanderson.com/2016/05/02/angular2-react-knockout-apps-on-aspnet-core/

There is just one little hint missing "that you have to redo some of the steps after cleaning your repo".

I hope this may help others getting over the problem.

Btw. thank you for "aspnetcore-spa" - this saved me lots of time and trouble getting started with Angular2 and an ASP Net Core application!

**Comment by SteveSandersonMS** [comment]
Thanks for posting this. Hopefully it will be helpful for others!
