### ISSUE TITLE
build c# code (watcher)

### ISSUE THREAD

**Issue by vip32** [aspnet/JavaScriptServices#682]
hi, these templates are just great!

what is the story to build the c# code, i mean the controllers.
if 'dotnet run' is active (hmr is also great) then compiling is not possible (dll in use). it would be nice if dotnet run' was also able to compile the c# code when changed, with a watcher or so.

how do you handle this dev worklow?

**Comment by MarkPieszak** [comment]
Does `dotnet watch run` not work?

**Comment by vip32** [comment]
if that works it would be great and something for the 'get started' docs.
let me check it out

**Comment by vip32** [comment]
yes, it works when the watcher is added. thx for pointing that out 👍 

.csproj:
```
<ItemGroup>
    <DotNetCliToolReference Include="Microsoft.DotNet.Watcher.Tools" Version="1.0.0-msbuild3-final" />
</ItemGroup>

**Comment by pflannery** [comment]
I was just following the MVA "Single page Applications" video [here](https://mva.microsoft.com/en-US/training-courses/intermediate-aspnet-core-10-16964?l=b5VHZMmJD_3806218965) and it failed for me when @csharpfritz instructs students to run the "dotnet run watch" command. I had to include the cli tool in the csproj before I could continue.

It would be very useful to include the cli tool in each yo template csproj file.
