### ISSUE TITLE
Upgrade to VS 2017

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/JavaScriptServices#684]
We're going to be [removing Korebuild support](https://github.com/aspnet/KoreBuild/pull/171) for project.json soon. This repo should upgrade soon or [pin](https://github.com/aspnet/Mvc/commit/dc590fbb8e988d3e6a2493adbb8c24af2efb5b5f#diff-f0e02e42e53ec40f5d3b8bed031ad09eR36) korebuild to a project.json compatible version.

cc @SteveSandersonMS

**Comment by MarkPieszak** [comment]
What about vs2015 project support? @natemcmaster

**Comment by natemcmaster** [comment]
We are upgrading all of our repos to build with VS 2017. The packages we produce will still work with project.json and vs 2015.

**Comment by MarkPieszak** [comment]
That's incredible news! 
Thanks Nate.

**Comment by SteveSandersonMS** [comment]
This is being tracked in PR #703 so I'll close this issue.
