### ISSUE TITLE
WebPack for ES6

### ISSUE THREAD

**Issue by Serginio1** [aspnet/JavaScriptServices#685]
Please add the template to support EC6 article in Russian here

[CEF, ES6, Angular 2, WebPack 2 .Net Core desktop application without the server side](https://habrahabr.ru/post/321898/)

https://habrahabr.ru/post/321898/

There the contents of all the necessary files

Examples can be downloaded here https://yadi.sk/d/0If7C5jZ3CEhmf

**Comment by SteveSandersonMS** [comment]
Thanks for the suggestion. We're not planning to add extra third-party templates here, because `dotnet new` itself already supports third-party extensibility. The people who built that template can publish it to NuGet themselves if they want to.
