### ISSUE TITLE
Always override JsonSerializerSettings; don't use defaults as they might be nonstandard

### ISSUE THREAD

**Issue by senritsu** [aspnet/JavaScriptServices#688]
With a setup according to the documentation in the readme ([here](https://github.com/aspnet/JavaScriptServices/tree/dev/src/Microsoft.AspNetCore.SpaServices#webpack-dev-middleware) and [here](https://github.com/aspnet/JavaScriptServices/tree/dev/src/Microsoft.AspNetCore.SpaServices#webpack-hot-module-replacement)) HMR doesn't seem to work at all.

The server is running dot net core SDK 1.1 and the bundles are built with webpack@latest (2.x). Server runs in development mode.

The dev middleware itself seems to work well enough, even though it does generate files on disk inside the `publicPath` folder specified in the webpack config (the somewhat default `wwwroot/dist/`). According to the docs it should serve from memory, so that by itself is a bit unexpected already.

Even with `HotModuleReplacement = true` in the middleware options and/or the `HotModuleReplacementPlugin` plugin in the webpack config, nothing changes. The HMR connection message in the browser console never appears, and it does not react to source changes in any way other than just rebuilding the bundles. Reloading the page manually correctly loads the updated bundles.

Is there something missing from the docs that could result in the HMR middleware not being run correctly?

In an older issue (#603) someone reported it started working after he reinstalled VS and .NET, something i haven't tried yet due to the time it takes to do so, but i will check it from a different PC to see if this might be the same issue.

**Comment by senritsu** [comment]
So, after some debugging in the aspnet-webpack npm module, the issue seems to be the assumed JSON conversion options used to serialize the webpack options in the C# middleware. `createWebpackDevServer` in `WebpackDevMiddleware.js`package expects PascalCased property names in the options object.

The `WebpackDevMiddleware` serializes the options object using `JsonConvert.SerializeObject` with default options.

In our project we changed the default contract resolver for the JSON serializer to the `CamelCasePropertyNamesContractResolver`, so the casing does not match and the options that arrive in the relevant functions in the `WebpackDevMiddleware.js` are all `undefined`.

**Comment by senritsu** [comment]
It seems to be a workable workaround to just use a subclass of the contract resolver and add a special case for the `WebpackDevMiddlewareOptions` type.

```csharp
public class WebpackWoraroundContractResolver : CamelCasePropertyNamesContractResolver
{
    protected override JsonContract CreateContract(Type objectType)
    {
        if (objectType == typeof(WebpackDevMiddlewareOptions))
        {
            return new DefaultContractResolver().ResolveContract(objectType);
        }
        return base.CreateContract(objectType);
    }
}```

**Comment by SteveSandersonMS** [comment]
Thanks for reporting this. You're right: we shouldn't rely on `JsonSerializerSettings` being left in its default state. We should always override them.
