### ISSUE TITLE
Has anyone swapped in React/MobX in place of React/Redux?

### ISSUE THREAD

**Issue by mcquiggd** [aspnet/JavaScriptServices#689]
Before I start on this myself, and as I am still new to MobX, I wondered if someone had taken the React/Redux template and ported it to use MobX instead....?

I would appreciate any pointers / links to repos, if they exist...

_(p.s. don't try to type a post on GitHub using a tablet, when sitting next to a playful 2 year old Labrador)_

**Comment by SteveSandersonMS** [comment]
Doesn't sound like this is a common project setup, though in principle it certainly should be possible.

I'll mark this as closed as it's not a bug or enhancement, but people can feel free to continue discussing it here if desired.
