### ISSUE TITLE
.map files included in published wwwroot/dist/

### ISSUE THREAD

**Issue by HaraldMuehlhoffCC** [aspnet/JavaScriptServices#696]
I was quite stunned for a second that I found the `map` files included in my published ReactReduxSPA. 

The `publishOptions exclude` entry in `project.json` seems to be ignored since the move to the new (old) `.pubxml` file.

```
  "publishOptions": {
    "include": [
      "appsettings.json",
      "ClientApp/dist",
      "Views",
      "web.config",
      "wwwroot"
    ],
    "exclude": [
      "wwwroot/dist/*.map"
    ]
  },
```

I tried to add something like the following to my `CustomProfile.pubxml`:

```
    <ExcludeFilesFromDeployment>
      wwwroot\dist\*.map
    </ExcludeFilesFromDeployment>

```

(or `wwwroot/dist/*.map` ...) but so far was out of luck. 

The `map` files are older than the other files in `dist` but they are copied nonetheless.

For now I'm manually deleting the `map` files but an automatic solution would be preferred ;)

PS: BTW - thanks for a great start template! I've rebuilt my complete website as a universal ReactReduxSPA ;) (www.carecom.de)

**Comment by SteveSandersonMS** [comment]
The `project.json` tooling is being deprecated, so we probably won't add any further enhancements to those files, or even any noncritical fixes. Everything is moving to `.csproj`-based tooling.

Glad you've got a good solution for your own requirements though!
