### ISSUE TITLE
tsx - Babel loader in webpack.config.js

### ISSUE THREAD

**Issue by martinnov92** [aspnet/JavaScriptServices#698]
Hello, I was having issues with this `{ test: /\.ts(x?)$/, include: /ClientApp/, use: 'babel-loader' },` in your webpack.config.js (It used to display errors when building minif. production files.).
I change it to `{ test: /\.js(x?)$/, include: /ClientApp/, use: 'babel-loader' },` and now it's working properly. 

Shouldn't it be **.js(x?)$**:  `{ test: /\.js(x?)$/, include: /ClientApp/, use: 'babel-loader' },` when we are using babel-loader instead of tsx? 
Hope it makes sense.
Thank you

**Comment by SteveSandersonMS** [comment]
In the React templates in this repo, the source files are `.tsx`, so the Webpack config is correct as-is. You'd only change it to `.jsx` if you change your source files. The fact that you're using `babel-loader` is not relevant to the loader rules - all that matters are the names of the actual files on disk.
