### ISSUE TITLE
Injection Tree Inheritance

### ISSUE THREAD

**Issue by rpampin** [aspnet/JavaScriptServices#699]
As indicated at Angular 2 Docs, if one includes a provider on AppModule, every single child module should inherit those services.

Here's a [plnkr](https://plnkr.co/edit/GCBRgpgsAMoiP4i0FRCQ) I've made pretty quick. I have a service that function as an http interceptor. Inside I create a random seed to see if the service is created anew when a lazy module is loaded. If you run this code, changing from HomeComponent to LazyComponent and clicking on Request, on the console I get the same seed value. So it seems to work as advertised.

Now I'm trying to do the same thing with aspnetcore-spa. The first thing I did was add **angular2-router-loader** to load lazy modules with webpack, but the injector is not inherited. If I make any Http call inside a component of my LazyModule, nothing is intercepted. Whereas I make a request inside an eager loaded module, it works and with the same seed value.

I've tried adding the CoreModule to the LazyModule imports, but doing so creates a new instance of the interceptor service.

Is this something that should be working and it isn't, or am I missing something?

**Comment by rpampin** [comment]
Also to take into consideration.

This [example](https://github.com/daviddt/angular2-lazy-load-example/tree/master) in github use Angular CLI and Webpack. I downloaded the code, added CoreModule and put it as a provider into AppModule.

In both eager and lazy loaded modules in the example, the interceptor is working and showing the same seed on either module.

**Comment by SteveSandersonMS** [comment]
Interesting question, but I think it would be better if you followed up with the Angular community given that this is a fairly advanced Angular usage question. The Angular template in this repo is just Angular+TypeScript+Webpack (we haven't in any way modified how any of those things work), so whatever normally works with those will work here too. Sorry I can't give you a more useful answer. Anyone else who has more insight is welcome to post here. 

I'll mark this as closed as it doesn't appear to be an issue with any of the code in this repo, but if you do track it down and think we have some sort of defect here, please reopen with details. Thanks!
