### ISSUE TITLE
Angular 2 question - Protractor

### ISSUE THREAD

**Issue by markpritchett** [aspnet/JavaScriptServices#702]
How can I add Protractor E2E tests?  Will it require some kind of boot file (`boot-tests.ts`) like the unit tests?

**Comment by SteveSandersonMS** [comment]
That's an interesting question, but I'd recommend you put this to the Protractor community. The Angular project here is a standard Webpack+Angular2 setup (as far as the Angular part is concerned anyway; it doesn't need to know or care that the server is ASP.NET), so whatever is a standard Protractor setup should work just the same. Hope that's OK!
