### ISSUE TITLE
TS2.2 doesn't like "@types/whatwg-fetch"

### ISSUE THREAD

**Issue by benaadams** [aspnet/JavaScriptServices#705]
https://github.com/Microsoft/TypeScript/issues/4948#issuecomment-279109510 (Sounds like issue with isomorphic-fetch also)

The entry
```
"@types/whatwg-fetch": "0.0.28",
```
Needs to be removed from in fex. [ReactReduxSpa/package.json](https://github.com/aspnet/JavaScriptServices/blob/dev/templates/ReactReduxSpa/package.json#L14)

But then [domain-task](https://github.com/aspnet/JavaScriptServices/blob/dev/src/Microsoft.AspNetCore.SpaServices/npm/domain-task/package.json) doesn't like it as its a dependency 😞 

[Breaking-Changes#typescript-22](https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#typescript-22)

**Comment by benaadams** [comment]
Or maybe temporally change typescript from major version `"typescript": "^2.0.3",` to minor version `"typescript": "~2.0.3",`?

**Comment by SteveSandersonMS** [comment]
Thanks for reporting this!

To fix this, I've updated the templates' TS dependencies to 2.2.1+. This meant that the `@types/whatwg-fetch` package references could be removed, since `fetch` is now included in the TS standard lib.

The updated templates will be published as version 0.8.6 shortly.

**Comment by emirotin** [comment]
It would be nice if the updated typings have kept the parity with the `whatwg-fetch` types.
Specifically the typed version of `Body#json<T>()` would be nice to have: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/whatwg-fetch/index.d.ts#L39

**Comment by kuncevic** [comment]
Similar story here https://github.com/angular/angular-cli/issues/5692 any thoughts?
