### ISSUE TITLE
Cannot open csproj after installing aspnetcore-spa

### ISSUE THREAD

**Issue by im1dermike** [aspnet/JavaScriptServices#708]
I ran `yo aspnetcore-spa` on my machine and it successfully created various files.  When I try to open the *.csproj file up in VS2015 Community, I get the following error:

> The default XML namespace of the project must be the MSBuild XML namespace.  If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element.  If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.

I attempted to add the suggested xmlns value to the *.csproj file, but get a new error.

FWIW, when I run `dotnet --version`, it returns `1.0.0-preview2-003131`.

**Comment by Ketrex** [comment]
You're not going to be able to run the csproj version in VS2015. However, you can use VS Code as long as you update your dotnet version. You can get the latest SDK release [here](https://github.com/dotnet/core/blob/master/release-notes/rc3-download.md).

Alternatively, you can run the yeoman generator again and choose the project.json version. This will run in 2015 with no problem.

**Comment by MarkPieszak** [comment]
The repos will require: 
VS 2017, 
VS Code + C# 1.7, 
or .NET Core CLI `1.0.0-rc4`

**Comment by SteveSandersonMS** [comment]
Thanks @Ketrex and @MarkPieszak for posting the answers.

Just to emphasise, as per @Ketrex's comment, you *can* use VS2015 if you want, but you need to generate a `project.json`-based project and *not* a `.csproj`-based project. However, at this stage, it's probably better for you just to upgrade to VS2017 (since you're on the community editions, so it's free anyway).

**Comment by im1dermike** [comment]
I'm still unable to open the project.  I upgraded my .NET Core SDK version to 1.0.0-preview2-003131.  Now `dotnet --version` returns `1.0.0-rc4-004771`.  After running `yo aspnetcore-spa`, opting for the package.json option, and then trying to open the *.xproj in VS 2015 after completion, I get the following exception:

> The project is configured to user .NET Core SDK version 1.0.0-preview2-1-003177 which is not installed or cannot be found under the path C:\Program Files\dotnet.

I then installed VS 2017 Community and tried to open the *.xproj file.  It prompts me to do a one-way upgrade to a *.csproj file and ultimately gives the following exception when attempting to do so:

> An internal error occurred.  Please contact Microsoft Product Support Services.

**Comment by jckh1234** [comment]
I want to open the project in vs2015. I don't have vs2017

Is yeoman generator have option to choose project.json (I can't find the option in v.0.0.9) or have to use separate generator?

Or are there any tools to convert the csproj to project.json?

**Comment by SarahWallis** [comment]
Or how do you tell yeoman to create a project.json? 
Also, I just downloaded Community 2017 and tried to open the csproj and got the same error. Why is this?

**Comment by SteveSandersonMS** [comment]
@jckh1234 @SarahWallis The option to produce `project.json`-based projects was discontinued a few months back with the 0.9.0 release (we only have the resources to support the current technology stack). If you need VS2015 support, please use a version of `generator-aspnetcore-spa` in the 0.8.x range where this option still existed. Hope that's OK!
