### ISSUE TITLE
Failed typescript build task for npm projects

### ISSUE THREAD

**Issue by goaty92** [aspnet/JavaScriptServices#71]
The current tsconfig.json files are structured to take all *.ts files as inputs (except those from node_modules). 
```javascript
{
  "compilerOptions": {
    "moduleResolution": "node",
    "module": "commonjs",
    "target": "es5",
    "declaration": true,
    "outDir": "."
  },
  "exclude": [
    "node_modules"
  ]
}
```
This causes errors like this since the output definition file *.d.ts are also taken as inputs so they can't be overwritten.
![fail](https://cloud.githubusercontent.com/assets/11325809/15269163/30301292-1a21-11e6-82e0-444b28acac96.jpg)
I think it would be great if we could have a unified packaging model for node projects. tsconfig.json files like this would pass the build
```javascript
{
  "compilerOptions": {
    "moduleResolution": "node",
    "module": "commonjs",
    "target": "es5",
    "declaration": true,
    "outDir": "./lib/"
  },
  "exclude": [
    "node_modules",
    "lib"
  ]
}
```
and then in package.json
```javascript
{
  "name": "redux-typed",
  "version": "1.0.0",
  "description": "Helpers for building React+Redux apps with strong TypeScript type checking everywhere",
  "main": "lib/main.js",
  "typings": "lib/main.d.ts",
  "scripts": {
    "prepublish": "tsd update && tsc && echo 'Finished building NPM package \"redux-typed\"'",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "Microsoft",
  "license": "Apache-2.0",
  "devDependencies": {
    "typescript": "^1.8.10"
  }
}
```

**Comment by laskoviymishka** [comment]
Great point, take my :+1: 
Also i suggest to add some prebuild task to package.json to remove this file before build.

**Comment by SteveSandersonMS** [comment]
This was fixed recently (the builds now use `rimraf` to remove any previously-built `.d.ts` files).
