### ISSUE TITLE
Using asp-prerender-module with Office 365 Fabric and React

### ISSUE THREAD

**Issue by wiredprairie** [aspnet/JavaScriptServices#711]
I'm trying to use server-side prerendering with [Office 365 Fabric components](https://github.com/OfficeDev/office-ui-fabric-react).

I'm not sure what the best way to handle their method of injecting styles would be.

    import { configureLoadStyles } from '@microsoft/load-themed-styles';

    // Store registered styles in a variable used later for injection.
    let _allStyles = '';

    // Push styles into variables for injecting later.
    configureLoadStyles((styles: string) => {
      _allStyles += styles;
    });

The `_allStyles` must be injected into a `style` tag:

    <style>${ _allStyles}</style>

Should I create another `asp-prerender-module` to be included in `_Layout.cshtml`, or is there a more elegant (and possibly more efficient) method for doing this style/string injection?

**Comment by SteveSandersonMS** [comment]
Having a second `asp-prerender-module` tag, if that works for you, would be the simplest solution.

An alternative but more complex solution would be as follows: https://github.com/aspnet/JavaScriptServices/issues/607 The code there can receive back arbitrary data from the prerendering phase, which you can then inject into your view. Right now, this involves a bunch of nontrivial logic, but we are going to make a simpler API for doing it (which is what #607 is there to track).
