### ISSUE TITLE
Cannot regenerate dist/vendor.css file

### ISSUE THREAD

**Issue by victorantos** [aspnet/JavaScriptServices#713]
I have deleted the content of `dist/vendor.css ` and now I cannot regenerate the css.

When I build/debug there is no css being served from server, the file empty.

How to run force webpack to generate the css? 
It used to be the bootstrap css inside that file.

**Comment by MarkPieszak** [comment]
Run webpack --config webpack.config.vendor.js

**Comment by victorantos** [comment]
Long story short - it worked, thanks!

But this is not straight forward as it looks like, I had to deal with "webpack" not being recognised, and then npm install webpack not fixing the issue either, until I reinstalled angular cli latest and then webpack again...

**Comment by pavel-agarkov** [comment]
Does that mean I have to manually run
`webpack --config webpack.config.vendor.js`
every time I need to include a new css-module relation?

**Comment by samboustani** [comment]
Running `webpack --config webpack.config.vendor.js` didn't work.  Still no vendor.css in the dist folder.

**Comment by ovidiaconescu** [comment]
You don't need the `vendor.css` in your dist folder. The styles are automatically added by webpack in `main.js`. Use a text editor and inspect that file. It should be a big chunk of incomprehensible JavaScript, but if you search for a css property that you added in your `site.css`, you'll see that it's bundled in there.

Just take out the refecene to your vendor.css from the `_Layout.cshtml`
