### ISSUE TITLE
Strange output and frozen package manager console

### ISSUE THREAD

**Issue by jfreal** [aspnet/JavaScriptServices#716]
When I run yo aspnetcore-spa I get this output and the package manager console appears stuck.  Hitting enter, arrow keys, or any keys do nothing.

Seems like something is wrong?

yo : 
At line:1 char:1
+ yo aspnetcore-spa
+ ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
     _-----_     â•­â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•®
    |       |    [0mâ”‚[0m  [0mWelcome to the ASP.NET[0m  [0mâ”‚[0m
    |--(o)--|    [0mâ”‚[0m   [0mCore Single-Page App[0m   [0mâ”‚[0m
   `---------Â´   [0mâ”‚[0m        [0mgenerator![0m        [0mâ”‚[0m
    ( _Â´U`_ )    [0mâ”‚[0m             [0m[0m             [0mâ”‚[0m
    /___A___\   /[0mâ”‚[0m      [0mVersion: 0.8.6[0m      [0mâ”‚[0m
     |  ~  |     [0mâ•°â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•¯
   __'.___.'__   
 Â´   `  |Â° Â´ Y ` 

[?25l? Framework (Use arrow keys)
> Angular 
  Aurelia 
  Knocko

**Comment by SteveSandersonMS** [comment]
Looks like the package manager console doesn't support colours, so in general you will have problems with Yeoman or other tools that commonly use them.

I'd recommend using a different command line that does support colours (e.g., `cmd.exe`, or the standalone Powershell console, or Cmder, or pretty much anything else).
