### ISSUE TITLE
Node.js : error when using "now" module

### ISSUE THREAD

**Issue by pascalReygner** [aspnet/JavaScriptServices#718]
i have installed js and now modules in my project .
   "npm install js + npm install now + npm init"
the package.json generated  file seems correct
application  with "js" module works correctly.
but when using "now" module ("var nowjs = require('now');") their is an error :
  "Error: Cannot find module 'now'.
module "now" is present in project\node-modules.
Do you have any idea for solving this
Thank you

**Comment by SteveSandersonMS** [comment]
From the 'now' docs (https://zeit.co/now#features), it doesn't appear that 'now' is a regular NPM package that you can `require` in that sort of way. It's a standalone CLI tool, not a package you can import.

**Comment by pascalReygner** [comment]
Thank you
