### ISSUE TITLE
Add dotnet-template tag

### ISSUE THREAD

**Issue by sayedihashimi** [aspnet/JavaScriptServices#720]
I have created a "dotnet-template" tag in github, can you add the tag to this repository so it shows up in the [dotnet-template](https://github.com/search?q=topic%3Adotnet-template&type=Repositories) search result?

**Comment by SteveSandersonMS** [comment]
I don't have the necessary permissions on this repo.

@Eilon, could you add the `dotnet-template` topic to this repo? Instructions here: https://help.github.com/articles/classifying-your-repository-with-topics/

**Comment by Eilon** [comment]
Done!

**Comment by sayedihashimi** [comment]
Thanks
