### ISSUE TITLE
support for ES6 and Webpack in Visual Studio 2017 RC

### ISSUE THREAD

**Issue by stefan2410** [aspnet/JavaScriptServices#723]
In the asp.net core views, I use  my JavaScript objects. I need an easy way to write ES6 code and get other required libraries, to be transpiled and  bundled in Visual Studio 2017 RC, using Webpack.  Do you have a template, to support this process in VS2017, only for our JS libraries ?
thanks

**Comment by SteveSandersonMS** [comment]
I'm afraid we don't have a specific template for that, but if you just want to compile ES6, one straightforward options is to use Webpack with `babel-loader`.

**Comment by stefan2410** [comment]
My asp. net core views are like mini-spas (with JS code and API calls ) with  a main singleton object and  many widgets  (jQuery or vanilla).   
A view with tabs, 4 data-grids, 4 data forms, 3 filtering panels, 3 reporting panels, 1 notification area, in my opinion IS a  mini-Spa.
ASP.Net core has the best mechanism to create killer progress.web apps, mini SPAs and we don't have the last few steps, ES6+Webpack in VS2017. 
I need to convert my JS code in ES6 classes, to get the required external libraries with Webpack and to have the hot-reload as I debug in browser debugger ( no VS browserlink) and I change the js code from VSCode.
Why you or somebody else in Microsoft, does not implement feature, to make our life easier ?
