### ISSUE TITLE
HMR no longer working.

### ISSUE THREAD

**Issue by jrmcdona** [aspnet/JavaScriptServices#724]
Hi Folks,

I am using the Angular/.NET core VS project template.  Just today, HMR has stopped.  I am not seeing any errors anywhere.

The webpacks are building - see screenshot.   But just not seeing HMR.

How should I kick it to make it start up again?

![image](https://cloud.githubusercontent.com/assets/4327773/23435941/6487da5c-fdce-11e6-988a-30bf38c72d14.png)

**Comment by jadecostant** [comment]
Check the ASPNETCORE_ENVIROMENT variable. it should be set to Development.

**Comment by jrmcdona** [comment]
That was it!
