### ISSUE TITLE
Does testing w/ @angular/cli work?

### ISSUE THREAD

**Issue by jrmcdona** [aspnet/JavaScriptServices#726]
Hi - I installed the CLI but I am getting an error when trying ng test or ng serve. 
Wondering if CLI will work with these project templates for .NET Core/ Angular.  

My goal here is to setup Karma for TDD/Unit Tests.

Screenshot.

![cli](https://cloud.githubusercontent.com/assets/4327773/23489279/0087eea4-feb7-11e6-94d3-63bd18a0deb1.PNG)

**Comment by jrmcdona** [comment]
Ok just found this https://github.com/aspnet/JavaScriptServices/issues/642

Doesn't look like I should be using CLI.

**Comment by SteveSandersonMS** [comment]
Exactly - just run `npm test` to launch Karma. It's all set up already for you in the Angular template.
