### ISSUE TITLE
generator-aspnetcore-spa package error and @angular/forms broken

### ISSUE THREAD

**Issue by ste4net** [aspnet/JavaScriptServices#728]
Creating a new solution with aspnetcore-spa Yeoman i see package error and peer warnings.
Maybe this package issues are related to error received if i try to use form with formGroup.

Adding a form (with formGroup) to home.component i receive this error:
_Exception: Call to Node module failed with error: Error: Template parse errors: Can't bind to 'formGroup' since it isn't a known property of 'form'._

Removing formGroup and adding just a "consctructor (fb: FormBuilder)" to HomeComponent i receive this error:
_Exception: Call to Node module failed with error: Error: Uncaught (in promise): Error: DI Error_

### This problem does not exist using template from "ASP.NET Core Template Pack extension".

My environment:
VS2015 Upd3
Node 5.4.1 Npm 4.4.0
generator-aspnetcore-spa > Angular framework

### Error returned after creation:
```
+-- UNMET PEER DEPENDENCY rxjs@5.2.0
[...]
`-- UNMET PEER DEPENDENCY zone.js@0.7.7
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"ia32"})
npm WARN angular2-universal-polyfills@2.1.0-rc.1 requires a peer of zone.js@~0.6.21 but none was installed.
npm WARN angular2-universal@2.1.0-rc.1 requires a peer of rxjs@~5.0.0-beta.12 but none was installed.
npm WARN angular2-universal@2.1.0-rc.1 requires a peer of zone.js@~0.6.21 but none was installed.
npm WARN TestSPA@0.0.0 No description
npm WARN TestSPA@0.0.0 No repository field.
npm WARN TestSPA@0.0.0 No license field.
```

![formgroup](https://cloud.githubusercontent.com/assets/16885475/23521121/06782668-ff7e-11e6-9967-67c621cd2371.jpg)

**Comment by paddyza** [comment]
You need to import ReactiveForms in your app.module.

**Comment by ste4net** [comment]
I am sorry for the stupid question... i was sure ti have used the import in app.module too. And it is there... and now it works. I don't know what i have done. Probably a little bit of confusion with three different test folder. Now it works... import was here probably i change something accidentally. sorry
