### ISSUE TITLE
webpack-dev-middleware errors and warnings are not sent to the browser console

### ISSUE THREAD

**Issue by tmueller** [aspnet/JavaScriptServices#732]
Hi, 

the [webpack-dev-middleware](https://github.com/webpack/webpack-dev-middleware) has some interesting options, which cannot be found in [WebpackDevMiddlewareOptions.cs](https://github.com/aspnet/JavaScriptServices/blob/dev/src/Microsoft.AspNetCore.SpaServices/Webpack/WebpackDevMiddlewareOptions.cs).

Namely "quiet" seems to be locked to true. Because no warnings or errors are sent to the browser console. This is really helpful, because you don't miss an error when your command line is not visible. Is it possible to activate this feature?

**Comment by SteveSandersonMS** [comment]
A good suggestion. So good, in fact, that there's already a pull request for it: https://github.com/aspnet/JavaScriptServices/pull/714. We'll merge that soon.

I'll close this as a duplicate.

**Comment by tmueller** [comment]
Hi, 

I am sorry, but PR #714 does not include the options, I was hoping for. What got added in PR #714 were Webpack *Hot* Middleware Options. 

The [webpack-dev-middleware](https://github.com/webpack/webpack-dev-middleware) itself has some interesting options. And those are still hard coded at [WebpackDevMiddleware.ts / Line 108](https://github.com/novascreen/JavaScriptServices/blob/8e6147c3b40e1b136f5df5688448387010972ee1/src/Microsoft.AspNetCore.SpaServices/npm/aspnet-webpack/src/WebpackDevMiddleware.ts#L108).

Is it possible to add them in a similar manner like the Webpack Hot Middleware Options?

**Comment by SteveSandersonMS** [comment]
@tmueller Aha, yes, I see. Thanks for clarifying. Yes, if you submitted a PR for this similar to #714 then we would accept it.

**Comment by tmueller** [comment]
I see, what I can do :)
