### ISSUE TITLE
Unable to run React samples (dev branch)

### ISSUE THREAD

**Issue by mohannad-abwah** [aspnet/JavaScriptServices#734]
I've tried multiple times with various different versions of the [current .net core sdk](https://www.microsoft.com/net/download/core#/current) and every time I try to run any of the react samples (MusicStore/ReactGrid) I get the following error: (running on Win10)  
```
The current project is not valid because of the following errors:
C:\Users\<user>\Documents\vs-workspace\JavaScriptServices\samples\react\MusicStore(1,0): error DOTNET1017: Project file does not exist 'C:\Users\<user>\Documents\vs-workspace\JavaScriptServices\samples\react\MusicStore\project.json'
```
Reading around it seems the project.json file is now gone since moving to VS2017, which is totally fine. However why can't I build/run from the command line anymore?

Is it only supported to do this in VS2017 now? No VS Code? Command line? I haven't installed VS2017 yet but it shouldn't matter to my knowledge.

I'd imagine that it should build from the command line just fine, so what should I do? What version of the .net core sdk do I need? The newest version from the downloads page is confusing. The file name and dotnet --version say it's 1.0.0-preview2-1-003177 but running just 'dotnet' you see it says 1.1.0 and it's the same on the site.

I'd love to be able to run the samples, but can someone also please explain to me what on earth is going on with the versions?

Thanks!

**Comment by SteveSandersonMS** [comment]
You need the RC4 tools (or later) to build/run `csproj` on the command line: https://github.com/dotnet/core/blob/master/release-notes/download-archives/rc4-download.md
