### ISSUE TITLE
Deployment error with nested assets

### ISSUE THREAD

**Issue by tinchou** [aspnet/JavaScriptServices#735]
I'm deploying my AngularSpa-based application to Azure using WebDeploy. Every time I had to deploy twice, because the first time I always got this error for a couple of files:

```
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Publish.targets(100,5): Error MSB3030: Could not copy the file "C:\Repos\Solution\Project\wwwroot\dist\assets\asset-name.jpg" because it was not found.
```

It seems to be fixed now that I changed this in the `csproj` file (note `wwwroot\dist\**\**` vs the template's `wwwroot\dist\**`):

```xml

<!-- Include the newly-built files in the publish output -->
<ItemGroup>
  <DistFiles Include="wwwroot\dist\**\**; ClientApp\dist\**" />
  <ResolvedFileToPublish Include="@(DistFiles->'%(FullPath)')" Exclude="@(ResolvedFileToPublish)">
    <RelativePath>%(DistFiles.Identity)</RelativePath>
    <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
  </ResolvedFileToPublish>
</ItemGroup>
```

**Comment by tinchou** [comment]
Actually, it just skipped those files. I'll have to dig deeper into why they're missing, but if you have any pointers let me know!

**Comment by SteveSandersonMS** [comment]
Thanks for reporting this. I've been trying to reproduce it with the latest .NET Core 2.0 SDKs and cannot do so - it's correctly publishing nested asset directories even without needing an extra `\**` in the csproj.

So I'll close this as a no-longer-repros, but if you are still able to observe this issue with the .NET Core 2.0 SDK, please let me know!
