### ISSUE TITLE
Feature request: Angular 2 AoT option

### ISSUE THREAD

**Issue by alienlike** [aspnet/JavaScriptServices#744]
I would like to see an AoT option for the Angular 2 template. I have tried to manually adapt the Webpack configs for AoT but didn't get very far.

**Comment by SteveSandersonMS** [comment]
This is definitely on our radar already. I know @MarkPieszak was already looking into it, but he said there were some limitations in the underlying technologies that made it impractical last time we discussed it.

Hopefully when we move to Angular 4 all the pieces will be in place to enable this.

**Comment by MarkPieszak** [comment]
Yes, it's coming soon! :)
