### ISSUE TITLE
module.exports = vendor_a5a86878640dfc60743a; error in IE 11

### ISSUE THREAD

**Issue by gaotter** [aspnet/JavaScriptServices#756]
I'm testing the React redux template, but are unable to get it to run in IE 11. It breaks at module.exports = vendor_a5a86878640dfc60743a as vendor_a5a86878640dfc60743a is undefined.  Works fine in Chrome.

Edit: after looking some more i found that the vendor.js had element using .map(() => {}) that EI 11 did not like. I tried to { test: /\.js?$/, use: 'babel-loader' } to the webpack.config.vendor.js and setting up the .babelrc to this "presets": [ "react", "es2015-ie" ]. That did not work very well. Is there a way of making the vendor.js support IE 11?

**Comment by SteveSandersonMS** [comment]
We have issue #484 tracking the need for out-of-the-box IE11 support in the templates.

If you need to make your own app support IE11 quickly, I'd recommend referencing the `core-js` package (i.e., `npm install --save core-js`), and then putting `import 'core-js/shim';` at the top of your `boot-client.ts` file. That package puts in polyfills for pretty much everything.
