### ISSUE TITLE
HMR issue-The following modules couldn't be hot updated: (Full reload needed)

### ISSUE THREAD

**Issue by slavatarbinskyi** [aspnet/JavaScriptServices#757]
Im trying to implement hmr but when im changing any of components its giving the warning below:
[HMR] The following modules couldn't be hot updated: (Full reload needed)
This is usually because the modules which have changed (and their parents) do not know how to hot reload themselves. See http://webpack.github.io/docs/hot-module-replacement-with-webpack.html for more details.

File is tracked by hmr,it says that bundle rebuilt and after cheking for updates on the server its giving this warning and thats it.Can you help me find out solution to fix that?

Startup.cs:
```
// Webpack middleware setup
app.UseWebpackDevMiddleware(new WebpackDevMiddlewareOptions
{
HotModuleReplacement = true,
ProjectPath = env.ContentRootPath
});
```

**Comment by SteveSandersonMS** [comment]
Sorry, I don't have enough information to provide any suggestions based on this alone. You're probably missing some client-side code needed to accept the HMR updates (something similar to `module['hot'].accept();`).

I'd recommend comparing your app to those produced by the `Microsoft.AspNetCore.SpaTemplates` package to determine what's different and missing in your setup. See https://blogs.msdn.microsoft.com/webdev/2017/02/14/building-single-page-applications-on-asp-net-core-with-javascriptservices/

**Comment by justinyoo** [comment]
@SteveSandersonMS Hi, I've been experiencing the same error. I'm using Vue.js + ASP.NET Core. Without ASP.NET Core, HMR works just fine. However, when I implement ASP.NET Core using this `Microsoft.AspNetCore.SpaServices` package, it shows the error.

Here's my screenshot (never mind the last two `GET` method errors, by the way):

![image](https://cloud.githubusercontent.com/assets/1538528/23935056/cc113b70-099d-11e7-9f51-8d2843dae03c.png)

You can reproduce the same error using these code samples:

* https://github.com/devkimchi/Vue.js-with-ASP.NET-Core-Sample/tree/master/src/VueJsAspNetCoreSample
* https://github.com/devkimchi/Vue.js-with-ASP.NET-Core-Sample/tree/master/src/VueJsSample
