### ISSUE TITLE
How i should use modules with jquery dependency in Angular template?

### ISSUE THREAD

**Issue by wkololo4ever** [aspnet/JavaScriptServices#761]
I want to use module "ng2-datetime" that use jquery global variable.

What i do
```
mkdir PlayWithAngular
cd PlayWithAngular
yo aspnetcore-spa
npm install --save ng2-datetime
```
open up webpack.config.vendor.js 
add   `'ng2-datetime' `to entry.vendor
open up app.module.ts
add `import { NKDatetimeModule } from 'ng2-datetime/ng2-datetime';`
and  NKDatetimeModule, to imports
`webpack --config webpack.config.vendor.js`
but when i type
`webpack` 
i get errors
![image](https://cloud.githubusercontent.com/assets/7288803/23919958/e03aa526-0909-11e7-82e0-1a24a1c105af.png)
i don't understand what i should do?
here sources https://github.com/wkololo4ever/playWithAngular

**Comment by SteveSandersonMS** [comment]
Your import statement should be:

```
import { NKDatetimeModule } from 'ng2-datetime';
```

I'm not sure why you were putting `ng2-datetime/ng2-datetime`, but that breaks things because there's also `.ts` sources in that directory and you end up pulling them in unnecessarily, causing clashes.
