### ISSUE TITLE
Docker support?

### ISSUE THREAD

**Issue by beam-codegrind** [aspnet/JavaScriptServices#763]
When added docker support through VS2017, the project threw an exception from UseWebpackDevMiddleware (which I cannot expand the bubble to see details).

I remembered there was a Dockerfile included with project.json, so I tried using some of its code in VS's generated Dockerfile but it didn't work and threw the same exception.

Please advise.

**Comment by SteveSandersonMS** [comment]
The dockerfiles we removed in this commit were working correctly: https://github.com/aspnet/JavaScriptServices/commit/c9526dd4d238898e98f923382a067a04f3f10ba6. If you want to use them with a `csproj`-based project, replace `microsoft/dotnet:1.1.0-sdk-projectjson` with `microsoft/dotnet:1.1.0-sdk-msbuild`.

**Comment by beam-codegrind** [comment]
It didn't work with VS2017's docker support which enable you to debug an app running inside a docker container built using docker-compose.

The code below is Dockerfile automatically generated from that feature and worked well with normal web app project.

```
FROM microsoft/aspnetcore:1.1
ARG source
WORKDIR /app
EXPOSE 80
COPY ${source:-obj/Docker/publish} .
ENTRYPOINT ["dotnet", "MyProjectNamespace"]
```

**Comment by SteveSandersonMS** [comment]
That `Dockerfile` won't work because it doesn't set up Node in the docker image.

Please see the dockerfiles removed in c9526dd4d238898e98f923382a067a04f3f10ba6 for an example of the config you need.

**Comment by beam-codegrind** [comment]
@SteveSandersonMS Yes that generated file didn't work, and this was my edited Dockerfile back then.
```
FROM microsoft/aspnetcore:1.1

RUN apt-get update
RUN wget -qO- https://deb.nodesource.com/setup_6.x | bash -
RUN apt-get install -y build-essential nodejs

ARG source
WORKDIR /app
EXPOSE 80
COPY ${source:-obj/Docker/publish} .
ENTRYPOINT ["dotnet", "BuilkConnect.Web.Api.dll"]
```
That seemed to work and the project and docker image were successfully built. However, after it started running there's an unhandled System.AggregateException from this line:
```
app.UseWebpackDevMiddleware(new WebpackDevMiddlewareOptions {
                    HotModuleReplacement = true
                });
```
And I cannot expand it to explore the details.

Following steps below should reproduce the issue for you.

1. Create an Angular 2 Project from yo
2. Install Docker for Windows
3. Open it up in Visual Studio 2017
4. Right-click the project -> Add -> Docker Support
5. A project called 'docker-compose' will be created inside the same solution, along with a Dockerfile in your Angular 2 project.
6. Add nodejs installation codes into that Dockerfile.
7. Start debugging in docker-compose project, it will start building your Angular 2 Project using that Dockerfile and run it in a container.
8. After the container started running, you'll soon get this error.

**Comment by SteveSandersonMS** [comment]
OK, thanks for the info. Could you have a look at the suggestions in #772 and see if they cover what you're looking for? I'm not personally familiar with anything nonstandard that VS2017 does with Docker so might not be able to help with that.

**Comment by glennc** [comment]
Bit late on this, but there is an ASP.NET image that contains Node, the `aspnetcore-build` image. If all you need is Node does that image work for you? It might not be completely perfect because the image also contains a lot of NuGet packages that you probably don't need for your scenario, making it bigger on-disk. Unless you are compiling in the container?
