### ISSUE TITLE
Angular 2

### ISSUE THREAD

**Issue by jmurphzyo** [aspnet/JavaScriptServices#77]
I don't know if I just don't understand webpack or if there is an issue loading packages in the angular 2 template but I am not able load the material 2 package.

**Comment by laskoviymishka** [comment]
Could you provide additional details on these, what error message, webpack configs etc.

**Comment by jmurphzyo** [comment]
@laskoviymishka 
I am not receiving any errors its just not rendering the Material 2 styles and/or functionality (its behaving like webpack isn't loading the files at all) but I can look in the vendor.js and see all the components included. I am fairly new to web pack so this might be user error. here is where i am including the files. 
`var path = require('path');
var webpack = require('webpack');
var ExtractTextPlugin = require('extract-text-webpack-plugin');
var extractCSS = new ExtractTextPlugin('vendor.css');
var isDevelopment = process.env.ASPNETCORE_ENVIRONMENT === 'Development';

module.exports = {
    resolve: {
        extensions: ['', '.js', '.css']
    },
    module: {
        loaders: [
            { test: /\.(png|woff|woff2|eot|ttf|svg)$/, loader: 'url-loader?limit=100000' },
            { test: /\.css/, loader: extractCSS.extract(['css']) }
        ]
    },
    entry: {
        vendor: [
            'style-loader',
            '@angular/common',
            '@angular/compiler',
            '@angular/core',
            '@angular/http',
            '@angular/platform-browser',
            '@angular/platform-browser-dynamic',
            '@angular/router-deprecated',
            '@angular/platform-server',
            '@angular/router-deprecated',
            '@angular2-material/core',
            '@angular2-material/button',
            '@angular2-material/card',
            '@angular2-material/checkbox',
            '@angular2-material/icon',
            '@angular2-material/input',
            '@angular2-material/list',
            '@angular2-material/progress-bar',
            '@angular2-material/progress-circle',
            '@angular2-material/radio',
            '@angular2-material/sidenav',
            '@angular2-material/toolbar'
        ]
    },
    output: {
        path: path.join(__dirname, 'wwwroot', 'dist'),
        filename: '[name].js',
        library: '[name]_[hash]'
    },
    plugins: [
        extractCSS,
        new webpack.ProvidePlugin(
            {
                '@angular2-material/core': 'vendor/@angular2-material/core',
                '@angular2-material/button': 'vendor/@angular2-material/button',
                '@angular2-material/card': 'vendor/@angular2-material/card',
                '@angular2-material/checkbox': 'vendor/@angular2-material/checkbox',
                '@angular2-material/icon': 'vendor/@angular2-material/icon',
                '@angular2-material/input': 'vendor/@angular2-material/input',
                '@angular2-material/list': 'vendor/@angular2-material/list',
                '@angular2-material/progress-bar': 'vendor/@angular2-material/progress-bar',
                '@angular2-material/progress-circle': 'vendor/@angular2-material/progress-circle',
                '@angular2-material/radio': 'vendor/@angular2-material/radio',
                '@angular2-material/sidenav': 'vendor/@angular2-material/sidenav',
                '@angular2-material/toolbar': 'vendor/@angular2-material/toolbar'
            }),
        new webpack.optimize.OccurenceOrderPlugin(),
        new webpack.DllPlugin({
            path: path.join(__dirname, 'wwwroot', 'dist', '[name]-manifest.json'),
            name: '[name]_[hash]'
        })
    ].concat(isDevelopment ? [] : [
        new webpack.optimize.UglifyJsPlugin({
            compress: { warnings: false },
            minimize: true,
            mangle: false // Due to https://github.com/angular/angular/issues/6678
        })
    ])
};`

and I have also attempted it like this
`var path = require('path');
var webpack = require('webpack');
var ExtractTextPlugin = require('extract-text-webpack-plugin');
var extractCSS = new ExtractTextPlugin('vendor.css');
var isDevelopment = process.env.ASPNETCORE_ENVIRONMENT === 'Development';

module.exports = {
    resolve: {
        extensions: ['', '.js', '.css']
    },
    module: {
        loaders: [
            { test: /\.(png|woff|woff2|eot|ttf|svg)$/, loader: 'url-loader?limit=100000' },
            { test: /\.css/, loader: extractCSS.extract(['css']) }
        ]
    },
    entry: {
        vendor: [
            'style-loader',
            '@angular/common',
            '@angular/compiler',
            '@angular/core',
            '@angular/http',
            '@angular/platform-browser',
            '@angular/platform-browser-dynamic',
            '@angular/router-deprecated',
            '@angular/platform-server',
            '@angular/router-deprecated',
            '@angular2-material/core',
            '@angular2-material/button',
            '@angular2-material/card',
            '@angular2-material/checkbox',
            '@angular2-material/icon',
            '@angular2-material/input',
            '@angular2-material/list',
            '@angular2-material/progress-bar',
            '@angular2-material/progress-circle',
            '@angular2-material/radio',
            '@angular2-material/sidenav',
            '@angular2-material/toolbar'
        ]
    },
    output: {
        path: path.join(__dirname, 'wwwroot', 'dist'),
        filename: '[name].js',
        library: '[name]_[hash]'
    },
    plugins: [
        extractCSS,        
        new webpack.optimize.OccurenceOrderPlugin(),
        new webpack.DllPlugin({
            path: path.join(__dirname, 'wwwroot', 'dist', '[name]-manifest.json'),
            name: '[name]_[hash]'
        })
    ].concat(isDevelopment ? [] : [
        new webpack.optimize.UglifyJsPlugin({
            compress: { warnings: false },
            minimize: true,
            mangle: false // Due to https://github.com/angular/angular/issues/6678
        })
    ])
};
`

**Comment by laskoviymishka** [comment]
@jmurphzyo can you try to import styles via require in your app component, and then include it to your app root?

```
import '@angular2-material/core';
```
or 
```
var styles = require('@angular2-material/core');
@ng.Component({
  selector: 'app',
  template: require('./app.html'),
  styles: [styles]
})
```

**Comment by jmurphzyo** [comment]
@laskoviymishka I figured it out.... some how tsc got ran on this project and webpack wasn't getting the updates when I added material2...... Dumb mistakes number one time sync of programming!

**Comment by laskoviymishka** [comment]
So this issue could be closed?

**Comment by jmurphzyo** [comment]
I will for now... going to do more testing and will change to open if there is still an issue
