### ISSUE TITLE
Question: How to add 3rd party css and js files to the project ? 

### ISSUE THREAD

**Issue by codingonHP** [aspnet/JavaScriptServices#770]
I am trying to add https://getmdl.io/started/index.html#download to the project but it is not working. I am new to web-pack and I am not able to figure out how and where to exactly add .js and .css files. I have updated vendor-manifest.json and webpack.config.vendor.js but still, these files are not getting loaded. What am I missing here?

Thanks.

**Comment by SteveSandersonMS** [comment]
Don't edit `vendor-manifest.json` manually - it's generated by Webpack when you run `webpack --config webpack.config.vendor.js`. The steps you need are probably something like:

 * `npm install material-design-lite --save`
 * In your `boot-client.ts`, at the top, add `import 'material-design-lite/material.min.js';` and `import 'material-design-lite/material.min.css';`
 * In your `_Layout.cshtml`, add `<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">` in the `<head>`
 * Run `webpack` on the command line (unless you're running in `Development` mode, in which case you don't need to)

I haven't personally tried this, but basically the principle is installing the library from NPM, and then using TypeScript `import` statements to reference it.

**Comment by codingonHP** [comment]
@SteveSandersonMS Thanks a lot. It worked and solved some other issues I was having :)
