### ISSUE TITLE
asp-prerender-data values not passed to boot-server.ts

### ISSUE THREAD

**Issue by JohnGalt1717** [aspnet/JavaScriptServices#775]
Using the Angular2 template I have the following in my index.cshtml:

@{
    var serviceUrl = System.Environment.GetEnvironmentVariable("ApiUrl");
    var blogUrl = System.Environment.GetEnvironmentVariable("ApiUrl");
    if (string.IsNullOrWhiteSpace(serviceUrl))
    {
        serviceUrl = options.Value.ApiUrl;
    }
    if (string.IsNullOrWhiteSpace(blogUrl)) {
        blogUrl = options.Value.Url;
    }

    ViewData["Title"] = "CADLearning Blogs";

    var serviceData = new {
        ServiceUrl = serviceUrl,
        Url = blogUrl
    };
}

<app asp-prerender-module="ClientApp/dist/main-server" asp-prerender-data="serviceData">Loading...</app>

and then in my boot-server.ts I have the following:

export default createServerRenderer(params => {    
    return new Promise<RenderResult>((resolve, reject) => {                
        throw params.data.ServiceUrl;
...

I'm attempting to verify that it's actually being passed to the params.data per the docs. params.data returns [Object object] but params.data.ServiceUrl returns undefined.

I think I've tried every permutation and combination of the above there is with no joy, the values are never passed through.

what am I doing wrong?

**Comment by seven1986** [comment]
<div id="my-spa" asp-prerender-module="ClientApp/boot-server"
                 asp-prerender-data="new {
                    yourdata = 123456
                 }"></div>

then..
export default createServerRenderer(params => {
let d = params.data.yourdata;
return new Promise((resolve, reject) => {
throw params.data.ServiceUrl;
...

**Comment by JohnGalt1717** [comment]
This doesn't work. Still null even if I throw d instead of params.data.ServiceUrl which should be the same thing.

I'm using the Angular 2 template if that matters.

And here's the <app> line that injects serviceData (although I tried it inline and it also doesn't work): 

<app asp-prerender-module="ClientApp/dist/main-server" asp-prerender-data="serviceData">Loading...</app>

**Comment by JohnGalt1717** [comment]
*bump* This is a major blocker for us and I've played around for 4+ hours trying to get this working based on the samples in the docs with no luck. (and the sample is pretty straight forward so I don't know why there'd be an issue)

**Comment by SteveSandersonMS** [comment]
By default, Json.NET serialization converts .NET property names to JavaScript-style camelCase names, so I'd guess on the JS side you need to read `params.data.serviceUrl` instead of `params.data.ServiceUrl`. This is called out in the example in the docs as follows:

> Notice that the property names are received in JavaScript-style casing (e.g., isGoldUser) even though they were sent in C#-style casing (e.g., IsGoldUser). This is because of how the JSON serialization is configured by default.

**Comment by JohnGalt1717** [comment]
That did it! Might want to put that in the documentation. Will throw C# devs for a loop.
