### ISSUE TITLE
Using promise.prototype.finally with ReactReduxTemplate

### ISSUE THREAD

**Issue by DanHarman** [aspnet/JavaScriptServices#779]
Has anyone worked out how to use this polyfill with the template?

I've pulled in the package and the typings in `packages.json` & made an entry in `webpack.config.js`, but the polyfill seems to require the following code at a sensible entry point in the code:

```
import { shim } from 'promise.prototype.finally';
shim();
```

I've tried putting this in both `boot-client.tsx` & `boot-server.tsx` but it blows up the latter breaking the server side rendering.

**Comment by SteveSandersonMS** [comment]
Could you clarify what's not working? I just tried this and it seemed to work fine, having put the same code snippet as you in both `boot-server.tsx` and `boot-client.tsx`.

What error did you get from server-side rendering? And what change did you make to `webpack.config.js`? I didn't change the webpack config at all.

I'm marking this as closed for tidiness as I don't think it's a bug in the code in this repo, but I'm happy to continue discussing it to help you figure out the issue in your particular app!

**Comment by DanHarman** [comment]
Hi,

Thanks for looking at this, very kind of you to take the time. I think it must have been a build problem on my side.

One oddity, is that I have now moved onto using async-await from babel, and I have to `import "babel-polyfill";` in both `boot-*.tsx` files, rather than centralising in `configureStore.ts` as that fails on server side rendering with `regeneratorRuntime is not defined` (not sure on client as can't get that far!). So two questions:

1. Do you know why this might be the case here when the `finally` shim works fine in `configureStore.ts`? Is it because `configureStore.ts` isn't a proper webpack entry point, but by invoking shim() it forces the polyfill in?
2. Is `babel-polyfill` the best way of getting async await into a templated project given we have typescript in there already presumably transpiling as I thought that could do by itself? it n.b. when I tried it that way, i.e. without pulling in `babel-preset-latest` & `babel-polyfill` it compiled fine but again I had the regeneratorRuntime problem on the server.

In case anyone else is here looking to bring in `promise.prototype.finally`, the steps are:

`npm install promise.prototype.finally @types/promise.prototype.finally --save`

Easiet common place to shim is `configureStore.ts`

```
// configureStore.ts

import { shim } from 'promise.prototype.finally';
shim();
```

and don't forget to add to the vendor bundle:
```
// webpack.config.vendor.js
...
     entry: {
            vendor: [
                'bootstrap',
                'bootstrap/dist/css/bootstrap.css',
                'domain-task',
                'event-source-polyfill',
                'react',
                'react-dom',
                'react-router',
                'react-redux',
                'redux',
                'redux-thunk',
                'react-router-redux',
                'jquery',
                'promise.prototype.finally'
            ],
        },
...
```
