### ISSUE TITLE
Rename NodeServices to JavaScriptServices

### ISSUE THREAD

**Issue by Eilon** [aspnet/JavaScriptServices#78]
The repo has been renamed, but also need to update:

- [x] Assembly names
- [x] Package names
- [x] Namespaces
- [x] Readme
- [x] Docs/wiki/other content

**Comment by SteveSandersonMS** [comment]
All done. There weren't any assemblies or packages to rename, since it's the overall feature area that's changing name, not the packages within it (so the NodeServices package keeps that name). I have renamed the top-level solution file, plus docs and other content.

**Comment by Eilon** [comment]
Nice!
