### ISSUE TITLE
Basic class constructor DI problems

### ISSUE THREAD

**Issue by seven1986** [aspnet/JavaScriptServices#784]
## Inorder to adapt PC and Mobile device，I created files like this. 

![image](https://cloud.githubusercontent.com/assets/20808494/24228221/daaa9bac-0fad-11e7-9aa9-eab2f939dd0b.png)

Most things in **fetchdata.component.base.ts** are enough

```typescript
import { ReflectiveInjector } from '@angular/core/src/di';
import { apiService } from '../../common/apiService';

export class FetchDataComponentBase
{
    public forecasts: WeatherForecast[];

    constructor(api: apiService)
    {
        api.call('/api/SampleData/WeatherForecasts').subscribe(r =>
        {
            this.forecasts = r.json();
        });
    }
}

interface WeatherForecast {
    dateFormatted: string;
    temperatureC: number;
    temperatureF: number;
    summary: string;
}
```

**fetchdata.component.ts** 
```typescript
import { Component } from '@angular/core';
import { FetchDataComponentBase } from './fetchdata.component.base';

@Component({
    selector: 'fetchdata',
    templateUrl: './fetchdata.component.html'
})

export class FetchDataComponent extends FetchDataComponentBase {
}
```

**pc.fetchdata.component.ts** 
```typescript
import { Component } from '@angular/core';
import { FetchDataComponentBase } from './fetchdata.component.base';

@Component({
    selector: 'fetchdata',
    templateUrl: './pc.fetchdata.component.html'
})

export class FetchDataComponent extends FetchDataComponentBase {
}
```

But, when I run in PC browser, in **fetchdata.component.base.ts** the **api:apiService** is undefined.

![5](https://cloud.githubusercontent.com/assets/20808494/24229332/e4bde742-0fb3-11e7-8501-50b8466e5ae3.png)

### Could you help me ? thank you

**Comment by SteveSandersonMS** [comment]
Please see http://stackoverflow.com/questions/33970645/how-to-extend-a-component-with-dependency-injection-in-angular-2

In general, Angular's DI system doesn't pick up dependencies if they are declared on a base class constructor. There are various ways to deal with this, as described on that StackOverflow page.

**Comment by seven1986** [comment]
thanks
