### ISSUE TITLE
Unavailable SDK

### ISSUE THREAD

**Issue by ricky68** [aspnet/JavaScriptServices#786]
Current version of aspnetcore-spa (0.9.0) requires dot net SDK 1.0.0, but I'm unable to find this on microsofts website. I get the following error:

         _-----_     ╭──────────────────────────╮
        |       |    │  Welcome to the ASP.NET  │
        |--(o)--|    │   Core Single-Page App   │
       `---------´   │        generator!        │
        ( _´U`_ )    │                          │
        /___A___\   /│      Version: 0.9.0      │
         |  ~  |     ╰──────────────────────────╯
       __'.___.'__
     ´   `  |° ´ Y `

    This generator requires dotnet SDK version 1.0.0 or later. You have version 1.0.0-preview2-1-003177
    Please update your dotnet SDK then try again. You can run "dotnet --version" to check your version.

Restoring the previous version fixes this error:
    
     npm install -g generator-aspnetcore-spa@0.8.7
    

Anyone know how to get the required version of the dotnet sdk?

**Comment by DanHarman** [comment]
Here perhaps?
https://www.microsoft.com/net/download/core

**Comment by ricky68** [comment]
I tried there but it doesn't install 1.0.0 it installs 1.0.0-preview2-1-003177.

**Comment by ricky68** [comment]
I've fixed this by removing the .netcore sdk and deleting the C:\program files\dotnet directory before reinstalling it.
