### ISSUE TITLE
Getting Started with the Anuglar2Spa Template - Add a new dependency

### ISSUE THREAD

**Issue by spottedmahn** [aspnet/JavaScriptServices#788]
I'm trying to figure out how to add [bootstrap-toggle from npm](https://www.npmjs.com/package/bootstrap-toggle) to my project.  There's a CSS and JS file.  I added it to my package.json and I see it in my node_modules directory.

I'm thinking I need to add 'bootstrap-toggle' to the webpack.config.vendor.js file in the vendor array but that doesn't seem to be working.

Is there any documentation/blogs on adding new dependencies?  Thanks!!

**Comment by SteveSandersonMS** [comment]
You can use an approach similar to the one described here: https://github.com/aspnet/JavaScriptServices/issues/770

As for general documentation, really it's covered by the TypeScript and Webpack docs, though I do appreciate there would be a lot to read about both of those!

**Comment by spottedmahn** [comment]
After reading #770 I'm still not clear on how I would add this library: [https://www.npmjs.com/package/angular2-bootstrap-switch](https://www.npmjs.com/package/angular2-bootstrap-switch) to my project.  It seems different than #770 in that it's an angular2 component.

I'm thinking I need to add it to webpack.config.vendor.js?  I've tried this but when I try to add this to my declarations in my app.module.ts I get "Exception: Call to Node module failed with error: Error: Unexpected value 'SwitchComponent' declared by the module 'AppModule'"

module.exports = (env) => {
       const sharedConfig = {
        ...
        entry: {
            vendor: [
                ...
                **'angular2-bootstrap-switch'**
            ]
        },
...

Btw, thanks for your prompt response on my original question!
