### ISSUE TITLE
Debug the node instance for pre-render in vs code or vs.net?

### ISSUE THREAD

**Issue by JohnGalt1717** [aspnet/JavaScriptServices#789]
I'm getting an the following error: Response with status: 200 Ok for URL: null on any http call that our site needs for pre-render with the angular 2 template.

I have no way of diagnose this because it's burried inside node.

Is there any way to debug node properly for the pre-render pipeline so that I can get what's really going on?

**Comment by SteveSandersonMS** [comment]
Please see https://github.com/aspnet/JavaScriptServices/tree/dev/src/Microsoft.AspNetCore.SpaServices#debugging-your-projects. You can set a breakpoint in your `boot-server.ts` and follow it from there.

**Comment by JohnGalt1717** [comment]
Ok, well what I see on the screen after setting it in the startup.cs file and what actually happens are very different.
First the prompt in the ouptut trace says to run node-inspector --debug-port=5858

So I run that (yes node-inspector is installed globally) in the directory of the web app.

It runs, however when I browse to the URL that it tells me to nothing happens in the chrome debugger tools. 

However in the node-inspector output I get this if I refresh the tools:

Access to C:\Users\xxx\AppData\Local\Temp from ResourceTree denied. (Error: EPERM: operation not permitted, lstat 'C:\Users\xxxx\AppData\Local\Temp\2xniyvf5.i4y')

I've tried running it as Administrator with the same results.

In the Chrome tools it then says: 

Error: Debugger: Failed to resolve value by handle, ' #125# not found
Network.loadResourceForFrontend failed.
Error: ENOENT: no such file or directory, open 'D:\repos\xxx\ClientApp\dist\index.js.map'
Network.loadResourceForFrontend failed.
Error: ENOENT: no such file or directory, open 'D:\repos\xxxl\ClientApp\dist\Observable.js.map'

Once it says that it shows me stuff in the sources tab but no webpack section and nothing I can find to set break points on.

I've also tried setting up vs code with node attach with inspector and specified the port but that doesn't work either saying that there was no response on localhost:5858 which obviously isn't 8080/?port=5858 like it should be.

(Also I'm not seeing anywhere a "Threads" section in chrome debugging tools to be able to attach it directly there. I have to open a new window.)

(The reason for this is that I"m getting an "Error: DI Error" but it doesn't tell me what Provider is missing so I'm trying to find out with no luck...)

Perfect world I'd like to be able to setup a compound debug in vs code that launches .net core site, launches chrome for the site and then launches the node debugger as well automatically. (I'd bet others would love to have that level of visibility too) Clearly though, there is something I'm missing.

Sorry for being a pest, there's just a complete TON of moving parts to this and things are moving so quickly that the docs have different things than what shows up on the screen

**Comment by SteveSandersonMS** [comment]
You were unlucky - we *just* changed those docs to reflect the upcoming update to `NodeServices` that switches from `node-inspector` to Node's new built-in debugging system.

Since you're still using the `node-inspector`-based version of the library (and the update isn't published to NuGet yet, so you will need to keep using that version), the matching versions of the docs is this: https://github.com/aspnet/JavaScriptServices/blob/ee601bed5075e6cc927b04e6581ad2dc5ed02a69/src/Microsoft.AspNetCore.SpaServices/README.md. Please refer to those instructions about using `node-inspector`.

> Access to C:\Users\xxx\AppData\Local\Temp from ResourceTree denied. (Error: EPERM: operation not permitted, lstat 'C:\Users\xxxx\AppData\Local\Temp\2xniyvf5.i4y')

That does sound like a problem you will have to resolve, but is something specific to your Node setup and is not something I can help you with. I'd recommend searching for that error message and seeing what general advice Node people give. Sorry!

**Comment by JohnGalt1717** [comment]
Thanks for the old documentation. Any eta on when the new stuff is going to be released?
node-inspector clearly has a bug because multiple people are complaining about it: https://github.com/node-inspector/node-inspector/issues/833

I've tried clearing the node_modules folder with no joy so I'm stuck for now.
