### ISSUE TITLE
Visual Studio 2015 shows Dependencies - not installed

### ISSUE THREAD

**Issue by leontyr** [aspnet/JavaScriptServices#79]
Within it, there is npm - not installed.

When I run npm i, I see the following 

```
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.12
npm WARN Spa@0.0.0 No repository field.
npm WARN Spa@0.0.0 No license field.
```

**Comment by SteveSandersonMS** [comment]
The `fsevents` warning isn't a problem. It's an optional dependency and isn't needed for this to work on Windows.

Are you seeing any other problems? Please reopen with details if so!

**Comment by leontyr** [comment]
fsevents is not the issue. The issue is Visual Studio 2015 shows Dependencies - not installed although it might just be a UI problem.

**Comment by nil4** [comment]
@SteveSandersonMS to add to what @leontyr said: VS shows *Dependencies - not installed* without any indication of *what* failed to install. Perhaps this belongs in the aspnet/Tooling repo, though.

**Comment by jongalloway** [comment]
I'm getting this, too.

1. Scaffold a new application using `yo aspnetcore-spa`, use any of the templates.
1. Restore and run in console. Opens fine in VS Code.
1. Open the xproj in Visual Studio 2015.
1. Following is displayed in Visual Studio - Solution Explorer:

![capture](https://cloud.githubusercontent.com/assets/68539/17315972/8adaa664-58b3-11e6-8423-d96a331ee271.PNG)

**Comment by pwdst** [comment]
Is this related to https://github.com/aspnet/Tooling/issues/479 - gulp-watch seems to be frequently cited as the source of the warning.
Original issue with NPM is at https://github.com/npm/npm/issues/11632

**Comment by MarkPieszak** [comment]
I think so, that might ultimately be the culprit (or one of the issues) it's definitely not the repo but vstudio

**Comment by thesmallbang** [comment]
Is there any way to get visual studio to run the install with the --no-optional command? I assume this would stop the issue we are having with fsevents.

**Comment by JonCubed** [comment]
Scott Hanselman posted about this recently with a fix
http://www.hanselman.com/blog/VisualStudio2015FixingDependenciesNpmNotInstalledFromFseventsWithNodeOnWindows.aspx

**Comment by xperiandri** [comment]
That fix does not work for me
Tried with Node.js 3.10.8

**Comment by agilehobo** [comment]
That fix doesn't work for me too.
Tried with Node.js 3.10.9

**Comment by duongthaiha** [comment]
Same with be Node.js 3.10.9 still have issues

**Comment by SteveSandersonMS** [comment]
Sorry to hear you're all still having trouble with that.

This is not the best place to report it - if it bothers you, could you please report it to Visual Studio instead? For example, [here](https://visualstudio.uservoice.com/forums/121579-visual-studio-2015). Please bear in mind that this issue is not specific to anything in JavaScriptServices - it applies to *any* project that takes an NPM dependency on something like `angular2` which in turn depends on `fsevents`.
