### ISSUE TITLE
No more choice of VS2015 and VS2017 during generation

### ISSUE THREAD

**Issue by prindacerk** [aspnet/JavaScriptServices#790]
In version 0.8.7, we had the option to choose whether the project should be project.json (VS2015) or .csproj (VS2017).

That option is gone in the latest version. It is a problem for those who are still using VS2015 version. Would be great if it can be re-added in the next version.

**Comment by SteveSandersonMS** [comment]
Sorry, we don't have capacity to continue designing everything for both `project.json` and `csproj`-based projects. Of course, your existing projects will continue to work with VS2015.
