### ISSUE TITLE
Issue with less loader

### ISSUE THREAD

**Issue by peter-bozovic** [aspnet/JavaScriptServices#794]
Hello,

I have started new project and would like to use less files for styles.
Followed the guidelines for Approach 2: Loading the styles using Webpack and JavaScript
However, I can't figure out how to make it work. Always getting "You may need an appropriate loader to handel this file type."
My test project is here: https://github.com/peter-bozovic/AngularSpaProto

I see there is bootstrap css framework included, but I don't see how it's wired up ? I would need my own bootstrap package with custom less variables.

Thanks for help

**Comment by SteveSandersonMS** [comment]
Please see https://github.com/aspnet/JavaScriptServices/blob/dev/src/Microsoft.AspNetCore.SpaServices/README.md#example-a-simple-webpack-setup-that-builds-less or general Webpack docs

**Comment by peter-bozovic** [comment]
Thank you Steve, but I already tried all different methods in this documentation and was not able to make it work :(

**Comment by peter-bozovic** [comment]
This is why I provided repo with solution that reproduces steps described in the documentation and that doens't work for me.
I even tried on two different computers with same results.

I'm not expert enough to be able to look for issues in third party code so I'm asking for help.

**Comment by SteveSandersonMS** [comment]
@peter-bozovic I edited my comment shortly after posting it - I'm guessing you only saw the older one. Please see the updated comment about `loaders`/`rules` above.

**Comment by peter-bozovic** [comment]
Can you also help me on how to replace (or remove) currently built-in bootstrap css.
I would like to load my own bootstrap.less with custom variables.

**Comment by SteveSandersonMS** [comment]
You can remove the existing Bootstrap css file just by removing the `'bootstrap/dist/css/bootstrap.css'` entry from `webpack.config.vendor.js` and re-running `webpack --config webpack.config.vendor.js`.

As for creating a custom build of Bootstrap with your own variables, I'm afraid I don't know about that. That's specific to Bootstrap. I'd recommend raising this question with the Bootstrap community - anything they propose that works with Webpack will also work here, as there's nothing specific we're doing to change how it works.

**Comment by peter-bozovic** [comment]
Thanks, that should put me on the right track.
