### ISSUE TITLE
Getting Started with the Anuglar2Spa Template - Adding a Angular2 dependency

### ISSUE THREAD

**Issue by spottedmahn** [aspnet/JavaScriptServices#797]
After reading #770 I'm still not clear on how I would add this library: https://www.npmjs.com/package/angular2-bootstrap-switch to my project. It seems different than #770 in that it's an angular2 component.

I'm thinking I need to add it to webpack.config.vendor.js? I've tried this, but when I try to add it to my declarations array in my app.module.ts I get "Exception: Call to Node module failed with error: Error: Unexpected value 'SwitchComponent' declared by the module 'AppModule'"

module.exports = (env) => {
const sharedConfig = {
...
entry: {
vendor: [
...
'angular2-bootstrap-switch'
]
},
...

Btw, thanks for your prompt response on my original question #788 !

**Comment by ADefWebserver** [comment]
This may help: [Hello World Angular 2+ Data Sample Using JavaScriptServices .Net Core and PrimeNg](http://lightswitchhelpwebsite.com/Blog/tabid/61/EntryId/3304/Hello-World-Angular-2-Data-Sample-Using-JavaScriptServices-Net-Core-and-PrimeNg.aspx) .

You have to add a section to declare your components under the router section (in ..\ClientApp\app\app.module.ts):

`import { FormsModule } from '@angular/forms';
import { PrimeComponent } from './components/prime/prime.component';
import { ButtonModule, GrowlModule } from 'primeng/primeng';
@NgModule({
    declarations: [ 
        ...
        PrimeComponent
    ],
    imports: [
        RouterModule.forRoot([
            ...
            { path: 'prime', component: PrimeComponent },
            ...
        ]),
        FormsModule,
        ButtonModule,
        GrowlModule
    ]
})`

**Comment by spottedmahn** [comment]
Thanks @ADefWebserver, that's a great guide.

> You have to add a section to declare your components under the router section (in ..\ClientApp\app\app.module.ts):

I'm not going to a different page/component, I'm just trying to use this control in component.

**Comment by ADefWebserver** [comment]
When I received the same error (Unexpected value '...' declared by the module 'AppModule'), I did not have the component declared in app.module.ts.

**Comment by spottedmahn** [comment]
I see, thanks.  I went back and performed **another webpack** and now I'm getting an error (I'm not sure why I didn't get this the first time, maybe I didn't save webpack.config.vendor.js):

![can t resolve angular2-bootstrap-switch](https://cloud.githubusercontent.com/assets/14079228/24301196/5083f0c6-1085-11e7-932d-edbecd2ce451.png)

**Comment by SteveSandersonMS** [comment]
Sorry if this is patronising, but did you actually install `angular2-bootstrap-switch`? As in, did you run `npm install --save angular2-bootstrap-switch`? You only mention that you listed it in `webpack.config.vendor.js`, but didn't say you installed it first.

**Comment by spottedmahn** [comment]
@SteveSandersonMS I did, and I see it in my node_modules folder.

I installed by adding it to my package.json file Visual Studio took care of the rest.

**Comment by SteveSandersonMS** [comment]
OK, you were doing everything correctly. It's not an issue in either your code or in the JavaScriptServices code!

I'm afraid the problem is that `angular2-bootstrap-switch` is broken. Its `package.json` specifies `"main": "index.js"`, but there isn't even an `index.js` in that package (hence the `Can't resolve...` error). Based on https://github.com/ovsleep/bootstrap-switch/issues/2, it seems the `angular2-bootstrap-switch` author might need some help with adding NPM support.

They also have an outstanding PR - https://github.com/ovsleep/bootstrap-switch/pull/1 - that apparently is also needed before it would work. I'd recommend working with the `angular2-bootstrap-switch` author to get this properly supported with Webpack.
