### ISSUE TITLE
Path case issue with aspnet-webpack

### ISSUE THREAD

**Issue by waynebrantley** [aspnet/JavaScriptServices#798]
ReactSpa Template
Webpack 2.3.1
Node 7.7.4
Npm 4.1.2

Run webpack, everything works fine.

Run F5 from VSCode I get an error.
The error is `` configuration.output.path: The provided value "c:\\Projects\\Templates\\ReactReduxSpa\\wwwroot\\dist" is not an absolute path!``

This is of course an absolute path and it is valid.
The problem is the **lower case** ``c`` for the drive letter.

As a test, I changed webpack to 
```
        output: {
            path: path.join(__dirname.ToUpperCase(), bundleOutputDir),
            filename: '[name].js',
            publicPath: '/dist/'
        },

```
It it now works.  Of course, this is not a fix and would break on a mac/linux flavor....but this was just to prove that was the issue.  Again, running webpack from command line does not have that issue, so it has to do with calling it all through aspnet-webpack?

**Comment by SteveSandersonMS** [comment]
Good job on tracking it down - however unfortunately this is a known issue in the latest version of Webpack. Please see #782 for workarounds. I'm sure Webpack will fix this soon as it's affecting everyone using Webpack on Windows.
