### ISSUE TITLE
HMR stop working after changind JsonSerializerSettings 

### ISSUE THREAD

**Issue by skorunka** [aspnet/JavaScriptServices#799]
This breakes the HMR: `JsonConvert.DefaultSettings = () => new JsonSerializerSettings { ContractResolver = new CamelCasePropertyNamesContractResolver() };`.

Any chance to make this settings to work woth HMR?

ta

**Comment by SteveSandersonMS** [comment]
Yep, we know about this issue :) It's being tracked as #688.
