### ISSUE TITLE
asp.net core targeting full framework

### ISSUE THREAD

**Issue by waynebrantley** [aspnet/JavaScriptServices#802]
Taking your sample reactreduxspa, simply change the target to net461 and run it.
When the UseWebpackMiddleWare call is made you will get an error:
```
FileLoadException: Could not load file or assembly 'System.Diagnostics.DiagnosticSource, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
 
```

Evidentialy you are in good company as EF had this issue (https://github.com/aspnet/EntityFramework/issues/7889) and it seems core team has /is trying to fix https://github.com/dotnet/corefx/issues/15031

Anyway to fix this on your side or any ideas?   Not sure exactly which dependency you are using that is causing this issue.

Tried assembly binding in web.config to no avail:
```
<runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.Diagnostics.DiagnosticSource" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.3.0.0" newVersion="4.3.0.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>  
```

**Comment by waynebrantley** [comment]
If you upgrade your spa services to use the latest release of System.Net.Http package (4.3.1) it fixes this issue.
I was able to update that package in my template and it resolves it locally for me until you get the spa services package dependency updated.

**Comment by SteveSandersonMS** [comment]
Thanks for letting us know about this.

> If you upgrade your spa services to use the latest release of System.Net.Http package (4.3.1) it fixes this issue.
I was able to update that package in my template and it resolves it locally for me until you get the spa services package dependency updated.

I'm not sure what exactly you're updating. Neither `Microsoft.AspNetCore.SpaServices` nor the template projects in this repo have direct references to `System.Net.Http`. They reference `Microsoft.AspNetCore.Mvc`, which in turn references `NETStandard.Library`. So I'm not sure if there's a clean way to control the exact `System.Net.Http` version. What did you change in your project, and what are you proposing that we change here?

**Comment by waynebrantley** [comment]
I believe you have to target 1.6.1 of the standard library.
What I did in my project was add a reference to the System.Net.Http nuget package version 4.3.1.
This took care of it.  
You are correct, you do not reference it...but I believe 1.6 of NETStandard does reference it and that is corrected in 1.6.1....I think.

**Comment by DanHarman** [comment]
This is the same as #487

**Comment by SteveSandersonMS** [comment]
@DanHarman - Good point - I'll close this one as a duplicate then so we can focus on the other one.
