### ISSUE TITLE
How to display application version in home page of Angular2 SPA?

### ISSUE THREAD

**Issue by deeppriy** [aspnet/JavaScriptServices#809]
Hi Team,
I am not able find standard way to display application version information in home page of Angular2 SPA.
Should application version be updated by MSBuild and then we need to display it?

Thanks.

**Comment by SteveSandersonMS** [comment]
Interesting question, but I'm afraid it's completely separate from anything in this repo. Please check MSBuild and/or Webpack docs to find a suitable way of doing this. Hope that's OK!

**Comment by deeppriy** [comment]
Thanks for response. 
I was thinking in same direction, so I just thought to take view from expert or it might already part of this template. 

Thanks Again!!!
