### ISSUE TITLE
To use server side prerendering at runtime to produce entire HTML documents, not involving Razor at all.

### ISSUE THREAD

**Issue by anurag123chpr** [aspnet/JavaScriptServices#811]
We are using asp.net core + Angular 2 (with Angular Universal ) in our application and are trying to implement SEO. 
The application consists of static html pages with angular 2 and server side consists of Web API 's which we hit to fetch data from back-end.
But while implementing server side prerendering we encountered that we have to generate html using razor views on server side.
At this point we can't change architecture of our project, so is there any solution for server side prerendering without using razor.

**Comment by SteveSandersonMS** [comment]
Agreed this is something we should make better. It's already being tracked in #607, so I'll close this one as a duplicate. Hope that's OK!
