### ISSUE TITLE
Running dotnet publish -c Release broke the Angular template with browserify-sign@4.0.3

### ISSUE THREAD

**Issue by ajtowf** [aspnet/JavaScriptServices#812]
ERROR in ./browserify-sign/algos.js
Module not found : error : Can't resolve './browser/algorithms' in 'C:\dev\ps\aspnetcore-angular-sample\node_modules\browserify-sign' [C:\dev\ps\aspnetcore-angular-sample\aspnetcore-angular-sample.csproj]
       @ ./browserify-sign/algos.js 1:17-48
       @ ./crypto-browserify/index.js
       @ ./reflect-metadata/Reflect.js
       @ ./angular2-universal-polyfills/browser.js
       @ dll vendor

See https://github.com/crypto-browserify/browserify-sign/issues/35

I'll commit a PR that fixes this in a couple of minutes.

**Comment by SteveSandersonMS** [comment]
Thanks - will look at the PR.
