### ISSUE TITLE
How to make the {filename}.scss under the {filename}.html

### ISSUE THREAD

**Issue by seven1986** [aspnet/JavaScriptServices#814]
1,How to make the app.component.scss under the .html file?
![21](https://cloud.githubusercontent.com/assets/20808494/24393105/666f4fa6-13c9-11e7-8c2f-64ef4ba02629.png)
for now just support .css

**Comment by paddyza** [comment]
From what I can gather, .NET Core projects don't support file nesting beyond its own built in rules for nesting.

**Comment by seven1986** [comment]
should be
app.component.html
    app.component.ts
    app.component.scss/less
        app.component.css
        app.component.min.scss

**Comment by SteveSandersonMS** [comment]
I heard that future versions of VS might well allow this nesting to be varied, but that's managed separately from the JavaScriptServices project so is not something we can take action on here.
