### ISSUE TITLE
one click for create .ts/（.scss or .less or .css）/.html

### ISSUE THREAD

**Issue by seven1986** [aspnet/JavaScriptServices#815]
It is tired to create files one by one, because the file name always same.
Just use windows copy then rename that's faster than use VS - from my colleagues exp...
thanks!

![222](https://cloud.githubusercontent.com/assets/20808494/24393469/d34ba1be-13ca-11e7-80d7-6eecc383c12f.png)

**Comment by SteveSandersonMS** [comment]
Thanks for the suggestion.

If I understand correctly, you're posting this here as a tip for other to see, rather than as a bug or feature request. In that case I'll mark this closed (as there are no changes for us to make). Thanks again!
