### ISSUE TITLE
README.md: Omission of SpaTemplates & `dotnet new`

### ISSUE THREAD

**Issue by antmdvs** [aspnet/JavaScriptServices#824]
https://github.com/aspnet/JavaScriptServices#samples-and-templates does not mention SpaTemplates nor usage of `dotnet new` as prescribed here:

https://blogs.msdn.microsoft.com/webdev/2017/02/14/building-single-page-applications-on-asp-net-core-with-javascriptservices/

**Comment by antmdvs** [comment]
https://github.com/aspnet/JavaScriptServices/commit/c9486eac0bbdf589c9955619697d8ca95a33cea4 is a good step but I would still think you would want to either update the readme to call out `dotnet new` & SpaTemplates or strip the readme down and simply refer people to the blog post.

**Comment by SteveSandersonMS** [comment]
Thanks for pointing this out. Have now updated the README.
