### ISSUE TITLE
Any spa using aspnet spa generator ends up in this error...

### ISSUE THREAD

**Issue by asadsahi** [aspnet/JavaScriptServices#83]
![image](https://cloud.githubusercontent.com/assets/3470892/15430568/c249927c-1e9d-11e6-8f2c-ffb86f0a281e.png)

**Comment by laskoviymishka** [comment]
could you please provide `dotnet -v`, verbose the command you are using and `buildOptions` from your `project.json`

**Comment by asadsahi** [comment]
works fine now. dotnet cli version was old. Thanks @laskoviymishka
