### ISSUE TITLE
Using with babel-pollyfill

### ISSUE THREAD

**Issue by phrazed** [aspnet/JavaScriptServices#830]
Hi, I'm trying to use babel-pollyfill with the React-Redux template. As per the instructions, I've added babel-pollyfill to the entry value of the webpack-config.js.  However when I try to compile the solution I get this error:

Exception: Call to Node module failed with error: Error: To use HotModuleReplacement, your webpack config must specify an 'entry' value as a key-value object (e.g., "entry: { main: 'ClientApp/boot-client.ts' }")
    at attachWebpackDevMiddleware

Is it impossible to use an entry like this?

entry: [ "babel-polyfill", { 'entry': './ClientApp/boot-client.tsx' } ],

Sorry if this isn't the right repo. I'm not sure if its here or in the webpack repo, though I haven't had this problem before.

https://babeljs.io/docs/usage/polyfill/

**Comment by DanHarman** [comment]
put this at the top of `boot-server.tsx` and `boot-client.tsx`:
```
import 'babel-polyfill';
```

`webpack.config.vendor.js` should have something like this:

```
        entry: {
            vendor: [
                'babel-polyfill',
                'domain-task',
                'event-source-polyfill',
                'jquery',
                'react',
                'react-dom',
                'react-router',
                'react-redux',
                'react-router-redux',
                'redux',
                'redux-thunk'
            ],
        },
```

Not familiar with the syntax you are trying to use with nested entry...

**Comment by SteveSandersonMS** [comment]
If @DanHarman's technique works for you, great :)

If not, and you really need to put `entry: [ "babel-polyfill", { 'entry': './ClientApp/boot-client.tsx' } ]` in your webpack.config.js, then that's not a setup that `aspnet-webpack` currently supports. If you think there's a clean way we could support that, then we'd definitely be interested in a pull request hat updates `aspnet-webpack` to recognise that config style. Hope that's OK!
