### ISSUE TITLE
Bookmarked URLs and MapSpaFallbackRoute when templatePrefix is non-empty

### ISSUE THREAD

**Issue by RaviDesai** [aspnet/JavaScriptServices#834]
This may not actually be a bug - it may be expected behavior, but I was hoping someone might be able to explain to me why this is, or if there is a work-around.

I deploy my web site to a non-root location (Default Web Site\MyServer), and use MapSpaFallbackRoute to map requests to a single angular controller.  I was hoping that a bookmarked route (like: localhost/MyServer/fetch-data) would work to route me directly to the proper angular controller in my app.   When the app is rooted to "/" (instead of "/MyServer"), that does work, but when the app is rooted to /MyServer the bookmark just delivers a 404 error.

If I try to go to the top of the site `http://localhost/MyServer`, I'll get the home page, and can route properly (by following internal links) to any controller from inside my app, I only get the 404 if I try to load `http://localhost/MyServer/fetch-data` initially.

I've placed some of my relevant code below, in case it is related to some misconfiguration inside my app:

In _Layout.cshtml I have base href defined inside the `<head>` tag:
```
<base href="@Url.Content("~")" />
```

In Startup I have the following:
```
app.UseMvc( routes =>
 {
	 routes.MapRoute(
		 name: "default",
		 template: "{controller=Home}/{action=Index}/{id?}");

	routes.MapSpaFallbackRoute(
		name: "spa-fallback",
		templatePrefix: "MyServer",
		defaults: new { controller = "Home", action = "Index" } );
} );
```

In my app.module.ts:
```
@NgModule({
	bootstrap: [ AppComponent ],
	declarations: [
		AppComponent,
		NavMenuComponent,
		HomeComponent,
		PageNotFoundComponent
	],
	imports: [
		UniversalModule, 
		FormsModule,
		FetchDataModule,
		RouterModule.forRoot([
			{ path: '', redirectTo: 'home', pathMatch: 'full' },
			{ path: 'home', component: HomeComponent },
			{ path: 'fetch-data', loadChildren: './components/fetchdata/fetchdata.module#FetchDataModule' },
			{ path: '**', component: PageNotFoundComponent }
		])
	],
	providers: [
		[{ provide: APP_BASE_HREF, useValue: "/MyServer" }],
		SECURITY_INFO_PROVIDER,
		RolesService
	]
```

**Comment by ADefWebserver** [comment]
I can confirm this behavior. 
And that it works fine if you deploy to a root location like:
[http://helloworlddata.azurewebsites.net](http://helloworlddata.azurewebsites.net)
[http://helloworlddata.azurewebsites.net/fetch-data](http://helloworlddata.azurewebsites.net/fetch-data)

**Comment by RaviDesai** [comment]
Must be somewhere in my code then.  Thanks for posting.

**Comment by RaviDesai** [comment]
As a follow up, I think (for probably similar reasons) the use of a templatePrefix with MapSpaFallbackRoute prevents OpenIDConnect from operating properly.  The reason is that the middleware for OIDC creates a POST endpoint (by default at http://localhost/MyService/signin-oidc), but somehow when I pass MyService as a templatePrefix to MapSpaFallbackRoute, that endpoint is now blocked and only reports a 404 error.  

If I remove the call to MapSpaFallbackRoute and simply issue a series of individual MapRoute calls to map all route possibilities to my "Home" controller, OIDC begins working again.  That also fixes my original problem of bookmarked URLs not working.  So I guess that's my work-around.

**Comment by SteveSandersonMS** [comment]
I assume that when you say "deploy to a non-root location", you mean as an applicaction directory in IIS or similar. In that case, you just need to *not* configure a `templatePrefix` value on your `MapSpaFallbackRoute` route entry. The routing system already knows what path prefix (e.g., virtual directory name) to strip off the incoming URL before matching it against your configured routes. So you don't need to put any prefix like that on the route entries.
