### ISSUE TITLE
How to use prerendered templates by Asp.Net MVC Core Razor Engine as Angular2 template

### ISSUE THREAD

**Issue by skorunka** [aspnet/JavaScriptServices#838]
Hi, I have a Controller/Action which renders a view in an Angular2 template syntax, available on url `/angular-templates/navmenu-top`. Typing this url in a browser, renders out html, so I know it works.

When I set the `templateUrl` in a `@Component` attribute to `/angular-templates/navmenu-top`, I get this error:

```
./ClientApp/app/components/navmenu/navmenu-top.component.ts
Module not found: Error: Can't resolve './/angular-templates/navmenu-top' in 'C:\Projects\...ClientApp\app\components\navmenu'
 @ ./ClientApp/app/components/navmenu/navmenu-top.component.ts 21:18-55
 @ ./ClientApp/app/app.module.ts
 @ ./ClientApp/boot-client.ts
 @ multi event-source-polyfill webpack-hot-middleware/client?path=%2F__webpack_hmr ./ClientApp/boot-client.ts 


Do I need to change any webpack config, add any loader?

Thank you.

**Comment by ADefWebserver** [comment]
Is `navmenu-top`
`Imported `and `Declared `in app.module.ts?

**Comment by skorunka** [comment]
@ADefWebserver yes, if I change the templateUrl to`template: require("./navmenu-top.component.html")` it works, the "navmenu-top.component.html" file is in the same folder as "navmenu-top.component.ts"

`import { NavMenuTopComponent } from "./components/navmenu/navmenu-top.component";`
`declarations: [	... NavMenuTopComponent... ]`

**Comment by skorunka** [comment]
Found an answer here: http://stackoverflow.com/questions/41473511/how-to-render-asp-net-mvc-view-into-angular-2
