### ISSUE TITLE
ag grid angular 2 - prerendering issues

### ISSUE THREAD

**Issue by ibrahim978976** [aspnet/JavaScriptServices#841]
An unhandled exception occurred while processing the request.
Exception: Call to Node module failed with error: Prerendering failed because of error: ReferenceError: HTMLElement is not defined
at Object.<anonymous> (G:\RTS 3.3\RTS3.20\RTS3.17\RTS\RTS\node_modules\ag-grid\dist\lib\filter\baseFilter.js:174:31)
at Module._compile (module.js:571:32)
at Object.Module._extensions..js (module.js:580:10)
at Module.load (module.js:488:32)
at tryModuleLoad (module.js:447:12)
at Function.Module._load (module.js:439:3)
at Module.require (module.js:498:17)
at require (internal/module.js:20:19)
at Object.<anonymous> (G:\RTS 3.3\RTS3.20\RTS3.17\RTS\RTS\node_modules\ag-grid\dist\lib\filter\textFilter.js:29:20)
at Module._compile (module.js:571:32)
Current directory is: G:\RTS 3.3\RTS3.20\RTS3.17\RTS\RTS

**Comment by ibrahim978976** [comment]
Pls give me a solution ASAP

**Comment by MarkPieszak** [comment]
The Ag-grid library isn't compatible with Universal, meaning it doesn't Render on the server.
https://github.com/ceolter/ag-grid/issues/699

You can see from the Author that he has no intention of supporting it :(

You'll have to pick a component library is compatible with server renders, or disable that option in your application by removing the below attribute from your Views/Home/Index.cshtml view.

```html
<app asp-prerender-module="ClientApp/dist/main-server">Loading...</app>

<!-- change it to -->
<app>Loading...</app>
```

**Comment by ibrahim978976** [comment]
Thanks!
But now i can only see    this  <app>Loading...</app> when i run my app...
i don't have a idea to run my application with ag-grid.Please suggest now i what i need to do to run my application with ag-grid

**Comment by ADefWebserver** [comment]
Run your app in the Chrome web browser
Hit F12 to open the debug window
Click the console tab
Post any errors you see.

**Comment by SteveSandersonMS** [comment]
This seems to be a support question about Angular and "ag-grid", so I'd recommend taking the discussion to one of those communities. Hope that's OK!

**Comment by ibrahim978976** [comment]
OK.Thank You! @SteveSandersonMS.Now i will go with NG2 TABLE.
