### ISSUE TITLE
Upgrade Angular template to Angular4

### ISSUE THREAD

**Issue by ajtowf** [aspnet/JavaScriptServices#842]
Is it OK if I do this and create a PR?

Do we need to create some sort of official issue that I'm assigned to so nobody else sets of to do the same thing?

I'd like to contribute, got a pluralsight course coming out soon on building SPAs with aspnet core and javascriptservices,I'd love to bump the version :-)

Ping @SteveSandersonMS

**Comment by flightlevel** [comment]
https://github.com/aspnet/JavaScriptServices/issues/800

**Comment by ajtowf** [comment]
@flightlevel cool, I'll close this one then.
