### ISSUE TITLE
Bootstrap menu not collapsing

### ISSUE THREAD

**Issue by tigerwil** [aspnet/JavaScriptServices#846]
The bootstrap "hamburger" menu is not collapsing in some frameworks..

**Comment by Kevenvz** [comment]
Can you please specify which template(s)?

**Comment by tigerwil** [comment]
When generating an ASP.NET Core SPA application using Yeoman (Version 0.9.0)
yo aspnetcore-spa

The Bootstrap "hamburger" menu does not collapse when window is resized for the following templates:
-Knockout
-React
-Vue

The menu works fine in these templates:
Angular
Aurelia
React + Redux

Also is there a fix for the invalid html generated within the Angular template
<app><html><head><title></title><style>...</app>

**Comment by SteveSandersonMS** [comment]
Thanks for reporting this! The issue was just that we were missing `import` statements for the `bootstrap` JS in the boot-client files. You can fix it in your own app by adding the line as in this commit: https://github.com/aspnet/JavaScriptServices/commit/5dc476182cd9cf0df91a53e521dd111b99bfaed5

**Comment by tigerwil** [comment]
I generated a new SPA application using Vue template and I added the import
'bootstrap'  within the ..\ClientApp\boot.ts file
but the collapse still does not work.  Am I missing something here?

import 'bootstrap';
import Vue from 'vue';
import VueRouter from 'vue-router';
Vue.use(VueRouter);

**Comment by SteveSandersonMS** [comment]
@tigerwil Make sure you're running in development mode, or run `webpack` manually to rebuild the client-side assets. Adding that line is certainly enough to make it work when I tried.

**Comment by tigerwil** [comment]
Ok that works sorry, I should of thought of that.

Thanks
