### ISSUE TITLE
reactredux default  template state browsers differences

### ISSUE THREAD

**Issue by EmmaHansson** [aspnet/JavaScriptServices#847]
I tried to use reactredux template. And analyzed 'Fetch data' with Weather controller.

In Internet Explorer it uses cached data, in Edge it doesn't use cached data. 
How it could be explained ?

**Comment by SteveSandersonMS** [comment]
I'm guessing you mean that the HTTP request that fetches data is getting a result from the cache in IE but not in Edge. If so, I'm afraid I don't know the exact reason for why the two browsers would behave differently, but it's beyond the control of code in this repo.

If this is problematic in your app, you might need to change your server-side code to emit HTTP headers that request different caching behaviour (e.g., `Cache-Control`, etc.). Sorry I can't give a more directly useful answer!
