### ISSUE TITLE
Source maps for Angular and other libs

### ISSUE THREAD

**Issue by AndrewMayorov** [aspnet/JavaScriptServices#856]
Is it possible to get source maps for Angular and other libs available for the browser? I tried to solve it by changing webpack.config.vendor.js, but it seems that I don't have a single idea of how does it work.

**Comment by AndrewMayorov** [comment]
Looks like I got it:
1. Add "devtool" : "source-map" to the vendor webpack config.
2. Manually rebuild vendor package.

**Comment by SteveSandersonMS** [comment]
Glad you solved it!
