### ISSUE TITLE
Cache Priming?

### ISSUE THREAD

**Issue by blteblte** [aspnet/JavaScriptServices#858]
Is "cache priming" feature discontinued? Can not find how to really set it up - yet main readme..., mentions this feature.

(Last published: 2016-11-30)
https://www.nuget.org/packages/Microsoft.AspNetCore.AngularServices/1.1.0-beta-000002

Sorry - if this is a wrong place to ask this

**Comment by initialspark** [comment]
Not sure what the state of development is with it. To use it you will need the following package.

https://www.npmjs.com/package/angular2-aspnet

An example of using it is located in the musicstore app - which is a quite old now though.

https://github.com/aspnet/JavaScriptServices/blob/dev/samples/angular/MusicStore/Views/Home/Index.cshtml#L7-8

Hope that helps.

**Comment by SteveSandersonMS** [comment]
Yes, sorry, that feature was deprecated a *long* time ago. It's never been supported since Angular 2.0's original release.

It shouldn't be mentioned in docs anywhere, though I know it is still used in the very outdated MusicStore sample. We have an issue tracking the need to update this: #622
