### ISSUE TITLE
bootstrap.css.map is missing in reactredux template

### ISSUE THREAD

**Issue by EmmaHansson** [aspnet/JavaScriptServices#861]
1. Use reactredux template.
2. Run it
3. Press F12 in browser (Edge for example)
4. Find 404 error: /dist/bootstrap.css.map

I suppose it something dramatic happens in webpack.config.js file
How to fix it?

**Comment by SteveSandersonMS** [comment]
I'm not sure why you have a `bootstrap.css` file, or why the browser would be looking for a `bootstrap.css.map` file, but neither of these occurs in the templates by default.

If you specifically want to add source maps for your CSS, please see webpack docs, e.g., https://github.com/webpack-contrib/css-loader#options. Hope that's OK!
