### ISSUE TITLE
when i publish website . i have 2 dist folder

### ISSUE THREAD

**Issue by teamsmiley** [aspnet/JavaScriptServices#862]
when i publish website . i have 2 dist folder
/clientapp/dist
/wwwroot/dist

do i need both file for publish ?

**Comment by MarkPieszak** [comment]
Yes, one is all of your clientside dist files, one is used for the server-side rendering of the application.

**Comment by SteveSandersonMS** [comment]
Thanks for the answer @MarkPieszak!
