### ISSUE TITLE
Caching in IE11

### ISSUE THREAD

**Issue by beatsm** [aspnet/JavaScriptServices#863]
Hi

I have come across an issue using the Aurelia template in IE11 where the weather forecast response is cached after first use.

Is it prudent to have a note that if targeting IE11 (not that I want to but what can you do) that you should change to using the HttpPostAttribute 

`[HttpPost("[action]")]` 

in the SampleDataController and update fetchdata.ts file to use the post method 

`http.fetch('/api/SampleData/WeatherForecasts', {
            method: 'post'
        })` 

Regards

Mike

**Comment by SteveSandersonMS** [comment]
Thanks for the pointer! I hope anyone else encountering this issue finds your solution.

We have an issue tracking IE9-11 support: https://github.com/aspnet/JavaScriptServices/issues/484
