### ISSUE TITLE
HMR Stops Working After IIS Setting for Angular2 Router in web.config

### ISSUE THREAD

**Issue by MapleYe** [aspnet/JavaScriptServices#864]
Currently working on an Angular2 project on ASP,NET Core. HMR works fine before I set up IIS settings in Visual Studio 2017 for the Angular 2 router. But it stops responding to any changes in the front code/markup after I add web.config for the IIS settings  
![temp_2](https://cloud.githubusercontent.com/assets/18238023/25024611/d159de78-205b-11e7-912f-234e8cfafc13.jpg)

HMR fails starting and Chrome pops up the error in the console: 
"EventSource's response has a MIME type ("text/html") that is not "text/event-stream". Aborting the connection."

**Comment by SteveSandersonMS** [comment]
HMR relies on the browser being able to make requests to the URL `/__webpack_hmr` and getting back an event stream or websocket response. If your URL rewriting rules interfere with that, it will break :)
