### ISSUE TITLE
Cannot open client bundle after a few HMR reloads on Windows in VS 2017

### ISSUE THREAD

**Issue by markthiessen** [aspnet/JavaScriptServices#865]
```Microsoft.AspNetCore.NodeServices:Information: webpack building...
Microsoft.AspNetCore.NodeServices:Error: Error: EBUSY: resource busy or locked, open 'C:\source\xxxxxx\src\Web\wwwroot\dist\main-client.js'
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.writeFileSync (fs.js:1316:33)
    at C:\source\xxxxxx\src\Web\node_modules\aspnet-webpack\WebpackDevMiddleware.js:138:20
    at Array.forEach (native)
    at copyRecursiveToRealFsSync (C:\source\xxxxxx\src\Web\node_modules\aspnet-webpack\WebpackDevMiddleware.js:131:31)
    at C:\source\xxxxxx\src\Web\node_modules\aspnet-webpack\WebpackDevMiddleware.js:144:17
    at Array.forEach (native)
    at copyRecursiveToRealFsSync (C:\source\xxxxxx\src\Web\node_modules\aspnet-webpack\WebpackDevMiddleware.js:131:31)
    at C:\source\xxxxxx\src\Web\node_modules\aspnet-webpack\WebpackDevMiddleware.js:144:17
    at Array.forEach (native)
```

After working for a couple minutes and triggering a few HM reloads, my app starts failing with this error in debug output. I haven't so far been able to determine what it could be..

If I restart the app, it will build and run again for just a couple of HMRs.

**Comment by MarkPieszak** [comment]
Are running everything as an Admin? Just a shot in the dark

**Comment by markthiessen** [comment]
I have a suspicion that nCrunch might be the culprit. But once HMR fails, it's broken until a restart.
Will post again if disabling nCrunch makes it go away...

**Comment by markthiessen** [comment]
Quite certain this was caused by NCrunch watch.. no longer happening after disable and working for a couple days. Could keep enabled and configure to ignore specific files/projects.
Hopefully useful to someone in the future.
