### ISSUE TITLE
React router - server side rendering

### ISSUE THREAD

**Issue by Jenan** [aspnet/JavaScriptServices#869]
Hey, is it possible to use the React-Router version 4 for server-side rendering?

Thank you.

**Comment by peterlazzarino** [comment]
@Jenan saw this and thought I could maybe help. We are using a react-router 3 setup but there shouldn't be any issue with using react-router 4 as far as I know as long as the end result is using the renderToString from react-dom/server and feeding that into the html in the resolve the function passed into createServerRenderer

**Comment by SteveSandersonMS** [comment]
Please see #817
