### ISSUE TITLE
Is my gitignore file wrong for using this framework?

### ISSUE THREAD

**Issue by Mech0z** [aspnet/JavaScriptServices#875]
I have created a project on my laptop and got it running 

https://github.com/Mech0z/Foosball9001

Then I tried to clone it on another machine and doing what I have in my readme

But when I run "webpack --watch" I get errors due to 

wwwroot\dist and ClientApp\dist being in my https://github.com/Mech0z/Foosball9001/blob/master/.gitignore

Should I change it for it to work? or should I not run webpack --watch?

If I create a new yoman project and just copy the ClientApp\app of my other app into it, it works fine, so some files are missing

**Comment by SteveSandersonMS** [comment]
You can either include your `wwwroot/dist/*` and `ClientApp/dist/*` files in source control, or you can remember to rebuild them each time you start on a new machine (i.e., with `webpack --config webpack.config.vendor.js` then `webpack`).

It's up to you which approach you prefer :)

**Comment by Mech0z** [comment]
@SteveSandersonMS Removed those 2 files from my gitignore, but still I get errors

I have to first install webpack locally

And I get Cannot find module webpack-merge, is it not possible to have a git repo where you can just pull and run it?

Also I choose Angular, according to http://blog.stevensanderson.com/2016/05/02/angular2-react-knockout-apps-on-aspnet-core/ I should be able to do 

set ASPNETCORE_ENVIRONMENT=Development
dotnet run

And not run webpack at all? But when I run it nothing is recomiled, I can read Node will restart because file changed: C:\Git\test3\nod... but nothing happens when I refresh my browser, if I do webpack --watch it recompiles my files fine
