### ISSUE TITLE
How to add my own javascript file to react template (webpack config)

### ISSUE THREAD

**Issue by maximus780** [aspnet/JavaScriptServices#881]
I generated react template with yeoman. I want to add my own javascript files to the bundle. I've created it in ClientApp/js/myscripts.js beside ClientApp/components/*.tsx. I don't know what to do to include it in my bundle. Webpack configuration is black magic to me. Could anyone help me?

There is webpack.config.js and webpack.config.vendor.js I can't see the difference in these 2 files. I feel like a lost sheep.

Currently I resolved it like this:

Added 
```
...
  "compilerOptions": {
    "allowJs": true
...
```
 to tsconfig.json and imported it in .tsx file like this:
`import './js/myscripts.js'`

But the script uses jQuery and now I get

> myscripts.js:25 Uncaught ReferenceError: $ is not defined

Even if I import before like:
```

import $ from "jquery"; //or:
import * as $ from "jquery";
```

**Comment by SteveSandersonMS** [comment]
I hope you don't mind, but this is a TypeScript question (it doesn't really even involve Webpack, since you're just trying to reference a `.js` file from a `.ts` one), so could you follow up with the TypeScript community? Thanks!
