### ISSUE TITLE
How to Run Webpack to Build for Production

### ISSUE THREAD

**Issue by uNkNowN92-git** [aspnet/JavaScriptServices#885]
I've been trying to figure out how to make webpack build for production.

I added some `console.log` to check the values of variables like below:
```javascript
const isDevBuild = !(env && env.prod);
console.log(isDevBuild);
console.log(env);
```

And the output is:
```js
true
undefined
```

1. Can anyone show me how to run webpack to build production files?

**Comment by initialspark** [comment]
Hey have a looking into the following.

https://webpack.js.org/guides/production-build/

**Comment by chromefox** [comment]
@uNkNowN92-git 

I resolved mine by editing the webpack configuration to:
```
const isDevBuild = !(env && env === 'prod');
console.log("isDevBuild: " + isDevBuild);
```
and running the following console command:
`webpack -p --env=prod --progress`

Hope that helps!

**Comment by SteveSandersonMS** [comment]
@chromefox Thanks for answering.

Yes, the way to do it is to specify `--env.prod` when invoking Webpack on the command line, i.e.,

```
webpack --config webpack.config.vendor.js --env.prod
webpack --env.prod
```
