### ISSUE TITLE
Static files slow?

### ISSUE THREAD

**Issue by jbaxleyiii** [aspnet/JavaScriptServices#888]
*This may be the wrong place for this*

After playing around with the sample projects, I wanted to get a performance benchmark. I setup a deploy to [`now`](https://zeit.co/now) using a simple docker file:

```Dockerfile
FROM microsoft/aspnetcore:1.1
RUN apt-get update
RUN apt-get install curl
RUN curl -sL https://deb.nodesource.com/setup_6.x | bash
RUN apt-get install -y build-essential nodejs
WORKDIR /app
ENV ASPNETCORE_URLS http://*:80
ENV ASPNETCORE_ENVIRONMENT Production
ENV NODE_ENV production
EXPOSE 80
COPY ./bin/Release/netcoreapp1.1/publish/ /app
ENTRYPOINT ["dotnet", "RockNative.dll"]
```

The response time are really not good. Especially for loading simple static assets. Am I doing something wrong here? Are there spec requirements for running a kestrel server?

![static](https://cloud.githubusercontent.com/assets/4967600/25316294/8cf7f86c-2832-11e7-825f-94acd4605619.png)

The site is deployed [here](https://web-eqxkrklraj.now.sh/) if you want to take a look.

Thanks!

**Comment by ctolkien** [comment]
You need to take `now.sh` out of the equation and benchmark on a predictable (preferably local) service  - `Zeit` are extremely opaque about how your site will be hosted, how resources are partitioned, what is the scenario with noisy neighbours, etc.. I can't even get an answer about where the DC's are located.

**Comment by DanHarman** [comment]
Also worth noting Kestrel is not safe to use on edge deployments. https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel

**Comment by SteveSandersonMS** [comment]
This is interesting, but you're right, this is not really a good place to discuss Kestrel performance in general. It would be better to discuss it in the Kestrel repo, where you'll find more experts :) I also agree with @ctolkien that you're measuring `now`'s performance here rather than just Kestrel's.
