### ISSUE TITLE
Is it possible to execute serverside Javasctipt without NodeJs installed with alternative JS engine?

### ISSUE THREAD

**Issue by OrezObserver** [aspnet/JavaScriptServices#889]
Is it possible to execute serverside Javascript without NodeJs installed with alternative JS engine or somehow else? I am using Angular Universal with .NET Core server with server rendering. But on my hosting NodeJs is not installed. Maybe there is any solution with using portable NodeJs builds?

**Comment by SteveSandersonMS** [comment]
> Is it possible to execute serverside Javascript without NodeJs installed with alternative JS engine or somehow else?

No, sorry. It has to be a real Node instance. So much of the JS ecosystem you're relying on will be assuming Node semantics. Some other JS environment is not going to produce the same results.

> Maybe there is any solution with using portable NodeJs builds?

The NodeServices package just relies on being able to invoke `node.exe` and some Node instance starting up. The NodeServices package doesn't care how you've installed Node, whether it's a portable installation or anything else. Perhaps experiment with deploying the Node binaries along with your application. I'm not certain exactly what the minimal amount of setup is needed to make Node work normally, as that's a somewhat separate question from what we're doing in this repo. Hope you find a suitable way to make it work for you!
