### ISSUE TITLE
'WeakMap' is undefined

### ISSUE THREAD

**Issue by im1dermike** [aspnet/JavaScriptServices#891]
I just tried to open up my application generated using this tool in IE10 and I get the following error in my browser console:

> SCRIPT5009: 'WeakMap' is undefined 
> vendor.js, line 112874 character 1

It seems to trace to [this](https://github.com/webcomponents/webcomponentsjs/issues/210) thread, but the only references to "WeakMap" in this solution is in `\dist\main-client.js` and `\dist\vendor.js` so I'm unclear on how to resolve it.

**Comment by SteveSandersonMS** [comment]
If you need IE10 support, please install core-js/shim as described here: https://github.com/aspnet/JavaScriptServices/issues/854#issuecomment-293260852

As for making things work out of the box, we have an issue tracking IE9-11 support here: https://github.com/aspnet/JavaScriptServices/issues/484

**Comment by im1dermike** [comment]
@SteveSandersonMS Thanks for your replied.  I installed `corejs` and added `import 'core-js/shim';` to the top of my `boot-client.ts` file, but now I get a "Can't resolve 'core-js/shim'" error.

**Comment by SteveSandersonMS** [comment]
@im1dermike Then I don't know why that would happen - it should be possible to resolve `corejs/shim`. I'm afraid you'll have to track that down yourself :(

**Comment by im1dermike** [comment]
@SteveSandersonMS Should I be running:

    npm install --save corejs

as described in Issue 854 or

    npm install --save core-js

**Comment by SteveSandersonMS** [comment]
Ah yes, that's it - it's `core-js` and *not* `corejs`. I've updated the comment in #854 to match. Well spotted!

**Comment by im1dermike** [comment]
@SteveSandersonMS Oof.  Now I'm getting the following error:

> SCRIPT5022: Error: DI Error 
> vendor.js, line 104835 character 13

Anything you can do to point me in the right direction?

**Comment by idenev** [comment]
I can confirm the issue with IE. Following the shim installation, DI error is in place. Looking forward for possible solution.
