### ISSUE TITLE
HMR not working with Webpack 2.2.1

### ISSUE THREAD

**Issue by xevantus** [aspnet/JavaScriptServices#892]
HMR returns a 404 error when used with Webpack 2.2.1.
The Webpack middleware path appears to be encoded, and is attempting to resolve to a relative path containing the absolute path.
`http://localhost:49663/http%3A%2F%2Flocalhost%3A62132%2F__webpack_hmr` instead of `http://localhost:62132/__webpack_hmr`

The issue appears to be in WebpackDevMiddleware.ts.
Changing `const webpackHotMiddlewareOptions = '?path=' + encodeURIComponent(hmrClientEndpoint);`
to `const webpackHotMiddlewareOptions = '?path=' + hmrClientEndpoint;` allows the path to resolve normally.

versions:
"aspnet-webpack": "1.0.28",
"aspnet-webpack-react": "1.0.5",
"webpack": "2.2.1"

**Comment by SteveSandersonMS** [comment]
I've been doing a lot of manual testing of the templates over the last couple of days (including HMR support), and never once hit this issue in any configuration.

Can you still reproduce it with the current (v0.9.2) templates? If so, and you can give repro steps that work on a clean machine, please let us know!

In the meantime I'll mark this as closed because it doesn't appear to be an issue that still exists.

**Comment by xevantus** [comment]
I'm indeed still seeing this.  I've tried multiple versions of all of the packages, and am currently using the most updated version of all three.
I'm seeing the following:
![image](https://cloud.githubusercontent.com/assets/11984651/26224482/9f16bbce-3bf0-11e7-8755-40cb87575841.png)

I can confirm that the same fix from above gets HMR running again.

**Comment by xevantus** [comment]
Original issue is fixed after cleaning and restoring npm, but still having 404 issues.

The current issue is my site is not the root website in the dev environment.  So the root URL for the project is "localhost/monitor".  However, the middleware assumes that the root is "localhost". This problem will exist for any site that doesn't use "localhost" as it's root URL.

ConditionalProxyMiddleware is currently ignoring `PathBase`, which is fine in most cases since there shouldn't be anything there.  This edge case can be mitigated by checking `_pathPrefix` against the combination of `PathBase` and `Path` if the check against `Path` fails.
