### ISSUE TITLE
Publish latest changes as beta release in Nuget

### ISSUE THREAD

**Issue by peterlazzarino** [aspnet/JavaScriptServices#895]
Hi,

I had a PR merged a few weeks / month-ish ago and wanted to see if some of the newer functionality could be published to Nuget so we could use some in our project that will be going to production soon.

Thanks

**Comment by SteveSandersonMS** [comment]
The latest stuff was published to NuGet last week. The current NuGet package versions are all `1.1.1`, and include everything in `dev` up to commit 214a908c92c405c426407ab84f60bc74a4ae3eb9.
