### ISSUE TITLE
How about add "private": true to package.json?

### ISSUE THREAD

**Issue by g0t4** [aspnet/JavaScriptServices#897]
How about add `"private": true` to `package.json`? 

This will avoid the following warnings on npm install:

```bash
npm WARN Skills_Web@0.0.0 No description
npm WARN Skills_Web@0.0.0 No repository field.
npm WARN Skills_Web@0.0.0 No license field.
```

and of course avoid publishing, as web projects tend to be private.

**Comment by SteveSandersonMS** [comment]
Great idea - would you be willing to submit a pull request? Thanks!

**Comment by g0t4** [comment]
Yup
