### ISSUE TITLE
Not working on Visual Studio 2015

### ISSUE THREAD

**Issue by blinkbomber** [aspnet/JavaScriptServices#899]
Installed:
VS2015 Update 3
NET Core tools Preview 2 for Visual Studio 2015
NET Core SDK (dotnet --version 1.0.3)
TypeScript 2.2.2
Node v6.10.2

When I create a New Project and select ASP.NET Core Angular 2 Starter Application (.NET Core) template, I get the following error. I hit OK and and am unable to launch app.

![e1](https://cloud.githubusercontent.com/assets/28100006/25484960/12c2761c-2b2a-11e7-9006-9822024667ac.PNG)

When I create the project using yeoman and try to open the .csproj file in VS2015, I get the following error.

![e2](https://cloud.githubusercontent.com/assets/28100006/25484967/19f10b60-2b2a-11e7-986a-0c16361c6cfc.PNG)

I appreciate any help you guys can offer!

**Comment by GregoryKhakov** [comment]
You need to install visual studio 2017, that's only way now to open .csproj projects. Visual studio 2015 doesn't support it.

**Comment by blinkbomber** [comment]
Okay, so that's one issue down. But shouldn't the template still work?

**Comment by MarkPieszak** [comment]
You'd have to use an older version of the generator, 2015 support was dropped now that everything is csproj.

**Comment by blinkbomber** [comment]
Gotcha. Looks like I was a few weeks too late. Oh well. For those who need it later... instead of running 'npm install -g yo generator-aspnetcore-spa' to pull the latest generator, run 'npm install -g yo generator-aspnetcore-spa@0.8.7' to get the last version compatible with VS 2015
