### ISSUE TITLE
Accessing globals from boot-server prerendering

### ISSUE THREAD

**Issue by abhilash1990** [aspnet/JavaScriptServices#903]
Hello Steve,

I am using the  Angular2Spa template and below is my boot-server.ts

import 'angular2-universal-polyfills';
import 'zone.js';
import { enableProdMode } from '@angular/core';
import { platformNodeDynamic } from 'angular2-universal';
import { AppModule } from './app/app.module';

enableProdMode();
const platform = platformNodeDynamic();

export default function (params: any): Promise<{ html: string, globals?: any }> {
    return new Promise((resolve, reject) => {
        const requestZone = Zone.current.fork({
            name: 'angular-universal request',
            properties: {
                baseUrl: '/',
                requestUrl: params.url,
                originUrl: params.origin,
                preboot: false,
                // TODO: Render just the <app> component instead of wrapping it inside an extra HTML document
                // Waiting on https://github.com/angular/universal/issues/347
                document: '<!DOCTYPE html><html><head></head><body><app></app></body></html>'
            },
            onHandleError: (parentZone, currentZone, targetZone, error) => {
                // If any error occurs while rendering the module, reject the whole operation
                reject(error);
                return true;
            }
        });

return requestZone.run<Promise<string>>(() => platform.serializeModule(AppModule)).then(html => {
            resolve({
                html: html,
                **globals: { myKey: params.data.myVal }**
            });
        }, reject);
    });
}

And inside the app component constructor i am trying to access like below

 constructor(){
 **const data= (window as any).myKey;**
}

Inside  Index.cshtml 

asp-ng2-prerender-module="ClientApp/dist/main-server" 
asp-ng2-prerender-data="new { myVal = true }"

But I am getting the value as undefined.

Please suggest the steps how I can access the server side global data like appsettings in angular 2 component.

**Comment by MarkPieszak** [comment]
Do a view source, it's an object on the window that you need to access.

**Comment by abhilash1990** [comment]
I am trying to access it like this  **(window as any).myVal**

Which object of window can you please explain.

**Comment by SteveSandersonMS** [comment]
Just like @MarkPieszak suggested, I'd recommend having a look at the generated HTML file and seeing what property or properties get assigned to the `window` object. Somewhere in the HTML will be some code similar to `window.someProperty = { ... your data ... }`.

**Comment by irejwanul** [comment]
Hi, if you set `globals: {
                            postList: [
                                heading1,
                            ]
                        }`
in your boot.server.ts
Then you can retrieve in any component with following code:
`console.log((<any>window)._this.postList);`
