### ISSUE TITLE
React route with route params is doing postback

### ISSUE THREAD

**Issue by bliitzkrieg** [aspnet/JavaScriptServices#905]
For some reason a react route I have is doing a postback nomatter what I do. The SSR is working correctly but accessing the route through a link on my app triggers a postback. Any idea how I can investigate what's going on?

This is my route: 

```
    <Route path='/conference/:slug/:id' components={{ body: Conference }} />
```

Is there something I am doing wrong?

You can see all the code here: https://github.com/bliitzkrieg/Conferency/blob/master/Conferency.Application/ClientApp/routes.tsx

**Comment by SteveSandersonMS** [comment]
Sorry, I don't know. Since this issue is happening entirely within your client-side React app, I'd suggest this is more of a question to raise with the React or `react-router` community as it doesn't seem to be specific to this repo in any way that I know of. Hope that's OK!

**Comment by bliitzkrieg** [comment]
I figured it out! In case anybody has this issue, the issue was that I was using a href to change routes instead of react-router's <Link> component.
