### ISSUE TITLE
Support for Webpack Configs that Export a Promise

### ISSUE THREAD

**Issue by mattwcole** [aspnet/JavaScriptServices#907]
Webpack config promises are currently [not supported](https://github.com/aspnet/JavaScriptServices/blob/dev/src/Microsoft.AspNetCore.SpaServices/npm/aspnet-webpack/src/WebpackDevMiddleware.ts#L36) when using the dev middleware. If there is enough interest in this feature, perhaps it could be added?

**Comment by SteveSandersonMS** [comment]
Do you know what the implementation would look like? If this is really simple, we can definitely consider a PR for this! I'd be reluctant to do anything sophisticated to support this, though, as so far only one person has asked for it :)

I'll close this but if you think there's a really simple implementation, would be be interested in submitting a PR? Thanks!

**Comment by nbarbettini** [comment]
The webpack config that vue-cli outputs will always run into this issue. It looks like:

```javascript
module.exports = new Promise((resolve, reject) => {
      // some stuff...

      resolve(devWebpackConfig)
    }
  })
})
```
This causes JavaScriptServices to error with

> Exception: Call to Node module failed with error: TypeError: Cannot read property 'publicPath' of undefined

Changing the above to simply

```javascript
module.exports = devWebpackConfig;
```

Solves the issue. It would be nice if JavaScriptServices supported this use case. I can open a new issue for this if you prefer @SteveSandersonMS.

**Comment by Sky4CE** [comment]
I've created issue #1399 before reading this. So as I understand no plans to implement this feature @SteveSandersonMS ? Very sad, I'm really need it.

**Comment by SteveSandersonMS** [comment]
@Sky4CE It's not something on my list of things to do, but as per my previous comment, if you're keen I'd certainly be interested in a pull request for this feature (assuming the implementation turns out to be simple). Thanks!
