### ISSUE TITLE
500 (Internal Server Error) if accessing directly a route instead home

### ISSUE THREAD

**Issue by Cae2** [aspnet/JavaScriptServices#908]
Hello guys, Im with a strange error.

Im using aspnetcore-spa for about two months, but there is an error that aways pursue me during this time..

If I access my page using for example: `http://myserver.com:8080` everything works if I use the menus to access the inner application, `/page2` or `/page3/` for example..

but if I try directly `http://myserver.com:8080/page2` (or even if I use the steps above and just hit a F5 or Ctrl+F5) it aways throw a:

![1](https://cloud.githubusercontent.com/assets/24416663/25571542/2132f304-2e07-11e7-9803-22c601ff073f.png)

anyone has any tips to help me on this? there is also another peculiar thing... If I connect to the server via Remote Desktop and access `http://localhost:8080/page2` it works, this problem only occurs accessing from outside, but it doesnt seem like a firewall problem or so..

thanks! (I can provice the full error if someone think that its needed)

**Comment by SteveSandersonMS** [comment]
The difference between clicking links to get to the internal URLs, vs directly accessing them, is that in the latter case you're doing server-side rendering for the internal URLs and in the former case you're not.

As for why this triggers an error in your particular application, there's no way for us to know. I'm afraid you'll need to debug your code to track this down. I'd suggest checking the server logs to see if any exceptions were logged. Sorry I can't offer any more insight than that!
