### ISSUE TITLE
Doesn't build on VS2015 update 2

### ISSUE THREAD

**Issue by dmeagor** [aspnet/JavaScriptServices#91]
If you follow the instructions and download a new copy of the repo the npm install fails on the wrong sibling version of angular universal.  I attempted to update the packages but even after getting all of the npm packages to install the build then silently hangs.  Also hangs running clean or rebuild.

Running msbuild manually seems to work so perhaps the issue is with the gulp script.

**Comment by laskoviymishka** [comment]
Hi,
could you please clarify what exact sibling fails and what exact project fail to install dependencies? I just run `npm install` on fresh machine and it works good.

**Comment by dmeagor** [comment]
I just did a clean git clone and followed the manual process (no luck with VS either.)

C:\Users\dmeag\Documents\Visual Studio 2015\Projects>node -v
v4.4.4

C:\Users\dmeag\Documents\Visual Studio 2015\Projects>npm -v
2.15.1

dotnet restore
cd samples/angular/MusicStore/
npm install [err - see below]

`npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package angular2-universal@0.98.1 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer angular2-express-engine@0.13.0 wants angular2-universal@>=0.100.3
npm ERR! peerinvalid Peer angular2-hapi-engine@0.13.0 wants angular2-universal@>=0.100.3

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\dmeag\Documents\Visual Studio 2015\Projects\JavaScriptServices\samples\angular\MusicStore\npm-debug.log`

**Comment by hisomu** [comment]
I also had this issue, I resolved it by adding angular2-express-engine and  angular2-express-engine into package.json

ie 
` "dependencies": {
   ..
    "angular2-express-engine": "0.11.1",
    "angular2-hapi-engine": "0.11.1",
    ..
  }`

**Comment by SteveSandersonMS** [comment]
You're on NPM version 2.x, which runs into path length limitations on Windows and doesn't reliably restore the `angular2` packages. Please try upgrading to a newer version of Node which includes NPM 3+.
