### ISSUE TITLE
HMR Error When Running From CLI

### ISSUE THREAD

**Issue by jkruer01** [aspnet/JavaScriptServices#910]
If I run my application from Visual Studio by clicking on the green arrow, it launches on port 60186 and everything works fine.

However, if I launch the application from the cli using
`dotnet run`

I get errors in Chrome's debugger that state "EventSource's response has a MIME type ("text/html") that is not "text/event-stream". Aborting the connection."

How can I fix these errors when running from the CLI?

**Comment by SteveSandersonMS** [comment]
Sounds like your CLI-launched application is running in production mode. You need to run it in development mode. Please see https://docs.microsoft.com/en-us/aspnet/core/fundamentals/environments

**Comment by AlwaysAbhl001** [comment]
@SteveSanderson  What ever, After deployed our environment is not dev on that case  Hotmodule wont be used. so then how to handle this issue ?
