### ISSUE TITLE
Error  in boot-server.tsx for react-redux app when deploying to Azure 

### ISSUE THREAD

**Issue by Tonvengo** [aspnet/JavaScriptServices#917]
Hi. I got this error when I try to deploy fresh react-redux app.
`ERROR in [at-loader] ./ClientApp/boot-server.tsx:43:25 TS2345: Argument of type '{ html: string; globals: { initialReduxState: ApplicationState; }; }' is not assignable to parameter of type 'RenderToStringResult | RedirectResult | PromiseLike<RenderResult>'. Type '{ html: string; globals: { initialReduxState: ApplicationState; }; }' is not assignable to type 'PromiseLike<RenderResult>'. Property 'then' is missing in type '{ html: string; globals: { initialReduxState: ApplicationState; }; }'.

Can anyone help me with this?
Thank you in advance!

**Comment by marcelush** [comment]
the problem might be aspnet-prerendering package, try using aspnet-prerendering@2.0.3

**Comment by SteveSandersonMS** [comment]
Sorry for the inconvenience. This is now fixed as per discussion in #918 - just update to the latest `aspnet-prerendering` to get the fix.
