### ISSUE TITLE
An unhandled exception has occurred: Call to Node module failed with error: Error: No provider for CompilerFactory!

### ISSUE THREAD

**Issue by JohnGalt1717** [aspnet/JavaScriptServices#927]
Hi there.

I'm attempting to do an inplace upgrade to Angular 4 and everything works fine except for server side pre-rendering. (I.e. if I disable <app asp-prerender-module="ClientApp/dist/main-server" asp-prerender-data="serviceData">Loading...</app> and just use <app>Loading...</app> it's fine.

I've removed angular-universal and switched to the core functions for this.

I've looked at https://github.com/MarkPieszak/aspnetcore-angular2-universal trying to figure out what it's doing in specific (i.e. getting AOT working and this) but I can see anything substantively different. (Although there are alarming changes in it)

Given that I'm not seeing any development in this repo for Angular 4, what are our options going forward? Starting to feel like this is abandonware and it would just be better to start using Node and skip .net core entirely.

**Comment by ADefWebserver** [comment]
Please see that there are a large number of recent closed issues (including fixes) before accusing this project of being 'abondonware'.

**Comment by JohnGalt1717** [comment]
Angular 4, the most used SPA on the market has been out for almost 2 months. There isn't any check-in at all, and based on the rules setup by Google and companies like Kendo, if you don't upgrade you're toast because even bug fixes aren't being back ported.

There hasn't been a single check in that I have found, not a single branch indicating that anyone at MS is working on Angular 4 support. None.

MS doesn't abandon. It kills through patch only with nothing new. (see WinForms)  But the result is the same and in this case, this is going to become a useless project very quickly if this isn't done. And if this isn't done, then there is 0 reason for me to use .NET core and asp.net core going forward when I can just use node and the fully supported and continually updated tools from google.

Thus this should deeply concern people at MS because you're giving me yet another reason to abandon development on MS platforms.

If I'm wrong and someone is stealth working on getting this updated, great! Show me where and give us a timeline. But given the silence and nothing in the repo that I can see I strongly doubt it.

In the mean time, anyone have a solution to the actual error?

**Comment by SteveSandersonMS** [comment]
@JohnGalt1717 This is far from abandoned. It's very much in active development, as per @ADefWebserver's comment. I'll close this because we already have another issue tracking Angular 4 work.

**Comment by JohnGalt1717** [comment]
Well the other issue points to a complete separate git hub repo not this one and that one is VASTLY different than this and until now there's been no comment that that was going to get merged into this.

Also my root question still remains: How do I fix this: Call to Node module failed with error: Error: No provider for CompilerFactory!

**Comment by ADefWebserver** [comment]
@JohnGalt1717 Please see #930 for instructions on how to try the Angular 4 version of the template. Report any issues against that version rather than from your own upgrade.

Keepin mind @SteveSandersonMS 's comment:
> As per [this comment](https://github.com/aspnet/JavaScriptServices/issues/800#issuecomment-300823558), this is a first step towards updating to Angular 4. It's an attempt at the minimal changes needed to get Angular 4 working correctly on both client and server.
