### ISSUE TITLE
Issue on version upgrade. Angular 2.4 => Angular 4

### ISSUE THREAD

**Issue by dasdecoder** [aspnet/JavaScriptServices#929]
ERROR in [at-loader] ./node_modules/angular2-platform-node/node-platform.d.ts:1:10
TS2305: Module ‘”C:/angular/node_modules/@angular/platform-browser/platform-browser”‘ has no exported member ‘AnimationDriver’.

ERROR in [at-loader] ./node_modules/angular2-platform-node/node-renderer.d.ts:2:10
TS2305: Module ‘”C:/angular/node_modules/@angular/platform-browser/platform-browser”‘ has no exported member ‘AnimationDriver’.

**Comment by SteveSandersonMS** [comment]
We're working on the Angular 4 update in #800.

**Comment by imleihuang** [comment]
Hi, is this problem solved?
