### ISSUE TITLE
Angular 2 in debug mode not working with InputOutputStream

### ISSUE THREAD

**Issue by laskoviymishka** [aspnet/JavaScriptServices#93]
### Steps to reproduce

1. Open solution
2. Select Angular2Spa from templates as startup project
3. Change `HostingModel` by adding following code in `ConfigureServices` method:
```
            services.AddNodeServices(new NodeServicesOptions
            {
                HostingModel = NodeHostingModel.InputOutputStream
            });
```
4. Open any page
5. See exception
```
JsonReaderException: Unexpected character encountered while parsing value: A. Path '', line 0, position 0.
```

### The issue

Page not load, and exception accured

```
JsonReaderException: Unexpected character encountered while parsing value: A. Path '', line 0, position 0.
```

### Further technical details

This is pretty easy issue - right now `InputOutputStreamNodeInstance` wait for first recieved data from Node, and claim it as boot function response. With ng2 it not so, since in development mode it everytime produce message: `Angular 2 is running in the development mode. Call enableProdMode() to enable the production mode.`
To fix this issue we need implement some kind of filtering our result. Root couse placed inside `OnOutputDataReceived` method in `InputOutputStreamNodeInstance` class.

**Comment by SteveSandersonMS** [comment]
As per discussion on the pull request, `InputOutputStream` is now obsolete and has been removed, so this issue no longer applies.

**Comment by laskoviymishka** [comment]
What is alternatives?

**Comment by laskoviymishka** [comment]
My bad, didn't mention pr sisscussion
