### ISSUE TITLE
Contributing section instructions missing webpack step

### ISSUE THREAD

**Issue by ferrx** [aspnet/JavaScriptServices#934]
From https://github.com/aspnet/JavaScriptServices#contributing

```
If you're interested in contributing to the various packages, samples, and project templates in this repo, that's great! You can run the code in this repo just by:

Cloning the repo
Running dotnet restore at the repo root dir
Going to whatever sample or template you want to run (for example, cd templates/Angular2Spa)
Restoring NPM dependencies (run npm install)
Launching it (dotnet run)
```

You can reproduce this error by following the current directions.

After performing these steps, the wwwroot directory is empty (except for a favicon). The step to bundle js/css is never performed. You will get an error when navigating to localhost:5000 with logs showing that the bundled js/css requests are coming back with 404 errors.

Either include a step for `dotnet publish` which performs the required webpack commands AND npm install, or explicitly include the two webpack commands as steps. I think the difference would be that `dotnet publish` will set the environment to `production` whereas it may be in `development` by default. If going with the former, removing the `npm install` direction in the contributor notes would be possible.

**Comment by SteveSandersonMS** [comment]
Thanks - have updated the instructions.
