### ISSUE TITLE
Problem with dist assets and git

### ISSUE THREAD

**Issue by PeterWone** [aspnet/JavaScriptServices#936]
To reproduce
---
1. Mint a new project with `dotnet new aurelia`
1. Load the project in VS2017 and run it successfully.
3. Create a git repo then push it to VSTS then pull it to some other location
1. Use VS2017 to open the project in the folder you just pulled. 
1. Run the project and observe that `UseWebpackDevMiddleware` barfs because it can't find `vendor-manifest.json`
1. Inspect the `wwwroot` folder and observe that `dist` is absent.

Workaround
---
Obtain dist and contents from another project. A freshly minted one will do.
  
Question
---
Is there a simple way to cause generation of the dist folder and its contents?

**Comment by SteveSandersonMS** [comment]
> Is there a simple way to cause generation of the dist folder and its contents?

Yes, run `webpack --config webpack.config.vendor.js`.

**Comment by PeterWone** [comment]
The project template needs a CLUES.TXT file for help newbies to get clues.

I actually tried to do that  with webpack based on similar issues reported for other projects, but it wasn't on my node shell's path and when you don't know anything about webpack and how it's supposed to be used you're just blundering around in the dark not knowing what to search for. No-one tells you that (a) you have to run it with node, (b) you explicitly path to it. The only thing that tipped me off to this was a chance look inside the csproj file. 

If I hadn't read CSPROJ I _still_ wouldn't have a resolution because I wouldn't know how to use your suggestion. If you put this and similar stuff in CLUES.TXT it would save newbies a lot of grief.

**Comment by SteveSandersonMS** [comment]
> No-one tells you that (a) you have to run it with node, (b) you explicitly path to it

You don't need to. If you run `npm install -g webpack`, then `webpack` becomes available as a global tool.

Sorry there is a lot to learn. We do have some docs ([most linked from here](https://github.com/aspnet/JavaScriptServices)), but I don't know there's a particular set of clues that everybody needs to know. Some people know Node/Webpack well but have no idea about `dotnet`, others know C#/dotnet but are just getting started with Webpack, others are new to Angular/React/etc. So in the end we have docs and hope that people can find their way to the bits they need to know. If you can suggest improvements to the docs (not ones that are just tuned to your own specific needs, but balanced for everyone that's going to be using these templates), please let us know!

**Comment by PeterWone** [comment]
Yes I agree on all points, yet it’s still a problem.

It needs to be centralised per the project template yet user driven. A wiki?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by PeterWone** [comment]
I was so busy complaining about the imperfections I forgot to say what a fantastic boon this template is. You are doing a fantastic job and your efforts are hugely appreciated.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by SteveSandersonMS** [comment]
Thanks @PeterWone!
