### ISSUE TITLE
react-hotkeys not working when HMR is activated

### ISSUE THREAD

**Issue by raphi011** [aspnet/JavaScriptServices#939]
In my project I'm using react-hotkeys to handle hotkeys such as F1, ctrl+s, etc which are normally used by the browser. These work as intended when the HMR feature is deactivated, but when I activate it the handlers don't get called and the browser handles them (and e.g. opening the save dialog).

This is annoying while developing because to test them I have to deactivate HMR.

I have no clue why this is happening, does anyone have a similar issue?

**Comment by SteveSandersonMS** [comment]
Sorry, I don't know. It might be better to bring this to the attention of the `react-hotkeys` people since the templates here don't do anything nonstandard (it's just a stock React+HMR setup).
