### ISSUE TITLE
Aurelia template threw syntaxerror

### ISSUE THREAD

**Issue by nicewk** [aspnet/JavaScriptServices#940]
After generate Aurelia app, it runs without error with dotnet cli, but doesn't work in the vs2017 with iis express. A exception throw from the code: app.UseWebpackDevMiddleware(.,.,). The error message as below:
Call to Node module failed with error: SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.requireNewCopy (D:\Labs\Aurelia\node_modules\aspnet-webpack\RequireNewCopy.js:16:16)
    at createWebpackDevServer (D:\Labs\Aurelia\node_modules\aspnet-webpack\WebpackDevMiddleware.js:171:48)
    at createWebpackDevServer (C:\Users\n9wal\AppData\Local\Temp\tmpE47F.tmp:74:50)

**Comment by mabouchalkha** [comment]
i have the same issue try to run this 2 lines

`
node node_modules/webpack/bin/webpack.js --config webpack.config.vendor.js --env.prod
 node node_modules/webpack/bin/webpack.js --env.prod
`

**Comment by rlwilkerson** [comment]
I'm getting the same exception.  Created a new project, restored the packages, set the environment to development and ran.  No modifications are made to the project.

If I change the environment back to "Production" the project will run successfully..

**Comment by nicewk** [comment]
I found the reason that was caused webpack who doesn't recognize var { AureliaWebPlugIn } syntax, as well as constructor(options=[]); , [ x, y]. It seams like something lost when called to wabpack --config.

**Comment by SteveSandersonMS** [comment]
I'd definitely like to fix this, but so far have been unable to reproduce the issue.

What version of the template package are you using to generate the Aurelia app? Does it still happen if you use the current version (0.9.2) of the template package?

Does the error still repro if you [clean your NPM cache](https://docs.npmjs.com/troubleshooting/try-clearing-the-npm-cache) before creating a new project?

**Comment by nicewk** [comment]
@SteveSandersonMS Thanks.
The issue is still there after I reinstalled template, cleared the npm cache, and created new project.  The screenshot is the error when I ran the webpack cli.
<img width="548" alt="error" src="https://cloud.githubusercontent.com/assets/14103977/26202262/4a0ce6a8-3c09-11e7-9c04-4db5feadf546.png">

**Comment by SteveSandersonMS** [comment]
Oh, I see what the issue is. Your version of Node.js is too old. Please update to 6.x or later.

**Comment by zewa666** [comment]
Would adding an engines section in the package.json help to result in better error messages?

**Comment by SteveSandersonMS** [comment]
That sounds like a good idea. PR would be welcomed!

**Comment by nicewk** [comment]
@SteveSandersonMS Thank you so much! I will update nodejs to latest version and try again. The node was installed by VS 2017 installer. :(

**Comment by zewa666** [comment]
before doing so @nicewk could you try adding this to your package.json and see if you get any hints on npm install?

```
"engines" : { "node" : ">=6.0.0" }
```

**Comment by nicewk** [comment]
@zewa666 not any special hints. The engines didn't take effect.

**Comment by zewa666** [comment]
Yeah that ones on the Aurelia side. We're on it ;) thanks for checking though
