### ISSUE TITLE
integrating lodash in this, or any, ng2+ app?

### ISSUE THREAD

**Issue by larstbone** [aspnet/JavaScriptServices#942]
Don't know if it's a limitation of ng2, webpack or what, but am having trouble integrating lodash.  Anyone have any luck with this?

**Comment by SteveSandersonMS** [comment]
I don't know of any specific problems with using lodash. In general, the templates in this repo give you a standard Webpack setup, so I'd suggest consulting Webpack docs for any info you need about using third-party libraries.

If you track down some specific bug in the code in this repo, please do let us know as we would definitely want to fix it. Thanks!
