### ISSUE TITLE
Angular 2 template - Problem running jquery in a view thats not part of the Angular App

### ISSUE THREAD

**Issue by jagmagh** [aspnet/JavaScriptServices#943]
I have created a project using the Angular 2 template of JavascriptServices.

In that template, based on my understanding of webpack configuration, the vendor.js file already includes JQuery. I also opened up the file generated and I can definitely find JQuery included in the file generated by the development mode of webpack.

This vendor.js file is included in my _Layout.cshtml as I need it for all my views. 
The order of loading is as given below
```
<script src="~/dist/vendor.js" asp-append-version="true"></script>
<script src="~/dist/site.js" asp-append-version="true"></script>

```
In the site.js file, I get the dreaded "`Uncaught ReferenceError: $ is not defined`" error
```

$(document).ready(function() {

```
when trying to access the the JQuery $ object as it doesnt recognize it.

Since vendor.js has already jquery in it, I was expecting to be able to use $ in my site.js
Am i missing something here?  or is there something fundamentally wrong in my understanding of how all of this fits together?

Note : I am not trying to use jQuery $ inside of my Angular application itself. This site.js is just part of my Razor view.

**Comment by SteveSandersonMS** [comment]
In general, Webpack-packaged apps aren't meant to expose their imports to the global namespace, because everything is meant to be self-contained.

But if you really want to do this, see http://stackoverflow.com/questions/29080148/expose-jquery-to-real-window-object-with-webpack

**Comment by jagmagh** [comment]
Thanks for the explanation. I am still finding my feet with webpack and that really helps understand better how it works.
