### ISSUE TITLE
Template AureliaSpa - aurelia-syncfusion-bridge integration  Question

### ISSUE THREAD

**Issue by atoninelli** [aspnet/JavaScriptServices#944]
I say I'm totally new to Aurelia and in general to Webpack / npm,
this said, I'm trying to integrate the [syncfusion UI](http://aureliajq.syncfusion.com/) in the template, using [aurelia-syncfusion-bridge](http://aureliajq.syncfusion.com/).
Till now without success.

Did the following steps:
- dotnet new aurelia 
[generated a working core, dotnet, aurelia project]

- install/update existing npm packages

- installed from npm: 'syncfusion-javascript' and 'aurelia-syncfusion-bridge' as you can see from the attached file **package.json**
 also added (in package.json) a 'resource' such as:
"aurelia": {
    "build": {
      "includeDependencies": "aurelia-*",
      "resources": [        "aurelia-syncfusion-bridge/button/button"      ]
    }
  }

- in **webpack.config.js** added  cur|gif support in module / loaders (webpack.config.js attached)

- in **boot.ts** added:  aurelia.use.plugin('aurelia-syncfusion-bridge', (syncfusion) => syncfusion.ejButton()) , boot.ts is attached

- in **app.html** added syncfusion-javascript  css &lt;require&gt; tag (app.html is attached)

- in home.html trying to integrate 
 &lt;button ej-button="e-text:submit" e-on-click.delegate="click()"&gt;&lt;/button&gt;
but ej- attributes are not recognized (no text displayed and no event fired).

Am I missing something?
[app.html.txt](https://github.com/aspnet/JavaScriptServices/files/1007024/app.html.txt)
[boot.ts.txt](https://github.com/aspnet/JavaScriptServices/files/1007027/boot.ts.txt)
[package.json.txt](https://github.com/aspnet/JavaScriptServices/files/1007025/package.json.txt)
[webpack.config.js.txt](https://github.com/aspnet/JavaScriptServices/files/1007026/webpack.config.js.txt)

Thanks for your answers.

**Comment by SteveSandersonMS** [comment]
This is an interesting question, but unfortunately this issue tracker isn't a good place for support requests relating to specific third-party libraries such as SyncFusion. Could I suggest you move this question to the `aurelia-syncfusion-bridge` community? Thanks!

**Comment by atoninelli** [comment]
Thanks Steve,
opened the same Question in
[https://github.com/aurelia-ui-toolkits/aurelia-syncfusion-bridge/issues/62](https://github.com/aurelia-ui-toolkits/aurelia-syncfusion-bridge/issues/62)
Bye.
