### ISSUE TITLE
asp-prerender-module isue with service fabric

### ISSUE THREAD

**Issue by vidya091209** [aspnet/JavaScriptServices#949]
i am using angular 2 app and hosting it in service fabric cluster.
locally(local cluster) every thing works.
but when i host in azure cluster it is not working.
i have used **asp-prerender-module** tag.
i have installed node.js manually on cluster VM.  but it is still not working.
when i remove **asp-prerender-module** tag it start rendering. 
Note: every script in copied on cluster i  have verified vendor.js and client.js

**Comment by SteveSandersonMS** [comment]
Thanks for letting us know. Do you have specific error messages, or something else that would give an indication of what might need to be fixed?

**Comment by SteveSandersonMS** [comment]
I'll close this due to inactivity. If you do manage to find out what the error messages are, please let us know.
