### ISSUE TITLE
Zone parameters always empty

### ISSUE THREAD

**Issue by JKetelaar** [aspnet/JavaScriptServices#950]
### Title
When using `Zone.current.get("any param")` the result is always null.

### Functional impact
`Zone.current.get` does not work properly.

### Minimal repro steps
1. Install default/latest JavaScriptServices; `yo aspnetcore-spa`
2. Add `asp-prerender-data='new { }'` to the `<app/>` within index.cshtml
3. For example add `cookies` as a data object; `cookies = ViewContext.HttpContext.Request.Cookies`
4. Within any part of the module, add `Zone.current.get('cookies')` and print this somehow
5. The result is now undefined

### Expected result
Instead of `get` returning undefined, return the actual result.

### Actual result
`get` returns undefined instead.

### Further technical details
When printing the entire zone, the properties are also empty:
```
Microsoft.AspNetCore.NodeServices:Information: Zone {
  _properties: { isAngularZone: true },
  _parent: 
   Zone {
     _properties: {},
....
}
```

This also causes issues with [angular2-cookie](https://github.com/salemdar/angular2-cookie), as it's requesting [`Zone.current.get('req')`](https://github.com/salemdar/angular2-cookie/blob/74d6434669eb235ee05a46f8219222a67c92dc8c/src/services/cookies.backend.service.ts#L12), which is undefined too;
This `console.log(cookieService.getAll());` causes:
```
Exception: Call to Node module failed with error: Error: Uncaught (in promise): TypeError: Cannot read property 'headers' of undefined
TypeError: Cannot read property 'headers' of undefined
```

Am I missing anything or is this the expected result due to a bug?

**Comment by SteveSandersonMS** [comment]
`asp-prerender-data` has never automatically populated `Zone`, so I'm not sure how to make sense of your repro steps. If you're having issues with using the `Zone` APIs, can you close report that to the Zone/Angular project?

**Comment by JohnGalt1717** [comment]
@SteveSandersonMS In the previous versions before Angular 4 you could at least set the values in the zone properties in the boot-server.ts. Now however all of that's gone.

How do we push values from .net mvc through to our apps now?

**Comment by JKetelaar** [comment]
Hi @SteveSandersonMS, sorry for missing a bit of information.

As @JohnGalt1717 already commented, it's hard to figure out how Zone is getting populated, as the documentation is meant for an earlier version of this build and I'm using the latest version with Angular 4.

First thing I've tried is using the providers constant and adding content into there:
```
    const providers = [
    ...
        { provide: "cookies", useValue: params.data.cookies }
    ]
```

Next thing I've tried is running the zone within the `platformDynamicServer` return:
```
    return platformDynamicServer(providers).bootstrapModule(AppModule).then(moduleRef => {
        const appRef = moduleRef.injector.get(ApplicationRef);
        const state = moduleRef.injector.get(PlatformState);
        const zone = moduleRef.injector.get(NgZone);

        // This is what I've adjusted
        zone.run(() => this.cookies = params.data.cookies);
```
Neither of these adjustment make it solve the issue.

Could you either tell me if this is a bug or how to correctly populate the Zone with the latest code?
Thanks!

**Comment by SteveSandersonMS** [comment]
> as the documentation is meant for an earlier version of this build and I'm using the latest version with Angular 4.

Can you let me know what documentation you're referring to? There shouldn't be any documentation about using Zone APIs here, because that's framework-specific - all docs about that should be maintained by the Zone/Angular project owners.

> Could you either tell me if this is a bug or how to correctly populate the Zone with the latest code?

Zone is a third-party framework API. In general this repo isn't a good place to raise framework-specific questions - those need to be addressed to the relevant third-party framework community, as we can't scale otherwise. I hope that seems reasonable!

However I have pushed a framework-specific example here: https://github.com/aspnet/JavaScriptServices/commit/678e2300211ad6f0eec9e84103e7173cf0890a66. This uses Angular 4's DI APIs to get the `asp-prerender-data` value to Angular components. Hope that helps.

**Comment by JohnGalt1717** [comment]
Window is unassigned during server side pre-render and throws an unhelpful error.
