### ISSUE TITLE
Lazy routes not working

### ISSUE THREAD

**Issue by clintsinger** [aspnet/JavaScriptServices#955]
I have a project based off of the Angular 2 `dotnet new SpaTemplate` where I had a router which used a number of lazy loaded modules.   I then used the `generator-aspnetcore-spa` to create a version sample compatible with Angular 4.   I then used the Angular 4 version as the template for upgrading my Angular 2 project.

Now that I have changed over to Angular 4 my lazy loaded routes aren't working anymore.  I get a message in the browser about the module not being found.  The routes themselves haven't changed from the V2 version.

I also added a simple lazy loaded module to the plain yeoman version and it behaves the same way so it definitely appears to be something about the new version - either the routing logic changed or webpack isn't doing its thing, etc.

**Comment by skorunka** [comment]
You have to define your lazy routes like `{ path: 'projects', loadChildren: './+project/project.module#ProjectModule' },`.

See thsi SO: http://stackoverflow.com/a/43396199/522322

Modify `webpack.config.js`:

```
const path = require('path');
const webpack = require('webpack');
const merge = require('webpack-merge');
const CheckerPlugin = require('awesome-typescript-loader').CheckerPlugin;
const ExtractTextPlugin = require("extract-text-webpack-plugin");

module.exports = (env) => {
	// Configuration in common to both client-side and server-side bundles
	const isDevBuild = !(env && env.prod);
	const isSSREnabled = (env && env.ssr) ? true : false;

	console.log(`==== Dev: ${isDevBuild} SSR: ${isSSREnabled} ====`);

	const sharedConfig = {
		stats: { modules: false },
		context: __dirname,
		resolve: { extensions: ['.js', '.ts', '.scss'] },
		output: {
			filename: '[name].js',
			publicPath: '/dist/' // Webpack dev middleware, if enabled, handles requests for this URL prefix
		},
		module: {
			rules: [
				{
					test: /\.ts$/, exclude: [/\.(spec|e2e)\.ts$/],
					use: [
						{
							loader: 'ng-router-loader',
							options: { loader: 'async-import', genDir: 'compiled' }
						},
						'awesome-typescript-loader',
						'angular2-template-loader'
					]
				},
				{ test: /\.scss$/, use: ['to-string-loader', 'css-loader', 'sass-loader'] },
				{ test: /\.css$/, use: ['to-string-loader', isDevBuild ? 'css-loader' : 'css-loader?minimize'] },
				{ test: /\.html$/, use: 'html-loader?minimize=false' },
				{ test: /\.(png|jpg|jpeg|gif|svg)$/, use: 'url-loader?limit=25000' }
			]
		},
		plugins: [new CheckerPlugin()]
	};
...
``` 
The code snippet alse has a `scss` support. You will need to `npm i -D ...` all the required packages(cant remember which).

**Comment by SteveSandersonMS** [comment]
Thanks for the answer, @skorunka!

**Comment by clintsinger** [comment]
The route configuration is the same as before but what I did have to add were the differences outlined in the `webpack.config.js` and import the `ng-router-loader`. 

Since this is the required configuration to make lazy routes work, any reason to not include it as part of the default template?

**Comment by skorunka** [comment]
@clintsinger Yes, I think it should be included by default.

**Comment by SteveSandersonMS** [comment]
@clintsinger @skorunka Would either of you be willing to write up the steps to enable lazy routes as a wiki entry [under "Recipes" here](https://github.com/aspnet/JavaScriptServices/wiki)?

If others want to do this, it would be great to have a clear place to point them. And then if it turns out to be a common request, we can certainly consider migrating it to be in the default setup.

**Comment by skorunka** [comment]
@SteveSanderson Sure. Do I need a permission to edit the page?

**Comment by ste4net** [comment]
I had the same "problem" with Angular2 template. There was information somewere in this repository.
Anyway I made the same things i have done for Angular2.
Add angular2-router-loader package and change webpack config to
```
                {
                    test: /\.ts$/, include: /ClientApp/, use: ['awesome-typescript-loader?silent=true','angular2-router-loader', 'angular2-template-loader']
                },
```
