### ISSUE TITLE
Please Add an Example of how to Get .NET variables into Angular code for Angular 4

### ISSUE THREAD

**Issue by JohnGalt1717** [aspnet/JavaScriptServices#956]
In the past you could inject the params.data.xxx into the zone in the boot-server.ts

Then you could get them with Zone.get("xxx") and you were good.

But now this doesn't work because there is no zone setup in the boot-server.ts and there doesn't appear to be any reasonable way to pass the values. The const providers = ... in boot-server.ts looks promising but I can't get this to inject properly anywhere with a value.

This is a major (and only) blocker for us going to production. Any assistance would be greatly appreciated. I'm 16 hours in on trying to make this work with no luck no matter what I try.

**Comment by jrmcdona** [comment]
What do you mean by variables, do you have an example?   Like an HttpContext.User.Identity.IsAuthenticated?

**Comment by JohnGalt1717** [comment]
Ie environment variables such as urls for where your API is so that when you do ci build and release the paths aren't hard cider and point to the right version of the API depending on the environment settings of the release target.

This is absolutely vital for a viable system in anything short of the most basic case. Sane people don't put their API in the same app as their UI.

**Comment by jrmcdona** [comment]
I see, never done it that way via boot server, etc..   I don't work on this repo so maybe they will have  better answer using this their template.     Could you use the Web.config and transform it per enviornment during built process?    That is how we have currently done it in one of my projects.

**Comment by JohnGalt1717** [comment]
@jrmcdona  Obviously that's one approach to get it into .NET. And getting it into the browser is easy using global variables set on the page.

But that DOES NOT in ANY WAY have anything to do with the issue at hand. YOU MUST be able to pass these values to node in the back end for server side pre-rendering because in an SPA ALL data comes from an ajax call AND thus things like product lists etc. have to be filled in for pre-rendering to matter at all.

There used to be a way (that was poorly documented) that worked that allowed you to pass these variables. However that way is now gone. Thus I need the maintainers of the project to fully document and give an example of it actually working to solve this MAJOR issue.

Please read and if you don't know the answer please don't answer.

**Comment by ADefWebserver** [comment]
> Please read and if you don't know the answer please don't answer.

I would hope that we can be kind and considerate to each other. 
Also, for others facing this issue, see: https://github.com/aspnet/JavaScriptServices/issues/964

**Comment by JohnGalt1717** [comment]
How is my request to read the post carefully and not try and answer a question without first fully reading and understand the problem inconsiderate?  When someone posts needlessly it simply clogs up the thread for which I have a vital issue that has yet to be resolved with a concrete answer no matter where and how I've asked it.  

The issue is still unresolved and the linked thread was originally referenced by me and there still is no answer and the suggested documentation is no longer relevant with angular 4 as the entire load process has changed and thus the documentation is out of date.

**Comment by SteveSandersonMS** [comment]
The template update from Angular 2 to Angular 4 has not changed anything about how prerendering exposes data to your boot function, so the docs that @ADefWebserver linked to are still applicable. In `boot-server.ts`, the `params.data` value still contains the JSON-serialized data supplied via `asp-prerender-data`. This is all framework-agnostic, and it's up to you what to do with `params.data` in your `boot-server.ts` file.

I have now published an example of getting `asp-prerender-data` values to Angular 4 components here: https://github.com/aspnet/JavaScriptServices/commit/678e2300211ad6f0eec9e84103e7173cf0890a66

In future cases, if you have questions like this that are specific to a particular third-party framework such as Angular, would you be able to address them to that third-party framework's community/docs? We don't have the capacity here to provide end-to-end guidance on all aspects of third-party framework usage. I know it's inconvenient that there isn't any one specific place you can get all questions answered, but we're not in a position to solve that problem. Hope that seems reasonable!

**Comment by JohnGalt1717** [comment]
I got this partially working (I'm using a Hybred of this and @MarkPieszak 's code so I can get AOT and Tree Shaking going) so that it now loads server side and I can pull on the client side from window.TRANSFER_CACHE.  But oddly even with this:

{
            provide: 'SERVICE_URL', useValue: (<any>window).TRANSFER_CACHE.serviceUrl
        }, {
            provide: 'CLIENT_ID', useValue: (<any>window).TRANSFER_CACHE.clientId
        }, {
            provide: 'SITE_URL', useValue: (<any>window).TRANSFER_CACHE.url
        }

in the browser-app.module.ts which is I believe the same as what you have in the boot-browser.ts fall intents and purposes they still aren't being provided, so I'm having to fall back to the TRANSFER_CACHE again. While it works it's non-optimal. 

Any suggestions to get this to reliably go through the entire pipe in both cases the same way?
