### ISSUE TITLE
Support for Angular CLI ?

### ISSUE THREAD

**Issue by gorlok** [aspnet/JavaScriptServices#957]
With Angular CLI we could use the generate command, to generate components, routes, services and pipes with a simple command. The CLI will also create simple test shells for all of these. That would be great!

**Comment by ADefWebserver** [comment]
This has been discussed here:
https://github.com/aspnet/JavaScriptServices/issues/873
and here:
https://github.com/aspnet/JavaScriptServices/issues/828
Please reefer to the answers provided there.
You can this close this issue.
Thanks!

**Comment by gorlok** [comment]
I will try this https://github.com/aspnet/JavaScriptServices/issues/828#issuecomment-290728688 

I will close this one, but I think that maybe can be added a reference to this in README.md or create .angular-cli.json file by default.

Thanks ADefWebserver for directions!

**Comment by ADefWebserver** [comment]
My hope is that the SpaTemplatePack will be enhanced to provide this functionality. 
https://github.com/madskristensen/SpaTemplatePack
