### ISSUE TITLE
v0.9.3 Angular and Bootstrap issues

### ISSUE THREAD

**Issue by flightlevel** [aspnet/JavaScriptServices#960]
Spent ages on this today trying to figure what I'd broken upgrading from Angular 2 to 4. Hopefully someone will have an idea what I'm missing or it at least helps someone else...

Repro:

Download aspnetcore-spa v0.9.1 (Angular 2.4.5)
Remove all the html content from a file eg. \ClientApp\app\components\counter\counter.component.html
and copy and paste the below from https://www.w3schools.com/bootstrap/bootstrap_modal.asp

```
<!-- Trigger the modal with a button -->
<button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal">Open Modal</button>

<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Modal Header</h4>
      </div>
      <div class="modal-body">
        <p>Some text in the modal.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>
```

Click the button and note a modal dialog appears

Do the same thing on v0.9.3 (Angular 4.1.2) as above
Note now that when clicking on the button the bootstrap modal dialog now doesn't work

Finally I found that adding the below makes it work, but I don't understand why when both Bootstrap and JQuery are both in package.json

Copy this into index.cshtml in your 0.9.3 project 
```
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.js" type="text/javascript"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.js" type="text/javascript"></script>
```
and now it works in Angular 4

**Comment by IAmShipy** [comment]
The bootstrap hamburger menu does not work out of the box.  Adding the jquery/bootstrap scripts as described above also fixes the issue.

**Comment by bm-software** [comment]
I've experienced another problem when trying to call the `collapse` function on `.navbar-collapse` manually from the `navmenu.component.ts`:

    ngAfterViewInit(): void {
        $(".navbar-collapse").on("click", "li:not('.dropdown')", () => {
            $(".navbar-collapse").collapse("hide");
        });
    }

In the console the following error is printed:
    `ERROR TypeError: $(...).collapse is not a function`

Moreover, I'm not able to import jquery with

    var $: JQueryStatic = require("jquery");

I've both jquery (3.2.1) and @types/jquery installed but VS says `Cannot find name 'jQueryStatic'`

How can I solve these?

**Comment by MarkPieszak** [comment]
@bm-software Use ngx-bootstrap (https://github.com/valor-software/ngx-bootstrap) as it's Bootstrap done for Angular, so the directives/components all don't use jQuery or anything.

**Comment by bm-software** [comment]
@MarkPieszak  ngx-bootstrap suggestion is related to `jquery` and `bootstrap` imports in the controller, is that right?

**Comment by MarkPieszak** [comment]
If you use that instead of bootstrap itself, you won't need jquery, and can just do everything the Angular way. Check out the website/repo for more info. You'll be happier in the long run the more you can stay away from jQuery (when combining with these newer front-end frameworks)

**Comment by bm-software** [comment]
@MarkPieszak I'm trying `ngx-bootstrap` with this code:

    <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" (collapsed)="collapsed($event)" (expanded)="expanded($event)">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" > 
                <i class="fa fa-lg fa-home" aria-hidden="true"></i>
            </a>
        </div>
        <div class="navbar-collapse collapse" (collapsed)="collapsed($event)" (expanded)="expanded($event)">
            <ul class="nav navbar-nav">
                <li [routerLinkActive]="['link-active']">
                    <a [routerLink]="['/courses']">
                         Corsi
                    </a>
                </li>
                <li [routerLinkActive]="['link-active']" *ngIf="authService.isAdmin()">
                    <a [routerLink]="['/subscriptions']">
                         Abbonamenti
                    </a>
                </li>
                <li [routerLinkActive]="['link-active']" *ngIf="authService.isAdmin()">
                    <a [routerLink]="['/registry']">
                         Anagrafica
                    </a>
                </li>
                <li [routerLinkActive]="['link-active']" *ngIf="authService.isAdmin()">
                    <a [routerLink]="['/settings']">
                         Impostazioni
                    </a>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a [routerLink]="['/login']">Logout</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

As you can see I've tried to put `collapsed` and `expanded` events on `navbar-collapse collapse` and `navbar-toggle` but in both cases `collapsed` and `expanded` function are not called. Have I to make some more changes?

**Comment by bm-software** [comment]
I'm experiencing a similar issue with bootstrap modals:

`TypeError: this.$modal.modal is not a function`

This time bootstrap and jquery scripts includes are not enough.
The modal won't open with that error.

How to fix?

**Comment by bm-software** [comment]
I found a solution that make all work as expect.
Instead of import `jquery` and `bootstrap` scripts files from `Index.cshtml`, I've imported them from `app.component.ts` (the root component) adding the following lines at the top of the file:

    import 'jquery';
    import 'bootstrap';

With these I'm able to manage both modals and navmenu as I want to.

Hope this helps.

**Comment by ADefWebserver** [comment]
@bm-software - Your solution works. Do you plan to make a pull request? If not I can do it.

**Comment by MarkPieszak** [comment]
> Now the collapse/expand works well but the slideDown/slideUp animation does not.
> Is it a problem due to the CollapseDirective?

You just add the animations through Angular, letting it know the States you want / etc.  It's more manual, but you have full control and you're not depending on dated and extremely large bootstrap & jQuery codebases.

**Comment by bm-software** [comment]
@ADefWebserver I've just created a pull request

**Comment by SteveSandersonMS** [comment]
Glad you got a solution.

**Comment by jsinh** [comment]
I spent 2 hours trying to make following work:

```
<div class="collapse navbar-collapse">
    <ul class="nav navbar-nav navbar-right">
        <li [routerLinkActive]="['active']" class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-user"></span> LoggedIn_User_DisplayName <span class="caret"></span> </a>
            <ul class="dropdown-menu">
                <li><a [routerLink]="['/edit']"><span class="glyphicon glyphicon-star"></span> Edit</a></li>
                <li><a [routerLink]="['/logout']"><span class="glyphicon glyphicon-log-out"></span> LogOut</a></li>
            </ul>
        </li>
    </ul>
</div>
```
Without adding @bm-software suggested following fix:
```
import 'jquery';
import 'bootstrap';
```
to my `app.component.ts` file - evertime I try to click on the dropdown title link it refresh the page thinking i want to do a navigation to `myurl/#`

Anyone using this with templates (asp.net core + Angular) and trying to create a NavBar / Menu dropdown in their app will face this problem. Someone new like me adapting Core and Angular would run into lots of problem.

Assuming putting following imports in app.component is not harmful or graceful way to handle described issue.... it would be great if the authors / contributors put a note of this fix on home readme or add above imports (commented by default) with two lines explaining it (in templates) - would reaaaally help.
CC: @SteveSanderson @ADefWebserver 

Thanks @bm-software again for the note, cheers!

**Comment by sweetgecko** [comment]
i had a lot of problems using javascriptservices for angular.  two things really helped.  
one, as stated before, adding the Import statements for jquery and bootstrap. 
two, disabling server side prerendering by removing the attribute from the from the <app > element.  this helped with the ...error: Prerendering failed...

also, i had to use vs 0.9.3 because 'latest' versions did not include angular template.  maybe that is fixed by now
