### ISSUE TITLE
Guidance on deployment to virtual directory

### ISSUE THREAD

**Issue by MiniverCheevy** [aspnet/JavaScriptServices#961]
It would be nice to have some guidance (or command line options) to bundle the application for deployment to a virtual directory off of the site root.  I've had some luck with the HTML webpack plugin, but am still having some issues getting my webpacked MDI icons to resolve properly.

**Comment by ADefWebserver** [comment]
I have been able to get my application to work in Dev (off the root) and in production (in a virtual directory off the root) by simply opening the file at Views/Shared/_Layout.cshtml and change the base href to the following:

` <base href="~/" />`

See: [Implementing PrimeNG FileUpload in a .Net Core Application](http://lightswitchhelpwebsite.com/Blog/tabid/61/EntryId/4305/Implementing-PrimeNG-FileUpload-in-a-Net-Core-Application.aspx)

**Comment by SteveSandersonMS** [comment]
I've now added @ADefWebserver's dynamic `<base>` element to all the templates in the `dev` branch, so hopefully this gets people closer.

If there are specific bugs that anyone's encountering, could you report them with exact details on what you regard to be the bug? Thanks!
