### ISSUE TITLE
Best way to get data from MVC layer into the Angular layer.

### ISSUE THREAD

**Issue by jrmcdona** [aspnet/JavaScriptServices#964]
I am using AAD and trying to go get values from HttpContext.

Right now I am returning it to _Layout.cshtml and grabbing it from the DOM in Angular.

But this cannot be the right way!

For example:
        public IActionResult Index()
        {
            var viewModel = new AppViewModel()
            {
                IsAuthenticated = HttpContext.User.Identity.IsAuthenticated
            };
            return View(viewModel);
        }

Thanks

**Comment by rosieks** [comment]
Look at this page: https://github.com/aspnet/JavaScriptServices/tree/dev/src/Microsoft.AspNetCore.SpaServices

There is section about that: Passing data from .NET code into JavaScript code

**Comment by SteveSandersonMS** [comment]
Thanks for the answer @rosieks!
