### ISSUE TITLE
How to add generating of map files for css?

### ISSUE THREAD

**Issue by skorunka** [aspnet/JavaScriptServices#965]
How to add generating of map files for css into webpack?
Thank you.

**Comment by ADefWebserver** [comment]
@skorunka This appear to be related only to webpack rather than JavaScriptServices. Can you close this issue and raise on in the Webpack project after consulting their documentation [https://webpack.js.org/configuration/](https://webpack.js.org/configuration/) Thanks!

**Comment by skorunka** [comment]
Anyways, it would be nice to have it as part of this solution.
