### ISSUE TITLE
Pre-render with Vue 

### ISSUE THREAD

**Issue by GusBeare** [aspnet/JavaScriptServices#968]
Hi

Great work on these templates. Fantastic being able to evaluate the frameworks side by side so easily!

The Angular template does server side pre-rendering which is really nice.  However, the Vue,js one does not.  Are there any plans to make the Vue template do this?  It's clearly possible:

http://mgyongyosi.com/2016/Vuejs-server-side-rendering-with-aspnet-core/

**Comment by SteveSandersonMS** [comment]
It would certainly be nice to have that feature! (Assuming it doesn't add significant complexity to the app)

This is a case where we'd rely on community contribution if it would happen. Would you be interested in figuring out the details and submitting a pull request?

**Comment by GusBeare** [comment]
Hi Steve, thanks for responding

I'd love to be of help but at the moment I don't have the knowledge to figure it out quickly. I am using these templates to help me decide which framework to learn. 

I've contacted the author of that post to see if he's interested in getting involved.

**Comment by SteveSandersonMS** [comment]
OK, thanks for the response!

Since there's no direct plan to make this happen in the short term, I'll mark this closed. If anyone wants to come forward with a PR please let us know :)
