### ISSUE TITLE
Unclear server dependencies for server-side rendering

### ISSUE THREAD

**Issue by rgamage** [aspnet/JavaScriptServices#969]
I'm having trouble getting the Angular2 SPA template to run on the web server, and in Azure.  I'd like to know which files are needed to be deployed in order for this to work.  My understanding is that NodeJS is required to be installed on the server, but I'm not clear which source/lib files are needed.

The template, as generated, fails on any web server that I've deployed it on, but it runs fine if I disable server-side rendering, by replacing 

this:
`<app asp-prerender-module="ClientApp/dist/main-server">Loading...</app>`

with this:
`<app>Loading...</app>`

(comment-out the pre-render module).

I was able to get the server rendering to work by copying the ~13,000 files in the node-modules folder to the server.  These are not published by the project as the current template is written (as of mid May 2017).  If these files are needed on the server for the template to run, shouldn't they be included as output files in the .csproj file?  Are they all really needed, or am I over-doing it by copying all 13000 files to the server?

Thanks,
Randy

**Comment by skorunka** [comment]
@rgamage commands `webpack` && `webpack --config webpack.config.vendor.js` (append `--env.prod` for Production build)
1. Client side : webpack generates bundles into `wwwroot/dist` folder
2. Server side: webpack generates bundles into `ClientApp/dist`folder.

You need to include `wwwroot`(whole folder) in your deployment package and `ClientApp/dist` if you want SSR(Server Side Rendering).

This is part of my `.csproj`:

```xml
	<ItemGroup>
		<!-- Files not to publish (note that the 'dist' subfolders are re-added below) -->
		<Content Remove="ClientApp\**" />
	</ItemGroup>

	<Target Name="RunWebpack" AfterTargets="ComputeFilesToPublish">
		<!-- As part of publishing, ensure the JS resources are freshly built in production mode -->
		<Exec Command="npm run lint" />
		<Exec Command="npm run build:prod" />
		<!-- Include the newly-built files in the publish output -->
		<ItemGroup>
			<DistFiles Include="wwwroot\dist\**; ClientApp\dist\**" />
			<ResolvedFileToPublish Include="@(DistFiles->'%(FullPath)')" Exclude="@(ResolvedFileToPublish)">
				<RelativePath>%(DistFiles.Identity)</RelativePath>
				<CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
			</ResolvedFileToPublish>
		</ItemGroup>
	</Target>
```

and part of `package.json`:

	"scripts": {
		"test": "karma start ClientApp/test/karma.conf.js",
		"build:vendor": "node node_modules/webpack/bin/webpack.js --config ./webpack.config.vendor.js --progress",
		"build:dev": "npm run clean && node node_modules/webpack/bin/webpack.js --config ./webpack.config.vendor.js && node node_modules/webpack/bin/webpack.js",
		"build:prod": "npm run clean && node node_modules/webpack/bin/webpack.js --config ./webpack.config.vendor.js --env.prod && node node_modules/webpack/bin/webpack.js --env.prod",
		"clean": "rimraf -- wwwroot/dist -- ClientApp/dist",
		"compodoc": "compodoc -p tsconfig.json -d _docs -n Anticipate --theme Readthedocs",
		"dev:watch": "set ASPNETCORE_ENVIRONMENT=Development && dotnet watch run",
		"lint": "tslint \"ClientApp/**/*.ts\"",
		"test:watch": "npm run test -- --auto-watch --no-single-run"
	},

**Comment by SteveSandersonMS** [comment]
@rgamage: @skorunka's comment looks right to me.

The current templates do not require you to have a `node_modules` directory in production. The production bundles are completely self-contained in `ClientApp/dist` and `wwwroot/dist`.

Older versions of the templates did rely on `node_modules` in production, so perhaps your project is based on one of the older versions of the templates. If you create a new project and can still repro the need to have `node_modules` in production (after publishing via `dotnet publish -c Release`), please let us know!
