### ISSUE TITLE
asp-prerender-module issue with Windows Authentication enabled

### ISSUE THREAD

**Issue by scoon1329** [aspnet/JavaScriptServices#971]
In the Angular template, enabling Windows Authentication causes the /fetch-data route to fail with the error Exception: Call to Node module failed with error: Response with status: 401 Unauthorized for URL: <root>/api/SampleData/WeatherForecasts

Changing "asp-prerender-module" to "asp-ng2-prerender-module" in Views/Home/Index.cshtml line 16 seems to fix the issue.

**Comment by SteveSandersonMS** [comment]
If your API backend requires authentication, and you want to make calls to it during server-side prerendering, then you will need to modify your TypeScript code to supply the relevant authentication credentials during the HTTP request that it makes. We don't attempt to do this automatically - it would be a serious security issue if we passed through credentials without knowing that you really want to do that (maybe you're making calls to third-party APIs - you definitely wouldn't want to pass through your auth tokens in that case).

It is tricky to pass through Windows Authentication credentials in any case. If you don't have a strict business requirement for server-side prerendering and hence can disable it (like you have done by removing the `asp-prerender-module` attribute), that will be far simpler.

**Comment by mjhoffm2** [comment]
Hi, I am running into a similar issue.  I am not sure how to go about obtaining the authentication credentials required in node.  I have found that I am able to modify the fetch when executed on the server to make it work.  I change the url to localhost on port process.env.ASPNETCORE_PORT, and add a MS-ASPNETCORE-TOKEN header in my request set to process.env.ASPNETCORE_TOKEN.

While this works with iisSettings.windowsAuthentication set to true, this fails if I have [Authorize] on my controller, despite the fact that adding the [Authorize] annotation [should have no effect](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/windowsauth?tabs=aspnetcore2x).  I also cannot find much documentation on this header that I have added.  Can you shed any light on this and help point me in the right direction?
