### ISSUE TITLE
Purpose of MapSpaFallbackRoute

### ISSUE THREAD

**Issue by im1dermike** [aspnet/JavaScriptServices#973]
What is the purpose of the following code which is automatically loaded to the `Startup` class with this project:

    routes.MapSpaFallbackRoute(
        name: "spa-fallback",
        defaults: new { controller = "Home", action = "Index" });

This results in a 200 being thrown when a non-existent API endpoint is hit instead of a 404.

**Comment by MarkPieszak** [comment]
It's for when you want to handle the 404 within your front-end application.

**Comment by im1dermike** [comment]
My use case - which I assume is very common - is to want to handle bad angular routes in the front-end, but throw 404s on bad API calls (that is, requests whose URL follows a certain pattern eg. "/api").

Can you give me a recommendation?

**Comment by MarkPieszak** [comment]
You want to use a mapWhen looking for something that starts with `/api`, use this below and you'll be all set:

```c#
           // this part you already have
           app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "default",
                    template: "{controller=Home}/{action=Index}/{id?}");
            });

            // here you can see we make sure it doesn't start with /api, if it does, it'll 404 within .NET if it can't be found
            app.MapWhen(x => !x.Request.Path.Value.StartsWith("/api"), builder =>
            {
                builder.UseMvc(routes =>
                {
                    routes.MapSpaFallbackRoute(
                        name: "spa-fallback",
                        defaults: new { controller = "Home", action = "Index" });
                });
            });
```

Hope that helps!

**Comment by SteveSandersonMS** [comment]
Thanks @MarkPieszak for the answer. If this becomes a common request, we could add a further `excludePrefix` option onto `MapSpaFallbackRoute` so you can set it to `api`.

**Comment by SteveSandersonMS** [comment]
Also:

> It's for when you want to handle the 404 within your front-end application.

That's not the whole story. It's mostly just so that *all* URL that *might* be handled by your front-end application cause the front-end application to be returned. For example, a request for the URL `/counter` (in the default template) should cause the front-end application to be loaded, which will then display a suitable UI. If you didn't have `MapSpaFallbackRoute` then the server would just return a 404 for `/counter` since there's no matching MVC controller.

**Comment by im1dermike** [comment]
@MarkPieszak Perfect.  Your solution works as desired.

Fantastic responsiveness as usual.

**Comment by ADefWebserver** [comment]
> If you didn't have  MapSpaFallbackRoute  then the server would just return a 404 for  /counter  since there's no matching MVC controller.

So umm yeah, this is REALLY an important point that I hope does not get lost :)

Meaning. I can send someone a url like this:

[http://helloworlddata.azurewebsites.net/counter](http://helloworlddata.azurewebsites.net/counter)

..and it works even though there is really no `/counter` page. It exists only as an Angular route :)

**Comment by MarkPieszak** [comment]
> That's not the whole story. It's mostly just so that all URLs that might be handled by your front-end application cause the front-end application to be returned. For example, a request for the URL /counter (in the default template) should cause the front-end application to be loaded, which will then display a suitable UI. If you didn't have MapSpaFallbackRoute then the server would just return a 404 for /counter since there's no matching MVC controller.

Yes apologies I should of mentioned that! @SteveSandersonMS

**Comment by buvinghausen** [comment]
For anyone who wants to use ASP.NET Razor Pages that came out with .NET Core 2.0 I never could get map fallback route to work so I pivoted and went a different direction.

```csharp
		public void ConfigureServices(IServiceCollection services) =>
			services
				.AddMvc()
				.AddRazorPagesOptions(options =>
				{
					options.Conventions.AddPageRoute("/Index", "{*url:regex(^(?!api).*$)}");
				});
````

**Comment by pholly** [comment]
@buvinghausen That works well. Just be aware that every request that doesn't match a static file will get routed to your SPA - even requests with file extensions. `MapSpaFallbackRoute` does not match requests that look like filenames - that is, have an extension at the end.

**Comment by ripasfilqadar** [comment]
```
 app.UseMvc(routes =>
                {
                    routes.MapSpaFallbackRoute(
                    name: "spa-fallback-admin",
                    defaults: new { area="Admin", controller = "Home", action = "Index" });
                });
```
is this the correct way to using controller from some areas?
