### ISSUE TITLE
Angular HMR Webpack - No Updates

### ISSUE THREAD

**Issue by adammcgrade** [aspnet/JavaScriptServices#976]
For some reason I am unable to get the Webpack HMR working. I have ensured that I am running in development mode, (added ASPNETCORE_ENVIRONMENT=Development to System Environment Variables) however when ever I make a change to any component files, I am unable see any updates on the page in the browser.

**Development Environment**:

- OS: Windows 10 Pro x64 1607
- Browser: Google Chrome Version 58.0.3029.110 (64-bit)
- Node v7.10.0
- Visual Studio 2017

**Repro:**

- Run npm install -g yo generator-aspnetcore-spa (version 0.9.3)
- Create a new Angular project via yeoman generator
- Change to project directory and run dotnet run from command prompt
- Alternatively run via CTRL+F5 in Visual Studio

**Output:**

`Hosting environment: Development`
`Content root path: Y:\VS Projects\Vega`
`Now listening on: http://localhost:5000`
`Application started. Press Ctrl+C to shut down.
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:5000/home`
`info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Executing action method Vega.Controllers.HomeController.Index (Vega) with arguments ((null)) - ModelState is Valid`
`info: Microsoft.AspNetCore.NodeServices[0]
      webpack built c08511a8944571c5f834 in 5549ms`
`info: Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ViewResultExecutor[1]
      Executing ViewResult, running view at path /Views/Home/Index.cshtml.`
`info: Microsoft.Extensions.DependencyInjection.DataProtectionServices[0]
      User profile is available. Using 'C:\Users\adamm\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.`
`info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
      Executed action Vega.Controllers.HomeController.Index (Vega) in 3689.6395ms`
`info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 3985.3474ms 200 text/html; charset=utf-8`
`info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:5000/dist/vendor.js?v=8G5nuphpleAMB8hDVj0v8l9es64guglhqGWIwYdey3M  `
`info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:5000/dist/vendor.css?v=2OSKmU2Rna58MvkZa-1vCDjb7C1cgTMqz-guh-WoUGU `
`info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:5000/dist/main-client.js?v=loc3aC0rXik9WIwmLnk5d7LxtlCuyavV8GbswxiG25k`
`info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[6]
      The file /dist/vendor.js was not modified`
`info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[6]
      The file /dist/vendor.css was not modified`
`info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 554.9176ms 304 text/css`
`info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 556.3261ms 304 application/javascript`
`info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 760.3112ms 200 application/javascript; charset=UTF-8`
`info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:5000/__webpack_hmr`
`info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:5000/favicon.ico`
`info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/favicon.ico'. Physical path: 'Y:\VS Projects\Vega\wwwroot\favicon.ico'`
`info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 9.9921ms 200 image/x-icon`
`info: Microsoft.AspNetCore.NodeServices[0]
      Node will restart because file changed: Y:\VS Projects\Vega\ClientApp\app\components\home\home.component.html`
`info: Microsoft.AspNetCore.NodeServices[0]
      webpack building...`
`info: Microsoft.AspNetCore.NodeServices[0]
      webpack built 869d44392ab3037ea1ab in 280ms`
`info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:5000/__webpack_hmr`

**Comment by SteveSandersonMS** [comment]
I've been trying to repro this, but so far, no luck. I've got the latest versions of everything, but it works fine when I do the same.

So I don't know (based on the information here) why that's not working as expected. The only unexpected thing in your log is that, after you modified the `.html` file, the browser seems to make a second request for `/__webpack_hmr` instead of fetching a file like `/dist/(guid).hot-update.json`. As for why it's doing that, I'm not sure - there might be something odd about your browser such as an extension interfering with it. Or possibly your `npm` cache might be stuck on older versions of packages, so you might not be running up-to-date code.

Are you able to reproduce this problem on a different machine? Or do you know of anything specific to your machine that might explain why it behaves differently?

**Comment by adammcgrade** [comment]
Based on your feedback I did some troubleshooting and it looks like is the real time protection feature of  Bitdefender Antivirus on my PC, that is preventing this from working. I disabled the real time protection and I am now seeing the hot reload on changes and the logs appearing in the browser console. Thanks very much for your help!

**Comment by SteveSandersonMS** [comment]
Thanks for letting us know!
