### ISSUE TITLE
Unable to resolve 'Microsoft.NETCore.App (>= 2.0.0)' for '.NETCoreApp,Version=v2.0'

### ISSUE THREAD

**Issue by beatsm** [aspnet/JavaScriptServices#977]
Hi

I have just tried to build from the Dev branch and get this curious error. 

Any advice on how I can resolve this so that I can build the solution?

Regards

**Comment by SteveSandersonMS** [comment]
Until the 2.0.0 packages are released on the public NuGet feed, you would need to copy [this NuGet.config](https://github.com/aspnet/JavaScriptServices/blob/dev/NuGet.config) file to your project if you want to use them.

Note that if you do this, you're running directly against bleeding-edge dev builds, with no stability guarantees :)

**Comment by Serjster** [comment]
So this is closed, however, I am still getting this error with the VSTS Restore task for tiny project whose .csproj looks like this:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>

</Project>
```

Any clue why this is happening?

**Comment by jonathanfishbein1** [comment]
@Serjster did you figure this out.  I'm currently experiencing the same error on VSTS
