### ISSUE TITLE
using NodeServices in non-Core ASP.Net?

### ISSUE THREAD

**Issue by Barlind** [aspnet/JavaScriptServices#978]
We can't make the switch to Core yet but would like to use NodeServices with ASP.Net MVC on 4.7 - is this possible or does it require Core?

**Comment by SteveSandersonMS** [comment]
The core packages (NodeServices, SpaServices) currently target `net451` and `netstandard1.6` (soon to be changed to `netstandard2.0`). This means you can use them with .NET full framework as a way of invoking Node from .NET, or in an ASP.NET Core project that runs on .NET full framework.

>does it require Core

That depends whether you mean ".NET Core" or "ASP.NET Core". The project templates here are ASP.NET Core templates, which can run on the .NET Core runtime or the .NET Framework runtime.

**Comment by justrhysism** [comment]
So, "yes"?

**Comment by justrhysism** [comment]
Requires .NET Standard, but not dotnet Core. I have successfully tested executing NodeServices in .NET Framework (after the Dependency Injection dance).

**Comment by Amadeus82** [comment]
Hi Rhys
Thank you very much for the quick answer. Can you elaborate the "DI dance"? :-) Do you have a sample working in an Asp .NET MVC Project?
