### ISSUE TITLE
AureliaSpa template not handling loading of font files

### ISSUE THREAD

**Issue by mtimms** [aspnet/JavaScriptServices#979]
I'm getting loading errors ["Module parse failed"] for various font files using the AureliaSpa template.  The particular case came from adding Kendo UI support which includes font files such as .eot and .woff files.

Adding an additional entry to the rules section in the webpack.config file fixed the problem.

` { test: /\.(eot|woff|woff2|ttf)(\?\S*)?$/, use: 'url-loader?limit=100000' }`

**Comment by cvanslimming** [comment]
How is this an error in the template, you added kendo UI so you should take care of the webpack additions, same when adding font awesome or whatever new extension. This template should not be poluted with extras that not everybody uses.

**Comment by mtimms** [comment]
I'd think this a quite common occupance, not just specific to Kendo UI.  Since these templates are suppose to get you up and running smoothly better not to impede the first experience by having to root around for an hour or more trying to determine why it doesn't work.

**Comment by SteveSandersonMS** [comment]
Sorry for the inconvenience @mtimms. However there's no way we could anticipate all possible requirements that everyone will have (nor would anyone be able to understand an uber-config that covered all possible things), and Webpack is itself a system for letting people customise their build process to bring in whatever support is needed. So I'm afraid you will have to get familiar with Webpack if you want to customise your build setup. Hope that's OK!
