### ISSUE TITLE
Deploying MusicStore to Azure

### ISSUE THREAD

**Issue by hisomu** [aspnet/JavaScriptServices#98]
I attempted to deploy the Angular2 solution, Music Store, to Azure to see if JavaScriptServices would work without having to install node.js

When loading the site it displayed the following:
The specified CGI application encountered an error and the server terminated the process.

I looked further and checked out the error logs and found the following:
Event Id: 1000
Source: IIS AspNetCore Module
Details: Process '0' failed to start. Port = 16155, Error Code = '-2147024894'.

**Comment by laskoviymishka** [comment]
Well it not. 

Right now JS Services still require node.js intalled on your server. Somewhere inside of this library aspnet just create child nodejs process and interact with it. Scenario when you will be able to run JS without nodejs installed still blocking till #5 will be resolved (it blocked also see _https://github.com/tjanczuk/edge/issues/279_)

**Comment by SteveSandersonMS** [comment]
If you deploy to an Azure web site, Node is available and should work correctly with `NodeServices` etc (I have verified this).

If you deploy to a custom VM on Azure, then it would be up to you to install Node.

Closing as it doesn't sound like there's a bug, but please let me know if you think there is.

**Comment by hisomu** [comment]
I grabbed the latest from Master and I am still getting the same error, as above "The specified CGI application encountered an error and the server terminated the process.".

**Here are the steps to reproduce:**
- In Visual Studio 2015, update project.json and add _include_ in publishOptions:
```
"publishOptions": {
    "include": [
      "wwwroot",
      "Views",
      "appsettings.json",
      "web.config"
    ],
  },
```
- Right click on Music Store project and select 'Publish..'
- Click 'Microsoft Azure App Service'
- Select a site to deploy to then click OK
- In settings verify that the configuration is 'Release' and Target Framework is '.NETCoreApp,Version=v1.0'
- Click Publish
- Once the app has published successfully, open the website and confirm
