### ISSUE TITLE
Pre render send cookies

### ISSUE THREAD

**Issue by jeinz11** [aspnet/JavaScriptServices#984]
Hi just wondering if there is a way to send the cookie 
during SSR. i notice that in the first run all cookies and identities are empty

is there a way to specify the cookie in this method

            var prerenderResult = await Prerenderer.RenderToString(
                "/",
                nodeServices,
                new JavaScriptModuleExport(applicationBasePath + "/ClientApp/dist/boot-server"),
                unencodedAbsoluteUrl,
                unencodedPathAndQuery,
                transferData,
                30000
            );

**Comment by jeinz11** [comment]
@SteveSandersonMS , @laskoviymishka  please help i just want to send my cookie browser during SSR thanks for helping

**Comment by Maarten88** [comment]
I think you can unpack the cookie data and pass it in transferData. It arrives in boot-server in params.data

**Comment by SteveSandersonMS** [comment]
Yes, @Maarten88 is correct. The docs at https://github.com/aspnet/JavaScriptServices/tree/dev/src/Microsoft.AspNetCore.SpaServices under *Passing data from .NET code into JavaScript code* give a specific example of passing cookies to the `boot-server.ts` file. From there, it's up to you to pass it to the rest of your app in whatever way you want, using the APIs provided by your chosen SPA framework, and from there you can include it in your `fetch` requests if you want.
