### ISSUE TITLE
Cannot find module './wwwroot/dist/vendor-manifest.json' in ReactReduxSpa project

### ISSUE THREAD

**Issue by tutok** [aspnet/JavaScriptServices#99]
It seems that there is no `vendor-manifest.json` file in repo?
When I try to run ReactReduxSpa project I am getting following error:

`System.Exception
Call to Node module failed with error: Error: Cannot find module './wwwroot/dist/vendor-manifest.json'
at Function.Module._resolveFilename (module.js:326:15)
at Function.Module._load (module.js:277:25)
at Module.require (module.js:354:17)
at require (internal/module.js:12:17)
at Object.<anonymous> (C:\Users\[user-name]\Downloads\JavaScriptServices-master\JavaScriptServices-master\templates\ReactReduxSpa\webpack.config.js:33:23)
at Module._compile (module.js:410:26)
at Object.Module._extensions..js (module.js:417:10)
at Module.load (module.js:344:32)
at Function.Module._load (module.js:301:12)
at Module.require (module.js:354:17)
at require (internal/module.js:12:17)`

**Comment by laskoviymishka** [comment]
Execute `webpack --config webpack.config.vendor.js` before run application.
This issue addressed to new CLI behaivor. By some reason after `dotnet restore` it not run second command from `prepare` section of `project.json` by default.

**Comment by tutok** [comment]
Fixed, thanks @laskoviymishka!

**Comment by laslo67** [comment]
This fixed it for me too. thanks @laskoviymishka.

**Comment by KGrewe** [comment]
Could someone please explain me where to run the command?
nbm console?
or CMD?

**Comment by miniGweek** [comment]
@laskoviymishka  , worked like a charm! Thanks!

**Comment by 7100SW** [comment]
Yes.  Running with webpack.config.vendor.js fixed it.

**Comment by davidgristwood** [comment]
nice one - thanks!

**Comment by dotnetleader** [comment]
I am getting below error after running above command
EPERM: operation not permitted, open dist\vendor-manifest.json 

i am struggling to resolve this from last 4 days.. any help will be appreciated

**Comment by nivle** [comment]
(I use visual studio 2017)
What I do is, I open dependencies and rightclick the npm and restore packages to make sure they are all
restored, after a while once that's done, I run the project, it'll most likely fail, then I make it clean(by rightclick project and click clean) and repeat that till sucessfull and no errors, and then I build the project(by rightclick project and click build), after that's succesfull, then I run the project, (first time still can give some issues) so I stop it after it's loaded and run it again and then it mostly works like it should.

**Comment by 2225025616** [comment]
I came across  a problem like this — the file saved something built by gulp and webpack, and then i tried some ways but it's no working.
By the help of my colleagues, i tried install uglifyes-webpack-plugin and the paoblem is solved.

**Comment by ingale88s** [comment]
> (I use Visual Studio 2017, for ASP.NET Core Web App = ASP.NET Core 2.0 + Angular project)
> What I do after I create a new project are the next steps:
> I open dependencies and rightclick the npm and restore packages to make sure they are all
> restored, after a while once that's done, I run the project, it'll most likely fail, then I make it clean(by rightclick project and click clean) and repeat that until it's sucessfully cleaned and there are no errors, then I build the project(by rightclick project and click build), after that's succesfull I run the project, (first run sometimes still gives some issues) so I stop it after it's loaded and run it again and then it mostly works like it should.

This worked for in Visual Studio 2017.
