### ISSUE TITLE
Microsoft.AspNetCore.SpaTemplates on dotnet core preview 2

### ISSUE THREAD

**Issue by lohithgn** [aspnet/JavaScriptServices#990]
I am on a Win 10 64 bit OS. 

I have installed .net core 2.0 preview. 

When i do 

> dotnet --info

here is what i have:

![dotnetinfo](https://cloud.githubusercontent.com/assets/2450336/26568262/99160346-451f-11e7-8986-bc7cdf6e588d.png)

I am following this article by Steve [here]
(https://blogs.msdn.microsoft.com/webdev/2017/02/14/building-single-page-applications-on-asp-net-core-with-javascriptservices/).

I tried the command:

> dotnet new --install Microsoft.AspNetCore.SpaTemplates::*

Nothing happens on the command prompt. I see the templates that have been installed by dotnet 2.0 preview bits. 

![dotnetnewinstall](https://cloud.githubusercontent.com/assets/2450336/26568335/1f4b6438-4520-11e7-9182-2be44dd6e491.png)

Not sure what is happening. All i wanted was to use spa templates to create new angular app. Any body facing similar issue ?

**Comment by rsantosdev** [comment]
@lohithgn the command `dotnet new --install Microsoft.AspNetCore.SpaTemplates::*` is used to install the template on your machine. After that you need to navigate to any folder you wanna generate the project and run the following command:

`dotnet new angular`

**Comment by xusdom** [comment]
Hi all,
same issue here. Same dnc version. After doing
> dotnet new --install Microsoft.AspNetCore.SpaTemplates::*
nothing happens. After creating 
> yo aspnetcore-spa
with yeoman I opened resulting *csproj in Visual Studio. nuGet told me:
> "Microsoft.AspNetCore.SpaServices (>= 1.1.1)" kann für ".NETCoreApp,Version=v2.0" nicht aufgelöst werden.
("can not resolve Microsoft.AspNetCore.SpaServices dependencies..".)
I downgraded project to dnc v1.1 with the same result. now trying to build from source.

Greetz, and btw (never thought saying that :-)) Keep up the GOOD work...

**Comment by xusdom** [comment]
Hi,
i'm not tried building from source yesterday (was late at night in ger). Now at work on a Win7 x64 with dnc 1.0.4 everything is working as expected.

**Comment by xusdom** [comment]
Hi,
i checked my **global nuGet.config.** https://api.nuget.org/v3/index.json and https://api.nuget.org/v2/ were diabled. **I enabled both** and now everything is fine. Maybe this will help someone.

Cheers

**Comment by SteveSandersonMS** [comment]
@xusdom Glad you got this sorted!

@lohithgn The packages on NuGet don't currently support .NET Core 2.0. We will ship 2.0 preview packages soon (not sure exactly, but most likely within weeks I'd expect).

**Comment by tburnett80** [comment]
I am having the same issue
![capture](https://user-images.githubusercontent.com/4324080/29477879-f4109564-842f-11e7-92df-f93ce0502e44.PNG)


Then when I run 
dotnet new --install Microsoft.AspNetCore.SpaTemplates::*

This is what I get
![capture1](https://user-images.githubusercontent.com/4324080/29477927-1594776e-8430-11e7-9e25-cdc8778dbc48.PNG)


As you can see, angular is missing.

**Comment by cezanne108** [comment]
I have the same issue as tburnett80. All of my info is the same except my Windows OS version is 10.0.14393

**Comment by vdavi** [comment]
I am having the same issue. angular is missing from the templates
