### ISSUE TITLE
How to disable server side pre-rendering?

### ISSUE THREAD

**Issue by anunaykumar** [aspnet/JavaScriptServices#992]
I am using react redux webapp template. 

Another web application is doing a server side redirect to my JavaScriptServices webapp with some query parameters. I don't want these parameter to show up on the client side. I was thinking of disabling server side prerendering so that I could process the passed in parameters and rewrite the URL.

Whats the best way to achieve this?

Thanks

**Comment by rpampin** [comment]
Inside Index.cshtml you should change the following line:
`<app asp-prerender-module="ClientApp/dist/main-server">Loading...</app>`
for
`<app>Loading...</app>`

**Comment by rpampin** [comment]
Remove this from Index.cshtml
`asp-prerender-module="ClientApp/dist/main-server"`

**Comment by anunaykumar** [comment]
In addition to asp-prerender-module, I also removed following from _ViewImports.cshtml
@addTagHelper "*, Microsoft.AspNetCore.SpaServices"
