### ISSUE TITLE
LaunchWithDebugging broken in Microsoft.AspNetCore.SpaServices version 1.1.1?

### ISSUE THREAD

**Issue by Maarten88** [aspnet/JavaScriptServices#995]
I am trying to debug server side prerendering, so I added:

    services.AddNodeServices(options => {
        options.LaunchWithDebugging = true;
        options.DebuggingPort = 9229;
    });

This resulted in an immediate error on the first request going to node:

    System.InvalidOperationException: An attempt was made to transition a task to a final state when it had already completed.
       at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
       at Microsoft.AspNetCore.NodeServices.HostingModels.OutOfProcessNodeInstance.<>c__DisplayClass24_0.<ConnectToInputOutputStreams>b__0(Object sender, DataReceivedEventArgs evt)
       at System.Diagnostics.Process.OutputReadNotifyUser(String data)

This did work before for me. Indeed, downgrading Microsoft.AspNetCore.SpaServices to version 1.1.0 solved the problem, but I'd prefer using the chrome inspector that the 1.1.1 version supports.

I verified this error on a newly generated react-redux aspnetcore-spa solution: just adding options.LaunchWithDebugging = true reproduces the error on my machine.

My node version is 6.10.3

Edit: found #974, maybe that is my problem?

**Comment by SteveSandersonMS** [comment]
Yes, #974 is the fix. As a temporary workaround you could use an older version of Node until we ship updated packages. Sorry for the inconvenience!
