### ISSUE TITLE
How to get older template versions?

### ISSUE THREAD

**Issue by rgamage** [aspnet/JavaScriptServices#996]
We have been using this template for a few projects, but as of today the latest version of the template (0.9.3) is a little too 'bleeding edge' for us, with Angular4, etc.  I see there is also code added to reference the Core 2.0 preview runtimes.

If I don't want these latest features, how can I reference version 0.9.1 or 0.9.2?  I've tried some things at the command line, like:
`npm install -g generator-aspnet-core@0.9.1`

but it doesn't seem to work.   I get an error message about a null path.  Also it's not clear to me how to specify / detect which version of the template we are getting when using dotnet new to generate the template.  Using yeoman generator, it tells you the version of the generator.  There is also an option to update your generator to the latest version, but I could not find out how to downgrade my template version.  Using dotnet new I have no idea how to upgrade, read, or set which version of the template to use.

So at the moment I can only generate the latest version.  Any method to downgrade would be much appreciated.  Also I couldn't find any kind of release notes showing the differences between template 0.9.1 and 0.9.2, for example.  That would be extremely helpful.  Also would be nice if there was some property somewhere in the template that specifies which version was used to generate that project, so you can find out months later.  We've got many of these lying around that were made at different times with who knows which version of the template, it's getting confusing keeping up.

Thanks for all the great work, really appreciate all the effort here!
Randy

**Comment by SteveSandersonMS** [comment]
The package name is `generator-aspnetcore-spa`, not `generator-aspnet-core`. Besides that, what you have will work.

**Comment by SteveSandersonMS** [comment]
> We've got many of these lying around that were made at different times with who knows which version of the template, it's getting confusing keeping up.

That's an interesting possibility, though I suspect it's quite an edge case, since very few people are creating lots of different projects with different versions of the template. Our other templates don't embed version numbers in their outputs either, so it would be strange if the SPA ones did. However if this becomes a common feature request we could certainly reconsider. Hope that's OK!
