### ISSUE TITLE
phantomjs unit testing

### ISSUE THREAD

**Issue by petrce** [aspnet/JavaScriptServices#998]
hey guys did anyone managed to make phantomJs testing working?

I added karma-phantomjs
`npm i karma-phantomjs-launcher --save-dev`
and set browser to PhantomJS in karma.conf:
`browsers: ['PhantomJS'],`
I always get this error:
```
PhantomJS 2.1.1 (Windows 7 0.0.0) ERROR
  SyntaxError: Unexpected token '>'
  at boot-tests.ts:22607
```
I guess it is because PhantomJS requires es5 ONLY. Chrome works fine.
I am including some ES2015 .js files directly in my typescript code... do I need to recompile them somehow to es5? tsconfig.json is already set to `"target": "es5",`

**Comment by SteveSandersonMS** [comment]
Hope you got this figured out, but if not, could you please raise with the PhantomJS community? It sounds like you need some tips on configuring that, and people on this repo are not the best to advise on that.
